### ISSUE TITLE
1.7.6: tinker's construct pickaxes with luck 3 does not affect nether ores

### ISSUE THREAD

**Issue by phantomholo** [PrinceOfAmber/Cyclic#100]
So I was all excited about overworld ores spawning in the nether and I already had my tinker's construct pick with a max fortune upgrade on it but it seems to not work on cyclic ores in the nether only, I haven't tested it out in the end, but I hope that this issue can be fixed.  Thanks in advance.

**Comment by PrinceOfAmber** [comment]
I though luck did fishing? Anyway thats weird, it works with the fortune vanilla enchant. ill test it out.

**Comment by phantomholo** [comment]
No as in the luck 3 in tinkers' construct, which gives a fortune 3 to the pickaxes

**Comment by PrinceOfAmber** [comment]
Ok. so i downloaded the very newest Tinkers construct, and i grabbed cyclic 1.7.6.  I made an Obsidian pickaxe (durite).

Then i kept adding lapis to it using the Tool station until it had Luck III.  It also said fortune III down below on the tool

Now when i mine Nether diamond or emerald ore, it sometimes drops more then one.

For me it seems like its working fine. As long as you have enough lapis on it for it to say the word 'fortune' and not just luck it should work.

**Comment by phantomholo** [comment]
Hmm ok guess I'll try it again, thanks again for your help!

**Comment by PrinceOfAmber** [comment]
Thanks for reporting the issue regardless.  

Let me know if it still seems broken, there are sometimes other things happening like a third conflicting mod.
