### ISSUE TITLE
Dehydrator using power, no power is being stored in block, none of the recipes are working.

### ISSUE THREAD

**Issue by Demlou6** [PrinceOfAmber/Cyclic#1001]
Minecraft version & Mod Version: 

**1.12.2 & 1.17.7**

Single player or Server:

**Single Player**

Describe problem (what you were doing / what happened):

**Dehydrator works, but some funky glitching is going on.**

Here is a small GiF with a to show what's going on:

https://gyazo.com/850ed3118b3767807cf35eba626f67a8

Things that aren't working:

- Power doesn't show up
- The progress bar gets extremely wonky; gets longer than the bar should go, corrects, doesn't move with items in it that should work
- The items aren't actually drying out

Thanks!

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
