### ISSUE TITLE
[Crash] Putting items in autocrafter.

### ISSUE THREAD

**Issue by Demlou6** [PrinceOfAmber/Cyclic#1002]
Minecraft version & Mod Version:

**1.12.2 & 1.17.7**

Single player or Server:

**Single Player**

Describe problem (what you were doing / what happened):

Game crashed when trying to put diamond acorns in the auto-crafter

Crash log (if any):

[crash-2018-11-24_07.30.48-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/2612277/crash-2018-11-24_07.30.48-server.txt)

**Comment by PrinceOfAmber** [comment]
Note to self, key line from log

java.lang.RuntimeException: Caught exception while querying recipe 
	at com.lothrazar.cyclicmagic.block.crafter.TileEntityCrafter.findRecipe(TileEntityCrafter.java:193)

**Comment by josephcsible** [comment]
This bug isn't actually in Cyclic's crafter. The real issue is that some mod adds an ingredient and is changing the IntList that `getValidItemStacksPacked` returns after it returns it.

**Comment by josephcsible** [comment]
@Demlou6 What mod are "diamond acorns" from?

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
