### ISSUE TITLE
Sack of Storage

### ISSUE THREAD

**Issue by HeroicConcept** [PrinceOfAmber/Cyclic#101]
So just found out that if you open the sack and then put the same sack in the sack it crashes everything and then upon relaunching the game eats the sack and everything in it.

**Comment by PrinceOfAmber** [comment]
Sorry about this i will fix it right away.

Thanks for reporting it too.

**Comment by PrinceOfAmber** [comment]
How did you get the sack inside?  i tried to pick it up or shift click and it wont let me put it in

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.8 
https://minecraft.curseforge.com/projects/cyclic/files/2332809
