### ISSUE TITLE
[1.10.2] [Bug] Right Click Crop Harvest returns Null for Magic Beans

### ISSUE THREAD

**Issue by SnowShock35** [PrinceOfAmber/Cyclic#102]
Hello,

A quick bug to report regarding Cyclic for Minecraft 1.10.2, here are the details of the issue. . . 

### Important Information

* Minecraft 1.10.2 
* Minecraft Forge 12.18.1.2094
* Cyclic 1.10.2-1.7.7

### Issue Description

When right-clicking on magic beans to harvest them it returns no items (null). This is a problem when this feature is available like it is from EnderCore and other mods that add this ability.

**Comment by PrinceOfAmber** [comment]
Ok I can look into this. It has a preset random list of stuff that it randomly pulls from when harvested, but i might have to line things up differently for mod compatibility

**Comment by PrinceOfAmber** [comment]
Is this the gentle harvest mod you mean? https://minecraft.curseforge.com/projects/gentle-harvest

When I use my garden scythe or my harvester to auto harvest these it works fine, so im just trying to narrow down where its happening.

**Comment by PrinceOfAmber** [comment]
Actually with that gentle-harvest i linked above, i tried it out with Cyclic 1.7.7 and it worked fine.  I got a random crop and it replanted the seed.  So theres no bug related to that mod.

If EnderCore adds some sort of right click harvest feature similar to gentle-harvest, i guess it might be a bug there?  Either way i made a few changes (commit referenced above) to methods i thought were never used, so it might help...
