### ISSUE TITLE
[1.10.2] [Bug] Typo in config

### ISSUE THREAD

**Issue by SnowShock35** [PrinceOfAmber/Cyclic#103]
Hello, 

I believe I have found a bug with Cyclic for Minecraft 1.10.2, here are the details. . . 

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.1.2094
* Cyclic 1.10.2-1.7.7

### Issue Description 

Two of the config options appear to have the same comment but have different boolean values. (Better shown in the screenshot) - Note: This was a brand new config.

### Issue Media 

![Issue Screenshot #1](http://ss.snowshock35.com/2016/09/1475016653-7ea488de.png)

**Comment by PrinceOfAmber** [comment]
Yes that is clearly the wrong description :)

Thanks for reporting this

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.8 
https://minecraft.curseforge.com/projects/cyclic/files/2332809
