### ISSUE TITLE
[1.10.2] [Bug] Compatibility Issue with Pam's HarvestCraft (Causes issue with Magic Beans)

### ISSUE THREAD

**Issue by SnowShock35** [PrinceOfAmber/Cyclic#106]
Hello,

A quick bug to report regarding Cyclic for Minecraft 1.10.2, here are the details of the issue. . . 

### Important Information

* Minecraft 1.10.2 
* Minecraft Forge 12.18.1.2094
* Cyclic 1.10.2-1.7.8
* Other Mods:
    * Pam's HarvestCraft 1.9.4-1.10.2e

### Issue Description

So this is a continuation of my original issue from yesterday (#102). It appears that the issue lies with [Pam's HarvestCraft](https://github.com/MatrexsVigil/HarvestCraft) and Cyclic. 

HarvestCraft, like EnderCore which I originally sought as the problem also adds right click harvest for it's own crops however, this however also works with other crops (I believe it uses IPlantable to determine this) and because your crop doesn't return a _normal_ output (Or a seed of itself) I think it's causing this problem of not returning anything on right-click. I'm not sure if this is something you'd want to discuss with @MatrexsVigil to try and solve the issue or whether you try fix it yourself. But the problem definitely lies in compatibility between these two mods and I would hate to have to turn off the right-click harvest just to fix one crop's issue.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting, ill check this out

**Comment by SnowShock35** [comment]
Thanks @PrinceOfAmber! I appreciate all the help you've given with all the issues :-)

**Comment by PrinceOfAmber** [comment]
Yeah, the crop that comes out is determined at runtime, its not preset. Ill have to check harvestcraft source code i guess.

To be honest, it might not be fixable on my end...  as noted in #102 , right click gentle harvest works great when added by some mods such as the 'gentle harvest' one i linked in that thread.  The crop also works when auto harvested by other means such as harvester and garden scythe from this mod, or machines from other mods.   For now ill have to come back to this after other issues are resolved

 So at least as a stopgap until this is resolved, you could install that the mod noted above.

**Comment by PrinceOfAmber** [comment]
Confirmed this bug still happens in latest cyclic build (1.7.14) with pams harvestcraft.  However with other right click to harvest mods such as https://minecraft.curseforge.com/projects/gentle-harvest the harvested item from my Magic Bean pops out fine.  

So at this point i have to assume the bug is with pams.  

(technical detail L there are only two functions where i can return the 'crop item to give out when harvested' and i satisfy them both. )

**Comment by PrinceOfAmber** [comment]
Note if you have both gentle-harvest and Harvestcraft installed, make sure to go into harvestcraft.cfg and set

enableEasyHarvest=false

so it wont use both

**Comment by PrinceOfAmber** [comment]
Update: using the above linked "Gentle Harvest" mod does not harvest ANY of the pams crops, but it does work on vanilla and magic bean. so there may still be a fix

**Comment by PrinceOfAmber** [comment]
Fixed in latest release https://minecraft.curseforge.com/projects/cyclic/files/2336512

**Comment by vikassssxd** [comment]
i have a problem with pam's harvestcraft 1.10.2, the purple/black blocks appear on trees as crops, and so i cant see what plant is that, plz help
