### ISSUE TITLE
Server Crash with Block Placer v1.7.6+

### ISSUE THREAD

**Issue by psychofad** [PrinceOfAmber/Cyclic#108]
I have several block placers on my server from your mod.  After updating from v1.7.5 to v1.7.6 or above the server will crash with the following error:

http://pastebin.com/cL6m49rH

Reverting to v1.7.5 allows the server to load without crashing.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this.  Yeah, i should have made 1.7.6 into a major version such as 1.8, since so much was added or changed in it.

Ill get a new build out asap

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.9, let me know if it happens again / comes back

https://minecraft.curseforge.com/projects/cyclic/files/2333015
