### ISSUE TITLE
Bag of holding bug w/ Iron Chest Mod

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#109]
Picking up the copper chest using a bag of holding will place an iron chest down instead of copper.
Forge 2092

**Comment by PrinceOfAmber** [comment]
Weird, ill look into this.  It should copy the block id and all nbt data, i might have to dig into ironchests sourcecode :)

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by PrinceOfAmber** [comment]
Also What version of Cyclic did you see this in? Sack of holding changed / got an upgrade in 1.7.6 so it might matter what version you saw this in https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.7.6

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.9, let me know if it happens again / comes back

https://minecraft.curseforge.com/projects/cyclic/files/2333015
