### ISSUE TITLE
How to spoilers? (Uncrafting and modded items)

### ISSUE THREAD

**Issue by Iteries** [PrinceOfAmber/Cyclic#116]
I checked and rechecked but seemingly the uncrafter is not working properly in v1.10.2  
Even tested with a vanilla iron pickaxe and will not uncraft and all the recipes are working.  I do have the table enabled too, as its apart of checking.  I seriously would like it working for all the emerald armor & stuff to break down.  There really a need to have more than just pictures for all the mods but a few "how to's" for situations like this.  Thank you, as I do like a few of your mods.

Currently using mods (see list) and all working together just fine with only a few hiccups and this is one of them.
FORGE: 12.18.1.2076
MODs:
BOP
Gender
Cyclic - heh
Pam's Harvestcraft
BetterFoliage
Quark
Armorplus
Weaponplus
Ruins
ISM
RoguelikeDungeons
InfernalMobs
journeymap
Soundfilters
MultiMine
Findercompass
DragonMount
MCA
TheCampingMod
RESOURCEs:
Sphax_Harvestcraft_1.9.4-1.10
Sphax64x_BOP_Ver5.0.0.2080
PureBDcraft 64x MC110

**Comment by PrinceOfAmber** [comment]
Ill test it out.  There are a few restrictions:

1.  For things like tools and armor, they have to be fully repaired.   So a fully repaired iron pickaxe will uncraft, but if it has taken damage, it wont work.

2. Also, the input and output stack size must match.  So, if you put in a single wooden plank, it cant reverse that becuase one log makes 4 planks. This means you need 4 planks at once in the machine to get 1 log.

3.  if the item is crafted something not a 3x3 or 2x2, it wont work.  (such as brewing stands, or custom modded recipes such as 4x4 or something)

Please let me know which items are not working in the uncrafter, and what mods they are from and i can take a look.

**Comment by PrinceOfAmber** [comment]
I may revisit this just to add some sort of ?get info? or help button, but for now i assume the tips above have helped. Also i added those items to the curse page so it should help inform other players.

**Comment by Iteries** [comment]
yeah, it was interesting that worked with redstone power.  The spoilers didn't even mention you need one here on curseforge or otherwise. I had the feeling in the older versions of uncrafter that one you didn't need redstone and two it did breakdown modded items as long as there is a recipe from the minecraft crafting-table.  I could not even breakdown the emerald armor from your own mods.  I thought it was strange.
All suggestioning now to revisit your spoilers to more a type out than just simple picture, leaves many questions.  Like the new potions, I can't seem to get them to brew.  Is the base water-bottle awkward, mundane or simple water?   Just need to add touch ups.  simple as:  mundane water-bottles + emerald = luck +5?  I don't know what is what.  Not everyone into youtube how-to's and want it quicker and simple.  Sadly, our world is just that imo.
Thanks for answering.
