### ISSUE TITLE
Sack of Holding and Double chests

### ISSUE THREAD

**Issue by Leopardington** [PrinceOfAmber/Cyclic#119]
I've used sacks of holding to transfer a load of double chests between bases.... 

Shift Rclicking on the RIGHT-HAND chest makes the entire double chest disappear even though only a single chest is held in the sack. The other chest is invisible and only shows up after restarting MC. 

Shift-Rclicking on the LEFT-HAND chest puts that chest in the sack while the entire double chest still shows up. (Both chests are visible even though one's in the sack).

Using cyclic 1.7.10 in minecraft 1.10.2 using the hermitpack

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this, ill look into it.

Was this in single player or multi?

**Comment by PrinceOfAmber** [comment]
Fixed in release 1.7.14, let me know if it breaks again or if theres any more issues https://minecraft.curseforge.com/projects/cyclic/files/2336276
