### ISSUE TITLE
Silk Touch Nether Ores

### ISSUE THREAD

**Issue by ShadowRoA** [PrinceOfAmber/Cyclic#125]
If I pick up Nether Ores with a Silk Touch Tool. I cannot process them further - I have to place and break them with a different tool. 

Just want to point that out and hope its not intended.

Greetings

**Comment by PrinceOfAmber** [comment]
Yeah youre right, i never added smelting recipes or anything for them, we should have those.

**Comment by PrinceOfAmber** [comment]
Resolved in 1.7.16 https://minecraft.curseforge.com/projects/cyclic/files/2338671
