### ISSUE TITLE
Emerald Carrot Horse Problem

### ISSUE THREAD

**Issue by JaRyCu** [PrinceOfAmber/Cyclic#126]
I'm playing the most current version of FTB Hermitpack.  I was looking through JEI and noticed the emerald carrot from cyclic.  I had a tamed horse with a saddle and diamond armor that I got last week, so I figured I'd try it on her.  She screamed, turned completely invisible, and then turned into a zombie horse.  (In retrospect, I'm guessing the zombie horse part was what the emerald carrot does?)  She still had a shadow on the ground.  I shift+clicked, removed the armor and saddle, and then killed her.  My screen turned all red and stayed that way for a while, before eventually returning to normal.  There were no potion effects nor text to give me a clue as to what happened, though.

Is that what's supposed to happen?

**Comment by PrinceOfAmber** [comment]
Really weird.  

Emerald carrot should swap the horse around between zombie, skeleton and regular, in a rotation like that.  When i have just cyclic installed and no other mods this works for me.  

Also i tried it in hermit pack, looks like this works too.

Were you on a server?  Do you have mods installed that added modded horse types.

Does this still happen to you after restarting the game?

I cant replicate this on my end, thats why im asking so many questions

**Comment by JaRyCu** [comment]
LOL no worries...I wish I had more information, but I haven't tried it again since that happened.  We've stuck to just the straight Hermitpack installation from Curse with no other mods added to the server.  On my end, I did add WAILA and it's associated mods (WAILA, -harvestability, and WAWLA).  As far as I can tell, we have only vanilla horses.  EnderZoo is part of the pack, but it doesn't add horses.  (I didn't even know there was a mod that added horses...I've seen the cow/pig mod, but that's it.)

I'll see if I can tame a horse I'm not attached to like I was to Bullseye.  She was an awesome horse, and I've setup a small memorial to her in my village that I've taken over.

BTW I love your mod...I seem to find some new toy every day to play with.

**Comment by PrinceOfAmber** [comment]
Thanks, glad you like it.

Yeah, i tried it with cyclic standalone, in single player, in a server, survival, creative, not seeing it happen.  very weird.  Sorry about the horse.  Closing issue for now, if it happens again or something new comes up feel free to comment and reopen
