### ISSUE TITLE
Autocrafter Dupe

### ISSUE THREAD

**Issue by Venrixia** [PrinceOfAmber/Cyclic#1300]
Minecraft Version: 1.12.2

Forge Version: forge-14.23.5.2847

Mod Version: Cyclic-1.12.2-1.19.19

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
When you use JEI to fill the recipe of the autocrafer after inputing the recipe already , provided you have enough to craft at least one , the autocrafter will produce an infinite number of the previously set item.

Video/images/gifs (direct upload or link): https://imgur.com/a/E8tSf55

**Comment by Lothrazar** [comment]
oh jeez i wonder what version introduced this one

**Comment by Lothrazar** [comment]
I couldnt get it to happen at first so thanks for the imgur, the trick is the SECOND time you do it, somehow it gets stuck like that, i see

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883487
