### ISSUE TITLE
Bag of Holding dupe bug

### ISSUE THREAD

**Issue by SullySadface** [PrinceOfAmber/Cyclic#1301]
Minecraft Version: 1.15.2

Forge Version: 31.1.0

Mod Version: Cyclic-1.15.2-0.1.8
--

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): Bag of holding causes all contents of container to drop to the ground in addition to the container being properly stored in the bag.

Log file link: No logs generated during the event

Video/images/gifs (direct upload or link): https://youtu.be/h0Qk6SCtpZk

**Comment by Krillic** [comment]
![2020-02-11_19 41 11](https://user-images.githubusercontent.com/60949978/74292919-466ed580-4d07-11ea-9a63-50088562cc21.png)
![2020-02-11_19 41 23](https://user-images.githubusercontent.com/60949978/74292920-47a00280-4d07-11ea-9c40-da69a7c51a84.png)
![2020-02-11_19 41 30](https://user-images.githubusercontent.com/60949978/74292921-48389900-4d07-11ea-9440-c4b5408e839f.png)
![2020-02-11_19 41 32](https://user-images.githubusercontent.com/60949978/74292922-48d12f80-4d07-11ea-8206-1141cf850b4c.png)

Hi this is definitely an issue, Using the sack of holding make the item(s) drop as well as the sack working correctly effectively making a duplication bug.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784
