### ISSUE TITLE
[1.15.2] Magnet enchant sucking items up in spectator mode

### ISSUE THREAD

**Issue by Quu1337** [PrinceOfAmber/Cyclic#1302]
Minecraft Version: 1.15.2

Forge Version: 31.1.0

Mod Version: 1.15.2-0.1.8

Single Player or Server: Server, didnt try in SP.

Describe problem (what you were doing; what happened; what should have happened):

Get magnet enchant in item, change to spectator mode and dropped items will be sucked to your location.

It could be affected by apotheosis, because it allows magnet to go to lvl XV.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784
