### ISSUE TITLE
Question about Charms 1.14-1.15?

### ISSUE THREAD

**Issue by Qsandas** [PrinceOfAmber/Cyclic#1303]
I hesitate a bit to ask this here, because I probably just overlooked something simple. But are the charms fully implemented in 1.14-1.15? I ask because I have tried everything I could think of to activate them and have scoured the internet for... over 6 hours now for an up-to-date answer with no luck. Are they activated in some unique way I just haven't tried, or have I overlooked something right in front of me this whole time?

**Comment by Lothrazar** [comment]
They dont have the on-off toggle feature from 1.12 so they should be always on.  I know i tested and they worked in 1.15.1

Looks like there is a bug in the new versions, somehow either my code or Curios isnt triggering them so ill fix that up https://www.curseforge.com/minecraft/mc-mods/curios

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784
