### ISSUE TITLE
Block Reach enchantment messes up inventory

### ISSUE THREAD

**Issue by GamerBah** [PrinceOfAmber/Cyclic#1304]
**Minecraft Version:**
1.12.2

**Forge Version:**
14.23.5.2846

**Mod Version:**
1.12.2-1.19.19

**Single Player or Server:**
Single Player

**Describe problem** (what you were doing; what happened; what should have happened):
When using Block Reach enchantment, the hotbar doesn't correctly identify where items actually are. It appears that the inventory index with Block Reach on starts at 1, not 0. Either that, or the first slot in the inventory becomes messed up, and only grabs from what's in the second slot (index 1). This makes it so that the item in slot 1 (index 0) will always act as if it was the item in slot 2. I show this by attempting to drop the item in my first slot without the Block Reach enchantment on, and then doing it again with the enchantment equipped.

Only way to fix this is by dying. Restarting the game or relaunching the world doesn't work.

**Video/images/gifs** (direct upload or link):
https://youtu.be/RFJMi6kqyC8

**Comment by Lothrazar** [comment]
Thanks for the great video. 

So there is something weird happening here.  

What modpack are you using? Or what modlist?

Has to be some mod conflict because with cyclic by itself and no other mods it works as normal.

But something else is happening at the same time and throwing something off center 

![1304](https://user-images.githubusercontent.com/621529/74620128-e3a58180-50ec-11ea-9a98-3ddd29dbe604.gif)

**Comment by GamerBah** [comment]
I added it to FTB Revelation, but I have a few more mods than what that pack comes with normally.
I'll see if I can get a full mod list after I'm done with some work!

**Comment by SonicX8000** [comment]
Looking closely at the video that @GamerBah showed. I spy Quality Tools and noticed how the block breaking was resetting after a split second. There's a conflict with using Cyclic alongside Potion Core + Quality Tools as it is the same bug that I get when using the Block Reach Enchantment.

Related Issue:
https://github.com/Lothrazar/Cyclic/issues/1241

Basically... you can only 'break' the block for a split second before it resets as if you couldn't break it... although if your harvesting speed is fast enough to instant-mine the block... it would break the block as intended.

Making the Block Reach enchantment use an attribute modifier... I think is called either 'reachDistance' or 'REACH_DISTANCE'... should fix it as it would allow both Block Reach Enchantment & Quality Tools to work together as the attributes will stack. Kinda like how the Heart Containers in older versions of Cyclic directly affected your health which caused a conflict with Scaling Health or other mods that used attributes, making your health buggy. The Hearts were changed to use an attribute modifier which fixed the conflict and were able to stack with other health attributes.

**Comment by Lothrazar** [comment]
Removed calls to NetController, now uses 
the property and nothing else
    public static final net.minecraft.entity.ai.attributes.IAttribute REACH_DISTANCE = new net.minecraft.entity.ai.attributes.RangedAttribute(null, "generic.reachDistance", 5.0D, 0.0D, 1024.0D).setShouldWatch(true);


https://github.com/Lothrazar/Cyclic/commit/f0059cd47dc379a6ec226d54e42a45fca6893ab0

**Comment by Lothrazar** [comment]
Also appli8es to https://github.com/Lothrazar/Cyclic/issues/1241 and  https://github.com/Lothrazar/Cyclic/issues/1332
