### ISSUE TITLE
Experience Obelisk exp gauge bugged in GUI

### ISSUE THREAD

**Issue by Keridos** [PrinceOfAmber/Cyclic#1306]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.19

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
GUI Updating not working properly in the experience obelisk.

If wanted, I could explain to you how you could properly do that without relying on block updates. Just poke me here when you'd like that.

**Comment by Lothrazar** [comment]
Doing it without block updates, you mean like sending a custom network packet?   Or using the "setField" system?

**Comment by Keridos** [comment]
In my mod OMT I use 2 systems, one that tracks all listeners (on the server inventory container, detectAndSendChanges()) and just distributes a custom network message (simpleimpl) to each listener per tick. Explanation for the other is down further. They both make GUI information that is not inventory (since minecraft handles that itself) super smooth and doesnt impact performance nearly as much as block updates do.

For the first system that can be used for GUIs that have an inventory container:
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.12/src/main/java/omtteam/openmodularturrets/client/gui/containers/TurretBaseContainer.java#L140-L149
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.12/src/main/java/omtteam/openmodularturrets/network/messages/MessageTurretBase.java


And I have an additional system that works for GUIs without inventory containers. It is a tiny bit more complicated and uses my Library mod. Basically the Tileentities that use it need to implement an interface, and have a list variable that gets updated through that interface. In their update() method they send a message to each member of that list containing needed information and additionally they scrub that list every 20 lists or so (checking player distance from block) in case a crash occurs or the gui did not close properly. 

https://github.com/OpenModularTurretsTeam/OMLib/blob/1.12/src/main/java/omtteam/omlib/network/ISyncableTE.java

This interface is then used by 2 messages that get sent during init of a gui on the client and on gui close:
https://github.com/OpenModularTurretsTeam/OMLib/blob/1.12/src/main/java/omtteam/omlib/client/gui/TrustedPlayersGUI.java#L75-L80
Those messages are really simple, they simply grab the listener list via a function on the interface and either add or remove a listener based on the contents of the message.

Sounds a bit complicated but this solved all the sync issues / performance (due to block updates/ unneceesary information flow) issues in my mod(s).

**Comment by Lothrazar** [comment]
Rebuilt in 1.15 problem does not occur there , 1.12 im just gonna leave  and move on :D
