### ISSUE TITLE
Let Block Placers/Structure Builders place redstone

### ISSUE THREAD

**Issue by Keridos** [PrinceOfAmber/Cyclic#1307]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.19

Single Player or Server: Server

This is more a feature request than a bug report.
The structure builder and the block placer both cannot handle redstone dust (as in place it). Would be neat if they'd be able to do that.

**Comment by Lothrazar** [comment]
The Automated User can place redstone if you put vertical offset at -1 (button on the left).  So for now you can use that

The Block Placer is very simple so i will keep that as it is.


For Structure Builder and Pattern Builder , yes it would make sense for both of these to be able to place redstone so ill look into that a bit
