### ISSUE TITLE
Text Projector leaves floating text

### ISSUE THREAD

**Issue by rickkloppers** [PrinceOfAmber/Cyclic#1308]
Minecraft Version: 1.12

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server:
Server
Describe problem:
So me and my friends are playing on a skyfactory server and one of them came across the Text projector and decided to check it out. What happened was he would place a projector put in the text and it would be there. But when he broke it the text stayed floating in the air and we dont know how to get rid of it.

**Comment by Lothrazar** [comment]
That is something weird.

If you log in and out does it still stay?  Does restarting server make a difference?


When i do a simple server (not SF4 just plain) it seems to work ok.

![1308](https://user-images.githubusercontent.com/621529/74621575-56652b80-50f2-11ea-83d8-dd0019e3242a.gif)

**Comment by rickkloppers** [comment]
Well that is weird, the issue is I dont know what they did to cause it to behave like that. Thought it may have been a more familliar bug. Its whatever now server isnt really active anyway. If you want i can ask them how they caused that bug so you can try and find a fix for it?

**Comment by Lothrazar** [comment]
Maybe its optifine or a laggy server? Or some conflict in the modpack ? Maybe report to modpack tracker?

Tried on my own server with small mod count and it works ok heres a gif.  
![1308](https://user-images.githubusercontent.com/621529/79179780-4057ac80-7dbd-11ea-83af-0bc7ff090093.gif)
