### ISSUE TITLE
Dupe glitch with Quantum Storage Unit + Cyclic Sack of Holding

### ISSUE THREAD

**Issue by Tiax** [PrinceOfAmber/Cyclic#131]
See http://webmshare.com/D3YKz

Not sure if a problem with Cyclic or Quantum Storage, so I'll report on both repos.

**Comment by Tiax** [comment]
Just for reference: [Not enough wands mod](https://github.com/romelo333/notenoughwands1.8.8/blob/master/src/main/java/romelo333/notenoughwands/Items/MovingWand.java#L185) does a `World#setBlockToAir` after saving the original data, instead of destroying the block, which seems to avoid the problem.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this.   If I use setBlockToAir by itself, then the inventory drops all its contents, but i see that they have a world.removeTileEntity(pos); which might help, thanks for the link

**Comment by PrinceOfAmber** [comment]
I fixed it using the removeTile and also setBlockToAir.  It no longer duplicates the items inside it (the nether star), but it still drops a block, and i cant stop it doing that from my end. 

If quantum storage was using default built in block behavior, it would drop as item on broken , and do nothing on setToAir.  Just like every other inventory container from vanilla and other mods.  They must be doing something custom?

So ill release like this for now

**Comment by Tiax** [comment]
Thanks!

**Comment by PrinceOfAmber** [comment]
Fixed in new 1.7.18, let me know if it happens again https://minecraft.curseforge.com/projects/cyclic/files/2338872

**Comment by Tiax** [comment]
Yay, block gets removed fine now! Next problem: you seem to get an extra bag now, when placing it down again. :s

**Comment by Tiax** [comment]
Fix: [b4b3d77.patch.txt](https://github.com/PrinceOfAmber/Cyclic/files/546660/b4b3d77.patch.txt)

**Comment by PrinceOfAmber** [comment]
do you get the extra bag only in creative?

When you place the full bag down, you get the empty one back.

**Comment by PrinceOfAmber** [comment]
Build 1.7.19 out soon

**Comment by Tiax** [comment]
Thanks - you may still want to consider handing off the task to the main thread in the packet handler. Doing so resolved the issue for me (see patch above).

> http://www.minecraftforge.net/forum/index.php?topic=20135.0
> **Warning for Minecraft 1.8:** As of Minecraft 1.8 onMessage is no longer called on the main thread but on the Netty-IO-Thread instead. Therefor you must not interact with the World or other "normal Minecraft-y things" in here directly. Instead you must schedule your code to be run on the main thread, which is done through the IThreadListener interface and it's addScheduledTask method. The Runnable you pass to this method will be executed on the main thread. The IThreadListener instance is Minecraft.getMinecraft() on the client and (WorldServer) ctx.getServerHandler().playerEntity.worldObj on the server. See below for examples.
