### ISSUE TITLE
1.15.2 Reusable eye of ender dupe

### ISSUE THREAD

**Issue by Yamza** [PrinceOfAmber/Cyclic#1310]
Minecraft Version: 1.15.2

Forge Version: forge-31.1.12

Mod Version: Cyclic-1.15.2-0.1.9.jar

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Using the Reusable eye of ender drops eyes of ender, giving infinite eyes of ender.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
