### ISSUE TITLE
[1.15.2] Main Menu crash, caused by Enchant?

### ISSUE THREAD

**Issue by NielsPilgaard** [PrinceOfAmber/Cyclic#1311]
Minecraft Version: 
1.15.2

Forge Version: 
31.1.12

Mod Version: 
https://gist.github.com/NillerMedDild/74ac019bd0f8471bea381bbc9bfaf2c5

Single Player or Server:
Neither, main menu.

Describe problem (what you were doing; what happened; what should have happened):
I was at the main menu, then alt-tabbbed away from Minecraft and back again, which made me crash.

Log file link:
https://gist.github.com/NillerMedDild/74ac019bd0f8471bea381bbc9bfaf2c5

**Comment by NielsPilgaard** [comment]
Downgrading Cyclic fixes the issue.

**Comment by Lothrazar** [comment]
apparently these key bind events for the player trigger in the main menu when the player is null, pushign out a quick fix soon

**Comment by NielsPilgaard** [comment]
Thanks :)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883170

**Comment by NielsPilgaard** [comment]
Thanks, will give it a go in a few minutes :)

**Comment by NielsPilgaard** [comment]
Can confirm it's fixed \o/
