### ISSUE TITLE
Question - Storage bag & Actually Additions crates

### ISSUE THREAD

**Issue by PurpleHel** [PrinceOfAmber/Cyclic#1313]
Question that might be a bug -
The storage bag won't deposit to Actually Additions crates. Is that on purpose?

Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.19; Actually Additions 1.12.2-r151

Single Player or Server: Server

**Comment by Lothrazar** [comment]
oops yeah the bag is using an old oudated api (IInventory) insetad of the new good stuff (inventory capability) so i just need to update my end
