### ISSUE TITLE
1.12.2-1.19.20 Conflicts with bibliocraft models

### ISSUE THREAD

**Issue by Chessus** [PrinceOfAmber/Cyclic#1314]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.12.2-1.19.20

Single Player or Server: Single player Enigmatica 2: Expert (Animania and Ice/fire dragons mods removed)

Describe problem (what you were doing; what happened; what should have happened):
-Updated to 19.20 to fix fluid collector bug
-Noticed all my Bibilocraft bookcases and icons in JEI were boned, mising textures, incorrect textures(Bookcase turning in to oak plank texture)
-Multi-MC console throwing up multiple Errors 
-Problem solved when reverting back to 19.19
-Recreated consistently

My first bug report, hope this is enough info

Log file link:
[debug-2.log.gz](https://github.com/Lothrazar/Cyclic/files/4219323/debug-2.log.gz)
https://www.pastefs.com/pid/179618

**Comment by Lothrazar** [comment]
1.19.20 reference https://github.com/Lothrazar/Cyclic/commit/e75867adeccb7fa0b72aeeb35455715fa3f41cbe

**Comment by Lothrazar** [comment]
Working on a new release (1.19.22).  Not sure what i changed but everything seems fine right now.  Biblio craft and forge version in the GIF, models seem ok.  Didnt see error from the log.  

![1314biblio](https://user-images.githubusercontent.com/621529/79031485-cf618c00-7b53-11ea-9292-55a8b0805efe.gif)

**Comment by Lothrazar** [comment]
Currently im getting a similar but different error, have to assume its on biblios side. Its random, about 1/5 times on startup, other times does not happen

` [jds.bibliocraft.models.BiblioModelWood:getModel:95]: Failed to load model. net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [bibliocraft:block/label.obj, bibliocraft:block/armorstand.obj]
[08:25:56] [Chunk Batcher 1/INFO] [STDOUT]: [jds.bibliocraft.models.BiblioModelWood:getModel:95]: Failed to load model. net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [bibliocraft:block/label.obj]
[08:25:56] [Chunk Batcher 1/INFO] [STDOUT]: [jds.bibliocraft.models.BiblioModelWood:getModel:95]: Failed to load model. net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [bibliocraft:block/label.obj]
`

**Comment by Chessus** [comment]
How bizare. Did any other users report the same bug I had?

**Comment by Lothrazar** [comment]
I dont know.

When i start the game 10 times, maybe 1 or 2 out of ten i get a "circular dependency" error from biblio craft and a few blocks dont render.  Other times everything is perfectly fine.  https://github.com/Nuchaz/BiblioCraft/issues/566
