### ISSUE TITLE
1.14.4 Harvester beam causing certain nearby blocks/environment to flash white

### ISSUE THREAD

**Issue by bessiq** [PrinceOfAmber/Cyclic#1315]
Minecraft Version: 1.14.4

Forge Version: forge-28.2.0

Mod Version: Cyclic-1.14.4-0.1.3.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

The Harvester causes a variety of different things to flash white when it fires its...crop-laser. (Do I call it a crop-laser? Harvest  beam? Plant pew-pew-er?)

I've linked a short video clip below, but here's a partial list of stuff I noticed flashing:

- water (Minecraft)
- torch flames (Minecraft)
- waystone text (Waystones)
- windows (Engineer's Decor)
- crystal blocks (Quark)
- chunk loader (Persistent Bits)
- campfire smoke (Minecraft)

Seems to be primarily affecting things that have some type of animation, e.g. water, torches, etc. Once I remove the Harvester or turn it off with a switch, no more flashing. It's a shame, because it really does a wonderful job. I'll probably just turn it on occasionally and AFK harvest.

I attached logs, but didn't see any errors. Just the usual "server running behind" because my base has become a little...busy.

Log file link:

[latest.log](https://github.com/Lothrazar/Cyclic/files/4222890/latest.log)
[debug.log](https://github.com/Lothrazar/Cyclic/files/4222891/debug.log)

Video/images/gifs (direct upload or link): 

https://www.dropbox.com/s/twz8693nr2v7yqf/Enigmatica%204%202020-02-18%2021-39-04.mp4?dl=0

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

N/A

**Comment by Lothrazar** [comment]
im just going to remove the laser from 1.14 since it also doesnt work in 1.15 anyway.  Will need to remake in new rendering system down the line
