### ISSUE TITLE
Not moving to normal pipe

### ISSUE THREAD

**Issue by CalebChrzan** [PrinceOfAmber/Cyclic#1316]
Minecraft Version: 1.12

Mod Version: 1.19.4

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Using Energy pipe to move power from Simple Energy Generator to tier one charger, with correct starting pipe and ending pipe, but no power is getting transferred.

**Comment by Lothrazar** [comment]
Just tested in latest version 1.19.20 , works just fine currently . https://www.curseforge.com/minecraft/mc-mods/simple-generators 
![2020-04-12_23 51 16](https://user-images.githubusercontent.com/621529/79099278-a4746500-7d18-11ea-8841-1def6909ed19.png)
also works with the simple ender pearl generator one too
