### ISSUE TITLE
Empty Heart Container Not Working

### ISSUE THREAD

**Issue by delprince979** [PrinceOfAmber/Cyclic#1317]
Minecraft Version: 1.12

Forge Version: 2837

Mod Version: Cyclic-1.12.2-1.19.20

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

I'm trying to use the empty heart item to lower my health (a bug accidentally made it like insanely high and it feels cheaty to leave it like that so I'm trying to lower it back down) but after I ate about 9 of them they just... stopped working. It wouldn't let me eat anymore.
If I had to guess, it probably said "Well I've taken away 9 hearts, and I don't wanna run the risk of taking away another if the player originally had 10 hearts and leaving them with NONE, so I'm gonna hard-lock here." However, I still have like... 50 hearts left lmao.

**Comment by SonicX8000** [comment]
Cyclic Hearts uses a health attribute so you might've already reached it's cap, which would be -18.0 '-9 Hearts' normally if lowering health, making that 9 cursed hearts.

Do you have other mods installed? They might be adding in their own Health Attributes and one or two, etc might be adding up to 50 Hearts, which would be 100 Health.

**Comment by Lothrazar** [comment]
Yeah must be some other mod setting the user to a fixed number of hearts.   With about 10 or so mods installed it works on its own 
![1317](https://user-images.githubusercontent.com/621529/79099432-f9b07680-7d18-11ea-87d9-9a91df81c628.gif)
