### ISSUE TITLE
Sack of Holding not respecting anything

### ISSUE THREAD

**Issue by Quu1337** [PrinceOfAmber/Cyclic#1321]
Minecraft Version: 1.15.2

Forge Version: 31.1.14

Mod Version: 0.1.10

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Sack of Holding can pick up pretty much everything;
RFtools forcefield blocks, securitycraft reinforced blocks, mekanism locked machines, refined storage locked system parts.
Stuff you arent able to break, should not be able to break, but still can somehow pick them up and place them somewhere else.
Even some modded torches, without them losing light.

**Comment by furtabs** [comment]
Can confirm this is a bug

**Comment by Lothrazar** [comment]
Are these blocks set as unbreakable? ill update to check the hardness,  and see if theres also another way too.

edit: testing with state.canHarvestBlock(world, pos, player)

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/commit/025d6903fcfef6d741ef0357cf51f5a6fbf26370
