### ISSUE TITLE
1.15.2-0.1.10 crashes dedicated server Forge 1.15.2 build 31.1.16

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Cyclic#1322]
Issue:  cyclic 1.15.2-0.1.10 crashes dedicated server Forge 1.15.2 build 31.1.16

Notes:
     upgraded forge from 31.1.14 to 31.1.16 and now cyclic is crashing the server on startup

crash report: 
http://paste.ubuntu.com/p/qx9kQrRZrg/

fml server latest: 
http://paste.ubuntu.com/p/trRgMZcr6g/

**Comment by Lothrazar** [comment]
Thanks for report, testing this on latest forge (.18).   On my local server on 31.1.18 i can log in and out of the running server ok


The crash logs on that website are cut off at a bottom, and the "download as text" button is locked behind a login or paywall or something, i cant see the full version



Can you please 
(A) Test v.18 of forge to see if it went away, or 
(B) if its still happening get the full log in a github gist or something similar

**Comment by kreezxil** [comment]
thanks for telling me about the truncation, i will switch to using gists from now on. 

I'll test this again shortly, thank you.
