### ISSUE TITLE
Huge dupe glitch with autocrafter

### ISSUE THREAD

**Issue by Apexassass1n** [PrinceOfAmber/Cyclic#1324]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.12.2-1.19.20

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):
when you are in the autocrafter and lets say you set the recipe to an iron block, if you double click with and extra iron ingot in your inventory it will auto-craft and infinite amount of iron block without using a single iron ingot.
What should have happened is it would not craft an infinite amount of item

Log file link:no log

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
This should fix it, thanks for testing and reporting https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2892633
