### ISSUE TITLE
Remote lever

### ISSUE THREAD

**Issue by Riddome** [PrinceOfAmber/Cyclic#1325]
Minecraft Version: 1.15.2

Forge Version: 1.15.2

Mod Version: 1.15.2

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Good afternoon just one little thing that bugs me is the ON/OFF is opposite from the action of the redstone lever. When i set the remote to a lever and shift click to turn it ON, the remote says off even though the power is on, and vice versa. 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
a bug is a bug, doesnt matter how much of a little thing it is :)

**Comment by Gr3atsaga** [comment]
Any chance of fixing this in 1.12.2?
