### ISSUE TITLE
Experience Pylon bug

### ISSUE THREAD

**Issue by Pengu-Hunter** [PrinceOfAmber/Cyclic#1328]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847 and others

Mod Version: 1.19.21 and others

Single Player or Server: SMP

Describe problem (what you were doing; what happened; what should have happened):
When  adding and removing xp from players xp bar to the pylon and back the pylon doesn't give back 100% of the added xp, if this is an intentional cost then i ask if a config option to change it could be added.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
RIght so , before if there was "555" exp in the tank, and i hit "-500" it would give me 500 and leave the 55 left over.

Hitting -500 over and over again refulsed to give those last few drops.   I changed it so if you hit "-500" and there is less than 500 remaining you get the remainder.

Heres a GIF where i start out with a command to give myself 555 exp exactly and going back and forth with it a few times to make sure its clean .

Also, you can always click the Top button (switch collect to spray mode to spray out EXP orbs into the world, this is also good for mending enchants. 

![1328](https://user-images.githubusercontent.com/621529/79084735-30bb6380-7cea-11ea-9a6b-d45fb1af7639.gif)
)
