### ISSUE TITLE
Boomerang dupe problem

### ISSUE THREAD

**Issue by lion099** [PrinceOfAmber/Cyclic#1329]
Minecraft Version: 1.15.2

Forge Version: 31.1.16

Mod Version: 0.1.11

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
I threw a boomerang, changed to a full slot, it gave me the boomerang in the inventory, and it droped it to the ground, and then i have two boomerangs

Log file link:
-

Video/images/gifs (direct upload or link): 
https://drive.google.com/open?id=12Rvs7PviZ7WXtD3NPkfCYzy7Dg8IR9rI
If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
oh so you switch hands and it has a collision, maybe it collides with the player or a block and then drops one the same second you pick it up. thanks for the report and video
