### ISSUE TITLE
Fluid Storage Tank not rendering contents

### ISSUE THREAD

**Issue by random51** [PrinceOfAmber/Cyclic#1331]
Minecraft Version: 1.1.5.2

Forge Version: 31.1.18

Mod Version: 1.15.2-0.1.11

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Fluid Storage Tanks not rendering contents in world or in inventory. Tested with lava and water.

Video/images/gifs (direct upload or link): 

![cyclic_tank_1](https://user-images.githubusercontent.com/12644511/76149631-f9fa8980-6069-11ea-8bff-0cbe6b69899b.jpg)
![cyclic_tank_2](https://user-images.githubusercontent.com/12644511/76149636-f9fa8980-6069-11ea-96a1-258f9513d8e1.jpg)

**Comment by Lothrazar** [comment]
making some progress

**Comment by Lothrazar** [comment]
screenshot https://twitter.com/lothrazar/status/1240451108864049154
