### ISSUE TITLE
Block Reach Enchantment doesnt work with creative flight items

### ISSUE THREAD

**Issue by bufu1337** [PrinceOfAmber/Cyclic#1332]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.21

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

I have an Draconic Armour Set. The chestplate gives creative flight capability in survival... but when i put the block reach enchantment on the chestplate i cant fly anymore... even if i put on the angel ring from extrautilities i cant fly... i disenchanted the chestplate and suddenly i can fly again... so block reach enchantment blocks creative flight...
in creative gamemode i can fly normally with the enchantment...
lately i updated Forge (earlier 14.3.5.2800) and Cyclic (earlier 1..19.5) where everthing was fine and now its infected with this bug :(

**Comment by Lothrazar** [comment]
Refactoring to remove calls to the Net Controller which affects flight.  will now only use the property https://github.com/Lothrazar/Cyclic/blob/dc34e1a80479b3916f4fe4714c56d8a97ad605d5/src/main/java/com/lothrazar/cyclicmagic/proxy/CommonProxy.java#L84
