### ISSUE TITLE
Any plan for Fabric version ?

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1334]
I don't know much about programming, but from what Minecraft community says, Fabric uses Mixin to standardize modification processes, therefore should have less compatibility issues and easier to adapt to latest version of Minecraft. 
Besides with adaption to Fabric you can still make it compatible with Forge using [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap), some mods such as [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge) already done this .
Many mod developers had migrated to use Fabric and the only available mod API available in 1.14 and later for MultiMC launcher is Fabric. So Fabric might be a good choice.
Don't get me wrong, I'm not asking for Fabric version, I'm asking if there's any plan for Fabric version.

**Comment by Lothrazar** [comment]
Its basically a time problem. The 1.15 port is only like 20% complete, so between that and supporting a bunch of other mods on both 1.12/1.15 , i have no time to learn what fabric is, how it works, and then start a new 1.15 port on fabric.

Fabric needs to find a way so people can run fabric mods and forge mods at the same time.  (I did hear that MultiMC has a bug or something where it cant get new forge versions, but thats their problem to fix.)

On the other hand if someone made a branch/pull request porting everything to 1.15 for me, i wouldnt care if it was fabric or forge id take it and support it fully.   

:)
