### ISSUE TITLE
Handheld Piston bypasses Clans protection

### ISSUE THREAD

**Issue by The-Fireplace** [PrinceOfAmber/Cyclic#1335]
Sorry for ignoring the template, I'm giving all the info that was given to me. Basically, I've been told the handheld piston from Cyclic bypasses the protections I have set up in Clans, and I'm finally getting around to trying to do something about it. Do you have a Maven? If there's a way to cancel the handheld piston's actions on my end, I'd be happy to do it. Otherwise, if you don't mind implementing a solution, `the_fireplace.clans.logic.LandProtectionEventLogic#shouldCancelRightClickBlock` will return whether or not the interaction should be allowed.

Minecraft Version: 1.12.2

The-Fireplace-Minecraft-Mods/Clans#101

Describe problem (what you were doing; what happened; what should have happened):
What happened: Handheld Piston moves blocks on someone else's claimed land
What should have happened: Handheld Piston fails to move blocks on someone else's claimed land

**Comment by Lothrazar** [comment]
Id love to have a maven i just dont know where to start setting one up for free. 

Ive heard about "Claimed Blocks" from lots of mods, does forge have an API or event for that? Is there a permission system where i can say "Does player have permission to edit block in this position"

**Comment by The-Fireplace** [comment]
I totally understand, I intend to get myself a Maven set up at some point once I have some spare money to use on one.
As for a Forge API for claimed blocks, not that I know of. Then again, the only other Forge claiming system I know of is FTB Utils (?), so there really isn't enough demand for one. Because of this, the best way to work with them is to either provide a way for them to cancel it or hook in to them and check before moving the block. I haven't actually looked at what the handheld piston is doing or how it works, but if it does something when you right click a block, maybe just making sure the RightClickBlock event is fired and the result respected will be enough? Using built in events would result in best compatibility, and remove the need for anyone to set up another soft dependency.
Edit: that said, if I need to set up Cyclic as a soft dep I have no problem with that as long as it doesn't break the dev environment.

**Comment by The-Fireplace** [comment]
Ok, so actually looking at the code now, it looks like the Piston Scepter is what the user was talking about. Looking at this code, couldn't I hypothetically send a bunch of PacketMoveBlocks to the server to mess with anything and everything I want? https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/item/ItemPistonWand.java#L172
If the problem is getting the client updated, would it not be better to send an update of the positions to the client after the movement happens? For example, https://github.com/The-Fireplace-Minecraft-Mods/Clans/blob/1.12.2/src/main/java/the_fireplace/clans/logic/LandProtectionEventLogic.java#L251

**Comment by Lothrazar** [comment]
For https://github.com/Lothrazar/Cyclic/issues/1212  i did some refactoring.

It now uses the BlockPistonStructureHelper.  Also it calls 
public boolean canPlayerEdit(BlockPos pos, EnumFacing facing, ItemStack stack)

To check if player is allowed to edit here
