### ISSUE TITLE
Bug with Better HUD

### ISSUE THREAD

**Issue by Swandar** [PrinceOfAmber/Cyclic#1336]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: Cyclic: 1.12.2-1.19.21 Better HUD: 1.12.2-1.4.1.jar

Single Player or Server: Single-player

Describe problem (what you were doing; what happened; what should have happened): 

Loading into the world gives me 2 hunger bars. I spent almost 4 hours trying to figure out what mod was causing it. Never would've thought it was Cyclic until I stumbled upon it by accident. Something else I stumbled upon by accident, because I created a new instance and only added Cyclic and Better HUD, was that I'm forced down to one heart in survival if I start the game in creative and use the /gamemode s command

Log file link: https://pastebin.com/MeCpM19r

Video/images/gifs (direct upload or link): 

1 heart in survival if I switch from creative
![image](https://user-images.githubusercontent.com/19779837/76489697-9375c280-63ff-11ea-9de3-91d4b0dcdcd5.png)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
I found the thing.  Luckily you can turn it off in my config file, just set this to false

`
        # Force the players hunger bar to show even when mounted [default: true]
        B:"Show Hunger Mounted"=false`
