### ISSUE TITLE
Cyclic's anvil on wrong side no matter what. Can't rotate with wood wrench.

### ISSUE THREAD

**Issue by Berths** [PrinceOfAmber/Cyclic#1337]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.12.2

Single Player or Server: server Roguelike adventure and dungeon modpack

Describe problem (what you were doing; what happened; what should have happened):
 I'm trying to place anvils from cyclic but they all stay in the same position no matter where i look. Wood wrench won't rotate them.
![2020-03-13_02 25 00](https://user-images.githubusercontent.com/26353567/76595426-f8015200-64d1-11ea-9352-9b292af7fe3f.png)

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/4328163/latest.log)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Swandar** [comment]
How do you expect Loth to solve the problem if you don't provide any information? You didn't include any logs, pictures, the mods you're playing with, or even something as basic as the forge version. Did you try finding out what mod is causing the problem? How about loading up an instance with only Cyclic to see if that's actually the default position or if it depends on the direction you're looking?

EDIT: Have you tried using an older version of Cyclic? You can find the forge version in the launcher, on the main menu(bottom left), or in the %appdata%/.minecraft folder. The log folders can also be found in the %appdata%/.minecraft folder.

**Comment by Lothrazar** [comment]
Thanks  for the picture.  Ill see about making them rotate , should be able to copy from normal anvil blockstates
