### ISSUE TITLE
Suggestion-Higher capacity automatic torch

### ISSUE THREAD

**Issue by PurpleHel** [PrinceOfAmber/Cyclic#1338]
I'd like to be able to set the automatic torch to have a higher capacity, basically so it can hold thousands (or more!) of torches. I used to use the void tear from XReliquary for this, but I stopped using that mod. If there was some cost to upgrade the autotorch, like add a diamond and upgrade the capacity by 512 or something, that'd be fine by me.
Playing 1.12.2

**Comment by Lothrazar** [comment]
Moved to my trello feature list to clear out issue tracker
