### ISSUE TITLE
You forgot to add lang to crystalized obsidian boots

### ISSUE THREAD

**Issue by Martin414** [PrinceOfAmber/Cyclic#1339]
Minecraft Version: 1.15.2

Forge Version: forge-31.1.19

Mod Version: Cyclic-1.15.2-0.1.11

Name for crystalized obsidian boots is "item.cyclic.crystal_boots"

![2020-03-13_15 58 29](https://user-images.githubusercontent.com/52965556/76632453-8c57cd00-6543-11ea-85e0-ddbc14671b4d.png)

**Comment by Lothrazar** [comment]
oops typo i had a '1' in there it was "item.cyclic.crystal_boots1": "Crystallized Obsidian Boots", fixed now
