### ISSUE TITLE
Ender Library Book Void Glitch

### ISSUE THREAD

**Issue by enderCoder99** [PrinceOfAmber/Cyclic#1340]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: Cyclic 1.19.20 with MC Eternal Modpack

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
When books are added to the library in multiples more than 1, the books get voided. Example:
If a 3 Power 1 books are added simultaneously, the bookshelf only displays a single [1] entry and not the expected [3] under Power 1.

When extracting, only one can be extracted.

I know in vanilla books are not stack-able, but  in MC Eternal it seems like it can, well for some books so far.

**Comment by Lothrazar** [comment]
How do you add three books at the same time?

You are Holding one book. that one book has Power 1.

Where are the other two Power 1 books, in your hotbar?  It only affects the one you are holding , right

**Comment by Lothrazar** [comment]
![1340](https://user-images.githubusercontent.com/621529/79143491-2e9ce780-7d72-11ea-9f5c-b5931cb3503a.gif)

**Comment by Lothrazar** [comment]
oh i just saw your last line just now oopes 

"I know in vanilla books are not stack-able, but in MC Eternal it seems like it can, well for some books so far."

Ok. i can fix it to check if you are holding a stack size >1

**Comment by enderCoder99** [comment]
Awesome, glad you could sort it out.
