### ISSUE TITLE
Wokrbench Duplication Glitch

### ISSUE THREAD

**Issue by BugmanBugman** [PrinceOfAmber/Cyclic#1344]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.12.2-1.19.21

Single Player or Server: LAN server

Describe problem (what you were doing; what happened; what should have happened):
if someone is crafting something in the workbench, and you take the item, then they are able to duplicate the item over and over. my friend did this and recorded it

Video/images/gifs (direct upload or link): 

![2020-03-17_18 13 27](https://user-images.githubusercontent.com/40730042/76910323-b2e77200-687b-11ea-876d-e222a8b13cb3.png)
![ezgif com-optimize](https://user-images.githubusercontent.com/40730042/76911103-df03f280-687d-11ea-932c-f7c89ee637df.gif)

**Comment by Lothrazar** [comment]
Got it to a place im happy with.

Recording of 2 players sharing a workbench on a server

![serversync](https://user-images.githubusercontent.com/621529/79029050-84417c00-7b47-11ea-9554-69c8fc4ffe66.gif)
