### ISSUE TITLE
Vanilla Ores still generate

### ISSUE THREAD

**Issue by Torino1564** [PrinceOfAmber/Cyclic#1347]
Minecraft Version: 1.12.2 

Forge Version: 14.23.5.2847

Mod Version: 1.16.9

Single Player or Server: Server 

Describe problem (what you were doing; what happened; what should have happened):
Vanilla ores still spawn even after the config file is set to false. I dont find any other way to disable them in the config other than the general ore spawn true/false. However, even with that set to false, they still spawn. 

Log file link: 

Video/images/gifs (direct upload or link): 

![Capture](https://user-images.githubusercontent.com/62400633/77106714-4f398200-69fe-11ea-81b6-60d94855b797.PNG)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
nothing in this mod disables VANILLA ores.   globalOverride means all ores from THIS mod are disabled.

For example if globalOverride  = false and aquamarine = true, it wont generate
