### ISSUE TITLE
Autocrafter crashing server when using a tool to craft inside it hits 0 durability 

### ISSUE THREAD

**Issue by LoneWolfGmer** [PrinceOfAmber/Cyclic#1348]
Minecraft Version: 1.12.2

Forge Version:  forge-14.23.5.2847

Mod Version:  Cyclic-1.12.2-1.19.21.jar

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

a user on my server has tested it on single player and also on the server.
basically it seems the auto crafter can't handle recipes that require tools like a knife or shears just about any tool that's modded or not

the issue is that once the tool's durability runs out it gets confused and crashes the server annoyingly enough. i'm certain what causes it ss the auto crafter

Log file link:

https://pastebin.com/LbbB1Cf1

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Ill add in a check for zero durability in the next version.

But also looks like something to be fixed in the other mod as well

`    at com.bewitchment.common.handler.PoppetHandler.toolProtection(PoppetHandler.java:165)`

**Comment by Lothrazar** [comment]
in hindsight i cant just change it to "when zero durability is reached delete the tool" as that breaks compatibilty with other mods.  Many items in other mods are "unbreakable" in that when they hit zero the user is meant to repair them.

Currently what happens, for examle with a wooden shovel.  it will hit zero. then get used again, the "breaking" of the item is done by vanilla handlers, nots not something i put in at all, the game detects the damage is below zero and kills it.  When its at zero, thats not for the user to decide. 


For example i made this farmland setup to test with wooden shovels.  No crashes of any kind, tool eventually breaks as normal.  If a mod such as bewitchment has a special case to handle zero durability, i dont want to interfere 
![test tool breaking 1348](https://user-images.githubusercontent.com/621529/78971902-71846400-7ac1-11ea-8a15-bb3deaa3b5ee.gif)

**Comment by Lothrazar** [comment]
Thanks for the report though, this was very much worth looking into and verifying the use cases
