### ISSUE TITLE
Item duping 1.14.4

### ISSUE THREAD

**Issue by Wlnfr** [PrinceOfAmber/Cyclic#1349]
Minecraft Version: 1.14.4

Forge Version: 1.14.4-forge-28.2.3

Mod Version: 
Cyclic-1.14.4-0.1.3
StevesFactoryManager-1.14.4-3.0.0-alpha26

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Found in ATM4 modpack, tested in new instance with only Steves Factory Manager and Cyclic mods.
Using factory manager to transfer items from item collector to another inventory(whitelisted) dupes any non-whitelisted item that stays in item collector in any 2 slots with at least one same item in different slots.
I've posted the exact same issue on Steves Factory Manager github as I'm not sure which mod's fault it is. Feel free to close the issue if it's not caused by your mod.

Video/images/gifs (direct upload or link): 
https://drive.google.com/open?id=1NNqFLD1ckFtrsksH52lPFE0L-4i3avuu

Counterpart(with hotfix from Steves Factory Manager): https://github.com/gigabit101/StevesFactoryManager/issues/96

**Comment by Lothrazar** [comment]
The block uses simple item capabilities in forge. cant find any errors using hoppers or pipes either.  But it sounds like its reported to ther mod already :)  

gigabit if you read this LMK if theres anything i can do
 
![2020-04-14_23 52 52](https://user-images.githubusercontent.com/621529/79307082-2eecce00-7eab-11ea-8606-b0014fe86f0c.png)
