### ISSUE TITLE
1.15.2 Log spam

### ISSUE THREAD

**Issue by Sunekaer** [PrinceOfAmber/Cyclic#1350]
Minecraft Version: 1.15.2

Forge Version: 31.1.25

Mod Version:  Cyclic-1.15.2-0.2.0

https://s1.sunekaer.com/i/25-03-2020_21-31-01_%25pn.gif

**Comment by LatvianModder** [comment]
You just need to do `context.get().setPacketHandled(true);` in end of each handle()

**Comment by Lothrazar** [comment]
thanks @LatvianModder  i didnt know that was a thing
