### ISSUE TITLE
[Request][1.12.2] Ability to move inventory buttons

### ISSUE THREAD

**Issue by ChaoticLogic** [PrinceOfAmber/Cyclic#1351]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847

Explanation:  Galacticraft adds another tab to the top of the inventory GUI for the space suit.  With your inventory expansion, the button can slightly overlap the GC tab, resulting in a space suit GUI appearing rather than your extended inventory. 

Request:  Would it be possible in a future version to allow the movement of the inventory and crafting buttons around the default GUI?

**Comment by Lothrazar** [comment]
Added configs

        # Location of the buttons on inventory [range: 0 ~ 200, default: 44]
        I:xOffsetButton=44

        # Location of the buttons on inventory [range: 0 ~ 200, default: 0]
        I:yOffsetButton=0

I thought about making them big upper tabs above the screen, but i couldnt find an API to add compatible tabs and i dont want ot break or overlap other tabs.

**Comment by ChaoticLogic** [comment]
You're amazing! Thank you!
