### ISSUE TITLE
Torches place in air from torch launcher

### ISSUE THREAD

**Issue by CreepyHobo** [PrinceOfAmber/Cyclic#1352]
Minecraft Version: 1.15.2

Forge Version: 31.1.27

Mod Version: 1.15.2-0.2.0

Single Player or Server:Single

Describe problem (what you were doing; what happened; what should have happened): When launching a torch quite often it will place in the air.

Log file link:

Video/images/gifs (direct upload or link):  https://imgur.com/2YX9tKh

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
haha yeah looks like its placing against non-solid blocks. like a torch on the side of a torch things like that pretty funny looking

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
