### ISSUE TITLE
Not compatible with my forge version?

### ISSUE THREAD

**Issue by DasFantatier** [PrinceOfAmber/Cyclic#1353]
Minecraft Version: 1.15.2

Forge Version: 31.1.0

Mod Version: Cyclic-1.15.2-0.2.0.jar

Single Player or Server: Tested both

Describe problem (what you were doing; what happened; what should have happened):
I installed the cyclic mod with twitch first, it automatically only shows mods wich are compatible. But when i load the game it says "cyclic needs forge 31.1.25 or higher", before the menu screen shows up.
I deleted the mod in twitch and downloaded the version manually from curseforge. First the 020, then the 017 file, but the problem stays.

I don´t know if this is a mod problem now, or a twitch problem because the mod should be compatible with my forge 31.1.0.  when twitch is showing it.

Log file link:
no log file because the message appears directly after starting

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

Thank you in advice!

**Comment by Lothrazar** [comment]
/shrug/ ok i guess you have to update to a newer forge version . 31.1.25  came out March 17th , and newest is 31.1.39 . twitch launcher isnt very fancy or smart
