### ISSUE TITLE
1.14.4 Issue with integer truncation when sending energy levels from server to client

### ISSUE THREAD

**Issue by LilyRose2798** [PrinceOfAmber/Cyclic#1356]
Minecraft Version: 1.14.4

Forge Version: 28.2.0

Mod Version: 0.1.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Client receives truncated (short instead of int) values from server for blocks such as the Battery.
Likely need to implement fix shown [here](https://github.com/Lothrazar/Cyclic/blob/6f402c4c3e7d779b00a7dd1932fb99e6ab3d15d4/src/main/java/com/lothrazar/cyclicmagic/net/PacketGuiShortOverride.java) for this version so client receives correct value. Server energy levels are fine and display correctly with mods such as WAILA/TOP, just an issue in the GUI itself.

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/1974590/78244736-f7d4ff00-7531-11ea-8b0a-42f0ec2b03ff.png)

**Comment by Lothrazar** [comment]
legacy versions are feature complete; resolved in 1.16+
