### ISSUE TITLE
Config Not Selectable

### ISSUE THREAD

**Issue by Rocho6** [PrinceOfAmber/Cyclic#1357]
Minecraft Version: 1.15.2

Forge Version: 31.1.35

Mod Version: 0.2.0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
I want to change the configs settings but when i go into the mods section on minecraft and select the mod, config is greyed out,

Log file link:

Video/images/gifs (direct upload or link): https://user-images.githubusercontent.com/53835426/78288740-91c78800-74ef-11ea-9959-d3d5f9c54d17.PNG

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Yeah forge changed the configs around, ill see if its available in forge yet . Can still use text file as always

**Comment by Lothrazar** [comment]
Looks like we are blocked by https://github.com/MinecraftForge/MinecraftForge/pull/6467
