### ISSUE TITLE
Fire charm particle crash

### ISSUE THREAD

**Issue by TehFoxFire** [PrinceOfAmber/Cyclic#1358]
Minecraft Version: 1.15.2

Forge Version: 31.1.30

Mod Version: Cyclic-1.15.2-0.3.0.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Taking fire damage with the fire charm in inv kicks client from server. 

Log file [link:](https://gist.github.com/TehFoxFire/af59de4154effc1e2e9c28d651970bce)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Log link is really huge but i replicated the same thing locally

https://pastebin.com/ZDc4Gm3t

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1318

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
