### ISSUE TITLE
Storage Bag not dumping items

### ISSUE THREAD

**Issue by Rithenar** [PrinceOfAmber/Cyclic#1360]
Minecraft Version: 1.12

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: Server 1.3.5

Describe problem (what you were doing; what happened; what should have happened):

I left click on a chest with empty slots and none of the contents of the Storage Bag are placed in t he chest. The first time I tried it I got a message that X amount of items had been deposited, however they didn't get deposit in the chest, they dissapeared.

I have tried changing the configuration of the bag from Dump to Merge as well as disable pickup. I've changed the colors just in case and tried several combinations of the above steps. I also left click and SHIFT+Lclick in case that was it.

So here is the chest with room. As you can see I also have partial stacks of Iron Ore and Clay in the last 2 slots
![chest](https://user-images.githubusercontent.com/9939332/78457272-9d8d8880-766e-11ea-9bf9-01a37b2e51af.png)

And here is the bag with plenty of clay and Iron as well as several other items that will not go onto empty slots
![Bag](https://user-images.githubusercontent.com/9939332/78457280-b007c200-766e-11ea-9eb6-cb2acbf5d07c.png)

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by postal291** [comment]
I'm experiencing the same issue.  MC Eternal pack.

Only difference I can see is my storage bag was renamed "Gathering Bag" in the anvil.

**Comment by Lothrazar** [comment]
Yeah it wasnt working with certain destinations such as AA crates, fix of this issue also applies https://github.com/Lothrazar/Cyclic/issues/1313

**Comment by Lothrazar** [comment]
Fix also applies to normal chests.  SO in merge mode, it wont go into empty slots at all, so the intended use is as you were showing, if theres 16 clay in the chest, it will fill that up to 64 from the bag. GIF here using an AA create with clay and books (after fix)
![1360](https://user-images.githubusercontent.com/621529/79161030-a594a900-7d8f-11ea-94d9-27686770742f.gif)

**Comment by postal291** [comment]
Yea I changed my dump chest to a vanilla double chest, two quick smacks as I walk in the door and it's all dumped.
