### ISSUE TITLE
Certain textures have not been updated for the Texture Update

### ISSUE THREAD

**Issue by muzikbike** [PrinceOfAmber/Cyclic#1361]
For example these chestplates:
![2020-04-05_02 08 23](https://user-images.githubusercontent.com/52297970/78464518-740e4480-76e2-11ea-839c-a49f7e1eb2ef.png)

**Comment by Lothrazar** [comment]
yeah new chest plates are kind of lame eh.. 

 You can always use the classic art to make them match if you want to. at least thats how i play 
![classic](https://user-images.githubusercontent.com/621529/78750332-e1a9b300-7924-11ea-840a-5ed9b072f1ec.png)
