### ISSUE TITLE
Harvester - Nether wart gives no extra nether wart

### ISSUE THREAD

**Issue by redaktiv** [PrinceOfAmber/Cyclic#1364]
Minecraft Version: 1.15.2

Forge Version: 31.1.36

Mod Version: Cyclic-1.15.2-0.3.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
When the harvester harvest nether wart you get no extra nether wart it just harvest the nether wart. 

1: Fully grown nether wart on soul sand.
2: Harvester harvest the nether wart
3: Nether wart is now on the first growth stage
4: No Nether wart is dropped.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
