### ISSUE TITLE
Server Crash when using excavate enchantment

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#1365]
Minecraft Version:1.15.2

Forge Version:31.1.30

Mod Version:Cyclic-1.15.2-0.3.0
PickleTweaks-1.15.2-4.0.1

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened):
some one got a pick with excavate enchantment on it it was also broke i have the mod pickle tweaks that does not brake a tool but it stops being usable and you repair it but he try to use it anyway and it crashed the server and then server whent into a crash loop. 

Log file link:
https://pastebin.com/bJtr1Vmz crash report
[latest.log](https://github.com/Lothrazar/Cyclic/files/4448036/latest.log)

let me know if this is more a pickle tweaks issue and ill report it there.

**Comment by Lothrazar** [comment]
ill unlock it so it will still work even if soomeone forces it to level 88 or whatever

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2924390
