### ISSUE TITLE
Cyclic Item Pipes need a way to add a filter

### ISSUE THREAD

**Issue by Lakota5225** [PrinceOfAmber/Cyclic#1367]
Minecraft Version: 1.15.2

Forge Version: 31.1.36

Mod Version: 0.3.2

Single Player or Server: server and single player

Describe problem (what you were doing; what happened; what should have happened):
Trying to get clay blocks to be moved using an energy condenser from Project e. but the pipes grab the items put it to be converted. A filter would be nice for other things as well. less of a bug just super annoying. other pipes work for the block but cyclic pipes ignore input and output of a universal block with inputs on all side with outputs on all sides.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
moved to https://github.com/Lothrazar/Cyclic/projects/4
