### ISSUE TITLE
Dry Peat Bogs not working?

### ISSUE THREAD

**Issue by TBFShad** [PrinceOfAmber/Cyclic#1368]
Minecraft Version: 1.15.2

Forge Version: 1.15.37

Mod Version: 1.15.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Placing a dry peat bog on the top layer of an ocean to saturate it, the block is not transforming nor is there any indication its working. it has been 3 hours since i placed them.

Video/images/gifs (direct upload or link): 
![2020-04-10_16 54 09](https://user-images.githubusercontent.com/63465132/79004187-22cfdc00-7b4c-11ea-8550-3cee6a63c8c4.png)
![2020-04-10_16 54 32](https://user-images.githubusercontent.com/63465132/79004191-24010900-7b4c-11ea-9114-d4f07b375549.png)

**Comment by TBFShad** [comment]
one block finally saturated after 5 hours of keeping the chunk loaded.

**Comment by Lothrazar** [comment]
They were hooking to the wrong random tick event for 1.15. ill also put a number in config that affects the conversion chance

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386
