### ISSUE TITLE
[Feature] XP from Autofisher [Mending Enchantment]

### ISSUE THREAD

**Issue by kvgeorge1** [PrinceOfAmber/Cyclic#137]
Could you add being able to use a "Mending" fishing rod in the Autofisher to actually receive XP when it fishes and use that to repair the rod?

https://minecraft.curseforge.com/projects/cyclic?comment=59

**Comment by PrinceOfAmber** [comment]
Auto fisher now sometimes repairs the rod if it has mending, so you will see the durability of a mending rod go up and down https://minecraft.curseforge.com/projects/cyclic/files/2342114
