### ISSUE TITLE
Automatic Torch wrong light level

### ISSUE THREAD

**Issue by purplemanjoe** [PrinceOfAmber/Cyclic#1370]
The automatic torch is placing torches when the light level is < 7, as opposed to <= 7. This leads to many situations where the block along a wall in a room is light level 7 but you can't light it with the automatic torch, and you don't have any torches in your inventory because the automatic torch ate them. It would be great if this were adjusted. Extra great if the light level were configurable.

**Comment by Lothrazar** [comment]
There is a light level config for this.  

In 1.12 its this

    I:AutoTorchLightLevel=7

IDK what version youre on but If you are playing in 1.15 this will be added soon
