### ISSUE TITLE
Crash when veign mining the item pipe

### ISSUE THREAD

**Issue by Lakota5225** [PrinceOfAmber/Cyclic#1371]
Minecraft Version:  1.15.2

Forge Version: 31.1.36

Mod Version: 0.3.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
using the veignminer mod to remove some pipes while working on a project and instant crash

Log file link: 
[WGQCpYJM.txt](https://github.com/Lothrazar/Cyclic/files/4463809/WGQCpYJM.txt)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386
