### ISSUE TITLE
Password Trigger Duplication Bug

### ISSUE THREAD

**Issue by adamsong** [PrinceOfAmber/Cyclic#1372]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.11

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

When triggering a password trigger from a different dimension a second one will appear in the players current dimension at the same coordinates as the password trigger in the original dimension. This is caused by `BlockPassword` sending the player's world to the tile entity instead of using the world reference.

Log file link:
Not applicable

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Fixed  world pass in the linked commit ^

Also i changed from creating a new default state, to get the current blockstate and alter the property, and then log an error if the block is not matching. to prevent new block creation
