### ISSUE TITLE
Client side request for turning off sprinklers' animation [1.12.2]

### ISSUE THREAD

**Issue by RaposoHunter** [PrinceOfAmber/Cyclic#1374]
Would there be any possibility of turning off the sprinklers animation in-game or via the cyclic configs file?

I'm experiencing some fps reduction when multiple sprinklers are in the screen (what makes perfect sense, obviously) and even when they're hidden by terrain or walls.

This isn't a major issue since someone could just transfer the farm they are being used to another dimension but keeping them on the overworld would be way much easier. 

I love this mod, btw. 

I'm playing on the most stable version of the mod for minecraft/forge 1.12.2

**Comment by Lakota5225** [comment]
Raposo one how much ram do you have dedicated to this client.
and two turn your particle effects to minimal.

**Comment by Lothrazar** [comment]
There is already a feature to turn off particles, if you shift (sneak)-right click on it , you can turn splash particles off.  Killing the particles this way should help with fps for sure.  
The animation is not very ram heavy, no more than a chest opening and closing.  If you are very worried you can use the sampler mod linked in the template.

In development i have 3.5 GB allocated to java, but having 8GB is better.  

These are some good java args https://darkosto.tv/DarkostoJavaArgs , also if this is a public modpack you can try reporting the lag issue there

**Comment by RaposoHunter** [comment]
> There is already a feature to turn off particles, if you shift (sneak)-right click on it , you can turn splash particles off. Killing the particles this way should help with fps for sure.
> The animation is not very ram heavy, no more than a chest opening and closing. If you are very worried you can use the sampler mod linked in the template.
> 
> In development i have 3.5 GB allocated to java, but having 8GB is better.
> 
> These are some good java args https://darkosto.tv/DarkostoJavaArgs , also if this is a public modpack you can try reporting the lag issue there

I dedicate 8GB for the game and I already used them without the water particles. I guess the problem as you already stated isn't in their animation itself. I use them combined with Actually Additions' worms so I guess this might have something to do with de fps reduction.

But, as I said, the fps reduction is not that troubling and it won't be lower than 30fps. Thanks for the quick reply and your willingness to help =D
