### ISSUE TITLE
Power System

### ISSUE THREAD

**Issue by TBFShad** [PrinceOfAmber/Cyclic#1375]
Minecraft Version: 1.15.2

Forge Version: 1.15.36

Mod Version: Forge

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): After a battery or generator hits 32k power, it turns into minus power so it will go from 32,000 to -32,000 and decline till it hits around -24,000.

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/63465132/79050210-7f043000-7c20-11ea-8bd5-4dd5b0b87569.png)
![image](https://user-images.githubusercontent.com/63465132/79050224-8b888880-7c20-11ea-9ada-ab6c63b8cf0d.png)

**Comment by Shockks** [comment]
Yes same issue same version

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
