### ISSUE TITLE
Excavation enchant empties NBT data

### ISSUE THREAD

**Issue by NielsPilgaard** [PrinceOfAmber/Cyclic#1376]
Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/369

Minecraft Version: 
1.14.4
Forge Version: 
1.14.4-28.2.3
Mod Version: 
1.14.4-0.1.3
Single Player or Server:
N/A

Describe problem (what you were doing; what happened; what should have happened):

When breaking a shulker box with a Cyclics excavation enchanted pickaxe and there is a similar colored shulker boxes right next to it the pickaxe excavates all the similar colored shulkers, drops them as items like it should but all the shulkers are empty.
If you use the enchanted pickaxe to mine only one shulker that dosent have same colored ones next to it, the shulker retains its contents. Same if there are different colored shulkers next to each other the pickaxe will only mine the one and the shulker keeps its contents.

**Comment by ediblecandles** [comment]
Beat me to it, lost a few stacks of iron to this bug unfortunately.
EDIT: this is also present in 1.15.2-0.2.0

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386

**Comment by NielsPilgaard** [comment]
Thanks!

**Comment by NielsPilgaard** [comment]
I can confirm that it is fixed, thanks again.
