### ISSUE TITLE
Scythes do not work.

### ISSUE THREAD

**Issue by Naxanria** [PrinceOfAmber/Cyclic#1377]
Minecraft Version: 1.15.2
Forge Version: 31.1.36
Mod Version: 1.15.2-0.3.0
Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Trying to harvest with the scythe, it breaks the single block, and that is it.

Log file link:
https://paste.feed-the-beast.com/view/8be78c92

**Comment by Lothrazar** [comment]
Worked in older releases but yeah broke in 0.3.x versions. fix on the way

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386
