### ISSUE TITLE
Unable to apply Experience Boost on pickaxe

### ISSUE THREAD

**Issue by simonboasaeter** [PrinceOfAmber/Cyclic#1378]
Minecraft Version: 
1.14.4
Forge Version: 
28.2.3
Mod Version: 
0.1.3
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Wiki and item tips says the enchantment "Experience boost" should work on pickaxe. However, it does not work. I never found it in the enchanting table with a pickaxe, I have a book with that enchantment but I cant apply it to my pickaxe. Using /enchant command does not work either, only gives me this message back :( "Diamond Pickaxe cannot support that enchantment" 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Last i checked the "break drops" event in forge wasnt hooked up because of something with loot tables, so for now this only works with Swords for mob xp. 
Ill see if it can be fixed in latest forge, if not ill change tooltip

**Comment by simonboasaeter** [comment]
Ah okay so thats why :D 
Take your time, just wanted to let you know! Maybe they added it in the new forge version? 2.28.4

**Comment by Lothrazar** [comment]
Yeah basically because of this https://github.com/MinecraftForge/MinecraftForge/issues/6420 .

But since forge is putting their new features in 1.15 ill look into the 1.15 build for another way to do block experience harvesting without that, .

Because loot tables dont do experiecne. unless im wrong lol
