### ISSUE TITLE
Crash with most recent version

### ISSUE THREAD

**Issue by Pengu-Hunter** [PrinceOfAmber/Cyclic#1379]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
During launch the instance crashes with the following log I don't know if this is on your end or if it is a compatibility issue.

Log file link:
[crash-2020-04-14_15.45.59-client.txt](https://github.com/Lothrazar/Cyclic/files/4473392/crash-2020-04-14_15.45.59-client.txt)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Oops, looks its crashing if FastWorkbench is not installed, but we want that to be optional so thats a quick fix https://www.curseforge.com/minecraft/mc-mods/fastworkbench

**Comment by Lothrazar** [comment]
I just have to roll back this change for 1.20.1 https://github.com/Lothrazar/Cyclic/commit/9fff34cad19217bf4c309661453e2969201daa8d#diff-85bc526acead8215d42f5ebb0b12c391L64

**Comment by Lothrazar** [comment]
This should fix it please try it https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2929610
