### ISSUE TITLE
Problem with item sorter and arrows 

### ISSUE THREAD

**Issue by Akeuh** [PrinceOfAmber/Cyclic#1380]
Minecraft Version: **1.12.2**

Forge Version: **14.23.5.2838**

Mod Version: **1.19.20**

Single Player or Server: **Server**

Describe problem (what you were doing; what happened; what should have happened): **I noticed that the "item sorter" doesn't know how to differentiate the different arrows with a potion effect.**

Log file link:

Video/images/gifs (direct upload or link): https://youtu.be/GmF3nXAnNBs

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Ill make a change to fix this.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934381
