### ISSUE TITLE
You cant join on 1.12.2 server

### ISSUE THREAD

**Issue by ImMineOfficial** [PrinceOfAmber/Cyclic#1383]
Minecraft Version: 1.12.2

Forge Version: forge-1.12.2-14.23.5.2847-universal.jar

Mod Version: Cyclic-1.12.2-1.20.1.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Every time when I try to join on the server then comes the remotehost exception message. And in the Console is this message: `[Server] Server thread/ERROR [FML]: 8: ASM: com.lothrazar.cyclicmagic.potion.effect.PotionBounce@183c8911 rebounceTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V`

Log file link: https://paste.labymod.net/ehequtayob.sql

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934381
