### ISSUE TITLE
Server crash 1.15.2

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#1384]
Minecraft Version: 1.15.2

Forge Version: 31.1.43

Mod Version: Cyclic-1.15.2-0.3.2

Single Player or Server: server

Not sure how it Happned as i was not on when it did but looking at my crash reports and it looks like it was something from this mod.

https://pastebin.com/PqZ46UXM
[latest.log](https://github.com/Lothrazar/Cyclic/files/4484500/latest.log)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386
