### ISSUE TITLE
[1.15.2] lost items when breaking non-empty item collector.

### ISSUE THREAD

**Issue by Bass2style** [PrinceOfAmber/Cyclic#1385]
Minecraft Version: 1.15.2

Forge Version: 31.1.46

Mod Version: Cyclic-1.15.2-0.3.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

when you break a Item Collector with items in it, those items are lost. it should hold items, or drop it on the floor, but none of those happen.
it should be interresting that the Collector maintain the Redstone mode set before breaking, because it's also resetting when broken and place back.

Video/images/gifs (direct upload or link): https://www.youtube.com/watch?v=oQYgTp-U2vo

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934386

**Comment by Bass2style** [comment]
working perfectly. thanks.
