### ISSUE TITLE
[1.12.2] Lack of Ore Dictionary Support in some recipes

### ISSUE THREAD

**Issue by ChromaPIE** [PrinceOfAmber/Cyclic#1386]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2852

Mod Version: 1.20.1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

The recipes for Fluid Drain and Block Hydrator lack support for Ore Dictionary, causing <<ore:blockIron>>s from other mods failing to join in and achieve the recipes. It is weird that other stuff in Cyclic do support any <<ore:blockIron>>. I'm not sure if there are more recipes which also lack OD support.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2934381
