### ISSUE TITLE
Minecraft 1.14.4 Config

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1387]
Minecraft Version: 1.14.4

Forge Version: forge-28.1.99

Mod Version: Cyclic-1.14.4-0.1.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I would like to change/disable the enchantments like the magnet one. But i dont have any configs to work with. It only shows me:

"
#General settings
[cyclic]
	#Testing only, this does nothing
	itemTooltip = true
"

Log file link: -

Video/images/gifs (direct upload or link): -

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Blognarth** [comment]
I am also having this issue and can't enable a feature i want to use as a result

**Comment by Lothrazar** [comment]
legacy versions no longer getting enhancements
