### ISSUE TITLE
Item Transfer Node item duplication bug

### ISSUE THREAD

**Issue by Webberjo** [PrinceOfAmber/Cyclic#1388]
**Minecraft Version**: 1.12.2
**Forge Version**: 14.23.5.2838
**Mod Version**: 1.19.14
**Single Player or Server**: Server (SkyFactory 4 v1.4.0)
**Describe problem**:
Linking an **Item Transfer Node** to a **Filing Cabinet** causes the item in the **Item Transfer Node** to get stuck, resulting in an infinite amount of that one item being sent to the **Filing Cabinet**. This allows for duplicating any item that can be stored inside a **Filing Folder**. The item in the **Item Transfer Node** should be emptied upon transfer, as it does if the node is linked to a chest.

My setup goes as follows:
- **Hopping Bonsai Pot** [_Bonsai Trees_]
  - **Dirt** [_Minecraft_]
  - **Dirt Sapling** [_sky_orchards_]
- **Chest** [_Minecraft_]
- **Item Extraction Cable** [_Cyclic_]
- **Item Transfer Node** [_Cyclic_]
  - **GPS Marker** [_Cyclic_]
- **Filing Cabinet** [_Real Filing Cabinet_]
  - **Filing Folder** (Oak Wood) [_Real Filing Cabinet_]
  - **Filing Folder** (Stick) [_Real Filing Cabinet_]
  - **Filing Folder** (Dirt Sapling) [_Real Filing Cabinet_]
  - **Filing Folder** (Dirt Leaves) [_Real Filing Cabinet_]
  - **Filing Folder** (Dirt Acorn) [_Real Filing Cabinet_]
  - **Filing Folder** (Dirt Resin) [_Real Filing Cabinet_]

![filing_cabinet_item_duplication_bug](https://user-images.githubusercontent.com/11682731/79619432-326a9a00-80e3-11ea-8416-dd61b95ad76a.png)

**Comment by Lothrazar** [comment]
I think this has been resolved with newer versions of the mods or forge.

forge 14.23.5.2847
Cyclic 1.20.1
Real Filing cabinet 0.2.0.19


Folders: oak wood
oak planks

For me the node slot gets emptied and the cabinet accepts the item.  Exact number of items are moved over

animated GIF:
![1388](https://user-images.githubusercontent.com/621529/79672741-a95a6e00-8189-11ea-9675-4ee318da1417.gif)

**Comment by Webberjo** [comment]
Good to know this was fixed in a later version. I guess SkyFactory 4 will just need to release a new version with the updated Cyclic mod in it for this to be fixed in the modpack.

As a workaround I have the node transferring to a chest, then transferring the items from the chest to the filing cabinet.

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1259 <3
