### ISSUE TITLE
Uncrafting Table suggestion

### ISSUE THREAD

**Issue by Pengu-Hunter** [PrinceOfAmber/Cyclic#1389]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.201.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
The configs for the uncrafting table are all great except that you cant access them through the ingame config, but the last uncrafting config either makes you take the first of multiple recipes or not at all for the uncrafter, my suggestion is to implement something similar to "jglrxavpok's Uncrafting Table" where the output recipe can be selected from multiple if available.

Video/images/gifs (direct upload or link): 
https://www.curseforge.com/minecraft/mc-mods/jglrxavpoks-uncrafting-table

**Comment by Lothrazar** [comment]
moved to 1.16+ idea bucket
