### ISSUE TITLE
[Feature] Some other suggestions  (exp bottler, mobproof magic glass, auto feeder, totem)

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#139]
1. ChunkLoader block
2. Some way to get XP from player and store it, like a liquidxp or xpbootler etc.
3. Two "magic" glass block: One is solid for player and non-solid for mobs, second acts in the opposite way.
4. Automatic feeder: Put wheat/carrots/seeds/etc into this block's inventory and animals will be bred automatically.
5. Something like a totem from MC 1.11 pre: A special Item. When a player has this item in inventory and hp drop to 0, then he was resurrected, fully healed(and feeded) and get a Regeneration III, Resistance IV, and FireResistance for 10 seconds. But this item in player's inventory will destroyed/used up.

**Comment by PrinceOfAmber** [comment]
Thanks for all the feedback!  A few chunk loaders already exist and work pretty well (Persistent Bits standalone mod, extra utils 2, other mods), but the other ideas i will look into for sure.

 The EXP idea is one ive been thinking of for a while.  I had a way to bottle exp in a really old mod.

**Comment by PrinceOfAmber** [comment]
for #4 Im slowly working on some farming blocks. one that shears sheep and milks cows, and another that feeds them. might combine them both into the same block

**Comment by Calvin315** [comment]
Could you also add a whitelist mode for the Controlled Miner?

**Comment by GrzechuGrek** [comment]
>  few chunk loaders already exist and work pretty well (Persistent Bits standalone mod, extra utils 2, other mods)

I understand, but if you least one more time consider to add a simple chunk loader, this would be very kind of you. This would denote independent from few/many other mods too. This is one of mainly reason why I use Cyclic. 
Use ExtraUtils for one item/block isn't make bigger sense imho.
I did used some other mod whose introduced a very simple chunk loader but is not suitable for current version MC 1.11.2, as it is for 1.10.2 only. This simple chunk loader was crafted from 3 iron ingots, 3 redstone powder and 1 ender pearl and worked very well, loaded 9 chunks as well. I did liked it.

**Comment by PrinceOfAmber** [comment]
I will not 100% rule out a chunk loader, i might one day but i have many more things to look into first.  I list my future ideas under milestones https://github.com/PrinceOfAmber/Cyclic/milestones

For now ive been using this https://mods.curse.com/mc-mods/minecraft/258914-the-weirding-gadget

As for other things, sooon there will be a new update where the EXP pylon lets you bottle your own experience.  Also I have just now added a soulstone as a totem like death prevention.

As for an autofeeder, currently the automated user does work to feed animals.  Its not great and has limited range but it works.

I have put mobproof block on my milestone backlog so i dont forget, but im not sure how to make this work so ill revisit later ( https://github.com/PrinceOfAmber/Cyclic/milestone/50 ), 

For now i think that addresses everything.  Look for version 1.3.0 for 1.11.2 comin soon!

**Comment by PrinceOfAmber** [comment]
Everything here has been either added to release https://minecraft.curseforge.com/projects/cyclic/files/2411176
or added to my backlog for future consideration, so closing this issue https://github.com/PrinceOfAmber/Cyclic/milestones
