### ISSUE TITLE
Allow XP extraction from Experience Pylon

### ISSUE THREAD

**Issue by Silicato** [PrinceOfAmber/Cyclic#1390]
Minecraft Version: 1.15

Forge Version: 31.1.45

Mod Version: 1.15.2-0.3.2

Single Player or Server: Single Player & Server - FTB Omnia

Description:
In a mob farm configuration, we placed the pylon a the center to collect xp. The problem now is that we need to enter the farm to collect this xp, clicking with sugar or glass bottle. The pack doesn't contain an automatic block that right click the pylon to 'create' this items, that could actually be one solution.

NOTE:
I previously player other pack with 1.12 that contains liquid experience (probably from OpenBlock) and if i remember correctly, Cyclyc allowed extraction as liquid. FTB Omnia doesn't contain such liquid form.

I think will be useful:
 - allow extraction from the pylon as old liquid system + **dedicated Cyclic specific xp liquid**.
 OR
 - create a linkable remote pylon that allow to extract by manually right click without entering the farm.

**Comment by Lothrazar** [comment]
![2020-06-27_20 16 48](https://user-images.githubusercontent.com/621529/85936842-3836e580-b8b3-11ea-86d2-eac91c135df9.png)
![2020-06-27_20 16 05](https://user-images.githubusercontent.com/621529/85936843-38cf7c00-b8b3-11ea-9aba-d21c5636104c.png)
