### ISSUE TITLE
ore-excavation, vein mineing cable crashes game

### ISSUE THREAD

**Issue by usafphoenix** [PrinceOfAmber/Cyclic#1391]
Minecraft Version: 1.15.2

Forge Version: 31.1.46

Cyclic Mod Version: 1.15.2-0.3.2
Ore excavator version: 1.7.151

Single Player or Server: SSP

Describe problem (what you were doing; what happened; what should have happened):
when breaking cable with vein miner key activated, client crashes to launcher. 
"The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=down, clazz=class com.lothrazar.cyclic.block.cable.EnumConnectType, values=[NONE, CABLE, INVENTORY, BLOCKED]} as it does not exist in Block{minecraft:air}"

Log file link: http://txt.do/1l7zd

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
