### ISSUE TITLE
Replaceable scaffolding Deletes ANY block in some circumstances when trying to place

### ISSUE THREAD

**Issue by blarging2000s** [PrinceOfAmber/Cyclic#1393]
Minecraft Version: 1.15.2

Forge Version: 31.1.44

Mod Version: 1.15.2-0.3.2

Single Player or Server: Both

Modpack: All The Mods 5 (1.16a)

Describe problem (what you were doing; what happened; what should have happened):
While I was trying to place some replaceable scaffolding with shift-click I had clicked a face that didn't have enough space on the opposite side to place the scaffolding and instead of doing nothing it deleted the block I click and placed the scaffolding where the block was.
Steps to reproduce:
1:Hold Replaceable scaffolding.
2:Shift-right-click any block face that doesn't have enough space on the opposite side.
Tested on: Tile entities with gui, obsidian, bedrock.

Log file link:

[latest.log](https://github.com/Lothrazar/Cyclic/files/4502842/latest.log)
[debug.log](https://github.com/Lothrazar/Cyclic/files/4502844/debug.log)

Video/images/gifs (direct upload or link): 
Setup
![Setup-2020-04-20_02 49 34](https://user-images.githubusercontent.com/1069422/79742761-2be14b80-82b8-11ea-8d42-c34ac09863af.png)
Shift
![Shift-2020-04-20_02 49 45](https://user-images.githubusercontent.com/1069422/79742818-44516600-82b8-11ea-8ba3-9bbcf1aba11e.png)
Rightclick
![Rightclick-2020-04-20_02 49 47](https://user-images.githubusercontent.com/1069422/79742844-4f0bfb00-82b8-11ea-81c8-5a02a2836b3d.png)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
i think this has fix https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2941336
