### ISSUE TITLE
shape builder shift click crash

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1394]
Minecraft Version: 1.15.2

Forge Version: 31.1.47

Mod Version: 1.15.2-0.3.4

Single Player or Server: Singleplayer

I placed diorite into the shape builder. I then shift-clicked the diorite out of the shape builder and minecraft crashed

Log file link:
https://pastebin.com/FidYaJCp <-Crash Log
https://pastebin.com/Q0q6RyAW <-Latest.Log

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2941336
