### ISSUE TITLE
Don't understand how it works?

### ISSUE THREAD

**Issue by KyleRickards** [PrinceOfAmber/Cyclic#1395]
Minecraft Version: 1.15.2

Forge Version: forge-1.15.2-31.1.48-installer

Mod Version: 1.15.2

Single Player or Server:Single

Describe problem (what you were doing; what happened; what should have happened):

It's probably something very simple but I have downloaded the mod, installed it and I can see it in the start game menu - but I have no idea how to do anything else with it? I have looked online and Youtube but nothing - is there something I am missing? I did see a video for auto placing of torches for example but I don't know how to get to that feature

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Not sure i understand the question.  Sounds like you have forge installed already. and inside the forge mods button you see it in the start game menu thats good.

craft the items in survival, or in creative mode just give your self some items and try them out

**Comment by KyleRickards** [comment]
Thanks for getting back to me - I just can't see the crafting options but I will have another go.
Really appreciate the work you have done :)

    On Saturday, 25 April 2020, 18:47:12 BST, Sam <notifications@github.com> wrote:  
 
 


Not sure i understand the question. Sounds like you have forge installed already. and inside the forge mods button you see it in the start game menu thats good.

craft the items in survival, or in creative mode just give your self some items and try them out
