### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#1397]
Minecraft Version:1.15.2 

Forge Version:31.1.47

Mod Version: Cyclic-1.15.2-0.3.4

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Not sure what not on when it happened just looked at crash report and it seems like it was from cylic

Log file link:

https://pastebin.com/B3W0yFb3

**Comment by IchigoGames** [comment]
not sure if this one is connected but all the info is the same https://pastebin.com/gVfqyPPc another crash from cyclic on server

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2941336
