### ISSUE TITLE
Crash when placing fluid extraction cable on growth crystal tier 3 from mystical agriculture in Sky Factory 4 mod pack

### ISSUE THREAD

**Issue by PranavSuby** [PrinceOfAmber/Cyclic#1399]
Minecraft Version: 1.12.2

Forge Version: 
14.23.5.2838
Mod Version: 
Cyclic-1.12.2-1.19.14
Single Player or Server:
Single Player
Describe problem (what you were doing; what happened; what should have happened):
I placed an fluid extraction cable on a tier three growth crystal and the game crashed and won't reopen

Log file link:
[Link
](https://docs.google.com/document/d/1YFy9u7c-2uOHcT-QVeb1vKq56670tisbTwWJUZeKNko/edit?usp=sharing)
Video/images/gifs (direct upload or link): Don't have 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
modpack uses old version of the mod, please report to the modpack issue tracker or update the mod directly
