### ISSUE TITLE
How to use a few of the tools (Need Basic Documentation)?

### ISSUE THREAD

**Issue by GeneralAtrox** [PrinceOfAmber/Cyclic#140]
Hi there,

Loving the mod and the ideas around it so far. 

I built an automatic torch but have no clue, nor can I find any documentation on the web about how to use it. 

Could you throw up a quick Wiki on how some of the things work? 

Thanks for your time & work!

**Comment by PrinceOfAmber** [comment]
I agree.  I keep meaning to make an in-game book just like actually additions or like tinkers construct but i never have the time to find out the code or API they use.  And posts like this I found just re confirm that things are not super clear and usuable https://www.reddit.com/r/HermitPack/comments/5a43kj/cyclic_controlled_miner/

Ill try to get started on a wiki on monday when im back to it.

**Comment by PrinceOfAmber** [comment]
Starting a wiki, but it wont be up fast.  https://github.com/PrinceOfAmber/Cyclic/wiki

**Comment by PrinceOfAmber** [comment]
also investigating using guide api, similar to what blood magic does : https://github.com/TeamAmeriFrance/Guide-API

**Comment by GeneralAtrox** [comment]
Excellent, thank you Sam!

I would help myself but I don't know how to use the majority of things
myself.

**Comment by PrinceOfAmber** [comment]
Closing this now since almost everything has an ingame tooltip as well as a JEI description.  I dont plan to add an ingame book, at least not anytime soon or unless some cool API comes out for one.  I do plan to finish off the wiki or make a website, but those arnet code bugs.  

Thanks for your reports and ideas 👍
