### ISSUE TITLE
Exchange Scepter Crash

### ISSUE THREAD

**Issue by FallenEagle1** [PrinceOfAmber/Cyclic#1400]
Minecraft Version: 1.15.2

Forge Version: 31.1.36

Mod Version: 1.15.2-0.3.2

Modpack: RAM 0.3.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

It looks like that the scepter has issues with exchanging certain blocks, and will crash a server. The issue does not happen in single player. To replicate, try to select the block Dark Stone Bricks from Forbidden Arcanus with the building scepter (exchanging) and the server will immediately crash.

Log file link: https://hastebin.com/igoziyayoh.rb

**Comment by Lothrazar** [comment]
Seems resolved in 0.4.0 which was released april 26 , using it with no issues on a server
