### ISSUE TITLE
Extended Inventory Tool Belt reset when using Vampirism mod

### ISSUE THREAD

**Issue by SilverKaz** [PrinceOfAmber/Cyclic#1403]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server:  single

Describe problem (what you were doing; what happened; what should have happened):

1. Store equipment into Extended Inventory Tool Belt (default key: R)
2. Become a Vampire or Vampire Hunter using Vampirism mod
3. Check Extended Inventory Tool Belt, nothing is there (seems to reset)

Possible cause (totally guessing here): becoming a Vampire or Hunter sets the player as a new character which doesn't have access to wherever the toolbelt stores its information.

Will post similar to Vampirism mod.  Thank you for your awesome work and mod, btw!

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by MrMSch** [comment]
Any update on this?  I've currently lost access to all my stuff on the server I play on due to this bug.  Is there any way to stop being a hunter like you can do with the cleansing for being a vampire?

**Comment by TheSnowyChickens** [comment]
Hello, 

same problem here. :D
I turned myself in a Hunter and lost all my stuff. :(

**Comment by MrMSch** [comment]
@TheSnowyChickens  - I found you can inject Sanguinare Vampiris to turn you back into a normal player from a hunter.  All your stuff remains when you switch back.

This defect still needs resolved as it's super annoying.

**Comment by TheSnowyChickens** [comment]
Ah okay, ty for this info. :)

**Comment by Lothrazar** [comment]
Ok, so it does not work when you are mutated into the hunter, because it uses completely different player data. But everythings still there, and works again when you revert to normal human player  

i dont really have control over that, if thats how the vampire mod works.  Wish i could fix it

**Comment by MrMSch** [comment]
You may not be able to control the switch into different player data but you there is still a link between them in the vampire mod which could be read to adjust gracefully.
