### ISSUE TITLE
Item transfer node bug

### ISSUE THREAD

**Issue by Joca019751** [PrinceOfAmber/Cyclic#1404]
Minecraft Version: 1.12.2

Forge Version: 1.12.2

Mod Version: 

Cyclic-1.12.2-1.19.14
--

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I set up wireless transfer node and when i place an item in the slot it doesn't transfer my item, it just duplicates it

Log file link:

Video/images/gifs (direct upload or link): 
Link of the video:
https://anonfiles.com/H2L7Rctcob/2020-04-27_10-37-02_mp4

**Comment by Lothrazar** [comment]
please update the mod this should have been fixed in older version https://github.com/Lothrazar/Cyclic/issues/1259
