### ISSUE TITLE
Bug w/drawers and Cyclic pipes.

### ISSUE THREAD

**Issue by Tabomeister** [PrinceOfAmber/Cyclic#1405]
Minecraft Version: 1.15.2

Forge Version: 

Mod Version: 0.4.2

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
When pulling item out from a storage drawer with a Cyclic item pipe, it fills the destination inventory and doesn't cosume the items in the drawer.

Thanks.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by minsterxev** [comment]
This also happens on MP servers as well.  I was able to fill a chest with diamonds by putting one diamond into a storage drawer and use the item pipe to extract into a chest.  

Mod Pack: All the Mods 5

**Comment by Lothrazar** [comment]
bugs not occurring between different chests or different machines,
mod 0.7.0
mc_version=1.15.2
forge_version=31.2.36

Leaving this up to other mods as noted. will continue testing in 1.16 for future storage drawer updates  as they come
