### ISSUE TITLE
BOP Mud

### ISSUE THREAD

**Issue by NordicGamerFE** [PrinceOfAmber/Cyclic#1407]
Minecraft Version: 1.12.2

Forge Version: forge-14.23.5.2847

Mod Version: Cyclic-1.12.2-1.19.18.jar

Modpack: MC Eternal 1.3.5.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
using water walking enchantment and walking into bop mud (biome of plenty) will make you sink,
i am using fire and ice armor

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
