### ISSUE TITLE
[1.15.2] crash when reloading a world.

### ISSUE THREAD

**Issue by Bass2style** [PrinceOfAmber/Cyclic#1408]
Minecraft Version: 1.15.2

Forge Version: 31.1.63

Mod Version: Cyclic-1.15.2-0.4.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
i have tryed the Tesseract mod by SuperMartijn642, and i tested some pipes/ducts without issue.
when testing some other stuff not related to another mod (not related about items etc), i had to relaunch my game because of config changes.
i wanted to use the same test world, but when loading the save, the game is crashing because the pipe still attached to the Tesseract seems buggy.

Log file link:
https://pastebin.com/dVzZXrbF
https://pastebin.com/bgCuvvS0

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by SuperMartijn642** [comment]
That's definitely caused by my mod, not by cyclic.

**Comment by Bass2style** [comment]
okay, good to know. i should close this issue then. do i need to report this on your Github, or it's OK ?

**Comment by SuperMartijn642** [comment]
I fixed it in Tesseract version 1.0.2, so you don't need to open one their.

**Comment by Bass2style** [comment]
ok, no problem. i had not noticed your reply on CurseForge before my reply here. ^^
