### ISSUE TITLE
Extract/Push Issue With Item Pipes

### ISSUE THREAD

**Issue by LovelessTie** [PrinceOfAmber/Cyclic#1409]
Minecraft Version: 
1.15.2

Forge Version: 
31.1.63

Mod Version: 
Cyclic 1.15.2-0.4.0

Single Player or Server:
Both

Using Item pipes
Once a inventory was full items where being pushed into a inventory that should have been only pull from
![2020-05-01_18 12 09_LI](https://user-images.githubusercontent.com/24214058/80786400-a757cc80-8bd7-11ea-9984-33eb10f55448.jpg)
Once inventory 3 was full the items in the first slot of inventories 1 and 2 would bounce between them

https://clips.twitch.tv/HungryCautiousRaccoonDendiFace

**Comment by Lothrazar** [comment]
Right should be a 1-way direction when there is that extraction mode
