### ISSUE TITLE
Crystallizaion Chamber adds Liquid instead of using it.

### ISSUE THREAD

**Issue by DreiPixel** [PrinceOfAmber/Cyclic#1410]
Minecraft Version: 1.15.2

Forge Version: 31.1.63

Mod Version: 0.4.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Tried to use the Crystallization Chamber.
instead of using the liquid, it added the amount of liquid it needed to the tank.
needs a bit of liquid in the tank though.
seems to work with all recipes of the chamber

**Comment by Lothrazar** [comment]
oops !
