### ISSUE TITLE
Item Cable intersections cannot be disconnected

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrinceOfAmber/Cyclic#1411]
Minecraft Version: 1.15.2

Forge Version: 31.1.46

Mod Version: 1.19.14

Single Player or Server: Modpack 

I'm developing a modpack and have found Item Cable intersections cannot be disconnected. There must be a space between as in the furnaces on the left for the cables to not connect. The ones on the right always connect and cannot be configured with the Cable Wrench. It would be nice if the Cable Wrench could toggle the connection from input > output > disconnected

![Minecraft- 1 15 2 - Multiplayer (3rd-party)_028](https://user-images.githubusercontent.com/17887664/80849000-9193d880-8bd2-11ea-9ee6-61731a402cff.png)

BTW: I love your mod!

**Comment by Lothrazar** [comment]
yeah its kind of awkward how you have to left click to switch between the two modes and then right click to disconnect or add extract. disconnect should work there anyway but hmm. yeah

**Comment by Lothrazar** [comment]
on mod version 0.4.0 it seems ok
![discon](https://user-images.githubusercontent.com/621529/80868487-c8f49a80-8c4f-11ea-91f6-21cac2a1ddf6.gif)

**Comment by ClaudiusMinimus** [comment]
Thank you for your reply! I was able to do as you indicated. Without your input, I don't think I would have figured out to left-click to change modes. Is there a wiki or any online documentation for cyclic? Thanks, CM

**Comment by ClaudiusMinimus** [comment]
You posted the video while I was typing my response. LOL
Thanks for the video!

**Comment by ClaudiusMinimus** [comment]
I noticed that now that I can disconnect the cables, the items still feed to inventories that are next to the cable, but not connected. Using Cyclic-1.15.2-0.4.1
