### ISSUE TITLE
Cyclic (cyclic) encountered an error during the load_registries event phase Block{null} has property: up with invalidly named value: ınventory

### ISSUE THREAD

**Issue by ezurako13** [PrinceOfAmber/Cyclic#1413]
Minecraft Version: 1.15.2

Forge Version: 31.1.63

Mod Version: 0.4.1

Single Player

Describe problem (what you were doing; what happened; what should have happened):

Cyclic (cyclic) encountered an error during the load_registries event phase
Block{null} has property: up with invalidly named value: ınventory

Log: https://pastebin.com/Bg8E2sR6

**Comment by Lothrazar** [comment]
works as expected in 0.7.0+
