### ISSUE TITLE
Crystallization/Melting Chambers destroyed when broken with pickaxe

### ISSUE THREAD

**Issue by bessiq** [PrinceOfAmber/Cyclic#1414]
Minecraft Version: 1.15.2

Forge Version: 31.1.63

Mod Version: Cyclic-1.15.2-0.4.0.jar

Single Player or Server: server (ATM5 v1.21)

Describe problem (what you were doing; what happened; what should have happened):

The Crystallization Chamber and Melting Chamber are destroyed when breaking them. I've tried a stone pickaxe, an inferium pickaxe, and the cyclic nether pickaxe, and the chambers are destroyed regardless. Do they require silk touch or a different tool to break?

Log file link:

There were no relevant messages in the debug or latest log files, but I can still provide them if you like.

Thanks!

**Comment by AntoniSkup** [comment]
Hello, I don't know the answer to your question, but I have a problem with using the melting chamber. I'm placing honey inside, putting liquids in it but nothing is happening. Do you know how to use it?

**Comment by CritFlaw** [comment]
I'm having this issue with the magma blocks. Lava below like it used to be in 1.12, and it's receiving power

**Comment by Lothrazar** [comment]
@AntoniSkup Melting takes item and and produces fluid as output, so recipe is read left to right. then just give it power

**Comment by Lothrazar** [comment]
these blocks do not care about 'liquid in world' anymore, just use power and normal in output for fluids.  
In https://github.com/Lothrazar/Cyclic/issues/1410   https://github.com/Lothrazar/Cyclic/commit/c95bf1421b608dd528abc1dfce9555e490f3c9c4  i fixed the loot tables so mining with pickaxe gives block again

**Comment by SilasTurner** [comment]
how do you get liquids out of melting chamber

**Comment by trunksbomb** [comment]
@SilasTurner You should open a new issue instead of reviving an old, unrelated issue.
