### ISSUE TITLE
Builder crashes only client after clicking preview button

### ISSUE THREAD

**Issue by EnderMelody** [PrinceOfAmber/Cyclic#1415]
Minecraft Version: 1.12.2
Forge Version: forge-14.23.5.2847
Mod Version: Cyclic-1.12.2-1.20.2.jar
Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I was trying to figure out how to use the builder, and ended up clicking the preview button before setting any structure. The preview button had no gui other than the box even when hovering over it. Now whenever I join the server I crash. I was able to fix this by spamming setblock using the cords from crashlog while logging in, but this is not ideal.

Log file link:
Crash report: https://paste.dimdev.org/ikenasucur.mccrash

**Comment by Lothrazar** [comment]
The link to the log is broken but looking into it regardless 
![log fail](https://user-images.githubusercontent.com/621529/84608284-81744780-ae66-11ea-929d-c06b04a42a77.png)

**Comment by Lothrazar** [comment]
cant make it crash, being empty doesnt seem to matter
![1415](https://user-images.githubusercontent.com/621529/84608944-930b1e80-ae69-11ea-83b0-6a022ff17847.gif)

**Comment by EnderMelody** [comment]
I havent played in a while, but ill try to reproduce it and also find the log again when I get a chance.

**Comment by Lothrazar** [comment]
re open if it comes back
