### ISSUE TITLE
[1.15.2] offhanding experience boost book

### ISSUE THREAD

**Issue by Quu1337** [PrinceOfAmber/Cyclic#1416]
**Minecraft Version:** 
1.15.2

**Forge Version:** 
31.1.74

**Mod Version:**
 0.4.1

**Single Player or Server:** 
both, probably

**Describe problem (what you were doing; what happened; what should have happened):**
Offhanding experience boost book and veinmining grass (blocks) or dirt, gives massive amounts of exp. Attached video from player who reported it.

**Video/images/gifs (direct upload or link):** 

https://youtu.be/uEMwJJ3mAxA

**Comment by Lothrazar** [comment]
fix on the way https://github.com/Lothrazar/Cyclic/commit/3ffc67e841f7feccca70ba318ce39237d405aa99

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
