### ISSUE TITLE
Builder uses twice as many blocks as it places.

### ISSUE THREAD

**Issue by sporefreak** [PrinceOfAmber/Cyclic#1417]
Minecraft Version: 1.12.2

Forge Version: 8.0.99.99

Mod Version: 1.20.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I set up the Builder to place stone and wood around a pure daisy with Botania, (3x3, 4 high, center taken by daisy so 4 squares of 8 = 32) However it consumes 2 blocks and places one. easily noticeable when placing a stack into the builder and it consumes the whole stack.
Tested in Single player, same result.
putting in a single block at a time places them correctly, but putting a stack will consume twice as much as it should.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
