### ISSUE TITLE
Breaking the Fluid Storage Tank containing Liquid XP causes error on server world

### ISSUE THREAD

**Issue by whemmingsson** [PrinceOfAmber/Cyclic#1419]
Minecraft Version: 1.12.2

Forge Version:  14.23.5.2847

Forge Mod Loader Version: 8.0.99.99

Mod Version: 1.19.20

Single Player or Server: Server

Mod pack: Enigmatica 2

Describe problem (what you were doing; what happened; what should have happened):

Breaking the Fluid Storage Tank containing Liquid XP causes error described in the link below. 

Additional info, just in case:
* Used the XP Drain from Open Blocks to input the XP into the tank
* After breaking the tank, the block vanished visually but was still there, invisible (able to stand on it)
* After this, the server kicked me out and I'm seeing the error in the server console repeatedly, approx once a minute.
* Unable to reconnect while the entity still exists / error keeps occuring. I assumed the entity would despawn after 5 minutes (the chunk should be loaded) but that did not happen.
* _A server reboot seems to fix this temporarily, tank is back as a placed block but XP gone_. 

I've tried to replicate the error in a single player world, but here it works just fine and as expected.

Log file link:

https://pastebin.com/JpFYGPAQ

**Comment by Lothrazar** [comment]
in mod version 1.20.2 and forge server  14.23.5.2847 its working as expected, cant replicate.  openblocks 1.8.1
I can place and break over and over again with no issues
![1419](https://user-images.githubusercontent.com/621529/84611395-91922400-ae72-11ea-8a3c-539f13aab3e0.gif)
