### ISSUE TITLE
Fortune with nether ores from this pack does not work in the overworld

### ISSUE THREAD

**Issue by bs89** [PrinceOfAmber/Cyclic#142]
I've silk-touched the diamond, emerald and lapiz ores from the nethers and found out that fortune 3 does not work if i harvest these blocks in the overworld (in comparison to doing the same in the nether). The nether quartz (from vanilla) still works fine, though.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this ill check it out

**Comment by PrinceOfAmber** [comment]
I mined 16 diamond ore blocks with silk touch, brought to overworld

Using a diamond fortune III pickaxe, i got 34 diamonds.  Seems to work for me.  Which ore and which pickaxe were you using, exactly?  

What quantity of ores did you try with?

**Comment by PrinceOfAmber** [comment]
This seems to work fine with tinkers tools and enchantments.  Closing the issue.  If it happens still for you just reopen and comment with some details.
