### ISSUE TITLE
Ender Library Bug?

### ISSUE THREAD

**Issue by Rithenar** [PrinceOfAmber/Cyclic#1421]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Placing more than one stacked enchanted book into the Ender Bookshelf causes the following
1- Only one of the enchanted books is stored
2- The rest of the stack is deleted
3- A regular, un-enchanted vanilla book is returned
4- Can't interact with the 1 book stored (cannot retrtieve)
5- Breaking the bookshelf does not drop contents and erases them

Video/images/gifs (direct upload or link):  https://youtu.be/gMHAXRMs8FE

**Comment by DizzyDJW** [comment]
I am having this same bug, I don't think it was designed to allow stacked enchanted books, I have to separate the books individually, also, be careful, if you put too many stacks of books into the Ender Library, it stops accepting any at all. ~Might be a server related issue, as a restart may fix the issue.~

Edit: Restart didn't fix the issue, my Ender Library refuses to accept any more enchanted books, tried breaking and replacing and even trashed it and made a new one, seems to be more on the side of the Ender Bookshelfs and not the Library itself.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
