### ISSUE TITLE
[Feature Request] Apply fire resistence continuously for fire charm

### ISSUE THREAD

**Issue by StevenDoesStuffs** [PrinceOfAmber/Cyclic#1422]
Minecraft Version: 1.15

Forge Version: 31.1.87

Mod Version: 0.4.1

Currently, the fire charm doesn't apply until you take fire damage, and while you're in lava continuously, it'll occasionally stop applying fire resistance momentarily, at which point you get a fire tick, before it reapplies fire resistance. Would it be possible to make it so it applies all the time?

**Comment by Lothrazar** [comment]
working as intended. making fire resistance potions completely useless doesnt sound very fun
