### ISSUE TITLE
[1.12.2] Wireless Transmitter/Receiver dupe bug with CarryOn

### ISSUE THREAD

**Issue by ChromaPIE** [PrinceOfAmber/Cyclic#1423]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
Right after the Wireless Transmitter or Receiver was carried under the feature of the mod CarryOn (https://www.curseforge.com/minecraft/mc-mods/carry-on), one more Transmitter/Receiver would drop to the ground, both the one being carried and the dupe can be placed and used with no problem. However the possible problems that might be related to the redstone channels and block binding is not tested.

**Comment by Lothrazar** [comment]
I dont think this block is doing anything special with block breaking.  Best thing i guess is just blacklist this in the CarryOn list
