### ISSUE TITLE
[Suggestion] Climbing gloves model

### ISSUE THREAD

**Issue by Fateyasha** [PrinceOfAmber/Cyclic#1424]
The climbing gloves bauble should have a model shown on the hands when applied, would be really neat

Something like this from the Aether mod:
![2020-05-20_23 52 35](https://user-images.githubusercontent.com/58151507/82521701-56ac0300-9af5-11ea-8c8c-02dac772610a.png)
![2020-05-20_23 52 59](https://user-images.githubusercontent.com/58151507/82521723-60356b00-9af5-11ea-887c-47032c65b98f.png)

**Comment by Lothrazar** [comment]
If any 3d modellers or coders want to add this in a pull request, i would 100% accept this it looks great.
