### ISSUE TITLE
[Bug?] Books enchanted with Magnet can pull items

### ISSUE THREAD

**Issue by SpiderKolo** [PrinceOfAmber/Cyclic#1425]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.0

**Mod Version:** 0.4.1

**Single Player or Server:** I assume both, for me it happened on Singleplayer

**Describe problem (what you were doing; what happened; what should have happened):**
I was testing enchantments and at some point accidentally died while testing on another world.
I took items, but noticed they acted a bit weird when I touched them, so I decided to investigated.

Turns out if you hold a book in your hand, it will act as enchanted item and will pull items to you.

I think this might be a bug because if it wasn't... what would be the point of applying it to anything if all you needed to use it would be just holding the book?
Besides - Mojang a while ago fixed one of their bugs where Silk Touch book would actually let you mine some blocks (glass, leafes, grass...), so I assume enchanted books are not supposed to actually have enchantments on their own.

I didn't made screenshot of this bug happening, because it wouldn't show bug in action.
I can't record videos really on my computer...
But I hope it's easy enough to replicate.

All you have to do is to hold book with enchantment while dropped items are near you.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
