### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by SjaakBakkerYT** [PrinceOfAmber/Cyclic#1426]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2847
Mod Version: 
1.12.2-1.20.2
Single Player or Server:
single player
Describe problem (what you were doing; what happened; what should have happened):
I was creating and loading a world and vanillafix gave a a crash report

Log file link:
https://drive.google.com/open?id=1kJGDhjx_Ejxp68XTpMuTnWaf4wjFPzz5

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
