### ISSUE TITLE
Ender Library and Bookshelves Bugs and Suggestions

### ISSUE THREAD

**Issue by DizzyDJW** [PrinceOfAmber/Cyclic#1427]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2847

**Mod Version:** 1.19.18

**Single Player or Server:** Single

**Describe problem (what you were doing; what happened; what should have happened):**

Had a system setup for enchanted books to be pumped into the Ender Library, _(surrounded on all sides with Ender Bookshelves that line the walls of my Enchantments Room)_, via Cyclic's item input pipe. Was working fine for a few minutes then stopped, system got backed up. Checked to see the issue and found that I was unable to even manually place enchanted books into the Library, had to place them manually into the Shelves. Attempted to switch out Input Pipe with a Mechanical user, worked for a single book then stopped accepting enchanted books once again, now refuses to accept any at all.
I am officially stumped as I do not know how the Library or Shelves function but I do know that neither breaking and replacing the library nor crafting a new library fixes the issue, meaning it lies in the bookshelves and not the library block, or the code within the relationship between the two.

Also, sometimes, (seemingly randomly), some enchantments of the same exact kind, from the same exact mod, with the same exact NBT tags and item names, not only refuse to stack when the library was working, but also doesn't place "new" enchantments in any particular order and does so in any random open spot, making the bookshelves look incredibly disorganized.

**Other issues:**
-Using a stack of enchanted books on the Bookshelf or Library uses all of them and "places" only one, giving back a single book.

**Suggestions:**
-Ability to use an enchanted book on the Bookshelf to add multiple different enchantments to a single book. _(This would help lower the initial cost to apply the book to an object by some amount)_
-Flip side of that: Up the "tier" of the current enchantment, such as: Using an empty book on Efficiency I, then the new enchanted book on Efficiency I again will result in Efficiency II and so on until the limit is reached.
-Secondary Option: Multiple enchantments of the same type could be "toggled" to stack into higher tiers, within the bookshelves themselves, such as two tier 1 enchantments forming into a tier 2, two tier 2s would form a tier 4, etc...
-Shift+Click any spot with enchantments, while holding (insert object), to clear it out; allowing us to delete useless enchantments easier if they are full and we need the room for more.
-Adding NBT tags to the bookshelves to keep their enchantments when broken. _(Went to move them and discovered they retain zero NBT data related to the enchantments within them) Good way to delete those useless enchantments though._

**Comment by Lothrazar** [comment]
In a recent update this was changed
It makes sure you have stack size 1 when inserting

Also , as long as you mine with something like a diamond pickaxe, the itemstack keeps the data so you can place it again just like a shulker box

As for merging tier 1 to tier 2 enchantments, this is an addon i would like to look into
 
![test](https://user-images.githubusercontent.com/621529/84859161-6dc11080-b021-11ea-983b-48eb925b01e3.png)

**Comment by DizzyDJW** [comment]
Sweet! I look forward to the update and any future features.

**Comment by Lothrazar** [comment]
1.12 is feature complete. 1.16 in progress
