### ISSUE TITLE
Multijump with Bounce

### ISSUE THREAD

**Issue by Grizzlyxstrait** [PrinceOfAmber/Cyclic#1428]
Minecraft Version:  1.12

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
Upon consecutive jumps with multi-jump IV, after using the player launcher, the bounce effect it bestows is sending me **>100,000** blocks from where I started jumping. Needless to say the world does not load that fast. Not sure if the interaction is exacerbated by the slime boots I'm wearing or not, but it seems unintended. 
Edit: Tried it with a jetpack, managed to move over 1,000,000 blocks away... I guess I figured out warp speed.

Log file link:

Video/images/gifs (direct upload or link): 
https://convertio.co/download/b4dbec35801188cfc01a3d0a0cd5c8b4ccc9d5/

Not sure if the link will work, new to file conversion.

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
"technically" both things **individually** are working as intended, but the way this plays out is way to overpowered.   

will have to put in a special case for the multi jump activation to check if bounce is active, and tone it down in that case only

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
