### ISSUE TITLE
AA Knife cannot be repaired

### ISSUE THREAD

**Issue by melody-rs** [PrinceOfAmber/Cyclic#1429]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: r-151

Single Player or Server:Both

Describe problem (what you were doing; what happened; what should have happened):
I want to use an AA knife to automate bacon, but the diamond anvil won't repair it. I've tried many other items, and the only items it'll repair are vanilla ones. We can't use vanilla tools since they're disabled in the pack I'm playing so it's pretty much useless. It won't repair TC items as well. All it does is put the items in the output slot, without repairing them. Also, the energy bar always shows empty until an item is put in it.

**Comment by Lothrazar** [comment]
Yes the AA mod specifically marks this item to make the method 
   
    public boolean isRepairable()

return false.

So this is by choice and design of the AA mod to disable this.

You can Force the anvil to repair ALLL items that return false from this method with the config file 


B:ForceNonRepairable=true
