### ISSUE TITLE
Crash on destroying HV Wire from Immersive Engineering with Rainbow Cannon

### ISSUE THREAD

**Issue by NielsPilgaard** [PrinceOfAmber/Cyclic#1430]
Minecraft Version: 
- 1.12.2
Forge Version: 
- 1.12.2-14.23.5.2847

Mod Version: 
- Cyclic-1.12.2-1.19.21

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Game crash on shooting HV wire with Rainbow cannon from Cyclic

Log file link:
https://pastebin.com/q4snW7fn

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1721

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
