### ISSUE TITLE
Redstone Torch Duplication

### ISSUE THREAD

**Issue by unit285** [PrinceOfAmber/Cyclic#1431]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server: Server - minewonderland.com

Describe problem (what you were doing; what happened; what should have happened):
Right clicking cyclic cable

Log file link:

Video/images/gifs (direct upload or link):  https://youtu.be/lGfpI1SqNU8

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
In latest mod version (1.20.2) this error isnt happening.  Maybe because of an old version or a mod conflict.  or maybe some nearby block?  
Please try updating the mod and this should fix it
![1431](https://user-images.githubusercontent.com/621529/84682690-deb1dc80-aeea-11ea-89f4-c9bf87a6f327.gif)

**Comment by ghost** [comment]
I am on version 1.20.3 in 1.12.2, this only happens if you right click on the cable where a torch is

https://drive.google.com/file/d/1piw_63oRyCJD55Xo9WhH6g3K89CQJFdZ/view?usp=sharing
