### ISSUE TITLE
[1.15.2] Slime ball Dupe(ish)

### ISSUE THREAD

**Issue by koalalord9999** [PrinceOfAmber/Cyclic#1432]
Minecraft Version:  1.15.2

Forge Version: 31.1.87

Mod Version: 1.15.2-0.4.1

Single Player or Server: probably both, but server right now.

Describe problem (what you were doing; what happened; what should have happened):
I have no idea if this is intentional, but if it is, good lord does it require some complicated setup.
Via recipes in JEI I figured out a way to convert magma blocks, slime, and TONS of pipes into a infinite loop + profit of slimeballs. Hopefully the picture I linked is understandable, I am using mekanism pipes for everything.

Log file link:

Video/images/gifs (direct upload or link): 
![Inked2020-05-26_19 54 07_LI](https://user-images.githubusercontent.com/9123026/82964939-619ae380-9f8c-11ea-8c65-47252d088273.jpg)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by FreezePhoenix** [comment]
You can record the forge version by going to mod options, and typing "forge"

**Comment by koalalord9999** [comment]
Forge version is 31.1.87

**Comment by Lothrazar** [comment]
in mod version 0.7.0, and forge 31.2.36, i am able to join a server in minecraft 1.15.2 currently

**Comment by Lothrazar** [comment]
![serverrr](https://user-images.githubusercontent.com/621529/105064468-b3b7da00-5a31-11eb-8ba8-63fa42be494a.png)

**Comment by Lothrazar** [comment]
cant replicate in newer mod versions 0.7.0+.  since most modpacks are moving to minecraft 1.16 we should re test there

**Comment by koalalord9999** [comment]
Pretty sure it's fixed in 1.16, magma slime converts to magma instead of slime when melted
But with the uncrafting grinder it might still be possible to have an infinite loop

Not with default configs, as uncrafting magmaslime is blacklisted
