### ISSUE TITLE
Autonomous User Buggy Attacks

### ISSUE THREAD

**Issue by FreezePhoenix** [PrinceOfAmber/Cyclic#1433]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.2

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

The autonomous user often does not attack the entire area that is defined. Usually, it only attacks one corner of the area. This can be demonstrated by setting up a large area for it to attack, and walking into it. It does not attack some (rather large) areas.

It should attack the entire area.

**Comment by Lothrazar** [comment]
Yep , for some reason it only gets one corner and not all. this can be fixed

![2020-06-17_20 09 09](https://user-images.githubusercontent.com/621529/84973691-893a2300-b0d6-11ea-8f87-2748e0de7621.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
