### ISSUE TITLE
Workbench Duplication

### ISSUE THREAD

**Issue by DevBefell** [PrinceOfAmber/Cyclic#1436]
Minecraft Version: 1.12.2

Forge Version: 

Mod Version: 1.19.19

Single Player or Server: SinglePlayer

Describe problem (what you were doing; what happened; what should have happened):
When you open the Workbench and put a item in to craft, if the item get extracted by anything, it will leave the crafted item in the slot while requiring no item thus duplicating the items. 

Log file link:

Video/images/gifs (direct upload or link): 
https://i.postimg.cc/QM3tH5v3/2020-05-31-22-39-45.png
If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2983081
