### ISSUE TITLE
Ender Bookshelf not working in multiplayer

### ISSUE THREAD

**Issue by Anegasakii** [PrinceOfAmber/Cyclic#1438]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.2

Single Player or Server: Server (Running on my computer)

Describe problem (what you were doing; what happened; what should have happened):
I set up a wall of Ender Bookshelves in a community enchanting area. It works for me; I can put in and take out enchantments, and it not being heavily automated isn't a big deal.
Someone else logged on and wanted to use an enchantment. They can't actually interact with it. On their end, when they try, they see the counter change accordingly, but nothing actually changes [the enchantment isn't actually used up/inserted].
The enchanted book keeps its enchantment, and their mundane book stays mundane. The lack of change isn't actually seen by them until they drop the book, as the exchange leaves the slot visually empty.

Video/images/gifs (direct upload or link): https://youtu.be/uAwjfIoZG4I
(Video recorded by them)

**Comment by Lothrazar** [comment]
I cant force this to trigger with my initial testing, but this is just a small local server with 15 mods.  I think its either (A) a mod conflict interaction or (B) a server->client desync, where player 1 updates things, but player 2 doesnt see the most up to date info
![1438](https://user-images.githubusercontent.com/621529/84862034-4b31f600-b027-11ea-9ffb-2b3a1f7409cb.gif)

**Comment by Nonsanity** [comment]
This may be a related server issue:

If the owner of the block clicks with a stack of the same enchanted book, only one "count" is added to the block, but the whole stack disappears. (Haven't tested the same thing with a non-owner.)

**Comment by Lothrazar** [comment]
seems to work as intended 1.20.7
