### ISSUE TITLE
1.15.2 0.4.1 Harvester: Does not harvest Melons and Pumpkins, only harvests seeds

### ISSUE THREAD

**Issue by OfficialStamper** [PrinceOfAmber/Cyclic#1439]
Minecraft Version: 1.15.2

Forge Version: 31.2.0

Mod Version: 0.4.1

Single Player or Server: SMP, Dedicated Server

Describe problem (what you were doing; what happened; what should have happened):
Harvester only harvests melons and pumpkin seeds and does not harvest the actual crop. (Pumpkin block/Melon slice)

Log file link: N/A

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
