### ISSUE TITLE
Obsidian and Flint Shears destroy Botania flowers 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrinceOfAmber/Cyclic#1440]
Minecraft Version: 1.15.2

Forge Version: 31.2.0

Mod Version: Cyclic-1.15.2-0.4.1

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):
Obsidian and Flint Shears destroy Botania flowers. The Botania flowers should drop flowers.

**Comment by Lothrazar** [comment]
Nice, looks like they added a forge:shears tag last week so i can get this working 
Will need at least forge  v1.15.2-31.2.26 

https://github.com/MinecraftForge/MinecraftForge/pull/6765
