### ISSUE TITLE
Don't know how to use melting chamber 1.15.2

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1442]
Minecraft Version: 
1.15.2
Forge Version: 
31.2.0
Mod Version: 
0.4.1
Single Player or Server:
single player

I don't know how to use malting chamber. I put magma like jei showed me. Then I added lava to it.
I filled whole chamber and still nothing happened. Please give a tutorial or sth.

**Comment by Lothrazar** [comment]
Yeah its different than it was in 1.12 
![1442](https://user-images.githubusercontent.com/621529/85934789-f1d68c00-b89c-11ea-94ad-9d4d1452626d.gif)
