### ISSUE TITLE
1.15.2 0.4.2 Harvester: Completely harvests Sugar Cane, doesn't leave lowest block.

### ISSUE THREAD

**Issue by OfficialStamper** [PrinceOfAmber/Cyclic#1444]
Minecraft Version: 1.15.2

Forge Version: 31.2.0

Mod Version: 0.4.2

Single Player or Server: SMP, Dedicated Server

As soon as you plant a Sugar Cane block, Harvester immediately harvests it.  Need it to grow :)

**Comment by OfficialStamper** [comment]
(works if you plant 1 block down, or raise harvester one block up)

**Comment by Lothrazar** [comment]
(works if you plant 1 block down, or raise harvester one block up) yep sounds good
