### ISSUE TITLE
[Suggestion] Water Sprayer

### ISSUE THREAD

**Issue by DevBefell** [PrinceOfAmber/Cyclic#1445]
Converting concrete powder is a pain to do, the water sprayer(can be any name, maybe moisturizer)can spray water on blocks that needs water or can change when water is applied to it, such as crops. concrete powder, and if any other mods that adds these kinds of blocks.

**Comment by trunksbomb** [comment]
I think adding Concrete to the Solidifier would be a good candidate for this instead of making a new tool or block.

**Comment by Lothrazar** [comment]
Yep concrete powder already runs through the hydrator in 1.12 and and solidifier in 1.16
