### ISSUE TITLE
[Suggestion] Allow Fortune enchantment for the (Garden) Scythe

### ISSUE THREAD

**Issue by Jack-McKalling** [PrinceOfAmber/Cyclic#1446]
**Minecraft Version**: 1.12.2

**Forge Version**: 14.23.5.2838

**Mod Version**: 1.19.14

**Single Player or Server**: single

**Describe problem** (what you were doing; what happened; what should have happened):
Trying to add Fortune to the Garden Scythe doesn't work on an anvil, it appears not compatible. In creative mode it does work because that bypasses enchantment compatibility. Other modded ways of applying enchantment didn't work either (e.g. Industrial Foregoing's Enchantment Applicator).

However the scythe is a harvesting tool, and Fortune does function on harvesting crops when used on other, non-harvesting items, such as a weapon or pickaxe. In the newest version of Minecraft, even the Hoe now accepts the enchantment. The scythe should really accept it too, for consistency.

**Video/images/gifs** (direct upload or link): 
![fortune scythe](https://user-images.githubusercontent.com/14236702/85795877-47922380-b739-11ea-8513-59b0cd873f4d.jpg)

**Comment by Lothrazar** [comment]
1.12 is feature complete, aim for this in 1.16+ version

**Comment by Jack-McKalling** [comment]
I indeed intended this for the new version. I'm merely playing in 1.12.2 because of Sky Factory 4, I didn't mean to limit the suggestion to this version. Sorry for the confusion, could you please reopen and relabel?
