### ISSUE TITLE
Automated user machine generates error logs

### ISSUE THREAD

**Issue by darkvergus** [PrinceOfAmber/Cyclic#1447]
Minecraft Version: 
1.12.2

Forge Version: 
forge-14.23.5.2854

Mod Version: 
Cyclic-1.12.2-1.20.3.jar

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Using a katana created from tinkers mod using its addon plustic and using an "automated user" machine from cyclic with the katana in it, while killing silverfish it generates that error and spams it everytime a silverfish is killed.

Log file link:
https://mega.nz/file/74AzySoJ#rx5tiqxtJywmCSyCE1MIfnOK9MiXxaX05B931r5UG6o

**Comment by Lothrazar** [comment]
Pulling related errors from the logs here: 

` Automated User [interactEntities] Error 'bound must be positive'class java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_251]
	at com.sosnitzka.taiga.traits.TraitSlaughtering.onMobDrops(TraitSlaughtering.java:31) ~[TraitSlaughtering.class:?]`

...


`Exception caught during firing event net.minecraftforge.event.entity.living.LivingDropsEvent@6ca22fb1:
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_251]
	at com.sosnitzka.taiga.traits.TraitSlaughtering.onMobDrops(TraitSlaughtering.java:31) ~[TraitSlaughtering.class:?]`





The error is coming from this mod 'com.sosnitzka.taiga.traits' , sounds like they are somehow passing bad integer values, negative or zero when its not allowed.  Not sure what mod this is, but needs to be reported to their issue tracker
