### ISSUE TITLE
FPS drops when looking into the chunk that contains sprinkler

### ISSUE THREAD

**Issue by TopCraft** [PrinceOfAmber/Cyclic#1449]
Minecraft Version: 1.12.2

Forge Version: forge-14.23.5.2854

Mod Version: Cyclic-1.12.2-1.20.2.jar

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

FPS drop when I look into the chunk that contains sprinklers. I already turned of particles and no improvement at all.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

[sampler-snapshot_0.zip](https://github.com/Lothrazar/Cyclic/files/4843745/sampler-snapshot_0.zip)

(https://user-images.githubusercontent.com/34287494/85972358-9da6d700-b984-11ea-80c7-6d8fe8ea2418.png)

**Comment by Lothrazar** [comment]
wow thats a lot of sprinklers.  thanks for the snapshot too

**Comment by TopCraft** [comment]
It even lag on a Ryzen 9 3900x, 32GB of RAM and RTX 2070 :(

**Comment by Lothrazar** [comment]
removing particles and adding a config 

    #  Set false to delete - requires restart  Restart for best effects [default: true]
    B:SprinklerAnimationsAllowed=false

**Comment by Lothrazar** [comment]
B:SprinklerAnimationsAllowed=true

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547

**Comment by LameGaming** [comment]
> B:SprinklerAnimationsAllowed=true

how can i find this?
