### ISSUE TITLE
Crash when installed with p455w0rdsThings

### ISSUE THREAD

**Issue by swyrl** [PrinceOfAmber/Cyclic#145]
(leaving this here for cross-reference, not 100% sure whose side the bug is coming from)
MinecraftModDevelopment/p455w0rdsThings#19

**Comment by PrinceOfAmber** [comment]
I notice that it is a GUI from that mod breaking based on at p455w0rd.p455w0rdsthings.client.gui.GuiDankNull.func_73863_a(GuiDankNull.java:305)

Based on that, You can try to turn off the Inventory -> Terraria inventory buttons feature, or some other features in there, since they are inventory related.

**Comment by swyrl** [comment]
Yeah, just tried that and it worked. It seems the /dank/null can't render the terraria buttons properly :p 
Thanks for the prompt response!

**Comment by PrinceOfAmber** [comment]
I think i will change the default value for this config option to false. ive had other mods crash on a similar issue here as well https://github.com/PrinceOfAmber/Cyclic/issues/74

**Comment by swyrl** [comment]
Might I also recommend adding the `p455w0rd.p455w0rdsthings.client.gui.GuiDankNull` to the default blacklist?

**Comment by PrinceOfAmber** [comment]
Good idea  on the default blacklist.    Bad timing as i just pushed out build   1.7.22 https://minecraft.curseforge.com/projects/cyclic/files/2340924 .  Ill leave the ticket open to remind me to add it for version 23.  For now the feature defaults to false and hopefully it works in your config blacklist.

**Comment by PrinceOfAmber** [comment]
that guidanknull is now in default config https://minecraft.curseforge.com/projects/cyclic/files/2342114
