### ISSUE TITLE
Invulnerability with Glowing Chorus and Forgiving Void

### ISSUE THREAD

**Issue by Jack-McKalling** [PrinceOfAmber/Cyclic#1452]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.12.2-1.19.14
Forgiving Void version: 1.12.2-1.0.23
Mod pack: Sky Factory 4.1.0

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened):
Cloning #1229. When you fall into the void with Forgiving Void also installed, and under the effects of the Glowing Chorus, you will receive invulnerability that prevents you from dying (even by the `/kill` command!) or taking any form of damage.

Also posted on modpack github: DarkPacks/SkyFactory-4/issues/1511

Log file link: https://gist.github.com/Jack-McKalling/af768b4860d4096b71c31856a71c16af (includes game booting)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by sam-kirby** [comment]
Issue is resolved by updating Forgiving Void, Cyclic has no issue.

Suspect this commit is what resolved it: blay09/ForgivingVoid@a7688d20a3f89e50b192098aaf022f1f70b1577c
