### ISSUE TITLE
Pylon "drain all" xp dupe

### ISSUE THREAD

**Issue by Foreck1** [PrinceOfAmber/Cyclic#1453]
**Minecraft Version**: 1.12

**Forge Version**: latest

**Mod Version**: 14.23.5.2854

**Single Player or Server**: server

**Describe problem (what you were doing; what happened; what should have happened):**

I'm posting this on behalf of a player of [Rebirth of the Night](https://www.curseforge.com/minecraft/modpacks/rebirth-of-the-night) (modpack), it appears that pressing drain all xp when there's none stored in the pylon will give an absurd amount of levels back

**image**

![image](https://user-images.githubusercontent.com/47757429/87174786-b200a300-c2a5-11ea-9cf5-41b44b72f3c9.png)

I'll keep you posted on any new info we get, thanks.

**Comment by Lothrazar** [comment]
im going to change this to the way i do it in 1.15/1.16 kinda. just ill remove the buttons, player can crouch on top to drain into it like an xp grate.  remove the normal way, with bottles or spewing the orbs out etc. This is not the first bug reported with these buttons

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1328

https://github.com/Lothrazar/Cyclic/issues/860

https://github.com/Lothrazar/Cyclic/issues/573

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
