### ISSUE TITLE
1.16.1

### ISSUE THREAD

**Issue by closeshot** [PrinceOfAmber/Cyclic#1458]
Minecraft Version: 1.16.1

Forge Version: 32.0.70

Mod Version: 0.6.1

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

Game crashes upon loading world and also creating a new world.

Log file link:

https://pastebin.com/ZEiy6ed0

**Comment by Lothrazar** [comment]
Caused by a mod called ' **_oresAboveDiamonds_**


as shown here in your log  oresAboveDiamonds.events.ServerStartEventHandler.onServerStart(ServerStartEventHandler.java:14) ~[?:1.0] {re:classloading}
