### ISSUE TITLE
[1.12.2] Stunned Potion Effect has missing texture

### ISSUE THREAD

**Issue by SandwichHorror** [PrinceOfAmber/Cyclic#1459]
Minecraft Version: 1.12.2

Forge Version: last stable 1.12.2

Mod Version: 1.12.2-1.20.3

Single Player or Server: Single player (likely both)

This seems to be an unimplemented feature, but when afflicted by the "Stunned" potion effect, the player inventory displays the classic checkered purple and black square in place of a proper potion effect icon.

Is it possible to have even a placeholder texture assigned to this effect so it might be used in modpacks?

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
