### ISSUE TITLE
Experience Pylon not working in Enigmatica 5

### ISSUE THREAD

**Issue by zachsai** [PrinceOfAmber/Cyclic#1460]
Minecraft Version: 1.15.2

Forge Version: 

Mod Version: 

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):

The experience from the xp pylon cannot be collected. It can be transferred to tank, but then no way to collect from tanks
bottles are not working, sugar is not working

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by themonsterstorm** [comment]
I am having this exact same issue although it is not from Enigmatica 5 modpack.

**Comment by Lothrazar** [comment]
Yes, this was upgraded, if you look for uses of exp fluid you can craft them in this machine
a
![1460](https://user-images.githubusercontent.com/621529/90912962-5b9c7f00-e390-11ea-9079-b4d71f49e662.png)
![1460 2](https://user-images.githubusercontent.com/621529/90912965-5c351580-e390-11ea-82a2-7b444e2a0819.png)
