### ISSUE TITLE
torch launcher broken on 1.16.1 ?

### ISSUE THREAD

**Issue by darkpainn123** [PrinceOfAmber/Cyclic#1461]
Minecraft Version: 1.16.1

Forge Version: 32.0.97 , tried other versions didnt fix

Mod Version: Cyclic-1.16.1-0.6.1.jar

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened): so the torch launcher is broken on 1.16.1 when im trying to throw it, it will throw to the sky instead of the position i want , tried the 1.15.2 version of the mod on a 1.15.2 and works , so seems like is broken on 1.16.1

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
yeah, looks like its not spawning or shooting in the right angle at all. if you go in F5 mode it kind of works, ill get a fix out
