### ISSUE TITLE
Using an unconfigured Pattern Replicator crashes client and breaks world

### ISSUE THREAD

**Issue by Frikkle** [PrinceOfAmber/Cyclic#1463]
Minecraft Version: 
`1.12.2`

Forge Version: 
`forge-14.23.5.2847`

Mod Version: 
`Cyclic-1.12.2-1.20.2.jar`

Single Player or Server:
Single Player

Describe problem (what you were doing; what happened; what should have happened):
I placed down a Pattern Replicator, in a completely fresh world, opened the GUI and clicked the blank unmarked button, as shown in the image below. The world crashes with the linked log and the world does not start up afterwards anymore.

I traced the stacktrace in the code and the issue is most likely being caused by the `getCenterSource()` function. When clicking the button in the unconfigured machine, bot GPS targets A and B are `null`, causing a series of function calls on `null` to be performed.

https://github.com/Lothrazar/Cyclic/blob/5ecb690fbfd1423945a398b343a0959bfab7849c/src/main/java/com/lothrazar/cyclicmagic/block/builderpattern/TileEntityPatternBuilder.java#L237-L244)

Link to the original issue: 
https://github.com/NillerMedDild/Enigmatica2Expert/issues/1783

Log file link:
https://pastebin.com/7cq6mBVy

Video/images/gifs (direct upload or link): 
![2020-08-01_09 41 30](https://user-images.githubusercontent.com/9324165/89097377-b28ce500-d3de-11ea-8ab6-01ef38e138f3.png)

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1462

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
