### ISSUE TITLE
Minecraft 1.6.1 Frost Bringer and other projectiles based weapons don't seem to be working correctly

### ISSUE THREAD

**Issue by bzhang19** [PrinceOfAmber/Cyclic#1464]
Minecraft Version: 
1.6.1
Forge Version: 
forge-1.16.1-32.0.97
Mod Version: 
Cyclic-1.16.1-0.6.1
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Frost Bringer, lighting, fire staff aren't working as intended. After right clicking, there is a SFX and no VFX nor there isn't any damage being applied. 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
yeah, looks like its not spawning or shooting in the right angle at all. if you go in F5 mode it kind of works, ill get a fix out

**Comment by bzhang19** [comment]
Thank you so much!!:)
