### ISSUE TITLE
Crashed when using text projector

### ISSUE THREAD

**Issue by TheRealKamisama** [PrinceOfAmber/Cyclic#1465]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2854

Mod Version: 
Cyclic-1.12.2-1.20.4

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
I was using the text projector in a server. When I changed the Blockoffset bar rapidly and the server crashed.
This problem was reproduced several times, so it seems like it is not a random bug or something.
The problem can **ONLY** be reproduced when running on **SERVER**.
I failed to capture a gif when the problem occured, sorry for that.

Crashreport(server):
https://paste.ubuntu.com/p/8Mh6stCszQ/

**Comment by Lothrazar** [comment]
i dont see any crash in that link, is this the full log? I just see this and then it ends, and it doesnt download either


`                       * wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.12.97.jar
                       * wft|api (1.0.4) from WirelessFluidTerminal-1.12.2-1.0.4.jar
                       * wit|api (1.0.2) from WirelessInterfaceTerminal-1.12.2-1.0.2.jar
                       * wpt|api (1.0.3) from WirelessPatternTerminal-1.12.2-1.0.3.jar
  AE2 Integration: IC2:OFF, RC:ON, MFR:OFF, Waila:OFF, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Player Count: 12 / 40; [EntityPlayerMP['Hoshimiya_Tokine'/9433510, l='world', x=384.25, y=71.37, z=379.11], EntityPlayerMP['Sakitam_Ins'/13766261, l='world', x=-869.76, y=128.00, z=822.48], EntityPlayerMP['YaoerWu'/10365999, l='world', x=573.78, y=120.00, z=1480.62], EntityPlayerMP['amunesia'/14838963, l='world', x=-245.57, y=69.00, z=1270.51], EntityPlayerMP['TheRealKamisama'/14842016, l='world', x=572.92, y=70.00, z=1538.16], EntityPlayerMP['Prunoideae'/15167277, l='world', x=529.61, y=65.33, z=1434.52], EntityPlayerMP['NekoparaString'/15182707, l='world', x=-278.84, y=71.49, z=1226.05], EntityPlayerMP['780712'/14756264, l='world', x=545.84, y=120.66, z=1486.57], EntityPlayerMP['DimensionMage'/15268239, l='world', x=588.13, y=74.00, z=1526.62], EntityPlayerMP['Jonaiyoo'/12989279, l='world', x=1085.04, y=61.37, z=802.85], EntityPlayerMP['YoungGT'/15362983, l='world', x=542.70, y=64.00, z=1460.82], EntityPlayerMP['Sky'/14464362, l='world', x=551.39, y=63.00, z=1470.02]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)`

**Comment by Lothrazar** [comment]
I tried spamming it on a local server, both arrow keys and mouse 
![1465](https://user-images.githubusercontent.com/621529/90983048-26bf3200-e520-11ea-8d01-4a90e3a18251.gif)

**Comment by Lothrazar** [comment]
closed due to:
- no response
- log does not indicate this mod at all
- cannot replicate on my server

Open an issue if you get more detail
