### ISSUE TITLE
Disenchanter doesn't work

### ISSUE THREAD

**Issue by TheStarfishMan** [PrinceOfAmber/Cyclic#1466]
Minecraft Version: 
1.16
Forge Version: 
32.0.98
Mod Version: 
0.6.1
Single Player or Server:
Single Player
Describe the problem (what you were doing; what happened; what should have happened):

It doesn't work with my Netherite Sword with like a billion enchants. Yes I put a book.

**Comment by Lothrazar** [comment]
Now when you say "doesn't work", what does that even mean? Did you have enough power? Was it turned on?  Please elaborate.  I recorded a video of me doing it.

![1466](https://user-images.githubusercontent.com/621529/90946113-b2c94080-e3de-11ea-9760-37da411dd526.gif)

**Comment by Zignomitos** [comment]
How does the disenchanter even works?

I can maybe help or something but I dont even know how to turn the thing on.

**Comment by Lothrazar** [comment]
Did you watch the video thats right there where i turned it on? ill make another one :) the button in the top left has tooltips. also it needs power if you look at the right side that bar is RF energy

![1466](https://user-images.githubusercontent.com/621529/92855143-ceed4b80-f3a6-11ea-94b9-e804f62938d6.gif)

**Comment by ghost** [comment]
It doesn't work for me... it's on and everything is right but still doesn't work
