### ISSUE TITLE
Infinity Fluid

### ISSUE THREAD

**Issue by Richard969** [PrinceOfAmber/Cyclic#1467]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.4

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):I‘ve placed two fluid pumps near a liquid,
and i have infinity fluid.

Log file link:

Video/images/gifs (direct upload or link): 

![2020-08-10_12 43 18](https://user-images.githubusercontent.com/62456622/89752513-4fe6c800-db07-11ea-9440-291b31434439.gif)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Richard969** [comment]
place a fluid near the pump,just wait the fluid flow to the pump to make a infinity fluid.

**Comment by Lothrazar** [comment]
by "pump" which block to you mean exactly.  Screenshot shows cables so.. .The fluid extraction cable? 

This is what happens for me, it grabs just one bucket and doesnt like. refill or anything? 
![1467](https://user-images.githubusercontent.com/621529/90990411-1033cd80-e556-11ea-9d6e-cea9e8c5aaae.gif)

**Comment by Richard969** [comment]
Hmm,May you can put fluid on other side to replicate it.

**Comment by Lothrazar** [comment]
tested again. nothing changed since  1.20.4 to current  1.20.6 in this area. still works as intended in isolation, modpack must have something making infinity lava, so it respawns like water. even in lava ocean. same as gif
