### ISSUE TITLE
1.12.2 Merchant Almanac

### ISSUE THREAD

**Issue by greel70** [PrinceOfAmber/Cyclic#1468]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: Cyclic-1.12.2-1.20.3.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
When using the merchant almanac on a villager, shift-right clicking a stack-able item duplicates the item in the player's inventory.

The UI is also bugged when using auto UI scaling so I can't tell you the intended use for the almanac. 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
