### ISSUE TITLE
question - Uncrafting in 1.16?

### ISSUE THREAD

**Issue by PurpleHel** [PrinceOfAmber/Cyclic#1469]
Is cyclic on 1.16 going to have the uncrafting grinder at some point? Cos the lack of any mods that uncraft is keeping me on 1.12.2. So it'd be super awesome if a mod I already love like cyclic were to be the thing that had uncrafting and let me move to 1.16!

**Comment by prodigyrick** [comment]
Its broken, It just keps duping duplicates of the uncrafted item in the window. I  broke the machine and it dropped all the dupes. at one point I had 10 diamond chest armor pieces for one iron chest. same with weapons, etc

**Comment by PurpleHel** [comment]
> Its broken, It just keps duping duplicates of the uncrafted item in the window. I broke the machine and it dropped all the dupes. at one point I had 10 diamond chest armor pieces for one iron chest. same with weapons, etc

You should probably make a separate issue, the dev closed this one.
