### ISSUE TITLE
Request: Setting cyclic ores with proper tool/mining levels.

### ISSUE THREAD

**Issue by Kaisoul** [PrinceOfAmber/Cyclic#147]
I have an issue with your ores now to explain the issue in detail my pick axe is a tinkers construct pickaxe made with  paper head,paper binding/knightslime handle with 5 reinforced plates added & a obsidian sharpening kit added to the tool.

So the tool will mine Cobalt level ores and will mine ores faster if the tool is a higher minging level then the ore in question.

Your ores are not either requiring a pickaxe to mine or they don't have a min mining level set so mining each one of your ores is like mining obsidian...

was wondering if this can be corrected in a future update?

**Comment by PrinceOfAmber** [comment]
Yeah, they should require a pickaxe.  This is a bug, the diamond nether and end ores should have the exact same mining requirements as vanilla diamond ore, and the same with other ores.

**Comment by PrinceOfAmber** [comment]
Just a note to myself, i confirmed that nether diamond ore can be mined & harvested with a wood pick so the release this weekend will deal with that.

**Comment by PrinceOfAmber** [comment]
Fixed mining levels for all ores. so for example now the diamond end and nether ores act same as vanilla, cannot be harvested with wood and stone tools https://minecraft.curseforge.com/projects/cyclic/files/2342114
