### ISSUE TITLE
[1.12.2] Crash with Just a Few Fish

### ISSUE THREAD

**Issue by mxnmnm** [PrinceOfAmber/Cyclic#1470]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.4

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
I broke a chance cube that started spawning stupid amounts of potion effects everywhere and then I crashed after a salmon from just a few fish got the effect.

Log file link: https://gist.github.com/mxnmnm/95f5c1e75180402630b7c96883373df3

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
