### ISSUE TITLE
Cyclic Fluid Node Transfer Rate does not change with GUI

### ISSUE THREAD

**Issue by bukschr** [PrinceOfAmber/Cyclic#1472]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

The fluid transfer rate is stuck at 500mB no matter what the GUI is set to. I was using FTB Interactions to check, and a steam boiler was outputting the correct amount of steam , but the fluid transfer node was only transfering at 500mB per GPS slot max.

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547

**Comment by bukschr** [comment]
Thank you so much!
