### ISSUE TITLE
( 1.15.2 ) Building Scepter causes screen to go blank with Optifine

### ISSUE THREAD

**Issue by amccarn** [PrinceOfAmber/Cyclic#1473]
Minecraft Version:  1.15.2

Forge Version: 31.2.36

Mod Version: Cyclic-1.15.2-0.6.1.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

When trying to use the building scepter (Fill), the preview of placement causes the screen to go blank. However I do know this is an issue with shaders/optifine because when I turn off shaders, it works fine. My question is, is there a way to turn off the placement preview which seems to be causing the issue? Also I will add that everything worked fine with optifine pre.18 but now with pre.30 it seems to be having this issue. 

Thanks!

**Comment by Lothrazar** [comment]
nothing is ever compatible with optifine. I can try to check it out

**Comment by amccarn** [comment]
Just out of curiosity, is there a way to disable or take out the transparent previews that the scepter shows? When using just optifine, everything works but when you use shaders, thats when the problem happens. Just wondering if there was a way to disable those to see if that works?

**Comment by Lothrazar** [comment]
works ok in 1.16. in 1.15 idk just disable optifine for a while if you need to
