### ISSUE TITLE
[1.16.1] Cyclic HP issues with Project MMO

### ISSUE THREAD

**Issue by ZeWolfTah** [PrinceOfAmber/Cyclic#1474]
Minecraft Version: 1.16.1

Forge Version: forge-1.16.1-32.0.108

Mod Version: Cyclic-1.16.1-0.6.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Upon dying, player's max hp increases by 1 heart with each death. Players should keep the same amount of max hp when respawning instead of it increasing each death. This seems to be a compatibility issue between Project MMO and Cyclic. Project MMO adds extra hearts to players with endurance levels, and it appears there's a weird interaction occurring when the two mods are both trying to handle extra hearts on respawn, specifically when the player has at least 1 extra heart from PMMO.

I have reached out to the PMMO team about this issue and they helped me figure out it wasn't just on PMMO's side, but rather a compatibility issue. I have tried removing mods one at a time from a backup of the server, and when Cyclic is removed, all the excess bonus hearts are removed upon the next respawn and the issue is resolved. I have attached a picture of a reply I got on how PMMO is handling the extra hearts in case it's useful.

![4fca037e6ffd9d223b3c5aad529ec969](https://user-images.githubusercontent.com/27912891/90952515-fccf1800-e418-11ea-948f-3bee9d04f7aa.png)

**Comment by ZeWolfTah** [comment]
To add more information:
-The issue still occurs in singleplayer
-The issue occurs with only Cyclic-1.16.1-0.6.1 and Project MMO-1.16-3.15.2 in the mods folder
-The steps to reproduce this bug are:
1) Create a new world with OP/Cheats
2) Make sure you're in survival
3) Use the command /pmmo admin [PlayerName] add endurance level 10 (This grants 1 bonus heart)
4) Use the command /kill (To die)

**Comment by ZeWolfTah** [comment]
If I had to guess, I'd say that Cyclic is likely looking at how many bonus hearts a player had before they died so it can reapply them after death, so when the player comes back to life after dying, PMMO adds their bonus hearts, then Cyclic adds the total previous bonus hearts, and the result is now Max HP = Base HP + PMMO Bonus + Previous Bonus.

If this is the case, a potential solution may be to have Cyclic track bonus hearts from heart containers used and reapplying that after death rather than having it reapply all bonus hearts including those not given by Cyclic. I figure having it reapply all bonus hearts, even those not given by Cyclic itself, will likely cause issues with any other mod adding bonus hearts in a similar way.

**Comment by trunksbomb** [comment]
Issue is still present in 1.16.3 and fixed by my PR above.

I haven't checked, but I believe a tangential issue still exists for the toxic heart. Not sure if the negative health modifier from those are supposed to persist through death.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113
