### ISSUE TITLE
[Request] Option to disable Energy

### ISSUE THREAD

**Issue by accessdenied0** [PrinceOfAmber/Cyclic#1475]
Minecraft Version: 1.12.x or 1.15.x

Hello Lothrazar,

I'm planning to make a very Vanilla based mod-pack. I really like your mod and want to include it, but the I find the concept of the energy production/consume not so good in my pack... 

I wanted to ask if you could make an option to entirely disable the Energy-system of your mod? In the past every Machine used Coal or other burnables to generate Energy, that would be an alternative, too... but I think you removed it for a reason and I can't expect you to re-add that feature because of the work...

But in general it would be great to disable the energy system...

**Comment by Lothrazar** [comment]
in both 1.12 and 1.16 it is currently possible to set energy levels to zero for a machine and they still run. 
 in 1.12 it is under
 fuelcost { 
section
in 1.16 it is in
[cyclic.energy.cost]
section

i need to double check some of the visual GU screens in 1.12 to make sure it also hides the red bar, but they still run

**Comment by b0hle** [comment]
> in both 1.12 and 1.16 it is currently possible to set energy levels to zero for a machine and they still run. in 1.12 it is under fuelcost { section in 1.16 it is in [cyclic.energy.cost] section
> 
> i need to double check some of the visual GU screens in 1.12 to make sure it also hides the red bar, but they still run

Where is this config? I have looked and I cannot find it on 1.12.2
