### ISSUE TITLE
1.15.2 - Cyclic blocks randomly disappear when broken

### ISSUE THREAD

**Issue by oemupenn** [PrinceOfAmber/Cyclic#1476]
Minecraft Version: 1.15.2

Forge Version: 31.2.36

Mod Version: 1.15.2-0.6.2

Single Player or Server: Single player & LAN mode

Describe problem (what you were doing; what happened; what should have happened):

Cyclic blocks will randomly disappear when broken, Reinforced Storage, Fluid Tanks, and the Fluid Collector so far. Possibly only while a Sack of Holding is in the hot bar (not being used on these blocks though.)

This does not seem to affect vanilla blocks or other mods in my experience during the same game.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Can't replicate on 1.15.2-0.7.0 (appears that nothing related to these blocks or classes they inherit changed between 0.6.2 and 0.7.0).

Tried placing and breaking a stack of 64 crates (reinforced storage) and 64 tanks 3x -- without sack, with empty sack, with filled sack. Received 64x of each all three times.

Can confirm that there's a different issue (at least in my dev environments for 1.15 and 1.16) where Fluid Collectors break instantly and where right clicking the Fluid Collector causes a crash.

**Comment by Lothrazar** [comment]
yep collector_fluid was missing loot table, adding to 1.15
