### ISSUE TITLE
Disenchanting Table crash (Forge 33.0.22+ not compatible)

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1477]
Minecraft Version: 1.16.2

Forge Version: 33.0.22+

Mod Version: 0.6.2

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

Interacting with the disenchanting table crashes the game.  Let me make this easier for you as I already know the issue

Your code is trying to gather data from LazyOptional.  This function was changed as of Forge 33.0.22 and up and no longer returns the same value.  All of your crafting-table like block entities need to be changed to fit the newest forge.  Visit forge's changelog for details.  This should be a very quick and easy fix.

Log file link:

(not required, the function is easy to find in your Disenchantment table object code)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Yep, version 0.7.0 fixes this. Should have at least forge 33.0.59  https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3054309
![1477](https://user-images.githubusercontent.com/621529/93301564-7e625d80-f7ad-11ea-92ae-938f79b4d225.gif)
