### ISSUE TITLE
[1.16.2] Exception in server tick loop

### ISSUE THREAD

**Issue by VoiidInVaiin** [PrinceOfAmber/Cyclic#1479]
Minecraft Version:  1.16.2

Forge Version: 33.0.37

Mod Version: Cyclic-1.16.2-0.6.2.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Tried to use harvester (first cyclic item crafted)

Log file link: https://pastebin.com/bS8QecKq

**Comment by Lothrazar** [comment]
Should be fixed in 0.7.0 release
