### ISSUE TITLE
pattern replicator crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [PrinceOfAmber/Cyclic#1480]
Minecraft Version: 

Forge Version: forge-14.23.5.2854

Mod Version:Cyclic-1.12.2-1.20.5.jar 

Single Player or Server:
single player

Describe problem (what you were doing; what happened; what should have happened):
 tried to copy a region with gps and when puting the second one into the slots of the replictor for source it crashed

Log file link:
https://pastebin.com/zABLjMgH

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3074579
