### ISSUE TITLE
 Problem logging on to the server

### ISSUE THREAD

**Issue by Fortleyz** [PrinceOfAmber/Cyclic#1481]
Minecraft Version: 1.16.2

Forge Version:1.16.2-forge-33.0.41 

Mod Version: Cyclic 0.6.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

My friends and I downloaded Cyclic and can't go to the same world together, although the ping is normal and without Cyclic everything was fine, please help solve the problem.

Log file link:

[crash-2020-09-09_16.01.31-client.txt](https://github.com/Lothrazar/Cyclic/files/5195328/crash-2020-09-09_16.01.31-client.txt)

**Comment by Lothrazar** [comment]
Yep, fixed in latest release 0.7.0 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3054309
