### ISSUE TITLE
Spawner Seeker not working - eye stands still and doesn't vanish on server start

### ISSUE THREAD

**Issue by Mingu2209** [PrinceOfAmber/Cyclic#1482]
Copying an old issue that's happening in version 1.16.1. Command offered not working.

Minecraft version & Mod Version: 1.16.1 & 0.6.1
Single player or Server: Server
Describe problem (what you were doing / what happened): When using the Spawner Seeker, the purple 'projectile' stays in place, and doesn't move. The projectile stays at the same location for a long time, and restarting the server doesn't clean up all the purple eyes.
Crash log (if any): No crashes.

I'm running a further modded Valhelsia 3 modpack on Forge 32.0.108.
Let me know if there's any tips for cleaning up the purple eyes that are hovering on my base! 

Please, I need some help since I can't delete it and I don't have a real updated backup.

Thanks!

**Comment by Lothrazar** [comment]
Yep, this issue was fixed in the newer 1.16 releases https://github.com/Lothrazar/Cyclic/issues/1464 , 0.6.2+

**Comment by Mingu2209** [comment]
Hi, thanks for your message, but I can't see a version for 1.16.1. Will it be available soon?
