### ISSUE TITLE
Solidifier crash

### ISSUE THREAD

**Issue by IamStig** [PrinceOfAmber/Cyclic#1483]
Minecraft Version: 1.16.2

Forge Version: 33.0.61

Mod Version: 0.6.2

Single Player or Server:Single

Describe problem (what you were doing; what happened; what should have happened): 
Crafted Solidifier, placed it, Crashed. 
Restarted and click on solidifier ...Crashed

Log file link: https://pastebin.com/xt5VbW1F

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
I was just fixing this area in version 0.7.0  , works in both client and server which was just released.  Thanks for the report

**Comment by IamStig** [comment]
Not problem. Thanks for you work
