### ISSUE TITLE
stun and swimspeed potions can be brewed from any potion (and not just awkward potions)

### ISSUE THREAD

**Issue by vemerion** [PrinceOfAmber/Cyclic#1484]
Minecraft Version: 1.16.3 and 1.15.2, I have not checked the other versions

Forge Version: 1.16.3-34.0.7

Mod Version: As of commit 95dc63230167ad97ce4856476eee1d2b15a2ba1f this bug still exists

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Both potions that this mod adds (stun and swimspeed) can be brewed from every potion, and not only from awkward potions. This occurs because of how the Ingredient class works (it disregards NBT completely).

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113
