### ISSUE TITLE
boomerang shouldn't brack Reinforced glass form SecurityCraft

### ISSUE THREAD

**Issue by leonpano2006** [PrinceOfAmber/Cyclic#1486]
Minecraft Version: 1.12.2

Forge Version: 2854

Mod Version: 1.1.3

Single Player or Server:server

Describe problem (what you were doing; what happened; what should have happened):
boomerang should check for player relative hardness because of modded undestructible blocks
ex. reinforced glass form SecurityCraft

Log file link:

Video/images/gifs (direct upload or link): 
https://streamable.com/2cve4z
If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
The boomerang was changed to not break blocks at all in commit adea8cdd1c41af661dd4e2fff1aef19fa8cef9fe but it was not backported to the 1.12 branch. It's up to @Lothrazar if he wants to backport it and release an update for 1.12.

**Comment by Lothrazar** [comment]
Yep 1.12 is still supported, so hopefully this week should be a small fix.


EDIT: looks like in 1.12 its harvesting blocks, and in modern versions it just doesnt touch or break anything.

To avoid making hard breaking changes in 1.12, ill add one or more new  config-file values to better control this feature.  I hvae securitycraft installed indev to test block hardness and other things

**Comment by Lothrazar** [comment]
Also even if the config is true, and boomerang breaks blocks like it did before, it still wont break this reinforced block so i have that fix as well

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3074579
