### ISSUE TITLE
Monster Ball doesn't seem to work

### ISSUE THREAD

**Issue by Rithenar** [PrinceOfAmber/Cyclic#1488]
Minecraft Version: 1.16.3

Forge Version: 34.1.0

Mod Version: 1.16.3-0.7.1

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened): First time trying to use the Monster Ball. If I right-click it to throw it I see a small animation as it is being thrown but it doesn't capture any animals. If I hold right-click and then release the monster ball disappears without catching the animal either. Tried also just dropping it and it doesn't do anything of course.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Found the issue, which you can see in third person camera mode when you throw a monster ball.

The direction in which the monster ball is shot is incorrect in the code, so it just shoots directly up above your head. You should find your monster ball after a few seconds on the ground somewhere around you.

I'm working on a PR that resolves this issue right now.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113

**Comment by jmmd2000** [comment]
> https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113

I'm having this same issue in a 1.16.1 custom modpack, any way to get a fix without having to update every other mod because of a version change?
