### ISSUE TITLE
Experience Pylon missing buttons

### ISSUE THREAD

**Issue by mrdeadlocked** [PrinceOfAmber/Cyclic#1489]
Minecraft Version: 1.15.2

Forge Version: 1.15.2-31.2.43

Mod Version: Cyclic-1.15.2-0.7.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Experience Pylon has no button to be able to store/retrieve exp.

Modpack: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2

Log file link:

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/461352/94559915-ec883500-022f-11eb-8617-70404dad2262.png)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Looking at the code, the Experience Pylon is not meant to have other buttons in the GUI.

Its current functions are: 

1. Extract experience from a player crouching on top of it
2. Gather experience orbs in a radius around the pylon

You can also pump experience into and out of the pylon.

From what I can tell, there's meant to be a feature that allows you to right click the pylon with sugar to get an "Experience Confection" but I can't tell where that's coded (ie I don't think it's been implemented yet). @Lothrazar can correct me on that if I'm wrong.

**Comment by trunksbomb** [comment]
My PR addresses the issue in 1.16, but should be a simple copy paste to fix it in 1.15 as well.

**Comment by choekstr** [comment]
Not sure if your PR was accepted and included in the 1.16.4-0.9.3 release @trunksbomb but there are no buttons still in the pylon and the sneak on top of the pylon doesn't seem to work either.  I think you were referring to the sugar to get confection however.

I can't actually find a way to extra player experience into the pylon; I have not tested pumping XP into or out of the pylon however as getting it out of the player is the impossible task right now and what we loved about the XP pylon in the past. :(

**Comment by trunksbomb** [comment]
The PR was merged but as I mentioned in my first reply, the GUI wasn't meant to have any new buttons so I haven't added any. I don't think Lothrazar added any either.

Sneaking on top of the pylon only works if you toggle the redstone button in the GUI but this one is suffering from a similar bug that others had where the GUI doesn't update properly when you click on the Redstone control button. I just confirmed in 1.16.4-0.9.3.

![cyclic_exppylon](https://user-images.githubusercontent.com/1904331/100520867-447ae380-316e-11eb-995c-7d44b88f5c51.gif)

**Comment by Lothrazar** [comment]
Yeah, the buttons caused non stop complaints and bugs and EXP desyncronization on servers in 1.12. 

Instead, in 1.16+ you can pipe it to a solidifier to either
- turn it into the Experience Confection, and eat that very fast, 

or bottle it into the vanilla ones to dump orbs into the world (good for mending)

And as above, sneaking above it to deposit.

**Comment by Lothrazar** [comment]
Actualy, the redstone button is used to block it from collecting orbs in the world on the ground, so ill keep that but default it to "on"

And the feature for sneaking players will in future ignore that toggle. (also 1.14/1.15 are retired, all changes being applied to 1.16)
