### ISSUE TITLE
Gradle task setupDecompWorkspace no longer exists as of MC Version 1.13.x+

### ISSUE THREAD

**Issue by trunksbomb** [PrinceOfAmber/Cyclic#1491]
Minecraft Version: 1.13.x+

Describe problem (what you were doing; what happened; what should have happened):

I'm setting up Cyclic in IntelliJ IDEA. Following instructions in README.md, I'm instructed to run `gradlew setupDecompWorkspace eclipse`. Attempting to run that command in the root directory of the Cyclic project tells me that `setupDecompWorkspace` does not exist .

According to a post on the [Forge forums](https://forums.minecraftforge.net/topic/68778-setupdecompworkspace-not-found/), the `setupDecompWorkspace` task no longer exists as of Minecraft version 1.13.x due to extensive rewrites to ForgeGradle.

Also according to that post, all I should have to do is import the `build.gradle` file into my IDE.

I've confirmed that just importing build.gradle is enough to get the workspace setup complete in IntelliJ IDEA.

Log:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupDecompWorkspace' not found in root project 'Cyclic1.16'.```

**Comment by Lothrazar** [comment]
aha good catch.  Ill update the readme.  i havent converted to IJ yet and still use eclipse so i threw it in a bash script https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/scripts/setup.sh#L3

TODO: port these to 1.15 branch
