### ISSUE TITLE
[1.16.3] User keeps getting a new fake user uuid each restart

### ISSUE THREAD

**Issue by WhitePhant0m** [PrinceOfAmber/Cyclic#1495]
Minecraft Version: 1.16.3

Forge Version: 34.1.1

Mod Version: Cyclic-1.16.3-0.7.1.jar

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
Joined the server, noticed my user wasn't doing anything, went to check my allies from FTB Chunks, noticed that there were multiple users.
I expected it to keep its fake player uuid

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/33400200/95003939-86affa80-05ed-11eb-9421-e50f84e691c5.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113
