### ISSUE TITLE
Update Projects/Todo

### ISSUE THREAD

**Issue by trunksbomb** [PrinceOfAmber/Cyclic#1500]
Not an "issue" really, but I'm interested in contributing more to this mod. I looked at your Projects and both seem like they've got a lot of ideas that are already implemented, or that were implemented and then removed (doorbell, auto-smelt enchantment).

If you've got some time, do you mind sharing some things that I might be able to help out with? If you've got Discord we could chat on there since Github issues isn't really the place to have this sort of conversation lol.

I've got the "throw ender pearl on sword swing" enchantment made, for example (https://github.com/trunksbomb/Cyclic/tree/trunk/1.16_enchantments).

**Comment by Lothrazar** [comment]
Honestly there is a TON of stuff in 1.12 that hasnt yet been ported into 1.16+ yet and id love some help.  you are correct that its very out of date.  Yeah the pearl sword sounds awesome 



This one still is currently the "stuff that needs to be ported out of 1.12 into 1.16", ill start cleaning this up  tonight https://github.com/Lothrazar/Cyclic/projects/4    , its close to accurate

This one https://github.com/Lothrazar/Cyclic/projects/1 i was using when 1.12 was the newest MC version, just ideas for stuff to add  . I should retire it and move any of the good ideas into a new column in board /4

My discord user id is Lothrazar#7738  , closing so we can continue there (if i dont respond im sleeping or at work)
