### ISSUE TITLE
Datapack recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [PrinceOfAmber/Cyclic#1501]
Minecraft Version: 1.15 1.16

you can add datapack recipe for cyclic ? 

with datapack recipe is more easy change or add recipe with custom datapack

**Comment by Lothrazar** [comment]
Yes all recipes are currently already using the data pack system.

So if you make a data pack, then in the resources/data folder create the cyclic/recipes folder, and copy any of these you want and then edit them

https://github.com/Lothrazar/Cyclic/tree/trunk/1.16/src/main/resources/data/cyclic/recipes

**Comment by AlleCraft-alterego** [comment]
oh, sorry I didn't see the recipes, couldn't they differentiate by processes in folders? it would be cleaner

**Comment by Lothrazar** [comment]
thats just the way minecraft is :)
