### ISSUE TITLE
[1.16.3] Heart containers, how to use them ?

### ISSUE THREAD

**Issue by Moustik2002** [PrinceOfAmber/Cyclic#1503]
Minecraft Version: 1.16.3

Forge Version: 34.1.10

Mod Version: Cyclic-1.16.3-0.8.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

I've crafted several heart containers to increase the number of it, but when i'm trying to use them, nothing happens.
I've tried right click, wait for starvation to use it, no results. Am i missing something ?

**Comment by trunksbomb** [comment]
There's a bug right now where you have to use the Heart Container on a block in order to consume it. You can't just right click the air to consume it.

**Comment by Lothrazar** [comment]
:) https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3076981
