### ISSUE TITLE
Filled buckets inside an Auto Crafter in the "Recipe holder" space are emptied upon recipe crafting

### ISSUE THREAD

**Issue by Swainoo** [PrinceOfAmber/Cyclic#1506]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Attempting to use Auto Crafter to craft "Infinite Water Source" from NuclearCraft. Use JEI to import the recipe, using processing cable to putt 2x water buckets, 2x basic plating and 2x Tin ingot. 

What happened was a single Infinite Water Source block was crafted but then the 2 water buckets in the "Recipe holder" section are emptied and turned into empty buckets, thus stopping the autocraft process.

What should of happened is the items in the "Recipe holder" aren't touched/changed and the 2 water buckets stay as water buckets.
 
Log file link:

Video/images/gifs (direct upload or link): 

![ezgif-2-84b2dd7380a1](https://user-images.githubusercontent.com/24801126/95371646-65435d00-08d2-11eb-9997-ebf937b3c936.gif)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Same issue was happening for cake recipes, just like in your GIF. the empty buckets got left behind.  Made a fix so it moves the empty ones over and swaps them out like this
![cakee](https://user-images.githubusercontent.com/621529/95413312-e6edb780-08df-11eb-9d3c-24c52ac41334.gif)
