### ISSUE TITLE
Items disappear Powered Diamond Anvil [1.16.2-0.7.0]

### ISSUE THREAD

**Issue by ZeTr0nIx** [PrinceOfAmber/Cyclic#1511]
Minecraft Version: 1.16.3

Forge Version: 34.1.0

Mod Version: 1.16.2-0.7.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): I wanted to repair my enchanted diamond pants; I put the into the anvil; The pants dissapeared; Tried it again with various other armor parts and weapons; same result.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
This was fixed just a few days ago in 0.8.0, please test https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113
