### ISSUE TITLE
[suggestion (and a bug with Forester)] Add a guide book that explains what the items/blocks do and how to use them

### ISSUE THREAD

**Issue by llssc** [PrinceOfAmber/Cyclic#1514]
I went through each blocks in the mod trying to figure out what they do and it took me a whole hour in creative mode with JEI cheat enabled to understand the block mechanisms except three: Forester, Fluid Collector, and Miner.

I could not get these to work since I did not know what they require to run other than power source, and Forester even crashes the game when I tried putting in sapling or bonemeals (I have not tried other items) in the slot.

It would be helpful if there's an up-to-date guide somewhere that explains how the elements in the mod interacts with the game or with each other.

Edit: 
Should've known better when I already crashed 5 times trying to put a sapling into the Forester,
now I have corrupted my test world by trying to supply Forester with sapling using a chest and an item pipe and I can't open the world anymore.

**Comment by trunksbomb** [comment]
Use the issue template that you get when clicking "New Issue" to provide information about your situation, please.

Cyclic used to implement Guide-API in 1.12.2 but that mod did not get updated, so newer versions of Cyclic naturally had to drop support. That said, it looks like there's a fork: https://www.curseforge.com/minecraft/mc-mods/guide-api-village-and-pillage

**Comment by trunksbomb** [comment]
Checking back in, it looks like Lothrazar wants to use Patchouli since it's already included in the code.

**Comment by llssc** [comment]
So some time in the future, there will be an in-game guide?

**Comment by trunksbomb** [comment]
![image](https://user-images.githubusercontent.com/1904331/95643963-f821fa00-0a80-11eb-8105-d10163d7ecc7.png)

**Comment by llssc** [comment]
Is it implemented in 1.16.3 versions? I can't seem to find it

**Comment by trunksbomb** [comment]
Not yet, I'm working on it. Soon™

**Comment by Lothrazar** [comment]
yeah since patchoulli is data driven (json) instead of code, it should hopefully be easier to port going forward. in 1.12 it was dozens and dozens of lines of code for the guide book.  . i love guide API and ive submitted a bunch of pull requests to it, but the new fork cant use any of the 1.12 code, from the wiki it looks totally different, so staying with guideapi would need a rewrite anyway.  I polled twitter a while ago and everyone voted patchoulli.  
shoutout to @trunksbomb for taking on the guide

**Comment by trunksbomb** [comment]
The other half of your issue, the bug with the forester, is fixed in commit related to #1516

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3076981
