### ISSUE TITLE
[1.16.3] A bug with Forester that causes the game to crash

### ISSUE THREAD

**Issue by llssc** [PrinceOfAmber/Cyclic#1516]
Minecraft Version: 1.16.3

Forge Version: 34.1.16

Mod Version: 1.16.3-0.8.0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
When a player attempts to place a sapling into Forester (or bonemeal, I have not tried other items), the game crashes.

Log file link:
https://i.imgur.com/iS1HIQX.png

Video/images/gifs (direct upload or link): 
https://youtu.be/sV-uP0L-D5A
(Youtube algorithm may start recommending weird videos after this so you might want to delete it from history)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3076981
