### ISSUE TITLE
Horse Speed Upgrade reducing speed

### ISSUE THREAD

**Issue by MindCaged** [PrinceOfAmber/Cyclic#152]
I am using version 1.10.2-1.8.0. I tried using the horse speed upgrade on a horse, and noticed it actually /decreased/ the speed stat.

**Comment by PrinceOfAmber** [comment]
That sounds weird and broken ill test it out.

**Comment by PrinceOfAmber** [comment]
SO i can see Horse Speed in F3 mode.  I spawned in a new horse and it had about 20 speed.  Fed it a few carrots and it went up to 23 and then 27.27.    Fed it a ton more until it refused to eat and now it has 48.98 

Tried another horse that started at 16.something , and fet it only one and it went to 17.66.  Fed it as much as I could and it got to 49.21.

Works on my machine, but can you post some more details?  What was the speed before and after? Was it a modded or vanilla horse? Any other info you have?

.

**Comment by MindCaged** [comment]
Hmm, looks like it's been tweaked in 1.8.2. I'm going to retest it.

Ok, haven't tested yet, but I have a theory. Does the code take the /current/ speed of the horse and multiply it then set the /base/ speed? Because I had a mod giving nearby entities slowness 3. So if it took the current speed modified by slowness, and then set the /base/ speed to a certain percentage over /that/ it might effectively reduce the speed stat, since the decrease from the slowness effect would be more than the increase from the carrot. I'll have to test as soon as I can get minecraft finally booted up.

YES!!! That does seem to be the problem, when the horse is under slowness it decreases the speed, when not, it increases the speed. BTW, the reduced speed increase in v1.10.2-1.8.2 makes it require a lot more carrots. Especially since I started at a low speed stat after it decreased it initially. I think I used 2 stacks just getting it up to 2.7x. from like 0.5x or something, I can't remember.

Apparently, it also works in reverse with speed splash potions, greatly boosting the speed increase granted by the carrots, of course I think I was using speed 2.

**Comment by PrinceOfAmber** [comment]
yes, i add a percentage to the speed, i assumed i was using the base speed, but maybe the game sets that value to base + potions. i can look into this.  

Maybe as you say adding a fixed number not a percentage is a better way.

I did make a small change, yeah. in older versions you could use just a handful and max out right away.  They are already super cheap already, and i think for half a stack of redstone its not too much to ask.

**Comment by PrinceOfAmber** [comment]
It now upgrades at a  constant rate, not percentage of current https://minecraft.curseforge.com/projects/cyclic/files/2346133
