### ISSUE TITLE
Suggestion: JAPPA-fied textures

### ISSUE THREAD

**Issue by BugmanBugman** [PrinceOfAmber/Cyclic#1521]
a lot of the textures in this mod are a bit out of place due to being from 1.12, and rather programmer art-y. Perhaps there could be a total artist overhaul to make the textures in the mod a lot more inline with the current JAPPA textures?

**Comment by trunksbomb** [comment]
Contributions are always welcome, if you're able to do any of the textures.

**Comment by Lothrazar** [comment]
Personally I enjoy some pre jappa textures including armor, i even have a custom texture pack i use to make vanilla armor the old way.

I know some people are not fans, but i can't please everyone.  If you make or find JAPPA emerald armor texture, you can also create a custom resource pack with the armor and it will override my modded textures.  Also as said above, pull requests are welcome and would be evaluated.  If you do go this route DM me on twitter or discord if you need any help :)
