### ISSUE TITLE
[Suggestion] Problems with forester logic

### ISSUE THREAD

**Issue by llssc** [PrinceOfAmber/Cyclic#1522]
Minecraft Version: 1.16.3

Forge Version: 34.1.19

Mod Version: 1.16.3-0.8.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Saplings grow trees beyond the range for the forester, making these residues (first image).
Because saplings placed by each other grows a huge tree, the first problem is very much more likely to happen (second image).
The forester will not mine the bottommost block, meaning the machine will come to a complete stop after some time (third image).

Unless these are intended features of forester, the logic needs some tweaking.

Video/images/gifs (direct upload or link): 
https://i.imgur.com/F0LRtZK.jpg
https://i.imgur.com/eISCw8T.jpg
https://i.imgur.com/icVte89.jpeg
after some time with tick speed at 50... https://i.imgur.com/nc5u2Us.jpeg

**Comment by trunksbomb** [comment]
For #1, the Forester does not implement any type of "leaf tracing" where it finds adjacent leaves and breaks those. This could be implemented relatively easily.
For #2, the Forester just needs to space its saplings apart by 1, which again is pretty easy to implement.
For #3, that seems like an actual bug with the logic, yes.

**Comment by Lothrazar** [comment]
For the spacing question, it tries to plant on every square, but it knows if the space is valid and "plantable".  So for example, if you put down Stone and Dirt in any pattern you like, it will not be able to plant the saplings on stone.

For example, if you want to grow 2x2 spruce trees, make 2x2 squares for the four dirt blocks, and then use stone or wood or some other non-plantable block for the spaces in between

**Comment by Lothrazar** [comment]
I am not a fan of machines that do absolutely everything for the player, its better if a machine can encourage the player to find a way to solve or build around a problem.

For example ,if I want to farm 2x2 spruce saplings, i can grow something like this picture, and it wont plant on stone.

(also shown is i bumped the region off by 1, so the region starts in front of the machine)

Similarly, yes some trees like Acacia and oak can grow sideways, which can go outside the region if the player allows saplings to plant on the edge.  This is a problem for the player to solve.  Either by building walls to confine this growth, or not planting on the edge, or even setting up multiple foresters if desired.

Hope that helps



![2020-10-12_23 23 55](https://user-images.githubusercontent.com/621529/95823334-4550d680-0ce2-11eb-8ce8-9524c13b2b3d.png)

**Comment by llssc** [comment]
I am aware of the player-end solutions for 1 and 2, but I wanted integrity of the farm that the field looks the same inside the region and its context (if you know what I'm saying).
Is it possible to add a GUI in the machine that specifies places the machine plants?

**Comment by Lothrazar** [comment]
"Is it possible to add a GUI in the machine that specifies places the machine plants" Its possible. 

But what would it look like, and what options would it give? off the top of my head people often grow trees in rows, or spaced appart, sometimes 2x2 sometimes not.?  I m not totally against it, i just dont know where to start? i guess?.  And, player can just replace any dirt with wood or stone to define where the planting happens already.

**Comment by Lothrazar** [comment]
Closing this because bug is fixed.  If you want to make a new issue with your suggestion for an upgrade like this, i look forward with what you can come up with
