### ISSUE TITLE
[Bug?] Miner and Fluid collector do not work

### ISSUE THREAD

**Issue by llssc** [PrinceOfAmber/Cyclic#1523]
Minecraft Version: 1.16.3

Forge Version: 34.1.19

Mod Version: 1.16.3-0.8.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Miner doesn't mine, (I broke that grass block).
Fluid collector does not replace fluid even though there are replacement blocks in its buffer.

Log file link:

Video/images/gifs (direct upload or link): 
https://i.imgur.com/IXBNsI6.png
https://i.imgur.com/DzcVaEP.png
https://i.imgur.com/JgfB6mC.png
https://i.imgur.com/NMWsgEF.png

**Comment by Lothrazar** [comment]
Im fixing some issues with the miner.  SUch as : if it was holding a shovel, it would get stuck mining stone forever, but new way will to check if its a harvestable block with the tool.  Also fixed issues with both collector and miner where when you resized the area, the client render would be accurate but the server was still processing over the old area.

Looks like your screenshots have everything set up correctly.  One other thing, if the fluid collector picks up some lava, it will then ignore non-matching fluids such as water.  

Release soon that should fix everything , just doing more testing first
