### ISSUE TITLE
How do you get liquids out of melting chamber

### ISSUE THREAD

**Issue by SilasTurner** [PrinceOfAmber/Cyclic#1524]
Minecraft Version: 1.16.3

Forge Version: 34.1.10

Mod Version: 0.8.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
How do you get a liquid out of a melting chamber. The pipes don't take the liquid out and buckets dont work either.

**Comment by trunksbomb** [comment]
You need to use a cable wrench on an fluid pipe to turn Extract mode on. You'll know Extract mode is on when you see a little gray "plate" extending out of the pipe onto the face of the block you want to extract from.

![cyclic#1524](https://user-images.githubusercontent.com/1904331/95924665-070cf300-0d86-11eb-9a3f-28550f1e8bb0.gif)

**Comment by SilasTurner** [comment]
Thanks that fixed it!
