### ISSUE TITLE
[BUG] Torch launcher directional issue

### ISSUE THREAD

**Issue by Caffin8tor** [PrinceOfAmber/Cyclic#1525]
Minecraft Version: 1.16.1

Forge Version: 32.0.108

Mod Version: 0.6.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
When using the torch launcher, torches are fired in a completely different direction than straight ahead.
Unknown if issue occurs with 1.16.3 versions, but not able to update due to several needed mods not updated beyond MC 1.16.1 yet.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Similar bug was affecting the Monster Ball (#1488) recently.

Issue was fixed in a7c70866a473aba4122bbe841fa3a2d5a831b80e for issues #1461 and #1464.
![cyclic#1525](https://user-images.githubusercontent.com/1904331/95925160-19d3f780-0d87-11eb-989c-0618a19e1382.gif)

**Comment by Caffin8tor** [comment]
So will this be fixed only for 1.16.3 or will the fix also be applied to 1.16.1? Thanks!

**Comment by Lothrazar** [comment]
Looks like fixed in https://github.com/Lothrazar/Cyclic/issues/1464 . Everyone is updating to 1.16.3 , and theres so much difference between them that nobody has the space to support both

**Comment by Caffin8tor** [comment]
Alright. I figured I'd ask anyways. I'll just wait for other mods to update to 1.16.3 (Glares at Quark)
