### ISSUE TITLE
How to use the miner

### ISSUE THREAD

**Issue by SilasTurner** [PrinceOfAmber/Cyclic#1526]
Minecraft Version: 1.16.3

Forge Version: 

Mod Version: 0.8.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
How do you get the miner to work. I think I set it up right but it doesn't mine

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/72347173/96002016-9242c300-0e30-11eb-816e-73baeebac1f6.png)

**Comment by Lothrazar** [comment]
Fixed some bugs in miner where it was getting stuck https://github.com/Lothrazar/Cyclic/issues/1523 .  Latest version should work fine with empty mining slot or with a tool . It checks if a block can be harvested, and skips over it if not doable
