### ISSUE TITLE
Terra Preta causing Server Console spam?

### ISSUE THREAD

**Issue by scopiplays** [PrinceOfAmber/Cyclic#1529]
Minecraft Version: 1.16.3

Forge Version: 34.1.18

Mod Version: 1.16.3-0.8.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I have Terrra Preta under my farmland, and "[Server thread/INFO] [co.lo.cy.ModCyclic/]: growth from TP " is printing to the server console 2 times a second.

Is there a debug switch to make the mod less chatty?

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Will be a quick fix https://github.com/Lothrazar/Cyclic/blob/efdab3081f2ccd660ce873b0d8359b539e90be22/src/main/java/com/lothrazar/cyclic/block/soil/TileTerraPreta.java#L92

**Comment by Lothrazar** [comment]
1.12 had a debug switch that defaulted to off., ill delete this line but also add that switch back in so it wont happen later, just have to wrap the logger

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3086233
