### ISSUE TITLE
Fail in server

### ISSUE THREAD

**Issue by atzelpool** [PrinceOfAmber/Cyclic#1530]
Minecraft Version: 

Forge Version: 34.1.19

Mod Version: 1.16.3 0.8.2

Single Player or Server: Server  conection

Describe problem (what you were doing; what happened; what should have happened):
In single it works fine, the problem is when I want to connect to my server and I tried with all the mods that I use which have not given problems and I tried only the cyclic mod, with all the mods it simply never loads, only cyclic the message "failed to synchronize registry data from server closing connection "
I will share the logs in both scenarios I love your mod alone, it is the best thing I wanted to use with my friends on my server

Log file link:
https://drive.google.com/file/d/1senTRHbzUspafE_Y80APjDgt3SJdug1d/view?usp=sharing

Video/images/gifs (direct upload or link): in zip file

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
I get access denied on your link, can you upload the log to an online pastebin service instead?

**Comment by atzelpool** [comment]
http://www.mediafire.com/file/7wv7w1emtio3ejr/logs.zip/file
or
[logs.zip](https://github.com/Lothrazar/Cyclic/files/5392080/logs.zip)

**Comment by trunksbomb** [comment]
```
[16Oct2020 05:57:35.297] [Worker-Main-3/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe cyclic:guide_book
com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
```

It's looking for Patchouli to create the guidebook, but can't. For now, you'll need to download and install Patchouli, which Cyclic uses for its guidebook to demonstrate all its features. https://www.curseforge.com/minecraft/mc-mods/patchouli

@Lothrazar, will Patchouli be required to run Cyclic now that the guidebook is implemented, or is there something additional to do in code that will only register the item if Patchouli is present?

**Comment by atzelpool** [comment]
Well, the mod was not there, I added it and the same happened :c
[logs.zip](https://github.com/Lothrazar/Cyclic/files/5393667/logs.zip)

**Comment by atzelpool** [comment]
Well, the mod was not there, I added it and the same happened :c
[logs.zip](https://github.com/Lothrazar/Cyclic/files/5393675/logs.zip)

**Comment by atzelpool** [comment]
![Captura de pantalla (89)](https://user-images.githubusercontent.com/69577379/96297044-83354f80-0fad-11eb-9206-8c18b5971388.png)

**Comment by trunksbomb** [comment]
```
com.mojang.authlib.GameProfile@99bcbd0[id=<null>,name=atzelpool94,properties={},legacy=false] (/190.86.96.128:12708) lost connection: Took too long to log in
[16Oct2020 14:29:20.385] [Netty Epoll Server IO #4/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [patchouli:main,cyclic:main_channel] rejected their client side version number
[16Oct2020 14:29:20.385] [Netty Epoll Server IO #4/ERROR] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Terminating connection with client, mismatched mod list
[16Oct2020 14:29:20.423] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@433a061[id=<null>,name=Cesar3072,properties={},legacy=false] (/179.51.31.14:3330) lost connection: Connection closed - mismatched mod channel list
```

You have to put Patchouli on the client and server side. Your disconnect this time was because one of the sides doesn't have the mod.

Also anyone connecting to your server will need the mod as well.

**Comment by atzelpool** [comment]
![Captura de pantalla (90)](https://user-images.githubusercontent.com/69577379/96326407-88b28a00-0fed-11eb-96cb-0c6046a6ffd4.png)

**Comment by Lothrazar** [comment]
When i test with patchouli installed, server and client run ok.  . EDIT: and also server/client should always have the same mod list whenever possible

**Comment by trunksbomb** [comment]
`Channels [patchouli:main,cyclic:main_channel] rejected their client side version number`

**Comment by Lothrazar** [comment]
Ill look into whats required to make patchuli optional, or somehow make the recipe conditional / optional, if any changes are needed.  What i expect SHOULD happen is that , it fails to load recipe for the book, BUT server and client should continue to load if forge is working correctly

**Comment by atzelpool** [comment]
Thank you very much because you both have it and it is seen that they work well the synchronization seems to fail

**Comment by atzelpool** [comment]
> `Channels [patchouli:main,cyclic:main_channel] rejected their client side version number`

in capture the version is 1.16.2.-45 in server and client

**Comment by Lothrazar** [comment]
ive been using version -44 for most things. ill test with v45 tonight, looks like it just came out. 

still, mostly it sounds like Forge checking versions of client server and finding an error.

**Comment by atzelpool** [comment]
Well I'll be waiting because if I love your mod and wanted to put it on the server

**Comment by Lothrazar** [comment]
patchouli fixed this months ago :)
