### ISSUE TITLE
[1.16] Playing too many sounds at once crashes the game

### ISSUE THREAD

**Issue by trunksbomb** [PrinceOfAmber/Cyclic#1531]
Minecraft Version: 1.16.3

Forge Version: 34.1.18

Mod Version: 0.8.2-SNAPSHOT

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

While making the Fireplace block, found that flipping a lever rapidly to activate a block that plays sounds will crash the game. Confirmed that this happens with spikes as well.

Log file link: https://hastebin.com/iriturujib.properties

**Comment by Lothrazar** [comment]
I removed the world.isRemote check, and moved the Extinguish sound to use
 worldIn.playEvent(1009, pos, 0);

Seems better? 
going to keep testing
![fireeeeee](https://user-images.githubusercontent.com/621529/96328291-40e43080-0ff6-11eb-8d06-488d7f5ea2f4.gif)
