### ISSUE TITLE
Cyclic Fan Causes Player To Get Kicked For Flying

### ISSUE THREAD

**Issue by SilasTurner** [PrinceOfAmber/Cyclic#1535]
Minecraft Version: 1.16.3

Forge Version: 34.1.10

Mod Version: 0.8.0

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
When a player uses the fan, he gets kicked for flying.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3086233
