### ISSUE TITLE
Wing Charm not wearing off? [unknown minecraft version]

### ISSUE THREAD

**Issue by Exclusive541** [PrinceOfAmber/Cyclic#1538]
Minecraft Version: 

Forge Version: 

Mod Version: 4.2.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
So I got a wing charm and it was doing it's thing, but now it just won't stop. It's not in my inventory or even in any chests. Any help would be much appreciated. Thanks!

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
"Mod Version: 4.2.2"

I dont understand this line. Mod never had this version.

Also you left the other lines blank. Are you in Minecraft 1.16.3? 1.12.2?

**Comment by Lothrazar** [comment]
latest version is updated on https://www.curseforge.com/minecraft/mc-mods/cyclic
