### ISSUE TITLE
Ender Wing & Ender Wing Prime

### ISSUE THREAD

**Issue by lulabyte** [PrinceOfAmber/Cyclic#1539]
Minecraft Version: 1.16.1

Forge Version: 1.16.1

Mod Version: 1.16.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
The Ender Wing and Ender Wing Prime don't seem to do anything. I used them and nothing happens at all. I expected them to return me to spawn.

Thanks for all you do!

**Comment by trunksbomb** [comment]
This is fixed in 1.16.3 in commit 2c75dbcc39dd7d5d4bd123e907c3e376951aedf5
