### ISSUE TITLE
Monster Ball doesnt work

### ISSUE THREAD

**Issue by jmmd2000** [PrinceOfAmber/Cyclic#1540]
Minecraft Version: 1.16.1

Forge Version: 32.0.108

Mod Version: 1.16.1-1.0.1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): Monster Ball just doesn't 
 work, it shoots up into the air no matter where you aim.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

I think this was addressed but for a different game version

**Comment by trunksbomb** [comment]
This is fixed in 1.16.3 in commit 3251159876a025e991eca327ef96615ebfccac2c

Based on @Lothrazar's reply to another issue present in 1.16.1 and fixed in 1.16.3, I don't think the fix will be backported.
