### ISSUE TITLE
[Bug] Nitro creeper + diamond spikes = heads

### ISSUE THREAD

**Issue by AlienXtream** [PrinceOfAmber/Cyclic#1541]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2854
Mod Version: 
1.12.2-1.20.6
Single Player or Server:
SP
Describe problem (what you were doing; what happened; what should have happened):
heads. lots and lots of heads. more a less a stack per nitro creeper kill. only happens with Cyclic spikes.

not even 100% sure it IS your mod but the nitro creepers dont drop heads like this when killed by myself (and i even have a beheading enchant on my sword). only nitro creepers seem affected. not actually done control tests beyond survival mode scenario it happened in. posting this here more as an FYI that something funky is happening.
Log file link:

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/12606809/96575154-207ce480-131c-11eb-9ed9-5777b6ca9cce.png)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Diamond spikes do a different flow than the iron ones, uses a fake player . so same thing would happen if its an Automated user with a weapon, or a player.

Probably from https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/block/BlockSpikesRetractable.java#L148

attack from the player entity. i dont apply looting or anything like that, so must be just settings from mob or pack or loot table.

**Comment by AlienXtream** [comment]
custom pack. no modified loot tables and ive not changed anything that might cause that afaik. would have to be a bug in (i think) natura then. unless it happens with normal creepers too... either way i have a crap ton of creeper heads i can use and you know of something funky happening in case it pops up elsewhere more destructively. just have to make sure the collection method i use can keep up XD

**Comment by AlienXtream** [comment]
ok... so its NOT just nitro creepers... any vanila head other than wither skeletons drop the same....

**Comment by AlienXtream** [comment]
and endermen.... i dont know WHAT drops anymore...

**Comment by LordKiel** [comment]
Looks like onCollision is being processed even after mob is dead and too many drops are being created. maybe check that health > 0.0 before handling event?
