### ISSUE TITLE
[Suggestion] switchable unbreakable block

### ISSUE THREAD

**Issue by 4Magma** [PrinceOfAmber/Cyclic#1542]
I use a fortune+efficiency pickaxe to break blocks generated by botania orechid,
which are pushed with a piston before me.
**Problem:** sometimes even obsidian blocks behind the target block are destroyed

Could you add a block, which can be toggled between breakable|unbreakable
per redstone, gui, specific item or empty hand.  
- optical perhaps bedrock sides with a metal frame
- recipe e.g. 3x3 obsidian or obsidian around a redstone dust

greetings
Martin Urban

**Comment by trunksbomb** [comment]
![cyclic_unbreakable](https://user-images.githubusercontent.com/1904331/101146925-a792cd00-35e9-11eb-8618-93069da4d50d.gif)

I've almost got this done, will work on it more later.
