### ISSUE TITLE
According to the Blame Mod, Cyan Flower generation is not a registered ConfiguredFeature

### ISSUE THREAD

**Issue by BugmanBugman** [PrinceOfAmber/Cyclic#1543]
Minecraft Version: 1.16.3

Forge Version: 34.1.24

Mod Version: 0.8.3

Single Player or Server:
singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Title. According to the Blame mod, it will break other mods or datapacks that registered their stuff.

Log file link:
https://hatebin.com/udoqcjdlfq

**Comment by Lothrazar** [comment]
Its registered here https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/event/WorldGenEvents.java#L34
as a Feature.FLOWER , generated with VEGETAL_DECORATION feature .

Added in only some biomes with forge reccomended BiomeLoadingEvent .  so its all in the one class.

What needs to change exactly? I dont know how to "register a feature"a different way

**Comment by BugmanBugman** [comment]
i believe this could help
![image](https://user-images.githubusercontent.com/40730042/96918244-a2315700-146f-11eb-9501-d3f4deca329f.png)
otherwise, i think the blame author telepathicgrunt could assist as well
