### ISSUE TITLE
Water Candle Dupe Bug

### ISSUE THREAD

**Issue by Rogue238** [PrinceOfAmber/Cyclic#1544]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2846

Mod Version: Stoneblock 2  version 1.16.1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):  I have been playing Stoneblock 2 and created a dark room for mobs.  I placed the water candle and lit it.  (It's still spawning mobs in walls, but that isn't the issue here and doesn't bother me much.)  However, it randomly replaces blocks around near it with more water candles (unlit).  I don't believe that's an intended behavior.

**Comment by Lothrazar** [comment]
This looks similar to https://github.com/Lothrazar/Cyclic/issues/1320 what version of cyclic does stoneblock 2 have in 1.16.1?   If its 1.20.X it should be ok

**Comment by Rogue238** [comment]
Okay, how do I find that version to update it?  I can only see 1.16.1 as the current version.
