### ISSUE TITLE
Server crash - Ticking block entity

### ISSUE THREAD

**Issue by zISKo666** [PrinceOfAmber/Cyclic#1546]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.7

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Server keeps crashing during start.

Log file link:

https://pastebin.com/RjWm58dV

**Comment by Lothrazar** [comment]
thanks for report. flagged 1.20.7 as alpha, still some issues

**Comment by Lothrazar** [comment]
I think it stopped being broken in this one https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3089348

**Comment by zISKo666** [comment]
Thank you for that quick update.
It is working again :)
