### ISSUE TITLE
Bug found on reddit, mod interaction with GPS Marker?

### ISSUE THREAD

**Issue by trunksbomb** [PrinceOfAmber/Cyclic#1547]
https://www.reddit.com/r/feedthebeast/comments/jfmre5/so_apparently_if_you_hold_a_cyclic_gps_marker/

I've asked in the comments for some more details, will update the usual ticket template if there is a response.

**Comment by Lothrazar** [comment]
is this only with optifine installed? seems like im leaving some OpenGL buffer pushed/out of sync or something lol

**Comment by trunksbomb** [comment]
The OP on reddit hasn't responded.
