### ISSUE TITLE
Don't know how to use melter and other machines 1.12.2

### ISSUE THREAD

**Issue by Eric-Li-7** [PrinceOfAmber/Cyclic#1549]
![Dingtalk_20201024082917](https://user-images.githubusercontent.com/61606573/97067846-8dca9700-15f4-11eb-92b6-a42155262bac.jpg)
![Dingtalk_20201024083330](https://user-images.githubusercontent.com/61606573/97067847-902cf100-15f4-11eb-8515-f11f0884d808.jpg)

Minecraft Version: 1.12.2

1. I put acacia wood in the melter and it quickly filled up with amber, but I can't figure out how to take the amber out with a bucket! I need it to make crystalized amber 

2. I put the needed ingredients for lily pads and water in the hydrator, but the machine won't run!

please help me as soon as possible

**Comment by jkolbly** [comment]
Sorry for the late reply. I'm not sure if there's an easier way, but you can probably pipe the amber out into a tank and fill the bucket just by right-clicking the tank. As for the hydrator, it looks like the machine may require power, which it doesn't seem to have.

**Comment by Eric-Li-7** [comment]
> Sorry for the late reply. I'm not sure if there's an easier way, but you can probably pipe the amber out into a tank and fill the bucket just by right-clicking the tank. As for the hydrator, it looks like the machine may require power, which it doesn't seem to have.

I will try the tank methtod. but what do you mean by power? redstone?

**Comment by Eric-Li-7** [comment]
> Sorry for the late reply. I'm not sure if there's an easier way, but you can probably pipe the amber out into a tank and fill the bucket just by right-clicking the tank. As for the hydrator, it looks like the machine may require power, which it doesn't seem to have.

what do you mean by pipe the amber? I put a tank next to the melter and nothing happened

**Comment by trunksbomb** [comment]
You need to use a Fluid Extraction Cable to get the fluid out of the Melter and into a tank. Then you can use a bucket on the tank.
![cyclic_melter](https://user-images.githubusercontent.com/1904331/97771415-12e10f00-1b13-11eb-9549-b3449e7c9720.gif)
