### ISSUE TITLE
Autocrafting with Mystical Agriculture

### ISSUE THREAD

**Issue by jkolbly** [PrinceOfAmber/Cyclic#1550]
Minecraft version:
1.12.2

I'm playing Skyfactory 4 and I'm using Cyclic crafters to autocraft mystical agriculture essence. This was working fine until I upgraded to Cyclic 1.20.8 for Fix #1497, which broke autocrafting with items that aren't used up in the crafting recipe due to Fix #1506.

I'll admit I'm not sure how this works internally, but I propose a way to have both. I would think maybe if the item is changed to a different item in the recipe (containers, for example, are changed to empty containers), the item could be piped out and if the item remains the same it could remain. If that's not possible, perhaps a toggleable option (either in the mod config or the crafter itself, the latter more preferable in my opinion) to enable/disable piping out containers.

**Comment by Lothrazar** [comment]
for 1.12 it works as intended in latest versions. the recipe does fire but you need a second crystal to loop around and around every time or a few of them.  different workflow than minecraft 1.16 
![1550](https://user-images.githubusercontent.com/621529/114947905-cd837600-9e02-11eb-96d5-b074fef9c7bc.gif)
