### ISSUE TITLE
Melter causing console spam

### ISSUE THREAD

**Issue by Aberzhulan** [PrinceOfAmber/Cyclic#1558]
Minecraft Version: 1.12.2

Forge Version: 1.12.2-14.23.5.2847

Mod Version: Cyclic-1.12.2-1.19.18

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Seeing console spam of
```
[Server thread/ERROR] [cyclicmagic]: 15000/16000 
[Server thread/ERROR] [cyclicmagic]: true fluidAllowed
```
The only cyclic item in use at the time is a melter.

Additional note, we are running the MC Eternal modpack.

Log file link: https://pastebin.com/0Ew0UMKM

**Comment by Lothrazar** [comment]
updated in latest versions
