### ISSUE TITLE
disabling emerald equipment crashes "world load screen" back to client

### ISSUE THREAD

**Issue by usafphoenix** [PrinceOfAmber/Cyclic#1559]
Minecraft Version: 1.16.3

Forge Version:  forge-34.1.34

Mod Version: Cyclic-1.16.3-0.8.3

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Modpack includes both Cyclic and Pickle Tweaks, both of which add Emerald tools. Pickle Tweaks adds emerald multipurpose, but with Cyclic installed, crafting emerald pickaxe results in cyclic's version. Thus, disabling cyclic emerald equipment is necessary...
But doing so in a world already created causes the world to not load, instead, it crashes back to client. This may be an issue with forge, or other mod, but as the only change was disabling emerald gear in cyclic config...and re-enabling allows world to load again, i'm assigning fault to Cyclic :P 

Log file link: https://file.io/97GTIFoSpQpl

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Looks like deleting items like this is not supported the same way it was in 1.12. just throws errors and crashes.  ill delete any configs that delete content, we will have to remove items with data packs and hide from JEI
