### ISSUE TITLE
Uncrafting Grinder not working with custom recipe handlers from other mods (for example: Mekanism) 

### ISSUE THREAD

**Issue by Tridon343** [PrinceOfAmber/Cyclic#156]
Hi there,

I tried to uncraft some mekanism machines. According to some modders it is because Mekanism has its own crafting handler. 
Would be great it you could add support for those crafting handlers.

Having fun so far.
Thanks!

**Comment by PrinceOfAmber** [comment]
Yes, by default the uncrafter only currently works with 2x2 and 3x3 recipes. Upgrades to it are on the plan, but not in the near future. 

 Its a great idea!

**Comment by Tridon343** [comment]
The recepies I tried to uncraft are depicted as normal 3x3 crafting receipes. I did not mean special uncrafting like from smelting or crushing/ refining items.

**Comment by PrinceOfAmber** [comment]
Ive decided not to support recipes from other mods, at least not with the uncrafting grinder.

If i go this route, i would have a seperate block and a cost that could handle special crafting recipes.

If this really is an issue with vanilla crafting recipes sometimes not detected then im addressing that issue soon here https://github.com/PrinceOfAmber/Cyclic/issues/248
