### ISSUE TITLE
[1.16.3] Obsidian Shears cannot extract honeycombs

### ISSUE THREAD

**Issue by andrewsf** [PrinceOfAmber/Cyclic#1560]
Minecraft Version: 1.16.3

Forge Version: 34.1.25

Mod Version: 1.16.3-0.8.3

Single Player or Server: Single Player

Not too much to explain here. Regular shears can extract honeycombs from a hive, but Obsidian Shears cannot.

**Comment by Lothrazar** [comment]
I didnt know this was a thing that shears could do. Ill have to see how much mojang has this hardcoded or if its easy to add

**Comment by trunksbomb** [comment]
Interestingly, it's hardcoded into the BeeHive class that it will only drop HoneyComb `if (itemstack.getItem() == Items.SHEARS)`.

That said, it will be trivial to replicate that code in Cyclic's Shears class.
