### ISSUE TITLE
[1.12.2] Experience Pylon XP dupe

### ISSUE THREAD

**Issue by NielsPilgaard** [PrinceOfAmber/Cyclic#1562]
Minecraft Version: 
1.12.2

Forge Version: 
1.12.2-14.23.5.2847

Mod Version: 
Cyclic-1.12.2-1.20.6

Single Player or Server:
SP I think

Describe problem (what you were doing; what happened; what should have happened):

Using the Cyclic Experience pylon, you can dupe exp really quickly and effectively. Drain your exp from crouching on top of it while set to collect orbs, then immediately set to spray orbs. Gives more exp than was taken, for example from 69 levels worth to 91.

Original report: 
https://github.com/NillerMedDild/Enigmatica2Expert/issues/1850

**Comment by DenseInL2** [comment]
The easiest repro for me was to just leave the pylon set to Spray Orbs, and just crouch for a bit, then stand, then crouch again, rinse and repeat. I also noticed that the XP meter is often wrong, showing negative or outdated values, but fixes itself if I click the empty bottle slot. Possibly the same bug, possibly not: Sometimes after draining the pylon to zero in Spray mode, then clicking back to Collect Orbs, it magically refills itself right back to where it was at before I drained it. I was able to get into a loop where I could empty the same pylon as many times as I wanted as long as I staying in the UI cycling the mode like this.

**Comment by IRISHMAN04** [comment]
Had this happen today on MC Version 1.12.2, Mod Version 1.20.8, in the Enigmatica 2: Expert Skyblock pack. Recorded 2 videos of it happening: https://youtu.be/eHGD8nsIcDc, https://youtu.be/9N9a6LwQuTw. Ignore the fact that the compressed creeper pushed me off my skyblock, causing me to die from fall damage. The XP gained from both of these bugs is in fact permanent, it's not just a visual bug

**Comment by Lothrazar** [comment]
was also reported in discord with Clumps-3.1.2 . also thanks for videos https://www.curseforge.com/minecraft/mc-mods/clumps/files/2666198

With clumps installed and a new world, i give /xp 100 to myself, drain it into the pylon its accurate at 100 xp and 2k fluid.  it tries to export two xp orps with 50 xp each, and appears to do so. but player ends up collecting 200 xp  .

**Comment by Lothrazar** [comment]
when i uninstall clumps (or disable it Clumps-3.1.2.jar.disabled) and i do this loop, theres no dupe or anything it stays at 400 no matter what  
![no clumps](https://user-images.githubusercontent.com/621529/114914063-bdee3800-9dd6-11eb-8e03-fc65e013627a.gif)
