### ISSUE TITLE
[1.16.3] Crash when killed by Creeper.

### ISSUE THREAD

**Issue by Gbergz** [PrinceOfAmber/Cyclic#1563]
Minecraft Version: 1.16.3

Forge Version: 34.1.42

Mod Version: 0.9.0

Single Player or Server: SP

Describe problem:
Running around the world, creeper exploded, I died. Client crashed.

Crash-Report:
https://hatebin.com/mqdfasktdg

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/5506256/latest.log)

**Comment by LlubNek** [comment]
I'm getting the same thing 
cyclic 0.9.1
mc 1.16.3
forge 34.1.42

no creeper though
