### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by BedrockLegends** [PrinceOfAmber/Cyclic#1565]
Minecraft Version: 1.16.4

Forge Version: 35.0.7

Mod Version: Cyclic-1.16.3-0.9.0.jar

Single Player or Server: Server
[crash-2020-11-08_11.44.51-fml.txt](https://github.com/Lothrazar/Cyclic/files/5506867/crash-2020-11-08_11.44.51-fml.txt)
[crash-2020-11-08_11.45.31-fml.txt](https://github.com/Lothrazar/Cyclic/files/5506868/crash-2020-11-08_11.45.31-fml.txt)

Describe problem (what you were doing; what happened; what should have happened):

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by BedrockLegends** [comment]
https://github.com/Lothrazar/Cyclic/issues/1564 Same issue I think

**Comment by BedrockLegends** [comment]
Just Downgrade to Cyclic-1.16.3-0.8.3 to avoid this issue

**Comment by Lothrazar** [comment]
getting out a quick hotfix today

**Comment by BedrockLegends** [comment]
@Lothrazar More server crashes
[crash-2020-11-08_17.54.05-server.txt](https://github.com/Lothrazar/Cyclic/files/5507422/crash-2020-11-08_17.54.05-server.txt)
[crash-2020-11-08_18.08.23-server.txt](https://github.com/Lothrazar/Cyclic/files/5507423/crash-2020-11-08_18.08.23-server.txt)

**Comment by BedrockLegends** [comment]
https://github.com/Lothrazar/Cyclic/issues/1572
https://github.com/Lothrazar/Cyclic/issues/1571
https://github.com/Lothrazar/Cyclic/issues/1569

**Comment by Lothrazar** [comment]
Yep i agree, same issue as #1572
#1571
#1569 and fixed by https://github.com/Lothrazar/Cyclic/pull/1573

**Comment by Lothrazar** [comment]
0.9.2 soon
