### ISSUE TITLE
Crash on using Cyclic Empty Heart Container

### ISSUE THREAD

**Issue by IamStig** [PrinceOfAmber/Cyclic#1566]
Minecraft Version: 1.16.3

Forge Version: forge-1.16.3-34.1.25

Mod Version: Cyclic-1.16.3-0.9.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Right clicked Empty Heart Container; Crashed; Remove 1 Heart health and add 500 xp (I am guessing, not used it B4)

Log file link: Crash Report: https://pastebin.com/xTi7inzu

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
0.9.2 will fix this

**Comment by IamStig** [comment]
Nice work, thank you
