### ISSUE TITLE
possible issue when using gravestones Mod by Henkelmax

### ISSUE THREAD

**Issue by tekman123** [PrinceOfAmber/Cyclic#1567]
Minecraft Version: 1.16.3

Forge Version: 34.1.42

Mod Version: 1.16.3-0.9.1

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened): when I put this with the gravestones mod by Henkelmax the Gravestones mod stops working as intended. I remove Cyclic and it works fine. Issue also reported with Henkelmax

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by tekman123** [comment]
This issue that is mentioned above likely isn't the same issue I'm having. My server isn't crashing just throwing an error

**Comment by Lothrazar** [comment]
This should have it fixed, but i will test it out https://github.com/Lothrazar/Cyclic/pull/1573

**Comment by tobi-polar** [comment]
Not sure whether it's important to mention but I'm getting the same issue with the latest version with corailtombstones-6.0.2 on mc 1.16.3 as well.

EDIT: 0.9.2 Update has fixed the issue with corail
