### ISSUE TITLE
Sorting the inventory of crates uses the player's inventory too

### ISSUE THREAD

**Issue by nddragoon** [PrinceOfAmber/Cyclic#1574]
Minecraft Version: 1.16.3

Forge Version: 34.1.25

Mod Version: 0.8.3

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): Crates seem to consider the block's inventory and the player's inventory as a single one and middle clicking to sort it with InvTweaks drags along the player's inventory into the sort too. I'm playing on All The Mods 6

Video/images/gifs (direct upload or link): https://www.youtube.com/watch?v=PcBNcBwTYHE

**Comment by trunksbomb** [comment]
Duplicate of #1527

**Comment by trunksbomb** [comment]
I had this happen yesterday with an RFTools Coal Generator and Inventory Tweaks Renewed in 1.16.4 All the Mods 6 pack.

**Comment by trunksbomb** [comment]
Same pack, this time with the Modification Table from Mining Gadgets. Just compiling instances of this happening so we can draw a conclusion on how these mods are causing the player's inventory to not be separated from the container inventory.

**Comment by Lothrazar** [comment]
Closed since its a dupe of https://github.com/Lothrazar/Cyclic/issues/1527 so we dont double up on info. thanks for video BTW
