### ISSUE TITLE
Excavation enchantment StackOverflowError

### ISSUE THREAD

**Issue by rasm945i** [PrinceOfAmber/Cyclic#1575]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.25

**Mod Version:** 1.16.3-0.8.3

**Single Player or Server:** Singleplayer & Server, modpack Allthemods6

**Describe problem (what you were doing; what happened; what should have happened):**
Using a Diamond Pickaxe with the Excavation (IV to be exact) enchantment and mining Azure Silver Ore from the mod Silent Gear in The End world, the server/client crashes. Initially this happened on a server me and my friend played on and it came out with a StackOverflowError. I just tried to reproduce in singleplayer, but the client just crashed with exitcode 0. I assume it is also a StackOverflowError in this case.

The excavation enchantment works perfectly fine in Nether and Overworld. I don't recall mining modded ores with it, but I'm pretty sure it has happened without the server crashing.

**Log file link:** https://pastebin.com/GSuUUXDi
**Crash-log:** https://pastebin.com/NzXpZxzz
I also have a debug-logfile and another crash-file, but none of them seem to have any information regarding this issue.
The other crash-file is saying "java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)" and has a bunch of thread/network IO stuff, not anything mentioning any mods.

**Video/images/gifs (direct upload or link):** None

**Comment by Sunekaer** [comment]
I got this crash too, on 1.16.4
https://paste.sunekaer.com/xerinakofe.rb
In overworld, with a golden pickaxe
