### ISSUE TITLE
problems minecraft sky factory 4

### ISSUE THREAD

**Issue by ChunkyMunkey1310** [PrinceOfAmber/Cyclic#1577]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2854
Mod Version: 
4.2.2
Single Player or Server:
both
Describe problem (what you were doing; what happened; what should have happened):
if i open the launcher it craches when loading snad
this is minecraft ouput
16:59:13.095
SmoothFontCore ASM
Thread-3
SET_UNICODE_FLAG:true
16:59:13.095
SmoothFontCore ASM
Thread-3
SIZE_STRING_TO_WIDTH:true
16:59:13.095
SmoothFontCore ASM
Thread-3
BIND_TEXTURE:true
16:59:13.095
SmoothFontCore ASM
Thread-3
** FontRenderer was transformed successfully.
16:59:13.145
FML
Client thread
Searching C:\Users\32474\Twitch\Minecraft\Instances\SkyFactory 4\mods for mods
16:59:13.148
FML
Client thread
Searching C:\Users\32474\Twitch\Minecraft\Instances\SkyFactory 4\mods\1.12.2 for mods
16:59:13.910
FML
Client thread
Mod aroma1997core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0.0.2.b167
16:59:13.929
FML
Client thread
Mod aromabackup is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.0.0.0.b132
16:59:13.930
FML
Client thread
Mod aromabackuprecovery is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.0.0.0.b132
16:59:14.186
FML
Client thread
Disabling mod bedpatch it is server side only.
16:59:14.363
FML
Client thread
Mod clienttweaks is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.1.11
16:59:14.369
FML
Client thread
Mod codechickenlib is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.3.358
16:59:14.612
FML
Client thread
Mod cookingforblockheads is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 6.5.0
16:59:14.762
FML
Client thread
Mod cyclicmagic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.20.3
16:59:14.905
FML
Client thread
Mod defaultoptions is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 9.2.8
16:59:14.947
FML
Client thread
Mod enderstorage is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.4.6.137
16:59:15.038
FML
Client thread
Mod fbp is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.4.1
16:59:15.042
FML
Client thread
Mod farmingforblockheads is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.1.28
16:59:15.188
FML
Thread-3
Using sync timing. 200 frames of Display.update took 74805700 nanos
16:59:15.286
FML
Client thread
Mod microblockcbe is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.6.2.83
16:59:15.308
FML
Client thread
Mod forgemultipartcbe is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.6.2.83
16:59:15.310
FML
Client thread
Mod minecraftmultipartcbe is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.6.2.83
16:59:15.314
FML
Client thread
Mod forgivingvoid is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.0
16:59:15.699
FML
Client thread
Mod kleeslabs is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 5.4.12

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
fixed in latest versions
