### ISSUE TITLE
pack crash when adding Cyclic

### ISSUE THREAD

**Issue by Altoyda** [PrinceOfAmber/Cyclic#1578]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847
Mod Version: 1.20.3-1.20.8

Single Player or Server:both

Describe problem (what you were doing; what happened; what should have happened):
with cyclic added to pack. it will crash and the error with Mystical Lib, and LagGoggles. It will load with cyclic disable.

Log file link: https://paste.ee/p/Ak5xl

Video/images/gifs (direct upload or link): N/A

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler N/A

I have tryed different ones of cyclic and still happen. cyclic is a add in. I have been using for a while now. Would love to add it to pack I am playing now

**Comment by Lothrazar** [comment]
log file link mentioned other mods, not cyclic causing crash last time i checked, right now says Paste not found. 

I know for sure many big packs like sky factory 4 in 1.12 load cyclic, and i have it running on my computer hard to track this down exactly where its form

**Comment by Lothrazar** [comment]
mystical lib newest latest versions arent crashing, i just tried with MysticalAgriculture-1.12.2-1.7.5.jar so this seems resolved now  .  also new 1.20.9 version for 1.12 is coming soon
