### ISSUE TITLE
Monster Ball

### ISSUE THREAD

**Issue by 4ilur0phile** [PrinceOfAmber/Cyclic#1579]
Minecraft Version: 1.16.3

Forge Version: 34.1.22

Mod Version: 0.9.2

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): Would you change the monster ball recipe back to using iron ingots instead of coral blocks? I cannot find a coral reef biome in my worlds. Also, when I cheated a monster ball in with JEI and tried to release a bee I captured, minecraft crashed.

Log file link: I'm sorry, but I don't know what this is. :(

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Can confirm crash is present in 0.9.2 version, I tested with a wolf. Crash report: https://hastebin.com/egivucidal.rb

**Comment by trunksbomb** [comment]
Hm, different error for a bee, though. The previous was done in ATM6 modpack. The following crash report is for a bee, done from a dev environment https://hastebin.com/owazoyowuj.yaml
