### ISSUE TITLE
[1.16.4] [Suggestion] Change enchant config to allow each one to be disabled individually

### ISSUE THREAD

**Issue by Peach774** [PrinceOfAmber/Cyclic#1580]
Minecraft Version: 1.16.4

I am submitting this as a suggestion.
I would like to be able to disable certain enchants such as magnet or growth without disabling all of the enchantments.

**Comment by AhSchoo** [comment]
This would be very helpful.  I suspect we're seeing issues on our server related to the debuffs from the Gloom enchant.  Maybe not a problem with the enchant itself but not having it available would prevent what we're seeing (player kicked and can't login when some debuff expires, currently we are wiping player.dat to 'solve' and that's a terrible non-solution.)

**Comment by trunksbomb** [comment]
@AhSchoo can you open a separate issue for that Gloom enchant issue?

**Comment by trunksbomb** [comment]
I've implemented this feature request in the linked PR above.
