### ISSUE TITLE
GUIs showing 0 power, yet blocks are powered and function just fine.

### ISSUE THREAD

**Issue by SephirothWS** [PrinceOfAmber/Cyclic#1584]
Minecraft Version: 1.16.4

Forge Version: ~35.0.16~ 35.1.0

Mod Version: 1.16.3-0.9.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Disenchanter is hooked up to power using Mekanism Universal Cables. GUI shows Disenchanter has no power. I can still insert enchanted tools + books and strip enchants off them

Log file link:

Not server operator, cannot access logfiles for server.

Video/images/gifs (direct upload or link): 

![Screenshot](https://i.imgur.com/WeN3wuE.png)
https://youtu.be/d1nLC6uCaSA

**Comment by SephirothWS** [comment]
Pack I'm alpha-testing has updated Forge from 35.0.16 to 35.1.0, issue continues to persist.

**Comment by trunksbomb** [comment]
I imagine that the energy bar is a visual bug, and that Disenchanter does actually have power. I loaded it up in my dev environment on mod version 0.9.2 and MC version 1.16.3 and was able to see energy in the machine, however.

That said, there is an issue where energy isn't extracted.

https://github.com/Lothrazar/Cyclic/blob/5d12b895d5b09b8057083c5cb4fcc79662240f63/src/main/java/com/lothrazar/cyclic/block/disenchant/TileDisenchant.java#L90

The `true` in that method is for simulating extracting the power -- it doesn't actually extract it. That part's a trivial fix but I'm not sure why your GUI isn't showing power.

**Comment by Lothrazar** [comment]
For reference, from the video the cables are Elite Universal Cable - Mekanism.
Looks like yeah a server->client desync of power capability data

**Comment by SephirothWS** [comment]
![image](https://user-images.githubusercontent.com/9165737/100397705-065fb180-3000-11eb-8400-9cf66e087ff3.png)

Pack in development got updated this morning to Cyclic 1.16.3-0.9.3 and I can confirm the GUI looks fixed. :)
