### ISSUE TITLE
can't deactivate the anti-gravity necklace on right-click

### ISSUE THREAD

**Issue by Algester** [PrinceOfAmber/Cyclic#1585]
Minecraft Version: 1.16.3

Forge Version: 34.1.42

Mod Version: 0.9.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

according to the Cyclic Manual and JEI tooltip the necklace should deactivate when I press right click when holding it, when its not.

**Comment by trunksbomb** [comment]
Cyclic's toggle behavior is unique in that you don't hold it in your hand and right click in the world, but rather open your inventory and right click on the item to toggle it.

**Comment by Lothrazar** [comment]
Yep, also the right click in-inventory is not hooked into creative mode inventory. Works in all survival invos including curios, see GIF 
![1585](https://user-images.githubusercontent.com/621529/100150445-7c271a00-2e54-11eb-8654-a1d71b04c600.gif)
