### ISSUE TITLE
Experience pylon infinite XP bug

### ISSUE THREAD

**Issue by lucifer7303** [PrinceOfAmber/Cyclic#1586]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.6

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): I turned on spray orbs and pressed shift simultaneously. this somehow gave me more experience than i had.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Duplicate of #1562
