### ISSUE TITLE
how to craft items in survival 

### ISSUE THREAD

**Issue by firestorm2039** [PrinceOfAmber/Cyclic#1593]
Minecraft Version: 

Forge Version: 1.16.4

Mod Version: 

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):
i will start by saying i am new to minecraft, but i am asking this question on behalf of my 6 year old son, i also know very little about computers.
i can craft all items in creative, but i have no idea how to get them in survival, how do bring up a list of them all in survival so i know what i need to build them? all youtiube videos i have seen they have a separate menu up for them.

is there a separate crafting table i need to make or something?

i have managed to make emerald armour an weapons, but thats about it.
Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei

You'll want Just Enough Items, that's the mod that shows you all the items off to the right-hand side. You can click on them individually to see how to craft them.
