### ISSUE TITLE
What is the recipe Name for the player launcher?

### ISSUE THREAD

**Issue by Popaulol** [PrinceOfAmber/Cyclic#1594]
I just have a technical question cause I want to remove an recipe from a modpack. What is the recipe name for the player launcher?
cyclic-version: 1.20.3
minecraft-version: 1.12.2

**Comment by Lothrazar** [comment]
Recipe name should be the same as the item name.  which is https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/item/ItemPlayerLauncher.java#L131  . 

Using craft tweaker ?

**Comment by Popaulol** [comment]
Yes I am using crafttweaker.

**Comment by Lothrazar** [comment]
Do one of these work?

recipes.remove(<cyclic:tool_launcher>);

recipes.remove(<cyclic:tool_launcher>, false);

recipes.removeByRecipeName("cyclic:tool_launcher");

Or maybe removing by item.  More info on https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Crafting/Recipes_Crafting_Table/ . let me know if its ok
