### ISSUE TITLE
Item extraction pipe should extract the precise number of objects 

### ISSUE THREAD

**Issue by shifenis** [PrinceOfAmber/Cyclic#1595]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: Cyclic-1.12.2-1.19.0

Single Player or Server: Single-player

### Problem:
Like the title, the extraction pipe can't extract the number of items. 
I mean, the pipe should provide not only the possibility to extract a list of element but, but it should have the capacity to extract that number of elements over in a period of time 

### Desired:
Possibility to define how many objects the pipe has to extract.

**Comment by Lothrazar** [comment]
we have the 'transfer rate' slider already, so it can take only 1 per tick or up to 64. what exactly does it mean to "extract that number of elements over in a period of time". if its to slow it down more, how would we represent that in the current interface screen

**Comment by Lothrazar** [comment]
ok it makes sense now. 1.12 isnt getting any new features especially GUI rewrites but ill keep in mind for future versions such as 1.16+
