### ISSUE TITLE
Peat generator issue

### ISSUE THREAD

**Issue by Doughboy2783** [PrinceOfAmber/Cyclic#1596]
Minecraft Version: 
1.16.4
Forge Version: 
35.0.5
Mod Version: 
1.16.4
Single Player or Server:
single player
Describe problem (what you were doing; what happened; what should have happened): When the peat generator fills up on power it doesn't export the power anymore even when it has a place to go. Only way to fix I have found is break and replace the machine 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Which version of Cyclic are you on, the version number is formatted like 0.9.3, it's not the same as the MC version.

**Comment by Doughboy2783** [comment]
0.9.2
