### ISSUE TITLE
Fearure request [an option to replace rf with botanica mana or some other magic mod energies]

### ISSUE THREAD

**Issue by Tenchu98** [PrinceOfAmber/Cyclic#1598]
Minecraft Version: 1.16.4

Forge Version: 
Latest
Mod Version: 
Latest
Single Player or Server:
Both
Describe problem (what you were doing; what happened; what should have happened):
Would it be possible to add an option to replace rf with botanica mana or some other magic mod energies? I am making a modpack and would like to maintain the magical aspect of cyclic all the way through.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Each mod added is a pretty large undertaking, also we dont even know if its possible, like if the other mod allows that to be done.  Is there one energy type that exists, is common, maybe has an API or has other mods already hooking in?   

I found a botania API https://github.com/Vazkii/Botania/tree/master/src/main/java/vazkii/botania/api/mana  . that might work. But what would it do. Do i just make every single machine a mana pool? How would you see the mana.

Might it be easier to have a mod with a "converter Block" between energies

**Comment by Lothrazar** [comment]
In the cyclic config you can disable all power requirements, set the energy cost to zero "0" for machines

**Comment by Tenchu98** [comment]
I'm not sure, botanias table works sort of in the manner I was thinking.

**Comment by trunksbomb** [comment]
This would require implementing Botania's Mana capability on all machines with a config setting on which power method (energy or mana) to use. Would require refactoring every machine in a non-trivial way.

I'm going to pass on taking this on, but someone else could.

**Comment by Lothrazar** [comment]
moved to https://github.com/Lothrazar/Cyclic/projects/4
