### ISSUE TITLE
Harvester not working properly with Mystical Agriculture

### ISSUE THREAD

**Issue by Oridjinn1980** [PrinceOfAmber/Cyclic#1600]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): 
A Harvester will never generate extra seeds when harvesting Mystical Agriculture crops. I tested it with a 9x9 farm for about 30 minutes, and it never harvested a seed, only the drops that the plant would give normally (essence and occasionally Fertilized Essence. I have found at least 2 other reports of this in the past through googling, but they were brushed off as "working at intended". I don't know if something has changed since then, but if you right click on a fully grown plant to "soft harvest" it (plant isn't broken, no seeds consumed, plant reverts to a non-mature state and has to grow again), the Mystical Agriculture plants WILL occasionally give you extra seeds that you can replant to expand your farm (at least in SkyFactory 4). This allows you to not only save a lot of Inferium Essence, but also lets you gain passive Inferium by putting the extra seeds you gain in a Seed Reprocessor. The only other way I can think of to automate my farm and still get the extra seeds is to use an Industrial Foregoing Plant Interactor, but this is very slow because it only harvests one plant at a time, has a large delay between actions, and has to scan through the entire area it's harvesting- additionally, I think it duplicates drops because it both harvests items to it's inventory, and drops items on the ground like it's "soft harvesting". If the Cyclic Harvester was able to generate Seed drops like intended, it would be a much better solution to farming!

**Comment by trunksbomb** [comment]
The "soft harvest" feature you mentioned is not a vanilla feature, it's added by another mod (likely [Quark's](https://quark.vazkii.net/#features) "Simple Harvest" feature).

I imagine that the issue lies in how Cyclic figures out what seeds to drop -- it pulls the seeds from the "default state" of the crop. Since all Mystical Agriculture crops share the same "default state", there likely is no seed populated in its default state's drop table.

**Comment by Oridjinn1980** [comment]
That's interesting! Although, it does make me wonder how something like the "Plant Interactor" from Industrial Foregoing is able to make it work... it seems to work almost too well, given that it drops items from the crop like normal, as well as pulls items into it's inventory. For that reason, I don't really think this is an issue with Mystical Agriculture or whatever mod allows you to harvest crops with a right click, but with Cyclic (specifically the Harvester). Additionally, when I did some new tests in response to your comment, I used a few different machines to see what would make seeds drop. Interestingly, if you use an Automated User from Cyclic, set to use (right click), it will soft harvest the crop like normal, and will continue to drop the extra seeds like intended, but of course it will just leave them all on the ground instead of pulling to it's inventory. While this is a little bit faster than the aforementioned Plant Interactor, it still won't harvest an entire area like the Harvester does, which is one of the main features I like about it! It also won't pull items into it's inventory, but I suppose it could be paired with an Absorption Hopper or other such item gatherer in order to automate farming.

**Comment by trunksbomb** [comment]
It was definitely an issue in Cyclic's implementation. I submitted a PR (linked above your comment) fixing this.

**Comment by Oridjinn1980** [comment]
Nice, great job!

**Comment by trunksbomb** [comment]
I just noticed that this was a 1.12 issue. I submitted the PR for 1.16 but the mod author, @Lothrazar, may backport it to 1.12 separately.

**Comment by Lothrazar** [comment]
going to leave this unchanged, plants are functionally harvested and changing how the feature works here would affect peoples existing setups as 1.12 is getting old. no seeds but we get crops working as intended at least.  player can always use other machines or by hand farming as before in older modpacks. Gif of testing it with MysticalAgriculture-1.12.2-1.7.5 and Cyclic 1.20.8+  
![one twelve harvester](https://user-images.githubusercontent.com/621529/115073511-49d29380-9ead-11eb-8764-cdb8c251f44a.gif)
