### ISSUE TITLE
Sack of Holding bug

### ISSUE THREAD

**Issue by sscards55** [PrinceOfAmber/Cyclic#161]
Dumping items from a sack of holding into an inventory will merge items with different NBT data

**Comment by PrinceOfAmber** [comment]
Yep, i just confirmed this testing with Carbon Paper with and without nbt data. thanks for reporting

**Comment by PrinceOfAmber** [comment]
Should be fixed in 1.8.5, let me know how it goes https://minecraft.curseforge.com/projects/cyclic/files/2344399
