### ISSUE TITLE
Solidification chamber 

### ISSUE THREAD

**Issue by Doughboy2783** [PrinceOfAmber/Cyclic#1617]
Minecraft Version: 
1.16.4
Forge Version: 
35.1.0
Mod Version: 
0.9.4
Single Player or Server:
single player
Describe problem (what you were doing; what happened; what should have happened):
I had put 3 stacks of leaves in the solidification chamber to make biomass. I logged off to eat dinner, came back and there was nothing in the machine. I tested it with snow to make ice, concrete powder and leaves again, those disappeared as well when I logged off and on. The power and water stayed, its just the items that vanished.  I also tested one with liquid biomass making grass blocks and that didn't have any issue.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
testing with leaves 
![solidifier](https://user-images.githubusercontent.com/621529/102703282-c025f880-4221-11eb-866a-f590aca9ea6d.gif)

**Comment by Lothrazar** [comment]
Testing concrete this time with a hopper below
![hopper](https://user-images.githubusercontent.com/621529/102703319-2f035180-4222-11eb-9f52-e5b638974913.gif)

**Comment by Lothrazar** [comment]
1.0.0 is released
