### ISSUE TITLE
Cables use an insane amount of block states

### ISSUE THREAD

**Issue by LatvianModder** [PrinceOfAmber/Cyclic#1618]
Minecraft Version: 1.16.4

Mod Version: 0.9.4

Single Player or Server: Both

Energy cable is (4 ^ 6) = 4096. Not great, not terrible. But item and fluid cables are (4 ^ 6) * 7 = 28'672 states. In total , 61'440 states. Now that's something. What I suggest doing is storing these properties in block entity instead of block states and rendering it as custom baked block model.

**Comment by Lothrazar** [comment]
That sounds like a good idea.  by "storing in block entity" that means as tile entity values, thats pretty easy.  

However, i have no idea what a baked model even is, let alone how to make a custom one.  

Looks like theres no documentation either https://mcforge.readthedocs.io/en/latest/search.html?q=baked

I did add this ShapeCaching logic from refined storage, as they use blockstates for cables too as do may mods. so the caching should help performance https://github.com/refinedmods/refinedstorage/commit/a9bfe70587fdea0b5c5c253ede4ae3908793a8b6
 


How can i learn more?

**Comment by LatvianModder** [comment]
I don't have any example of my own, but you can look at what implements IBakedModel. RS does it <https://github.com/refinedmods/refinedstorage/tree/mc1.16/src/main/java/com/refinedmods/refinedstorage/render/model>

**Comment by Lothrazar** [comment]
Ive been looking at refined storage.  But all those models are not usd for CABLES they are used for things like Disk drives, crafting grid, crafters,  Theres no CableModel ..   The cables still use normal states .  https://github.com/refinedmods/refinedstorage/blob/a9bfe70587fdea0b5c5c253ede4ae3908793a8b6/src/main/java/com/refinedmods/refinedstorage/block/CableBlock.java#L184

Also question: What even are the downsides of having so many block states? Unless someone has thousands of cables in the world, and the states are constantly changing every tick, i cant see where it would affect performance enough that the client would notice. 


I did notice that blockstates get cached sometimes, but there are some forge PRs related to it https://github.com/MinecraftForge/MinecraftForge/pull/7496

**Comment by Sunekaer** [comment]
Maybe look at Mekanism, from what i understand they do this

**Comment by Lothrazar** [comment]
Looks like mekanism has a baked model for a QUI Redstone adapter, a DriveArray, a Digital Miner, and Transmitter https://github.com/mekanism/Mekanism/search?q=ibakedmodel  
https://github.com/mekanism/Mekanism/tree/7ac23a606a155847d6d26d0b9503c0c74f5e672f/src/main/java/mekanism/client/render/obj
nothing on the surface appears to be used by cables/pipes

**Comment by Lothrazar** [comment]
Still no updates on this? quickly looked into this again.

Many other mods do the exact same thing cyclic does basically, for example Quark pipes use blockstates same way i do 


https://github.com/Vazkii/Quark/blob/b2ed0be1cfda53b1bbd1d36d19f76e9774daec3e/src/main/resources/assets/quark/blockstates/pipe.json

Unless ia single shred documentation in ibakedmodels in forge, or ANY ONE SINGLE mod that does cables as ibaked models, this feature is not possible.  

I already implemented the blockstate caching that RefinedStorage does anyway

**Comment by Lothrazar** [comment]
recently i deleted the 'extract' block state property, and changed it to only be a VALUE inside the existing directional block state.

So instead of "extract: up" , extract doesnt exist and its "up: cable" (cable meaning extract).  This reduces the states a ton

This : 
https://github.com/Lothrazar/Cyclic/commit/78d57a77b2ae7a2808248a89b1e266a704af6faa#diff-15450cbdd6c9dcddfc8479991773e0f4c23c3ac61917bfdd3742c16ace332b9cL85


Im sure Baked models great and wonderful, but based on previous comments, and forge having no official support or documentation for them, and this not causing any measurable performance difference or other user-facing issues, this refactor isnt worth it
