### ISSUE TITLE
Does the cyclic change something globally?

### ISSUE THREAD

**Issue by Forturian** [PrinceOfAmber/Cyclic#1619]
It's just that I only need a couple of items from this mod, and I'm wondering if it changes something important.

**Comment by trunksbomb** [comment]
It adds some innocuous flowers to worldgen and older versions add a couple of villager types, otherwise everything else added you'd have to specifically craft which you can disable with something like CraftTweaker.

**Comment by Lothrazar** [comment]
in 1.12 it does some gameplay changes in addition to adding items and blocks, but most are disabled by default or have configs to turn off.

In 1.16+ the mod only adds content such as blocks/items/fluids.  The one worldgen it has is the Cyan flower.
