### ISSUE TITLE
[1.16.4] Bug and Enhancement.

### ISSUE THREAD

**Issue by scottctd** [PrinceOfAmber/Cyclic#1620]
**Minecraft Version:** 
1.16.4

**Forge Version:** 
35.1.10

**Mod Version:** 
Cyclic-1.16.4-0.9.4.jar

**Single Player or Server:**
Server

**Describe problem (what you were doing; what happened; what should have happened):**
1. User and Forester do not work in FTB claimed chunks. (Fake player is forbidden in FTB claimed chunks? I don't know, maybe it is an issue of FTB chunks).
2. Maybe add config for adjusting the range of machines like item collectors and harvesters will be better?.
3. Maybe more later as my players found more.
4. Thanks for providing such a useful mod and I actually learned how to make a Minecraft mod following your examples.

**Log file link:**
Not applicable.

**Video/images/gifs (direct upload or link):** 
Not applicable.

**If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler**
Not applicable.

**Comment by trunksbomb** [comment]
In regards to your first point, others have had success by adding the fake player as an ally to their claimed chunks. Since the FakePlayer abides by the rules that normal players do, it makes sense that you'll have to specifically allow it to make changes in your chunks. I don't play SMP so I'm not sure what that involves but there's a screenshot in #1495 that I think shows the interface you need to get to.

**Comment by scottctd** [comment]
Ok, thanks for responding and I will try it later.

**Comment by trunksbomb** [comment]
@ScottCTD any luck adding the fake player to your claimed chunk?

**Comment by Mickimoo** [comment]
I attempted to add the fake players to my allies list with no result.

I would suggest trying to use the latest version of FTB Chunks and test again as it seems they pushed a patch in version 50 to fix fake players.
Commit: https://github.com/FTBTeam/FTB-Chunks/commit/e38bfbe65f8645c999a3b2703cebd119df3de521
<https://www.curseforge.com/minecraft/mc-mods/ftb-chunks/files/3134599>

**Comment by scottctd** [comment]
> @ScottCTD any luck adding the fake player to your claimed chunk?

@trunksbomb Sorry, I was busy and forgot to reply.. It did not work. I just switched to the latest version of FTB Chunks yesterday and I gonna test it if I had some spare time. Sorry my bro..

 By the way, why not use something like tree cutting algorithm instead of a fake player? I think to use an algorithm to search for available logs will be a better choice. Just like this: https://github.com/ScottCTD/Additional-Things/blob/main/src/main/java/xyz/scottc/additionalthings/blocks/treecutter/TileentityTreeCutter.java#L62

**Comment by scottctd** [comment]
Also, searching for all logs will avoid the issue of logs out of the working area, which is much more cleaner.

**Comment by trunksbomb** [comment]
There is an algorithm to find the tree, you'll need that for any method you choose.

While I don't know the original intent behind it, two good reasons I can see using a fake player is to respect chunk claims like FTB Chunks, and to be able to equip the Fake Player with a particular tool (say, an enchanted one).

**Comment by trunksbomb** [comment]
I just tested it.

1. Claim chunk
2. Place Forester
3. Give it something to chop down (a tree)
4. It chops it.
4a. Check FTB Chunks Allies list, see Forester's UUID in there automatically (I didn't add it).

**Comment by scottctd** [comment]
Yes I just tested it, it worked, with the latest FTB Chunk, in the singleplayer world.

However, my server with the same mod list failed..It's really wired. Maybe it is because of some legacy problems like my server world switched from an older version world to 1.16.4? I don't know but ... Okay it's all good. Thanks for replying!

Except.. Some saplings go out of the area?
![image](https://user-images.githubusercontent.com/35100768/102170225-cf7a0e80-3ece-11eb-8395-458983628ac9.png)

**Comment by Lothrazar** [comment]
as  Mickimoo  noted, this was fixed on the other side, nice
