### ISSUE TITLE
Bug with the GPS

### ISSUE THREAD

**Issue by Halosymph** [PrinceOfAmber/Cyclic#1624]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.19.14

Single Player or Server: Solo

Describe problem (what you were doing; what happened; what should have happened):

When i hold a GPS in my hand normally i should see with a blue square but i don't see it. I searched in the command part if somethings talk about that and I already searched on internet, without clues.. I don't know if this is a bug or if the issue has already been treated so I'm sorry if it is !

Have a nice day/night and thanks for your help ;)

**Comment by Lothrazar** [comment]
did you see in the item tooltip its coords? once you pick a spot. is optifine on.  maybe the latest 1.20.8 + has an update. maybe it was from another dimension
