### ISSUE TITLE
[1.16.4] Magma Anvil Broken

### ISSUE THREAD

**Issue by Dragnier** [PrinceOfAmber/Cyclic#1627]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 0.10.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Piping lava into the Magma Anvil does nothing but void the lava; the tank does not fill and it will not repair things. Cannot place lava in via bucket nor do magma blocks go in. Pretty sure piping lava in should fill the tank and power the device to repair items placed in it's inventory.

Log file link:

No crash; no log.

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by gabry280** [comment]
also the powered diamon anvil is broken

**Comment by DatenThielt** [comment]
I believe this should be re-opened as the bug seems to have resurfaced in mod version 1.16.5 (1.2.1)  Lava anvil when piping into it does not  fill up, and voids the lava instead.
