### ISSUE TITLE
Need Help Figuring Out Disenchanter for Cyclic Modpack

### ISSUE THREAD

**Issue by ThePandaMan135** [PrinceOfAmber/Cyclic#1630]
Minecraft Version: 1.16.1

Forge Version: 32.0.108

Mod Version: 1.16.1

Single Player or Server: Server (with only a couple other people)

Describe problem (what you were doing; what happened; what should have happened): I am trying to use the disenchanter to get a Fortune III enchantment off of a Golden Pickaxe. The problem is,  I do not know how to get redstone power into it. I have tried looking up solutions, but nothing is coming up except for how to use it rather than how to put power into it.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
It's the same as getting power to any other device, so I'm guessing you don't have much experience with energy-based machines?

If you've only got Cyclic, you can do one of the following:
1. Use a Peat Farm + Peat Generator to generate power, then pipe it in with energy cables.
2. Cheat in a Creative Battery and put it next to the Disenchanter
3. Turn off energy consumption in the config file, then you won't have to worry about power.

If you've got other mods, then use any power generation method from one of those and either place the generator/battery next to the Disenchanter, or pipe it in with Cyclic energy cables or cables from another mod.

**Comment by ThePandaMan135** [comment]
Thank you very much. I hadn't tried a generator from the Cyclic mod (I didn't even know it had any). I was using the heat generator from the Mekanism mod.
