### ISSUE TITLE
Item repaired/disenchanted from grindstone can't be used in uncrafting grinder.

### ISSUE THREAD

**Issue by BrokenValkyrie** [PrinceOfAmber/Cyclic#1632]
Minecraft Version: 1.16.4

Forge Version: 35.1.12

Mod Version: 1.16.4-0.10.1

Single Player or Server: Both

Any tools/weapon/armor that has been used on the vanilla grindstone can't be used in the uncrafting grinder. Item repaired using vanilla repair can still be used in the uncrafting grinder.

I think this is because of the NBT tag Repair Cost. Using anvil to repair item also prevent it from being usable in the uncrafting grinder.

**Comment by Lothrazar** [comment]
adding some configs to allow uncrafting items that have been repaired/enchanted/damaged etc.
