### ISSUE TITLE
Excavate not working on nether quartz

### ISSUE THREAD

**Issue by MacChuck** [PrinceOfAmber/Cyclic#1635]
Minecraft Version: 1.16.4

Forge Version:  unsure, playing on the FTB Presents DW20 1.16.4 pack version 1.1.1

Mod Version: 1.16.4-0.10.1

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened): using an Excavate 3, Fortune 2 pickaxe, does not excavate Nether Quartz ores. Fortune seems to be working. Excavate works on other ores including Nether Gold.

Log file link: n/a
Video/images/gifs (direct upload or link): n/a

**Comment by Lothrazar** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3150540
