### ISSUE TITLE
Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#1638]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Cyclic v1.0.0`

Waterlogging of all the non-full blocks would be nice to see, especially for decorations, such as the dice, cables, or the trash void.

All transparent blocks also does not render correctly underwater, such as with the Tempered Glass, scaffolding, Fishing Net, tanks, peat farm, pharos beacon, or laser cell. There is a boolean called `shouldDisplayFluidOverlay` that can fix this.

![2020-12-21_21 31 45](https://user-images.githubusercontent.com/12000593/102845800-fc00bf80-43d3-11eb-84b8-fbfd7e1d76d8.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3154443

**Comment by WenXin20** [comment]
Thanks! Although adding `shouldDisplayFluidOverlay` to non-full blocks, like dice or the fan doesn't actually make them waterlogged. It's usually just used for full-sized blocks such as custom glass blocks.
