### ISSUE TITLE
New Scythes

### ISSUE THREAD

**Issue by Rithenar** [PrinceOfAmber/Cyclic#1640]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 0.10.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Need more information on how to add data tags for new Scythes. Is that an external/config process or something in game we are missing?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by trunksbomb** [comment]
As in adding new things that scythes can break/harvest? You do it through Minecraft's JSON tag system. https://minecraft.gamepedia.com/Data_Pack

![image](https://user-images.githubusercontent.com/1904331/102946805-b86b8b80-448f-11eb-87f6-11176ef7d970.png)

**Comment by Lothrazar** [comment]
this slightly changed recently. planning to do either a wiki or an Example standalone data pack for this eventually https://github.com/Lothrazar/Cyclic/projects/4
