### ISSUE TITLE
[1.16.4] Harvester has no inventory and does nothing

### ISSUE THREAD

**Issue by GamerBah** [PrinceOfAmber/Cyclic#1642]
**Minecraft Version:**
1.16.4

**Forge Version:**
35.1.13

**Mod Version:**
0.10.1 and 1.0.0

**Single Player or Server:**
Single Player / LAN Server

**Describe problem (what you were doing; what happened; what should have happened):**
Harvester has no inventory and doesn't do anything when powered with redstone / energy.

**Log file link:**
[latest.log](https://github.com/Lothrazar/Cyclic/files/5738162/latest.log)

**Video/images/gifs (direct upload or link):** 
![image](https://user-images.githubusercontent.com/6743436/103061660-e4a30d00-4560-11eb-8b66-6cfefe7d554b.png)

**Comment by Xyclade** [comment]
Harvester is working fine for our mod pack on with the same versions. You need to have energy and redstone on always on or with a lever:
![image](https://user-images.githubusercontent.com/3858419/103085087-ea403780-45e0-11eb-9285-addbde795ceb.png)

The harvester needs to be aimed with the black circle towards the fields:
![image](https://user-images.githubusercontent.com/3858419/103085115-ff1ccb00-45e0-11eb-9a97-eb75936acb66.png)

**Comment by Lothrazar** [comment]
yep it does not speed up growth, crop needs to be fully grown on its own, then you need something to collect the drops that are items on the ground

**Comment by Dashboy1998** [comment]
I also have this issue with the same version of Minecraft, Forge, and the mod version is 1.0.0. I can only see the inventory of the item collector, I cannot see it on any other machine.

Special note I am using All The Mods 6 - 1.3.7

**Comment by trunksbomb** [comment]
The Harvester does not have an inventory, its only function is to gently harvest fully grown crops, by way of dropping the crop on the ground where it was harvested.

**Comment by GamerBah** [comment]
Ah, so the functionality was changed since 1.12 I assume. That's good to know!

**Comment by choekstr** [comment]
My 1.0.0 and 1.0.2 version doesn't show render preview either, but it is harvesting on both and is just subtle.  The item collector next to it was the only way I knew it was working as things started showing up in it.  The render preview DOES work on the item collector though.

**Comment by Lothrazar** [comment]
Latest version has fixes.   Suggested to use Item Collector to grab drops
