### ISSUE TITLE
[1.16.4] [Request] Port Transmission Nodes

### ISSUE THREAD

**Issue by Hekkmac** [PrinceOfAmber/Cyclic#1643]
I was playing Skyfactory 4 with the 1.12 MC Version and Cyclic.

Using the Transmission Nodes for Fluids/Energy/Items was always a pleasure. Is there any information about if you going to port these to 1.16.4? Maybe with the input-side configuration update mentioned in an issue here?

Happy chrismas.
Thanks for your time!

**Comment by trunksbomb** [comment]
We've both been working on porting 1.12 features to 1.16 at a steady pace, I'm sure one of us will get to it soon!

**Comment by Lothrazar** [comment]
moved to https://github.com/Lothrazar/Cyclic/projects/4
