### ISSUE TITLE
[Request] Ability to disable certain potions

### ISSUE THREAD

**Issue by IchHabeHunger54** [PrinceOfAmber/Cyclic#1644]
I am making a modpack where the haste potion is also added by another mod, and I prefer the other mod's haste over the one added by Cyclic (since theres a longer variant too). Since both mods have no config option to disable it, I used JEI to hide Cyclics potion. I would, however, prefer a config option to remove it (like, also removing the recipe, etc)

On top of that, I would also like an option to change the items required to brew it. (Specifically, Id like to change the item required for paralyze.)

**Comment by Lothrazar** [comment]
These recipes can be removed and changed with craft tweaker  https://www.curseforge.com/minecraft/mc-mods/crafttweaker
