### ISSUE TITLE
Peat Farmer has no energy bar, crash when mouseover

### ISSUE THREAD

**Issue by ShinyLuxray** [PrinceOfAmber/Cyclic#1647]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Updated Cyclic mod from 1.20.3 to 1.20.8
Had a Peat farmer, went to GUI, energy (RF) bar was missing. When hovered over the area the bar should be, the game would crash.

Peat farmer was working fine 1.20.3
Log file link:

[log.txt](https://github.com/Lothrazar/Cyclic/files/5742538/log.txt)

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/19845217/103143664-e566ab00-46e8-11eb-9c82-523a81b4dd2b.mp4

Let me know if more info is needed.

**Comment by Azafraia** [comment]
I have the same problem ://

**Comment by Lothrazar** [comment]
config change of 
 
` I:peat_farm=64`
 
 to any number > = will fix for now.  and there will be a 1.20.9 release eventually to fully fix it
