### ISSUE TITLE
Crash caused by Caving Torch placer in 1.16.4

### ISSUE THREAD

**Issue by ProfessorBiddle** [PrinceOfAmber/Cyclic#1648]
Minecraft Version: 
1.16.4
Forge Version: 
35.1.13
Mod Version: 
1.0.0
Single Player or Server:
Singleplayer
Describe problem (what you were doing; what happened; what should have happened):
I was in a large dark area with the caving torch placer in my inventory, and my game froze and then crashed.

Log file link:

https://pastebin.com/JvLfxiGd

Video/images/gifs (direct upload or link):

**Comment by trunksbomb** [comment]
The crash was definitely caused by the Caving Torch Charm but I'm not able to replicate in a test world.

**Comment by Lothrazar** [comment]
ConcurrentModificationException errors tend to be very inconsistent

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3154443

**Comment by Jkosio23** [comment]
Time to reopen it.
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Cyclic Version: 1.1.6
Singleplayer

Specifically was using a Botania (1.16.4-411) Terra Shatterer in addition to the Ring of Loki to extend it's range.

https://paste.gg/p/anonymous/51e2beb0c33f473b8b71eb94ffb8e814
