### ISSUE TITLE
Feature Request: Experience Confections quicker conversion and consuming

### ISSUE THREAD

**Issue by Shorepion** [PrinceOfAmber/Cyclic#1651]
Minecraft Version: 1.16.3/.4

Request:

It would be awesome if you could Shift+Right Click with sugar on Experience Pylons to convert a whole stack (or the amount you are currently holding) to Experience Confection.
Takes so much time that its converting only one by one.
Same goes for the comsuming of Experience Confection stacks.

**Comment by trunksbomb** [comment]
This is pretty quick.

![cyclic_exp](https://user-images.githubusercontent.com/1904331/103176694-ec550100-4841-11eb-8ef9-e800585a292e.gif)

**Comment by Shorepion** [comment]
1) not quicker than a whole stack at once ;)
2) All RF machines are disabled in my pack.
3) quick consuming aren't working with machines
But its funny though, Ill give you that :D

**Comment by trunksbomb** [comment]
1. Maybe but I can't think of any other mods that let you consume entire stacks at once.
2. That's a personal restriction that shouldn't be coded around.
3. Here https://imgur.com/T2EhatA

Point is, Cyclic is more about giving you the tools so you can figure it out yourself, rather than doing it all for you.

**Comment by Shorepion** [comment]
Alright, makes sense 👍
maybe as a optional config option?

**Comment by Shorepion** [comment]
1. 'Global Xp' for example lets you store or retrieve all xp at once with one click (but its not able to collect xp from ground)
EDIT: Same goes for the Experience Obelisk from Ender IO

**Comment by Lothrazar** [comment]
Side note, in config each machine has the option to run with power required = 0 and it can run without RF.

im not sure how valuable this change would be. this is my speed when i interact and hold down the button , seems not too bad. 
![1651](https://user-images.githubusercontent.com/621529/103420686-6f7d9c00-4b4d-11eb-8fa2-f28f207a2513.gif)

**Comment by Shorepion** [comment]
> Side note, in config each machine has the option to run with power required = 0 and it can run without RF.
> 
> im not sure how valuable this change would be. this is my speed when i interact and hold down the button , seems not too bad.
> ![1651](https://user-images.githubusercontent.com/621529/103420686-6f7d9c00-4b4d-11eb-8fa2-f28f207a2513.gif)

Oh ok. That actually is very good hint👍🏻 thanks.
