### ISSUE TITLE
[1.16.4] Server Crash - Storage Bag - Pickup Mode Button

### ISSUE THREAD

**Issue by Xechorizo** [PrinceOfAmber/Cyclic#1655]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 1.0.0 (pack ATM 6-1.3.7)

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Open the Storage Bag, click the top-left button. The tooltip appears, the button label changes, followed by a server crash.  Can replicate and provide further details as needed.

Log file link: https://pastebin.com/mpZWi5rn

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/14857131/103271736-46f07900-4978-11eb-9948-5a0a82f4f139.png)

**Comment by trunksbomb** [comment]
Fixed in #1646 and released in v1.0.1.
ATM6 hasn't updated yet.

Also you listed the pack version instead of the mod version above -- the mod version in ATM6 is 1.0.0.

**Comment by Xechorizo** [comment]
@trunksbomb Thank you! Will correct and anticipate ATM's update.
