### ISSUE TITLE
Empty workbench - clicking "Empty the grid" button crashes server

### ISSUE THREAD

**Issue by Lordmau5** [PrinceOfAmber/Cyclic#1656]
Minecraft Version: 1.16.4

Forge Version: 35.1.15

Mod Version: 1.16.4 1.0.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
- Empty workbench
- Click "Empty the grid" button
- Server crashes

Maybe this also happens with the other buttons?

Log file link:
[crash-2020-12-30_19.01.29-server.txt](https://github.com/Lothrazar/Cyclic/files/5755197/crash-2020-12-30_19.01.29-server.txt)

**Comment by khazoda** [comment]
Duplicate of #1652

**Comment by Lordmau5** [comment]
I swear to god I was searching for "Workbench" yesterday and nothing came up.

Sorry for the duplicate! Closing this now.
