### ISSUE TITLE
Structure Builder does not set "User Placed" data tag for leaves.

### ISSUE THREAD

**Issue by kondrik** [PrinceOfAmber/Cyclic#166]
When using leaves in the Structure Builder, if you break any leaf block or break a log that has been placed next to a leaf block, the leaves decay.  

Because a player obviously wanted the leaves placed, shouldn't the Structure Builder apply the data tag that tells the game the block was placed by a player & shouldn't decay?

**Comment by PrinceOfAmber** [comment]
Yes, all blocks should act as if placed by a player.

**Comment by PrinceOfAmber** [comment]
Fixed in 1.8.7 
https://minecraft.curseforge.com/projects/cyclic/files/2345006
