### ISSUE TITLE
Slots mixed up for auto-crafting on solidifier

### ISSUE THREAD

**Issue by uecasm** [PrinceOfAmber/Cyclic#1661]
Minecraft Version: 1.16.4

Forge Version: 35.1.15

Mod Version: 1.16.4-1.0.1
Refined Storage version: 1.9.9
JEI version: 7.6.0.62

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Interaction with JEI and Refined Storage seems weird, as if the slots are mixed up.  Specifically:

1. Clicking the + icon in JEI into an RS pattern grid will put the output of the recipe into an input slot, along with the inputs.
2. Using an RS crafter to insert items ends up putting the input items all into the first slot, then the machine doesn't run since it wants the same item spread across three slots.  It would be nice if it would auto-balance piped input.
3. Using an RS importer extracts the items from the input slots (which is normally not permitted for most machines) and does not extract the items in the output slot (which again suggests that the slots aren't classified correctly somehow).

**Comment by uecasm** [comment]
Ok, ignore #3, that was a sidedness issue.  It works if the importer is on the bottom.  (It would be nice if there were better documentation on these things.)

The other points remain valid, however.  (For the moment I've gotten it to work by using an exporter to keep the machine full, instead of only crafting on-demand as I originally wanted.)

**Comment by Lothrazar** [comment]
https://github.com/mezz/JustEnoughItems/issues/2211

**Comment by uecasm** [comment]
Weirdly, I made a different solidifier-based setup, this time turning terracotta+water into clay, and the RS importer refused to accept the clay blocks from any side, including the bottom.  But I ended up putting a hopper on the bottom and then the importer on that, and that seemed to work.  As mentioned I did previously have the importer working on a different solidifier (with different recipe and location), although admittedly that was also with the versions listed above (I'm now running slightly newer ones).

**Comment by stefanak-michal** [comment]
https://github.com/refinedmods/refinedstorage/issues/2843

**Comment by uecasm** [comment]
I was just about to add that on closer inspection it looked like the problem was that the implementation of `ItemStackHandlerWrapper` had completely the wrong logic for managing the output slot (and wasn't implementing all required methods properly even for the input slots), but it looks like @BlueAgent has beaten me to it, and with a patch.
