### ISSUE TITLE
[1.16.4] In consistencies with its range (item collector + harvester oddity).

### ISSUE THREAD

**Issue by Ruchian** [PrinceOfAmber/Cyclic#1662]
Minecraft Version: 1.16.4
Forge Version: 35.1.13
Mod Version: 1.0.0
Single Player or Server: Dedicated Server

The item collector collects in an area of 16 by I'm not sure what. It's inconsistent. 
Depending on the angle, one size indeed does reach the 8 blocks in length, but the other side only reaches 7, giving a total length of 16. This effect is also present in the width and for a player its difficult to predict where it will pick stuff up. For some reason the rendering of the range isn't displayed properly either, as in, in random angles you see something, on most angles its invisible. I am not sure why.

The item collector is supposed to be in the center. According to my findings it should have a range of 8, meaning, it should be 17 in length at least, and likely 17 in width, but it is not.

The harvester is supposed to collect from crops in front of it, but instead it is taking up one of the spaces itself. Also for some reason it is slow even when it has enough power. It seems to pluck crops randomly here and there, every... now and then, which could be related. There are seconds between its actions at least. I am mentioning this because I think it might be confused as to where it should harvest due to it being in that range for some reason.
The range preview doesn't work, likely because the harvester is inside its supposed range.

**Comment by tanyan-tanyan** [comment]
> For some reason the rendering of the range isn't displayed properly either, as in, in random angles you see something, on most angles its invisible. I am not sure why.

It looks like the preview render disappears exactly as soon as you turn away from the machines, as in when the machine is no longer in your sight.

Also, can confirm I get the same issue with the harvester render not previewing on Cyclic version `1.0.2`.

**Comment by Lothrazar** [comment]
The intention is to only perform on the blocks that are within the hilighted area (border included), so looking into this.

And yes should be a square, with the center offset from the machine going the same in all directions
