### ISSUE TITLE
Feature request: Side Configuration for item I/O : improve automation (any machine with in and out slots such as disenchanter)

### ISSUE THREAD

**Issue by CKY-** [PrinceOfAmber/Cyclic#1665]
Minecraft Version: 1.16.4

Forge Version:  35.1.13

Mod Version: Cyclic-1.16.4-1.0.0.jar

Single Player or Server: Server 

Describe problem (what you were doing; what happened; what should have happened):
Items applied to most Item blocks; "power anvil, disenchanter, crafter, solidification chamber" when feeding items will apply the to the output and input at the same time, not allowing the machine to work. there is no input output configuration for feeding items please give us the ability with a user defined side configurations for inputs and outputs.

**Comment by Lothrazar** [comment]
instead of sided i just fixed the in/out automation.

SO a hopper inserting into disenchanter goes into the left slots, and a hopper/cable/pipe can only pull from output slots. same for crafter and solidifier.

I think i forgot to do anvils , ill test and maybe do a new release lol
