### ISSUE TITLE
[1.16.4] Crash when using Excavate enchantment.

### ISSUE THREAD

**Issue by Gbergz** [PrinceOfAmber/Cyclic#1666]
Minecraft Version: 1.16.4

Forge Version: 35.1.28

Mod Version: 1.0.2

Single Player or Server: Server (maybe SP too?)

Describe problem (what you were doing; what happened; what should have happened):
Used the Excavate enchantment and the server decided to crash.

Log file link: (crash log)
https://hatebin.com/zwcvuwpfrg

**Comment by Leyzr** [comment]
It seems to happen instantly if you use a weapon that can break blocks instantly. 
https://hatebin.com/czbqtljylk

**Comment by FullMetalMaster** [comment]
yeah got the same crash on my server
