### ISSUE TITLE
cyclic workbench "clear grid" button crashes game

### ISSUE THREAD

**Issue by ellisten** [PrinceOfAmber/Cyclic#1667]
Minecraft Version: 1.16.4

Forge Version: 35.1.15

Mod Version: 1.16.4-1.0.1

Single Player or Server: single player and server, sort of

Describe problem (what you were doing; what happened; what should have happened): Opened workbench, clicked "clear grid," game immediately crashes. On a server, the server crashes and you are sent to the main menu. In a single player world Minecraft crashes to desktop.

Log file link: https://paste.ee/p/CEy8e

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/77031152/103714101-73615200-4f83-11eb-917e-a3186ccdfd95.mp4

**Comment by ellisten** [comment]
The other 2 buttons appear to work fine, or at least they don't crash your game.

**Comment by khazoda** [comment]
You're one version behind the current release which came out 5 days ago. It fixed this issue. 
![image](https://user-images.githubusercontent.com/42558699/103731979-5b6aec00-4fde-11eb-9734-9a802ccad65c.png)

**Comment by Lothrazar** [comment]
Yep, thanks for the report. Khazoda is correct  https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3154443
