### ISSUE TITLE
[1.16.4-v1.0.1] Mob Spawner Config - Empty Sack of Holding 

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [PrinceOfAmber/Cyclic#1669]
Minecraft Version: 1.16.4

Forge Version: 35.1.15

Mod Version: 1.16.4 1.0.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Per our discussion before, 
Trying to allow spawner pickups on DW20 1.16 pack with Sack of Holding, removed the spawner from the blocking config and restarted the server. still said "disabled by config" or something along those lines, attempted to remove the rest of the blocks in that list for testing and no luck after the restart, still same message.

what should have happened, well pick up spawners now :P 

Log file link:

no log

Video/images/gifs (direct upload or link): 

no videos to show, only way to test is by replicating. 

Thanks Loth! Appreciate you as always.

**Comment by Lothrazar** [comment]
Just did some testing.  You might have to change it in both config files (the one on the server, and the one on your client, both are in the /config/ place not the weird one. and maybe reboot both), in the currently released version anyway.
Can you check out both files?

Recorded my test also 
 

![1669](https://user-images.githubusercontent.com/621529/103736681-8b49cd80-4fa5-11eb-9e6d-608cda6b4270.gif)

**Comment by EPIICTHUNDERCAT** [comment]
Interesting, I changed the config on my client and the server and it worked now :P weird. we can close this out now, unless that in itself is a bug.
