### ISSUE TITLE
Crafting Machine consuming entire item instead of lowering durability (MysticalAgriculture)

### ISSUE THREAD

**Issue by Mr404ServerError** [PrinceOfAmber/Cyclic#1670]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: Cyclic-1.16.4-1.0.2       MysticalAgriculture-1.16.4-4.1.4

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Compatibility with MysticalAgriculture. 

When using the Crafting machine, any recipe that requires the "Infusion Crystal" consumes the entire crystal, instead of lowering its durability. 

![BeforeCraft](https://user-images.githubusercontent.com/34142779/103719876-de5c5a00-4f7e-11eb-9cdc-a307bfb1e479.png)
![AfterCraft](https://user-images.githubusercontent.com/34142779/103719882-e5836800-4f7e-11eb-814c-88703bfb5c8d.png)

**Comment by T-Smith01** [comment]
@Lothrazar Running a newer version of the mod (4.2.6) on 1.16.5 and had the same issue, but with the master infusion crystal instead. Was this fix also done for the master infusion crystal? I am sure you have done many changes since this one, so figured I would bring it up in case it was overlooked
