### ISSUE TITLE
Auto pickup not working

### ISSUE THREAD

**Issue by SnoeyNoey** [PrinceOfAmber/Cyclic#1672]
Minecraft Version: 1.12.2

Forge Version: 12.23.5.2847

Mod Version: 
Cyclic-1.12.2-1.19.18.jar

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
Turn on matching or even all deposit into bag and nothing happens goes straight to inventory.

should just deposit into the bag(tried hotbar and not hotbar)

Log file link:

Video/images/gifs (direct upload or link):

**Comment by SnoeyNoey** [comment]
I think the issue is linked to multiple bags being used.

**Comment by Lothrazar** [comment]
can you confirm and please test in latest Cyclic-1.12.2-1.20.8.jar version https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3089348

**Comment by Lothrazar** [comment]
working as intended as seen . as stated above if multiple bags have pickup only one of them of course gets the items 
![1672](https://user-images.githubusercontent.com/621529/115074596-c31eb600-9eae-11eb-8a52-7682a3e0b968.gif)

**Comment by SnoeyNoey** [comment]
Well with filters it would be thought that multiple bags can be used but sadly it can’t but other mods do so its okay, I just was trying something it wasn’t intended for. Sent from Mail for Windows 10 From: SamSent: Friday, April 16, 2021 3:25 PMTo: Lothrazar/CyclicCc: SnoeyNoey; AuthorSubject: Re: [Lothrazar/Cyclic] Auto pickup not working (#1672) working as intended as seen . as stated above if multiple bags have pickup only one of them of course gets the items—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
