### ISSUE TITLE
Can you support mystical agriculture for harvester?

### ISSUE THREAD

**Issue by ArmoID** [PrinceOfAmber/Cyclic#1674]
Minecraft Version: 1 16 4

Forge Version: 35 1 7

Mod Version: 1 16 4 - 1 0 0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
I'm surprised it doesnt work already.  I bet those plants are doing something really funky so maybe i can do something

**Comment by Lothrazar** [comment]
oh it works actually .  it harvests a bit slow so i might try to speed it up a bit but yea 
![mystical](https://user-images.githubusercontent.com/621529/103970095-4a27f980-511c-11eb-944d-b306dae45e77.gif)

**Comment by ArmoID** [comment]
I don't know if it is possible to write further here... Firstly, I would like to thank for the bug fix. Now I have one new problem: minecraft does not open my old world anymore with an updated mod for version 1.1.0. I would like to play on my own world, and not create a new one.
Secondly in version 1.0.0 there was a problem with the peat generator. After setting it up, it worked fine, but after some time (about a couple of real minutes), it literally stopped transmitting energy, keeping it in itself. To solve the problem, you had to break and put the block in the same place.

**Comment by Mr404ServerError** [comment]
I second the peat generator issue, but I have only seen it in single player. 

@Lothrazar As for speeding up the auto harvester, I have a question as to the design. I might be reading the code wrong, but it looks like it picks a random block in the harvest range about twice a second. This feels slightly frustrating as the will be plants waiting to be harvested, but they don't get touched for a long period of time. Why not have the harvester check the entire harvest area every 5-10 seconds instead? 

Edit: I just saw the release notes, I look forward to testing the new method :)
