### ISSUE TITLE
Can't choose Forester/Harvester size

### ISSUE THREAD

**Issue by stromseng** [PrinceOfAmber/Cyclic#1675]
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.16.4-1.0.2
Modpack:  All the mods 6 1.3.9b

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
I do not get the adjustable slider on the forester/harvester to select the area it should harvest. 

Log file link:

Video/images/gifs (direct upload or link): 
![javaw_MGfSNjxKer](https://user-images.githubusercontent.com/24990129/104058334-d8bb7a00-51f3-11eb-9b32-c081e9d031cf.png)

**Comment by ArmoID** [comment]
Try the latest version of the mod(1.1.0), the author has fixed everything.
https://www.curseforge.com/minecraft/mc-mods/cyclic
