### ISSUE TITLE
Item user and ender bookshelf automation duping enchanted books

### ISSUE THREAD

**Issue by cainamar** [PrinceOfAmber/Cyclic#1676]
Minecraft Version: 1.16.4 (dw20 pack)

Forge Version: 35.1.15

Mod Version: 1.0.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

attempting to automate the ender bookshelf with an item user results in the book staying in the user and endlessly duplicating into the shelves

Log file link: [latest.log](https://github.com/Lothrazar/Cyclic/files/5789254/latest.log) (I wasn't sure what you wanted here so I hope I gave the right file)

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/53030836/104060865-8ebb9f80-51c5-11eb-8b67-76601f56dc58.mp4

**Comment by cainamar** [comment]
additional related note: if you break a shelf with books in it, they stack and behave strangely when trying to separate the stacks

https://user-images.githubusercontent.com/53030836/104063349-05f33280-51ca-11eb-8da7-5587dc1f005b.mp4

**Comment by MichaelNZ404** [comment]
Pull request in. https://github.com/Lothrazar/Cyclic/pull/1683


https://user-images.githubusercontent.com/4734163/104119428-e51e0f00-537a-11eb-9ce4-3afb01b7a1f9.mp4
