### ISSUE TITLE
Items get stuck inside item cables

### ISSUE THREAD

**Issue by MichaelNZ404** [PrinceOfAmber/Cyclic#1677]
**Minecraft Version:** 1.6.4
**Forge Version:** 35.1.36
**Mod Version:** 1.1 & 1.0.1
**Single Player or Server:** SP(but presume both)
**Describe problem:**

When items go into pipes, it checks all directions **excluding** its ingestion direction. This causes items to get stuck when they enter a pipe with no valid outputs. The items are frozen in the network until the pipe segment is broken.

PR open (https://github.com/Lothrazar/Cyclic/pull/1678)

**Video/images/gifs (direct upload or link):** 
Video of bug (extracting from multiple chests):

https://user-images.githubusercontent.com/4734163/104119801-e270e900-537d-11eb-8ebe-391fcfc1ddf8.mp4

Video of bug (dead end branches):

https://user-images.githubusercontent.com/4734163/104119797-de44cb80-537d-11eb-8bea-3a0cd2083328.mp4

Video of fix (extracting from multiple chests):

https://user-images.githubusercontent.com/4734163/104119802-e4d34300-537d-11eb-88ce-5504edca468d.mp4

Video of fix (dead end branches):

https://user-images.githubusercontent.com/4734163/104119800-e13fbc00-537d-11eb-884f-a44c51e73623.mp4

**Comment by Lothrazar** [comment]
Another simple test configuration.

items should not get stuck in the dead end.  
![2021-01-10_10 07 28](https://user-images.githubusercontent.com/621529/104131543-c93f4c80-532b-11eb-925e-ce5941ba958e.png)
