### ISSUE TITLE
Uncrafting Grinder outputting into Interface (Refined Storage) causes game to crash.

### ISSUE THREAD

**Issue by stefan7080** [PrinceOfAmber/Cyclic#168]
Facing the output of the Uncrafting Grinder into the Interface of the Refined Storage mod causes a gamecrash.

http://pastebin.com/yrScGT9H

**Comment by PrinceOfAmber** [comment]
Ah thanks for reporting this, ill check it out

**Comment by PrinceOfAmber** [comment]
ive got a fix to stop it crashing. but right now its not inserting into the inventory.  Looks like Refined storage didnt use the standard inventory interface IInventory, its using a different forge layer ive never seen before.  So ill release the crash hotfix and then ill have to work on this new IItemHandler thing in a later update
