### ISSUE TITLE
Name Tags Always Drop From Named Enemies

### ISSUE THREAD

**Issue by SalTheGunzerker** [PrinceOfAmber/Cyclic#1685]
Minecraft Version: 1.10.2 

Forge Version: 123

Mod Version: 1.10.15 

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I bought a minecraft server a few days ago and me and my friends chose SkyFactory 3, a day after we added Cyclic mod in our mob farms, we were getting swarms of custom name tags from all the named enemies, and this hadn't happened until I added Cyclic. Is there anything in the config to fix this?

**Comment by Lothrazar** [comment]
Yeah, if you look up cyclicmagic.cfg on the server and client, in /config/ folder you can set the setting to false, and then reboot

"   # When an entity dies that is named with a tag, it drops the nametag [default: true]
        B:"Name Tag Death"=true
        "
        
        
                B:"Name Tag Death"=false
        


https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/cyclicmagic.cfg#L510

**Comment by Lothrazar** [comment]
let me know how it turns out when you try it
