### ISSUE TITLE
Peat Generator stops working

### ISSUE THREAD

**Issue by Elcar903** [PrinceOfAmber/Cyclic#1686]
Minecraft Version: 1.16.4

Forge Version: 35.1.29

Mod Version: Cyclic-1.16.4-1.0.2

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

The Peat Generator will stop generating power after a few minutes, 
and sometimes you can either break the generator or take the fuel out of the 
Generator then put it back in.

It seems to get stuck on 55040 RF a lot too.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by MichaelNZ404** [comment]
This is fixed in the latest version, see https://github.com/Lothrazar/Cyclic/issues/1681

**Comment by Elcar903** [comment]
thank you
