### ISSUE TITLE
[Questions, not issues] How the Ender Library works

### ISSUE THREAD

**Issue by greenking13** [PrinceOfAmber/Cyclic#1691]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Probably both, but the build is currently on a server

Describe question:

To give a bit of preface before the questions for why I am asking the questions. If you just want to know the questions, feel free to skip down to the numbered list.
Anyways, I am attempting to build an ender library to store all enchantments I can possible get within Roguelike Adventures and Dungeons, which comes out to being 399 enchantments, excluding anything I can get that can surpass the regular level caps. (Unbreaking X from a flint and steel is like what is being excluded for good reason.) All these enchantments are coming directly from your mods Automatic Fishing Nets (Abbreviated AFNs from now on.), and since apparently a mending fishing rod in your AFNs last forever, I am backlogging on books, hence the ender library plan. Simple math would make the assumption that with 399 enchantments in game, I would need 399/4 ender bookshelves, since each bookshelf can hold 4 enchantments, which is 100 ender bookshelves. That's a lot, and considering this system might be ran indefinitely, or another two weeks depending on how the other two people I'm playing with start to feel about the pack, I could acquire an absolute ton of enchantments. So, the questions.

1. How are ender bookshelves and the ender library interconnected? Does the library assume it is on the lowest level and looks up (which seemed like the case), does it scan for adjacent bookshelves and have a somewhat recursive algorythm to detect the number of connected shelves, does the ender library have a hard limit on how many blocks it can extend in one direction? (For example, 7 blocks in each direction to avoid extending over a chunk in size, or 16 blocks in height if my first assumption is right.)

2. Is there a coded limit for the number of duplicate enchantments that can be stored in one space, or a theoretical limit? (Max=256 copies VS Max=2^31)

Those are my two questions. Thank you very very much for any info you can give, and I hope you have a wonderful day tomorrow! (Or today, whichever one daytime lies in.)
-Michael (greenking13)

(Note: The follow image does not pertain to answering the questions, it's just a visual for the number of enchantments, and some math I did in paint.)

![numberOfEnchantedBooks](https://user-images.githubusercontent.com/9355993/104419326-eea3a480-553d-11eb-9ed0-b09e7c6a9a57.png)

**Comment by greenking13** [comment]
So, to expand a bit on the above questions, since I've done a bit more testing, it appears that the detection radius of the ender library is a 4 block radius from itself, having itself as the lowest layer, so technically a 5-high and 9-wide wall is possible. I am still uncertain as to the limit one section can hold since I'm still working on making the system in the first place. 

Also, fun fact, apparently the mod Dungeon Tactics has their plant effects as enchantments, and their ring effects as enchantments, and their spells as enchantments. That alone is 58 of the enchantments. Although, technically the rings can have their enchantments stripped off so maybe I'll be including them.

**Comment by Lothrazar** [comment]
Yep just like storage drawers for enchantments. 1.16 version works a bit different. 
If theres any bugs report away otherwise weve discussed these and other blocks in the discord  https://discord.lothrazar.net/


![2021-04-16_13 38 34](https://user-images.githubusercontent.com/621529/115103536-6a2f3c00-9f07-11eb-9dcb-47dba476b30b.png)
