### ISSUE TITLE
Disenchantment table eating items/tools when output slots are full/occupied

### ISSUE THREAD

**Issue by 5ully** [PrinceOfAmber/Cyclic#1692]
Minecraft Version: 
1.16.4
Forge Version: 
35.1.36
Mod Version: 
1.16.4 - 1.1.1
Single Player or Server:
Both
Describe problem (what you were doing; what happened; what should have happened):
Reproduse:
1. Place Disenchanter and feed it RF
2. Place items/enchanted books in both right slots (can also use a tool with 3 or more enchantments, but the bug only happens if both output slots er occupied)
3. Place books inside and a tool/item to disenchant, also turn on no redstone signal needed ( i dont think its related to the signal)
4. Remove the book in the upper right output slot.
5. The item you tried to disenchant vanishes. 

Log file link:

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/9050688/104513155-801f1f00-55ef-11eb-8805-a53408777feb.mp4

**Comment by MichaelNZ404** [comment]
Sorry started working on this before you picked it up :(
