### ISSUE TITLE
No-Cap Spawning

### ISSUE THREAD

**Issue by Danekjovax** [PrinceOfAmber/Cyclic#1693]
(originally posted at https://github.com/Freebi85/Explorico_Easy/issues/2)
(https://github.com/HellFirePvP/AstralSorcery/issues/1647)

Playing Explorico 1.7 SMP, with the following specs:
Forge: 1.16.4-35.1.36-universal
Ice&Fire: 2.1.5-1.16.4
Cyclic: 1.16.4-1.1.1
Astral Sorcery: 1.16.4-1.13.9

In darkened caves within rendering distance, Cyclic Toretoices and Ice&Fire Cave Trolls seem to spawn without limit.  This is despite the Astral Sorcery ritual Lucerna being active in the area.  I see two issues:

1) Toretoices are spawning with no spawn cap.
2) Cave Trolls are spawning despite an effect/ritual supposedly preventing hostile mobs from spawning.

Thanks.
![image](https://user-images.githubusercontent.com/10191173/104518864-6b7a6100-55c6-11eb-9866-5a1a6367eb64.png)

**Comment by Lothrazar** [comment]
This mod doesnt add any mobs or entities or rituals. 

 Is there an item or block you are referencing?

**Comment by Danekjovax** [comment]
OneProbe reports that the Toretoices are from Cyclic.  I'll send a screenshot later, when I'm home.

**Comment by Danekjovax** [comment]
OK, my bad.  This mob is from Quark.  I'll move this ticket there.  Sorry for the trouble.
