### ISSUE TITLE
[BUG][CRASH] Server crash if FTB ultimine is used with excavation enchant.

### ISSUE THREAD

**Issue by WeasleyWalls** [PrinceOfAmber/Cyclic#1696]
Minecraft Version: 1.16.4

Forge Version: 35.1.29

Mod Version: 1.0.2

Single Player or Server: Server ATM6 Modpack

Describe problem (what you were doing; what happened; what should have happened):

A server I am admin on kept crashing with stackoverflow errors from cyclic. Tracked it down to the excavation enchant on a pickaxe. Using the pickaxe normally worked but crashed the server when FTB ultimine was used with it. Pickaxe had both excavation(level 2) and auto smelting(level 1) on it.

Log file link:

https://pastebin.com/8ht8XEEZ

**Comment by Lothrazar** [comment]
plz test again in https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3168180 changed how excavate runs

**Comment by WeasleyWalls** [comment]
Owner has tested it with that version and it works as intended. Thanks for the quick fix
