### ISSUE TITLE
Incorrect CompareTo override - breaks /help on server

### ISSUE THREAD

**Issue by C0rn3j** [PrinceOfAmber/Cyclic#170]
[16:34:29] [Server thread/WARN] [com.matthewprenger.helpfixer.HelpFixer]: Command [searchrecipe, com.lothrazar.cyclicmagic.command.CommandRecipe] incorrectly overrides compareTo: %s 
etc etc
http://pastebin.com/m1vJAkGP

This is how LootBags fixed this exact issue on their side.
https://github.com/Malorolam/LootBags/commit/2647147688ea02e3de88c87e5e927a5e2dbfd6c8

**Comment by PrinceOfAmber** [comment]
Thanks for the link !

**Comment by PrinceOfAmber** [comment]
For future reference, replacing

    return this.equals(arg0) ? 1 : 0;
  
with

return this.getCommandName().compareTo(o.getCommandName());

**Comment by PrinceOfAmber** [comment]
1.8.9 https://minecraft.curseforge.com/projects/cyclic/files/2346133

**Comment by C0rn3j** [comment]
Thanks for fixing this problem, the issue is gone.

By the way this wasn't a critical issue, it would just throw an error on trying to execute /help from the server console(and possibly in game). 
HelpFixer actually fixes mods that have /help broken like this and makes it work correctly while screaming in the logs to report the problem to the mod author ^^
