### ISSUE TITLE
Cyclic Autocrafter causing massive fps lag when there is a Mystical Agriculture infusion crystal in it.

### ISSUE THREAD

**Issue by Luptoneb** [PrinceOfAmber/Cyclic#1700]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: MC Eternal 1.3.7.1, Cyclic version 1.19.18, Mystical Agriculture version 1.7.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Using a Cyclic Autocrafter with an infusion crystal in it causes my fps to drop from 60+fps to 13fps.  It was not actually crafting anything, just placing the crystal in the crafting grid causes the lag.

Log file link:

Video/images/gifs (direct upload or link): 
![javaw_I1ME9lP2vC](https://user-images.githubusercontent.com/8659793/104651249-ff0e6900-567c-11eb-8fce-f8b58c3e4680.png)
![javaw_yrJkAfQw3C](https://user-images.githubusercontent.com/8659793/104651261-046bb380-567d-11eb-9b87-13cfa4e59588.png)
![javaw_kPE1BDE0FY](https://user-images.githubusercontent.com/8659793/104651267-0766a400-567d-11eb-8320-fe3842e63797.png)
![javaw_QkDaH0ean9](https://user-images.githubusercontent.com/8659793/104651270-09306780-567d-11eb-9717-00df33cc9689.png)

**Comment by Lothrazar** [comment]
Wont be fixing this at least not in 1.12.2, its very stable right now even if its not optimized.  in the future optimizaion will come up in 1.18.2+
