### ISSUE TITLE
[Question] How to change settings of conveyor belts?

### ISSUE THREAD

**Issue by akisephila** [PrinceOfAmber/Cyclic#1701]
Minecraft Version: 1.16

Forge Version: Irrelevant.

Mod Version: 1.16.4-1.1.2

How do you change the settings of the conveyor belt? Its description is "Conveyor with many settings to move entities" but says nothing about how to change said settings.

**Comment by Lothrazar** [comment]
Wooden wrenches  change rotation, dyes change colour. https://www.curseforge.com/minecraft/mc-mods/patchouli has info
