### ISSUE TITLE
Item Collector and Harvesters work area include the same row the block is on.

### ISSUE THREAD

**Issue by ariosos** [PrinceOfAmber/Cyclic#1706]
Version: Cyclic-1.16.4-0.10.1

For the harvester, place farmland like in the image below, including the same row that the harvester is on. The harvester will harvest that row.
For the collector, do the same as above, but drop items in the same row.

I would have expected the row to be offset by 1 block in front of the machines, like with the work range of other cyclic machines. Also, the collector has can even 16x16 range, so it can't be centered on a block.

![image](https://user-images.githubusercontent.com/7917753/104829614-768df500-5843-11eb-8816-339abf29dbfe.png)

**Comment by Lothrazar** [comment]
fixed in a recent version, thanks for the report
