### ISSUE TITLE
Excavate and Auto-Smelt enchants do not work together

### ISSUE THREAD

**Issue by invalidCards** [PrinceOfAmber/Cyclic#1707]
Minecraft Version: 1.16.4

Forge Version: 35.1.15

Mod Version: 1.0.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
When using the Auto-Smelt and Excavate enchant together on the same tool, only the first item gets auto-smelted, and the rest is dropped as the normal block drop. This is most notable when using a shovel with Excavate 5 and Auto-Smelt being used in a desert.

**Comment by Lothrazar** [comment]
possibly was fixed in "1.1.0"
