### ISSUE TITLE
Disenchanter voiding items instead of dropping them when broken

### ISSUE THREAD

**Issue by Mig979** [PrinceOfAmber/Cyclic#1709]
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.1.4

Single Player or Server: Server (haven't tried single player)

Describe problem (what you were doing; what happened; what should have happened): The disenchanter is voiding items inside it's inventory if broken, input slot and output slots, instead of dropping them.

**Comment by Lothrazar** [comment]
Resolved by https://github.com/Lothrazar/Cyclic/pull/1734
