### ISSUE TITLE
Fluid Extraction Cable doesn't exist?

### ISSUE THREAD

**Issue by SoaringGecko** [PrinceOfAmber/Cyclic#1710]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Fluid Extraction Cable doesn't show up in creative menu or JEI

Log file link:

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/48862796/104948476-5b2e0180-598b-11eb-9f6d-21afc87a9205.png)

**Comment by Lothrazar** [comment]
Thats weird. in 1.12.2 the block ID is 

tile.fluid_pump.name=Fluid Extraction Cable

matching with the normal

tile.fluid_pipe.name=Fluid Cable

**Comment by Lothrazar** [comment]
is a modpack changing any recipes?

**Comment by SoaringGecko** [comment]
Not sure, the modpack I'm playing with is R.A.D.
[https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons](https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons)

**Comment by Lothrazar** [comment]
i just tested with RAD 1.41 . yeah i think the disable some recipes at different times and places. on a new world i dont even see any regular cables. modpack by design i guess, or take it to them :)
