### ISSUE TITLE
Solidification Chamber not taking lava

### ISSUE THREAD

**Issue by arihb** [PrinceOfAmber/Cyclic#1711]
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.1.2

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
I'm trying to make obsidian with the solidification chamber, but I can't get lava into the chamber. I've tried right clicking and shift-right clicking with a bucket, and with fluid tanks and fluid pipes from various different mods, and with just the Cyclic tank and pipe. I tried giving a redstone signal, and the chamber is powered with a rftoolspower coal generator. Also tried with water, still didn't work. Playing as part of the ATM6 pack. 

Log file link:

Video/images/gifs (direct upload or link): 
![2021-01-19_00 10 47](https://user-images.githubusercontent.com/77656843/104990637-fe623380-59ea-11eb-835f-dbf077f2e8c6.png)
![2021-01-19_00 11 02](https://user-images.githubusercontent.com/77656843/104990641-002bf700-59eb-11eb-9765-2dad80643d00.png)

**Comment by KrashKourse** [comment]
you need to use the wrench to configure the top of the fluid transfer before you place the fluid tank back down this will enable liquids to be pulled

**Comment by Lothrazar** [comment]
Yep, as the comment said. solidifier working as intended.  Pipes only extract when told to
