### ISSUE TITLE
Charms not functioning. (no effect)

### ISSUE THREAD

**Issue by KrashKourse** [PrinceOfAmber/Cyclic#1712]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.1.36

**Mod Version:** Cyclic-1.16.4-1.1.2

**Single Player or Server:** Server and Single Player

**Describe problem (what you were doing; what happened; what should have happened):** The Fire, Poison, Void, Wither (charms) are not working and there is no way to toggle them. they do not provide the said buff. 

Also there are only those 4 charms plus the combo (charm talisman) - also does not work. 

items were placed in "bauble" slots, hot bar (in hand and not), and inventory storage and base inventory, and same effect was the same (no effect)

Below I have shown that these are not toggleable, the fire charm is not glowing while the  charm talisman is.
VOID CHARM does NOT save you. and you still DIE

**Video/images/gifs (direct upload or link):** 
![image](https://user-images.githubusercontent.com/77669424/105021567-e77d0a80-5a05-11eb-9c48-fb9b1934edfb.png)
![image](https://user-images.githubusercontent.com/77669424/105021620-f794ea00-5a05-11eb-838c-b24232521bb7.png)
![image](https://user-images.githubusercontent.com/77669424/105022079-8dc91000-5a06-11eb-8afc-8e7874ea3736.png)

**Comment by Lothrazar** [comment]
Are you in a large modpack with lots of mods that might conflict?


This is me testing Fire, Void and ultimate charm so far.  The recording is outside Curios slots, functions inside it as well when i test 

![1712](https://user-images.githubusercontent.com/621529/105764973-8f19a180-5f0c-11eb-966d-0fc46bdb1014.gif)

**Comment by Lothrazar** [comment]
poison also works. but i will fix the $0 text issue in the book

If you can make a recording and link the modpack you are using i might be able to test it out.

If i had to GUESS, there is some mod that kills you at y=-1 but this charm doesnt trigger till -30. but i dont own every modpack /shrug

![1712 again](https://user-images.githubusercontent.com/621529/106367711-5b1df200-62f9-11eb-8312-744093f4868a.gif)
