### ISSUE TITLE
Feature request: Ender Controller Automation

### ISSUE THREAD

**Issue by CKY-** [PrinceOfAmber/Cyclic#1714]
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.1.2

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

Please add support for refined storage and applied energistics 2 to allow import and export using external storage connecters. 
The idea is  to use the ender shelfs like storage drawers but being able to access any of the items from with in the shelfs much like you can with storage drawers.

**Comment by Kandrathe** [comment]
That might help with the sorting problem.  Or,  add an option to re-sort the shelves from the controller.  In ATM6 we have 60 shelfs of enchanted books in FIFO order,  But, way better to walk down the aisle to search for a book, rather than a 40 barrels and shulker boxes.

**Comment by Lothrazar** [comment]
progress update. testing with refined storage soon  
![did it](https://user-images.githubusercontent.com/621529/113664745-2879d800-9661-11eb-815a-40341ee50622.gif)
