### ISSUE TITLE
Problema com o item  "PATTERN REPLICATOR"

### ISSUE THREAD

**Issue by SERGIOHERB** [PrinceOfAmber/Cyclic#1717]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): 
I created the item "PATTERN REPLICATOR" and now my map no longer opens. I do not know what to do :(

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
are there any files in the crash-reports or logs folder?  

Also the latest Mod version is 1.20.8

**Comment by Lothrazar** [comment]
Working as intended with common map mods
