### ISSUE TITLE
Crafting Machine consumes all items for recipe

### ISSUE THREAD

**Issue by brybry251** [PrinceOfAmber/Cyclic#1722]
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.0.2

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened): Crafting Machine consumes items that normally wouldn't be consumed by the recipe when crafted normally

Log file link: N/A

Video/images/gifs (direct upload or link):

**Comment by BlueAgent** [comment]
Can you give more information like steps to reproduce and log files?
What recipe where you crafting and what where the items that were in the input slots?

**Comment by Lothrazar** [comment]
Do you mean things like buckets from cakes? There is a fix coming soon for 1.1.4 that will fix the container item cake-bucket issue, and also it for example blocks the machine from consuming the Master Infusion Crystal from mystical agriculture

**Comment by Lothrazar** [comment]
Fixed in latest versions, as per previous comment
