### ISSUE TITLE
Incompatibility with "Mythical Monsters and Dangerous Dungeons"

### ISSUE THREAD

**Issue by border999** [PrinceOfAmber/Cyclic#1723]
Minecraft Version:  1.12.2
Forge Version: 1.12.2-forge-14.23.5.2854
Mod Version: Cyclic-1.12.2-1.20.8
Single Player or Server: singleplayer
Describe problem (what you were doing; what happened; what should have happened):
Crash during startup
Log file link: [logs.zip](https://github.com/Lothrazar/Cyclic/files/5861419/logs.zip)
[crash-2021-01-23_15.31.13-client.txt](https://github.com/Lothrazar/Cyclic/files/5861421/crash-2021-01-23_15.31.13-client.txt)
Mythical Monsters and Dangerous Dungeons version: MMDD+v0.9

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1545
