### ISSUE TITLE
Excavate and Fortune not working together

### ISSUE THREAD

**Issue by MacChuck** [PrinceOfAmber/Cyclic#1725]
Minecraft Version:  1.16

Forge Version: 35.1.36

Mod Version: 1.16.4-1.1.3

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened): 10 diamond ore mined with an excavate 5, fortune 3 pick is returning 10 diamonds. Tested 5 times in a fresh single player flat world. It should be giving more than 10 diamonds.

**Comment by Lothrazar** [comment]
Weird. it was fixed and then it got broken again.  Fixing it again and doing lots of tests this time
