### ISSUE TITLE
Disenchanter duplicates enchantments on Tetra tools

### ISSUE THREAD

**Issue by Lansy22** [PrinceOfAmber/Cyclic#1729]
Minecraft Version: 1.16.5

Forge Version: 35.1.36

Mod Version: 1.1.4

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
When placing an enchanted tool from Tetra in the Disenchanter, the enchantment is not removed but the enchanted book is produced.

**Comment by BlueAgent** [comment]
Is there actually enchantments being duplicated? Can you repeatedly disenchant the same tool to get infinite books?

I tried enchanting a tetra tool with mending in the workbench.
Then I disenchanted it and it removed the vanilla mending enchantment from the pickaxe but still kept the special tetra mending enchantment on the pickaxe.
At this point I could no longer put the pickaxe back into the disenchanter.

Right now, I'm guessing Tetra handles enchantments internally in a special way.
It doesn't display any Vanilla enchantments when you use the `/enchant` command directly but they can still be removed.

**Comment by Lothrazar** [comment]
Yes, bug is on Tetra side.  

If i cant enchant the item with the /enchant command, so it has a bug and doesnt interface with enchantments the same way vanilla and every other mod does. you will have to report to the Tetra issue tracker to fix enchantment
