### ISSUE TITLE
Cyclic Scepter crashing the game when 'out of range'

### ISSUE THREAD

**Issue by wadabum** [PrinceOfAmber/Cyclic#173]
Reproduce: 
Have Scepter filled with blocks (Cobble) in any placement mode.
right click floor infront  of you -> block is placed correctly.
right click in the sky ->"Server is shutting down"

Tested on **Cyclic-1.10.2-1.8.9**
(Hermitpack 1.4.0 with "bleeding edge manual mod updates" + a few Ads)
Forge 12.18.2.2124 with Optifine on Java Version: 1.8.0_111
Complete details: https://gist.github.com/wadabum/cc4582ae6a2badf3303a01805b4bf449

> Client thread/FATAL]: Unreported exception thrown!
> java.lang.NullPointerException
> 	at com.lothrazar.cyclicmagic.util.UtilSound.playSound(UtilSound.java:59) ~[UtilSound.class:?]
> 	at com.lothrazar.cyclicmagic.util.UtilSound.playSoundPlaceBlock(UtilSound.java:33) ~[UtilSound.class:?]
> 	at com.lothrazar.cyclicmagic.spell.SpellRangeBuild.cast(SpellRangeBuild.java:42) ~[SpellRangeBuild.class:?]
> 	at com.lothrazar.cyclicmagic.util.UtilSpellCaster.tryCast(UtilSpellCaster.java:32) ~[UtilSpellCaster.class:?]
> 	at com.lothrazar.cyclicmagic.util.UtilSpellCaster.tryCastCurrent(UtilSpellCaster.java:25) ~[UtilSpellCaster.class:?]
> 	at com.lothrazar.cyclicmagic.item.tool.ItemCyclicWand.func_77659_a(ItemCyclicWand.java:90) ~[ItemCyclicWand.class:?]
> 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495) ~[blm.class:?]
> 	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73) ~[PlayerControllerOF.class:?]
> 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544) ~[bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184) ~[bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961) ~[bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749) ~[bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by PrinceOfAmber** [comment]
Oops! thanks for reporting this, ill fix right away

**Comment by PrinceOfAmber** [comment]
Fixed https://minecraft.curseforge.com/projects/cyclic/files/2346647 thanks again for reporting the bug
