### ISSUE TITLE
quickdraw doesn't come

### ISSUE THREAD

**Issue by wowxiz** [PrinceOfAmber/Cyclic#1731]
modpack: R.A.D

I'm trying to get a quickdraw enchantment, I've enchanted a lot of bows and nothing, its treasure only?

**Comment by Lothrazar** [comment]
nope not treasure https://github.com/Lothrazar/Cyclic/blob/9af562544bcbf5213754518ffd60b8c00dc0e088/src/main/java/com/lothrazar/cyclic/enchant/EnchantQuickdraw.java#L59

**Comment by wowxiz** [comment]
> nope not treasure
> 
> https://github.com/Lothrazar/Cyclic/blob/9af562544bcbf5213754518ffd60b8c00dc0e088/src/main/java/com/lothrazar/cyclic/enchant/EnchantQuickdraw.java#L59

so I'm just unlucky AF
