### ISSUE TITLE
Feature Request - Piston Sceptre 1.16

### ISSUE THREAD

**Issue by Kurunoa** [PrinceOfAmber/Cyclic#1732]
Minecraft Version:  1.16.4

Single Player or Server: Yes.

Describe problem (what you were doing; what happened; what should have happened): Please re-add the piston scepter.

**Comment by Lothrazar** [comment]
yes. glad you enjoyed the 1.12 version of that. added a new note for this to https://github.com/Lothrazar/Cyclic/projects/4 just now for planning . discord.lothrazar.net
