### ISSUE TITLE
harvester not working correctly with mystical agriculture

### ISSUE THREAD

**Issue by LukaZwaan** [PrinceOfAmber/Cyclic#1736]
Minecraft Version: 1.16.5

Forge Version: 36.0.9

Mod Version: 1.1.4

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

The harvester will always drop seeds from Mystical Agriculture crops, even when it is not supposed to. Secondary seeds from said crops should only drop when planted on certain types of farmland, but the harvester ignores those rules.

**Comment by Lothrazar** [comment]
testing with 

mc_version=1.16.5
forge_version=36.0.1
    runtimeOnly fg.deobf("libs:Cucumber:1.16.4-4.1.5")
    runtimeOnly fg.deobf("libs:MysticalAgriculture:1.16.4-4.1.4")

**Comment by Lothrazar** [comment]
Works as intended in stated versions now, with latest cyclic (1.1.5+)
