### ISSUE TITLE
Kubejs not working on machiens

### ISSUE THREAD

**Issue by benbenlaw** [PrinceOfAmber/Cyclic#1738]
Minecraft Version: 1.16.5

Forge Version: 36.0.9

Mod Version: 1.1.15

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

kubejs not removing recipes from machines like melter and solidifer 
recipes removed for other craftable items 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
https://github.com/architectury/architectury-api/issues/36

**Comment by Lothrazar** [comment]
In recent update i fixed the issue where CraftTweaker couldnt remove recipes, and now we can . Example scripts are here https://github.com/Lothrazar/Cyclic/tree/trunk/1.16/crafttweaker 


I assume this will fix kubejs as well, but its still in a broken state.

Good luck, and test it out once kube is fixed i guess :)
