### ISSUE TITLE
Inventory Upgrades not aviable

### ISSUE THREAD

**Issue by HeroGamer2119** [PrinceOfAmber/Cyclic#1739]
Minecraft Version: 1.16.3

Forge Version: Forge 1.16.3 (34.1.42)

Mod Version: Cyclic-1.16.3-0.8.3.jar

Single Player or Server: Multiplayer Survival Server

Describe problem (what you were doing; what happened; what should have happened):
I wanted to make the inventory upgrade, like in the 1.12 versions of this mod and noticed that it wasn´t there.
Is this just not displayed in JEI or generally no longer included in the mod?

Thanks.

**Comment by Lothrazar** [comment]
Thanks for the request, theres lots of things that need work to re-build them in 1.16.  Moved to project board https://github.com/Lothrazar/Cyclic/projects/4  , progress updates in discord
