### ISSUE TITLE
Uncrafting grinder - items disappear if no empty slots

### ISSUE THREAD

**Issue by vysmirnov** [PrinceOfAmber/Cyclic#1741]
Minecraft Version: 1.16.5

Forge Version: 36.0.1

Mod Version: Cyclic-1.16.5-1.1.5

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened):
Uncrafting grinder: machine works and output items disappears when number of free slots is less than needed for recepie output.

**Comment by Staegrin** [comment]
Fixing this has created a new problem and not solved it completely at the same time.
If you put in some golden boots could be anything.
![2021-02-27_18 10 52](https://user-images.githubusercontent.com/8494635/109394456-59127780-7927-11eb-9537-df95fd26130f.png)
It will fill all output slots with 4x gold ingots
![2021-02-27_18 10 55](https://user-images.githubusercontent.com/8494635/109394466-6b8cb100-7927-11eb-98b0-b4951062cb92.png)

But when you uncraft something with more than one crafting component it only gives the first component and deletes the rest. Example uncrafting an iron sword only gives iron and no stick

![2021-02-27_18 13 21](https://user-images.githubusercontent.com/8494635/109394518-bc040e80-7927-11eb-9ff6-f48a9b5f09fe.png)
![2021-02-27_18 13 26](https://user-images.githubusercontent.com/8494635/109394519-bdcdd200-7927-11eb-8fe3-a29fd827ef20.png)
