### ISSUE TITLE
Crafting mashine consumes items when recepie set from JEI

### ISSUE THREAD

**Issue by vysmirnov** [PrinceOfAmber/Cyclic#1742]
Minecraft Version: 1.16.5

Forge Version: 36.0.1

Mod Version: Cyclic-1.16.5-1.1.6

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Crafting mashine consumes items when recepie set from JEI with "+" button. 

JEI version: jei-1.16.4-7.6.1.71

**Comment by Lothrazar** [comment]
in older versions of JEI this worked fine, because i have a workraound in CrafterGridSlot. If i cant fix it for next release ill disable the + transfer until it gets figured out
