### ISSUE TITLE
Burning enchant affects players on servers with PVP=False

### ISSUE THREAD

**Issue by DMCK96** [PrinceOfAmber/Cyclic#1743]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.13

**Mod Version:** 1.16.5-1.1.5

**Single Player or Server:** Server

**Describe problem (what you were doing; what happened; what should have happened):** Burning enchant damages players on servers that have PVP damage disabled. I'd expect it would check to see if the entity being damaged is a player and then check the server to see if the player is an ally (FTB team, or PVE server).

**Comment by BlueAgent** [comment]
Cylic doesn't have a Burning enchantment afaict.

Do you mean the Curse enchantment?
That only applies when the player gets hurt on to their attacker, and it's a random selection of negative effects.
<details>
<summary>Offtopic</summary>

Looking at the implementation it includes all negative effects even added by mods.
If it gets the instant damage effect that might be a bit broken cause typically it's meant to only last for a single tick.
Also mods might add some pretty crazy negative effects. But that's another issue and unrelated.
</details>
