### ISSUE TITLE
storage bag delelting items

### ISSUE THREAD

**Issue by IMaFishEatshark** [PrinceOfAmber/Cyclic#1745]
Minecraft Version: 1.16.4

Forge Version: 35.1.7

Mod Version: 1.1.5

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
right-clicking a chest goldchest in this case with a Storage bag deletes the content of the bag

Log file link:

Video/images/gifs (direct upload or link):

**Comment by IMaFishEatshark** [comment]
Edit: it happens when "deposit mode is set to merge" when you open inventory close it then open the bag it goes haywire

**Comment by IMaFishEatshark** [comment]
Edit; when you open the bag close it then open inventory and open the bag it destroys all items

**Comment by IMaFishEatshark** [comment]
it seems to only happen in creative mode

**Comment by BlueAgent** [comment]
Duplicate of https://github.com/Lothrazar/Cyclic/issues/1659
