### ISSUE TITLE
Game crash as soon as I load in

### ISSUE THREAD

**Issue by Sizzle1609** [PrinceOfAmber/Cyclic#1746]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2846 

Mod Version: 1.19.16

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened): Went to connect a fluid extraction cable to a growth crystal tier 3 and the the game crashed. Now I am unable to reload the game without it crashing right away. 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
i need to have a log file to have any information, we dont even know which mod caused your crash

**Comment by Lothrazar** [comment]
v1.19.x is a very old version.  fixed in v1.20.8+ , report back if there are any new issues or crash logs
