### ISSUE TITLE
Ender Shelf Multi-Enchanted Book

### ISSUE THREAD

**Issue by Jessi7321** [PrinceOfAmber/Cyclic#1749]
Minecraft Version: 1.16.4
Forge Version: 35.1.29
Mod Version: Cyclic-1.16.4-1.1.0
Single Player

Feeding a multi-enchanted book into the shelf causes the book to completely disappear. Using Cyclic in 1.12.2 before easily allowed for the separation of multi-enchanted books.

**Comment by Lothrazar** [comment]
good idea, adding this feature but only on the controller. so it can spread them out  
![eeehcv](https://user-images.githubusercontent.com/621529/109369133-29447080-7850-11eb-94a6-347861c134c9.gif)
