### ISSUE TITLE
Terra Preta not affecting crop growth at all

### ISSUE THREAD

**Issue by Niko-O** [PrinceOfAmber/Cyclic#1750]
Minecraft Version: 1.16.5
Forge Version: 36.0.14
Mod Version: cyclic-1.16.5-1.1.5
Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I placed a pillar of 16 Terra Preta blocks, then a block of farmland on top, then placed seeds on the farmland.
Expected behavior: Wheat grows rather quickly (more quickly than the wheat next to it that doesn't have Terra Preta below it).
What actually happens: The wheat does not seem to grow at all.

Log file link: Does not apply
Video/images/gifs (direct upload or link): Does not apply

Hint to the code:
In https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/block/soil/TileTerraPreta.java#L51 you **skip** scheduling extra ticks for the growable, if it is either **false** that the block **can** grow, or if it **can** use bonemeal. It seems you forgot the `== false` in the right operand of the or-operator. (Or rather, you probably should simply use a not-operator, as it's generally considered easier to read.)
Non-fully-grown wheat **can** grow and it **can** use bone meal. That would be "skip if `true == false || true`", so it always skips for the wheat.
Unless I misunderstood the purpose of Terra Preta.

**Comment by Lothrazar** [comment]
Yeah your logic is sound, i think.  I remember testing it just recently with mystical agriculture.  but yeah.  

the intent is to say "is it fully grown, if so then stop.  OR, am i not allowed to use bonemeal (ties into forge events, etc) then stop"
