### ISSUE TITLE
how do i pour water/lava/honey in to machines?

### ISSUE THREAD

**Issue by firestorm2039** [PrinceOfAmber/Cyclic#1751]
Minecraft Version: 1.16.4

Forge Version:35.1.37 (1.16.4) 

Mod Version: 1.16.4

**I am using a PS4 controller** 
i have 3 issues

1. Describe problem (what you were doing; what happened; what should have happened):
when using the solidification chamber it wont let me pour lava/honey in it to make items?, i click on it and it just opens it up (like a crafting table), also i can not pour water in to the peat generator, again it just opens it up (this is when i have bucket of water selected).

when my generator gets fully charged it will not give the power to another machine (like harvester) and when a machine gets fully charged (like harvester), it wont work.

how come i have to make the items before they appear in the crafting table? for example if i want to make emerald tools/armour, i have to put the pattern in the crafting table myself and craft it before it get added to the crafting table automatically, luckily i have Just Enough Items installed to see how to make stuff 1st.

**Comment by Lothrazar** [comment]
Fluid cables with cable wrench will pull it over. Yeah buckets dont work on machines like they do in tanks... i should look at what other mods are doing with buckets like that.

" i have to put the pattern in the crafting table myself and craft it before it get added to the crafting table automatically", im not sure about that, if you mean the Green recipe book then idk

**Comment by firestorm2039** [comment]
> Fluid cables with cable wrench will pull it over. Yeah buckets dont work on machines like they do in tanks... i should look at what other mods are doing with buckets like that.
> 
> " i have to put the pattern in the crafting table myself and craft it before it get added to the crafting table automatically", im not sure about that, if you mean the Green recipe book then idk

i have seen a youtube video of him just pouring a bucket of water in to the machines though, but i will try an giving pumping stations a go.

will the machines of different power sources from other mods (say a coal generator?), not something i have, but worth asking i suppose.
what are you not sure about? Just enough items? its a mod that shows you every item you can make in the game (even mods items), then it shows you the crafting layout (how to make it), i said its lucky i have that mod as i wouldnt know how to craft any of the stuff lol.

**Comment by Lothrazar** [comment]
Yes everything is compatible, so pipes, RF power energy, fluids from other mods work just fine.

JEI has recipes, also there is a Guide Book if this mods installed https://www.curseforge.com/minecraft/mc-mods/patchouli
