### ISSUE TITLE
Levels of Dry Peat Production

### ISSUE THREAD

**Issue by rachel8973** [PrinceOfAmber/Cyclic#1752]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.13

**Mod Version:** 1.1.5

**Single Player or Server:** Single Player

**Describe problem (what you were doing; what happened; what should have happened):**

This is not so much a problem and you have every right to tell me "that's just the way it is".

I'm trying to play Cyclic as a standalone mod without other mods but have difficulty with the progression of peat production and its automation.

Looking at the recipes as given in the picture provided.  I understand the second recipe with dirt is used to as a started to get you some dry peat at the start.  However, the third one with peat and biomass gives you no net production of peat.  Surely this should give you something like 6 or 8 (to match the 8, 16, 32) progression.  This way you can add more and more machines to work up the levels of yield.

**Log file link:** N/A

**Video/images/gifs (direct upload or link):** 

![Cyclic - Dry Peat](https://user-images.githubusercontent.com/7691541/107475924-cf179000-6b6c-11eb-82db-6d63770fc1f4.JPG)

**Comment by Lothrazar** [comment]
Yeah good point, made some changes 
![1752](https://user-images.githubusercontent.com/621529/109369609-d66bb880-7851-11eb-811f-03c52a77bd71.png)

**Comment by rachel8973** [comment]
Thank you!
