### ISSUE TITLE
Doup with advanced crafting stick.

### ISSUE THREAD

**Issue by sporefreak** [PrinceOfAmber/Cyclic#1753]
Minecraft Version: 1.16.5

Forge Version: 36.0.0

Mod Version: 1.16.4-1.1.1

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):
I was crafting up the essences in mystical agriculture to insanium so I could make the master infusion stone, I was crafting with the advanced crafting stick and put in some materials to craft with but ran out of essence, leaving only a crystal in I grabbed some lower tier essences and after opening the stick realized I needed a lower tier crystal too. so I had to take out the crystal that was in the crafting stick, closed the stick, grabbed the correct crystal and opened the crafting stick again to see a second duplicated crystal in the table and another in my inventory, both working for crafting and both are real crystals I can use. the duplicated had the exact same durability as the real one.
I am not sure exactly why it happened but there was a doup that happened while I was using the advanced crafting stick.

**Comment by Lothrazar** [comment]
Thanks for the info. I tried to switch back and forth and craft like you were but , so far it seems ok 
![stick](https://user-images.githubusercontent.com/621529/109361804-8b947580-783e-11eb-93d9-9ab1320fe128.gif)

**Comment by sporefreak** [comment]
I do believe it was one of those 1 in a million things, if its worth noting I only had one crafting stick.
I wish I knew exactly what I was doing but if it pops up again at least it isn't new 🤔

**Comment by paricbat** [comment]
This happened to me too, but i don't remember how i did it.

**Comment by Lothrazar** [comment]
Havent seen it break for me or any of the twitch streams/videos. so i guess its ok in new versions /shrug
