### ISSUE TITLE
[Suggestion] Make solidification chamber recipes shapeless for integration with other mods; enhance insertion of melting chamber recipes

### ISSUE THREAD

**Issue by tanyan-tanyan** [PrinceOfAmber/Cyclic#1756]
Minecraft Version: 1.16.5
Forge Version: 36.1.12
Mod Version: 1.1.5

**Problem with the current Solidification Chamber recipes:**

I connected RefinedStorage (fork of AE2) to the Cyclic melting and solidification chambers for auto-crafting things like crystallized amber, obsidian, liquid slime and magma, etc. The way auto-crafting works, I make a pattern which is recognized as an auto-crafting recipe in my storage network. 

To make crystallized amber, I set a pattern to the following:

![javaw_SxuH9HOOD4](https://user-images.githubusercontent.com/68793071/107597718-69caaa00-6c13-11eb-9cb0-ec001279ebbc.png)

When the items end up getting sent to the solidification chamber, they're all in disorder and the entire auto-crafting operation in my network is stopped until I re-arrange them manually - which brings me to the question - is it necessary for the mod to have shaped recipes for this chamber if all recipes are unique?

![javaw_8cEFbPYorv](https://user-images.githubusercontent.com/68793071/107597943-36d4e600-6c14-11eb-9a2a-1ba8f2a6eea5.png)

**Problem with the current Melting Chamber insertion:**

To make liquid slime, I set a pattern to have 10 slimeballs as components for making 1 bucket of slime. I specifically set the pattern to have 5 slimeballs on each of the 2 slots as seen below:

![javaw_nSv2aVw1v0](https://user-images.githubusercontent.com/68793071/107597403-726eb080-6c12-11eb-9632-8e18c7ad19aa.png)

Because RefinedStorage (other pipe mods probably do the same thing, including AE2) sends items into the left slot first, and the next slot in the pattern is of the same type as the previous slot, all 10 slimeballs end up in the first slot, I believe that's just the way items of the same type get inserted regardless of pattern. They will be stuck in the machine and the rest of my auto-crafting is halted until I split them evenly.

![javaw_Umpmh7Jmi8](https://user-images.githubusercontent.com/68793071/107597375-55d27880-6c12-11eb-854c-a722c25a4332.png)

**Suggestions:**
- To solve the problem with inability to integrate melting chamber recipes with other mods, I suggest accepting a sufficient amount of the same material in one slot as an alternative way to fulfil the recipe. Alternatively, make an integration where mods like RS and AE2 can actually send the same material into separate slots.
- To solve the problem with inability to integrate solidification chamber recipes with other mods, I suggest turning this chamber's recipes into shapeless recipes.

**Comment by cornytrace** [comment]
Totally agree! In the meantime, is there any workaround using other mods such as XNet, Modular Routers etc.?

**Comment by Revv1e** [comment]
Im 100% on board with this suggestion, I got no idea what other workarounds exist, I am dying to know how to auto craft with these

**Comment by Lothrazar** [comment]
adding this 
![shapeless](https://user-images.githubusercontent.com/621529/114347121-5788c180-9b19-11eb-928a-f6d8d401c55a.gif)

**Comment by Lothrazar** [comment]
also adding option for data pack makers or whatever to have the second and third slot empty  with a few defaults 
![optional](https://user-images.githubusercontent.com/621529/114347200-6d968200-9b19-11eb-9908-0cf4ce7d6d28.png)

**Comment by AlexHunterCodes** [comment]
The recipe for Experience Confection has not received this fix, it still requires all three slots to be filled with Sugar. Can you please add these alternative recipes for 1/3 and 2/3 slots filled?

**Comment by arconom** [comment]
This issue is not fixed.  When sending items into a Solidification Chamber, for instance [Dirt, Dirt, Dirt], via a Refined Storage Crafter, the Solidification Chamber places the Dirt in the first empty slot, rather than the slot specified by the crafter.
