### ISSUE TITLE
Rod of elevation sends you on top of bedrock in nether

### ISSUE THREAD

**Issue by Arkatos** [PrinceOfAmber/Cyclic#1757]
Minecraft Version: 1.16.5

Forge Version: 36.0.14

Mod Version: 1.1.5

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened):

Rod of elevation in the nether puts you on top of the bedrock roof. i assume this is not intended. Was able to send myself and my friend up there.

**Comment by Lothrazar** [comment]
Yep, working as intended.  You can get up there in Vanilla very very easily, there are several ways such as ender pearls, etc
