### ISSUE TITLE
[REQ] Prevent Block Placer conducting redstone

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#1758]
Minecraft Version: 1.16

Forge Version: 36.0.14

Mod Version: Cyclic-1.16.5-1.1.6

Single Player or Server: Irrelevant

Describe problem (what you were doing; what happened; what should have happened):

I discovered just now that if a Block Placer is powered by redstone, it conducts the signal to adjacent blocks. This means that it disables the hopper that feeds it! I verified this with levers on adjacent and opposite sides of the block and even used a repeater feed the signal. 

This dramatically reduces the value of the Requires Redstone mode, IMO. I now need to use pipes to distance the feed or set up a timing device to alternate between work/feed. I feel it would be better if the placer did not conduct redstone.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
This is not related to block redstone state, this is a property of ALL blocks in vanilla, for example even Sand.  GIF included.

However, yeah it makes sense for this, actually all machines, to "absorb" the redstone signal and not let it pass by, so ill see if its possible

![1758](https://user-images.githubusercontent.com/621529/109409214-9a198480-7945-11eb-8cd5-d648d2ebecd2.gif)
