### ISSUE TITLE
ilimited duplication with wireless crafting grid from RS on uncrafting grinder

### ISSUE THREAD

**Issue by idealjo** [PrinceOfAmber/Cyclic#1759]
Minecraft Version: 1.16

Forge Version: 35.1.36

Mod Version: Cyclic-1.16.5-1.1.4.jar

Single Player or Server: single 

Describe problem (what you were doing; what happened; what should have happened):

the wireless crafting grid from RS in the uncrafting grinder give unlimited parts. Cannot remove the grid unless breaking the grinder, and still intact.

**Comment by Lothrazar** [comment]
Looks like its functioning normally.  Wireless crafter reverses into a dyed crafting grid, which then reverses again.

If you want to block the ones with dye messing up the mix, items like "refinedstorage:brown_crafting_grid" need to go in config file to disable, in cyclic.blocks.uncrafter  -> ignore_list. ill add some defaults, so next release will have fixed config

**Comment by Lothrazar** [comment]
Also see the new config options added in v 1.1.7 . added some of the RS items as default values
