### ISSUE TITLE
[1.16] Dupe of sieving material when cyclic mod is present with ex nihilo sequentia

### ISSUE THREAD

**Issue by jinkhya** [PrinceOfAmber/Cyclic#1769]
Hello, 
Here's the full report :
https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/120

I'm not sure who would have to fix this so I posted the problem on both :)
Thanks in advance !
Jin

**Comment by benbenlaw** [comment]
i am able to reproduce this with just cyclic installed
