### ISSUE TITLE
Cyclic Bug With Iron Chest Mod

### ISSUE THREAD

**Issue by Dekuchi** [PrinceOfAmber/Cyclic#177]
I used a diamond chest with the cyclic mod for a long time and it was working fine, I went into the nether and had used it in the nether but am positive I picked it up, but when I came back it was missing, it just showed an empty bad. No sign of my diamond chest and the rows of items I had inside it. (HermitCraft modpack ftb)

**Comment by PrinceOfAmber** [comment]
What item from cyclic were you using with this? Was it the Sack of holding, where you pick up the bag and put it down again?  

Hmm ill test it out.

Do you know which version of the hermitpack modpack or which version of Cyclic you're using?

**Comment by PrinceOfAmber** [comment]
I was using Cyclic version 1.8.11 and iron chests version ironchest-1.10.2-7.0.11.797.  I used this on a diamond chest a bunch of times, used it in the nether a bunch, came back to the overworld again.  I cant make any errors happen. so far.
