### ISSUE TITLE
Enchantment tokens for Silent Gems have no recipe

### ISSUE THREAD

**Issue by numskull34** [PrinceOfAmber/Cyclic#1770]
Minecraft Version: 1.16.5

Forge Version: 0.167.2.7

Mod Version: 1.1.6

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):

Enchantment tokens for Silent Gems have no recipe. The tokens come up in JEI but have no recipe. I have tried to disable all enchantments and re-enable but still no recipes.

Log file link: 

Video/images/gifs (direct upload or link):

**Comment by tlsctf2** [comment]
not to sound rude, but what does that have to do with Cyclic at all? if anything you should check in with SilentChaos512 on the Silent Gems issue tracker and say this there. if you're sure this is a Cyclic issue you may want to explain why you think that if you want help with it at all

**Comment by numskull34** [comment]
not sure where the recipes come from seeing how the enchants come from cyclic thought I would ask. Also already was a post to Silent and from the half solved issue from what I could tell it sounded like a cyclic issue.... https://github.com/SilentChaos512/SilentGems/issues/340
