### ISSUE TITLE
Pharos Beacon does not accept "un-enchanted" potions

### ISSUE THREAD

**Issue by Maritisa** [PrinceOfAmber/Cyclic#1772]
Minecraft Version: 1.16.5

Forge Version: 36.0.43

Mod Version: 1.1.7                   (Has been present since at least 1.1.3)

Single Player or Server: Single Player

If a potion has its enchantment glow removed (either somehow spawned that way or by an external mod, ex: RandomPatches) the Pharos Beacon will refuse to allow it to enter its inventory. Shift-click, direct drop, even hoppers/pipes do not allow the item in. It appears whatever method is being used to search for a valid potion fails if the enchantment glow is not present.

Normally, the potion would go into the slot and wait for the beacon to activate to be consumed, however "un-enchanted" potions are completely rejected by the beacon.

Restoring the potion glow (setting RandomPatches' "remove_glowing_effect_from_potions = false") restores the beacon to intended functionality.

**Comment by Lothrazar** [comment]
Yeah, i should check if the stack has a list of actual potion attributes instead of checking "is it shiny"
