### ISSUE TITLE
#1741 continuation uncrafting grinder

### ISSUE THREAD

**Issue by Staegrin** [PrinceOfAmber/Cyclic#1773]
Minecraft Version: 
1.16.5
Forge Version: 
36.0.43
Mod Version: 
Cyclic-1.16.5-1.1.7
Single Player or Server:
Single player
Describe problem (what you were doing; what happened; what should have happened):
Fixing #1741 has created a new problem and not solved it completely at the same time.
If you put in some golden boots could be anything.
![2021-02-27_18 10 52](https://user-images.githubusercontent.com/8494635/109394456-59127780-7927-11eb-9537-df95fd26130f.png)
It will fill all output slots with 4x gold ingots
![2021-02-27_18 10 55](https://user-images.githubusercontent.com/8494635/109394466-6b8cb100-7927-11eb-98b0-b4951062cb92.png)

But when you uncraft something with more than one crafting component it only gives the first component and deletes the rest. Example uncrafting an iron sword only gives iron and no stick

![2021-02-27_18 13 21](https://user-images.githubusercontent.com/8494635/109394518-bc040e80-7927-11eb-9ff6-f48a9b5f09fe.png)
![2021-02-27_18 13 26](https://user-images.githubusercontent.com/8494635/109394519-bdcdd200-7927-11eb-8fe3-a29fd827ef20.png)

**Comment by jackwright-ual** [comment]
confirmed that this is present in the 1.16.5-1.1.9 version, also: I'll open another issue - I've noticed that the durability doesn't effect the uncrafting process. Seems a bit OP

**Comment by AdamDN** [comment]
I can also confirm, bug still present. 1.16.5-1.1.9

**Comment by Lothrazar** [comment]
For reference, most recent change was https://github.com/Lothrazar/Cyclic/issues/1741  which likely introduced the bug
