### ISSUE TITLE
Bounce from player launcher combined with Multi Jump Elytra causes immense speed, then bugs player model, movement velocity out of control.

### ISSUE THREAD

**Issue by MrAwexome** [PrinceOfAmber/Cyclic#1774]
Minecraft Version:  1.12.2

Forge Version: 

Mod Version: 1.12.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I was flying on my elytra, then I used a player launcher to go forward flying, repeating this multiplied my speed until i was going hundreds of blocks per second. I landed, then had a velocity/momentum glitch and player model also bugged out from inventory, looked like the arms and legs were going in all directions. Tried to reload world and modpack, didn't work. Spamming movement keys started movement glitch again. Slammed into a wall in a cave because I was going to fast, then error occured in my world.

Log file link: [latest - Copy.log](https://github.com/Lothrazar/Cyclic/files/6065725/latest.-.Copy.log)

[crash-2021-03-01_21.00.33-client.txt](https://github.com/Lothrazar/Cyclic/files/6065730/crash-2021-03-01_21.00.33-client.txt)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Yep, this has been a known feature for a long time.  Dont use both at once, the game cant handle it. error message is from mojang code <3
