### ISSUE TITLE
Solidification Chamber not Processing

### ISSUE THREAD

**Issue by Ilike0reos** [PrinceOfAmber/Cyclic#1776]
Minecraft Version: 1.16.5

Forge Version: 35.1.37

Mod Version: Cyclic-1.16.5-1.1.8.jar

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

I am currently playing the mod pack Sky Bee found on the curseforge application. When using the solidification chamber nothing happens. I have supplied the solidification chamber with 64000/64000 power and 46000/64000 honey to create things like honey apples, honey bottles, and crystalized amber. I supple the resources in the correct position and nothing is output from the machine as seen in the graphic below. I suspected it would be due to the version of the mod as sky bees hasn't updated to Cyclic-1.16.5-1.1.8.jar but I updated it to the latest version and the problem persists. 

Log file link:

Video/images/gifs (direct upload or link): 
![Honey_prob1](https://user-images.githubusercontent.com/79936740/109702019-b560db80-7b61-11eb-92d5-e1fc0d5edfc6.PNG)
![Honey_prob2](https://user-images.githubusercontent.com/79936740/109702036-babe2600-7b61-11eb-85f9-4ea0e1eac3cb.PNG)
![Honey_prob3](https://user-images.githubusercontent.com/79936740/109702048-beea4380-7b61-11eb-9477-78f4ee289fd3.PNG)

**Comment by Leomacchia** [comment]
I also have your same problem, playing the same pack... I think this issue is due to the fact that in the pack there are two versions of honey: the Cyclic's one, and the Resourceful Bees' one, and when you try to use the RB's honey for Cyclic recipes in Cyclic machines, it doesn't work... I wish Cyclic developers will implement some kind of compatibility between these two mods, because getting honey just with melting chamber whilst the centrifuge gives you a ton of it is really stressful

**Comment by mdedmon** [comment]
I'm unable to get any fluids into the Solidification chamber. It was working a few versions back, but in the last couple of updates to the Direwolf20 modpack, it's not. I've tried putting magma into the machine using buckets, tanks, fluid pipes from cyclic and other mods. Nothing. It just won't take any. I even made a new machine and no difference.  This is part of the Direwolf20 1.16.5 (version 1.7.0) - Cyclic Mod info: version 1.16.5-1.1.8.

This is running on a hosted server. 
![2021-03-07_21 45 41](https://user-images.githubusercontent.com/459278/110267826-95308280-7f8e-11eb-8951-bd18e1a3a3fd.png)
![2021-03-07_21 45 08](https://user-images.githubusercontent.com/459278/110267830-9792dc80-7f8e-11eb-86fc-f377b8d57327.png)

**Comment by Epic428** [comment]
The recipes for the solidification chamber don’t use the forge:honey fluid tag. Changing that would fix the issue with our mod.

https://github.com/Lothrazar/Cyclic/blob/3a2070848ff136eec199143a1e0f9a4941c85038/src/main/resources/data/cyclic/recipes/solidifier_honey_block.json#L13 For example

reference issue in our github
https://github.com/Resourceful-Bees/ResourcefulBees/issues/182

**Comment by Lothrazar** [comment]
Thanks for the reference on the Honey fluid tag.  to be honest i forgot you could tag fluids just like blocks

**Comment by Lothrazar** [comment]
@Epic428 Thanks for all the help

Adding fluid tags to all my fluids.  

Also, for recipes im coding something like this to see if the input fluid matches the recipe fluid, instead of just "=="

Loop over all tags, if the tile fluid and the recipe fluid both have the same tag, its a match

```
    for (INamedTag<Fluid> fluidTag : FluidTags.getAllTags()) {
      if (fluidInput.getFluid().isIn(fluidTag) && tile.getFluid().getFluid().isIn(fluidTag)) {
        return true;
      }
    }
```

**Comment by Epic428** [comment]
Ah perfect! Glad you got it all set up well :)
