### ISSUE TITLE
Recipes aren't updated on reload

### ISSUE THREAD

**Issue by jaredlll08** [PrinceOfAmber/Cyclic#1781]
Minecraft Version: 
1.16
Forge Version: 
N/A
Mod Version: 
N/A
Single Player or Server:
N/A
Describe problem (what you were doing; what happened; what should have happened):
Since you store recipes yourself in `RecipeMelter` and `RecipeSolidifier`, they aren't updated when `/reload` is done.

In general, you shouldn't be storing your own recipes unless you have a good reason to be.

You should be getting the RecipeManager from the world, and getting your recipes through that, like so:
```java
world.getRecipeManager().getRecipesForType(CyclicRecipeType.MELTER)
```

The way you have things setup now, you won't even be able to change recipes with datapacks and`/reload`.

The list of recipes and hashes is never cleared before a reload, meaning that reloading only works for adding *new* recipes, since if it tries to add a recipe with a name that has already been used, it will fail due to the hash check.

With the hash check as well, the only time there would ever be conflicting hashes is when recipes are added through CraftTweaker or through a mod calling your api methods (which they shouldn't be doing, they should be shipping datapack json files). since recipes added through a datapack with the same recipe name (So 2 datapacks adding a recipe with the same name), one would override the other, so it wouldn't even trigger then. 

Log file link:
n/a

Video/images/gifs (direct upload or link): 
n/a

**Comment by jaredlll08** [comment]
Hey uh, I don't see any commits that would fix this and the change log seems to imply it only affected CraftTweaker. 

This is an issue that you can reproduce with datapack recipes alone (changing a recipe through a datapack) and also mods that add recipes through your api methods (which does include CraftTweaker recipes)

**Comment by Lothrazar** [comment]
note to self, fix here on x2 recipes, and for https://github.com/Lothrazar/PlainGrinder and for FC
