### ISSUE TITLE
[REQ] Let Fishing Net accept modded fishing rods

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [PrinceOfAmber/Cyclic#1782]
https://www.curseforge.com/minecraft/mc-mods/aquaculture adds a couple of fishing rods, none of them can be used in the fishing net. Would be neat if they did.

**Comment by Lothrazar** [comment]
it accepts anyhing in DataTags.RODS https://github.com/Lothrazar/Cyclic/blob/3f0757a1ac5975cb408dee86d0df36e07e0727bb/src/main/java/com/lothrazar/cyclic/block/fishing/TileFisher.java#L99  
for example this 
https://github.com/Lothrazar/Cyclic/blob/d96a16680481e2713e66ca66ac2c8ebb3dd2dc93/src/main/resources/data/forge/tags/items/fishing_rods.json

So other mods need to tag their items and it will work
