### ISSUE TITLE
[Feature request] Keyboard Shortchut for Excavation with the enchant

### ISSUE THREAD

**Issue by Fireztonez** [PrinceOfAmber/Cyclic#1783]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.46

**Mod Version:** Currently using Cyclic 1.1.8

**Describe problem (what you were doing; what happened; what should have happened):**
I have try your Excavate enchant on my modpack question to see if this is something interesting for my modpack or not. I really enjoy the idea to have enchantments for excavate, but I think having if I can activate manually the Excavation by pressing a Key (Little like Ore Excavation) this will be a lot more usefull and have less risk to caused your death! An option can also be added question to Toggle the chose if the excavation if enabled by default with the enchant (In that case the key can be for Not-Excavate) or if you need to press on it question to excavate.

Thank's again for your great mod!
Fireztonez

**Comment by Lothrazar** [comment]
Good idea, but seems like a big waste for a keybind that will always do nothing unless you are holding a tool with this enchant.

What I do is i have Two or three tools with different enchants (fortune, silk / excavate / auto smelt) and swap between them with this mod 
https://www.curseforge.com/minecraft/mc-mods/tool-belt
You put your tools on your belt, and press a key to swap.

Also ore exavation is on 1.16 now
