### ISSUE TITLE
Wont connect to Server

### ISSUE THREAD

**Issue by willtarax** [PrinceOfAmber/Cyclic#1784]
Minecraft Version: 1.16.4

Forge Version: 35.1.37

Mod Version: 1.1.9

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Trying to connect from client to server, told system registry has issues, and crashed. Removing Cyclic corrected the issue.

Log file link:
[latest (1).log](https://github.com/Lothrazar/Cyclic/files/6104325/latest.1.log)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Do you have the config file on the server and client matching?  If configs match this wont happen

It seems like some enchantments were disabled on the server but not the client, or maybe the other way around.  If your modpack updated on the server, make sure client updated too

"[13:35:25] [Render thread/ERROR]: Missing registry data for network connection:
	minecraft:enchantment: cyclic:auto_smelt
	minecraft:enchantment: cyclic:beheading
	minecraft:enchantment: cyclic:curse
	minecraft:enchantment: cyclic:disarm
	minecraft:enchantment: cyclic:excavate"

**Comment by willtarax** [comment]
I went full nuclear on the server and client side. Deleting everything and running a fresh download from my modpack page on curseforge. I will run it again tonight to see if maybe I missed something, but this was affecting all of my server members.

**Comment by willtarax** [comment]
After recreating a new modpack, and trying with Cyclic I found there was no longer an issue. Potentially a compat issue, but honestly at this point, unless you get a bunch more like this, then I would consider this a non issue.
