### ISSUE TITLE
Can't use Cyclic user to activate Astral Sorcery Starlight Infuser with Resonating Wand

### ISSUE THREAD

**Issue by TwilightWolfi** [PrinceOfAmber/Cyclic#1785]
Minecraft Version: 1.16.5

Forge Version: 36.0.43

Mod Version: 1.1.7

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

While I'm able to add items to the Infuser's internal buffer using a User, I'm unable to successfully start the infusion using another User with a resonating wand in its inventory. I've read prior issues regarding the infuser that have allowed the user to activate the infusion, however.

**Comment by Lothrazar** [comment]
This must be on astrals end. Probably by design, either for balance or whatever idk

They have tons of source where they check "Is this a fake player? if so cancel whatever they are trying to do"

https://github.com/HellFirePvP/AstralSorcery/search?p=1&q=isPlayerFakeMP
