### ISSUE TITLE
Experience Pylon ConcurrentModificationException

### ISSUE THREAD

**Issue by Barragek0** [PrinceOfAmber/Cyclic#1786]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): Withdrawing experience from an experience pylon repeatedly can cause ConcurrentModificationException causing game to crash.

Log file link: [crash-2021-03-10_00.27.39-server.txt](https://github.com/Lothrazar/Cyclic/files/6112214/crash-2021-03-10_00.27.39-server.txt)

**Comment by Lothrazar** [comment]
old mod version, Was fixed in 1.120.5
