### ISSUE TITLE
Cyclic Bag is stuck in AE2 storage

### ISSUE THREAD

**Issue by 4emili4** [PrinceOfAmber/Cyclic#1787]
Minecraft Version: 1.16

Forge Version: 36.0.45

Mod Version: 1.16.5-1.1.8

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Can not retrieve Cyclic storage bag out of AE2 storage, just stays in storage; Bag does not remove, but a second bag that was recently created is freely able to be moved in and out of storage

**Comment by Lothrazar** [comment]
This must be a bug with AE2.  I tested with Storage network, and also Refined storage using a 16k disk drive, and both are working normally

![1787](https://user-images.githubusercontent.com/621529/111262441-8460bc00-85e1-11eb-8719-7506070f04ad.gif)
