### ISSUE TITLE
Growth Enchant available on all tools via Enchantment Table

### ISSUE THREAD

**Issue by Serifina** [PrinceOfAmber/Cyclic#1788]
Minecraft Version: 1.16.5

Forge Version: 36.0.58

Mod Version: 1.1.9

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Growth mod can only be applied to Hoes via Anvil, but is available for any tools (pickaxe/shovel/axe) via the Enchantment Table. By the description of the enchantment, this is incorrect, and should only be available to Hoes.

**Comment by Lothrazar** [comment]
Weird, i wonder if this is a bug in forge or if i missed something. Literally i have 

`
  @Override
  public boolean canApply(ItemStack stack) {
    return stack.getItem() instanceof HoeItem;
  }
`

Maybe if i cant fix it ill just change the guide book and make it a feature

**Comment by Lothrazar** [comment]
nevermind, theres a second method i can route, 'canApplyAtEnchantingTable'
