### ISSUE TITLE
Where did the item cable filters go?

### ISSUE THREAD

**Issue by Firusew** [PrinceOfAmber/Cyclic#1789]
Minecraft Version: 1.16.5

Forge Version: 36.0.46

Mod Version: 1.1.9

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
I apologize in advance, I am from Russia and do not know English well, so I translate everything through Google translator.

Why have item cable filters been removed for the new version of Minecraft?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
in 1.12 it was a different block, in 1.16 it is built into the main cable block

Use the Cable Wrench on the cable to make it extract.
item id:

cyclic:cable_wrench

**Comment by Firusew** [comment]
How do you transfer only a specific item through these cables?
