### ISSUE TITLE
[Feature Request] Support other XP fluids on the Experience Pylon

### ISSUE THREAD

**Issue by KaseiFR** [PrinceOfAmber/Cyclic#1791]
Minecraft Version: 1.16
Forge Version: 36.0.42
Mod Version: 1.16.5-1.1.6

Could it be possible to support other mods XP fluids in the Experience Pylon ? It's a very convenient XP storage, but having to convert other XP fluids to XP orbs for the pylon to accept is very annoying.

Here are some XP fluids that I know of on 1.16:
- Industrial Foregoing Essence
- COFH Essence of Knowledge
- Pneumaticraft Memory Essence
- Reliquary XP Juice (seems experimental)

**Comment by Lothrazar** [comment]
Just recently i added data tags for all fluids, so the fluid 'cyclic:xpjuice' now has the tag

/data/forge/tags/fluids/xpjuice.json  aka "forge:xpjuice"


For the purpose of compatibility.  Released in mod version 1.2.0  https://github.com/Lothrazar/Cyclic/commit/8cd03132268504741ade742a8ec063c44d9da508#diff-ed31cf0c384dd95a3b2387c1775a4a41755dcc06b14471fd9d0ec95d764ff7d7R2

**Comment by KaseiFR** [comment]
I see that IF also tags its fluids, although its XP fluid is tagged with `forge:essence` and not `forge:xpjuice` I think:
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/d37485ad78f637e4a1d089b858672140b3387140

But is adding tags to the Cyclic fluids enough to make the Pylon _accepts_ other fluids ?
https://github.com/Lothrazar/Cyclic/blob/3eb43884d7f98fbec4d0a77e29308e6a3bf8ac2c/src/main/java/com/lothrazar/cyclic/block/expcollect/TileExpPylon.java#L65

**Comment by Lothrazar** [comment]
essense is something different.  We talked in forgecraft, everyone will be using "forge:experience" for the tag moving forward. (for example mob grinding utils, king lemmings mods, Buuz135  )

**Comment by KaseiFR** [comment]
Nice !
Should I open an issue on some mods for them to use the standard tag ?
