### ISSUE TITLE
Crafting Machine consumes left-behind bucket in "bucket-only" recipe

### ISSUE THREAD

**Issue by TheRealWormbo** [PrinceOfAmber/Cyclic#1792]
Minecraft Version: 1.16.5

Forge Version: 36.1.0

Mod Version: 1.16.5-1.1.9

Single Player or Server:Single player

Describe problem (what you were doing; what happened; what should have happened):

Using the crafting recipe of "1 latex bucket -> 3 rubber, 1 left-behind bucket" from Thermal, i.e. machine is configured with one latex bucket in the recipe grid. When inputting a latex bucket, the machine consumes the input, produces the rubber as output, but does not leave behind the bucket. (The recipe works fine for manual crafting or in Thermal's own Sequential Fabricator.)

Even worse, if the crafting machine was previously configured to turn 4 honey bottles into a honey block (leaving behind 4 empty bottles), the latex bucket recipe also now leaves behind one empty bottle.

Testing things with other bucket types, the machine also does not appear to recognize the Immersive Engineering recipe "1 Bucket of Creosote Oil surrounded by 8 planks -> 8 Treated Wood Planks + left-behind bucket". In that case the machine does not seem to accept the recipe at all. Again, that recipe works fine for manual crafting or in a Thermal Sequential Fabricator.

**Comment by Lothrazar** [comment]
Does it have room to dump empty buckets? For cake it works just fine, we can see in the top left empty buckets being left over . mod version 1.2.0 
![milk120](https://user-images.githubusercontent.com/621529/112222147-90eaa300-8be5-11eb-9e64-45a6433fca74.gif)

**Comment by TheRealWormbo** [comment]
Yes, it works fine with cake and similar recipes that use multiple ingredients.

My test setup is as follows: Create a "vanilla" Forge 36.1.0 instance in GDLauncher, installing nothing but the current versions of Cyclic and the Thermal mods.

The test contraption uses just the Cyclic crafting machine, a Cyclic creative battery and a Thermal latex bucket. Put the latex bucket into the crafting grid (I chose to put it into the center slot, but the location within the grind doesn't seem to matter) and a couple of them into the input slots. When enabled, the machine will produce 3 rubber per latex bucket, as expected, but consumes the buckets without leaving behind empty buckets.

As second test, I removed the latex bucket from the crafting grid, entered the 2x2 honey bottle recipe and added a couple honey bottles. Produces honey blocks and leaves behind 4 empty bottles per operation, as expected. Then I clear the crafting grid again and put back the latex bucket. Now, when I add latex buckets to the input (again, there is free space available), the machine will leave behind individual empty bottles instead, still producing the expected three rubber per operation as output.

**Comment by TheRealWormbo** [comment]
Found another example, this one not using only bucketed ingredients: Create's recipe "Wheat Flour + Water Bucket -> Dough + left-over empty bucket" exhibits the same behavior of discarding the empty bucket, while other crafting options correctly output it.

**Comment by Lothrazar** [comment]
looks a lot like https://github.com/Lothrazar/Cyclic/issues/1811
