### ISSUE TITLE
Extreme duplication bugs with crafting machine

### ISSUE THREAD

**Issue by ludovicb1239** [PrinceOfAmber/Cyclic#1794]
Minecraft Version: 1.16.4

Forge Version: im not sure

Mod Version: near december

Single Player or Server: Server but doesnt seems to matter

Describe problem (what you were doing; what happened; what should have happened):

Theres two bugs.

The first is that you shift click an item into the receipe output pattern and then it changes the reciepe for the entire game

The second is that you can simply duplicate items using the nine slots for placing the pattern.

Video/images/gifs (direct upload or link): 

https://drive.google.com/file/d/1ZMvuZTvWOJFX4iSCgiOKz3EgsRS5oknB/view?usp=sharing
https://drive.google.com/file/d/16qib4R6JNAc-2AbUOOMiV5tAlEMGLgLp/view?usp=sharing

**Comment by Lothrazar** [comment]
The videos say access denied, can you post on youtube or imgur or something like this?

**Comment by ludovicb1239** [comment]
oops it should work now. Forgot to enable viewing
