### ISSUE TITLE
Bug with spikes

### ISSUE THREAD

**Issue by MrToast24** [PrinceOfAmber/Cyclic#1796]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):

Any kind of spike included in cyclic dont appear in Just Enough Items, and arent craftable either. I'm using a modpack named Roguelike Adventure and Dungeons. I'm still able to find the textures of the spikes inside the jar file.

**Comment by Lothrazar** [comment]
Mod recipe works as intended, normally. the modpack you named must have changed a ton of stuff, which we encourage. maybe they made it a quest reward or something  
![1796](https://user-images.githubusercontent.com/621529/115103329-fccedb80-9f05-11eb-9f8e-eea61388ea0b.png)
