### ISSUE TITLE
dupe glitch with workbench in MP

### ISSUE THREAD

**Issue by Sunekaer** [PrinceOfAmber/Cyclic#1798]
Minecraft Version: 1.16.5

Forge Version: 36.0.58

Mod Version: Cyclic-1.16.5-1.1.9

Single Player or Server: Server

Describe problem:
1. opens the workbench to in recipe for like sticks
2. opens the workbench while 1 is still in it, and removes the planks for the stick recipe
1. can still get the output of the recipe (the 4 sticks) but the planks are gone.

**Comment by Lothrazar** [comment]
Fixed in latest versions : 
![1798](https://user-images.githubusercontent.com/621529/124872482-2f72f800-df7a-11eb-8a95-096d8cc3b059.gif)
