### ISSUE TITLE
[1.16.5] Magma Anvil Broken

### ISSUE THREAD

**Issue by DatenThielt** [PrinceOfAmber/Cyclic#1800]
Minecraft Version: 1.16.5

Forge Version: 36.1.2

Mod Version: Cyclic-1.16.5-1.2.1

Single Player or Server: SP Survival

Describe problem (what you were doing; what happened; what should have happened):
Unable to load Magma into Magma Anvil using Cyclic pipes from a Cyclic tank full of lava, or using buckets,  Related to #1627  as it appears to be the same issue

**Comment by TheSaucyWelshman** [comment]
"Cyclic tank full of lava"

Lava or magma? It only accepts magma which is a separate fluid added by Cyclic

**Comment by DatenThielt** [comment]
"Bows head in shame in lack of reading comprehension"  working with magma, sorry
