### ISSUE TITLE
Spawner seeker not working

### ISSUE THREAD

**Issue by tyler489** [PrinceOfAmber/Cyclic#1806]
Minecraft Version: 1.16.5

Forge Version: 36.1.2

Mod Version: 1.2.1
Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
spawner seeker doesn t move floats in air and never drops.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
yeah im testing on a server now, i see the same thing happening, it just freezes but nothing crashes

**Comment by tyler489** [comment]
Better than 1.12 where it would crash the server after 60 seconds ;p

**Comment by Lothrazar** [comment]
"Better than 1.12 where it would crash the server after 60 seconds ;p", yikes i dont remember that report.  i used to watch people use it all the time on sevtech ages servers tho

https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3268221
