### ISSUE TITLE
Extend Ender Shelf and Controller

### ISSUE THREAD

**Issue by CloWnicide** [PrinceOfAmber/Cyclic#1807]
Minecraft Version: 1.16.5

Forge Version: 36.1.2

Mod Version: 1.2.3

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Not an actual issue, but it seems that the controller has a set range or block limit for the Ender Shelves. Is it possible to extend its range at all, or include in the config to extend the shelves it is able to use?

**Comment by CloWnicide** [comment]
On a side note regarding the shelves, it keeps skipping over random ones when inserting books into the controller. I've tore down the shelves, replaced all of them including the controller and it continues to do this every time to random shelves.

![Screenshot (23)](https://user-images.githubusercontent.com/27911500/113962549-c0e89780-97dc-11eb-8d5c-e7bc1ad28e8d.png)

**Comment by Lothrazar** [comment]
skipping the middle shelve is a bug. range is hardcoded and yeah should be bigger or upgradeable or something.

also if shelves kept their contents when broken like  a shulker box it would be useful too for re arranging

**Comment by Lothrazar** [comment]
changing public static final int MAX_ITERATIONS = 24; to 64 to up the range, testing https://github.com/Lothrazar/Cyclic/blob/5284ff10679f384dafdb6e6ce382b7f09ca0a612/src/main/java/com/lothrazar/cyclic/block/enderctrl/EnderShelfHelper.java#L19
