### ISSUE TITLE
[Feature Request] Sound Proof Blocks Camouflage 

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1810]
Minecraft Version: 1.16.5

Forge Version: 36.1.0

Mod Version: 1.2.3

Single Player or Server: Any!

Describe problem (what you were doing; what happened; what should have happened):

Hey! I have a great idea! 

What if the Sound Proof blocks could be given a camouflaged block to help it mimic whatever you're building?! That way, it won't stand out as much. Super bigly quality of life if you ask me!

Thanks in advance,
Dr. Osto, Ph.D.

**Comment by Lothrazar** [comment]
what if there was a tiny compressed version, like a button or lever you could tuck under a machine.   that would help keep them out of the way.  Also, yes actually i do want to do some camouflaged blocks. just in general having an ability to hide a set or region of blocks or have it look like stone or the thing next to it.  Just in general that ability gives me the idea to try things. whether its a paintbrush type item or a block or something else like covers. if the camoflauging can get working and look good theres many possibilities

**Comment by Lothrazar** [comment]
once it was working, i made a version for light source too 
![1810](https://user-images.githubusercontent.com/621529/114498995-13112a80-9bda-11eb-963d-30202c877e2d.gif)

**Comment by Lothrazar** [comment]
Released in latest versions
