### ISSUE TITLE
Reusable Items Are Moved to Output Slot in Crafter

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1813]
Minecraft Version: 1.16.5

Forge Version: 36.1.0

Mod Version: 1.2.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
After the previous update to the crafter logic, the Master Infusion Crystals from Mystical Agriculture are being moved to the output slot and breaking the ability to reuse the item in multiple crafts. Is there a way to allow them to stay in the input?

Thanks!

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1811

**Comment by Lothrazar** [comment]
this seems better. for recipes like the essence, the crystal gets re used on the left, but for buckets that get drained they move to the right as output 
![1813](https://user-images.githubusercontent.com/621529/114497989-11defe00-9bd8-11eb-85f2-25bd68f67d6b.gif)
