### ISSUE TITLE
Cyclic Crafting Machine does not allow automated extracting of reusable items

### ISSUE THREAD

**Issue by AndrewR73** [PrinceOfAmber/Cyclic#1815]
Minecraft Version: 1.16.5

Forge Version: forge-36.1.3/forge

Mod Version: 1.16.5-1.2.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Crafting honey blocks in the Crafting Machine by feeding in filled honey bottles, the post craft items are Honey Blocks and empty glass bottles. The Honey blocks are placed in the output side allowing for hopper (or other means) to extract away. However, the empty glass bottles are placed back into the Input side and are not extractable by automated means. The only way to remove is manually pulling them out. Eventually the honey bottles are replaced by empty bottles preventing the machine from working.

There needs to be a way to designate that "reusable" items are not to be held in inventory, allowing them to be extracted like the result items of the craft -- a toggle button to turn on/off retention of reusable items, maybe?

Log file link: N/A

Video/images/gifs (direct upload or link): 
![Screenshot 2021-04-15 090827](https://user-images.githubusercontent.com/8558973/114885025-defd5b80-9dcb-11eb-9efc-a88f2de1251f.png)

**Comment by BuggaNoia** [comment]
Solved here: https://github.com/Lothrazar/Cyclic/issues/1811
