### ISSUE TITLE
Server startup crash on version 1.16.5-1.2.6

### ISSUE THREAD

**Issue by starmun-0010** [PrinceOfAmber/Cyclic#1816]
#### Minecraft Version: 
Server 1.6.5

#### Forge Version: 
forge-1.16.5-36.1.4

#### Mod Version: 
Cyclic-1.16.5-1.2.6.jar

#### Single Player or Server:
Server

#### Details
The server crashes on startup with a java.lang.NoClassDefFoundError. 
Error only seems to exist with the latest version of the mod i.e. 1.2.6 and disappears with 1.2.5.

Crash report is attached below

[crash-2021-04-15_21.27.00-fml.txt](https://github.com/Lothrazar/Cyclic/files/6319608/crash-2021-04-15_21.27.00-fml.txt)
[latest.log](https://github.com/Lothrazar/Cyclic/files/6319617/latest.log)

**Comment by zISKo666** [comment]
I have the same crash on my servers startup.

**Comment by IchigoGames** [comment]
same

**Comment by Dunkmania101** [comment]
It looks like it's trying to use the MatrixStack class. I'm pretty sure it's for client-sided stuff, although the logs don't seem to say anything about invalid dists in particular. Maybe it still is that and the problem comes from the class not being available on the server, instead of from the dist marker thingies? Is that a thing?

**Comment by kreezxil** [comment]
Confirmed!

Issue:  1.16.5-1.2.6 crashes dedicated server Forge 1.16.5 build 36.1.4

Notes:
     java.lang.NoClassDefFoundError: com/mojang/blaze3d/matrix/MatrixStack

crash report: 
https://gist.github.com/70f0fd369cf45f53a1f3ef59ce6840ac

fml server latest: 
https://gist.github.com/e1909e94944136521f268080a5ce4102

**Comment by kreezxil** [comment]
version 1.2.5 works without a hitch btw, if that helps.

**Comment by Lothrazar** [comment]
sent up 1.2.7 for a fix https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3279021

**Comment by kreezxil** [comment]
Thank You So Much! That did fix it!
