### ISSUE TITLE
Scythe doesn't work with vanilla seeds in Stoneblock 2

### ISSUE THREAD

**Issue by jdhenry08** [PrinceOfAmber/Cyclic#1817]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.20.6

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
I have a 7x7 field of fully grown wheat with a single water block in the center. There's a tier 1 growth crystal (tiny progressions) below the water, and a sprinkler above the water. When I right click with the garden scythe on one of the fully grown wheat plants, it LOOKS like every plant is harvested (visually, they all go back to 0% growth progress), but only the plant I right clicked is actually harvested and replanted (I got a single wheat and seed). If I right click on any of the other plants, they drop their normal yield and continue growing like normal.

**Comment by jdhenry08** [comment]
I'm guessing this might be related to the right click harvest/replant functionality, but I'm not positive.

**Comment by Lothrazar** [comment]
Can you maybe take screenshots or video?  
Its possible that when you use it on a plant, a different right click harvest mod activates, try using the scythe on a nearby dirt or stone .  I did a test with wheat and mystical agriculture , it seemed great 
![1817](https://user-images.githubusercontent.com/621529/115103406-723aac00-9f06-11eb-8355-44b5952c9eb8.gif)

**Comment by jdhenry08** [comment]
No wheat/seeds in inventory:
![2021-04-18_15 30 36](https://user-images.githubusercontent.com/11464199/115159987-77f5d600-a05b-11eb-95a6-28a509cfb2b7.png)

Full field of fully-grown wheat:
![2021-04-18_15 30 31](https://user-images.githubusercontent.com/11464199/115159994-804e1100-a05b-11eb-97fc-a13eda8b5c59.png)

Right click on wheat in the corner of the field (note that WAILA says the wheat I'm looking at is fully grown still):
![2021-04-18_15 30 45](https://user-images.githubusercontent.com/11464199/115160017-9bb91c00-a05b-11eb-892a-77d8bf19cbd4.png)

Only one wheat/seed in inventory:
![2021-04-18_15 30 48](https://user-images.githubusercontent.com/11464199/115160034-b2f80980-a05b-11eb-8892-38a71e71b851.png)

**Comment by Lothrazar** [comment]
Yeah the seeds get planted again. back into the ground.  IDK if this is good or bad but its how it always worked

**Comment by zoller27osu** [comment]
this was very easily replicated in the latest beta of Stoneblock 2 (in case relevant, on a server).

**Comment by zoller27osu** [comment]
@Lothrazar this was very easily replicated in the latest beta of Stoneblock 2 (still on 1.12.2, in case relevant, on a server).
Even a pumpkin disappeared but you can tell it's not really gone because you can't walk into the space it occupied.
No durability on the Scythe is consumed either.

Interestingly, it seems to do the exact opposite in a Mechanical User with Use Item on Block (i.e. consumes durability, silk touched melons and essences pop out above Mechanical User, no visual block updates on the client)...
