### ISSUE TITLE
Odd interaction between 'Resourceful Bees' centrifuge and 'Cyclic' item cable

### ISSUE THREAD

**Issue by Ben10inch** [PrinceOfAmber/Cyclic#1818]
Minecraft Version: 1.16.5

Forge Version: 36.1.3

Mod Version: 1.2.1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

For some reason, item cables seem to stop extracting when centrifuge finishes a processing cycle (see attached video)

Log file link:

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/82653572/115017835-64116f00-9eb7-11eb-9b9a-beae43caf4f6.mp4

**Comment by AndrewR73** [comment]
I noticed this also happens on other items beyond the Centrifuge. Barrels, Chests, and other blocks where the block undergoes some kind of status change (opening a barrel for instance) causes the "Pull" setting to be reset.

**Comment by alric71** [comment]
Having the same issue also with the Cyclic Item Cables. The fluid cables do the same thing trying to extract honey from Resourceful Bees centrifuge. Very frustrating!!!

**Comment by Lothrazar** [comment]
i cant find anything that explains this. every single other fluid container from like a dozen other mods dont have any issues. at least with the latest verision
