### ISSUE TITLE
ender bookshelves causing significant frame drop

### ISSUE THREAD

**Issue by alexshore** [PrinceOfAmber/Cyclic#1819]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.8

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Ender bookshelf causing significant fps drop,,,,, I stumbled upon another issue thread for the end bookshelf and didnt know if you had implemented any of the changes intended to fix the issue such as adding an option not to render the text at all as it is really massively decreasing my performance

when not looking at the bookshelves
![Screenshot_16](https://user-images.githubusercontent.com/40403410/115127965-82b85880-9fd2-11eb-8487-9a0f162a4b77.png)

when looking at the bookshelves
![Screenshot_17](https://user-images.githubusercontent.com/40403410/115127968-8350ef00-9fd2-11eb-961c-07dcc668b27d.png)

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
ah. looks like its the part where it renders the picture of the enchanted book, with the shine and everything.   

I should disable that, maybe with a config or something because ya huge drop

**Comment by Lothrazar** [comment]
Because im curios how many shelves did you have up in that screenshot

**Comment by alexshore** [comment]
uhh we had quite a few, like maybe 30/40, i cant remember now. we circumvented the issue by just throwing all the bookshelves into a compact machine and only going in there when we needed
