### ISSUE TITLE
[Feature Request] Add sprinklers back, toggable with config option.

### ISSUE THREAD

**Issue by Nopm** [PrinceOfAmber/Cyclic#1820]
Hey!

Normally I'd use the issue template, but as this is a feature request, I don't think it's all too relevant.

Simply, I suggest that sprinklers, as they functioned in 1.12, stacking and all, be added back to Cyclic. I'm aware of the Terra Preta block, but currently it has two major issues for modpack developers such as me:

1. It doesn't work in an area;
2. What probably is the biggest issue, is that it checks whether bone meal works or not in said crop. Without a config option for it, this makes it hard for modpack developers to balance their pack. Currently, there isn't a single OpenBlocks sprinkler alternative for 1.16 that I could find, making automating things such as Mystical Agriculture really difficult in Skyblock-type modpacks.

I believe the Terra Preta was used instead of the sprinkler for balancing reasons, so if that is the case, I also suggest adding a config option for enabling/disabling the crafting and/or use of sprinklers, including the ability to toggle whether they stack with each other or not.

**Comment by Lothrazar** [comment]
Yeah. Terra preta can stay but they need a power buff, maybe stackable.

For sprinklers we could do maybe a few different smaller sizes such as 5x5 ? and some bonemeail checking that uses the same logic.  Should large ones consume something ? water and/or power? still probably checking for water src below

**Comment by Nopm** [comment]
I'm all up for having various tiers of sprinklers, each being progressively more expensive to craft and requiring the previous tier as a crafting ingredient, so that they're not hard to upgrade. Each tier could maybe speed up crop growing by a certain factor with increased range, while also requiring more water to be piped into/below the sprinkler itself, perhaps power?

The bonemeal logic is something that I think should be toggable in a config option. Some modpack developers might wanna let people use sprinklers with Mystical Agriculture, and you can't use bonemeals with MA crops, though I believe it should by default come turned on.

**Comment by Lothrazar** [comment]
added but they consume water now
