### ISSUE TITLE
why  Fluid Collector  not work?

### ISSUE THREAD

**Issue by bd-dxg** [PrinceOfAmber/Cyclic#1822]
Minecraft Version: 1.16.5

Forge Version: 36.1.0

Mod Version: Cyclic-1.16.5-1.2.7.jar

Single Player or Server: Player

Describe problem (what you were doing; what happened; what should have happened):

Why doesn't the machine work?

I gave it power

Give the fluid pipe

Give the  fluid tank

But it just doesn't work!   why?

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/34816426/116191621-38b43d00-a75f-11eb-8e9a-5acea6d00751.png)

![image](https://user-images.githubusercontent.com/34816426/116191651-47025900-a75f-11eb-8710-dd0e360aa445.png)

not work!!!!

**Comment by bd-dxg** [comment]
anywhere?

**Comment by Lothrazar** [comment]
Try making the area smaller? I just put one beside a river in a new world, and gave it stone, and it filled up with water nad placed it all
![2021-05-22_14 27 28](https://user-images.githubusercontent.com/621529/119241244-d9510f00-bb09-11eb-8f03-2674a178b430.png)
