### ISSUE TITLE
Void Charm and Charm Talisman Break in seconds after falling into the void

### ISSUE THREAD

**Issue by ScythiaThe1st** [PrinceOfAmber/Cyclic#1823]
Minecraft Version: 1.16.5

Forge Version: forge-36.1.4

Mod Version: Cyclic-1.16.5-1.2.7

Single Player or Server: both

Modpack: Direwolf20-1.16

Describe problem (what you were doing; what happened; what should have happened):
as i understand correctly when falling into the void the charm is supposed to teleport you to height limit only using one durability and just drop you/to your death) what happened instead is that the charm began consuming its durability in seconds and then broke, during its self destruction i was stuck in midair waiting for my charm to break
this goes for both the void charm and charm talisman

Log file link: i can't retrieve the log file due to the fact i do not own the server

Video/images/gifs (direct upload or link): 
VoidCharm: https://youtu.be/h0hailb5W54
CharmTalisman: https://youtu.be/FQQMI1iT4VM

**Comment by Lothrazar** [comment]
Fixed in newest versions 

![2021-07-07_17 48 44](https://user-images.githubusercontent.com/621529/124845577-dee4a600-df4b-11eb-9567-70989b71aeb0.png)
