### ISSUE TITLE
Problems with Forge and Cyclic 

### ISSUE THREAD

**Issue by SaintRub** [PrinceOfAmber/Cyclic#1826]
[crash-2021-05-01_17.38.50-fml.txt](https://github.com/Lothrazar/Cyclic/files/6409858/crash-2021-05-01_17.38.50-fml.txt)

Minecraft Version: 1.16.4

Forge Version: forge-1.16.4-35.1.37

Mod Version: 1.16.5

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Minecraft crash du to an error on cyclic (Pics at the end of issues)

Log file link:

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/83508046/116787708-f0ba5080-aaa5-11eb-9f58-acee85af10ae.png)

**Comment by Lothrazar** [comment]
maybe something in config files ? It doesnt like uppercase False, forge nightconfig wants lowercase "false"

**Comment by SaintRub** [comment]
Yeah, you’re right, thank you so much buddy I’d put a « F » instead of a « f » on a false/true value.
Sorry for my poor english, cheers from France 🇫🇷 
P.s: your mod is amazing ❤️

Bless you , best regards J.Saint Rub

Envoyé de mon iPhone
