### ISSUE TITLE
Energy Cables Without Extraction

### ISSUE THREAD

**Issue by akip1** [PrinceOfAmber/Cyclic#1828]
Minecraft Version: 1.16.5

Forge Version: 36.1.4

Mod Version: 1.2.7

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): 
Energy cables cannot be changed to extract power using a Cable Wrench, making them practically useless. (Also, 1.12.2 versions
allowed filters and customized extraction rates, but item/fluid cables can no longer do that.)
Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/6417648/latest.log)
Video/images/gifs (direct upload or link): 
https://user-images.githubusercontent.com/83151411/116932735-41f24d80-ac28-11eb-9739-7c5959833ce9.mp4

*Little note here, playing on the latest version of FTB Presents Direwolf20 1.16, with ProjectE 1.0.1B added.*

**Comment by Lothrazar** [comment]
WIP 
![2021-05-22_10 51 30](https://user-images.githubusercontent.com/621529/119236372-e4954200-baeb-11eb-80c1-4bb6d9018050.png)
