### ISSUE TITLE
No config to change the armor values of Emerald Armor or Crystallized Obsidian Armor.

### ISSUE THREAD

**Issue by Reshy** [PrinceOfAmber/Cyclic#1829]
Minecraft Version: 1.16.5

Forge Version: 36.0.42

Mod Version: Cyclic-1.16.5-1.2.6.jar

Problem:  There is no way to adjust the armor values of the Emerald Armor, the Leggings and Chest Piece specifically have disproportionately more armor value than any other vanilla armor, and even most modded armors.  Emeralds are very easy top get a hold of so it makes this really powerful armor trivial to obtain.   Crystallized Obsidian is a bit harder to get, however it comes across as too much still for a lack of config.

**Comment by Lothrazar** [comment]
i thought this was trivial in craft tweaker or data packs but i guess not. a config would be useful
