### ISSUE TITLE
Piston Scepter can move protected blocks

### ISSUE THREAD

**Issue by javierapl12** [PrinceOfAmber/Cyclic#183]
it can grief in protected areas of FtbUtilities and protected blocks by better builder wands

**Comment by PrinceOfAmber** [comment]
Ah, thanks for reporting.  I hope its easy to detect if the area is protected or not.

**Comment by PrinceOfAmber** [comment]
I wonder if this same bug applies to other building type tools in here, such as the cyclic build scepter or the scythes

**Comment by PrinceOfAmber** [comment]
Copying reply here for posterity

> LatvianModder commented 14 hours ago
First, you should make a permission nodes for your mod actions - like "cyclic.tool.break", "...place" or just one common node like "cyclic.tool.modify" or smth like that. Register that node in PermissionAPI during INIT (probably with value ALL by default) and then just check with PermissionAPI.hasPermission(gameProfile, node, context) context should contain BlockPos

**Comment by PrinceOfAmber** [comment]
Reference https://github.com/MinecraftForge/MinecraftForge/pull/3155

**Comment by PrinceOfAmber** [comment]
Looks like i need minimum forge version Build 1.10.2-12.18.2.2121

**Comment by PrinceOfAmber** [comment]
Updated in release 1.9.0 to use the api
