### ISSUE TITLE
Solidification Chamber not creating magma cream

### ISSUE THREAD

**Issue by jamest23** [PrinceOfAmber/Cyclic#1833]
Minecraft Version: 1.16.5

Forge Version: 36.1.2

Mod Version: Cyclic-1.16.5-1.2.7

Single Player or Server: Replicated in single player and dedicated server

Describe problem (what you were doing; what happened; what should have happened):
Playing on All the Mods 6 Sky-1.0.8, put magma and 3x slimeballs into the solidification chamber, processing runs down to zero, then nothing happens, no magma cream is output.

Recipe shows 100mB magma and 3x slimeballs should make 6 magma cream.

Log file link:

Video/images/gifs (direct upload or link): 
![solificationChamber](https://user-images.githubusercontent.com/28601039/118346438-a4c7db00-b57e-11eb-8acc-c4e2e298f1da.png)
![recipe](https://user-images.githubusercontent.com/28601039/118346440-a98c8f00-b57e-11eb-8985-71173d2a3846.png)

**Comment by derekspelledcorrectly** [comment]
I also have this problem, and had this recipe working fine before. I actually think it might be a breaking change in Patchouli 1.16.4-51, because it broke for me when Patchouli was bumped to 1.16.4-51 but Cyclic remained at 1.16.4-1.2.7.

#### Works with:
- Cyclic-1.16.5-1.2.7
- Patchouli-1.16.4-50

#### Doesn't work with:
- Cyclic-1.16.5-1.2.7
- Patchouli-1.16.4-51

**Comment by derekspelledcorrectly** [comment]
Actually just realized there are 3 other dependencies that got version bumps when this broke for me:

- curios-forge-1.16.5-4.0.5.0 to 4.0.5.1
- EnchantmentDescriptions-1.16.5-7.0.3 to 7.0.8
- jei-1.16.5-7.6.4.86 to 7.7.0.98

Maybe is more likely Curios?

**Comment by Lothrazar** [comment]
testing with
curios 4.0.5.1
JEI 7.7.0.99
forge 36.1.23
cyclic 1.2.7+
![1833](https://user-images.githubusercontent.com/621529/119241150-44e6ac80-bb09-11eb-9697-530ae7fe6a34.gif)

**Comment by derekspelledcorrectly** [comment]
It's currently reproducible in the Direwolf20 1.16 FTB pack. Worked until 1.10.0, is now broken.

**Comment by peckozz** [comment]
It's currently reproducible in tnp modpack 1.10.3
cyclic v 1.2.7

**Comment by Lothrazar** [comment]
Recipes all are compatible with fluid tags. Is there another mod adding magma fluid that is not tagged?  Testing in the latest 1.2.9 mod version still works, at least in standalone outside modpack.  fluid tag is "forge:magma"  

"It's currently reproducible in the Direwolf20 1.16 FTB pack. Worked until 1.10.0, is now broken."

This sounds like something in the pack or another mod changed 
![1833](https://user-images.githubusercontent.com/621529/120932512-ff9ab100-c6aa-11eb-8baa-428bcd76dd8c.gif)

**Comment by Nevyn0** [comment]
I believe the conflict is with Tinkers Construct. Remove it from pack and now can use Solidification Chamber for crafting with Magma.

**Comment by Corbi84** [comment]
Maybe a conflict with the liquid magma cream from Tinkers? Got the same problem on ATM6 (1.6.4 through 1.6.10). Other recipes work fine, it just won't create the magma cream (balls).

**Comment by Lothrazar** [comment]
recipes using tags now :)

**Comment by ZeldasWetDream** [comment]
I still have this problem :/

**Comment by VarsityPhysicist** [comment]
This issue is still present in the Direwolf20 1.11.0 pack

I tried updating to Cyclic 1.16.5-1.3.8 or 1.4.0 since it was noted that recipes use tags, but this recipe isn't working

**Comment by thefastlanesolution** [comment]
Issue still present...
