### ISSUE TITLE
[Bug] Mod Conflict: Vampirism Transformation-Inventory Upgrade

### ISSUE THREAD

**Issue by ProximityParadox** [PrinceOfAmber/Cyclic#1835]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Transforming into either a Vampire or a Vampire Hunter using the "Vampirism" Mod will cause all stored items in the "upgrade inventory" cake will vanish.

[Link to Vampirism Mod](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)

[Link to Vampirism Github](https://github.com/TeamLapen/Vampirism)

**Comment by Lothrazar** [comment]
Items are stored in a custom file in the servers /playerdata/ folder. for example

/saves/world/playerdata/_somebody.info   

So if those files exist they should be recoverable. If you re-upgrade again to get the button back are the items saved?
(if the players minecraft name gets overridden/changed this might cause it?)

The button is a true false in the players NBT data (so i think in the player file) with keys hasInventoryExtended / hasInventoryCrafting

Code of IPlayerExtendedProperties

https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/capability/InstancePlayerExtendedProperties.java#L15

Does vampirism delete the player entity without copying data over? Or change the player name or player UUID?
i dont really see how to fix it, but hopefully that information helps

**Comment by Lothrazar** [comment]
stale issue
