### ISSUE TITLE
No way to rotate the Block Breaker to face AWAY from player

### ISSUE THREAD

**Issue by DizzyDJW** [PrinceOfAmber/Cyclic#1837]
Minecraft Version: 1.16.5

Forge Version: 36.1.4

Mod Version: 1.2.7

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
There is no way to place the Block Breaker and have it face AWAY from the player, the wrench also does NOT work in rotating it.

**Comment by DizzyDJW** [comment]
Just a simple shift to place away from player or have the facing ba based on the four directions of a block would be awesome

**Comment by Lothrazar** [comment]
yeah you can place it and walk around it after. actually fix it so Wooden wrench with any facing or horizontal_facing states can rotate

**Comment by Lothrazar** [comment]
![1837](https://user-images.githubusercontent.com/621529/119237590-799b3980-baf2-11eb-9f88-73a88a7bfd26.gif)
