### ISSUE TITLE
Cables causing crashes if attached to Create contraptions

### ISSUE THREAD

**Issue by hedgehog1029** [PrinceOfAmber/Cyclic#1838]
Minecraft Version: 1.16.5
Forge Version: 36.1.0
Mod Version: 1.2.3
Single Player or Server: Server
Log file link: https://paste.dimdev.org/pokonehohu.mccrash

Moving an item cable with a Create contraption causes a crash:
1. Create removes the tile entity attached to a block before removing the block (as the tile entity has already been serialized onto the contraption)
2. Cyclic does not perform a null check [here](https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/block/cable/item/BlockCableItem.java#L66):

```java
  @Override
  public void onReplaced(BlockState state, World worldIn, BlockPos pos, BlockState newState, boolean isMoving) {
    if (state.getBlock() != newState.getBlock()) {
      TileEntity tileentity = worldIn.getTileEntity(pos);
      for (Direction d : Direction.values()) {
        IItemHandler items = tileentity.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, d).orElse(null);
```

You can just add an `if (tileentity != null)` check surrounding this code (early return would skip the supercall), as if the tile entity is gone there's not anything left to drop (chests do the same, just with an `instanceof` check).

It's good practice to assume a tile entity retrieved from the world can be null; there are several other reasons it could be (for example, if the server has Forge's "remove erroring tile entities" config option enabled)

There might be other tile entities in Cyclic that have a similar issue, I haven't checked.

**Comment by Lothrazar** [comment]
yeah good call on the null check . 

`
java.lang.NullPointerException: Ticking block entity
        at com.lothrazar.cyclic.block.cable.item.BlockCableItem.func_196243_a(BlockCableItem.java:68) ~[cyclic:1.16.5-1.2.3] {re:classloading}`
