### ISSUE TITLE
How do I mode change on the piston sceptre?

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#184]
Perhaps I'm having an attack of the dumb, but I can't figure out how to mode change the piston sceptre! There are no keybinds that I can find in-game or in the config file and I've tried various shift/ctrl/alt + left/right clicks!

Incidentally, I noticed the thread about the wiki. If you want to, just type out a mess of informative text in pages titled "to be sorted" and delegate a volunteer or two to clean it up and organise it. You should find plenty of volunteers for that part.

Cheers!

**Comment by PrinceOfAmber** [comment]
Left click on a block will change the mode.  Yeah i really need to get onto the wiki. I had been putting it off because i kept intending to make an ingame book, but i should do the wiki on the website first.  Then i can just pull that information in game if i need to

**Comment by PrinceOfAmber** [comment]
Closed since duplicate of  https://github.com/PrinceOfAmber/Cyclic/issues/140 basically wiki needed

**Comment by PrinceOfAmber** [comment]
https://github.com/PrinceOfAmber/Cyclic/wiki/Piston-Scepter
