### ISSUE TITLE
Ender Controller/Shelves Connection (1.2.8)

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#1841]
Minecraft Version: 1.16.5

Forge Version: 36.1.24

Mod Version: 1.2.8

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
If an Ender Controller is broken then replaced, it no longer "sees" the Ender Shelves next to it. Only by then breaking and then replacing one of the shelves does it seem to "update" and notice the shelves.

**Comment by Lupus590** [comment]
Maybe related, placing a shelf caused the shelf to stay in my inventory and be placed.

And the controller didn't drop when I broke it and also stayed in my inventory when I placed it (cheated in via JEI).

**Comment by Lothrazar** [comment]
yeah i broke something in the controller in 1.2.8, fix on the way

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3337264
