### ISSUE TITLE
Antimatter Evaporator destroys everything

### ISSUE THREAD

**Issue by ZeekDaGeek** [PrinceOfAmber/Cyclic#1843]
Minecraft Version: 1.6.2.

Forge Version: 36.1.23

Mod Version: 1.2.8

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
When the Antimatter Evaporator is in "Generic" mode it destroys fluids and blocks. Simply right click and watch your new hand held Clearing Quarry destroy everything including bedrock!

Edit:
Apparently it won't destroy blocks that are water loggable.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3337264
