### ISSUE TITLE
Miner still mines itself

### ISSUE THREAD

**Issue by LoneStarrr** [PrinceOfAmber/Cyclic#1845]
Minecraft Version: 1.16.5

Forge Version: 

Mod Version: 1.2.7

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):

Exactly issue #1744 - miner will mine itself when given a pickaxe and power.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Can you screenshot your GUI settings when it mined itself? I tried it both up and down, large squares and small, and its staying in the boundary. at least it hasnt yet mined itself.

Maybe its a very specific setting that makes the bug happen?  But i cant find it.  example 

In the screenshot, here it just digs the 3x3 hole down four and then stops
![2021-06-03_16 16 16](https://user-images.githubusercontent.com/621529/120723715-224c8000-c487-11eb-9894-644e22f6d89f.png)

**Comment by Lothrazar** [comment]
![2021-06-03_16 17 28](https://user-images.githubusercontent.com/621529/120723757-355f5000-c487-11eb-8282-ebd9dc3f228d.png)

**Comment by LoneStarrr** [comment]
I don't remember setting anything specific but I'll give it a shot in creative.

**Comment by LoneStarrr** [comment]
Ah, it's a mod interaction issue. With `ftb-chunks-1605.2.3-build.75` and the chunk claimed, it will always mine itself in 100% of all cases, whether a pickaxe is inserted or not. If the miner's fake user is allied, it will still do so. 

The item user does work in a claim with the fake user allied, however each individual item user has its own fake user whereas some other mods use a single fake user for all instances (e.g. modular routers). Might be worth looking into because it gets real messy on a server with all those fake users. But that's for another issue I suppose.

**Comment by Lothrazar** [comment]
How could i use one fake player instance for every single block placed in the world? What if i place two Users and give each of them a different item? The item in the first block would overwrite the item in the second block.  

Chunk permissions mods need to be ignoring fake players anyway, that sounds like a bug they should think about
