### ISSUE TITLE
Item Cables Transfer Items Despite Being Visually Disconnected 

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1847]
Minecraft Version:  1.16.5

Forge Version: 36.1.25

Mod Version: 1.2.8

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Connect 2 vanilla chests with an Item Cable. Then, using a wrench, disconnect one of the chests. The items will still transfer despite the connection visually not connected (that was a sentence that makes sense).

Log file link:

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/10309699/120704791-e22bd400-c46b-11eb-99cd-e78722189c38.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3337264

**Comment by Lothrazar** [comment]
@Darkosto fixing the issue where items still flow through the yellow blocks also that i saw on stream, continuing some testing for upcoming 1.2.10 release
