### ISSUE TITLE
 no recipes in JEI for 1.2.10

### ISSUE THREAD

**Issue by CKY-** [PrinceOfAmber/Cyclic#1849]
Minecraft Version: 1.16.5

Forge Version: 36.1.25

Mod Version: 1.2.10

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):

Jei all items have no recipes there is a conflict in cyclic that is causing all recipes to not be displayed in JEI.
reverting to 1.2.9 fixes this, there is no errors in any log so this is going to be a bit hard to track down. the version 9 and version 10 logs are identical.. this not going to be easy. 
adding jei, quark, craft tweaker, cosmetic armor, iron chests, and cyclic to a pack  and trying to craft anything will result in no recipes.

this is not affected by single player 

Log file link:

https://pastebin.com/258YcpuF

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Testing with JEI 7.7.0.99 and i get recipes loading.  Nothing in that particular log shows an error.  Any data packs causing issues or broken recipes? Maybe a different debug log or crash report?

**Comment by CKY-** [comment]
Well as that's the only mods that where loaded I dont know? there was no changes to anything I simply created a new project  and added the 6 mods no tweaking or data packs.  I do see that you fixed  https://github.com/Lothrazar/Cyclic/issues/1848 and pushed a new version. I will give this a try and report back this after noon.

**Comment by CKY-** [comment]
Lothrazar Seems to have been related not sure why it was not showing in the error log for me but you did gud thank you..
