### ISSUE TITLE
Shift-clicking a Speed Charm from a chest into inv makes you drink it! - add on/off toggle

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#185]
Hi,

I found a Speed Charm in a dungeon chest. I shift-clicked it to move into my inventory and triggered, buffing me and taking a durability it. I think it would be better if it didn't do that :-) 

edit: It could be bad if an ender bomb or similar triggered under similar conditions :-P

Incidentally, I've found Cyclic loot quite common in chests. Like, 3-5 pieces in a single chest. Is there any way to reduce the drop rate (perhaps to just 1 per dungeon chest)? I feel that 3-5 devalues the items somewhat.

Cheers!

**Comment by PrinceOfAmber** [comment]
Yeah thats a good idea.  By design i started out the charms just to work in your regular inventory.  It wasnt till a few versions later that i added bauble support, but it still has the inventory feature.  But for speed there is no 'trigger' like the other charms, so on / off makes sense.

**Comment by PrinceOfAmber** [comment]
Just had another idea:  If i could get the charm to increase the players speed without potion effects.

**Comment by PrinceOfAmber** [comment]
Behavior has changed in 1.9 + , it no longer gives potions. it just passively increases your base speed, so you dont suddenly get the sound or particles of a potion when pulling from a chest :) 

Enjoy and feel free to leave more feedback in future.

**Comment by xenoflot** [comment]
@PrinceOfAmber Service with a smile! Thank you!
