### ISSUE TITLE
[1.16.5] Server crash when eating an Ender Apple

### ISSUE THREAD

**Issue by Gbergz** [PrinceOfAmber/Cyclic#1851]
**Minecraft Version**: 1.16.5

**Forge Version:** 36.1.31

**Mod Version**: 1.2.8

**Single Player or Server**: Server, maybe single player too. Not sure.

**Describe problem (what you were doing; what happened; what should have happened):**
1. Ate the ender apple, 
2. server lagged and closed.
3. `Internal Exception: java.io.IOExeption: An existing connection was forcibly closed by the remote host.`

**Log file link(crash-report):**
https://gist.github.com/Gbergz/88706c1c8ced7c62b34ea9bd60e73f0b

**Note**
By looking at the logs it looks like Cyclic is mentioned but also repurposed structures, maybe its a cross mod issue.
Reporting here to be sure though.

**This apple:**
![image](https://user-images.githubusercontent.com/26634554/121867624-7154a980-cd00-11eb-9cf9-a5fcb1ceb369.png)

**Comment by Lothrazar** [comment]
ill add a safety handler to patch part of it. the apple basically uses the /locate command to print results, but repurposed structure mod took too long under their locateStructureFast method, so server watchdog jumped in
