### ISSUE TITLE
Cyclic Ender Shelf Duplicating

### ISSUE THREAD

**Issue by CloWnicide** [PrinceOfAmber/Cyclic#1852]
Minecraft Version: 1.16.5

Forge Version: 36.1.24

Mod Version: 1.2.8

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

While placing down ender shelves, I could keep inserting books into my shelves, open my backpack and the books would reappear as duped items. Then I noticed my other controller would not accept books into it, so I would break it, and the block would disappear until I tried to put another block down (which happened to be another ender shelf), then I was able to break the controller and pick it up without any problems. Then, as seen in the video below, I was able to duplicate shelves by just right clicking with an empty hand until I put a shelf down that was supposed to have book in it.

30837 is the line where the issue is starting.

[17Jun2021 03:08:42.392] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: class com.lothrazar.cyclic.block.endershelf.TileEnderShelf cannot be cast to class com.lothrazar.cyclic.block.enderctrl.TileEnderCtrl

Log file link: https://gist.github.com/CloWnicide/3655502b23fc08ee1f9de70a2dfaf81a

Video/images/gifs (direct upload or link): https://streamable.com/5tjrip

**Comment by Lothrazar** [comment]
Thanks for the report, this was fixed in 1.2.9
