### ISSUE TITLE
Elevation to the nether roof, can't get back without cheating.

### ISSUE THREAD

**Issue by rtxyd** [PrinceOfAmber/Cyclic#1853]
Minecraft Version: 1.16.5

Forge Version: 1.16.5-forge-36.1.31

Mod Version: Cyclic-1.16.5-1.2.11

Single Player or Server:Single Player

Describe problem (what you were doing; what happened; what should have happened):
"rod of elevation" is able to teleport to the nether roof. but there is no way to get back unless cheat.

Log file link:None

Video/images/gifs (direct upload or link): 
![2021-06-22_00 36 11](https://user-images.githubusercontent.com/65117312/122798378-1cfa8c80-d2f3-11eb-9019-f991a2782928.png)

**Comment by Lothrazar** [comment]
yeah, gotta be careful

**Comment by Lothrazar** [comment]
you can do the same thing with ender pearls, if you spam shoot them up at a 1 thin bedrock plane you can get through. make sure to bring a way back, maybe an item that can teleport
