### ISSUE TITLE
Incompatibility with Forestry in 12

### ISSUE THREAD

**Issue by joe-vettek** [PrinceOfAmber/Cyclic#1855]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Mod Version: 1.20.9

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened):

Thank you very much for the mod you made, which provides a lot of convenience for my Minecraft-life. But I found that the peat -generator of the mod cannot use the peat of Forestry as fuel. The reason is that it was written down when judging whether it is peat-fuel. I don't know if you can change it to ore or other ways.

Log file link:

None.

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/82761814/123250526-bd7fc500-d51c-11eb-9da4-6c48ae8af97f.png)

**Comment by joe-vettek** [comment]
Sorry for forgetting a problem. The use of Brush Scythe is also limited and cannot be used to destroy grass in other mods, such as Project: Vibrant Journeys. The configurable content of version 1.12.2 feels a bit lacking.

**Comment by Lothrazar** [comment]
At the time there wasnt any ore dictionary entries for peat fuel. also letting them each use the other would have broken the game balance and progression of existing modpacks.

**Comment by Lothrazar** [comment]
As for scythe, the config allows extra items to be added to be harvestable.
inside
S:tool_harvest_weeds.whitelist <

Also cyclic has the custom wildcard system. so if you have plants like

vibrant:blue_grass
vibrant:green_grass
with a ton of variants
You can just put in

vibrant:*_grass

and it will hit them all

Sample config: 
https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/cyclicmagic.cfg#L1488

**Comment by joe-vettek** [comment]
Thanks for your reply, I received it.
