### ISSUE TITLE
Cyclic Scepter does not work with Chisels & Bits blocks

### ISSUE THREAD

**Issue by rahangar** [PrinceOfAmber/Cyclic#186]
Cyclic Scepter does not seem to work with Chisels and Bits blocks.

By Chisels and Bits blocks, I mean custom blocks that I created using Chisels & Bits.

When I place the block, the animation shows as if it placed it, but no block gets placed.  Also, the block count in the scepter's inventory is reduced which presumably means those blocks are disappearing from the world.

This issue is a lot like the Handheld Filler (ActuallyAdditions mod) issue that I raised a couple of days ago.

**Comment by PrinceOfAmber** [comment]
I've never used chisel and bits too much, it probably doesn't recognize them.  Or maybe some data needs to be moved in from the itemstack to the block to set its structure.  Do you have a link to the ActuallyAdditions  ticket if there was one?

**Comment by rahangar** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/412
That's the actually additions ticket I raised

**Comment by PrinceOfAmber** [comment]
Looks like also related to https://github.com/romelo333/notenoughwands/issues/39

**Comment by PrinceOfAmber** [comment]
Possible solution:

instead of using metadata integers, use onItemUse(EntityPlayer playerIn, World worldIn, BlockPos pos, EnumHand hand, EnumFacing side, float hitX, float hitY, float hitZ)

**Comment by PrinceOfAmber** [comment]
Should be resolved in latest release https://minecraft.curseforge.com/projects/cyclic/files/2354294
