### ISSUE TITLE
None of wireless blocks work on 1.16.5

### ISSUE THREAD

**Issue by 3baady** [PrinceOfAmber/Cyclic#1862]
Minecraft Version:  **1.16.5**

Forge Version: **Latest version**

Mod Version: **Latest version**

Single Player or Server: **SP**

Describe problem (what you were doing; what happened; what should have happened):

**Wireless transmitter and wireless receiver dont work.** 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
What does this mean

"dont work"

Please explain.  did you set it up correctly via the instructions? 
![1862](https://user-images.githubusercontent.com/621529/124838533-e56b2180-df3b-11eb-87cb-ab48fdd9da04.png)

**Comment by Lothrazar** [comment]
if you are having trouble, use the preview button and it will try to lazer the target 
![proof](https://user-images.githubusercontent.com/621529/124838655-25ca9f80-df3c-11eb-9d54-e55d11d4cbed.png)

**Comment by Lothrazar** [comment]
the transmitter needs a signal too, like a lever, it doesnt magic out a signal from nowhere. so power the transmitter like this 
![haha](https://user-images.githubusercontent.com/621529/124838745-5579a780-df3c-11eb-8e38-713702f16157.gif)
