### ISSUE TITLE
automated user bug area

### ISSUE THREAD

**Issue by superlele07** [PrinceOfAmber/Cyclic#1863]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
in this version the creator fixed the problem of the automated user for the big area, but done this you broke the area in 1x1 as the large areas

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
"Mod Version: 1.20.3"

20.9 is the latest. I just gave it a shovel and it made paths in the 3x3 area 
![2021-07-11_11 19 30](https://user-images.githubusercontent.com/621529/125206051-f8cb0500-e239-11eb-9cd9-7bcd66e49ce5.png)
