### ISSUE TITLE
Feature Suggestion - Item to copy and paste signs and GUI settings of blocks 

### ISSUE THREAD

**Issue by Temenat** [PrinceOfAmber/Cyclic#1866]
Minecraft Version: 1.16.5

Description: 
I was playing with Mekanism when I noticed an item called "Configuration Card": it's a tool that lets the player copy and paste the GUI settings of various Mekanism blocks. 
Another time I was building a big storage room with signs on chests, and that's where I thought it would've been cool if something like that Card existed for signs. It turned out the only mod for Forge with such a tool, called Carbon Paper, is extremely outdated.
In addition to that, another item that works as a universal version of the Card could be handy in some situations with hard-to-configure machinery.
Since Cyclic already has all kinds of useful tools, I thought such items would fit well in the mod, so I decided to tell you in case you're looking for suggestions.

**Comment by Lothrazar** [comment]
the Settings data card is built to do this.  Can you try that out and see if it fits your needs? 
![sett](https://user-images.githubusercontent.com/621529/125130148-5bdf5f00-e0b5-11eb-84dc-a43b8a024118.png)

**Comment by Temenat** [comment]
> the Settings data card is built to do this. Can you try that out and see if it fits your needs?
> ![sett](https://user-images.githubusercontent.com/621529/125130148-5bdf5f00-e0b5-11eb-84dc-a43b8a024118.png)

After having downloaded the latest version of the mod, I think this issue I opened makes very little sense, as I noticed the Carbon Paper mod HAS ALREADY BEEN INCLUDED IN CYCLIC, along with a Settings Data Card that works on Cyclic machines just like the Configuration Card works on Mekanism machines and Redprint works on TE machines. That said, to answer your question, I don't know if it's doable in terms of code, but when I wrote the suggestion I was thinking about a UNIVERSAL version of the Configuration Card/Settings Data Card/Redprint, that could work on machinery from Industrial Foregoing, EnderIO and so on, so if you wish you can mark this as Enhancement and focus on making the Data Card more versatile. I'm still embarassed for the nonsensical suggestion and happy for the quick answer and the fact that Cyclic actually HAS Carbon Paper. If you don't want to enhance the Settings Data Card, the issue should be closed.

**Comment by Lothrazar** [comment]
the problem with making it work on other machines is that theres no standard agreed way of how machines store data.

For example if a Machine has some data that means the machine has been upgraded with an expensive item, then copying that setting would be a dupe.  Or it might copy the Fluid /energy/gas contents of a machine.  Things like that.  Not all data in a machine is 'free' anyway, so not just every mod, but every block from every mod would have to have possibly custom code in it.  

If you have other ideas in the future ill be around :)
