### ISSUE TITLE
Chisels and Bits designs wiped out after dumping into chest

### ISSUE THREAD

**Issue by rahangar** [PrinceOfAmber/Cyclic#187]
I was keeping my Chisels and Bits designs inside a "Sack of Storage".  When I dumped the content into a chest by left clicking on the chest with the sack, the items were inserted into the chest, BUT all the C&B designs merged together (all positive designs into one stack, negative designs into one stack, etc)... this caused me to lose all my designs :-(. 

I haven't tried it, but it might be a good idea for you to try testing it with blueprints from Super Circuit Maker mod.   I'm guessing blueprints will also merge into a stack... I'm too scared to try it.

**Comment by PrinceOfAmber** [comment]
What version of cyclic was installed?  This **should** have been fixed in 1.8.5 by this change : https://github.com/PrinceOfAmber/Cyclic/issues/161 

 PS thanks for reporting it

**Comment by rahangar** [comment]
It is Cyclic-1.10.2-1.8.2 - as part of hermitpack 1.4.0.

The description of #161 seems to match.  I'll upgrade and let you know if I see the problem again.

Thanks again for a great mod and your continued support.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting it.  I just tested it in hyperantix pack which has 1.8.13 and chiseled grass patterns seemed to keep their data. 

Let me know how it works after update

**Comment by rahangar** [comment]
I tried it with 1.8.13, and it works great.  Thanks again.
