### ISSUE TITLE
[Suggestion] Ability to rebalance the strength or duration/durability of charms and other trinkets from the mod

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#1870]
I'd like to request the ability to rebalance the strength of the effects from some of your charms and such. Stuff like the speed charm and flippers are rather very strong for craftable items while some other things would be more balanced if their shown durabilities would actually ticks down when they're protecting you from their respective damage types and stuff or would only block X AMOUNT of their damages before breaking.

Stuff like settings in the config to change the percentage of strength of those that use percentages and/or durability of the trinket and the amount of damage taken from each action of their protections.
Like say the crit bracelet ticking down when you crit, or windforce gauntlets ticking down whenever you swing and deal damage.

I suggest these limitations or changes because they're craftable and a number of them can be found in more permanent forms from other mods when cyclic is combined with them, which just makes cyclic outclass them rather strongly.

I have resulted to either rebalance their recipes or off their recipes in my pack barring a lack of easily turning off each feature like 1.12.2 had, but the ability to balance them to taste would be greatly appreciated for pack devs too.

As an aside or potential bug, if the charms are MEANT to be ticking down already when you do their actions or just in general while using them... they're not for a lot of the new ones which were added recently. That being for the versions of:

MC 1.16.5
Cyclic-1.16.5-1.3.1
Forge: 36.1.24

for example my speed charm is not ticking down while I'm having it enabled and running. it simply loses one durability when i turn it on from off, but then doesn't continue ticking off.

**Comment by Lothrazar** [comment]
im not sure if i want to depend on tinkers, but this is a really cool suggestion.  (and even without tinkers i could make multiple weaker versions of some of the items).  Right now the only way to balance them is the Durability damage they take, or the recipe.

  I was talking to some discord people about the Terraria charm system as well, how all the charms there start out really weak (like a 1-2% movement speed).

But then you can Merge them together and upgrade them in a huge crafting tree type thing. so yeah having one ability per charm and then having a multi tool. or combine two weak attack power charms together for a strong one, or upgrade them.

**Comment by Darkmega18** [comment]
> im not sure if i want to depend on tinkers

wait-wait. I never mentioned tinkers construct at all... :V. 

I basically just want a config for them so I can fiddle with the default power level of them, cause they're actually remarkably strong, but that charm combination thing actually sounds interesting in the case of these trinkets that can be crafted. So if thats what you want to consider, and maybe make them like a quarter of what they are now and then you combine them up to get full strength trinkets of how they are now, that could be quite good.

**Comment by Lothrazar** [comment]
oh sorry i mis read that, i dont know why i was thinking of tinkers construct thats my bad. i was thinking of something else i guess


For durability, i thought something like data packs or Craft Tweaker could change durability? Is that still possible in craft tweaker in 1.16?  

For power level yes i can add config values for many properties.  

"Stuff like settings in the config to change the percentage of strength of those that use percentages and/or durability of the trinket and the amount of damage taken from each action of their protections."

Yeah config values like this can totally be done.

Is there a list of items and properties specifically i can put in config? That would make it easier rather than me trying to remember them all. 

For example
item name - doesnt take durability and it should
item name - it gives 50% strength but its not in config
etc

**Comment by Darkmega18** [comment]
oh, I'll take a quick look. I had been testing them previously and a good number of the new items weren't ticking down when you do their actions.

**Comment by Darkmega18** [comment]
Heres a list:

**_is probably fine:_**
XP blocking ring.

**Does not tick down durability when doing their action but has durability meter**

steel rend bracelet -> taking a hit

Runic Signet -> while having potion effects.

windforce gauntlets -> when attacking

Crit ring -> when critting.

spider fang -> when poison procs

Alchemical Veil -> when blocks potion effects. Could use a blacklist for things it doesn't block?

Incomplete Phylactery -> when taking on a potion effect and amplifying it. (also, could use a config trigger to say if it also amps bad potions.)

XP ring -> Over time? or once a second when actually picking up XP?

cloak of invisible -> ticks semi inconsistently. But should continue to be over time. for added complexity: faster over time in bright light, but when in light at mob spawn level or less, it's slower? Maybe also disable for a short period when striking foes.

**weirdly loses durability when toggled on and off, but doesn't tick durability otherwise.**
Luck ring -> should tick over time?
_(btw how much luck are you giving!? this thing is making me one shot creepers with my bare hands cause of war dance making luck affect damage dealing and taking.)_

speed charm -> should tick when moving

**Does not seem to have durability or limitation at all**
Flippers
Climbing glove.

**Could use a durability modifier**
yes. :V (all of them could benefit from being rebalanceable. everyone has their own kind of balance really.)
Further, let setting a durability to something like -1 make it just endless. for those who want to break the video game. or turn them into relics or something via loots but disable recipes or whatever people want to do.
