### ISSUE TITLE
Server thread error on PlayerEvent.SaveToFile

### ISSUE THREAD

**Issue by CodeGordon** [PrinceOfAmber/Cyclic#1873]
Minecraft Version: 1.16.5

Forge Version: 36.1.32

Mod Version: 1.3.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Constant log entries on every `save-all` command: `[Server thread/ERROR] [com.lothrazar.cyclic.ModCyclic/]: Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}`

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/6836481/latest.log)

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/7526525/126072006-4b7c6695-ef09-4742-a66f-f24782ab5064.png)

**Comment by dualmacops** [comment]
Having this error in ATM6 1.7.1 modpack  (Cyclic-1.16.5-1.3.2) 
The error did not occur in ATM6 1.6.14      (Cyclic-1.16.5-1.2.11))

**Comment by CodeGordon** [comment]
The offending line of code. Stuff like this ought to be a debug level log entry, not an error.

https://github.com/Lothrazar/Cyclic/blob/d7e9e73618c1edb75a61c288ed121dc66f18aa6d/src/main/java/com/lothrazar/cyclic/event/PlayerDataEvents.java#L45
