### ISSUE TITLE
Server crash with inventory crafting

### ISSUE THREAD

**Issue by blockgoblin31** [PrinceOfAmber/Cyclic#1875]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Mod Version: Cyclic-1.12-1.20.11.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I had just gotten some wheat and wanted bread, so I opened my inventory to craft it, and pressed the inventory crafting grid button with wheat in my hand and the server crashed.

Log file link:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-1.12.2-0.2.6.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/18/21 7:24 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at net.minecraft.world.World.func_72907_a(World.java:3143)
	at com.tmtravlr.jaff.JAFFEventHandler.countAllFish(JAFFEventHandler.java:245)
	at com.tmtravlr.jaff.JAFFEventHandler.trySpawningFish(JAFFEventHandler.java:103)
	at com.tmtravlr.jaff.JAFFEventHandler.onWorldTick(JAFFEventHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_433_JAFFEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-74-generic
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412920336 bytes (393 MB) / 1156055040 bytes (1102 MB) up to 1771044864 bytes (1689 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1900M -Xms950M
	IntCache: cache: 0, tcache: 5, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                   | Signature                                |
	|:------ |:-------------------- |:----------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                            | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854      | forge.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | quark                | r1.6-179          | Quark-r1.6-179.jar                       | None                                     |
	| LCHIJA | autoreglib           | 1.3-32            | AutoRegLib-1.3-32.jar                    | None                                     |
	| LCHIJA | am                   | 1.0               | Avatar Armory Mod v1.1.3.jar             | None                                     |
	| LCHIJA | avatar_currency      | 1.0.0             | avatar-currency-of-the-4-nations-mod.jar | None                                     |
	| LCHIJA | gorecore             | 1.12.2-0.4.5      | avatarmod-1.6.0-alpha.14.jar             | None                                     |
	| LCHIJA | avatarmod            | 1.6.0-alpha.14    | avatarmod-1.6.0-alpha.14.jar             | None                                     |
	| LCHIJA | clumps               | 3.1.2             | Clumps-3.1.2.jar                         | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                 | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar         | None                                     |
	| LCHIJA | conarm               | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar               | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | cucumber             | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                | None                                     |
	| LCHIJA | cyclicmagic          | 1.20.11           | Cyclic-1.12.2-1.20.11.jar                | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | enhancedfarming      | 1.1.3             | Enhanced-Farming-1.12.2-1.1.3.jar        | None                                     |
	| LCHIJA | fastleafdecay        | v14               | FastLeafDecay-v14.jar                    | None                                     |
	| LCHIJA | forgelin             | 1.8.4             | Forgelin-1.8.4.jar                       | None                                     |
	| LCHIJA | futuremc             | 0.2.6             | future-mc-1.12.2-0.2.6.1.jar             | None                                     |
	| LCHIJA | jaff                 | 1.7_for_1.12      | JustAFewFish-1.7_for_1.12.jar            | None                                     |
	| LCHIJA | mysticalagriculture  | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar     | None                                     |
	| LCHIJA | mysticalagradditions | 1.3.2             | MysticalAgradditions-1.12.2-1.3.2.jar    | None                                     |
	| LCHIJA | theoneprobe          | 1.4.28            | theoneprobe-1.12-1.4.28.jar              | None                                     |
	| LCHIJA | betteranimalsplus    | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar       | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['blockgoblin31'/728, l='world', x=363.44, y=65.00, z=143.47]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Caused by JustAFewFish mod 

`at com.tmtravlr.jaff.JAFFEventHandler.countAllFish(JAFFEventHandler.java:245)
at com.tmtravlr.jaff.JAFFEventHandler.trySpawningFish(JAFFEventHandler.java:103)
at com.tmtravlr.jaff.JAFFEventHandler.onWorldTick(JAFFEventHandler.java:73)`
