### ISSUE TITLE
Regularly recurring error in log pertaining to SaveToFile()

### ISSUE THREAD

**Issue by Teibidh** [PrinceOfAmber/Cyclic#1876]
Minecraft Version: 1.16.5

Forge Version: 36.1.32

Mod Version: 1.3.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): While there is no noticeable in-game impact because I have not used any of Cyclic's storage items as of yet I get the following error every few minutes in my server log as long as a player is connected.

[Server thread/ERROR] [co.lo.cy.ModCyclic/]: Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

Log file link:

Video/images/gifs (direct upload or link):

**Comment by dualmacops** [comment]
Having this error in ATM6 1.7.1 modpack  (Cyclic-1.16.5-1.3.2) 
The error did not occur in ATM6 1.6.14      (Cyclic-1.16.5-1.2.11))

**Comment by starryfae** [comment]
Also experiencing this issue on a custom 1.16.5 modpack on Forge 36.1.61, both singleplayer and sevrer

**Comment by MaxSaleh** [comment]
Me too.....
