### ISSUE TITLE
Disenchanter not working - has power etc. What's wrong?

### ISSUE THREAD

**Issue by Immaculala** [PrinceOfAmber/Cyclic#1885]
Minecraft Version: 1.16.5

Forge Version: 1.16.5 Forge 36.1.10

Mod Version: Cyclic-1.16.5-1.3.4

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
The Disenchanter has Power, Redstone mode is set to Always On, but it doesn't process.
I have tried with Needs Redstone and added both a Lever and a Redstone block - neither of those options worked either. 
I have tried with a standard enchanted item as seen in attached video but it doesn't work with any enchantments.
I have tried with just 1 book and a stack of books.

Log file link:

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/26187212/127655262-7ecf5344-635f-4d4e-bc6f-7b27383e2509.mp4

**Comment by DarkiTsuna** [comment]
Hi, I had the same Problem as you did, my Solution was to pump Liquid EXP into the Disenchanter.
It seems with the Last Update they added this.

Hope i could help you!

**Comment by Immaculala** [comment]
> Hi, I had the same Problem as you did, my Solution was to pump Liquid EXP into the Disenchanter.
> It seems with the Last Update they added this.
> 
> Hope i could help you!

Thank you DarkiTsuna - that worked :)

**Comment by Morabert** [comment]
Hey, could you guys make this a little less complicated? Doing anything thing with mod has more tedious steps than the prep-kitchen in a Michelin-Rated French Restaurant.

**Comment by HalcyonSeas73** [comment]
You can turn off the 'use liquid exp' option off in config. Not sure why it's difficult. Cyclic, _by design_, has a lot of random stuff in it.
