### ISSUE TITLE
[1.16.5] Fishing Net description not accurate

### ISSUE THREAD

**Issue by faizjamil** [PrinceOfAmber/Cyclic#1887]
Minecraft Version:  1.6.5

Forge Version: 36.2.0

Mod Version:  1.3.4

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

After figuring out why I couldn't get the Fishing Net to work, a friend suggested I try placing it in the water, the first layer from above. That worked, can the description of the fishing net be updated to reflect this? It currently states "Fishes in nearby water if given fishing rod"

**Comment by faizjamil** [comment]
Actually, I found where I need to change the text, I'll change it and submit a PR.

**Comment by Lothrazar** [comment]
Yeah for sure. what if the tooltip was something like 

"Uses fishing rods while underwater"

**Comment by faizjamil** [comment]
I was thinking of just changing one or two words in the guide, but I'm all for changing the tooltip as well

**Comment by faizjamil** [comment]
Ok, where is the JAR I'm supposed to test with after the build is done?
