### ISSUE TITLE
Disenchanter: what am I missing?

### ISSUE THREAD

**Issue by GINGMIRE** [PrinceOfAmber/Cyclic#1890]
Minecraft Version: 1.16.5

Forge Version: 36.2.0

Mod Version: Cyclic-1.16.5-1.3.4.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I am trying to setup and use a disenchanter to take enchantments off items such as an iron helmet with protection and put them onto books. I have the table connected to power and it shows it is powered but there is a second bar that shows 0. We haven't been able to figure out what it needs and any youtube videos I've found don't have this extra bar so we aren't sure what to do. This is our request for help, please and thank you. :)

Log file link:

Video/images/gifs (direct upload or link): 

![2021-08-02_16 40 04](https://user-images.githubusercontent.com/88350345/127927406-0ab51e45-6058-4a6d-88e3-63b1a0ea7988.png)

![2021-08-02_16 42 14](https://user-images.githubusercontent.com/88350345/127927670-f4083d54-8e79-4277-a472-f2bf9637a85b.png)

![2021-08-02_16 42 17](https://user-images.githubusercontent.com/88350345/127927696-f1dd2409-bf00-4937-abd6-21f07c204497.png)

![2021-08-02_16 43 02](https://user-images.githubusercontent.com/88350345/127927723-8c31cfe3-cf8f-4603-b93d-5371cbb58845.png)

![2021-08-02_16 43 10](https://user-images.githubusercontent.com/88350345/127927751-d38ea05c-ef4f-408b-a24c-e5acb0f16497.png)

**Comment by tlsctf2** [comment]
(not Lothrazar but) to my knowledge (aka I'm trying to remember this from several months ago), that shows remaining time on an operation; it doesn't actually do anything until you get something to start disenchanting. I may be wrong about that- again, it's been a while- but I'm assuming this is it, since the 1.15.4 crystallization chamber has the same thing. it's probably a good idea to see if the device works as-is for the time being, since I believe nothing is wrong here

**Comment by lynnpye** [comment]
I'm in the same situation. I have full power, I can place a simple enchanted item (iron chestplate with protection 1) in, along with a book, and I can click to turn on or off the redstone activation switch... and nothing happens, not even anything into the log file. I see in the config a reference to an xp cost per book split out, defaulting to 100 xp, so I figured perhaps it needs fluid xp, but then I'm also having a problem with the experience pylon where there is no option to drain my personal xp into that either, so I'm truly at a loss.

EDIT: Nevermind, I see now that to push xp into the pylon, you crouch on top of it. Now to figure out how to pump it into the disenchanter.

**Comment by GINGMIRE** [comment]
We figured it out. It has to have XP being pumped into it as well as power. We set up an XP Draining Singularity Tank  from _Mob Grinding Utils_ and mechanical pipes from _Mekanism_. Stand on the tank and configure the pipe to pull the xp into the Disenchanter. Hard to hide the pipes going in since the block isn't one whole block tall but we got it to work.

Thank you to those who answered!

![2021-08-02_19 34 16](https://user-images.githubusercontent.com/88350345/127939860-5ee45353-156f-4a61-8c90-e41a77ddca8b.png)
![2021-08-02_19 34 26](https://user-images.githubusercontent.com/88350345/127939867-a69bc541-8499-440d-9a9f-7d9921d66ac5.png)

**Comment by lynnpye** [comment]
![2021-08-02_19 50 29](https://user-images.githubusercontent.com/1483771/127940900-50719640-2dd3-4141-9812-209b3e8012a2.png)
To follow up, if you want to use pure Cyclic items... you can connect an Experience Pylon to the Disenchanter with a length of cable. Then take a Wrench and right click near the end of the cable attached to the pylon. It will then have a white square that appears on that end and any xp in the pylon should begin flowing toward the Disenchanter. As mentioned above, squatting on top of the pylon dumps your personal xp into the pylon.
