### ISSUE TITLE
Game breaking when placing diamond spikes

### ISSUE THREAD

**Issue by Eli-Eli-Oh** [PrinceOfAmber/Cyclic#1894]
Minecraft Version: 1.16.5

Forge Version: 36.1.62

Mod Version: 1.3.5

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): I was messing around in a creative world and I placed down a diamond spike, then it crashed and now whenever I play on the world it immediately crashes.

Log file link: https://pastebin.com/V57FNJ0p

**Comment by tazzy989** [comment]
I would just like to say I just experienced the same issue. I don't know how to pull and show logs for you, but in my single-player world I went to place Diamond spikes and the world crashed. It also crashed when attempting to reload. Thankfully I had a backup from earlier today. :)
