### ISSUE TITLE
Experience Boost enchantment survival gacha rate

### ISSUE THREAD

**Issue by Gideon9212** [PrinceOfAmber/Cyclic#1899]
Minecraft Version:  1.16.5

Forge Version: 36.1.16

Mod Version: 1.16.5-1.2.7

Single Player or Server: Server so far. Haven't checked single.

Mod pack used: FTB Endeavour version 1.4.0

Haven't issues on the enchantment Experience Boost as in, haven't been able to get it at all on any weapon or tool as can't seem to get lucky to get it on the enchantment table. Tested over 100 swords, pickaxes, and about 50 hoes and no luck on it getting on any of them, not even level 1 version of them. Had a friend try as well with no luck. Drop rate is either super rare or just being blocked by some other mod in the mod pack. Checked config to make sure it's enabled on the cyclic.toml and it is. I'm I just having bad luck on it, is it bug, or is it disabled somehow due to mod interfering? 

Tested with normal enchantment table and running a automatic setup with the mod Industrial Foregoing with their Enchantment Factory.

**Comment by Lothrazar** [comment]
Thanks for your patience on this.

I think i had the rarity to high. accidentally multiplied by 20.

For example: gold is the highest where enchantability of the item is up to 20.

XP boost was doing

11 + level * 20

So even at level 1 thats 33. turning that down/off now

**Comment by Lothrazar** [comment]
yep with new changes i got it after about 10 pickaxes.
![confirmed](https://user-images.githubusercontent.com/621529/137855698-aa0eac1f-aecb-49ac-8111-848f517ae29a.png)

**Comment by Gideon9212** [comment]
Thanks for getting back to me on this. I see from the pull as well that there's a change log of other enchantments too. Feel free to close this issue soon as this is merged with master.

**Comment by nguyendatlubo-rgb** [comment]
what mod

**Comment by nguyendatlubo-rgb** [comment]
experience boost what mod
