### ISSUE TITLE
Request to add config to disable cyclic guide book to 1.12.2+

### ISSUE THREAD

**Issue by tyon2006** [PrinceOfAmber/Cyclic#1902]
Minecraft Version: 1.12.2

Describe problem (what you were doing; what happened; what should have happened):

Hey! I'm just looking to request a change to all versions of Cyclic that would allow for the disable of the guidebook. To elaborate, I like the guidebook, but I've modded cyclic so much in my pack that the guidebook doesn't really provide value anymore and I've had to include another mod just to scrub away the item.

**Comment by Lothrazar** [comment]
there should be a flag for this already in Guide-API.cfg file, with false meaning dont give to player

```   

 spawn {
        #  [default: true]
        B:"cyclicmagic:guide"=true
        B:"deepmoblearning:deepguide"=false
    }```

**Comment by Lothrazar** [comment]
![Guide-api cfg](https://user-images.githubusercontent.com/621529/160303107-23489ed7-46e5-4698-8f5c-e91c397bfbc4.png)
