### ISSUE TITLE
Inventory Upgrade: From Launcher to Launcher

### ISSUE THREAD

**Issue by GreastTT2** [PrinceOfAmber/Cyclic#1904]
Minecraft Version: 1.12.2

Forge Version: forge-14.23.5.2855

Mod Version: Cyclic-1.12.2-1.20.9

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

So, I change my all mod pack to the new launcher, so i needed to transfer all my items. But as the strange things happen, my second inventory in cyclic has been EMPTY. After some time research I ask for Lothrazar in discord with  this message: "hi, what is the folder for Inventory Upgrade. When I transfer all my mods to another launcher and then logged into world, my all second inventory empty". He replied with: "Yes theres a playername . Dat file in with the world playerdata . Or .invo . Can be restored if moved safely," which I did in this following folder : 00000000-0000-0000-0000-000000000000.dat . Which eventually didn't work. So I transfer ALL the saves from my old launcher folder to the new one, but still no respond to that. I think it's not playerdata.

What I use to find playerdata:  AppData\Roaming\.minecraft\versions\Hexxit\saves\Hexxit\playerdata
![image](https://user-images.githubusercontent.com/63648841/130117071-0b134fec-f6a3-4b79-b9a3-25d8617afab8.png)

Log file link: N/A

Video/images/gifs (direct upload or link): 
![unknown](https://user-images.githubusercontent.com/63648841/130116974-feb47b4e-cc66-4b99-b4b0-74f958efd7af.png)

**Comment by Lothrazar** [comment]
hmm , thats weird. i wonder if maybe the 0000 means the player was in offline mode vs LAN or something?  the cyclicinvo is the right one. and the filename is the player id

**Comment by Lothrazar** [comment]
older versions used to use dat file, and a different older version had abug where single player used 000 000 instead of user id.  there might be things to do as said before with renaming/copying files, but this issue is really old now, and just /give i guess to restore for now. seems to be only an issue when sometimes updating from old versions of the mod
