### ISSUE TITLE
Is avaritia not meant to work with the uncrafting grinder?

### ISSUE THREAD

**Issue by jasonakamist** [PrinceOfAmber/Cyclic#1905]
Minecraft Version: **1.12.2**

Forge Version: **1.12.2**

Mod Version: **1.12.2**

Single Player or Server: **Single Player**

Describe problem (what you were doing; what happened; what should have happened):
**I was trying to uncraft the longbow of the heavens and it wouldn't work, I even tried to look in the config file to see if it was blacklisted and I saw nothing. If I could get some help that would be appreciated. :)**

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
as long as the items crafting in the vanilla crafting table, yeah it should be reversable.  Also the damage taken on the item or any NBT data  /enchantments could block the un-craft (for example , enchanted swords or damaged armor)  Sounds like you already checked config file. screenshot maybe?

**Comment by bloodscon** [comment]
I'm sure avaritia uses it's own crafting table if it does then that's the problem uncrafting grinding only works with the normal crafting grid size (3x3)

**Comment by PoolloverNathan** [comment]
Avaritia has its own 9x9 crafting table, which is used to make its items. Since the Uncrafting Grinder uncrafts Crafting Table items, it will not uncraft Avaritia items.

**Comment by Lothrazar** [comment]
yeah someone would have to make a new mod or their own block to uncraft 9x9 s

**Comment by Devilmxn2** [comment]
isnt there any script? like ssundee did on insanecraft.
