### ISSUE TITLE
uncrating grinder

### ISSUE THREAD

**Issue by biowarsgaming** [PrinceOfAmber/Cyclic#1907]
Minecraft Version: 1.12.2
Forge Version: latest

Mod Version: 

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

im trying to figure out how to get the infinity items from avarita to uncraft in the uncrafting grinder

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
we are discussing the same thing in https://github.com/Lothrazar/Cyclic/issues/1905 to figure it out , could be config or maybe item enchantments? check other thread
