### ISSUE TITLE
Uncrafting grinder

### ISSUE THREAD

**Issue by bendyfan101010** [PrinceOfAmber/Cyclic#1908]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Mod Version: 1.20.11

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
When i use the uncrafting grinder its like in reverse or something it days recipe found for air and when i put in a nugget like 9 diamonds  nuggets it crafts a diamond i dont know what i did or is it the mod 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
it found air? is it un crafting air to nuggets over and over?

**Comment by Lothrazar** [comment]
stale issue.possibly bad recipe or item. works with iron/gold nuggets as intended and other modded items just testing now, everything seems working as intended
