### ISSUE TITLE
Automatic Fishing Net deletes inventory when broken

### ISSUE THREAD

**Issue by Danklor** [PrinceOfAmber/Cyclic#191]
Tested with Cyclic 1.8.14 and Forge 12.18.2.2179.

When an automatic fishing net with fish and/or fishing rod is broken only the fishing net block is dropped.  The fishing rod and and fish are deleted.

I would expect the fish and fishing rod to drop as items.

Of course the workaround is to take out all the items before breaking the net, but some of us are forgetful about these things.

**Comment by PrinceOfAmber** [comment]
Fixed in 1.8.15 https://minecraft.curseforge.com/projects/cyclic/files/2353553
