### ISSUE TITLE
3 issues in 1.4.0 for MC 1.16.5

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [PrinceOfAmber/Cyclic#1914]
Minecraft Version: 16.16.5

Forge Version: 36.2.4

Mod Version: 1.4.0

Single Player or Server:Single Player

Describe problem (what you were doing; what happened; what should have happened):

Issue 1: Missing localization on Patchouli guide book
```
item.cyclic.gem.guide
enchantment.cyclic.multishot.guide
enchantment.cyclic.excavate.guide
```
By the way, cyclic's multishot enchantment requires rename, the name is conflicted with vanilla Crossbow‘s Multishot enchantment.

Issue 2: Quickshot bow on off hand makes the action by holding the right-click faster.
When holding the bow with Quickshot enchantment on my off hand, the action by holding the right-click will be faster.
The actions include eating food, drinking potions...
GIF: https://imgtu.com/i/4Vpjpt

Issue 3: Copy block bug about item shelf.
- what you were doing
-- Put a block "A" into the item shelf. After a distance of at least 1 block, then put a block "B" into the same line of this item shelf.
- what happened
-- Block  "A" is gotten and block  "B"  is placed in front of the item shelf. One more block.
- what should have happened
-- Block  "A" is gotten and block  "B" is put into the item shelf,  "B" should not be placed.

GIF: https://imgtu.com/i/4VCHJA

Log file link:no crash

**Comment by Lothrazar** [comment]
Fixed issue 1 and to. also ill rename cyclic:multishot Multi-Bow in english lang file so its still easy to find and its more clear.  looking into 3`
