### ISSUE TITLE
Shape builder and Empty card crash

### ISSUE THREAD

**Issue by MrCandyman101** [PrinceOfAmber/Cyclic#1915]
Minecraft Version: 1.16.5

Forge Version:  1.16.5-36.2.2

Mod Version: 1.16.5-1.3.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I was messing around with the shape builder and shape computer. Gave the shape builder an empty card and crashed on the spot. The machine did not have power. 

Edit: Issue did not fix itself upon the crash. Now stuck in a crash loop until the machine or the item is destroyed from my vicinity by the server.

Log file link: https://pastebin.com/wF81geGK

**Comment by Lothrazar** [comment]
Fix for this is out in v1.3.8 or higher
