### ISSUE TITLE
Localization missing and bug on Patchouli guide book

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [PrinceOfAmber/Cyclic#1917]
Minecraft Version: 1.16.5
Forge Version: 36.2.4
Mod Version: 1.4.1
Single Player or Server:Single Player

Describe problem (what you were doing; what happened; what should have happened):
Issue 1: Missing localization on Patchouli guide book
```
enchantment.cyclic.experience_boost.guide(only en_us)
block.structure.guide
```
Issue 2: Experience Pylon page's `BAD LINK: misc/experience_food` on "Experience Confection"

Change `$(l:misc/experience_food)` to `$(l:consume/experience_food)` is OK.

I'll update Chinese translation after closing this issue, then I'll create a PR.

**Comment by Lothrazar** [comment]
Fixed the link.

Adding

    "enchantment.cyclic.experience_boost.guide": "Whenever mining a block that drops experience orbs, it increases by a random number based on enchant level.  Whenever a Living creature dies and drops experience, if it was killed by the attacking player more exp is dropped randomly based on level",

**Comment by mc-kaishixiaxue** [comment]
The `block.structure.guide` key has not been added in en_us. Without it, I can't translate.
