### ISSUE TITLE
ATM6 - Sky Solidification Chamber 

### ISSUE THREAD

**Issue by MorganaLaLuna** [PrinceOfAmber/Cyclic#1918]
Minecraft Version: 
1.16.5

Forge Version: 
36.2.2

Mod Version: 
Cyclic-1.16.5-1.4.1  (ATM6 Sky 1.1.8)

EDIT: I forgot to mention, ATM6 Sky 1.1.8 doesn't use this version of cyclic, I manually updated the mod because I was getting a "failure to sync registry data from server" error, which was being caused by cyclic (according to people in the ATM6 discord). That said, the recipe didn't work before or after manually updating

Single Player or Server:
Both

Describe problem (what you were doing; what happened; what should have happened):

I was attempting to create magma cream with the solidification chamber.
The recipe did not work, nor show any sign of working.
At the cost of 100mb of Magma and 3 Slimeballs, 6 Magma Cream should be produced

Log file link:
(I don't know what this section is, sorry)

Video/images/gifs (direct upload or link): 

The Magma Cream recipe, as shown by JEI:
![2021-09-21_12 53 59](https://user-images.githubusercontent.com/64173894/134104901-1cb679f6-a30e-4b5d-ad4e-c4ffbfcc7027.png)

The recipe in use:
![2021-09-21_12 53 48](https://user-images.githubusercontent.com/64173894/134104971-5a20697d-757b-4b89-b1a2-caf799a5b809.png)

To replicate this, just play any version of ATM6 - To the Sky dating from March 2021 to now, and attempt to make this recipe. It does not work.

I've brought up this issue on the ATM reddit and discord server, in both places the issue was mostly brushed off with "Update Cyclic" or "I dunno what causes it to not work". And I did update Cyclic each time and the recipe still didn't work.

**Comment by Lothrazar** [comment]
im just looking at this now. if i download cyclic without a modpack and nothing else it seems to work, but also i did download modpack and i did get it to be broken in the pack in my world.. 

 made changes to use forge:slimeballs data tag and ill add recipe to just use single item.  also i think its not resetting the 0 timer back when recipe is invalid. it should just go if it has fluid and power and items
