### ISSUE TITLE
Feature request - option for Cyclic machines to require energy

### ISSUE THREAD

**Issue by Danklor** [PrinceOfAmber/Cyclic#192]
Cyclic machines do valuable work saving the player much time.  However all of this work is now done for free without energy.  It may be more "accurate" to require some form of energy to do all this work.  When you get a chance, please add an option to use one of the various energy APIs available.

Thanks!

**Comment by PrinceOfAmber** [comment]
Ive been considering this for a while.  The things stopping me are

Balance: what to make everything cost
Which to use? Tesla? RF? forge? something else
Some of the cyclic machines are so simple they dont need a cost (block breaker)
how does it affect speed? Would uncrafter speed up with more power?  I only made the uncrafting grinder slow as a way to gate/balance it.

I think at the very least they should take burnable fuel like coal/wood.  But it might not get in until after 1.11 update, as people have been requesting that too.

**Comment by PrinceOfAmber** [comment]
After much back and forth thinking, and after porting it to 1.11.2, ive decided that energy systems dont suit this mod, i dont feel like its the right fit. You may have forgot about this ticket, but  Ill still try to put some of my thoughts here for anyone else who is wondering this too.  (forgive the typos)

- I dont feel anything in Cyclic is powerful enough to need that extra restriction. There is already the cost of building the thing, and then either waiting for it to work (for a machine), or it costs durability if its an item) .  So the cost is in time or resources or both.  The most 'expesnive' things would be uncrafting, placing blocks, or harvesting crops.  but those things arent even that crazy compared to what other mods can do..  There are  mods that create blocks and resources out of the void, or create whole dimensions, or spawn tons of mobs for farming; things like that I understand gating behind a power system, at least a little bit.

- Other mods sometimes have better machines than cyclic but they cost power, such as the Ender IO harvester.  well thats fine, cyclic machines are an early game option.

- I make and play lots of vanilla like modpacks that dont have any RF, and i feel like this fits in those pretty decently. at least half of it if you want to config tweak stuff.

- Whats the difference between a machine that runs for free.. vs a machine that costs power, and then you generate power for free over time (solar/wind/burning biofuel that you generate infinite amounts of).  Answer: well not much difference in the end you just have to run a cable.  

- Even without those eco friendlly ways, there has been many times where i build a giant reactor from one of a handful of mods, and a bunch of power storage, and never run out. I get it, power systems are interesting and immersive, and i enjoy playing with them too.  But its not really the right fit here.

If anything, i might add a fuel cost to a few things, like an upgraded uncrafter that works super fast but burns fuel, but the fuel will be coal or something. but even that is way down the road.

❤️  for the feedback

**Comment by PrinceOfAmber** [comment]
Reopening this since im considering it again.  Might not be RF but might be some other fuel / liquid / lava / something
