### ISSUE TITLE
[Incompatibility?] Solid Eyes of Ender can't track Better Stronghold's portal rooms.

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#1920]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.4

**Mod Version:** 1.4.1

**Single Player or Server:** Both

**Describe problem (what you were doing; what happened; what should have happened):**
The problem FEELS like it is a compatibility issue with better strongholds.

Better strongholds replaces the default stronghold with much better and detailed ones. However this has rendered the solid eye of ender inert as it won't track the location of the better stronghold strongholds as far as I can tell requiring us to use the default eyes of ender.

Default eyes of ender continue to work.

**If I'm correct:**
 install better strongholds, install cyclic. Attempt to throw Solid eye. Cause no stronghold portal exists and it's actually the better strongholds stronghold which is now in the world no eye is thrown, I guess can't it can't find anything.

**Log file link:**
It's not a logged or crashing issue. Just a physical issue.

**Comment by faizjamil** [comment]
Been able to replicate issue, specifically it's [YUNG's Better Strongholds](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds) that seems to be causing problems. Encountered this issue on ATM6, and with a custom profile with just Cyclic YUNG's Better Strongholds, and JEI installed.

**Comment by Darkmega18** [comment]
noice. so I'm not crazy.

**Comment by TerZenn** [comment]
What is the current status on this bug being fixed? I'm playing on a server with some friends using ATM 6 version 1.8.15 with cyclic version 1.5.11.

**Comment by Lothrazar** [comment]
a 1.16.5 fix is coming soon.

Used ther structure id 
`"betterstrongholds:stronghold"`
