### ISSUE TITLE
3 bugs in 1.16.5-1.4.2 [multi enchant, prospector, melt jei]

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [PrinceOfAmber/Cyclic#1924]
Minecraft Version: 1.16.5

Forge Version: 36.2.6

Mod Version: 1.4.2

Single Player or Server:Single Player

Describe problem (what you were doing; what happened; what should have happened):
Bug 1: Bow's MultiBow enchantment can pick up additional arrows that have already been shot. Vanilla crossbow's MultiShot is not.
1. Enchany MultiBow on a bow, shoot an arrow on survival mode and pick up the arrows on the ground.
2. The additional arrows that have already been shot can be picked up.

Bug 2: Ore Prospetor cannot be used to detect ores when it's in the left hand.
1. Take the Ore Prospetor in the left hand and right click an ore block;
2. The ore block do not show colorful borders, they should be shown, right hand is no problem.

Bug 3: Melting Chamber and Solidification Chamber's JEI interface cannot be shown when player entered the single player save in the second time and more times.
1. Run MC and enter a single player save, then right click the Melting Chamber in JEI.
2. Everything is normal, quit current save and enter again;
3. Right click the Melting Chamber in JEI, I found the JEI interface cannot be shown.

**Comment by Lothrazar** [comment]
1 -  yep arrows should be tagged so they cant be picked up i can add that
 ill upgrade ore prospect to work in offhand

For the JEI info tab issue, im testing in JEI-1.16.5:7.7.1.121 , in this version it always shows both tabs when i reload the world several times  . so this seems to work fine in latest jei version for me? 

![bothh](https://user-images.githubusercontent.com/621529/135888814-afa54cf7-a420-490f-b833-a4448fb2fccf.png)

**Comment by mc-kaishixiaxue** [comment]
For bug 3, it was successfully reproduced when only Cyclic and JEI were installed. The Java version is 16.0.2.

**Comment by Lothrazar** [comment]
2 and 3 i think are resolved, i need to test  1 again , note to self

"
    Enchany MultiBow on a bow, shoot an arrow on survival mode and pick up the arrows on the ground.
    The additional arrows that have already been shot can be picked up.
"
