### ISSUE TITLE
Got an Cyclic issue where i cant produce Crystallized obsidian

### ISSUE THREAD

**Issue by Hansider** [PrinceOfAmber/Cyclic#1925]
Minecraft Version: 1.16.5

Forge Version: 36.2.6

Mod Version: 

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
The problem is i dont know why i cant craft the Crystallized Obsidian watched vids how to but it still wont work
got slime got the amber the obsidian and the fruit but it wont work also got power but it just wont work

Log file link:

Video/images/gifs (direct upload or link): 

https://gyazo.com/c4d2e7b33f103d2f98eb49fffeaeb726

**Comment by Lothrazar** [comment]
This issue should be fixed nowif you update to the latest 1.5.2+ mod version and break/replace the block.  I fixed issue previously where recipe would get stuck

**Comment by Lothrazar** [comment]
Also the recipe was not shapeless in old versions it is shapeless now.
![shapeless](https://user-images.githubusercontent.com/621529/137854223-a10d1f88-9dec-422a-bd2a-f892083fae9b.png)

Wait, there is no recipe that takes both obsidian and emerald i think you have that mixed up. theres two alternate recipes
