### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ZEkA10000** [PrinceOfAmber/Cyclic#1926]
Minecraft Version: 1.16.5

Forge Version: 36.2.4

Mod Version: 1.2.7.1

Single Player or Server: Single Player

I playing on the Russian language but mod still in the English. 
In the mod file have Russian translate BUT with wrong ID of items. 

For example:
RU: 
"enchantment.venom"
EN:
"enchantment.cyclic.venom"

Can you fix translation file?

**Comment by Lothrazar** [comment]
yep should be good in newest version https://github.com/Lothrazar/Cyclic/blob/e33667e80c4a72ef2a4a9337369e086ff3dec0b0/src/main/resources/assets/cyclic/lang/ru_ru.json#L448
