### ISSUE TITLE
Error with recipes

### ISSUE THREAD

**Issue by aburone** [PrinceOfAmber/Cyclic#1929]
Minecraft Version: 1.16.5

Forge Version: 36.2.4

Mod Version: Cyclic-1.16.5-1.4.2.jar

Single Player or Server:single

Errors on log

https://hastebin.com/ifobuhigax.properties

**Comment by Lothrazar** [comment]
why is the hastebin empty

**Comment by Lothrazar** [comment]
![hastebinnn](https://user-images.githubusercontent.com/621529/137253480-d8f48cb3-29e3-4db3-b303-d8509b072fd2.png)

**Comment by aburone** [comment]
> 
> 
> why is the hastebin empty

Oh, shit. It didn't save

**Comment by aburone** [comment]
Here, sorry about that
https://pastebin.pl/view/22691358

**Comment by Lothrazar** [comment]
Oh yeah fixed this in latest versions. didnt affect anything, but errors showed sometimes for removed recipes/blocks
