### ISSUE TITLE
Phantom Scaffolding blocks

### ISSUE THREAD

**Issue by Danklor** [PrinceOfAmber/Cyclic#193]
Tested with Cyclic 1.8.14 and Forge 12.18.2.2179.

When building up with scaffolding blocks by looking straight down and holding space and RMB I often (about 20% of the time) get a tower of "phantom" scaffolding blocks adjacent to the one I am actually building.  This either occurs for every block in the scaffolding tower or for none of them.  The "phantom" scaffolding will instantly disappear if punched without dropping a duplicate block.  The "phantom" blocks will also disappear if I walk away far enough to unload the chunk and then walk back or simply exit the world and re-log.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this.  Ill try to fix it, but its possible that this is just the vanilla game (digging down into a pillar of sand with efficiency V shovel).

**Comment by PrinceOfAmber** [comment]
In single player for me this rarely happens. on servers it happens about the same as it happens with vanilla blocks as i said above, nothing i can see in my codes affecting this.  just a bug in vanilla https://bugs.mojang.com/browse/MC-90964
