### ISSUE TITLE
Fluid Hopper Deletes Water Logged Blocks

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1931]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.3

Single Player or Server: SP and SMP

Describe problem (what you were doing; what happened; what should have happened):

This is the same problem we encountered when altering the behavior of the fluid pipes. Looks like that same fix should apply to the fluid hopper, too.

Thanks!

https://github.com/DarkPacks/SkyFactory-One/issues/32

**Comment by Lothrazar** [comment]
Fix will be in 1.16.5 - 1.5.4
