### ISSUE TITLE
Duplication bug with durability based recipes using the Uncrafting Grinder

### ISSUE THREAD

**Issue by JohnGoten** [PrinceOfAmber/Cyclic#1932]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.16.5-1.5.3

Single Player or Server: Single Player (shouldn't matter)

Describe problem (what you were doing; what happened; what should have happened):

Using the Uncrafting Grinder it is possible infinitely duplicate items if the recipe consisted of an item which would lose durability upon crafting.
I am playing SkyFactory One 1.0.1 with forcecraft being the example in the attached gif down below yet the bug still applies to any mod that adds what I just mentioned.

It would be very helpful to have the option to block entire mods' recipes from being accepted alongside the already available recipe IDs as modpack developers will otherwise have to configure every. single. item. that could potentially lead to duplicates.

Video/images/gifs (direct upload or link): 

![BuAykD2juC](https://user-images.githubusercontent.com/92606827/137551998-43ca53a3-7f48-4a8d-a954-806285be4156.gif)

**Comment by Lothrazar** [comment]
you can ignore many items and recipes on the cyclic.toml config , for example

https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/cyclic.toml#L87

**Comment by Lothrazar** [comment]
config also needs more default values and stuff so thanks for reporting
