### ISSUE TITLE
Sack of Holding corrupts one lalf of a double chest when placed back (Just visual)

### ISSUE THREAD

**Issue by Radagast** [PrinceOfAmber/Cyclic#1933]
Minecraft Version: - 1.16.5

Forge Version: - 36.2.8

Mod Version: - Cyclic-1.16.5-1.5.3

Single Player or Server: - Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Using a Sack of Holding to move a double oak chest results in a visual bug when the chest is placed back down.

Log file link: - [Zerobin](https://zerobin.net/?4039391ac60e42a9#te/wDiUtCRp2H4lj+dItlpiVJ+zH/FDUI7k2rbScr4Q=)

Video/images/gifs (direct upload or link): 
Image [here](https://imgur.com/HjCJKL1)

**Comment by Lothrazar** [comment]
yes, this is correct. you will need two bags for the two chest blocks that make up the doublechest

**Comment by Lothrazar** [comment]
Aha. yeah looks like the sack remembers if the chest was "opening facing north but connected on the left"

So then if you pick up a double chest and place them facing differently than they were, it tries to connect to the nothing and doesnt "refresh"

GIF i got of it captured 

 https://i.imgur.com/EiMClBS.gif

**Comment by Lothrazar** [comment]
Fixes itself after a block update like putting dirt nearby

**Comment by Radagast** [comment]
It also seems to matter which half of a pair of chests is picked up first and placed down first. If I get the order correct there's no problem but if I get the left and right sides mixed up it has the 'glitch'.

**Comment by Lothrazar** [comment]
note to self, cause a block update or call 'update post placement' could fix
