### ISSUE TITLE
[Bug]: Duplication of Item Pipes

### ISSUE THREAD

**Issue by Shaahoo** [PrinceOfAmber/Cyclic#1935]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: Cyclic-1.16.5-1.5.3

Single Player or Server: Single Player

Describe problem:
Playing SkyFactory One Mod Pack;
If you stand on the block the pipe is attached to and have a halfblock/stairs above you, you can dupe the pipe by changing its configuration. I have attached a video below.

Video: 
https://www.youtube.com/watch?v=pIMCAKIbBeg

**Comment by Lothrazar** [comment]
cause:

Cyclic pipes have a feature where if you crouch-use a wrench on them, you harvest a wrench.

problem:
when harvesting the wrench, it failed to end the event so it also tried to rotate the pipe >< . so if you are crouching due to slabs above your head , it was doing both things at once
