### ISSUE TITLE
Possible Bug: Item Pipes stop extracting

### ISSUE THREAD

**Issue by sindacrof** [PrinceOfAmber/Cyclic#1936]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: Cyclic-1.16.5-1.5.2

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened): The Cyclic Item Pipes stop extracting items from a chest (vanilla chest / crate) when the next item in the chest cannot be pushed. For example, if I am extracting items into a drawer controller from a chest, and there is no corresponding drawer for an item, the pipe will stop pulling anything from the chest rather then just skip that item - which I believe is what normally happens. This causes the chest to get backed-up. One thing I did notice, that I'm not sure is a normal function of any type of item pipes is that the Cyclic pipe seems to rearrange the chest every time it pulls an item, and pulls from the first slot, rather then iterating through the different slots.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Sounds like it works as intended

Unlike some other pipe mods theres no over-arching "smart pipe network" that predicts where an item is needed and teleports it there.  Each pipe block is basically a hopper that can face from 0-6 outputs.  So the flow of blocks literally enters each pipe and leaves it within the buffer.

So just like a line of hoppers, of the end point chest of the pipe is full the whole thing backs up

You can also add the filter item to have it skip / focus on certain things
