### ISSUE TITLE
Every block is Doorbells

### ISSUE THREAD

**Issue by GoldeRuby** [PrinceOfAmber/Cyclic#1937]
Minecraft Version: 1.16.5

Forge Version: 36.2.0

Mod Version: 1.5.3

Single Player or Server: Server (Aternos)

Describe problem (what you were doing; what happened; what should have happened):
Before this bug became a big issue, I just wrote it off as a worldgen error, Cyan Roses were being spawned as Doorbells, they functioned like doorbells, but broke exactly like the flower would. At the time, it wasn't doing any harm, so I didn't think anything of it, until I was trying to use the Dark Glass for a viewing window into a Zombie farm, and when I placed the blocks, they placed as doorbells! I thought maybe it must've been an internal mod confliction (I was playing with a custom-assembled pack), so I went into a Singleplayer world in Creative to test it out and both blocks placed like normal.
While typing up this issue, I made a new world with Biomes O' Plenty (version 13.1.0.477-universal) to see if that was the confliction, but it wasn't. The only thing I could think could be causing this is some sort of internal confliction with Aternos, which I hope it isn't as it's the only server host I can afford without any solid income.
It's _very_ late right now (half-past midnight) and I have something to get to in the morning, so I'll update with a video of the blocks changing when I get the chance tomorrow.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by GoldeRuby** [comment]
UPDATE:
I've tried changing the Dark Tempered Glass to the Dark Connected Glass
that places like normal, except the texture is very buggy with connecting to other glass

**Comment by Lothrazar** [comment]
Thanks for the update, and good luck with your resource pack i guess
