### ISSUE TITLE
Construction Wand places item cables when an item cable is looked at

### ISSUE THREAD

**Issue by innesm** [PrinceOfAmber/Cyclic#1938]
Minecraft Version: **1.16.5**
Forge Version: **36.2.8**
Mod Version: **Cyclic-1.16.5-1.5.3**
Single Player or Server: **Single Player**

Describe problem:
(while playing SkyFactory One Mod Pack)

Looking at an item cable while holding a Construction Wand (Construction Core mod) causes item cables to be built around the existing one without any mouse clicks. The placed cables don't drop an item when mined.

https://user-images.githubusercontent.com/133220/137890238-ff1ff01a-506a-4213-a22d-b2f7088c32f8.mp4

**Comment by innesm** [comment]
Looks like this has been addressed in the modpack: 
https://github.com/DarkPacks/SkyFactory-One/issues/34

**Comment by Lothrazar** [comment]
modpack resolved with disabling in a config.  

making a change for mod v1.5.6 to allow building with cables again, gif shows preview and build working with default configs.
![1938](https://user-images.githubusercontent.com/621529/138582103-b9083e85-a544-46ce-b55d-cf2d4326bf6c.gif)
