### ISSUE TITLE
Crystallized Amber JEI Description Incorrect Display

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1940]
Minecraft Version: 1.16.5

Forge Version:  36.2.8

Mod Version: 1.5.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened): The JEI description page isn't displaying correctly 

![image](https://user-images.githubusercontent.com/10309699/138337937-bead56bd-b2df-4977-884a-695cebf2317c.png)

**Comment by Lothrazar** [comment]
Resolved in 1.5.5
