### ISSUE TITLE
COFH Honey Does Not Function in Solidifier

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1941]
Minecraft Version: 1.16.5

Forge Version: 26.2.8

Mod Version: 1.5.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

COFH liquid Honey (forge:honey) can be piped into the solidifier but will not work in the recipe to make Crystallized Amber. Can the recipe be altered to accept any forge:honey?

**Comment by Lothrazar** [comment]
Resolved in 1.5.5
