### ISSUE TITLE
obsidian gems

### ISSUE THREAD

**Issue by GingerNinja7129** [PrinceOfAmber/Cyclic#1943]
Minecraft Version: 
1.16.5
Forge Version: 
1.16.5
Mod Version: 
idk
Single Player or Server:
server
Describe problem (what you were doing; what happened; what should have happened):

where do i get and how do i get obsidian gems is there a new mod i need for them or something or can they be got with just the cyclic mod

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Yes it has a recipe just like everything else. uses the Solidifier with some liquids.

Do you have JEI or the guidebook mod in your pack they should help 
https://www.curseforge.com/minecraft/mc-mods/jei
https://www.curseforge.com/minecraft/mc-mods/patchouli

**Comment by GingerNinja7129** [comment]
What liquids and how do i get them is there a vid to watch

**Comment by Lothrazar** [comment]
"What liquids and how" all in the recipes my friend, in the mods linked. and yes tons of videos, look up your modpack name on youtube :D good luck. also for more help check out the discord 

https://discord.lothrazar.net/
