### ISSUE TITLE
Ender Book Teleports Players In or Below Blocks When Teleporting Between Dimensions

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1946]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.5

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

When using the Ender Book within the same dimension, teleporting works perfectly. When, however, you teleport from one dimension to another (e.g. The Nether to the Overworld) It will spawn you inside the block and you'll either suffocate or fall into the void. 

It may be because the block is not loaded when the player is teleported therefor the player falls through the location

**Comment by Lothrazar** [comment]
I changed the order of operations to be more similar to how Telepastries runs things and it feels better now.  I flew way out in the nether and reloaded the world to make sure the chunk was not loaded.  So 1.5.6 will have an improvement
