### ISSUE TITLE
[atm-6] Player gets stuck in sleeping mat when used in other dimensions

### ISSUE THREAD

**Issue by radiomike** [PrinceOfAmber/Cyclic#1949]
Minecraft Version: 1.16.5

Forge Version: 36.2.6/8

Mod Version: 1.5.3/5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Used sleeping mat in "mining" dimension
Mat shouldn't be useable in either dimension
Player becomes stuck in sleeping position, "Leave Bed" button doesn't work. Chat box is opened. Requires player to restart client, or be kicked.

Also tested in "The end", Nether and "The Other" with same result.

Log file link:

[ Client latest.log](https://github.com/Lothrazar/Cyclic/files/7412168/latest.log)
[Server latest.log](https://github.com/Lothrazar/Cyclic/files/7412171/latest.log)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
changing it to be like this https://i.imgur.com/a0VWE1i.mp4
