### ISSUE TITLE
Experience Boost giving a little more xp then intended

### ISSUE THREAD

**Issue by NordicGamerFE** [PrinceOfAmber/Cyclic#1955]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.8

Single Player or Server: Server [SP not tested]

Modpack: AffectCraft SMP

Describe problem (what you were doing; what happened; what should have happened):
Just mining and gaining xp loads faster then I should look at video for context

Log file link:

Video/images/gifs (direct upload or link): 
https://www.youtube.com/watch?v=f2MecVWeHK0

**Comment by Lothrazar** [comment]
Sample of enchant at max level (3) mining seven diamond ores with a fortune 3 netherite pickaxe . i gain about one and a bit levels, 14 to 15
![xppp7](https://user-images.githubusercontent.com/621529/140622119-117c779b-9bc4-42e4-a717-37248434bf2e.gif)
