### ISSUE TITLE
I can make Crystallized Obsidian with magma no custom recipes

### ISSUE THREAD

**Issue by NordicGamerFE** [PrinceOfAmber/Cyclic#1956]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.8

Single Player or Server: Server [SP not tested]

Modpack: AffectCraft SMP

Describe problem (what you were doing; what happened; what should have happened):
As the title says I can make Crystallized Obsidian with magma not needing slime to do it out of the box with no recipes changes made

Log file link:

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/18188155/139328601-c051f768-5f79-4694-80bb-88aca00dbb5e.png)

**Comment by Darkosto** [comment]
Adding on to this issue, it seems as though Cyclic does not differentiate between Liquid Slime and Liquid Magma. The recipes can then be swapped regardless of the liquid. This has also created issues when attempting to make Magma with vanilla slimeballs: https://github.com/DarkPacks/SkyFactory-One/issues/110

**Comment by Lothrazar** [comment]
question is the bug with Liquid slime and liquid magma for cyclic or liquids from other specific mods fluids (Tconstruct etc) ?  


GIF https://i.imgur.com/wyfyLKr.gif

**Comment by Lothrazar** [comment]
most recent change to these recipes was 1.3.0. https://github.com/Lothrazar/Cyclic/commit/6858357bb01e63eb82fb653a9870268923ec18ec#diff-0a88e0df665d623ca61bd7f609e86c4ed92e93d4f4104e4755519e1a4979bb65R4 

magma should be tagged just forge:magma and slime as forge:slime  . under forge/tags/fluids (not items or blocks)

**Comment by Lothrazar** [comment]
i believe this is happening only if cyclic:magma is tagged as tconstruct:slimelike   ![tag in sf 102](https://user-images.githubusercontent.com/621529/140183216-b4d41017-d2b3-4137-86f4-4ab66321558d.png)

**Comment by Lothrazar** [comment]
can this be fixed on modpack/datapack end?

If not i could make a change to allow the fluid to take only a tag instead of a fluid.  would make sense but affects recipe json structure for example currently its just 

  ```
"mix": {
    "fluid": "cyclic:slime",
    "count": 500
  },
```

could do a change and instead also accept above but also 

  ```
"mix": {
    "tag": "forge:slime",
    "count": 500
  },
```

**Comment by Lothrazar** [comment]
The fluid tags will be out in v1.5.10 . at that point for anything with fluid input (solidifier, fluid generator, not melter) can put in a tag as shown in previous comment .
this means even if slime and magma both get a "slimelike" tag, magma wont be allowed in slime fluid recipes anymore to fix this.

This also will be showing in JEI with the alternating rendering just like an item tag
![1956 slime](https://user-images.githubusercontent.com/621529/140618237-0f63878f-a21e-4d3d-b4de-4b68f3931ba2.gif)
