### ISSUE TITLE
Battery does not charge

### ISSUE THREAD

**Issue by cbunny787** [PrinceOfAmber/Cyclic#1957]
Minecraft Version: 1.16.5

Forge Version: 36.2.0

Mod Version: 1.5.8

Single Player or Server:both

Describe : I was playing with mods when i use cyclic battery to charge it using mekanism mod its just stay at 0 and taking all energy but it charge with wires idk if its bug or not

Log file link:

Video/images/gifs (direct upload or link): 
![2021-10-29_20 17 14](https://user-images.githubusercontent.com/85269722/139460463-24745e50-9883-42e0-be26-aa180493c285.png)
![2021-10-29_20 20 05](https://user-images.githubusercontent.com/85269722/139460633-d4983918-f788-4f2b-ade2-beffb5dce304.png)

**Comment by Lothrazar** [comment]
ah i need to fix the item capability setup
