### ISSUE TITLE
Inventory Upgrade

### ISSUE THREAD

**Issue by derpssundee23** [PrinceOfAmber/Cyclic#1958]
Minecraft Version: 1.12.2

Forge Version: Magma 1.12.2 vad7ca54-CUSTOM (14.23.5.2855)

Mod Version: Cyclic-1.12-1.20.11.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
For the inventory upgrade, whenever I put items in there and restart my server, it completely gets rid of all the things in that extra inventory and this only occurred when I started using Magma. It was never an issue with regular forge and I was just wondering if you could help me with this issue? Thank you

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
cannot replicate, check server/world/playerdata/ player UUID file names. for example 1234whatever.cyclicinvo and .dat . it uses your player id, which is unique kind of like your username and skin. maybe a mod conflict? These player files are what contain the items
