### ISSUE TITLE
Feature Request: Biome Compass

### ISSUE THREAD

**Issue by EmoKiba** [PrinceOfAmber/Cyclic#196]
-adds a compass that lets you toggle between biomes and points you to the closest biome (that is selected)

**Comment by PrinceOfAmber** [comment]
Good news and bad news:   

I should have known this right away, but i found a mod that does this exactly, and its in my vanilla modpack called Overpowered Non-content

https://minecraft.curseforge.com/projects/natures-compass

**Comment by EmoKiba** [comment]
doesnt mean you cant add it to your mod too

**Comment by PrinceOfAmber** [comment]
Created a milestone for this. I still want to do something for it https://github.com/PrinceOfAmber/Cyclic/milestone/23
