### ISSUE TITLE
TPS lag with Packager and Silent Gear

### ISSUE THREAD

**Issue by jeremiahwinsley** [PrinceOfAmber/Cyclic#1960]
* Minecraft Version: 1.16.5
* Forge Version: 36.2.8
* Mod Version: 1.5.8
* Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Packager creates major TPS lag with the Silent Gear mod installed.

To reproduce:
1. Fresh installation of Forge 36.2.8
2. Install latest versions of Cyclic and Silent Gear
3. Place packagers and provide power.

Here's a spark profile from placing 5 packagers down, resulting in a 200ms spike every 10 ticks.
https://spark.lucko.me/SkBQOVnMtU

Here's a spark profile from when we found it originally, this is the client tick thread on a server, with the ATM6 modpack.
https://spark.lucko.me/Gu7iAdwqL1

**Comment by BIuBOo** [comment]
This issue still exists in Minecraft version 1.19.2. I Play with the modpack Direwolf20 1.19
I get irritating stuttering with just one packager.
I Just checked the code and its looking up the recipe for every tick. Caching or saving the working Recipes should free up a lot of performance.

**Comment by Lothrazar** [comment]
yep looks like feature never got ported and only existed in 1.16 re https://github.com/Lothrazar/Cyclic/commit/c03da7a723262583eb0ffe85282a39db0b853ef0 , looking into porting
