### ISSUE TITLE
Sack of Holding Removes all Refined Storage Crafter Block Upgrades/Patterns

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1963]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.9

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

When picking up a Refined Storage Crafter that has Speed Upgrades or Patterns inside with an Empty Sack of Holding the contents are deleted. I believe this would be on your end because the NBT data is being preserved. 

https://github.com/DarkPacks/SkyFactory-One/issues/123

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
added to default config
