### ISSUE TITLE
Can't extract liquid EXP (from disenchanter)

### ISSUE THREAD

**Issue by SGZ-Creations** [PrinceOfAmber/Cyclic#1965]
Minecraft Version: 1.16.x

Forge Version: 36.2.6

Mod Version: 1.5.3
  
ATM6 Server 1.8.7 

Describe problem (what you were doing; what happened; what should have happened):
* Problem is that nether Mekanism or pipz mod works to take luquid EXP out of Disencahnter. & modpack diasbled yours.
* waht should happen is any of these fluid pipes from either mods should be able to extract the luquid EXP.
Note: Your config allow for gaining EXP my disenchanting so i felt it would be nice having some when disenchating please don't remove.

Log file link: 
[latest.log](https://github.com/Lothrazar/Cyclic/files/7481983/latest.log)
[debug.log](https://github.com/Lothrazar/Cyclic/files/7481986/debug.log)

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/59801736/140487447-3b7d1cb5-e21e-4c1d-94c4-26b1ac846c55.png)

**Comment by Lothrazar** [comment]
fluid hoppers work

![1965](https://user-images.githubusercontent.com/621529/140619710-b3ab049e-ce38-4be1-854c-f0ec20ddc8a7.gif)

**Comment by Lothrazar** [comment]
cables look good, yeah idk u will have to play with the pipez or mek cable filters or however those work i guess, sounds like your modpack is pretty customized

![1965part 2](https://user-images.githubusercontent.com/621529/140619743-ef483983-1d32-4296-9360-ba3d7342f090.gif)

**Comment by SGZ-Creations** [comment]
Thank for the help. The issue seemed to be a server issue of some sort that i can't explain
