### ISSUE TITLE
Battery resets to zero when placed in charging slot

### ISSUE THREAD

**Issue by jstansel** [PrinceOfAmber/Cyclic#1968]
Minecraft Version: 1.16.5

Forge Version: 36.2.0

Mod Version: 1.16.5-1.5.9

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
I placed a a battery with a full charge into a charging slot and observed that it reset to a charge of zero before starting to charge. It should have lost the initial charge. When reproducing, I found that any random amount of charge always resets to zero when placed into a charging slot. I reproduced the issue with only Cyclic installed, but I first saw the issue when using the Mekanism energy cube charging slot.

To reproduce:
1. Place a combustion generator and put in a stack of planks
2. Place a battery next to the generator and observe that it begins to charge
3. Place another battery into the charging slot of the generator and observe that it begins to charge
4. Wait several seconds and remove the battery from the charging slot
5. Note the charge level of the second battery
5. Insert the second battery back into the charging slot and observe that the initial charge reset to zero
6. Remove the battery from the charging slot without waiting and observe that the charge level is less than the level from step 4

I am not sure if this could be related to #1957 but I noticed it after upgrading to 1.5.9.

Log file link: NA

Video/images/gifs (direct upload or link): NA

**Comment by jstansel** [comment]
Note: I upgraded to the latest version of Forge (36.2.9) and observed the same behavior.

**Comment by jstansel** [comment]
I reverted to the Forge RB 36.2.0 and to Cyclic 1.5.8 and added Mekanism 10.0.24.453 in order to have a charging slot. When placing the battery into the charging slot of the energy cube it did not revert the battery charge to zero, but as expected it did not charge, either.

**Comment by Lothrazar** [comment]
ill test some more with these updated mod versions, and cyclic 1.5.9 , as was updated per change log 1.5.8->1.5.9
![minimal list](https://user-images.githubusercontent.com/621529/140627190-ec371ebd-1395-4678-92e2-0d242411ef36.PNG)

**Comment by Lothrazar** [comment]
yeah thats not working correctly
edit: same behavior in slots of generators etc, battery itemstack issue 

![replicate](https://user-images.githubusercontent.com/621529/140627303-b5b6ef45-ca37-4bc2-b1cf-1486f818a5b3.gif)
