### ISSUE TITLE
Ender book can't remove EXP cost

### ISSUE THREAD

**Issue by SgtDarkHawk** [PrinceOfAmber/Cyclic#197]
Hi
I'm playing on my server and i wanted to use the ender book without exp cost.
I looked in the file config and change the value to 0, but it didn't work, when i try to teleport it says Not enough EXP

what should i do?

Cyclic version: 1.8.14
Forge:  12.18.3.2185
Minecraft: 1.10.2

**Comment by PrinceOfAmber** [comment]
Should be resolved in latest release https://minecraft.curseforge.com/projects/cyclic/files/2354294

The config file used to have "minimum value 1" enforced, that was removed so it allows zero now
