### ISSUE TITLE
Energy transfer node is nerfed too much

### ISSUE THREAD

**Issue by LuciusV** [PrinceOfAmber/Cyclic#1972]
Minecraft Version: 1.16.5
Mod Version:  1.16.5-any

Describe problem (what you were doing; what happened; what should have happened):
In 1.12 version, we had 9 slots for GPS markers which was very convenient for supplying machines with energy without cable mess.
Now it only transfers to one block, which as best can be used as connection of two cable networks and everyone would do it with flux networks instead.

Could you please restore 1.12 functionality?

**Comment by Lothrazar** [comment]
yeah i know. it felt kind of OP before. 

Im not against balancing it up some more if needed maybe

Could you send it out to a large battery at the destination point, and then pull 4-6 cables out of that battery to split the signal?  or is that not enough to power things

**Comment by LuciusV** [comment]
Of course I can, but I do it with less expensive flux networks. Reason to use Energy transfer node is powering machines without cable mess and waste of space, not long distance transfer.
Recipe got more expensive in 1.16.5 so I feel it is balanced even if it will power 9 machines :)

**Comment by DIASILEDU** [comment]
I wonder if this could be set via config file in order to maintain balance depending on the preferred machine slots. Just to be able to set how many gps markers are available, i think it would be better for modders to choose than just locking it to 9 or 3.

**Comment by adkinss** [comment]
I came here looking for information about the 9 slot change to 1.  I used to use these nodes a lot to reduce cabling clutter and reduce overall machine footprint.  It can still be done with the 1 slot nodes, but it then becomes a 9x cost, in addition to the recipe cost changes.  I understand the OP argument though.

I like the idea of a config option to let the modder pick.  However, I would not be surprised if most modpacks end up using the defaults.  Having a default that isn't 1 would be nice, but it doesn't have to be 9 either.

Another idea: What about affecting the range of wireless power based on number of GPS cards installed?  (Like max range is inversely proportional to the number of cards installed).  For those of us who just want to declutter cables, sticking a node under a column of machines is worth the trade-off.  If that is still too OP, then scale the power down the same way, which would force a decision between fewer power hungry machines vs more power efficient machines.

**Comment by LuciusV** [comment]
> I came here looking for information about the 9 slot change to 1. I used to use these nodes a lot to reduce cabling clutter and reduce overall machine footprint. It can still be done with the 1 slot nodes, but it then becomes a 9x cost, in addition to the recipe cost changes. I understand the OP argument though.
> 
> I like the idea of a config option to let the modder pick. However, I would not be surprised if most modpacks end up using the defaults. Having a default that isn't 1 would be nice, but it doesn't have to be 9 either.
> 
> Another idea: What about affecting the range of wireless power based on number of GPS cards installed? (Like max range is inversely proportional to the number of cards installed). For those of us who just want to declutter cables, sticking a node under a column of machines is worth the trade-off. If that is still too OP, then scale the power down the same way, which would force a decision between fewer power hungry machines vs more power efficient machines.

Don't forget that Draconic Evolution has been released, and its wireless transfer is superior (it still takes effort to install). There is no point to nerf wireless energy transfer.

**Comment by YokoSilver** [comment]
So if there's no point to nerf wireless energy transfer then why was the Cyclic energy nerfed? The old method of crafting was indeed easier and swapping a block of redstone for Crystallized Amber did indeed make it harder to craft due to the now even more materials required along with have to use the solidification chamber and the melting chamber together. Not to mention the GPS even got a buff going from 3 items to a full 9 items and another 9 just to make one of those items needed.

It was great where I could have multiple solar panels being connected to the energy transfer node and have it be tucked away for easy energy usage. But now I'd need multiple of these. As others mentioned having it set somewhere in the GUI allowing us to choose how many slots we want would make things better or just go back to how it used to be.

**Comment by Lothrazar** [comment]
![stand](https://user-images.githubusercontent.com/621529/153527959-3225d133-a31a-4ddf-8f8c-4c21c8da702a.png)

**Comment by YokoSilver** [comment]
> ![stand](https://user-images.githubusercontent.com/621529/153527959-3225d133-a31a-4ddf-8f8c-4c21c8da702a.png)

so how do we go about changing it to that now?

**Comment by YokoSilver** [comment]
so no answer?

**Comment by LuciusV** [comment]
Why only 1.18 got this change while ticket was for 1.16?
1.18 if far from stable and least for modpacks, could you please backport...

**Comment by FDK101** [comment]
Can't believe the Dev just ignored the fact that this was requested for 1.16 and closed it off as it was added back to 1.18.
Sure, we don't have to use this mod and can use something else or just go to 1.18

But what it the point then of this mod in 1.16? The recipe is expensive and you only have one slot?

That to me does not sound like balancing the mod.

**Comment by YokoSilver** [comment]
> Can't believe the Dev just ignored the fact that this was requested for 1.16 and closed it off as it was added back to 1.18. Sure, we don't have to use this mod and can use something else or just go to 1.18
> 
> But what it the point then of this mod in 1.16? The recipe is expensive and you only have one slot?
> 
> That to me does not sound like balancing the mod.

Seriously, I've been wanting an answer and so far all we've gotten was radio silence. It's like you said we either move to the later version which does offer the feature or just ignore this mod entirely. Which at this point is something I plan on. Cyclic was nice while it lasted but with so many changes making certain items more expensive or giving them massive nerfs just isn't worth it anymore.

I mean why make the item crazy expensive only to then give it the ultimate nerf? I don't really see that as a balance. If you make something more expensive you keep the end results the same. If you want to nerf it then you make it cheaper and do less.

**Comment by FDK101** [comment]
Agree completely, but I can't see the light at the end of this tunnel so I moved to Flux Network for energy and then Ender Storage mod for items.

Not ideal but not much I we can do...
