### ISSUE TITLE
Cable duplication with Mekanism Configurator in wrench mode

### ISSUE THREAD

**Issue by JakeMoe** [PrinceOfAmber/Cyclic#1973]
**Minecraft Version:**
1.16.5

**Forge Version:**
36.2.2

**Mod Version:**
Cyclic - 4.0.5.2
Mekanism - 10.0.21

**Single Player or Server:**
Server (local, only myself)

**Describe problem (what you were doing; what happened; what should have happened):**
Not sure which side this is on (Mekanism or Cyclic), but if I try to remove Cyclic Cables with the Mekanism Configurator in wrench mode, it gives me the cable but also leaves the cable behind with the connection configs changed, i.e., it looks like it's changing the connections. If I have a cable that connects a chest to a machine, and I shift-right-click the cable on a non-connected side, the cable changes to push / pull, and if I look in chat, I can see messages saying that it's changed.

If I just right-click the block (without shift) with the Configurator in wrench mode, it also changes the connections, but doesn't dupe the cable.

I'm running the mod in the FTB DireWolf20 1.16 modpack.  And I've also logged this on the Mekanism side, but they believe it's on Cyclic's side: https://github.com/mekanism/Mekanism/issues/7343

**Comment by Lothrazar** [comment]
does it still happen on 

Cyclic-1.16.5-1.5.11.jar

**Comment by beholderface** [comment]
I just tried this with latest release versions of everything, I did not see any duplication

**Comment by JakeMoe** [comment]
DW20 just updated today, and Cyclic went up to 1.5.11.  Tested again and no duplication.  Cheers.
