### ISSUE TITLE
Forester Not picking up drops after Operation

### ISSUE THREAD

**Issue by starr274** [PrinceOfAmber/Cyclic#1974]
Minecraft Version: 1.16.5

Forge Version: 32.2.16

Mod Version: Cyclic-1.16.5-1.5.11.jar

Single Player or Server: SSP

Describe problem (what you were doing; what happened; what should have happened):

was running the Forester in a 7x7x7 room, after it completed the pass to break the logs and leaves it left the items on the ground, set up fans on creative to blow the drops into hoppers

Video/images/gifs (direct upload or link): 

![2021-11-22_21 18 10](https://user-images.githubusercontent.com/2853335/142967901-5ebb4ab4-57af-4004-8580-cbd6d9c3fd6f.png)

**Comment by Lothrazar** [comment]
the Item Collector can pick up drops such as saplings/logs
