### ISSUE TITLE
Garden Scythe (desync)

### ISSUE THREAD

**Issue by firestorm2039** [PrinceOfAmber/Cyclic#1975]
Minecraft Version: 

Forge Version: 36.2.4

Mod Version: latest 1.16.5

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
when i use the garden Scythe it auto farms the stuff its supposed to and leave the seeds in, but the image does not change, for example, wheat- use garden scythe on fully grown wheat and it stays fully grown, but it does mine the wheat like its supposed to. its like the fully grown wheat image is frozen?.
i DO NOT have this issue with the 1.16.4 version though, so i dont think its conflicting with another mod?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
This is fixed in Minecraft 1.18 , but yeah i do see the desync in 1.16

**Comment by firestorm2039** [comment]
> This is fixed in Minecraft 1.18 , but yeah i do see the desync in 1.16

but it works fine in previous versions as well, wouldnt it be an easy fix, maybe a 2 minute thing? like copy and pasting something from a previous version?

i dont know anything about modding lol, so i may be way of the mark or something lol.

i cant download 1.18 yet as none of the others mods i have are 1.18 yet, dont fancy getting of any as well
