### ISSUE TITLE
Crash after unbinding inventory management keys

### ISSUE THREAD

**Issue by darkphan** [PrinceOfAmber/Cyclic#198]
After unbinding the inventory movement keys I get the following crash:

http://pastebin.com/W6y8Ez5t

**Comment by PrinceOfAmber** [comment]
Couldnt replicate it any way i tried but the log narrowed it down to the line number.  In linked commit i added some if/else checks and a try/cacth as well, both of them should fix it

**Comment by PrinceOfAmber** [comment]
Should be resolved in latest release https://minecraft.curseforge.com/projects/cyclic/files/2354294
