### ISSUE TITLE
Multi Jump on Elytra doesn't work when used in a bauble slot

### ISSUE THREAD

**Issue by Memekiller** [PrinceOfAmber/Cyclic#1980]
Minecraft Version:  1.16.5

Forge Version:  36.2.8

Mod Version:  Cyclic-1.16.5-1.5.8.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

When worn as a bauble, the multi jump on an elytra does not work. Works just fine on the back though. This is on "All the mods! 6"

Log file link:

Video/images/gifs (direct upload or link):

**Comment by LiderKonmils** [comment]
Same thing if equiped in Curios slot in1.18.1.
