### ISSUE TITLE
Dehydrator Recipe Conflict

### ISSUE THREAD

**Issue by BoozeAndMidgets** [PrinceOfAmber/Cyclic#1984]
Minecraft Version: **1.12.2**

Forge Version: **14.23.5.2854**

Mod Version: **1.20.3**

Single Player or Server: **Self-hosted server on separate PC.** This is a Sky Factory 4 server specifically.

Describe problem (what you were doing; what happened; what should have happened):

Trying to make vines using the Dehydrator. Instead of Jungle Saplings making vines it just makes sticks.
There is a recipe conflict present and unfortunately the recipe for sticks takes priority. Screenshots below.

Video/images/gifs (direct upload or link): 

Vines Recipe:
![vinescyclic](https://user-images.githubusercontent.com/13664837/144762957-585217d7-62b3-44df-9109-b603028eb88f.PNG)

Stick Recipe:
![stickcyclic](https://user-images.githubusercontent.com/13664837/144762959-8d7acd12-b3fe-44bf-9723-049a7b7a2cd4.PNG)

Dehydrator in action using Jungle Saplings:
![dehydrator](https://user-images.githubusercontent.com/13664837/144762962-56c73ab9-19a1-49db-98b6-023aa9e5abd7.PNG)

**Comment by Lothrazar** [comment]
by default there arent any recipes to create vines. modpacks can add and remove recipes on their own if desired, so they could remove sticks and add something else with json or zenscript or whatever.  

no conflict by default
![1984](https://user-images.githubusercontent.com/621529/160305724-2eb02b5c-b361-4aa4-bdec-39f6415f9ee9.gif)
