### ISSUE TITLE
1.18 issue with items not saving inside containers

### ISSUE THREAD

**Issue by Herposhima** [PrinceOfAmber/Cyclic#1985]
Minecraft Version: 1.18

Forge Version: 38.0.15

Mod Version: 1.6.5

Single Player or Server: Both

Describe problem: Items placed inside of container will be purged upon reload of world. (Tested on machines, crates, and anvil variants. The Storage Bag works properly, and the Sack of Holding will save the inventory of the crate inside upon reload. Note: There are other 1.18 mods that I have used that experience this issue [ex. Mr. Crayfish's Furniture Mod])

**Comment by Herposhima** [comment]
Similar issue with the Storage Bag actually, when changing the gamemode from survival to creative it will purge the items from inside the bag. Items will also be purged during creative if you swap the bag from your hotbar into your inventory.

UPDATED TO 1.6.6 Storage Bag will purge during creative when grabbed from hotbar. 

Single player is now saving items inside the crate upon reload, but my server seems to still be deleting them. Items still vanish from anvil's and machines.

**Comment by Lothrazar** [comment]
Thanks for the update. yeah 1.6.6 should have  fixed the blocks saving but ill check out the storage bag too

**Comment by Lothrazar** [comment]
Marked storage bag as also affected by 1.18 here https://github.com/Lothrazar/Cyclic/issues/1886
