### ISSUE TITLE
Fluid cable crash

### ISSUE THREAD

**Issue by aAndrew3030** [PrinceOfAmber/Cyclic#1988]
Minecraft Version: 1.18

Forge Version: 38.0.16

Mod Version: 1.6.6

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Wrenching the fluid cable onto a machine caused the game to crash and I am now unable to rejoin the world

Log file link:

https://bytebin.lucko.me/BvUYHtQRBf

Video/images/gifs (direct upload or link):

**Comment by Eelt** [comment]
Although the crash is Voluminous Energy's fault, I do want to comment to the mod developer for Cyclic that their pipes passing a null direction, while allowed (as directions are nullable) may not be intended behaviour.

Block Entities (formerly known as Tile Entities) like in Voluminous Energy that has multiple fluid handlers do effectively require a direction to be passed to provide the correct handler based on the user's configuration for the Block Entity. Passing null, may not effectively work and it does not accurately reflect the settings of the user's in-game configuration for the machine. 

There are a few ways I could make this more elegant (IE allowing the user to choose what handler to pass when the side is null), but this may not be Cyclic's pipe's intended behaviour to pass null for the direction in 1.18.

**Comment by Lothrazar** [comment]
capabilities and the side can be null and that should be handled. also yeah for the sided ness, maybe i should change
`    return tile.getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY.orElse(null);`
    to 
    
`        return tile.getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY, side).orElse(null);`
        on that line 94
