### ISSUE TITLE
Cyan Rose and Lime Carnation graphic gub

### ISSUE THREAD

**Issue by etherealgears** [PrinceOfAmber/Cyclic#1989]
Minecraft Version: 1.18

Forge Version: 38.0.7.

Mod Version: 1.18-1.6.7.

Single Player or Server: Singe Player

Describe problem (what you were doing; what happened; what should have happened): The Cyan Rose and the Lime Carnation are bugged somehow and have these black and white boxes around them.

Log file link:

Video/images/gifs (direct upload or link): 

![2021-12-10_16 39 26](https://user-images.githubusercontent.com/93540791/145602876-c76d5f13-d552-4b4d-8c62-4ee78925002d.png)

**Comment by Lothrazar** [comment]
in mc 1.18.1 and forge 39.0.9  
![new forge](https://user-images.githubusercontent.com/621529/147793214-4a3e51fc-0639-42c7-9238-04783dd787cb.png)
