### ISSUE TITLE
Where is the Automated User to automate left clicks

### ISSUE THREAD

**Issue by sippeeey** [PrinceOfAmber/Cyclic#1992]
Minecraft Version: 1.16.5

Forge Version: 36.2.4

Mod Version: Cyclic-1.16.5-1.5.11

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Where is the Automated User to automate left clicks? I only have an Item User to automate right clicks.

**Comment by metalshark** [comment]
Have you tried it without an item? I use that personally but YMMV.

**Comment by sippeeey** [comment]
> Have you tried it without an item? I use that personally but YMMV.

i dont unterstand your question. i dont found any other way to automate a left click on some blocks. i want to use it for automate some flux dust from the "flux networks mod". There is no other way, to automate an left click on a block. the "item user" only make right clicks.

**Comment by metalshark** [comment]
My bad - you may be able to achieve what you need using the Miner. If you reduce the range it's trying to operate in and you can put a tool (if required) in the top slot.

**Comment by sippeeey** [comment]
> My bad - you may be able to achieve what you need using the Miner. If you reduce the range it's trying to operate in and you can put a tool (if required) in the top slot.

i allready tried that, but the miner destroy the block. i need an automated User left click. the block must not be destroyed.

**Comment by metalshark** [comment]
Excuse my bad throwing skills, but is this what you'd like it to do?

https://www.youtube.com/watch?v=5hOBOL1BEIE

If so the code to put this in would below and I can create a Pull Request with a new icon to select left or right-clicking on the Item User. If it isn't could you explain please?

```java
  public static ActionResultType leftClickBlock(final WeakReference<FakePlayer> fakePlayerWeakReference,
                                                final World world, final BlockPos targetPos, final Hand hand, final Direction facing) {
    final FakePlayer fakePlayer = fakePlayerWeakReference.get();
    if (fakePlayer == null) {
      return ActionResultType.FAIL;
    }
    final Direction placementOn = (facing == null) ? fakePlayer.getAdjustedHorizontalFacing() : facing;
    final BlockRayTraceResult blockRayTraceResult = new BlockRayTraceResult(fakePlayer.getLookVec(), placementOn, targetPos, true);
    try {
      fakePlayer.interactionManager.func_225416_a(blockRayTraceResult.getPos(), START_DESTROY_BLOCK, facing, 0);
      return ActionResultType.SUCCESS;
    }
    catch (Exception e) {
      return ActionResultType.FAIL;
    }
  }
```

**Comment by sippeeey** [comment]
> Excuse my bad throwing skills, but is this what you'd like it to do?
> 
> https://www.youtube.com/watch?v=5hOBOL1BEIE
> 
> If so the code to put this in would below and I can create a Pull Request with a new icon to select left or right-clicking on the Item User. If it isn't could you explain please?
> 
> ```java
>   public static ActionResultType leftClickBlock(final WeakReference<FakePlayer> fakePlayerWeakReference,
>                                                 final World world, final BlockPos targetPos, final Hand hand, final Direction facing) {
>     final FakePlayer fakePlayer = fakePlayerWeakReference.get();
>     if (fakePlayer == null) {
>       return ActionResultType.FAIL;
>     }
>     final Direction placementOn = (facing == null) ? fakePlayer.getAdjustedHorizontalFacing() : facing;
>     final BlockRayTraceResult blockRayTraceResult = new BlockRayTraceResult(fakePlayer.getLookVec(), placementOn, targetPos, true);
>     try {
>       fakePlayer.interactionManager.func_225416_a(blockRayTraceResult.getPos(), START_DESTROY_BLOCK, facing, 0);
>       return ActionResultType.SUCCESS;
>     }
>     catch (Exception e) {
>       return ActionResultType.FAIL;
>     }
>   }
> ```

yes it is. so maybe with some redstone e.g. to activate the left click.

i thought this is exactly what the "automated user" was supposed to be doing. if you were to integrate that into the "item user", it would be the same, so great.

**Comment by metalshark** [comment]
> > Excuse my bad throwing skills, but is this what you'd like it to do?
> > https://www.youtube.com/watch?v=5hOBOL1BEIE
> > If so the code to put this in would below and I can create a Pull Request with a new icon to select left or right-clicking on the Item User. If it isn't could you explain please?
> > ```java
> >   public static ActionResultType leftClickBlock(final WeakReference<FakePlayer> fakePlayerWeakReference,
> >                                                 final World world, final BlockPos targetPos, final Hand hand, final Direction facing) {
> >     final FakePlayer fakePlayer = fakePlayerWeakReference.get();
> >     if (fakePlayer == null) {
> >       return ActionResultType.FAIL;
> >     }
> >     final Direction placementOn = (facing == null) ? fakePlayer.getAdjustedHorizontalFacing() : facing;
> >     final BlockRayTraceResult blockRayTraceResult = new BlockRayTraceResult(fakePlayer.getLookVec(), placementOn, targetPos, true);
> >     try {
> >       fakePlayer.interactionManager.func_225416_a(blockRayTraceResult.getPos(), START_DESTROY_BLOCK, facing, 0);
> >       return ActionResultType.SUCCESS;
> >     }
> >     catch (Exception e) {
> >       return ActionResultType.FAIL;
> >     }
> >   }
> > ```
> 
> yes it is. so maybe with some redstone e.g. to activate the left click.
> 
> i thought this is exactly what the "automated user" was supposed to be doing. if you were to integrate that into the "item user", it would be the same, so great.

Thank you, great. I'll work on that later today. Which version of Minecraft do you use and do you mind testing it out?
