### ISSUE TITLE
Fluid pipe 

### ISSUE THREAD

**Issue by castilio20** [PrinceOfAmber/Cyclic#1998]
Minecraft Version: 
1.16,5
Forge Version: 
1.16.5-forge-36.2.22
Mod Version: 
Cyclic-1.16.5-1.5.12
Single Player or Server:
SP
Describe problem (what you were doing; what happened; what should have happened):
Fluid pipe extracts the first thing and ignores thermal configuration
should extract the final produs
tried to automate tree extract thing but it extracts the first thing it brakes to whole procees if you dont have a constant final product

![2021-12-21_08 37 27](https://user-images.githubusercontent.com/76228548/147389655-6d1bd763-c521-4ef8-8c3e-72a173eb83b1.png)

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
If your thermal machine is set to export to the right into the fluid cable, then the cable doesnt need to have its own export mode just have it a normal cable so it can fill up.
