### ISSUE TITLE
Sack of Holding purging chest inventories on use

### ISSUE THREAD

**Issue by Salamance73** [PrinceOfAmber/Cyclic#1999]
Minecraft Version: 1.18.1

Forge Version: 39.0.6

Mod Version: 1.6.7

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
Using Sack of Holding to move chests around, deleted two chests (modded and unmodded). Looks like it isn't recording the inventory within the NBT on pickup of the object.

Log file link:
No noticeable log entries.

Video/images/gifs (direct upload or link): 
Chest inventory pre-pickup:
![image](https://user-images.githubusercontent.com/26430914/147402994-adb5262a-305d-465e-9235-d363496dd0fe.png)

Sack NBT during holding:
![image](https://user-images.githubusercontent.com/26430914/147403023-87816c53-3c6e-49d4-9d5a-643d117a9bf0.png)

Chest inventory post-placement:
![image](https://user-images.githubusercontent.com/26430914/147403032-93aa476b-5c97-474c-9d0d-5d2c3afde122.png)

**Comment by alataq** [comment]
I have the same problem.
