### ISSUE TITLE
automatic fisher not working with Transfer Nodes from extrautils2 

### ISSUE THREAD

**Issue by LuisAdeur** [PrinceOfAmber/Cyclic#200]
tried every side nothing works with or without filter

**Comment by PrinceOfAmber** [comment]
I never thought about this, since if you had a transfer node on one side, there wouldnt be any water there, so it would stop fishing.

If its full, it will keep fishing and drop the items below out in the world.

But it shouldnt be hard to also let it work with hoppers/nodes as well.

**Comment by LuisAdeur** [comment]
correct , hoppers work fine but is a hassle. thanks i hope it gets fixed soon :)

**Comment by PrinceOfAmber** [comment]
Fixing this for 1.9.2 release coming soon.

Well, after these changes it works with hoppers, and works with enderio item conduits.  Doesnt appear to work with extrautils2, but i had an old version , must be a bug on their end that got fixed later on i hope (extrautils2-1.10.2-alpha-1.2.1)

**Comment by LuisAdeur** [comment]
thanks for the commit :)
