### ISSUE TITLE
1.18.1 - Crushing Macerator don't work on reloaded game

### ISSUE THREAD

**Issue by Justus75** [PrinceOfAmber/Cyclic#2000]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.0

**Mod Version:** Cyclic-1.18-1.6.7

**Single Player or Server:** Single Player

**Describe problem (what you were doing; what happened; what should have happened):**
The Crushing Macerator dont work on a reloaded game. Only to destroy and place them again solve the problem.

**Log file link:** -none-

**Video/images/gifs (direct upload or link):** 
<img width="393" alt="2021-12-26 19_02_31-Minecraft_ 1 18 1 - Singleplayer" src="https://user-images.githubusercontent.com/96327909/147416490-1f79069e-82d5-42e1-9a55-9859acb18303.png">

**Comment by Lothrazar** [comment]
v1.6.8 has a big fix related to this

**Comment by jack-flash** [comment]
This appears to be an issue with the tick() and not calling this.findMatchingRecipe(); when the game is first started to reset the recipe.  I will submit a pull request for this.

**Comment by jack-flash** [comment]
Sorry, still getting up to speed with the Pull Requests...new to this.
