### ISSUE TITLE
How to modify what can be used and what cannot.

### ISSUE THREAD

**Issue by HelixCreations** [PrinceOfAmber/Cyclic#2002]
**Minecraft Version:**  1.18.1

**Forge Version:**  39.0.0+

**Mod Version:** Latest

**Single Player or Server:** Server

**Describe the problem (what you were doing; what happened; what should have happened):**

I would like to know how can I modify the ingredients for some of the items in this mod. Because I think some of the items are too cheap for what they do.

Thanks.

**Comment by Lothrazar** [comment]
yep! there are many ways to do this. normally a modpack will just make a "data pack", and then you can override any recipe with whatever you want .
Default recipes are like this 
https://github.com/Lothrazar/Cyclic/tree/trunk/1.18/src/main/resources/data/cyclic/recipes

Ive never made a data pack i assume its just like resource packs https://minecraft.fandom.com/wiki/Recipe
https://www.wikihow.com/Make-a-Minecraft-Data-Pack
Also some people use mods to edit recipes like CraftTweaker or Kubejs, but i havent touched those in years so youd have to learn how they work

Good luck with the pack!
