### ISSUE TITLE
Items disapearing in devices after exit the game

### ISSUE THREAD

**Issue by riesseg** [PrinceOfAmber/Cyclic#2003]
Minecraft Version: **1.18.1**

Forge Version: **39.0.9**

Mod Version: **1.18-1.6.7**

Single Player or Server: **Single Player**

Describe problem (what you were doing; what happened; what should have happened):

Item disapear from some devises. 
Like Combustion generator. 
Or Melting Chamber.
Or Solidification chamber. 

Tested multiple times : Put some logs in the combustion chamber. Exit the game and closing the world. 
Reconnect. Log gone. try to replace them with planks. Disconnect-Reconnect. And it's the old logs in the device....

About the melting/solidification chamber. 
Put RF on in (full cyclic, with batteries and cable). 
Add like honey, and firecharge, redstone and magmablock... Disco-Reco.... Redstone gone ! and the crystalized amber too. 
For the melting, put some slimball. Disco-Reco... All Gone. Liquid and items. Same with magma. 

Not try with every recipes, every devices... 

_Know that ironFurnace have the same issue (item desapearing after exit the game) and he resolved-it some day ago._

**Comment by Lothrazar** [comment]
Weird that it sometimes deletes them and sometimes doesnt its kinda random but yeah tis still happening. sometimes and some machines. ill see what ironfurnace did

**Comment by Lothrazar** [comment]
v1.6.8 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3587277
