### ISSUE TITLE
Item User doesn't work with Mythical Agriculture Watering Can

### ISSUE THREAD

**Issue by Lavan** [PrinceOfAmber/Cyclic#2004]
Minecraft Version: 1.18.1

Forge Version: 39.0.9

Mod Version: 1.6.7

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Using a watering can from Mythichal Agriculture in an Item User should water the crops below, instead nothing happens..

Log file link:

No logs.

Video/images/gifs (direct upload or link): 

[Setup](https://imgur.com/a/jS8zlWR)

I have also tried to move the item user down one block as well removing the slab and torch below and also adding farmland just below.

**Comment by Lothrazar** [comment]
i just fixed some stuff with machines in v1.6.8
 
 It now works fine with the watering can from this https://www.curseforge.com/minecraft/mc-mods/gardening-tools  , grows weat fine
 
 Does the mystical one need water or any other special settigns?

**Comment by jack-flash** [comment]
Been poking at this for a day or so now.  See issue here:

https://github.com/BlakeBr0/MysticalAgriculture/issues/474

I also believe the FakePlayer is not properly decrementing the itemCooldown.  See issue submitted here:

https://github.com/MinecraftForge/MinecraftForge/issues/8392

Was talking with metalshark and likely the best course is to have the cyclic:user (Item User) override the FakePlayer cooldowns until it gets resolved.  This is a problem with the 1.18.1 MC version on Forge 39.0.* (tested 39.0.9 and 39.0.19) along with the Cyclic-1.18.1-1.6.9 version.

**Comment by cloneboss42** [comment]
Not to undermine the severity of this issue as I have not played a pack with both cyclic and MA in while. However, maybe 9 months ago I was able to automate this successfully... did you fill the watering can with water..?

**Comment by Lavan** [comment]
Yes, I did. This is the 1.18 version we're talking about. Please check the other comment on the issue for the probable cause. 

cloneboss42 ***@***.***> skrev: (2 februari 2022 14:25:59 CET)

**Comment by Lothrazar** [comment]
it doesnt show the client particles or do anything like that apparently, but if its filled and scroll down to 1 tick it seems to grow pretty fast.  
![watrrr](https://user-images.githubusercontent.com/621529/153305332-695e1155-5e62-4fbe-a487-6fd33ed4db00.gif)
