### ISSUE TITLE
Does not restore items on Magma Anvil  - 1.16.5

### ISSUE THREAD

**Issue by Billetiado10** [PrinceOfAmber/Cyclic#2006]
Minecraft Version: 1.16.5

Forge Version: 32.2.20

Mod Version: Cyclic-1.16.5-1.5.13.jar

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

When charging with the magma anvil, the restored item cannot be obtained.

Log file link:

Video/images/gifs (direct upload or link): 
[Video Cyclic Error Bug](https://youtu.be/aYP0SfbRj6A)

![2021-12-30_13 33 57](https://user-images.githubusercontent.com/76263374/147779117-b8166b1c-9985-4922-9e3d-8e238c102c9f.png)
![2021-12-30_13 34 09](https://user-images.githubusercontent.com/76263374/147779119-88fa697a-3a9c-4ab9-9e44-8dc808dfa2f9.png)

**Comment by Lothrazar** [comment]
Thanks for the video, i do see it not repairing in your video.  in v1.5.13 i took this.

IS this in any type of questing modpack with lots of changes? There as an item data tag

cyclic:anvil_immune

That lets modpack devs force items to be non-repairable.   Default values are only a few. 

https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/resources/data/cyclic/tags/items/anvil_immune.json

**Comment by Billetiado10** [comment]
it's in a modpack with 116 mods, maybe it could be for another mod, but it didn't happen in previous versions

**Comment by Lothrazar** [comment]
Yeah, thats pretty weird.  Unless something breaks or changes durability still works when i test in 1.18 and 1.16

The code also checks "isRepairable() == true" on the item, so maybe if another mod is changing that, idk what or how or if but its just a guess. the anvil says if that check is false then im not allowed to repair
https://github.com/Lothrazar/Cyclic/blob/6cf1133df48dd1c0beb50bd78afb2f43946b752d/src/main/java/com/lothrazar/cyclic/block/anvilmagma/TileAnvilMagma.java#L106

![magma](https://user-images.githubusercontent.com/621529/160258248-b5dd6e36-c735-4ab2-bf71-05d7e2965e5e.gif)
