### ISSUE TITLE
Cant craft any item while playing on modded server

### ISSUE THREAD

**Issue by ShyAssassin** [PrinceOfAmber/Cyclic#2008]
Minecraft Version: `1.12.2`

Forge Version: `forge-1.12.2-14.23.5.2860-universal`

Single Player or Server: `Server`

Describe problem (what you were doing; what happened; what should have happened):
When in single player i am able to craft items such as item pipes but when on a server and i try to craft i am not able to craft any items from this mod

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/7797680/latest.log)

Video/images/gifs (direct upload or link): 
https://imgur.com/a/EUTTIzC

**Comment by Lothrazar** [comment]
log says that the mod was installed. idk what that black stuff is in the image, it looks like quartz but black. anyway JEI will show the recipes . log says ` Mod cyclicmagic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.20.8`
