### ISSUE TITLE
Excavate enchantment not working properly

### ISSUE THREAD

**Issue by yasterday** [PrinceOfAmber/Cyclic#2009]
Minecraft Version: 1.18.1

Forge Version: 39.0.9

Mod Version: 1.18.1-1.6.8

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
using Enchantment Descriptions mod, Mod Name Tooltip, FastLeafDecay, WorldEdit, Patchouli, CraftingTweaks, Balm, and AutoRegLib, enchanted a netherite pickaxe with Excavate V in Creative mode, switched to Survival mode, attempted to excavate an area of diorite, only one block was mined. Expected behavior was that entire area of diorite would be mined. Previously in Cyclic 1.16.5-1.5.11 as part of FTB Endeavor modpack, Excavate enchantment worked in both Creative and Survival.

Log file link:

[debug.log](https://github.com/Lothrazar/Cyclic/files/7798299/debug.log)

**Comment by Lothrazar** [comment]
fix on the way for 1.6.9
