### ISSUE TITLE
Bug in Void charm 

### ISSUE THREAD

**Issue by jenny3883** [PrinceOfAmber/Cyclic#2010]
Minecraft Version: 1.18

Forge Version: 

Mod Version: 
0.9.0
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Void charm is glitching. below -30 it respawns me to the top ( sends me up to y200)
Since the new update it goes down to -64 blocks. 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1996
