### ISSUE TITLE
Fluid cable immersive engineering crash

### ISSUE THREAD

**Issue by freopt** [PrinceOfAmber/Cyclic#2012]
Minecraft Version: 
1.16.5
Forge Version: 
36.2.22
Mod Version: 
1.5.13
Single Player or Server:
singleplayer
Describe problem (what you were doing; what happened; what should have happened):
I was editing the fluid pipe configuration connecting to an IE cloche, then the game just crashed
not sure which mod is problematic but decided to post here first

Log file link:
https://bytebin.lucko.me/fkCF79y1ug

Video/images/gifs (direct upload or link):

**Comment by metalshark** [comment]
TBH this looks like a bug in Immersive Engineering here:
https://github.com/BluSunrize/ImmersiveEngineering/blob/a7e9124380d4170956283ca10c9d1ead9cce2726/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/ClocheTileEntity.java#L295
and nothing to do with Cyclic.

That function is being called by:
https://github.com/BluSunrize/ImmersiveEngineering/blob/a7e9124380d4170956283ca10c9d1ead9cce2726/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/ClocheTileEntity.java#L101
passing in `2` as the type argument.

**Comment by Lothrazar** [comment]
As above, and as with this issue as well, immersive issue https://github.com/Lothrazar/Cyclic/issues/2030
