### ISSUE TITLE
Apple of lofty stature does not let me step up blocks

### ISSUE THREAD

**Issue by Small321** [PrinceOfAmber/Cyclic#2014]
Minecraft Version: 1.16.5

Forge Version: 36.2.22

Mod Version: Cyclic-1.16.5-1.5.11

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
After eating the apple of lofty stature I wasn't able to step up full blocks and still ran into them like you would without eating it.
Mod pack is All the Mods 6

Log file link:

Video/images/gifs (direct upload or link): https://www.youtube.com/watch?v=_NHI46rC308

**Comment by Lothrazar** [comment]
There must be somethign else in the modpack disabling or messing up step height, like forcing it off for everyone. I guess u have to report it to modpack, works fine with mod by itself and in some other packs
![bbb](https://user-images.githubusercontent.com/621529/160255620-233eabc6-6fae-4da6-85c2-85d54521e1b8.gif)
