### ISSUE TITLE
Cyclic mod breaking vanilla night vision

### ISSUE THREAD

**Issue by hornertom** [PrinceOfAmber/Cyclic#2018]
Minecraft Version: 1.18.1

Forge Version: 39.0.10

Mod Version: 1.6.9

Single Player or Server:Server

Describe problem (what you were doing; what happened; what should have happened):

I think your mod is breaking the vanilla Night Vision, 
Your night vision helmet is the only item that gives me night vision, i tried, gobber mod night vision, vanilla potion night vision, and even the /effect command, and none of them are working. 

Log file link: No log file

**Comment by Lothrazar** [comment]
what modpack or modlist do you have, that sounds like a weird issue.  i made a gif testing the effect command and the helmet just alone without a modpack 
![nightvis](https://user-images.githubusercontent.com/621529/149732357-1a8a0abb-0dde-4ab9-8f7c-13fb49a72f8f.gif)
