### ISSUE TITLE
Evaporation Generator won't burn fuel

### ISSUE THREAD

**Issue by cubesteak** [PrinceOfAmber/Cyclic#2019]
Minecraft Version:  1.18.1

Forge Version:  39.0,9

Mod Version:  Cyclic-1.18-1.6.7

Single Player or Server:  Single Player

Describe problem (what you were doing; what happened; what should have happened):
Set up an evaporative Generator and filled with water, but it will not take any fuel.  I can't tell from the src which fuel(s) it SHOULD take, so it is possible user error on my part.  That said, have tried every fuel that I can think of to attempt it - both manually as well as with pipes, etc.  The block UI seems to want some kind of bucket, but none work.  Apologies if this is the incorrect place to log such an issue.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
If I recall, it's powered by lava. Try a lava bucket.

**Comment by cubesteak** [comment]
> If I recall, it's powered by lava. Try a lava bucket.

Yeah, tried that, though TY for the reply!

**Comment by Lothrazar** [comment]
v1.6.8 , 1.6.9 have fixes for this

**Comment by cubesteak** [comment]
TY
