### ISSUE TITLE
Solidfication Chamber Problem in ATM6 to the Sky

### ISSUE THREAD

**Issue by XiNaru** [PrinceOfAmber/Cyclic#2025]
Minecraft Version: 
1.1.6.5
Forge Version: 
26.2.20
Mod Version: 
1.16.5-1.4.2
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
i want to automate the honey block production...
there are two recipes 
1 Stick
and 1 Stick in every slot

but now..the maschine stops after each produce cycle. can i fix that?
with bottles the same problem

Log file link:
no log file?

Video/images/gifs (direct upload or link): 

https://i.imgur.com/mbn319I.png
https://i.imgur.com/fc3qLg6.png
https://i.imgur.com/9Q1XrME.png

**Comment by Lothrazar** [comment]
Fixed in newest versions of the mod, and also recipes can support fluid tags as well
