### ISSUE TITLE
How to use the Crushing macerator?

### ISSUE THREAD

**Issue by Bolibompa1draken** [PrinceOfAmber/Cyclic#2026]
Minecraft Version: 1.18.1

Forge Version: Forge beta

Mod Version: 1.18.1

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): I can't figure out how to use the Crushing macerator. I prety sure my RF/T is 55 and i put raw porkshop in the machine but nothing is happening. Please help me.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by jstansel** [comment]
The new release from yesterday (Cyclic-1.18.1-1.6.10) fixed an issue with the crushing macerator after a world reload. Can you check if it fixes your problem?

**Comment by Bolibompa1draken** [comment]
> The new release from yesterday (Cyclic-1.18.1-1.6.10) fixed an issue with the crushing macerator after a world reload. Can you check if it fixes your problem?

It works thank you so much
