### ISSUE TITLE
Ender book can't be repaired

### ISSUE THREAD

**Issue by rkap5423** [PrinceOfAmber/Cyclic#2028]
Minecraft Version: 1.16.5

Forge Version: 36.2.21

Mod Version: 1.5.13

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Ender book can't be repaired, either by energy or ender pearls. The issue seems to be caused by the book having the anvil_immune tag attached to it

Log file link: Unable to get logs, but corroborated in discord #cyclic channel

Video/images/gifs (direct upload or link): Unable to get screenshot, but corroborated in discord #cyclic channel

**Comment by HalcyonSeas73** [comment]
The Ender Book can be repaired at a (vanilla) anvil using Ender Pearls.

**Comment by Lothrazar** [comment]
if you want to enable repairing in stuff like Magma anvil / powered anvil, a modpack could override the cyclic:anvil_immune item tag to unblock the book. Also modpack scripts could increase the book durability.

By default the requirement is yeah to use normal basic anvil with a pearl just like armor
![2028](https://user-images.githubusercontent.com/621529/152878470-5c3a100a-90a2-4d2b-b063-308c07bdd39f.gif)

**Comment by SeamusDonohue** [comment]
The "Cyclic Guidebook" states in the entry for "Ender Book": "Repair with energy or ender pearls".  The mention of "repair with energy" needs to be clarified or removed from the Guidebook, please.

In case it's relevant, I'm playing a singleplayer game with the Direwolf20 pack for Minecraft 1.16.5.  Forge version is 36.2.22 (slightly different from what rkap5423 reports using).  Cyclic version 1.5.13.
![Ender Book description](https://user-images.githubusercontent.com/24704643/227089993-cfad90aa-7cde-40ea-be65-b2be95afc83f.png)
Thank you for this mod, by the way!
