### ISSUE TITLE
Block Reach Enchant no longer working 

### ISSUE THREAD

**Issue by UnhallowedDeath** [PrinceOfAmber/Cyclic#2029]
Minecraft Version: 1.18.1

Forge Version: 39.0.59

Mod Version: 1.6.10

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): Currently I have a chestplate that is enchanted with Block Reach. The Enchant was working just fine at the time (01/23/22).  Between the time I finished playing yesterday and today the enchant no longer is working. I do not have any extended reach. 

Between sessions I had installed a couple Mods. I have since disable those mods and the enchant still does not work.  
I have Created a New instance with only Cyclic and JEI. No Change. Enchant still does not work.
I tried a new instance with only Cyclic installed with new instances and no change.
I tried rolling the Cyclic version back to version 1.6.9 with new instance. No Change
I tried rolling Forge Version back to 39.0.58 and 39.0.57 with new instances. No change

I have not been able to Track down a reason for the enchant not working at this time. I will try to see if there is any further information I can find and will post update if I find anything.

Log file link: There is no log file. 

Video/images/gifs (direct upload or link):

**Comment by UnhallowedDeath** [comment]
So a little bit of an update.  I found that the Enchant does work but only with chest pieces. Currently all armour and tools can be enchanted with it but it is only effective on the chest piece.  If the chest peice is the only thing it is supposed to work with could you please remove it as an enchant from all other armour and tools

**Comment by Lothrazar** [comment]
in mod v1.6.11 and forge v39.0.66, i was able to put the Block Reach book on elytra in survival with the anvil, and then with that equipped i could break and place blocks at range. at least woth no other mods installed it seemed to work.  

It should have been correctly restricted to yeah not legs or boots or helm, as you said in the second comment. the enchanting table RNG should only work on chest slot so ill check that out

**Comment by Lothrazar** [comment]
ah, way back in i guess 1.17 i messed up the port, and reach got registered as `  register(r, new ReachEnchant(Enchantment.Rarity.RARE, EnchantmentCategory.WEARABLE, ARMOR_SLOTS)`

which means all wearable slots . so yeah since thats alreayd out ill just fix it so it can work from any armor slot
