### ISSUE TITLE
Crash everytime i connect more than 5 seconds

### ISSUE THREAD

**Issue by WiRrZz** [PrinceOfAmber/Cyclic#2030]
Minecraft Version: 1.16.5

Forge Version: 32.2.22 

Mod Version: 1.16.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
everytime i tried to connect, i crash after few seconds

Log file link:

[latest.log](https://github.com/Lothrazar/Cyclic/files/7933628/latest.log)

Video/images/gifs (direct upload or link)

[crash-2022-01-25_13.34.40-client.txt](https://github.com/Lothrazar/Cyclic/files/7933659/crash-2022-01-25_13.34.40-client.txt)

**Comment by Lothrazar** [comment]
Looks like an immersiveengineering crash, should be reported to their tracker . if you can break the cloches in those areas with some editing program that should let the world reload

quote from log, as source of crash 

`
	at blusunrize.immersiveengineering.common.blocks.metal.ClocheTileEntity.sendSyncPacket(ClocheTileEntity.java:295) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.ClocheTileEntity$1.onContentsChanged(ClocheTileEntity.java:101) ~[?:?] {re:classloading}`
