### ISSUE TITLE
Placing Coal generator crashing

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#2031]
Minecraft Version: 
1.18.1
Forge Version: 
39.0.63
Mod Version: 
Cyclic-1.18.1-1.6.10.jar
Single Player or Server:
Both cause a crash
Describe problem (what you were doing; what happened; what should have happened):
Place down coal generator on server = immediate crash
Place down coal generator and then right click it in singleplayer = crash

Log file link:
[crash-2022-01-28_17.48.17-server.txt](https://github.com/Lothrazar/Cyclic/files/7962323/crash-2022-01-28_17.48.17-server.txt)

Video/images/gifs (direct upload or link):

**Comment by Gbergz** [comment]
Probably caused by the breaking change in forge. Try Forge 39.0.44 until it's fixed.

**Comment by jstansel** [comment]
Not sure if it can help you, but I am using the cyclic combustion generator (burns coal) in single player with no problem.

Forge version: 39.0.64
Cyclic version: 1.18.1-1.6.10
