### ISSUE TITLE
Sprinkler issue.

### ISSUE THREAD

**Issue by VermillionKingpin** [PrinceOfAmber/Cyclic#2032]
Minecraft Version: 1.18.1

Forge Version: 39.0.43

Mod Version: 
Cyclic-1.18.1-1.6.10

Single Player or Server: Sever via Shockbyte

Describe problem (what you were doing; what happened; what should have happened): I put the sprinkler on a watersource and it sucks it up, then I put another watersource down, but the sprinkler never works? Is this sprinkler not like the one in SF4? 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
it doesnt spin anymore as people complained about lag from it but yeah, when it grabs the water from below it slowly drains and spends the water, you can interact to see whats left (no gui). and it slowly grows stuff nearby .  the Terra preta soil or glass may be faster but smaller are
![spriii](https://user-images.githubusercontent.com/621529/153102453-96c1c6f8-ad50-4df4-b428-8e18dce1fa9d.gif)
a
