### ISSUE TITLE
Scythes [1.18.1]

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2033]
Minecraft Version: 1.18.1

Forge Version: 39.0.64

Mod Version: 1.6.10

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

**Scythe of Foraging:** 
- destroys Flowering Azalea Leaves, without dropping them
- Collects vanilla flowers, but destroys 2-block tall flowers like Lilac
     -Likely related, the Gardening Scythe has odd behaviour with Supplementaries' Flax Seeds (see photo); those faces show up on mature ones, then the growth % is listed as 0. Only occurs when right-clicked on directly, not if clicked on a block next to farms, for example. 
- Only collects Sweet Berries if directly right clicked on, not an area effect
- Does not collect Lime Carnation, Purple Tulip, Absalon Tulip (but will Cyan Rose)

**Tree/Brush Scythes:**
- Neither support Silk Touch; would like to be able to collect leaves/grasses with them.

Video/images/gifs (direct upload or link): 

https://media.discordapp.net/attachments/927745944324296735/935690712765321267/unknown.png?width=705&height=378

**Comment by Lothrazar** [comment]
Working on this now

- sweet berries - no changes, as these are an age based growing crop the Garden scythe already harvests an area for these

I should be able to fix the rest.  Silk touch on them would be a nice feature for whole leaf blocks yeah

**Comment by Lothrazar** [comment]
for both tall flowers and for flax seeds seems like the same problem,  multiblocks have a "half:lower / half:upper" blockstate property, but only upper has the blocks.  tool was harvesting lower first, got no blocks, and top had to either die or glitch out.  Changing to only harvest top half and ignore lower, so we get drops and lower just expires
