### ISSUE TITLE
Micro stuttering while using the packager - possibly recipie look up lag ?

### ISSUE THREAD

**Issue by starr274** [PrinceOfAmber/Cyclic#2034]
Minecraft Version: 1.18.1

Forge Version: 39.0.59

Mod Version: 1.18.1-1.6.0

Single Player or Server: SSP

Describe problem (what you were doing; what happened; what should have happened):
I was using the packager to convert sticks into timber frames, inserted by a vanilla hopper, and extracted to a chest via hopper,and began to get microstuttering, that stopped the moment I went creative and broke the packager block. I ran my profiler and got the results below

https://spark.lucko.me/UvdPvObPkg

image below incase of non existing page 
Log file link:

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/2853335/151734856-9732cf27-ab75-427b-a6f1-3355989c33a2.png)

**Comment by Lothrazar** [comment]
yeah for sure, i can see that .getItems() is an expensive calll and its being used in two places over and over. not only with silentchaos gear probably with other recipes too. i can reduce method coalls do that one from 5 times down to 1 or 2 , and make a release. each custom or individual Ingredients would have to be internally be optimized as well if possible
