### ISSUE TITLE
builder not working 

### ISSUE THREAD

**Issue by Leprekonich** [PrinceOfAmber/Cyclic#2037]
Minecraft Version: 1.12.2

Forge Version: forge-1.12.2-14.23.5.2860

Mod Version: Cyclic-1.12.2-1.20.11

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
All you said was 'not working' so idk what that means, no logs or pics. works as intended on servers just ran it on a forge 14.23.5.2847 server in Cyclic-1.12.2-1.20.11 
![2037 bbb](https://user-images.githubusercontent.com/621529/160305165-d9937761-7466-4ee5-b2e0-eac7814249bf.gif)
