### ISSUE TITLE
Ender Shelves break stack connection on moving

### ISSUE THREAD

**Issue by alyssacodes** [PrinceOfAmber/Cyclic#2038]
Minecraft Version:  1.18.1

Forge Version: 39.0.63

Mod Version: 1.18.1-1.6.10

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Breaking a ender shelf to reposition it somewhere else in the array of shelves.

S = Shelve C = Controller A/B = Shelf moved

SSCS**B**   ->   SSCS**A**
S**A**SSS   ->   S**B**SSS
SSSSS   ->   SSSSS

**Expected Result:**

Shelves would continue working as expected. Enchant stacks continuing to build as more enchants are added.

**Actual Result:**

- Shelves A and B still contain their enchantment stacks but no more enchants can be added to those stacks, any more of those enchants will start a new stack in an empty slot in those or any other shelves.
   - If the shelf had _Protection IV x3_ and you add another _Protection IV_ to the system it will not become _Protection IV x4_. You will end up with a new stack created in an empty shelf slot with _Protection IV x1_.

- You can remove all the items from shelves A and B and re add them to the system which is a work around but if you have a full shelf this can be time consuming.

**Comment by alyssacodes** [comment]
This bug seems to go further, upon logging back into my server today the stack connections on the entire system are broken. Any book added creates a new stack. I know no one has messed with the shelves since I set them up yesterday since it is just myself and a friend who play on the server and they did not play yesterday, the daily reboot was this morning.

**Comment by Lothrazar** [comment]
i wonder if the controller is in an unloaded chunk, and a shelf over a chunk boarder doesnt find it when rebooting , and then the controller loaded and received connections after that . 

Is there anything useful that could be put in a new shelf controller GUI if there was one. or maybe its enough to have the controller reconnect or re-validate when it gets interacted with. or periodically

**Comment by alyssacodes** [comment]
I don't think there is anything that would be useful in a controller gui. I think revalidating the connection. The ability to mass remove books or force a reconnection by replacing (picking back up and putting back down) the shelf in the the array would be nice.

**Comment by Lothrazar** [comment]
ive got a fix or at least an improvement for this. didnt do the repeated scan or any controller update actually, some little bugs. tested moving shelves with 0, 1, and multiple books and controller seems to find it better now. closing for now but i can reopen if i missed some spots
