### ISSUE TITLE
Ender bomb in FTB Presents Hermitcraft

### ISSUE THREAD

**Issue by EzeKiel42** [PrinceOfAmber/Cyclic#204]
Hello,

I was playing on a server with the FTB Prensents Hermitcraft pack with two of my friends, and i found an Ender Bomb VI in a chest. I brought it back home, in a crate, and after closing the crate's window, the server crashed.

Impossible to restart the server after that... The crate is from Actually Additions i think, and i don't understand why the game crashed that way...

Anyway, thanks for looking, and i hope that i could have some info about this ;)

**Comment by PrinceOfAmber** [comment]
Whats weird. Do you have a crash log for the client or server?  Logs for when it crashed the first time i mean.

Also when you say "Impossible to restart the server after that." what does this mean?

**Comment by PrinceOfAmber** [comment]
Closed because i tried and cannot replicate this. If it keeps happening or you have more info feel free to reopen.
