### ISSUE TITLE
Empty Ender Shelves returned to inventory form a new stack

### ISSUE THREAD

**Issue by alyssacodes** [PrinceOfAmber/Cyclic#2040]
Minecraft Version:  1.18.1

Forge Version: 39.0.63

Mod Version: 1.18.1-1.6.10

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Emptied and broke an Ender Shelf / Place an never used shelf and then break it and pick it up.

**Expected Result:**

The shelf to be added to the existing stack of empty shelves in my inventory.

**Actual Result:**

Shelves that were once placed never return to the original stack and instead create a second stack of just shelves that have been placed in the world.

**Comment by Lothrazar** [comment]
yeah this seems like a bug. should only be a new stack if its unique enchantment data not empty
