### ISSUE TITLE
Inaccessible Enchantments

### ISSUE THREAD

**Issue by ComputerErika** [PrinceOfAmber/Cyclic#2041]
Minecraft Version: 1.16.5
Forge Version: tested in 36.2.21 and 36.2.26
Mod Version:  1.5.13
Single Player

Many of the added enchantments are not appearing from the enchanting table or fishing
This leads them to not be accessible in survival, despite working if you create them in in creative

I tried getting these enchantments manually for I'd say a decent amount of time, but in case I also tested
mass enchantment gathering devices such as the "Enchantment Factory" and "Marine Fisher" from Industrial forgoing

the case could be I was very very unlucky in my manual enchants and the IF machines were not working
But I doubt this as I spent a good time trying to get each enchant, plus checked the config for the IF machines and their code

Then again, I could've missed something, or perhaps the forge enchantment system is wonky somehow

The missing/unobtainable enchants are as follows:
Gloom, Beekeeping, Block Reach, Step Height, Traveler, Venom, Life Leach, Mulit-Bow, and Auto Smelt

Later:
After further investigation of the Enchantment Factory from IF it seems to be acting wonky as it isn't giving protection to armor pieces? Going to put a bug report over there too just in case

**Comment by Lothrazar** [comment]
making changes that will be fixing this for 1.16
![gloom progress](https://user-images.githubusercontent.com/621529/160202631-ac3ea60b-a90a-482d-b7ef-1ad499426e60.png)

![ffx](https://user-images.githubusercontent.com/621529/160202676-27f2dc1f-07ed-4716-ac54-1e9d270eb86b.png)
