### ISSUE TITLE
Problem with Enchant Excavation

### ISSUE THREAD

**Issue by mgarst** [PrinceOfAmber/Cyclic#2043]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Mod Version: 1.20.3-1.20.11

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
When I`m playing Minecraft I get the message "an unknown problem occurred press ctrl + i". I found that the problem was the enchantment of the excavation thanks to the crash report, and then I turned it off in the mod config and now everything works. Please fix this issue in future releases.

Log file link:

[crash-2022-02-14_20.12.07-server.txt](https://github.com/Lothrazar/Cyclic/files/8068845/crash-2022-02-14_20.12.07-server.txt)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
v 1.20.12  on the way
