### ISSUE TITLE
MultiJump Enchantment

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2049]
**Minecraft Version**: 1.18.1
**Forge Version**: 39.0.79
**Mod Version**: 1.6.12
**Single Player or Server**: Single
**Describe problem (what you were doing; what happened; what should have happened)**: The MultiJump enchantment cannot be applied to boots. Additionally, if a mod that makes Elytra a Curios is used, MultiJump does not work. Otherwise, if the Elytra with MultiJump is in the chest slot, the enchantment works.
**Video/images/gifs (direct upload or link)**:
![Capture](https://user-images.githubusercontent.com/84727791/154558824-faa7aad2-a7fc-451e-984c-d75a51fe7318.PNG)

**EDIT:** This seems to be a duplicate of Issue #1980

**Comment by Lothrazar** [comment]
I remember this one now. in 1.17 i was going to make it elytra only but changed it back

It still was declaring itself as ARMOR_FEET  and EquipmentSlot.FEET, which used to cover anvil but theres more to it now i think 
  public static final ElytraLaunchEnchant LAUNCH = (ElytraLaunchEnchant) new ElytraLaunchEnchant(Enchantment.Rarity.RARE, EnchantmentCategory.ARMOR_FEET,   EquipmentSlot.FEET).setRegistryName(ElytraLaunchEnchant.ID);
  

https://github.com/Lothrazar/Cyclic/blob/f71b143b53bee8e7479d35293432cee3aafd4d25/src/main/java/com/lothrazar/cyclic/registry/EnchantRegistry.java#L39


https://github.com/Lothrazar/Cyclic/blob/aee648820848e619b297ffabdd7b83078d8116a2/src/main/java/com/lothrazar/cyclic/enchant/ElytraLaunchEnchant.java#L72

**Comment by Lothrazar** [comment]
ok found a fix
![2049updated](https://user-images.githubusercontent.com/621529/156839732-78eb343e-9194-48ac-95f5-b8092de3c2cd.gif)
