### ISSUE TITLE
Silk Touch/Scythes

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2051]
**Minecraft Version**: 1.18.1
**Forge Version**: 39.0.79
**Mod Version**: 1.6.12
**Single Player or Server**: Single
**Describe problem (what you were doing; what happened; what should have happened)**: 
- Despite having Silk Touch, the Brush Scythe continues to destroy grasses such as Ferns, Tall Grass, Vines, etc. 
- Vines are broken with Scythe of Foraging as well as Brush Scythe; Gardening Scythe is the one that harvests them.

**Comment by Lothrazar** [comment]
brush one needed an override to help out. ill test out vines a bit ![2051](https://user-images.githubusercontent.com/621529/156848787-886a20ed-b026-4b2b-a246-382a6e3ce2aa.gif)

**Comment by Lothrazar** [comment]
with this change, brush scythe + silk will drop the vines
