### ISSUE TITLE
Fluid Tank Fill Level Colour

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2052]
**Minecraft Version**: 1.18.1
**Forge Version**: 39.0.79
**Mod Version**: 1.6.12
**Single Player or Server**: Single
**Describe problem (what you were doing; what happened; what should have happened)**: 
Fluid Tank Fill Level, in-inventory, shows as Blue for water. However, this appears to be the only colour matching; vanilla Lava and cyclic Experience fill level both render as white.
![Capture](https://user-images.githubusercontent.com/84727791/154561054-a5dac7c8-40d3-49fb-92f2-b50b0369dcc5.PNG)
![Capture2](https://user-images.githubusercontent.com/84727791/154561072-53ae8a4f-6b73-4292-8db8-4d4b8b343723.PNG)

**Comment by Lothrazar** [comment]
Right now it pulls one of the colors from the Fluid obj itself, so for water it gets a blue. ill see if lava has a more orangey color. otherwise maybe an entry in client-config could get one

**Comment by Lothrazar** [comment]
For lava and for all fluids i can register a color. I just have to pick some based on the texture. 

For lava im thinking maybe https://www.colorhexa.com/ff8c00 .

Then for fluids in other mods, as long as they have the .color() registered in the Forge fluid attributes then it will pull that

**Comment by Lothrazar** [comment]
![liquid xp and lava](https://user-images.githubusercontent.com/621529/156680748-d3beebd4-ea64-4b8c-a584-e69415f182e1.png)
