### ISSUE TITLE
Nether and end ore spawn chance and vein size should be in config

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#206]
Hi,

Assembling a new pack at the moment and I visited the nether tonight to find nether ores *everywhere*! At least 20 blocks of diamond, a similar number of emerald blocks and even more lapis, all within sight of my portal. I feel this is a little too common since they're dropping full gems!

I like to suggest the following:
* Have the ore spawn rates configurable
* Lower the default spawn rate OR
* Have all your nether ores drop nuggets (which obviously will require you to add new gem nugget items that craft 3x3 into a single gem).

Cheers!

**Comment by PrinceOfAmber** [comment]
In 1.9 i did reduce spawn rate of diamond and emerald ore in the nether, but...
Yeah, it wouldnt be hard to put the spawn rate for all the ores in the config.

**Comment by xenoflot** [comment]
heh, I'm already running 1.9.2. We definitely have differing ideas on what's "too common" :-p
Looking forward to configurable version!

**Comment by PrinceOfAmber** [comment]
Yeah, it feels rare when im running around with iron armor. but once i have fire protection potions and a jetpack, yeah i can see how its a bit too easy to farm tons.

**Comment by PrinceOfAmber** [comment]
Added in 1.9.4.  Keep the reports coming :) https://minecraft.curseforge.com/projects/cyclic/files/2358564
