### ISSUE TITLE
"Block Reach" enchantment is fully broken.

### ISSUE THREAD

**Issue by DarkeyPoo** [PrinceOfAmber/Cyclic#2061]
Minecraft Version: 
**1.18.1**
Forge Version: 
**1.18.x - 39.0.66**
Mod Version: 
**Cyclic - 1.18.1 - 1.6.13 (latest as of 3/1/22)**
Single Player or Server:
**Single Player**
Describe problem (what you were doing; what happened; what should have happened):
**I was playing regular hardcore survival and kept noticing how Block reach (no matter what it was on) would not commit to reaching any further than vanilla reach. I went to test it in multiple scenarios and it seems to be fully dysfunctional.**

**Comment by Lothrazar** [comment]
What other mods do you have installed?  Are you playing in a large public modpack such as enigmatica?


When i install only

forge
JEI
curios
Patchouli
Cyclic


The enchant works just fine i tried with a few other small mods, tried on elytra, on chestplate.  heres a GIF recording below


Often what happens is one mod sets data on a player and the other just erases and overwrites it, like if one mod adds ten hearts and another one removes it.  so maybe some other mod is like "Well you dont have the magic icecream bluebery hat so im forcing your block reach back to normal, without actually being careful and checking first"


![reach](https://user-images.githubusercontent.com/621529/156516741-f6309d12-882d-457c-b67f-26def6dd0b97.gif)
