### ISSUE TITLE
[Compatibility] Botania & Cyclic Scythe of Foraging

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2064]
Minecraft Version: 1.18.1

Forge Version: 39.1.2

Mod Version: 1.6.14

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

Scythe of Foraging is able to harvest the "regular sized" Mystical Flowers in Botania, but when it comes to the Tall variant, nothing is dropped. Would this be a similar issue to the earlier Supplementaries one?
Item tags:
![Untitled](https://user-images.githubusercontent.com/84727791/156870177-84cc7b0e-1485-41a1-b5e3-86061fae6365.png)

**Comment by Lothrazar** [comment]
hmm. yeah i just tried the Tall Mystical Red flowers and other tall examples. 

In botania if i harvest those with my Bare hands i dont get any drops either. maybe its meant to be that way? or do the botania 2 tall flowers need a tool like shears maybe

**Comment by HalcyonSeas73** [comment]
I feel silly; according to the guidebook:
> Tall mystical flowers... can only be gathered with shears, but can be plucked for twice the amount of petals...

So it may be something that a (fixed?) brush...? scythe? Essentially ranged shears.

**Comment by Lothrazar** [comment]
It has the block tag of "minecraft:flowers" so it should get harvested by the scythe that gets flowers

**Comment by HalcyonSeas73** [comment]
> It has the block tag of "minecraft:flowers" so it should get harvested by the scythe that gets flowers

I thought it was related to the 'double flowers' issue fixed a while back, but botania only has them harvestable via shears as-is.
