### ISSUE TITLE
Ender shelf duplicate item

### ISSUE THREAD

**Issue by lmaret** [PrinceOfAmber/Cyclic#2068]
Minecraft Version: 16.5

Forge Version: 36.2.29

Mod Version: Cyclic-1.16.5-1.5.14

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Maybe it's me using the mod wrong but I'm having trouble with the ender shelf.
Books are duplicated if I insert them directly, when I add with controller after adding ender's shelf, weird things happen.

Video/images/gifs (direct upload or link): 

https://youtu.be/t9HtZjmobtI

**Comment by Lothrazar** [comment]
these blocks got some fixes in 1.18.1+ so ill see about pulling them over and looking at this
https://github.com/Lothrazar/Cyclic/commit/0a8d470c8c74cdeb1d805461f7ac18663183c14c https://github.com/Lothrazar/Cyclic/commit/ca60aca60cecf3a9c91b945f2a73694e15fc6b4d

#2040 #2038

**Comment by Lothrazar** [comment]
nevermind its the supplimentaries thing . still ez fix
