### ISSUE TITLE
No config option for the Viscous potion

### ISSUE THREAD

**Issue by ariosos** [PrinceOfAmber/Cyclic#207]
Using the HermitPack modpack, there doesn't seem to be a config option to disable the Viscous Potion.

**Comment by PrinceOfAmber** [comment]
Good point.  if you want to disable every other potion, then viscous would still be in the game.  Ill add a config to disable this.    So if viscous potions are disabled, and other potions like haste are enabled, they will just not have a recipe

**Comment by PrinceOfAmber** [comment]
Added in 1.9.5 https://minecraft.curseforge.com/projects/cyclic/files/2359852
