### ISSUE TITLE
Solid Ender Eye not working alongside Better Strongholds

### ISSUE THREAD

**Issue by N1ch0l2s** [PrinceOfAmber/Cyclic#2072]
Minecraft Version: 1.18.1

Forge Version: 39.1.2

Mod Version: 1.6.15

Single Player world.

Similar to #1517. Playing a custom pack. I crafted a Solid Ender Eye in a survival world and tried to use it but nothing happened. Did some testing to see what mods might be causing this. It seems since Better Strongholds replaces vanilla strongholds entirely, ID and everything, the Cyclic eye is unable to locate them. I have some example videos with and without the mod. Repurposed Structures works with it fine.

Video where only RS, Cyclic, JourneyMap and required coremods are installed: 
https://user-images.githubusercontent.com/32824550/158005691-66513bf5-a9e7-4f15-a18b-15473df13645.mp4

Video where RS, JourneyMap, Better Strongholds and required coremods are installed: 

https://user-images.githubusercontent.com/32824550/158006019-a7a46ae9-e46b-44c0-afa2-9dc6a63b7218.mp4

If the videos are insufficient I can provide some where the Eyes are put into a Click Machine.

**Comment by N1ch0l2s** [comment]
Embedded version of first video 

https://user-images.githubusercontent.com/32824550/158006041-fa98ec4f-f942-4afb-b52b-e476d5a2d18e.mp4

**Comment by HalcyonSeas73** [comment]
Sounds like an issue with Better Strongholds, rather than Cyclic, especially if BS replaces vanilla strongholds entirely.

**Comment by Lothrazar** [comment]
this may have been different in older versions of the two mods, but currently it uses the data tag minecraft:eye_of_ender_located to find any strongholds that are correctly registered in the data tags.  current versions they are now compatible

**Comment by Lothrazar** [comment]
![yung 2](https://github.com/Lothrazar/Cyclic/assets/621529/33da2e42-119b-4bb5-a0f9-bfad89603f7b)
