### ISSUE TITLE
Cable pathing issue

### ISSUE THREAD

**Issue by arconom** [PrinceOfAmber/Cyclic#2073]
Minecraft Version:  1.16.5

Forge Version: 36.2.28

Mod Version: 1.16.5-1.5.11

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

Cables work fine in a straight line from source to destination, but if there are multiple adjacent connected cables at any point in the path, the pathing handles poorly, causing the pipes' buffers to fill before checking if there is a valid endpoint to send the payload to.

The image shows  the kind of adjacency that triggers the erroneous pathing.  This can be observed with all three types of cables.

I think the cables would be improved by removing their internal inventory and instead only using them as a pathway between connected inventories.

Log file link:

Video/images/gifs (direct upload or link): 
![2022-03-12_17 05 17](https://user-images.githubusercontent.com/7938555/158040524-700a7e19-9b9a-454d-8428-36ffbf9d647a.png)

**Comment by Lothrazar** [comment]
yeah the flow is random at every intersection. so when its leaving the chest. going straight and going left are both valid options. kind of like the item stacks only have a visiblity of 1 distance away from them and yeah like you said doesnt path ahead and see the whole network and the end

**Comment by arconom** [comment]
A* should work well here.

**Comment by arconom** [comment]
Also this is a bug, not an enhancement.

**Comment by Lothrazar** [comment]
if i do another major rewrite it wont be in any existing versions, thats too game breaking for existing players and modpacks.  maybe minecraft 1.19/20 .  also current cable system has no "Pulling" or "routing" or "direction" concepts

**Comment by arconom** [comment]
This still isn't working properly.  I see power moving around randomly in the energy cables.  The same issue with all the cable types.  A* is the correct implementation for this.
