### ISSUE TITLE
Fluid cable ticking entity in Compact Machines Dimension

### ISSUE THREAD

**Issue by TheDarkPreacher** [PrinceOfAmber/Cyclic#2077]
Minecraft Version: 1.16.5

Forge Version: 36.2.31

Mod Version: cyclic-1.16.5-1.5.14

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): fluid cable placed in Compact Machines dimension was wrenched by player, crashed the server due to ticking block. Not sure if it was caused by just being in that dimension, or what they were trying to connect the fluid cable to that caused the ticking entity crash.

Log file link: https://pastebin.com/uXiXxTad

Video/images/gifs (direct upload or link):

**Comment by TheDarkPreacher** [comment]
Further update: fluid cable was attached to Cyclic Melting chamber, caused a ticking block crash when player looked at it. Turned on the Forge "remove erroring block" setting, no crash, player was able to break the fluid cable.

**Comment by Lothrazar** [comment]
ya it was trying to extract from something null .  That reminds me i need to do a 1.16 bug release this week, been focused on other versions too much.

**Comment by Lothrazar** [comment]
same as https://github.com/Lothrazar/Cyclic/issues/2054 , fixes on the way
