### ISSUE TITLE
Unable to extract lava from cauldron with fluid cable

### ISSUE THREAD

**Issue by chokoth** [PrinceOfAmber/Cyclic#2078]
Minecraft Version: 1.18.1

Forge Version: 39.1.0

Mod Version: 1.16.5

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Use dripstone to fill cauldron with lava. Fluid cable will not extract from the lava, even with a filter for lava is inserted and cable is explicitly on extract mode.

Log file link: No error, no log.

Video/images/gifs (direct upload or link):  Attached

![2022-03-19_11 08 45](https://user-images.githubusercontent.com/9523009/159128980-e7a272e0-b79a-4353-b107-7aa52660926f.png)

**Comment by Lothrazar** [comment]
i have added this, but it will only be in the 1.18.2 version :D

**Comment by chokoth** [comment]
Soooo a bunch of the mods I use aren't 1.18.2 compatible yet. No chance I can get you to do just _one more_ update for 1.18.1?

I mean I get it, supporting old code is very annoying...but what if I were to offer a _Pretty PLEASE_?
