### ISSUE TITLE
Quark also has an obsidian pressure plate, which renders lots of recipes dead

### ISSUE THREAD

**Issue by winsrp** [PrinceOfAmber/Cyclic#2079]
Forge Version:  1.18.1

Quark has an obsidian pressure plate (same recipe and everything), when crafting this item it is directed to the quark version of the item, which Cyclic doesn't pick up for its own recipes.

**Comment by Lothrazar** [comment]
oh yeah, since theres no data tag for obsidian plates.  Would it solve the problem i changed my default recipe for obsidian pressure plate? to what im not sure.  i guess a data pack or modpack could as well but i can also change the original if theres a good idea for it

**Comment by winsrp** [comment]
Why not just use normal obsidian blocks? or... make like a compact obsidian with 9 obsidian blocks., and use that? just throwing some ideas...
