### ISSUE TITLE
Uncrafting Grinder new help button crashing game

### ISSUE THREAD

**Issue by Rithenar** [PrinceOfAmber/Cyclic#208]
I have replicated this error several times with different pieces of armor. This happens mostly with Bronze Armor as the progress bar goes all the way non-stop. The only way to stop is by removing the armor from the uncrafter. If I hit the _?_ button then the game crashes. Crash log attached.
Something else interesting is that when I remove the bronze armor while the progress bar is filling (after several cycles), the bar does not reset but stays wherever it was when i removed the item,

[Crash Log](http://pastebin.com/aynjuCQE)

**Comment by PrinceOfAmber** [comment]
had another report of what looks like the same issue http://pastebin.com/v5eHrFQ6

**Comment by PrinceOfAmber** [comment]
Fixed in 1.9.4.  Keep the reports coming :) https://minecraft.curseforge.com/projects/cyclic/files/2358564
