### ISSUE TITLE
Fluid Tanks being destroyed when "picked up"?

### ISSUE THREAD

**Issue by Boolyman** [PrinceOfAmber/Cyclic#2080]
Minecraft Version:  1.16.5

Forge Version:  36.2.29

Mod Version:  1.5.14

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Are Cyclic Fluid Tanks supposed to be destroyed when broken?  As in, a player can not pick them back up after being placed?  I feel like that would be noted in the book or on the FTB Wiki if that was the case.  So I don't know if its a bug, or a mod interaction.  I am having this problem in the pack Rustic Waters II.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
yeah i just noticed that recently as well, 1.5.15 should have a fix
