### ISSUE TITLE
Missing registry data for network connection

### ISSUE THREAD

**Issue by Maklith** [PrinceOfAmber/Cyclic#2083]
Minecraft Version: 
1.16.5
Forge Version: 
forge-1.16.5-36.2.33
Mod Version: 
Cyclic-1.16.5-1.5.15
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Join the server ,but received this:
client log
![image](https://user-images.githubusercontent.com/42534870/161204602-beed7ef1-5e17-43c6-b839-c24644936144.png)
server 
![image](https://user-images.githubusercontent.com/42534870/161204684-69b9f6b1-2e40-461f-a057-f272322cca4e.png)

Log file link:
client
[debug.log](https://github.com/Lothrazar/Cyclic/files/8395062/debug.log)
server
[debug.log](https://github.com/Lothrazar/Cyclic/files/8395068/debug.log)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
forge issue not mod issue.  i think forge has a config for this. if not make sure the 
modlist
config files with contents

 are the same on server and client

**Comment by huzpsb** [comment]
Encountering the same problem. Can you remember what's the config exactly plz?
