### ISSUE TITLE
Wooden and Gold hoppers pickup range is about a block too wide

### ISSUE THREAD

**Issue by ChiefArug** [PrinceOfAmber/Cyclic#2085]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: 1.5.15

Single Player or Server: Singleplayer (Rustic Waters II)

Describe problem (what you were doing; what happened; what should have happened):
The wooden hopper picks up items from almost a full block away, which gets really annoying when using it in builds.
The description in JEI also says "Collects only from the are directly above the hopper", which I assume is meant to mean it only picks up stuff directly above it.

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/73862885/162554381-7c09dba1-32ff-46cf-b726-1b48f92ed2c7.mp4

**Comment by HalcyonSeas73** [comment]
It may be worth also mentioning this on the modpack author's page (whatever that may be) as well, so that they can update their Cyclic once this is fixed.

**Comment by ChiefArug** [comment]
This also happens with the gold hopper
