### ISSUE TITLE
Void Anvil can't remove enchant from books?

### ISSUE THREAD

**Issue by kriogenic** [PrinceOfAmber/Cyclic#2086]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Mod Version: 1.20.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I figured since the description says remove enchants from ANYTHING that it should do just that even for books. However if an enchanted book goes in, its spat back out as an enchanted book in the output slot

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/8491325/latest.log)

Video/images/gifs (direct upload or link): 
https://user-images.githubusercontent.com/389938/163450839-f43a3d38-83d4-4d56-87ad-e4f05e150cba.mp4

**Comment by Lothrazar** [comment]
Correct, in 1.12.2 the Void anvil works on only tools and not books.

The Unchant pylon works on both books and tools, so can take a book with multiple enchants and split it up 
![yes chant](https://user-images.githubusercontent.com/621529/189972114-1adb3d76-d0f8-4222-a493-76f600f1b890.gif)

![unch](https://user-images.githubusercontent.com/621529/189972128-0a4ecb25-1ced-495c-96e5-9e9213bf48bf.png)
