### ISSUE TITLE
B:SprinklerAnimationsAllowed=true

### ISSUE THREAD

**Issue by LameGaming** [PrinceOfAmber/Cyclic#2087]
B:SprinklerAnimationsAllowed=true

_Originally posted by @Lothrazar in https://github.com/Lothrazar/Cyclic/issues/1449#issuecomment-678838612_

where can i paste this or i just need to go in the config folder and find cyclic and add a new line and just paste this?

**Comment by HalcyonSeas73** [comment]
Yes, I imagine it should be the in cyclic configuration file. Try pasting it in, if it doesn't show up. Not much point in opening a new issue just to reference an old issue you're waiting for a reply on.

**Comment by Lothrazar** [comment]
I made one with it set to true and one set false to show it disabling the animation in mc 1.12.2

![sprink false](https://user-images.githubusercontent.com/621529/190005300-b8029ffc-cad7-418b-b98b-6e2b779a93c1.gif)
![false](https://user-images.githubusercontent.com/621529/190005301-f748a0b5-2256-462a-82c5-b3ca1ef0a1ca.png)
![with particles](https://user-images.githubusercontent.com/621529/190005303-c6017063-f214-4d94-b5a5-4415afb91a0b.gif)
