### ISSUE TITLE
1.16.5 Cyclic Energy Cable cannot power AE2 Energy Acceptor (compat)

### ISSUE THREAD

**Issue by Raidobw2** [PrinceOfAmber/Cyclic#2088]
Minecraft Version: `1.16.5`

Forge Version: `36.2.34`

Cyclic Version: `Cyclic-1.16.5-1.5.15.jar`
AE2 Version: `appliedenergistics2-8.4.7.jar`

Single Player or Server: Singleplayer

### Describe problem (what you were doing; what happened; what should have happened):
The Cyclic Energy Cable cannot power the Energy Acceptor from Applied Energistics;
Relayed from FTBTeam/FTB-Modpack-Issues#728
Thank you in advance!

### Log file link:
Nothing in logs, neither debug.log

### Video/images/gifs (direct upload or link): 
Observe that the terminal is not lit up and the energy cell is not being charged up (texture becomes more colorful when charged). The cable is extracting from the generator configured with the Wrench.
![image](https://user-images.githubusercontent.com/17010632/164103521-764cb1da-7a35-424a-9011-4425219e3c4b.png)

**Comment by Lothrazar** [comment]
the cables accepts and outputs standard Forge Energy (RF), so if THEIR decided not to be compatible theres nothing i can do. maybe you could open a bug on their tracker

**Comment by Raidobw2** [comment]
Ahh I see, thanks for the info! Unfortunately I've checked and AE2's 1.16.5 version is now unsupported. I'll make a short test in 1.19 instead with both your mods and report to AE2 in the recent version in that case

**Comment by Raidobw2** [comment]
It looks like this has been fixed in 1.18+ by something, so no worries. Thanks for your help, glad this interaction could be fixed! Have a good weekend as well
1.18.2 `appliedenergistics2-11.1.4.jar` & `Cyclic-1.18.2-1.7.5.jar`
![image](https://user-images.githubusercontent.com/17010632/180571528-5e65325b-a122-4fc8-8341-c670810a9cc7.png)
