### ISSUE TITLE
1.16.5 fluid pipe server crash 

### ISSUE THREAD

**Issue by SunnyMenkov** [PrinceOfAmber/Cyclic#2090]
Minecraft Version:
1.16.5

Forge Version:
36.2.26 server

Mod Version:
Cyclic-1.16.5-1.5.15.jar

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Crash after fluid pipe placed

Log file link:

[crash-2022-04-24_10.15.54-server.txt](https://github.com/Lothrazar/Cyclic/files/8549439/crash-2022-04-24_10.15.54-server.txt)
[crash-2022-04-24_09.59.42-server.txt](https://github.com/Lothrazar/Cyclic/files/8549440/crash-2022-04-24_09.59.42-server.txt)
[crash-2022-04-24_10.08.24-server.txt](https://github.com/Lothrazar/Cyclic/files/8549441/crash-2022-04-24_10.08.24-server.txt)

Video/images/gifs (direct upload or link):

**Comment by fcojocaru90** [comment]
Same thing happened to me, i am playing the modpack SkyColonies Ultimate Pack if it helps
[crash-2022-05-04_22.24.07-server.txt](https://github.com/Lothrazar/Cyclic/files/8627786/crash-2022-05-04_22.24.07-server.txt)

**Comment by pku6h** [comment]
It happens to me too

**Comment by BatmansOmega** [comment]
I had a similar issue, the only difference i used  a wrench on the pipe after it was placed.

**Comment by jeremyng353** [comment]
> I had a similar issue, the only difference i used a wrench on the pipe after it was placed.

Same issue, but it only crashes in multiplayer. Doesn't crash in singleplayer. I'm playing SkyFactory One with all of the mods updated except for Bongo.

**Comment by jeremyng353** [comment]
It's a Java 14 issue. I switched from Java 14 to Java 1.8 on the server and I no longer crash when exporting fluids with the cables.

**Comment by Lothrazar** [comment]
yes, it seems to not happen on java 8 only 9 and up. i guess.
I was using java 17... Please try the new 1.5.17 for this, i found a world with the same crash and made some progress https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3853310
