### ISSUE TITLE
[1.18.2] Solidification Chamber Has No UI When A Fluid Tank Is Placed Nearby

### ISSUE THREAD

**Issue by jkwphysics** [PrinceOfAmber/Cyclic#2091]
Minecraft Version: 1.18.2
Forge Version: 40.1.0
Mod Version: 1.6.18
Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Solidification Chamber no longer provides access to GUI (and acts like a fluid tank according to One Probe) when a Fluid Storage Tank is placed nearby.  The tank doesn't even have to be adjacent, just in a nearby chunk.  Breaking the tank restores access to the solidification chambers UI.  While the tank is placed, right clicking on the chamber only gives a fill level "0/64000", same as the tank.

Log file link:
No log apparently associated with these actions.

Video/images/gifs (direct upload or link): 
https://youtu.be/G7OG6bluIWw

**Comment by HalcyonSeas73** [comment]
Update your Cyclic, this was fixed in a more recent version
