### ISSUE TITLE
[1.18.2] Filter Card Clearing

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2094]
Minecraft Version: **1.18.2**
Forge Version: **40.1.16**
Mod Version: **1.7.0**
Single Player or Server: **Single**

Describe problem (what you were doing; what happened; what should have happened):

Despite removing everything from the filter card, the tooltip of the filter card still gives the original first item; i.e. it isn't cleared. 

![Untitled](https://user-images.githubusercontent.com/84727791/167200375-bed1f48c-5548-4472-8cdf-1f284e1a4556.png)

**Comment by Lothrazar** [comment]
updating to hide tooltip if count is zero. adding _wipenbt.json recipes to match other data cards
