### ISSUE TITLE
[1.18.2] Multi-Jump enchantable on more than just boots/elytra

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2099]
Minecraft Version: **1.18.2**
Forge Version: **40.1.16**
Mod Version: **1.6.8-1.7.0**
Single Player or Server: **Single**

Describe problem (what you were doing; what happened; what should have happened):
Multi-Jump 1, 2, and 3 are all enchantable on more than just boot-items and the Elytra. The description might need to be updated, if this is intentional.

Video/images/gifs (direct upload or link): 

![Untitled](https://user-images.githubusercontent.com/84727791/167209033-0bb48ea6-ad6c-41c4-b218-897da767b807.png)

**Comment by nexonerr** [comment]
This issue doesn't seems to have been closed even though it was fixed in #2148?
