### ISSUE TITLE
Wooden hopper improperly handles item stacks

### ISSUE THREAD

**Issue by NekoSpirits** [PrinceOfAmber/Cyclic#2102]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: 1.5.15

Single Player or Server: Singleplayer and Server (Rustic Waters II)

Describe problem (what you were doing; what happened; what should have happened):
The wooden hopper tries to correct the amount in a stack, if the stack that it collected was greater than one. What should happen is the stack should update properly. It also instantly processes the stack of items, which may also be a bug.

Video/images/gifs (direct upload or link):
https://user-images.githubusercontent.com/20034469/167861240-2d953403-5843-4209-a180-bc04eb6e5edc.mp4

**Comment by Lothrazar** [comment]
confirmed not to occur in 1.18.2

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4065241  1.16.5-1.5.20
