### ISSUE TITLE
Wrenching a Fluid Cable causes crash. Restarting causes crash due to ticking entity

### ISSUE THREAD

**Issue by ZiphonOfficial** [PrinceOfAmber/Cyclic#2103]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.34

**Mod Version:** 1.5.15

**Single-Player or Server:** Server

Describe problem (what you were doing; what happened; what should have happened):
After placing fluid transfer pipes and attempting to set one end to extract, the server immediately crashed upon using the wrench. When trying to restart, the server encounters a fatal crash related to a ticking entity and the entity is labeled as the pipe that caused the crash (the crashlog also provides the coordinates of the "ticking entity") 

The bug does NOT happen in Single-Player (so all's good there <3)

**Log file link:**
[](https://pastebin.com/Vzy78rMt)

**Video/images/gifs (direct upload or link):** 
It was so sudden and out of the blue, if I had a video I would link one. If requested I will provide a video and information.
Modlist is in crashlog.

**Comment by Fabl0s** [comment]
I think I just observed a similar if not the same Issue with the Fuild Cable...

Interestingly the Server did not Crash and just kept generating 10GB of Logs in an hour with Crash Reports in the latest.log
(Here is a Log we tried on recreating the behavior... [Directory](https://files.fablos.net/minecraft/templog/)

**Comment by ZiphonOfficial** [comment]
> 

Interesting. What do you have your max-tick-time set to in server.properties?

**Comment by Fabl0s** [comment]
@ZiphonOfficial It's set to 0

**Comment by ZiphonOfficial** [comment]
So, if your max-tick-time is set to 0 or lower, what will happen is it will allow a tick to last an infinite amount of time, thus never allowing the server to fully crash, but still creating logs.

**Comment by TigerWalts** [comment]
I have a server that has also run into this:

- https://pastebin.com/amyUnDJM

The stack trace is the same as for this issue:

- https://github.com/Lothrazar/Cyclic/issues/2054

**Comment by Caldoric** [comment]
Just had this happen to me tonight, on a server I'm running. One of my players tried to wrench some cyclic pipe or cable, can't remember which, and now the server freaks out whenever anyone gets close to the chunk where the Event took place. My own account is now stuck in a chunk near the epicenter, too...

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3853310  

https://github.com/Lothrazar/Cyclic/issues/2090
https://github.com/Lothrazar/Cyclic/issues/2118
