### ISSUE TITLE
[1.18.2] Crystalised Obsidian Armour only has 30 dura and no config option

### ISSUE THREAD

**Issue by Hxrlio** [PrinceOfAmber/Cyclic#2109]
Minecraft Version: 1.18.2

Forge Version: 40.1.14

Mod Version: 1.7.0

Single Player or Server: Probably both, but singleplayer in this case

Describe problem (what you were doing; what happened; what should have happened):
pricked armour on a cactus, became 29/30 dura, seemed odd since it's referred to as being superior than netherite, and the tools have 6k dura. Wanted to change it in the config but there is no such option.

Log file link:
Nah I think I will pass lol it's not really relevant

Video/images/gifs (direct upload or link): 
Not really relevant either

**Comment by mpbb** [comment]
I have noticed a similar issue with all emerald and obsidian armor and tools. They have inconsistent durability, damage and armor. I believe the cause is the same as this issue.

Perhaps the config for these items could be ported up.
