### ISSUE TITLE
[1.16.5] Fluid cable crashing game

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [PrinceOfAmber/Cyclic#2118]
Minecraft Version: 1.16.5

Forge Version: 36.2.34

Mod Version: Cyclic-1.16.5-1.5.15.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Placing the fluid cable, crashes the entire game. After that game can't be loaded anymore. Have to disable the mod (removing everything Cyclic-related from the world), load game, exit game, enable mod, load game.

Log file link: https://pastebin.com/RyXtLBeu

**Comment by TeamRustic** [comment]
Having a similar issue on my server using same versions. Players crash when trying to visit another players base then can't rejoin without insta crashing. Log: https://pastebin.com/JuN4Fxex

**Comment by Lothrazar** [comment]
Please try the new 1.5.17 for this, i found a world with the same crash and made some progress https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3853310
