### ISSUE TITLE
[1.12.2] some villager get killed when spawn by fall damage

### ISSUE THREAD

**Issue by quentin452** [PrinceOfAmber/Cyclic#2123]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Mod Version: Cyclic-1.12.2-1.20.12

Single Player:

Describe problem (what you were doing; what happened; what should have happened): some villagers appear killed by fall damage (appear in the air)

Log file link:
[latest.log](https://github.com/Lothrazar/Cyclic/files/8914284/latest.log)

Video/images/gifs (direct upload or link): 

villager spawn in air : https://i.imgur.com/kUi1DfL.png
villager get killed : https://i.imgur.com/mnvNM4u.png

mod list:

villagernames_1.12.2-3.4
Cyclic-1.12.2-1.20.12
collective-1.12.2-3.0
this bug appears even if I only use cyclic

**Comment by Lothrazar** [comment]
Sadly not much i can do about that, this mod doesnt do any extra spawning code or rules, it just registered the villager type as "i exist and can spawn with villages in the world".  if the worldgen has lots of cliffs around or something happens thats gotta be something goin on but idk what it could be
