### ISSUE TITLE
Redstone Clock can't be disabled anymore?

### ISSUE THREAD

**Issue by FuzzyThailand** [PrinceOfAmber/Cyclic#2125]
Minecraft Version: 1.18.2

Forge Version: 40.1.48

Mod Version: 1.7.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened): Redstone clock can't be disabled. 

Log file link: n/a

Video/images/gifs (direct upload or link):  n/a

**Comment by Lothrazar** [comment]
you can disable the recipe with data packs as well as hiding the item from JEI. i think this is the normal thing modpacks do? should work fine
