### ISSUE TITLE
Problem with Creating Crystallized Obsidian, and Viewing Recipe

### ISSUE THREAD

**Issue by Floating8Tres** [PrinceOfAmber/Cyclic#2134]
Minecraft Version: 1.18.2

Forge Version: 40.1.0

Mod Version: 1.7.2

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
I tried looking for the Crystallized Obsidian and Amber recipes in JEI and the Cyclic guidebook but I found only an explanation along the line of 'you can create it in the solidification chamber' without mentioning the recipe.
More importantly, I couldn't make Crystallized Obsidian (I used both recipes: obsidian, crystalized amber, then chorus fruit with liquid slime; and tried obsidian, crystalized amber, then wither rose with liquid slime; slime; _EDIT: I also tried the recipe mentioned here #1925_). None of the recipes worked. I saw the issue raised (here #2084) so I tried deleting all the mods and datapacks but to no avail. I tried starting a new creative world and the issue is still present :\

This is the recipe and setup I tried:
![Screenshot (264)](https://user-images.githubusercontent.com/109096253/179347940-97cfc32e-743b-4444-8861-527c7ebc266b.png)

This is what shows in the Cyclic Guidebook:
![Screenshot (267)](https://user-images.githubusercontent.com/109096253/179347936-382d4339-544d-408a-8556-fa44c29b9a28.png)

I've tried the recipes in an older version of Minecraft about a year ago and it was working. Any idea what could be causing it?

Thanks in advance!

**Comment by Th3C0D3R** [comment]
I have the recipie in 1.18.2 and its working also it shows correct in JEI. but I don't need chorus fruit nor wither rose. this is my recipie from JEI. Guidebook is the same as yours

![grafik](https://user-images.githubusercontent.com/7798500/179296377-c48dead3-6aee-4052-82b1-c7a744543d7d.png)

**Comment by Floating8Tres** [comment]
> I have the recipie in 1.18.2 and its working also it shows correct in JEI. but I don't need chorus fruit nor wither rose. this is my recipie from JEI. Guidebook is the same as yours
> 
> ![grafik](https://user-images.githubusercontent.com/7798500/179296377-c48dead3-6aee-4052-82b1-c7a744543d7d.png)



YOUR RECIPE WORKED!! Finally T_T

There's still the issue of the guidebook not showing the recipe, and also in JEI it shows exactly what's in the guidebook, i.e. just a general description without a recipe. If I click on the first bar in the box (where it says "Solidification Chamber" in your picture), it'll show tabs of every machine\block and what you can craft with it, but I don't see the solidification nor melting chambers. Not sure if it's JEI or if it's related to the guidebook, or something else entirely.

**Comment by Lothrazar** [comment]
yeah the 1.16 recipes were different than 1.18.2. So

(A) i will look into adding these recipes to guidebook to show items and fluid etc. melter and other recipe types dont show either
(B) maybe adding some alternate recipes to be similar to old versions were? not sure, i like using amethyst. maybe both at different costs.  

i took some screenshots of 1.16.5 version
![116 old recipes](https://user-images.githubusercontent.com/621529/179313844-34300ece-dc1a-4921-b180-14ae3ba0762a.png)
![116 amber](https://user-images.githubusercontent.com/621529/179313846-5e2413c9-15db-4dd3-8331-c44ef85c95a6.png)
