### ISSUE TITLE
Uncrafting Grinder cannot Uncraft dyes

### ISSUE THREAD

**Issue by jbuffman** [PrinceOfAmber/Cyclic#2137]
Minecraft Version: 1.18.2

Forge Version: 40.1.0

Mod Version: Cyclic-1.18.2-1.7.0

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):

I’ve been trying to use the Uncrafter to uncraft dyes and some other items. The other items share way to craft so I wasn’t really worried but then I couldn’t uncraft any Minecraft dye and don’t know if there’s a way to fix this.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
Dye items are blacklisted by default in `cyclic.toml`, under the `[cyclic.blocks.uncrafter]` heading:
`#ITEM IDS HERE.  Block ALL recipes that output this item, no matter which recipe they use`
`ignore_list = ["minecraft:elytra", "minecraft:tipped_arrow", "minecraft:magma_block", "minecraft:stick", "minecraft:*_dye", "spectrite:spectrite_arrow", "spectrite:spectrite_arrow_special", "techreborn:uumatter", "projecte:*"]`

**Comment by Lothrazar** [comment]
above comment is correct, thanks Halcyon as always. default config blacklists many matching recipes with "minecraft:*_dye"
