### ISSUE TITLE
[Feature Request] Allow Home Command to Run in Functions

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#2138]
Minecraft Version: 1.18.2

Forge Version: 40.1.68

Mod Version: 1.7.4

Single Player or Server: Both

Hey Loth, 

Currently `/cyclic home` can not be run in an .mcfunction file. Would you consider allowing it to do so? This would be a big help to get the player back to spawn when needed via functions.

Thanks!

**Comment by Lothrazar** [comment]
yeah looks like an easy change, its checking for perm level 3 when it should check for 2 (command blocks and functions are 2) . home and some others will have to change to add player targets , maybe 'hunger random' and 'add' like scoreboard

**Comment by Lothrazar** [comment]
For example, right now /cyclic home only works on players and it does a TP on current player. Upgrade could be 


/cyclic home [ tp | reset | save | set ] @p 

where tp is teleport, reset clears it, save uses players position and sets it as home. and set can take x/y/z . uses home for players relative dimension/level they are currently in
so examples would be like this, what do you think?

/cyclic home set @p 2 3 -5
/cyclic home tp @p 
/cyclic home reset @p 
/cyclic home save @p

**Comment by Lothrazar** [comment]
let me know how it works out or if you need changes! 

I was too lazy to make documentation but examples are in the changelog https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3895500
