### ISSUE TITLE
EnderIO Item Cable + controlled miner = CRASH

### ISSUE THREAD

**Issue by Natchesprout** [PrinceOfAmber/Cyclic#214]
So the EnderIO item cable crash game and server  and  my map can't load anymore ;/

**Comment by PrinceOfAmber** [comment]
there is an option in forge to delete ticking tile entities.

Go to config/forge.cfg and there is a line there

    B:removeErroringTileEntities=false

change that to true.

If I am correct, that will stop these errors from happening by deleting whatever block is causing the crash.

Do you have a log of the crash so i can look into it? Either what shows up in your MC launcher, or in logs/latest.log

**Comment by Natchesprout** [comment]
Here is the Crash report of the server
[crash-2016-12-24_18.06.15-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/672261/crash-2016-12-24_18.06.15-server.txt)

Thank you

**Comment by PrinceOfAmber** [comment]
Thanks that log is exactly what i needed

**Comment by PrinceOfAmber** [comment]
Fixed in build 1.9.6 https://minecraft.curseforge.com/projects/cyclic/files/2360370 

Thanks for reporting it
