### ISSUE TITLE
[1.19.1] Crash when accessing controls menu, also multiple options reset each start.

### ISSUE THREAD

**Issue by Gbergz** [PrinceOfAmber/Cyclic#2140]
Minecraft Version: 1.19.1

Forge Version:  42.0.1

Mod Version: 1.19-1.7.6 | https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3905454

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Trying to enter the Controls menu crashes the game to desktop.

Also audio levels and some other settings reset each time the game boots, music volume etc.
But that could just be tied to the crash.

Log file link: https://gist.github.com/Gbergz/4ffc49dd65fa9a7b31880de2779d6b79

Video/images/gifs: 
![image](https://user-images.githubusercontent.com/26634554/181760396-c9946cb5-4df5-4803-a2fd-ef4c4ae45eff.png)

**Comment by Lothrazar** [comment]
yep thanks for reporting so quick https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3905985
