### ISSUE TITLE
JEI does not recognize Workbench and all the craftingtables on a stick as an inventory

### ISSUE THREAD

**Issue by Scha7ten** [PrinceOfAmber/Cyclic#2141]
Minecraft Version: 
1.16.5
Forge Version: 
36.2.5
Mod Version: 
1.16.5-1.4.2
Single Player or Server:
Single Player
Describe problem (what you were doing; what happened; what should have happened):
Crafting Table on a Stick (all versions of it) and workbench are not working with JEI. There does not appear a plus when looking at a recipe in JEI while using any of the above mentioned.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
Potentially related, with the latest Cyclic (1.7.6), the following shows up in my logs:

`[11:43:41] [main/WARN] [mixin/]: Error loading class: com/lothrazar/cyclic/item/craftingsimple/CraftingStickContainer (java.lang.ClassNotFoundException: com.lothrazar.cyclic.item.craftingsimple.CraftingStickContainer)
`

**Comment by Lothrazar** [comment]
Resolved in 1.16.5-1.5.18+
