### ISSUE TITLE
Curios equipment (accessories) seem to not work

### ISSUE THREAD

**Issue by krjencik** [PrinceOfAmber/Cyclic#2143]
Minecraft Version: 
1.19.1
Forge Version: 
42.0.1
Mod Version: 
1.7.8
Single Player or Server:
Single Player
Describe problem (what you were doing; what happened; what should have happened):
it looks like some of the curios equipment doesnt work... Im trying ring of luck in creative, and i dont think it gives better loot ( in a village chest were only apples, oak saplings and some bread)

water breathing charm doesnt work at all (the bubbles go out...)

Log file link:
It didnt crashed

Video/images/gifs (direct upload or link):

**Comment by krjencik** [comment]
p.s.: im using repurposed structures mod, if that changes anything

**Comment by krjencik** [comment]
maybe it works... : water breathing charm seems to work , im just getting one hit, but thats probably because of project mmo mod...
and the luck: im using repurposed structures mod...

**Comment by krjencik** [comment]
im confused

**Comment by Lothrazar** [comment]
Yep for water breathing charm, its kind of a lie it lets the bubbles run out. but. then you just take zero drowning damage. kind of opposite of water breathing potion :)
