### ISSUE TITLE
[1.19+] Broken Enchantments (auto_smelt loot modifier)

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2148]
Minecraft Version: **1.19/1.19.1**
Forge Version: **41.1.0/42.0.2**
Mod Version: **1.7.8**
Single Player or Server: **Single**

Describe problem (what you were doing; what happened; what should have happened):
- Autosmelt is broken; doesn't show up in JEI 
(relevent log snippet: `[14:09:22] [Render thread/WARN] [ne.mi.co.lo.LootModifierManager/]: Could not decode GlobalLootModifier with json id cyclic:auto_smelt - error: Unknown registry key in ResourceKey[minecraft:root / forge:loot_modifier_serializers]: cyclic:auto_smelt`)
- Multi-Jump doesn't work, and can be applied to all armour, not just boots and elytra. ( #2099 )
- Ender 1/2/3 doesn't consume a sword's durability

**Comment by Knight1night** [comment]
This might be a dumb problem, but multi-jump doesn't work for me too. Has there been a solution to this problem or have I missed something obvious because the linked thread doesn't mention any fix.

**Comment by HalcyonSeas73** [comment]
> This might be a dumb problem, but multi-jump doesn't work for me too. Has there been a solution to this problem or have I missed something obvious because the linked thread doesn't mention any fix.

The linked thread was to indicate it was an issue in **1.18**, this one is for **1.19**. 1.18 has since been fixed (not that I've had time to test it).

**Comment by Knight1night** [comment]
So does that means the enchantment is just broken for 1.19. My problem is the enchantment completely not working, not just it being applicable on all armor. In my case, even if you have multi-jump III you can only jump once. I tried it both on a server and a single player world. The results are the same.
