### ISSUE TITLE
[1.19+] "Cyclic Flight" Potion

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2149]
Minecraft Version: **1.19/1.19.1**
Forge Version: **41.1.0/42.0.2**
Mod Version: **1.7.8**
Single Player or Server: **Single**

Describe problem (what you were doing; what happened; what should have happened):
A "cyclic flight" effect is listed as a potion, but is improperly titled in JEI.

Video/images/gifs (direct upload or link): 
![Untitled](https://user-images.githubusercontent.com/84727791/182937249-4aa075e0-f5fc-44a0-b4a9-f294542383d4.png)
![Untitled2](https://user-images.githubusercontent.com/84727791/182937306-dcd3b6ab-a0db-492a-8af9-545a6ea0b13f.png)
![Untitled3](https://user-images.githubusercontent.com/84727791/182937331-39b158f6-b52a-4d43-a06c-b154656c025b.png)

**Comment by Intipablo** [comment]
This also occurs in 1.18.2 latest version (1.7.6)

![Screenshot 2022-08-14 133744](https://user-images.githubusercontent.com/19776887/184521450-c48f2b04-72bf-4a99-9917-4f6fa60b0eb0.png)
