### ISSUE TITLE
Where is the Peat Generator???

### ISSUE THREAD

**Issue by ElFamosoKiller** [PrinceOfAmber/Cyclic#2150]
Minecraft Version: 1.18.2

Forge Version: 40.1.69

Mod Version: 1.7.6

Single Player or Server: in any

Describe problem (what you were doing; what happened; what should have happened):

peat generator does not exist inside the mod, what do i do with the peat farm???
please put the peat generator, is essential

Log file link:

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/110687786/183125481-0a4bd66f-611e-41c9-864c-fb14cb3bdbbc.png)
![image](https://user-images.githubusercontent.com/110687786/183125558-13648fcc-cb50-4cde-8bab-8ca9582999f4.png)
![image](https://user-images.githubusercontent.com/110687786/183125691-88492ff3-24d4-4e9f-a12e-0e5659afb42c.png)
![image](https://user-images.githubusercontent.com/110687786/183125784-209ce360-0ecd-4be5-92b4-dfda3a34ac7a.png)

**Comment by HalcyonSeas73** [comment]
It's been renamed to the Material Generator.
