### ISSUE TITLE
Dupe bug with item user (1.18.2 lava bucket from cauldron)

### ISSUE THREAD

**Issue by Kn1nJa** [PrinceOfAmber/Cyclic#2153]
Minecraft Version: 1.18.2

Forge Version: Tested with both 40.1.67 and 40.1.69

Mod Version: Tested with both 1.18.2-1.7.2 and 1.18.2-1.7.6

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

1. Set up item user facing cauldron (either with lava already or under a dripstone)
2. Supply item user with power
3. put >1 empty buckets in item user (I tested with 2)
4. enable item user either by lever or by changing mode to ignore redstone
5. item user uses an empty bucket on lava in cauldron (one empty bucket remains in item user's inventory)
6. lava buckets continually pop out of item user after a small delay

Log file link:

[latest.log](https://github.com/Lothrazar/Cyclic/files/9277653/latest.log)

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/110789605/183312689-a7a97573-ddb1-4e69-b35d-8310bd0499e3.mp4

**Comment by HevyMusic** [comment]
Version: Cyclic-1.18.2-1.7.3
Minecraft: 1.18.2
Forge: 40.1.67
SP/MP: Both
Modpack: FTB Direwolf20 1.18

Description:
Same as above but with a "Tinkers Construct" "Seared Casting Basin".
Allows you to dupe extremely high quantities of blocks in seconds.
Example Video: https://streamable.com/9ovyab

**Comment by JakeMoe** [comment]
I'm seeing similar in DW20 1.18.  I'm inserting potions into an Ars Nouveau Potion Jar; the fluid inserts, but then I get stacks of empty bottles continuously popping out of the Item User.

**Comment by Lothrazar** [comment]
thanks for the report, in the latest version of the mod it no longer drops items, and has an internal buffer for output items such as full buckets that can be pulled out with a hopper     https://i.imgur.com/fSzMc1M.gif
