### ISSUE TITLE
[Bug] Powered Bedrock still crashes player

### ISSUE THREAD

**Issue by TheonlyTazz** [PrinceOfAmber/Cyclic#2160]
### Minecraft Version:
1.18.2

### Forge Version: 
40.1.69

### Mod Version: 
1.7.6

### Single Player or Server:
Singleplayer

### Describe problem (what you were doing; what happened; what should have happened):

Loading in powered Bedrock can crash the player. This was fixed in 1.19, but not in 1.18.2 yet
https://github.com/Lothrazar/Cyclic/issues/2142

This issue was originally posted on the FTB Modpack issue tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1232

**Comment by Lothrazar** [comment]
v1.7.7+ https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3946183
