### ISSUE TITLE
[Issue]: Dupe with "Cyclic" Sack of Holding and "Bonsai Trees 3" Bonsai Pot.

### ISSUE THREAD

**Issue by TheOneTrueDev** [PrinceOfAmber/Cyclic#2162]
Minecraft Version: 1.18.2

Forge Version: 40.1.73

Mod Version: 1.7.6

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): When picking up bonsai pot with the sack of holding the user is able to try to place it down but it says there's an error and nothing is placed but any items that were inside the bonsai pot will be spawned on the ground. It looks like the bag disappears but it doesn't allowing the player to spam dupe any item.

**To Reproduce**

1.  Grab Cyclic Sack of Holding
2.  Place item to be duped inside a bonsai pot from Bonsai Pots 3
3.  Pick up bonsai pot with the sack
4.  Attempt to place the bonsai pot
5.  Profit

Log file link: N/A

Video/images/gifs (direct upload or link): N/A

**Comment by Lothrazar** [comment]
I tried with version 3.1.0 of bonsai trees and it didnt happened.
![bbb](https://user-images.githubusercontent.com/621529/189546831-88b2f645-3f39-407a-b3ef-c1b89726ae75.gif)

I didnt get any duplicate swords when i tried this. is it only the other slots?

Video attached

Also you can use a config labelled 'tile_transporter.disable_pickup' to disable blocks from reacting to this
