### ISSUE TITLE
[Suggestion] Crafting Stick

### ISSUE THREAD

**Issue by INooBTooMuch** [PrinceOfAmber/Cyclic#2164]
Make the Crafting Stick work while in the inventory by making the 2x2 crafting into 3x3 or by adding a button/ key-bind to access it from inside the inventory and not in hotbar. (this should make it compatible with resource packs maybe idk)

**Comment by Lothrazar** [comment]
i hate adding keybinds that take up space and dont do much.

BUT i remembered the storage_bag had this right click feature to open like this:

![stick](https://user-images.githubusercontent.com/621529/189679312-43bfd7de-bcc7-4864-93c2-44235da585a4.gif)
