### ISSUE TITLE
Experience Boost Enchantment

### ISSUE THREAD

**Issue by ByPxndaa** [PrinceOfAmber/Cyclic#2166]
Minecraft Version: 1.18.2

Forge Version: 40.1.69

Mod Version: 1.82.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): We were playing normally and the next day i notice that the enchanment experience boost is no longer on my pick and any other item that had it no longer has it. What can we check or do?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
in the config/cyclic.toml , there are some controls to let modpack devs or whatever turn off enchants, so if this is false it makes sense. or maybe the tool got broken and repaired in some way? crafting recipes can strip off enchants?

**Comment by ByPxndaa** [comment]
it was all of a sudden that the enchant disappear, is that something i can check and put on true again?

**Comment by Lothrazar** [comment]
yeah just change the config from false to true, it doesnt wipe nbt off the item its still there just not doing anything
