### ISSUE TITLE
[Compatibility] Add descriptions for effects in JEED

### ISSUE THREAD

**Issue by INooBTooMuch** [PrinceOfAmber/Cyclic#2167]
## Versions

Minecraft Version: 1.18.2

## Description

There are Icons and Colors to the effects added but some are wrong and there aren't descriptions (some might have/not need).
[JEED](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed) has the code that is needed to add the compatibility in their curseforge page.

**Comment by Lothrazar** [comment]
JEED looks great i havent used it before, similar to https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions . yeah ill clean up the colours
