### ISSUE TITLE
Problem with Rainbow Cannon and Chaos Reaper

### ISSUE THREAD

**Issue by antoine-courant** [PrinceOfAmber/Cyclic#2169]
Minecraft Version: 1.18.2

Forge Version: 40.1.60

Mod Version: 1.18.2-1.7.6

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Hello ! I just found the new version of your mod, and I noticed two new items : The Chaos Reaper and the Rainbow Cannon
I tried to charge them via the battery upgrade of Sophisticated backpack or via the item slot of your batteries, with or without the "exporting power" enabled, and none of them worked (I guessed it was using FE from what I read on some issues and questions, because the cannon isn't in your guidebook
Nothing I can do, those two items just won't recharge, still staying at 0/16000
Do you have an idea if it's a bug or else ?
Thanks in advance !

Log file link:

Video/images/gifs (direct upload or link): 

![image](https://user-images.githubusercontent.com/11462348/188741587-eb8f3f69-559f-444c-8fdf-35ffb6ea009c.png)

**Comment by HalcyonSeas73** [comment]
I don't think they're fully implemented?

**Comment by Lothrazar** [comment]
Fixed in latest versions, thanks for the report! They charge up full as expected
