### ISSUE TITLE
Only vanilla ores spawning in the nether and end

### ISSUE THREAD

**Issue by BigSnapple** [PrinceOfAmber/Cyclic#2170]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2859

Mod Version: 1.12.2-1.20.12

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened): Only vanilla ore equivalents are spawning in the nether and end (diamond, coal, etc.) Others such as ruby and platinum don't even appear in JEI despite being enabled in the config. Affects OTG worlds, Biomes O Plenty worlds and vanilla worlds.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
Cyclic doesn't add additional ores to world generation... are you thinking of another mod?

**Comment by Lothrazar** [comment]
To enable non-vanilla ores in the 1.12 version of cyclic, go into the 
cyclic_ores.cfg file

set the global config to TRUE.

Then restart the game
Also make sure to start a new world
Then when you go to the nether they will start spawning, and show up in the creative tab .

Images

![orez 1](https://user-images.githubusercontent.com/621529/189962564-e743b3ab-5786-42e9-9194-baf5e2e923ab.png)

![orez 2](https://user-images.githubusercontent.com/621529/189962600-ebac635b-aa59-48b0-82f7-d411fc359f09.png)
![orez3](https://user-images.githubusercontent.com/621529/189962612-908d981a-c7bb-40ea-a851-a4e13e5b3b4d.png)

**Comment by Lothrazar** [comment]
Forge 14.23.5.2860 
Modlist i used for testing just now 
![modlist](https://user-images.githubusercontent.com/621529/189962743-3d1cfe00-fc9c-4dcb-83bc-aa4c67cdcfe1.png)

**Comment by Lothrazar** [comment]
And yeah sadly the ores only exist in 1.12.2, so minecraft 1.16.5, 1.18.2+ etc dont have them

The vanilla ones got remade into a new mod  https://www.curseforge.com/minecraft/mc-mods/elementary-ores

**Comment by Lothrazar** [comment]
Closing as resolved, if/when i ever make documentation i will make sure to note this for the 1.12.2 version
