### ISSUE TITLE
Can't Craft Compressed Cobblestone

### ISSUE THREAD

**Issue by djohna66** [PrinceOfAmber/Cyclic#2174]
Minecraft Version: 1.19.2

Forge Version: 43.1.10

Mod Version: 1.7.9

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): Trying to craft compressed cobblestone by using 9 cobblestone in a crafting table. It should create 1 compressed cobblestone. It creates a sturdy stone. I crafted 9 sturdy stones to see if those would create the compressed cobblestone, but that doesn't create anything. I'm trying to craft the Crushing Macerator.

Log file link: No crash issue.

Video/images/gifs (direct upload or link): 

![2022-09-14_08 51 22](https://user-images.githubusercontent.com/45616451/190158881-b2d8bff3-abb4-4a1a-bd3d-201ceac68457.png)
![2022-09-14_08 51 57](https://user-images.githubusercontent.com/45616451/190158859-74824033-3670-43ce-9d91-fa14ecc79870.png)

**Comment by Lothrazar** [comment]
The QUARK sturdy stone recipe is supposed to be a mix of smooth stone and cobblestone with hollow in the center.  i just checked it out.  Sounds like your modpack must have changed a bunch of recipes, nothing i can do about that 
![sturdy](https://user-images.githubusercontent.com/621529/190268607-f6446dd8-a290-4abc-bfcf-3b3fd24a8159.png)
![cobbl](https://user-images.githubusercontent.com/621529/190268609-adec99f7-2c04-4c2b-b351-678007c2464b.gif)

**Comment by Lothrazar** [comment]
or maybe quark changed their recipes again?

**Comment by djohna66** [comment]
I found and disabled Sturdy Stone in Quark and the issue is now resolved.

Thank you.
