### ISSUE TITLE
[Crash] Before Joining Game (Main Menu)

### ISSUE THREAD

**Issue by INooBTooMuch** [PrinceOfAmber/Cyclic#2175]
Minecraft Version: 1.18.2

Forge Version: 40.1.80

Mod Version: 1.7.9

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Opened Minecraft

Log file link: https://gist.github.com/INooBTooMuch/1256753e79116b3a99d7badddd85d429
[Mods](https://gist.github.com/INooBTooMuch/10cfa142657308873bc94d017f336ec9#file-mods-in-testing-v_1_9), Cyclic is in 1.7.8 in here crashes when I update to 1.7.9.

**Comment by Bass2style** [comment]
same issue here, game is crashing during launch. downgrading to 1.7.8 is fixing the crashes.

here is an additional crashlog : https://gist.github.com/Bass2style/f239d27e3bbea4d74c889ec7f3177c4c

**Comment by EtherialMind** [comment]
I think I found the issue. polymorph is having trouble accessing the UI of one of cyclic's crafters. Not sure which here is a file to support 
[latest.log](https://github.com/Lothrazar/Cyclic/files/9592157/latest.log)
```
[12:27:50]` [modloading-worker-0/FATAL]: Mixin apply failed polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter -> com.lothrazar.cyclic.block.crafter.TileCrafter: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching lastValidRecipe:Lnet/minecraft/world/item/crafting/Recipe; in com/lothrazar/cyclic/block/crafter/TileCrafter for polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter->@Accessor[FIELD_SETTER]::setLastValidRecipe(Lnet/minecraft/world/item/crafting/Recipe;)V [INJECT Applicator Phase -> polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter -> Apply Accessors ->  -> Locate -> polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter->@Accessor[FIELD_SETTER]::setLastValidRecipe(Lnet/minecraft/world/item/crafting/Recipe;)V]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching lastValidRecipe:Lnet/minecraft/world/item/crafting/Recipe; in com/lothrazar/cyclic/block/crafter/TileCrafter for polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter->@Accessor[FIELD_SETTER]::setLastValidRecipe(Lnet/minecraft/world/item/crafting/Recipe;)V [INJECT Applicator Phase -> polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter -> Apply Accessors ->  -> Locate -> polymorph_integrations.mixins.json:cyclic.AccessorTileCrafter->@Accessor[FIELD_SETTER]::setLastValidRecipe(Lnet/minecraft/world/item/crafting/Recipe;)V]
```

**Comment by INooBTooMuch** [comment]
> I think I found the issue. polymorph is having trouble accessing the UI of one of cyclic's crafters. Not sure which here is a file to support [latest.log](https://github.com/Lothrazar/Cyclic/files/9592157/latest.log)

Now that you mention it I found something about polymorph mixins [here](https://gist.github.com/INooBTooMuch/1256753e79116b3a99d7badddd85d429#file-crash-with-cyclic-L481)

**Comment by tac-owo** [comment]
Getting the exact same error as the rest of the thread, involving polymorph. Downgrading to Cyclic 1.7.8 works.

**Comment by Mrbysco** [comment]
This is something that needs to get reported to Polymorph as it's their integration that's broken due to the changes in 1.7.9
