### ISSUE TITLE
Silkweave Slippers do not go into Armor Slot

### ISSUE THREAD

**Issue by revdave33** [PrinceOfAmber/Cyclic#2176]
Minecraft Version: 1.19.2

Forge Version: 43.1.25

Mod Version: 1.7.11

Single Player or Server: Single Play

Describe problem (what you were doing; what happened; what should have happened):

I crafted the Silkweave Slippers. When I try to place them in the Armor slot for Boots it will not allow it. It does still work to eliminate fall damage, but since it uses a pair of boots to create, I would assume that it would be a boot.

**Comment by Lothrazar** [comment]
They are meant for a Curios slot.
But yeah maybe ill look into making them both. vision helmet is both armor and curio

**Comment by Lothrazar** [comment]
im going to keep it as curios only, they are kind of like socks.  

Apparently theres a way to make Curios items render on the player model, i saw this artifacts mod doing it so id like to look into that actually
