### ISSUE TITLE
[Bug] The Water Candle is not centered

### ISSUE THREAD

**Issue by INooBTooMuch** [PrinceOfAmber/Cyclic#2182]
Minecraft Version: 1.182

Forge Version: 40.1.80

Mod Version: 1.7.9

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):
The water Candle is off-center with the block/Candle base

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/107572028/193660207-70c65336-4c94-4223-886f-3b2861bba258.png)

I also tried to fix it using blockbenche, idk if it helps but its this : 
[Model](https://gist.github.com/INooBTooMuch/25a4185fd6ce48aea4eb6948803aceee)

I have made some textures, because I wanted to just make something, so these are here if you want :
![image](https://user-images.githubusercontent.com/107572028/193660796-c6ab237e-1aef-4ffb-ace9-66003632fec5.png)
![image](https://user-images.githubusercontent.com/107572028/193660817-e7437da4-2275-4e0b-a2e6-773b04eaccf0.png)
![image](https://user-images.githubusercontent.com/107572028/193660830-8b91e594-c095-469a-a79e-8a3ebdda89dd.png)

**Comment by Lothrazar** [comment]
![2023-06-09_09 32 32](https://github.com/Lothrazar/Cyclic/assets/621529/e166ad15-8c0a-400a-8002-4c71aa138e04)
