### ISSUE TITLE
Recipe Conflict with Quark

### ISSUE THREAD

**Issue by wildkurt** [PrinceOfAmber/Cyclic#2183]
Minecraft Version: 1.19.2

Forge Version: 43.1.25

Mod Version: 1.19.2-1.7.11

Single Player or Server: Server

Describe the problem (what you were doing; what happened; what should have happened):
I am trying to build the Harvester block and the ingredient Compressed Cobblestone has the same recipe as the Sturdy Stone in Quark 3.3-371 mod. 

Log file link:
No logs

Video/images/gifs (direct upload or link): 

No media files

**Comment by adamkad1** [comment]
You should get a mod like polymorph to get around duplicate recipes.

**Comment by wildkurt** [comment]
> You should get a mod like polymorph to get around duplicate recipes.

That was a excellent idea, thank you!

**Comment by Lothrazar** [comment]
added conditional recipes in latest 1.19 release for this
