### ISSUE TITLE
The forester did not chop down the gevea logs from the IC2 (Industrial Craft 2) mod.

### ISSUE THREAD

**Issue by Zapzatron** [PrinceOfAmber/Cyclic#2189]
Minecraft Version:  1.12.2

Forge Version: 1.12.2

Mod Version:  1.20.12

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
1. Put a forester.
2. Connected energy to the forester.
3. Put the gevea saplings in the forester's inventory.
4. The forester put the saplings out.
5. Waited until the saplings had grown and the forester started cutting.
6. The forester removed all the leaves.
7. The forester did not cut down the gevea logs.
My expectations: The forester should have planted the saplings and cut down the gevea logs and the gevea leaves.

Log file link: Not required.

Video/images/gifs (direct upload or link): 
![2022-10-29_00 18 32](https://user-images.githubusercontent.com/100136305/198734385-154f0dbe-400c-4955-8e3e-b474f7f04b6c.png)

**Comment by Zapzatron** [comment]
My suggestion is to add a whitelist to the forester, as in smart miner.

**Comment by Zapzatron** [comment]
And you can also add a config with additional ids of species of logs for the forester.

**Comment by Lothrazar** [comment]
Thats weird that its skipping those logs.

In mc 1.12.2 version of mod it uses the ore dictionary tags "logWood" and "treeLeaves" to decide what gets broken and harvested or not. maybe thse blocks dont have a logWood ore dictionary tag?

It uses also "treeSapling" for saplings  
Ref: https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/block/forester/TileEntityForester.java#L63

**Comment by Zapzatron** [comment]
![Скриншот 29-10-2022 104945](https://user-images.githubusercontent.com/100136305/198820358-7dadb596-d6e6-43ad-be4b-b22ddc116102.jpg)
![Скриншот 29-10-2022 104929](https://user-images.githubusercontent.com/100136305/198820361-5088267e-0c04-4668-8a3b-ae7780f9b568.jpg)

**Comment by Zapzatron** [comment]
What can I do to get a forester to work?

**Comment by Lothrazar** [comment]
im testing with https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/4048720 [IC2Classic-1.12-1.5.6.0](https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/4048720)

**Comment by Lothrazar** [comment]
This is the issue in more detail

See if i hold ctrl and then under 'OreDictionary Entries:' it has what type of wood or log type it has

I have a GIF recording below

The ic2 tree blocks use 'woodRubber' but cyclic only looks for 'logWood'.

Solutions:
I know other modpack devs have solved problems like this , use scripts like crafttweaker/zenscript to set dictionary values, but thats kind of tricky.
option 2: If the ic2 mod devs can update to add a second block Oredict, so it has both woodRubber and logWood, the forester should start working
option 3: ill see if i can do a mod update for this or a config file update to make this work

**Comment by Lothrazar** [comment]
![woodRubber](https://user-images.githubusercontent.com/621529/200087685-8dba5e3e-469a-43f4-a207-de501030e7eb.gif)

**Comment by Lothrazar** [comment]
i got a fix in 1.20.13 plz check it out https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4068137  . also the listed values about woodRubber and stuff will be in the new cyclicmagic.cfg 

After the fix: 
![asdfasdfasdf](https://user-images.githubusercontent.com/621529/200095335-e075f82b-c051-4755-a9a9-5e2116abe13b.gif)

**Comment by Lothrazar** [comment]
conf example ![new conf](https://user-images.githubusercontent.com/621529/200095357-ce9c1dac-94ae-432b-9e70-df16d04a95b6.png)
