### ISSUE TITLE
Sign Editing feature is calling a client only method on server

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#219]
@Morpheus1101 reported this in comment thread of different issue

Morpheus1101 commented 2 days ago
On a different note but still server console spam on the MMD-Dev server i noticed this:

https://puu.sh/t2bSE/a0a6111d75.txt

**Comment by Morpheus1101** [comment]
:D

**Comment by PrinceOfAmber** [comment]
Fixed in 1.9.9 https://minecraft.curseforge.com/projects/cyclic/files/2361605
