### ISSUE TITLE
living event crash

### ISSUE THREAD

**Issue by diamondbananaman265** [PrinceOfAmber/Cyclic#2192]
Minecraft Version: 1.18.2

Forge Version: 40.1.80

Mod Version: 1.7.13

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):

the mod is not letting my game load when the mod version is above 1.7.10 and when i check the crash logs i noticed it keeps saying this: Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingChangeTargetEvent

Log file link: 
[crash-2022-11-09_17.00.04-fml.txt](https://github.com/Lothrazar/Cyclic/files/9975759/crash-2022-11-09_17.00.04-fml.txt)

Video/images/gifs (direct upload or link):

**Comment by warjort** [comment]
The LivingChangeTargetEvent was added in forge 40.1.84 so you need to upgrade forge.
