### ISSUE TITLE
Can't start server with the new version of the mod

### ISSUE THREAD

**Issue by antoine-courant** [PrinceOfAmber/Cyclic#2195]
Minecraft Version: 
1.18.2

Forge Version: 
40.1.60

Mod Version: 
1.7.13 (also happens with the 1.7.12)

Single Player or Server: 
Server

Describe problem (what you were doing; what happened; what should have happened):
Starting the server

Log file link:
[crash-2022-11-13_12.13.34-fml.txt](https://github.com/Lothrazar/Cyclic/files/9997049/crash-2022-11-13_12.13.34-fml.txt)

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/11462348/201519077-991ffcc8-5c6e-4e1b-9cd0-719f5124dcee.png)

**Comment by TheIllusiveC4** [comment]
This is not a Cyclic issue, you need to update your version of Polymorph.

**Comment by antoine-courant** [comment]
Oh ! I'll do this and see if it starts then, thanks ;)

**Comment by antoine-courant** [comment]
Okay, I updated Polymorph mod, now the server still can't start, we have another error, see below :

![image](https://user-images.githubusercontent.com/11462348/202853883-e5543779-d2a4-47c8-acc6-5fe742dd068b.png)

**Comment by HalcyonSeas73** [comment]
> Okay, I updated Polymorph mod, now the server still can't start, we have another error, see below :

Try updating Forge? Same error as #2192

**Comment by antoine-courant** [comment]
I'll try, but I have a lot of mods, so it's kinda complicated to update Forge and keep it all running
I'll tell if it worked
