### ISSUE TITLE
1.19.2 cant launch single player

### ISSUE THREAD

**Issue by Netrecov** [PrinceOfAmber/Cyclic#2201]
Minecraft Version: 1.19.2

Forge Version: 43.1.7

Mod Version: 1.19.2-1.7.14

Single Player or Server: single palyer

Describe problem (what you were doing; what happened; what should have happened):
attempting to create new world, and the game crashes.

Log file link:

Video/images/gifs (direct upload or link): 

[crafttweaker.log](https://github.com/Lothrazar/Cyclic/files/10096660/crafttweaker.log)

[latest.log](https://github.com/Lothrazar/Cyclic/files/10096659/latest.log)

Mods that i am attempting to run together:
11/26/2022  09:35 AM           318,908 Bookshelf-Forge-1.19.2-16.1.11.jar
11/26/2022  09:40 AM           279,160 configured-2.0.1-1.19.2.jar
11/26/2022  09:03 AM           202,685 constructionwand-1.19.1-2.8.jar
11/26/2022  09:09 AM           220,543 corpse-1.19.2-1.0.0.jar
11/26/2022  09:34 AM         2,975,430 CraftTweaker-forge-1.19.2-10.0.16.jar
11/26/2022  09:23 AM        14,429,032 create-1.19.2-0.5.0.f.jar
11/26/2022  09:34 AM           269,319 curios-forge-1.19.2-5.1.1.0.jar
11/26/2022  09:00 AM         4,654,457 Cyclic-1.19.2-1.7.14.jar
11/26/2022  09:08 AM           188,477 dankstorage-1.19.2-5.1.3.jar
11/26/2022  09:33 AM            57,830 EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar
11/26/2022  09:09 AM         1,046,401 jei-1.19.2-forge-11.4.0.286.jar
11/26/2022  09:00 AM           635,370 Patchouli-1.19.2-77.jar
11/26/2022  09:07 AM         3,266,051 refinedstorage-1.11.1.jar

**Comment by Netrecov** [comment]
[crafttweaker.log](https://github.com/Lothrazar/Cyclic/files/10096663/crafttweaker.log)
[latest.log](https://github.com/Lothrazar/Cyclic/files/10096664/latest.log)

**Comment by Netrecov** [comment]
If i remove the mod pack, the game will create a new world just fine.

**Comment by Netrecov** [comment]
[crash-2022-11-26_10.52.18-client.txt](https://github.com/Lothrazar/Cyclic/files/10096672/crash-2022-11-26_10.52.18-client.txt)

**Comment by Mrbysco** [comment]
Have you tried updating forge itself? You're on a rather old version of Forge

**Comment by Netrecov** [comment]
there isnt an update option, and installing a new download from them results in same version.

**Comment by Mrbysco** [comment]
The latest forge is 43.1.57 and you're running 43.1.7 which is around 50 builds behind

**Comment by Netrecov** [comment]
i was able to go to options, profile options,  and choose the version you specified. I was then able to create a new world with the mods i have selected, thank you.
