### ISSUE TITLE
Failed on startup (NoClassDefFoundError)

### ISSUE THREAD

**Issue by light-sun-boy** [PrinceOfAmber/Cyclic#2203]
Minecraft Version: 1.18.2

Forge Version: 40.1.70

Mod Version: 1.7.13

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened): During startup, the game can failed. image and txt attached are crash report

Log file link:

[crash-2022-12-01_20.10.23-fml.txt](https://github.com/Lothrazar/Cyclic/files/10132230/crash-2022-12-01_20.10.23-fml.txt)

Video/images/gifs (direct upload or link): 

![Screenshot_82](https://user-images.githubusercontent.com/119596692/205049953-dd000d69-21c9-4ef0-a89f-66cb389f2648.png)

**Comment by Lothrazar** [comment]
this should go away on the newer forge versions such as 40.1.85+
