### ISSUE TITLE
[Suggestion] Add config options to disable Potion of Flight and Glowing Chorus Fruit 1.19.2

### ISSUE THREAD

**Issue by SolaceNL** [PrinceOfAmber/Cyclic#2204]
I have a no-fly server and would appreciate the ability to disable the potions. For Glowing Chorus Fruit, I'm using KubeJS to remove and hide the recipe but can't do so with the Potion of Flight.

**Comment by Lothrazar** [comment]
Yeah i can add that config.  At the very least i can remove the brewing recipes for sure.  I assumed it was real easy to remove recipes with just a data pack but i think that doesnt apply to brewing potions because mojang

**Comment by Lothrazar** [comment]
the config added in previous versions disables the basic potion recipe for the 3:00 potion 

`
		[cyclic.potion.flight]
			#Set false to disable the base recipe
			enabled = false`
