### ISSUE TITLE
common_setup phase error

### ISSUE THREAD

**Issue by ZacGames** [PrinceOfAmber/Cyclic#2210]
Minecraft Version: 1.18.2

Forge Version: 40.1.51

Mod Version: 1.7.43

Single Player or Server: Either or

Describe problem (what you were doing; what happened; what should have happened):
I just opened the game up, and, during the "common_setup" phase, Cyclic encountered a java.lang.NoClassDefFoundError.
Pretty sure _that's_ not supposed to happen, but I'm not sure what could have caused it.

Log file link:
[latest.log with other mods installed, including Patchouli.](https://github.com/Lothrazar/Cyclic/files/10200723/latest.log)
[latest.log _without_ other mods installed, running alone.](https://github.com/Lothrazar/Cyclic/files/10200730/latest.log)

Video/images/gifs (direct upload or link): 
[Crash Report with mods, if it helps.](https://github.com/Lothrazar/Cyclic/files/10200725/crash-2022-12-10_13.42.02-fml.txt)
[Crash Report without mods.](https://github.com/Lothrazar/Cyclic/files/10200732/crash-2022-12-10_13.54.25-fml.txt)

**Comment by ZacGames** [comment]
sorry, wrong mod version, mistyped "1.7.43" when i meant "1.7.13"

**Comment by HalcyonSeas73** [comment]
Update Forge to the latest for 1.18.2

**Comment by Lothrazar** [comment]
Yep moving to forge  40.1.84 + will fix this. working on making it use that screen to show minimum forge version instead of crashing.
