### ISSUE TITLE
Massive lag with harvesters

### ISSUE THREAD

**Issue by Jcodeerd** [PrinceOfAmber/Cyclic#2211]
Minecraft Version: 
1.19.2

Forge Version: 
43.2.0

Mod Version: 
1.7.14

Single Player or Server:
server

Describe problem (what you were doing; what happened; what should have happened):
Extreme lag caused by harvesters (We do have quite a few)

Log file link:
https://spark.lucko.me/M9JWsdG8ZB https://spark.lucko.me/vbKbd3nc0g
[debug.log](https://github.com/Lothrazar/Cyclic/files/10201334/debug.log)

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/68161666/206882941-64422bdb-d887-43a1-87c0-106096d7dae3.png)

**Comment by Lothrazar** [comment]
I looked into your logs.

I dove into the big red 95% percentage at the top, looks like most of it is from running a command, i drilled into another place and there is about 8-10% of the flagged resources being used by the harvesters getting their "shape" which is the area they are about to harvest over.

Ill see if i can reduce this a bit, but also you have other stuff going on. also, why are there so many harvesters?  Im fairly confident if you replaced that tower of 10 with just one, or maybe four one on each side, it would not produce items any slower  
![what](https://user-images.githubusercontent.com/621529/208173057-8f76f3a9-dc1b-45b5-a290-5ec6912b7823.png)
![part two](https://user-images.githubusercontent.com/621529/208173062-093987a8-3e99-4db8-9dd2-bf0c58cf5b7f.png)
