### ISSUE TITLE
Can you put the mod into a server and not expect errors (with about 20-30 plugins)?

### ISSUE THREAD

**Issue by FlyinC4T** [PrinceOfAmber/Cyclic#2213]
Minecraft Version: 1.17.2

Forge Version: na

Mod Version: na

Single Player or Server: Server (Paper)

Describe problem (what you were doing; what happened; what should have happened): Unsure if I can move my paper server to fabric or spongeforge and have no problems, since I already have at least 25 plugins that must not be removed

if so then how would it be done, so I don't do anything wrong

**Comment by HalcyonSeas73** [comment]
This would be better asked in some kind of Paper support server. Cyclic only runs on Forge, there's no Fabric port. I don't know anything about Paper or Spongeforge.

**Comment by Lothrazar** [comment]
You didnt show any error log so i dont know what errors you are seeing.  

If you have Forge ( 40.1.84 + ) with literally ZERO OTHER MODS INSTALLED, nothing but minecraft and forge thats it, then Cyclic works perfectly fine o nservers and single player

If you have 30 other plugins causing errors, please remove those first, install forge, and then collect some error logs if there areany.

Fabric still has this bug that they need to fix where they dont let forge be compatible with them for some reason, its a really strange design choice
