### ISSUE TITLE
1.16.5 Mattock has wrong harvest level

### ISSUE THREAD

**Issue by darchitectlp** [PrinceOfAmber/Cyclic#2223]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: Cyclic-1.16.5-1.5.20.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

Mattock doesn't register that is the right tool or harvest level for minecraft:stone_bricks, cracked_stone_bricks, chiseled_stone bricks. Also seems to not work on Create's limestone variants (including the cobble versions).

Playing Rustic Waters 2.

Thanks!

PS Quick edit to say, looks like this impacts the netherite version, as well.

**Comment by Lothrazar** [comment]
Does the mattock correctly get the harvest level from the center of a 3x3? Yes, mining obsidian takes forever, mining dirt is fast.

IF the center of a 3x3 area is dirt and the other 8 blocks are obsidian, does it mine everything at dirt speed? also yes.  i guess ill be leaving this easter  egg in , its been like this forever <3
