### ISSUE TITLE
1.16.5 Sprinkler doesn't work

### ISSUE THREAD

**Issue by darchitectlp** [PrinceOfAmber/Cyclic#2224]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: Cyclic-1.16.5-1.5.20.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Place sprinkler down, it absorbs the source block underneath it, but then fails to do anything else. It never uses the water in its internal tank, there is no movement, nor particle animations.

**Comment by Lothrazar** [comment]
if the sprinker runs out of water it will halt. you can tell it works on a block when you see these water partciles spraying up.

If you want an auto-refill method try three water sources like this, so when sprinkler consumes the water source below it gets re-filled when the water sources merge.  Enjoy the farming!


![1933](https://github.com/Lothrazar/Cyclic/assets/621529/f66a250a-ee37-454d-aa2d-1f01fd92a402)
