### ISSUE TITLE
Multi-jump not working at all

### ISSUE THREAD

**Issue by RadioActiveSoul** [PrinceOfAmber/Cyclic#2231]
Minecraft Version: 1.19.2

Forge Version: 43.2.3

Mod Version: 1.7.14

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened): not working on my main modpack, tested it with only JEI. neither worked. no multi jumps at all. you just got to tap space multiple times right?

**Comment by Liink56** [comment]
exactly, I already played on an older minecraft version, and the multijump worked with a double space, which no longer works on 1.19.2

**Comment by HalcyonSeas73** [comment]
It was fixed in 1.18.x, needs the fix ported to 1.19.x
