### ISSUE TITLE
Multi-Bow showing up in JEI but not available.

### ISSUE THREAD

**Issue by OldGamerBroad** [PrinceOfAmber/Cyclic#2232]
Minecraft Version: 1.19.2

Forge Version:  43.2.0

Mod Version: Cyclic-1.19.2-1.7.14

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

I can no longer find the Multi-Bow enchant.  It still shows up in JEI, but it appears to no longer be implemented.  I have scanned the .jar file and there are references to it in the code ("com/lothrazar/cyclic/enchant/MultiBowEnchant.class"), but there is no entry in the cyclic_guide_book for it.  In addition, it no longer appears in the config file.

I have purchased Multi-Bow scrolls from villagers in earlier versions so I'm a bit confused.

Please clarify.  Thanks!

Log file link:

n/a

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
I was able to find it after a few tries with some bookshelves up  and ill look at making it more "common" in RNG.

It does already show up in the guidebook as Multi-bow, but the ID and the config value is cyclic.enchantment.multishot , , sorry for confusion  
![bowwww](https://github.com/Lothrazar/Cyclic/assets/621529/3a2b82bb-eb4d-426f-b087-7884b5a65de8)
