### ISSUE TITLE
[1.19.2][Compatibility] Cyclic potions break Create potion brewing

### ISSUE THREAD

**Issue by Saereth** [PrinceOfAmber/Cyclic#2233]
Minecraft Version:  1.19.2 

Forge Version: 43.2.3

Mod Version: Cyclic-1.19.2-1.7.14

Single Player or Server: Both

Describe the problem (what you were doing; what happened; what should have happened):
Creating any potion with create while cyclic is added to the pack results in potions of haste. 
Without cyclic installed potions are created as expected in the create mixer.

This issue was originally reported on our ftb tracker for the DW20 1.19 modpack here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2526

And it contains sceen shots better showing the issue.

**Comment by Lothrazar** [comment]
is there a recipe conflict? the only way to get a haste 2 potion is with redstone plus haste 1 potion, not redstone with anything.

sounds like whatever potion machine thing you are using is mis-reading some recipes or mis-processing.    


![comp2](https://github.com/Lothrazar/Cyclic/assets/621529/82336682-8e76-4ec6-a369-e4189065184b)
![recipe conflict](https://github.com/Lothrazar/Cyclic/assets/621529/23cb5fa7-359c-49ff-8b2e-98a199d9e8d6)

**Comment by Lothrazar** [comment]
actually i just noticed that the linked issue is closed and resolved, glad it worked out!
