### ISSUE TITLE
Is it possible to add a blacklist for a forester so that he can't collect certain leaves, for example?

### ISSUE THREAD

**Issue by Zapzatron** [PrinceOfAmber/Cyclic#2234]
Minecraft Version: 1.12.2

Forge Version: 1.12.2

Mod Version: 1.20.13

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Due to the fact that the forester cuts down the leaves, he works slowly and very energy consuming. It would be faster and more economical to break the logs, and the leaves themselves will fall, for example, with the mod fastleafdecay.

Log file link: Not required.

Video/images/gifs (direct upload or link): Not required.

**Comment by Lothrazar** [comment]
1.12 might be a little different than newer versions, but even so to Refill the forester you can collect the saplings the normal way and pipe them in ( . gif was recorded in minecraft 1.20.1): 
![forester self refill](https://github.com/user-attachments/assets/c8ecae8c-9ff7-498c-9001-77ae4448d106)
