### ISSUE TITLE
Cannot make moss blocks with solidification chamber

### ISSUE THREAD

**Issue by sharkck** [PrinceOfAmber/Cyclic#2236]
Minecraft Version: 1.19.2

Forge Version: 43.2.4

Mod Version: 1.7.14

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Put dirtx3 into the solidification chamber with liquid biomass to make moss block.

Instead, it only makes 3 grass blocks.  There appears to be no way to set the recipe

Log file link:
N/A

Video/images/gifs (direct upload or link): 

https://cdn.discordapp.com/attachments/335973199538028555/1070145138975846510/image.png

https://media.discordapp.net/attachments/335973199538028555/1070134559020155010/image.png

**Comment by Faylen** [comment]
Just going to bump it here, we've got the updated version of the mod (1.8.0) that's supposed to fix the problem yet you still cannot make moss using the solidification chamber
