### ISSUE TITLE
Block breaker is not dropping certus quartz when breaking certus quartz crystals

### ISSUE THREAD

**Issue by Peca21** [PrinceOfAmber/Cyclic#2238]
Minecraft Version:  1.19.2

Forge Version: 43.2.4

Mod Version: Cyclic-1.19.2-1.7.14

Single Player or Server: Single Player 

Describe problem 
what you were doing:
Breaking certus quartz cluster from AE2 with a block breaker
what happened: certus quartz cluster didn't drop any items
what should have happened): certus quartz cluster should drop 4 certus quartz

Video/images/gifs (direct upload or link): 
https://streamable.com/ptmb9i

**Comment by Peca21** [comment]
So when you break the crystal by breaking a block that the crystal is attached to, it will not drop any certus, you need to break the crystal itself with a pickaxe. This may be related to this bug

**Comment by Zunft0** [comment]
I believe it is a AE2 problem/design the RF builder also cannot collect crystals

**Comment by Peca21** [comment]
I tried other block breakers, they also don't drop anything
RFTools Builder doesn't even attempt to break it for me
But the digital miner from mekanism works fine

**Comment by Lothrazar** [comment]
Block Breaker does not act as a fake player, so this is by design. you could try cyclic:miner that might have a different result as it should act exactly as a player does, or other mods
