### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by KaniasTokisaki** [PrinceOfAmber/Cyclic#2242]
Minecraft Version: 1.18.2

Forge Version: 40.2.1

Mod Version: 
Cyclic-1.18.2-1.7.14.jar
 
Single Player or Server: Server hosted on Essential (same happens in singleplayer)

Describe problem (what you were doing; what happened; what should have happened):

when loading new chunks server freezes doesn't crash and unless i restart minecraft it won't work the game completely freezes, even if i attempt to go back to main screen it just freezes on logging out or signing out whatever the message is just stuck on loading out **I do not know if this is the right logs since i am not sure if there are any logs for server freezing (no crashes happening) and i am forced to open task manager to close the game)**

Log file link:
[2023-02-14-2.log.gz](https://github.com/Lothrazar/Cyclic/files/10741433/2023-02-14-2.log.gz)

Video/images/gifs (direct upload or link): 
[crash-2023-02-07_23.33.33-server.txt](https://github.com/Lothrazar/Cyclic/files/10741518/crash-2023-02-07_23.33.33-server.txt)
 - Possible crash log from cyclic being added on earlier date too then crashing when loading chunks **Earlier cyclic version i believe**

**Comment by KaniasTokisaki** [comment]
P.S i don't think its my computer causing a freeze since without the mod it works perfectly fine AND i am running a 3060 ti and 11600 + Using a new WIFI 6 modem at 500 MBPS internet so those are NOT the problem

**Comment by Mrbysco** [comment]
I can't see any correlation between Cyclic and that Nullpointer crash as the only mod it mentions is TreeChop.
The only worldgen Cyclic does is adding some flowers

**Comment by KaniasTokisaki** [comment]
> I can't see any correlation between Cyclic and that Nullpointer crash as the only mod it mentions is TreeChop. The only worldgen Cyclic does is adding some flowers

okay i removed "treechop" and the same thing is still happening its cyclic related because it only happens after cyclic is added
and logs >  
[2023-02-15-1.log.gz](https://github.com/Lothrazar/Cyclic/files/10745208/2023-02-15-1.log.gz)

**Comment by KaniasTokisaki** [comment]
P.S i kept removing mods it says failed to load chunks with this is an endless chain i shouldn't need to remove other mods to use cyclic

**Comment by Lothrazar** [comment]
you probably saw this ages ago but latest log post was 
`
java.lang.NoSuchFieldError: FLUID
	at it.zerono.mods.extremereactors.gamecontent.compat.jei.reactor.CoolantFromFluidRecipeCategory.setIngredients(CoolantFromFluidRecipeCategory.java:82) ~[ExtremeReactors2-1.18.2-2.0.60.jar%23156!/:1.18.2-2.0.60]`
