### ISSUE TITLE
Item cable bug 

### ISSUE THREAD

**Issue by Jivonchi** [PrinceOfAmber/Cyclic#2245]
Minecraft Version: 1.16.5

Forge Version: 36.2.34

Mod Version: 1.5.20

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Have a simple setup of two chests and an item cable connecting them. Made one end of the cable pull items, and put items in that end of the chest. 
1. Put first item in the chest, doesn't show in the other chest,
2. Put second item in the chest, first item show in the other chest.
3. Put third item in the chest, second item show in the other chest.
4. Put fourth item in the chest, third item show in the other chest 

and so on.

Video/images/gifs (direct upload or link): 
https://imgur.com/a/KmgTDy0

**Comment by etmoonshade** [comment]
For what it's worth, I reported this under #2230 - looks like a similar issue on 1.16 at least, and I did my demonstration video differently. 😁
