### ISSUE TITLE
Item User not breaking wood log with axe

### ISSUE THREAD

**Issue by IamStig** [PrinceOfAmber/Cyclic#2246]
Minecraft Version: 1.19.2

Forge Version: 43.2.3

Mod Version: 1.7.14

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened): Placed user, placed axe in user, grew tree in front of user ...... nothing happens.

Tried changing settings in blocks UI, those being "Always on/require redstone" "Left Click/Right Click" "Block/Entity" I can get it to break saplings (by changing to entity) or strip the log (by changing to Right Click) but it will not break the log.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by RoronoaDroagon** [comment]
I can confirm this.
Made sure that FTB chunk's were not interfering and left click with the item user is not wanting to work.
Right click option works as it's suppose to.
I'm playing on Direwolf20 1.19

**Comment by IamStig** [comment]
It has been a long time since I posted this...... I can't be sure what you mean by "Made sure that FTB chunk's were not interfering". Just to be sure (I have no idea if this is the problem) look at the FTB info top left of screen and then look for "Allow all fake players" I think it is in "teams" even if you are a team of 1. If that is the problem let me know and I'll close this.

**Comment by Lothrazar** [comment]
if you need the tool to be equipped and harvesting blocks, does the 'cyclic:miner' work instead of the user?  Yes either way fake-players will need to be enabled

**Comment by IamStig** [comment]
I finally found time to revisit this. Firstly I had no Team, fixed that and allowed all fake players then tried to get the Item User to use an axe, it would not. I then made a Cyclic Miner and I got it working. I then had another go at the User and it does not want to use an axe. 
It seems odd to me to use a miner to break wood, seems odd that an Item User has a defined list of Items it Uses.... and that list doesn't include an Axe. At least I know now.

**Comment by Lothrazar** [comment]
Yeah try using the cyclic:miner which can hold tools and break blocks with them or cyclic:breaker which breaks blocks without tools

The way the user does left click (by design) is just like as if you, as a player, start mining left-click the block for a few ticks , then stop, then start, then stop. so of course it never finishes 'breaking' . its meant for single use items not click and hold digging, thats what the miner is for.  Hope this helps, always open for more questions and bugs

**Comment by Lothrazar** [comment]
and if some chunky mod disables fake players theres nothing i can do about it
