### ISSUE TITLE
Cant open the "Extended Inventory" after eating the "Ender Inventory Cake" 1.19.2

### ISSUE THREAD

**Issue by DasGammelTier** [PrinceOfAmber/Cyclic#2248]
Minecraft Version: 1.19.2

Forge Version: 43.2.3

Mod Version: 1.7.14

Single Player or Server: Server

Describe problem: I play the Limitless 6 Modpack and got the Cake trough a Loot Bag (also gave it to me with command after it didnt worked) and ate the cake, I got the message that I unlocked the inventory and also binded the key on Mouse 4, 5, Ä and F10...it just didnt opened

Log file link: /

Video/images/gifs (direct upload or link):  /

**Comment by Laande** [comment]
same issue
