### ISSUE TITLE
Item duplication bug with Disarming enchant[1.16.5] + alexsmobs:mimicube

### ISSUE THREAD

**Issue by TheOnlyMann** [PrinceOfAmber/Cyclic#2249]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: 1.5.15

Single Player or Server: Rustic Waters 2, Server

Describe problem (what you were doing; what happened; what should have happened):
With AlexMobs, specifically mimicube from said mod, copying the held inventory you have, can possibly duplicate items that you have held using the Disarming Enchant from cyclic.

Log file link:

Video/images/gifs (direct upload or link): 

https://cdn.discordapp.com/attachments/357597633566605315/1080507912188862484/image.png

https://cdn.discordapp.com/attachments/394202999209328650/1080502016322846751/image.png

**Comment by Lothrazar** [comment]
/summon alexsmobs:mimicube 
then yep it copies your sword after you hit it a few times
