### ISSUE TITLE
Controlled Miner + TiCo Tool = Durability Drain

### ISSUE THREAD

**Issue by ZwipZwapZapony** [PrinceOfAmber/Cyclic#225]
In my own personal little mod-pack, I've tried taking the Controlled Miner and putting a Tinkers' Construct pickaxe inside, in order to level it up using Tinkers' Tool Leveling. It gets 1 XP point per block as expected, and it loses 1 durability per block destroyed... but if it decides to try mining an air block, it will lose 1 durability point per tick that it doesn't find a non-air block to mine, although it doesn't gain XP every tick.

Set-up: A basic water+lava cobblestone generator with a Controlled Miner beside it, set to the 1x1x1 block right in front of it that gets turned to cobblestone that is always active. The pickaxe is a normal Tinkers' Construct one, with an iron pick-axe head and wooden tool rod and wooden binding. It has Reinforced IV, as I've only leveled it up once so far.

Through testing in Creative, Reinforced does affect how quickly the durability gets drained, and at Reinforced V/Unbreakable, it doesn't lose durability at all, but it still shouldn't actively lose durability when attempting to mine air without Reinforced V/Unbreakable. Vanilla-style tools, such as a Diamond (and Cyclic's Emerald and Sandstone) Pickaxe(s), only lose a durability point for each block mined, not when it tries to mine air.

Mod list:
> MineCraft 1.10.2
> Forge 2185
> Chisel & Bits 12.9
> Cyclic 1.9.10
> EnderCore 0.4.1.62-Beta
> Just Enough Items 3.13.6.393
> Just Enough Resources 0.5.8.98
> Mantle 1.1.3
> Tinkers' Construct 2.6.1
> Tinkers' Tool Leveling 1.0.1
> Torcherino 4.2s (Not being used on the miner nor water/lava/cobblestone)
> OptiFine D4

**Comment by PrinceOfAmber** [comment]
It seems like TIC tools durability gets drained for each tick the block is being 'worked on', like the breaking progress,  instead of just once when the harvest is complete. Im not sure why at all, since its using both tools the same way, ill have to dig some more tomorrow or on the weekend.

**Comment by ZwipZwapZapony** [comment]
No, it is _only_ when a block is being worked on that it _doesn't_ drain durability. And then it drains one durability per block broken. But if the controlled miner doesn't find a block to mine (whether it's because there is none in the affected area, or if there's only a partial amount of filled blocks and this tick, it randomly picks one of the air blocks), it also drains durability once per tick.

Try hovering your mouse over the TiCo tool with Shift held down while it's working, and you'll see that it doesn't get drained when working on a block, but it does every tick when not working on a block.

**Comment by PrinceOfAmber** [comment]
Oh i i misread that. Doing some testing with it now

**Comment by PrinceOfAmber** [comment]
Yep it was constantly mining regardless if it was air or solid. which normal tools dont care, but forcing tinkers tools to "mine and harvest air" they were taking damage. 1.9.12 coming out today or tomorrow with a fix

**Comment by PrinceOfAmber** [comment]
Build 1.9.12 is out, it fixes it for me, let me know if theres anything else!  https://minecraft.curseforge.com/projects/cyclic/files/2364870

**Comment by ZwipZwapZapony** [comment]
Thanks. Works perfectly on my end too. Now I can safely put Tinkers' tools in a miner at my cobblestone generator again, which will be pretty nice.
