### ISSUE TITLE
1.19.2 Multi Jump not working

### ISSUE THREAD

**Issue by Jivonchi** [PrinceOfAmber/Cyclic#2256]
Minecraft Version: 1.19.2

Forge Version: 43.2.6

Mod Version: 1.7.14

Single Player or Server: Tested on both single player and server (with and without other mods)

Describe problem (what you were doing; what happened; what should have happened):

Enchanted a boot with multi jump, but still cannot jump more than once.

**Comment by dylithian** [comment]
I'm also having this issue, in 1.19.2 as well. I've only tested it in multiplayer but enchanting diamond boots with multi-jump doesn't give any additional jumps. I'm also having an issue where the silkweave slippers do not prevent falling damage at all, but that's a separate issue.

**Comment by HalcyonSeas73** [comment]
This is a known issue already.

**Comment by reznovmp40** [comment]
Not working for me either and this enchantment is the main reason i downloaded this mod and its very frustrating because i cant find any other mod with a multi-jump style enchantment.
