### ISSUE TITLE
Apple of lofty stature

### ISSUE THREAD

**Issue by CallmeQueen69** [PrinceOfAmber/Cyclic#2258]
Minecraft Version: 1.19.2

Forge Version: 43.2.6

Mod Version: 1.7.14

Single Player or Server:singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Relogging after eating apple of lofty stature resets its effect.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Jona898** [comment]
I have the same issue.
Eate it once to get more hearts (another Mod).
Now each time i restart the world i have the step height and have to eat it twice (enable - disable) to remove the step height.
Is there a way to reset the eaten status?

**Comment by manmaed** [comment]
can confirm this bug is also in version 1.19.2-1.8.0
