### ISSUE TITLE
Material Generator not working correctly

### ISSUE THREAD

**Issue by The-Mats** [PrinceOfAmber/Cyclic#2268]
Minecraft Version: 
1.19.2 
Forge Version:
 -
Mod Version: 
1.7.14
Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
The nether star is supposed to generate a nice 100k RF/t but its generating 1.25k RF/t and lasting 30min..

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Alchemichai** [comment]
Its actually that the power generation and tick duration of netherstars are switched. They should gen 100k rf/t for 1250 ticks. Instead they gen 1250 rf/t for 100k ticks, or about 83 minutes. So close yet so far.

**Comment by Alchemichai** [comment]
Its actually that he has the power generation and tick duration of netherstars switched. They should gen 100k rf/t for 1250 ticks. Instead they gen 1250 rf/t for 100k ticks, or about 83 minutes. So close yet so far.
