### ISSUE TITLE
Exchange Scepter is able to destroy bedrock

### ISSUE THREAD

**Issue by darkphan** [PrinceOfAmber/Cyclic#227]
See title :D

**Comment by PrinceOfAmber** [comment]
- first ill make it not break anything that is 'unbreakable'  (probably ignored if player is creative.)

- second ill add a blacklist in config for future needs (so bedrock shouldnt need to be in blacklist because of above.)

**Comment by PrinceOfAmber** [comment]
This and many other updates are live https://minecraft.curseforge.com/projects/cyclic/files/2364510
