### ISSUE TITLE
Rainbow Cannon wont Charge.

### ISSUE THREAD

**Issue by Dahenator** [PrinceOfAmber/Cyclic#2274]
Minecraft Version: 1.19

Forge Version: 

Mod Version: 1.8.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Rainbow Cannon not charging in Multiplayer or single player.

Log file link:
N/a

Video/images/gifs (direct upload or link): 
https://github.com/Lothrazar/Cyclic/issues/2169
Same Issue and this one

**Comment by Lothrazar** [comment]
affecting 1.18 and 1.19 but only while on servers, single player seems to work out
