### ISSUE TITLE
Wing charm, slow fall not ending

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#228]
Hi,

I collected a wing charm from a dungeon chest and it worked as expected for the first 24-48hrs but I've noticed that now it seems the slowfall effect is reading 0:00 but not actually terminating. It stays at 0:00 even if I put the charm in a backpack.

If I disconnect from the server and reconnect, it has cleared.

I have not tested this in SSP, nor in a stripped down pack. If you can't track it down easily, let me know and I'll see if I can narrow it down.

Cheers!

cyclic 1.10.2-1.9.9
forge 2185

**Comment by PrinceOfAmber** [comment]
'It stays at 0:00 '

Very weird, thanks for the report.  I have never seen it in SSP which is where i often play, could be a server timing thing i need to get around.

**Comment by PrinceOfAmber** [comment]
Hopefully this release fixes it, let me know ! https://minecraft.curseforge.com/projects/cyclic/files/2364510
