### ISSUE TITLE
a request for this great mod

### ISSUE THREAD

**Issue by petITA1185** [PrinceOfAmber/Cyclic#2285]
Minecraft Version: 1.19.2

im searching magic minecraft mods... and i found this. its interesting, i wanna see every item that it adds. i was going to install it, but its forge... and i have fabric. will there be a fabric port??

**Comment by ZestyBlaze** [comment]
Unfortunately not from Lothrazar, his Discord has an FAQ which states he is unlikely to ever do a Fabric port themselves

**Comment by Lothrazar** [comment]
so any time investment i make has to be worth while.. fabric is too much work. ..., id rather make cool new mods with that time.
