### ISSUE TITLE
[Request] More support 

### ISSUE THREAD

**Issue by VanCock** [PrinceOfAmber/Cyclic#2288]
So Cyclic is one of the most unique and recognisable mods out there, being especially cherished by old, players because quite a number of modpacks back then had this mod in, so with modern version of this mod being actively maintained I was wondering if there is a chance rest of the community (fabric players that is) could enjoy this masterpiece of a mod, or is this way too much work, I'm asking because I didn't found answers anywhere and having this mod in a modpack would be sick as hell.

**Comment by ZestyBlaze** [comment]
The Discord has an FAQ and I think I mentioned this in another post, but chances are slim as I don't think Lothrazar wants to support Fabric versions themself

**Comment by Lothrazar** [comment]
More support and more bugfixes? yes no problem here have fun https://legacy.curseforge.com/minecraft/mc-mods/cyclic/files/4718127

**Comment by VanCock** [comment]
My disappointment is immeasurable and my day is ruined.



For real tho, it's understandable that you're not interested in supporting fabric mod loader, I understand it and respect your decision, have a wonderful day/evening kind gentleman, good luck with your fantastic mod,
Cheers.  :)
