### ISSUE TITLE
Guide book?

### ISSUE THREAD

**Issue by blahpers** [PrinceOfAmber/Cyclic#2291]
Minecraft Version: 
1.20.1

Forge Version: 
47.0.19

Mod Version: 
1.11.1

Single Player or Server:
SP

Describe problem (what you were doing; what happened; what should have happened):
How do I acquire a guide book so that I can read the documentation? I can't find it in JEI at all, and I don't see anything under the list of givable items ('cyclic:*')

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
You need to install Patchouli, but it hasn't updated for 1.20(.x) yet.

**Comment by Lothrazar** [comment]
patchouli changed some stuff, so guidebook will be fixed in next update for 1.20

**Comment by drakosoldier298** [comment]
was the guidebook ever fixed as i cannot find it in cyclic version 1.12.4

**Comment by ScoutTheSaneless** [comment]
i second the above question

**Comment by penturt** [comment]
any solution on how to get the guide book for mc 1.20.1?

**Comment by SailorEffinMoon** [comment]
I second the last question.  Can't seem to find it anywhere :(

**Comment by eqagunn** [comment]
Can we spawn it in somehow at least in 1.20.1?

EDIT: The recipe is Compressed Cobblestone + Book.

**Comment by massacring** [comment]
This has not been solved yet, so idk why it's closed.

**Comment by HalcyonSeas73** [comment]
> This has not been solved yet, so idk why it's closed.

It's closed because this isn't an issue. Cyclic has a guide book. You need to have Patchouli installed to see it, as I mentioned earlier in the thread.

**Comment by penturt** [comment]
Can you share the crafting recipe, because I don't see it. And I have patchouli installed and jei.

**Comment by HalcyonSeas73** [comment]
> Can you share the crafting recipe, because I don't see it. And I have patchouli installed and jei.

As mentioned in another comment above, Compressed Cobblestone + a Book.

**Comment by penturt** [comment]
Why doesn't it show on jei?
