### ISSUE TITLE
Apple of Lofty Stature(Step Height) Reactivates

### ISSUE THREAD

**Issue by DTech10** [PrinceOfAmber/Cyclic#2296]
Minecraft Version: 1.19.2

Forge Version: 43.2.19

Mod Version: 1.8.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

- Step Height effect re-activates on rejoin even its deactivated last time

Log file link:
N/A

Video/images/gifs (direct upload or link): 

https://youtu.be/hb_jEfdCA0I

**Comment by Lothrazar** [comment]
yep , if you eat one to turn on, eat another to 'turn off' and rejoin the world, the turn off wasnt saved. fix on the way

**Comment by DTech10** [comment]
thx for the fix
