### ISSUE TITLE
[1.20.1] Shields Have No Texture

### ISSUE THREAD

**Issue by HalcyonSeas73** [PrinceOfAmber/Cyclic#2297]
Minecraft Version: 1.20.1

Forge Version: 47.1.3

Mod Version: 1.12.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened): Shields seem to have no texture, either equipped, displayed, or via JEI.

Video/images/gifs (direct upload or link): 
![image](https://github.com/Lothrazar/Cyclic/assets/84727791/a0ea2a69-0660-4f2f-bc80-b17bcc4a6e79)

**Comment by Lothrazar** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/cyclic/files/4718127
