### ISSUE TITLE
Latest Cyclic Verson for 1.16.5 is installing FLIB 1.20

### ISSUE THREAD

**Issue by ModernGamingWorld** [PrinceOfAmber/Cyclic#2298]
Minecraft Version:  1.16.5

Forge Version: 36.2.39

Mod Version: 
Latest 1.16.5 version

Single Player or Server: single/server

Describe problem (what you were doing; what happened; what should have happened):

Went to update to latest 1.16.5 update today and crashed stright to desktop cause Curseforge auto downloaded your FLIB 1.20 version after you update to new cyclic release

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
thanks for letting me know! Curseforged had marked it as a dependency for all versions when its only needed for 1.20.  i edited  this on curseforge so it should no longer pull it https://legacy.curseforge.com/minecraft/mc-mods/cyclic/files/4656875
