### ISSUE TITLE
[1.20.1] Experience Boost Not Functioning

### ISSUE THREAD

**Issue by TheBiggestNose** [PrinceOfAmber/Cyclic#2306]
Minecraft Version: 1.20.1

Forge Version: 47.1.43

Mod Version: Cyclic-1.20.1-1.12.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
Experience Boost is not working on any tools, when I mine something no experience is created. Have tried shift around my mods and forge version as well as cyclic version to no avail. I am unsure if its cyclic or an incompatability
I haven't touched the config, but it is set to enabled
Attatched mod list in image
Log file link:

Video/images/gifs (direct upload or link): 

![image](https://github.com/Lothrazar/Cyclic/assets/22794820/aa167825-ad44-465c-a727-58c73979fdc9)

**Comment by HalcyonSeas73** [comment]
Experience Boost now only works on things that would normally give experience, such as Coal Ore.

**Comment by TheBiggestNose** [comment]
I hope it gets made a config option instead of just how it is
![image](https://github.com/Lothrazar/Cyclic/assets/22794820/bded9b34-4a71-469f-aa05-3a02195cc270)
