### ISSUE TITLE
Placing a crate besides a torch via Bag of Holding crashes the game

### ISSUE THREAD

**Issue by Catomax262** [PrinceOfAmber/Cyclic#2308]
Minecraft Version: 
1.18.2

Forge Version: 
40.2.4

Mod Version: 
1.7.16

Single Player or Server:
Single Player

Describe problem (what you were doing; what happened; what should have happened):
For some reason it crashed my game.

Log file link:
Server: https://crashy.net/af3215c8-d15f-4ba7-b0d6-7179cd30e101
Client: https://crashy.net/96081769-c89a-46d2-8b9c-c46ae9a77df6

Video/images/gifs (direct upload or link): 
n/a

**Comment by Lothrazar** [comment]
Looks fixed to me :) thanks for the report. (also crash logs dont open, i think crashy dot net went out of business) 
![looks good](https://github.com/user-attachments/assets/a45be39f-aa50-4b1f-b490-10c2cdec55f6)
