### ISSUE TITLE
Sack of Holding crash+duplication

### ISSUE THREAD

**Issue by EggoEgo** [PrinceOfAmber/Cyclic#2313]
**Minecraft Version:** 
1.18.2
**Forge Version:** 
40.2.4
**Mod Version:** 
1.7.16
**Single Player or Server:**
Single Player
**Describe problem (what you were doing; what happened; what should have happened):**
When placing an oak chest*(quark) from a sack of holding, the game placed the block and then crashed without removing the data in the sack of holding. This allows for the chest to be placed multiple times while retaining its contents. 
*oak chest is the block I used, it may work for other blocks
**Log file link:**
[crash-2023-08-07_02.51.41-client.txt](https://github.com/Lothrazar/Cyclic/files/12273501/crash-2023-08-07_02.51.41-client.txt)
[crash-2023-08-07_02.51.42-server.txt](https://github.com/Lothrazar/Cyclic/files/12273503/crash-2023-08-07_02.51.42-server.txt)
**Video/images/gifs (direct upload or link):** 
![Cyclic Sack of holding bug](https://github.com/Lothrazar/Cyclic/assets/37640575/06bb498e-c7ae-47de-980d-081c67993c38)

**Comment by Lothrazar** [comment]
Thanks for the report!  Looks like your forge version is out of date. with 1.7.16 or 1.7.17 of cyclic and quark 3.2-358 and forge  40.2.18 this works as intended with all quark chests without crash
![quarky](https://github.com/Lothrazar/Cyclic/assets/621529/2b0f2287-faa9-4721-8d3d-f8cd3d5fccdc)
