### ISSUE TITLE
Rendered preview is half of the expected size

### ISSUE THREAD

**Issue by KraziMyTrang** [PrinceOfAmber/Cyclic#2317]
Minecraft Version: 
1.20.1

Forge Version: 
47.1.44

Mod Version: 
1.12.2

Single Player or Server:
Both

Describe problem (what you were doing; what happened; what should have happened):
When toggling the rendered preview option, the size of the preview is scaled down by 1/2. For example, instead of highlighting a 25x25 block area, the preview only highlights a 12.5x12.5 block area.

I created a 25x25 farm specifically for the harvester's max size, but after updating from 1.12.0 to 1.12.2 the preview no longer encompasses the entire farm. The same holds true for all other blocks that have this feature.

However, this appears to be only a visual bug, and all blocks still function as expected.

Images: 
Item Collector Preview in Farm
![2023-08-18_06 54 49](https://github.com/Lothrazar/Cyclic/assets/142595002/d4f8f33d-02bc-4eaa-aeaf-107e2885c01d)

Aerial Screenshots of Area Preview
![2023-08-18_07 36 40](https://github.com/Lothrazar/Cyclic/assets/142595002/858ec32c-c6ce-47b2-92be-cd91af633028)
![2023-08-18_07 37 10](https://github.com/Lothrazar/Cyclic/assets/142595002/3054ce1d-e9b2-4fe6-8ad3-d94a2e20fba0)

**Comment by Lothrazar** [comment]
Built a fix for this, and also i added another option of preview type : 
![new preview](https://github.com/Lothrazar/Cyclic/assets/621529/e136bf28-0d5f-41d6-afcf-f0636f919031)

**Comment by Lothrazar** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/cyclic/files/4718127
