### ISSUE TITLE
Mod removing Curios visibility toggle 1.20.1

### ISSUE THREAD

**Issue by aAndrew3030** [PrinceOfAmber/Cyclic#2319]
Minecraft Version: 1.20.1

Forge Version: 47.1.3

Mod Version: 1.12.4 (and previous versions) FLIB 0.0.11

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):

Cyclic is removing the visibility toggle for most mods that are using curios. Recreated in a test world with just cyclic, flib, and curios

https://github.com/TheIllusiveC4/Curios/issues/331
https://github.com/The-Nexus-Project/Limitless-7/issues/5

**Comment by HeavyDeception** [comment]
Just going to bump this as it still is happening.

**Comment by emptychild107** [comment]
same and im on 1.20.1!

**Comment by 8bitminerman** [comment]
I am experiencing the same issue

**Comment by Gbergz** [comment]
Any news on this?

**Comment by Wizqok** [comment]
same here

**Comment by Wizqok** [comment]
> Minecraft Version: 1.20.1
> 
> Forge Version: 47.1.3
> 
> Mod Version: 1.12.4 (and previous versions) FLIB 0.0.11
> 
> Single Player or Server: Singleplayer
> 
> Describe problem (what you were doing; what happened; what should have happened):
> 
> Cyclic is removing the visibility toggle for most mods that are using curios. Recreated in a test world with just cyclic, flib, and curios
> 
> [TheIllusiveC4/Curios#331](https://github.com/TheIllusiveC4/Curios/issues/331) [The-Nexus-Project/Limitless-7#5](https://github.com/The-Nexus-Project/Limitless-7/issues/5)

also happens with forge 47.2.17 on SMP

**Comment by PantACRO4life** [comment]
@Lothrazar , this is still an issue with 1.12.6
