### ISSUE TITLE
Fluid Cable does not connect to cauldrons.

### ISSUE THREAD

**Issue by Angular-Angel** [PrinceOfAmber/Cyclic#2321]
Minecraft Version: 1.20.1

Forge Version: 47.1.0

Mod Version: 1.12.4

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): When placed beneath or adjacent to a cauldron, fluid cables do not connect, and will not connect even after being right clicked on by a wrench. I know in a previous version I was able to get the to connect to the cauldrons and withdraw fluids, I was expecting that behavior to still be in place.

**Comment by HalcyonSeas73** [comment]
This is intended behaviour; vanilla cauldrons aren't _really_ fluid containers.

**Comment by Angular-Angel** [comment]
...Is that how it worked in previous versions? I could swear in an older version I had it connecting to cauldrons just fine. :/

**Comment by CKY-** [comment]
> This is intended behaviour; vanilla cauldrons aren't _really_ fluid containers.

then why is there an entire helper class dedicated to them

https://github.com/Lothrazar/Cyclic/blob/d697eca3a38b432a9e2642b7ec8862c9ab636bc3/src/main/java/com/lothrazar/cyclic/util/FluidHelpers.java#L82
this was a thing in 1.18.2 
as per the update 
https://github.com/Lothrazar/Cyclic/blob/d697eca3a38b432a9e2642b7ec8862c9ab636bc3/update.json#L101


and is very much changed in 1.19.2 + what changed I have no idea but something did....

**Comment by Lothrazar** [comment]
at some point in the past there were a few cyclic blocks that tried to push/pull from cauldron but hardcoded to water, so yeah if something changed in 1.192ish then thats a bug probably. doing a full connection with a cable to a cauldron would not make sense as not all fluids would flow but something like a Fluid Hopper it would make sense to make that interact with cauldron if possible

**Comment by Lothrazar** [comment]
As noted above, fluid cables work as intended.

Fluid Hoppers are different than cables and they DO pull from cauldrons, and then you can connect cables to the hopper output  
![fluid hopper](https://github.com/user-attachments/assets/d37c9f88-799e-4190-87ca-c1c3aa56c2be)
