### ISSUE TITLE
total 1.20.1 server crash during startup

### ISSUE THREAD

**Issue by Linksapprentice** [PrinceOfAmber/Cyclic#2323]
Minecraft Version: 
1.20.1
Forge Version: 
47.1.44
Mod Version: 
1.12.4
Single Player or Server:
server
Describe problem (what you were doing; what happened; what should have happened):
While working completely fine in single player, whenever starting the server cyclic fails to load correctly. I haven't been able to find a stray conflict or anything. 

Log file link:
https://pastebin.com/L00j6iws

Video/images/gifs (direct upload or link): 

N/A

**Comment by zpprsprk** [comment]
Same effect in NeoForge 47.1.79

**Comment by Lothrazar** [comment]
Latest versions on curse and modrinth have this fixed
