### ISSUE TITLE
[1.18.2] Pots n Stuff retrograde compat

### ISSUE THREAD

**Issue by Catomax262** [PrinceOfAmber/Cyclic#2325]
Minecraft Version: 1.18.2

Forge Version: 40.2.7

Mod Version: idk

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened):
Dude, the Gloom effect causes enemies to take some effects from Pots N Stuff, such as lightning (it spawns lightning nonstop), bomb (it makes enemies explode a lot)

I just lost EVERYTHING because of this. Please add an effect blacklist to avoid bullshit like this.

For some reason, i was fighting a Wither, and i got hit and randomly got these effects, resulting in a death and loss of over 32 THOUSANDS of valious items.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
agreed this needs to change . CC https://github.com/Lothrazar/Cyclic/issues/2217
