### ISSUE TITLE
Question about Cyclic Mod  😋

### ISSUE THREAD

**Issue by SirTwsted** [PrinceOfAmber/Cyclic#2327]
Hi,  I was told to come here for any questions by the mod page information.
Anyways,
**Will there be any chance for this mod to have a fabric version?**
Just curious.  🤔😋

**Comment by HalcyonSeas73** [comment]
There are no plans for a Fabric mod.

**Comment by Lothrazar** [comment]
aha sorry yeah i dont have time to support more than one API
