### ISSUE TITLE
idle enchantment experience boost

### ISSUE THREAD

**Issue by Liink56** [PrinceOfAmber/Cyclic#2338]
Minecraft Version: 1.20.1

Forge Version: 47.2.1

Mod Version: 

Single Player or Server: 1.12.4

Describe problem (what you were doing; what happened; what should have happened):

I gave the “experience boost II” enchantment to my netherite pickaxe, and no XP orbs are given when I break any block (example: netherrack).

I know how this enchantment works because I had already used it on another game in 1.19.2, and it worked well.

if it's a bug, please let me know, but if it's normal operation of the sequence, please tell me what I should do to use it fully.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
That enchantment was nerfed to only give extra experience on blocks that would have already given it, i.e. coal ore.

**Comment by HalcyonSeas73** [comment]
!noissue

**Comment by Liink56** [comment]
okay I see, it's a shame
