### ISSUE TITLE
[1.18.2] Evaporation generator no longer accepts liquid biomass

### ISSUE THREAD

**Issue by karikusa** [PrinceOfAmber/Cyclic#2339]
Minecraft Version:1.18.2
Forge Version:1.18.2-forge-40.2.9
Mod Version:Cyclic-1.18.2-1.7.14&15&16&17
Player or Server:Single

[Expected behavior]
Accepts liquid biomass and ecologically generates electricity as usual.

Describe problem (what you were doing; what happened; what should have happened):.
EvaporationGenerator does not generate power from liquid biomass in versions 1.7.14 and above.
It does not accept delivery in liquid hoppers or buckets.
The same problem occurs when experimenting with Cyclic by itself.
PS: Thanks for making an interesting and fun mod!

Translated with www.DeepL.com/Translator (free version)

**Comment by HalcyonSeas73** [comment]
The Evaporation Generator was never meant to accept anything other than lava. 
Edit: the game indicates you can add liquids via JSON datapack. Have you tried that?

**Comment by karikusa** [comment]
How can that be done?

**Comment by HalcyonSeas73** [comment]
> How can that be done?

They're made the same as other datapacks; for getting started, see https://minecraft.fandom.com/wiki/Data_pack. I can't provide a step-by-step tutorial on how to use them.

**Comment by karikusa** [comment]
Thanks for the advice!
I had a feeling that was the case and had done some preliminary research,
Once again, I felt that Modder is awesome.

**Comment by karikusa** [comment]
Thanks for the advice!
I had a feeling that was the case and had done some preliminary research,
Once again, I felt that Modder is awesome.
