### ISSUE TITLE
dormant creeper spore doesn't work

### ISSUE THREAD

**Issue by jlp1528** [PrinceOfAmber/Cyclic#2340]
Minecraft Version: 1.20.1

Forge Version: 1.20.1-forge-47.1.76

Mod Version: 1.12.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
A special creeper in a structure 1shot me in full netherite armor, which I thought was odd because I was also wearing the dormant creeper spore. So I tested it with just a regular creeper and yeah, it doesn't prevent explosion damage at all.

**Comment by jlp1528** [comment]
It seems this item and the arcane relic may also be conflicted by the Alchemical Veil. They seem to be working as intended without the veil equipped. I have already created an issue about the veil.

**Comment by Barriga244** [comment]
but creeper spore is for fabric/quilt
