### ISSUE TITLE
Crash after ringing the door bell

### ISSUE THREAD

**Issue by SickElmo-GH** [PrinceOfAmber/Cyclic#2347]
Minecraft Version:
1.20.1

Forge Version:
47.2.4

Mod Version:
1.20.1-1.12.4 (no other mods)

Single Player or Server:
Single Player

Describe problem (what you were doing; what happened; what should have happened):
Place the door bell, press the button, sound plays and at the end of the sound playing the game crashes.

Log file link:
https://gist.github.com/Sickelmo83/c2a37031138d3a265fdd15371396592a

**Comment by Darkosto** [comment]
I just wanted to add in the crash report for this particular bug in case it's helpful: https://gist.github.com/Darkosto/c3f5610e22be2897f1880ebe59a544bc

Thank you Lothrazar for all of your hard work and I hope you had a great holiday! 🍪 
Darkosto
