### ISSUE TITLE
Bug/Compatibility Issue w/Mekanism Jetpack

### ISSUE THREAD

**Issue by MadToilet** [PrinceOfAmber/Cyclic#235]
After experiencing a bug in the 1.10.2 Mech and Magic pack on the ATLauncher whereby I was receiving fall damage while using the mekanism jetpack even when feathering down to a soft landing I started to search for the cause. Mekanism doesn't exhibit this bug when run solo, so it seemed to be a mod conflict isue. After doing a 50/50 of mods (cutting half out, rinse repeat until I could narrow it down to 2 or more mods), I found that this bug is exhibited only with the co-existence of two mods: Cyclic and Mekanism.

Steps for reproduction of bug:
1) Install latest version of both mods
2) equip a Mekanism jetpack **AND** any boots (no fall damage taken unless wearing boots - bug negated if boots are damage negation boot, such as the slime boots from TiCo).
3) attempt to land safely with above configuration -- fall damage taken at normal rate of damage per block of height if you are above the height limit for falling without damage. This will occur regardless of how safely you land (feathering the landing).

Replicated using the following mods(vers.):

Mekanism 1.10.2-9.2.1.295 (core mod plus generators and tools mods)
OR
Mekanism-1.10.2-9.2.1.298 (core mod plus generators and tools mods)

&

Cyclic-1.10.2-1.9.12
OR
Cyclic-1.10.2-1.9.14

I will cross-post this with the mekanism team so they can look into it as well.

**Comment by PrinceOfAmber** [comment]
Thanks.  I do have a few things that affect fall damage: but they set it to zero in certain situations, and shouldn't increase it.  Theres a slowfall potion effect thats given by the potion item and an item called the Wing Charm.  But they just set player.fallDamage to zero in certain situations.  

Definitely something to look into.

**Comment by MadToilet** [comment]
Still an issue - currently using:

forge-1.10.2-12.18.3.2202-universal

MODS:
Cyclic-1.10.2-1.10.7
AND
Mekanism-1.10.2-9.2.1.298 (core mod plus generators and tools mods)

To replicate:

Steps for reproduction of bug:

1) Install latest version of both mods (and perhaps the above forge version)
2) Equip a Mekanism jetpack AND any boots (no fall damage taken unless wearing boots - bug negated if boots are damage negation boot, such as the slime boots from TiCo). I just replicated with diamond boots, so maybe start there?
3) Attempt to land safely with above configuration -- fall damage taken at normal rate of damage per block of height if you are above the height limit for falling without damage. This will occur regardless of how safely you land (feathering the landing). I'd recommend trying to land on the same block you take-off from.

Note: If you are transitioning heights from a lower to higher point, fall damage is not taken as long as you don't get above the y-level of the landing area.

**Comment by PrinceOfAmber** [comment]
I just created a new world, Equipped a jetpack full of hydrogen from creative inventory, flew up, and i took fall damage. Then i flew up and down and up again, like you said, feathering, so hover bouncing up and down about 3 blocks from the ground. and i died, i think this is what you are talking about. boots had no effect at all

Please dont think i am ignoring this issue, i know its been a while, its just a very strange one.Screenshot of mods i have installed.  next test is without cyclic and only mekanism to see difference

![modsfalldamageya](https://user-images.githubusercontent.com/621529/27021515-d637aea4-4efd-11e7-81a0-e99d96abd97f.PNG)

**Comment by PrinceOfAmber** [comment]
Yeah i see it happening now. it still doesnt make sense but i can see it

**Comment by PrinceOfAmber** [comment]
I made an unlisted video with what i see happening, so this link should work once its done processing on youtubes side  

https://youtu.be/LHTH-dt5W3c

**Comment by PrinceOfAmber** [comment]
Just saw the part about "wearing boots" . so weird but yeah it happens https://youtu.be/98-pN-Vyvks

**Comment by PrinceOfAmber** [comment]
After some trial and error i was able to change how the Launch enchantment handles key binding events in a way that still works and also stops this bug.  release 1.10.25 coming soon

**Comment by MadToilet** [comment]
Totally still playing, and thanks for the awesome follow-through on this issue. I'll update and report back!
