### ISSUE TITLE
Advanced Crafting Stick Doesn't Open GUI

### ISSUE THREAD

**Issue by RConTRS** [PrinceOfAmber/Cyclic#2351]
Minecraft Version: 1.16.5

Forge Version: 36.2.39

Mod Version: 1.5.20

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

When I Rightclick With Advanced Crafting Stick, Nothing Happens, But A Fatal Error Message Is Sent To The Log

Log file link: [1.txt](https://github.com/Lothrazar/Cyclic/files/13500931/1.txt)

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
I released an update for this https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5226389
