### ISSUE TITLE
auto crafting machine duplicate glitch

### ISSUE THREAD

**Issue by SMACZEKX** [PrinceOfAmber/Cyclic#2358]
Minecraft Version: 
1.19.2
Forge Version: 
1.19.2
Mod Version: 
Cyclic-1.19.2-1.8.2
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
When i put gold to craft into gold block at 2 it started to add up to 23 then it instant become 12 then 3 and repeat and gold is still crafted it works with other 3x3 same materials,they are taken by barrel(Sophisticated Storage) with advected hopper upgrade

Log file link:

Video/images/gifs (direct upload or link):

**Comment by DexxKnight1** [comment]
I have the same duplicate issue.

https://github.com/Lothrazar/Cyclic/assets/78975662/a0443a83-0d1b-4899-884f-2471c823a0cd
