### ISSUE TITLE
Minecraft Crash 

### ISSUE THREAD

**Issue by Ondra0741Cze** [PrinceOfAmber/Cyclic#2359]
Minecraft Version: 1.20.1

Forge Version: 47.2.16

Mod Version: cyclic 1.20.1 -1.12.6

Single Player or Server: single-player

Describe problem (what you were doing; what happened; what should have happened):

Hello, my problem is that when I upload the mod to the modpack, everything runs, the game turns on and I also play singleplayer after exploring the map for a while, but the game crashes im play modpack All The mods 9 

Log file link: 

[crash-2023-12-31_00.48.28-server.txt](https://github.com/Lothrazar/Cyclic/files/13799444/crash-2023-12-31_00.48.28-server.txt)

Video/images/gifs (direct upload or link):

**Comment by rwilkin** [comment]
I have also been getting a crash with ATM9 with Cyclic. Seems to be having an issue with chunk generation. Not entirely sure it's a problem with Cyclic or a compatability issue with another mod and Cyclic, but removing Cyclic fixes the issue and adding it in creates the issue.
ATM9 version 0.2.34 is where I'm having the issue. I have tried Cyclic versions 1.12.4, 1.12.5 and 1.12.6
ATM9 version 0.1.1 worked with Cyclic 1.12.4 with no issue. So not really sure who to report the issue to.

FML: 47.2.16
MC: 1.20.1

[crash-2023-12-31_12.28.06-server.txt](https://github.com/Lothrazar/Cyclic/files/13799940/crash-2023-12-31_12.28.06-server.txt)
[crash-2023-12-31_12.30.41-server.txt](https://github.com/Lothrazar/Cyclic/files/13799941/crash-2023-12-31_12.30.41-server.txt)
[crash-2023-12-31_12.40.12-server.txt](https://github.com/Lothrazar/Cyclic/files/13799942/crash-2023-12-31_12.40.12-server.txt)
[crash-2023-12-31_12.43.44-server.txt](https://github.com/Lothrazar/Cyclic/files/13799944/crash-2023-12-31_12.43.44-server.txt)

**Comment by HalcyonSeas73** [comment]
Try [this ](https://modrinth.com/mod/cyclic-crash-fixer)mod from Modrinth; it fixes _a_ chunk generation issue with Cyclic, originally developed for compatibility with Terralith and other world generation mods.

**Comment by rwilkin** [comment]
> Try [this ](https://modrinth.com/mod/cyclic-crash-fixer)mod from Modrinth; it fixes _a_ chunk generation issue with Cyclic, originally developed for compatibility with Terralith and other world generation mods.

Amazing! That worked like a charm. Thank you so much!

**Comment by Lothrazar** [comment]
as shown in your crash this seems to be a bug in terralith , so it should be reported to terralith devs quote  `[Reference{ResourceKey[minecraft:worldgen/biome / terralith:snowy_cherry_grove]=net.minecraft.world.level.biome.Biome@6be3d060}, Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:lush_savanna]=net.minecraft.world.level.biome.Biome@63bcfea9}]` from [crash-2023-12-31_00.48.28-server.txt](https://github.com/Lothrazar/Cyclic/files/13799444/crash-2023-12-31_00.48.28-server.txt)  , other comments seem to have some resolutions as well.
