### ISSUE TITLE
Crash on doorbell use

### ISSUE THREAD

**Issue by blagdorfinguy** [PrinceOfAmber/Cyclic#2365]
Minecraft Version: 1.20.1

Forge Version: 47.2.0

Mod Version: 1.12.4

Single Player or Server: Single Player (untested on server)

Describe problem (what you were doing; what happened; what should have happened): Right clicking doorbell. Sound played, and then game crashed.

\/ crash log \/
Log file link: https://pastebin.com/ZadYY45L

**Comment by Lothrazar** [comment]
Thanks for the report, fixed in mod version 1.12.6 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4994392
