### ISSUE TITLE
Request: Being able to toggle the Magnet enchant

### ISSUE THREAD

**Issue by BIuBOo** [PrinceOfAmber/Cyclic#2366]
Minecraft Version: any

Forge Version: any

Mod Version: any

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
The magnet enchant happens to be on many pieces of equpment when enchanting. In a multiplayer environment it is very annoying when not needed(accidentally dropping something and seeing it get dragged all over the place to a team mate, Trying to drop something but it doesnt stay). It would be great if there was a way to toggle it with either a hotkey or in the inventory.

**Comment by Lothrazar** [comment]
This is kind of built in by the nature of it being an enchantment. you can take off the armor or, what i like best is putting magnet on a shovel. then it only works if youre holding it, it doesnt pull anywhere else in the hotbar 
![magnet shovel](https://github.com/Lothrazar/Cyclic/assets/621529/8026d9d5-d64f-489a-b4d9-44089de968a9)
