### ISSUE TITLE
Item filter for item pipes don't work properly.

### ISSUE THREAD

**Issue by Rmni2** [PrinceOfAmber/Cyclic#2370]
Minecraft Version:  1.20.1

Forge Version: 1.20.1-47.2.0

Mod Version: 1.20.1-1.12.6

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
I placed a filter card that is assigned to seeds inside a pipe out so it could take the seeds and put them somewhere else, and it does work. However, if more than one seed STACKED, it won't take it. It only works when there is a single seed item then it would take it.
This happens to every stackable item, not just seeds

Log file link: 

Video/images/gifs (direct upload or link): https://youtu.be/mIqn-d-OBts

**Comment by yurikus** [comment]
Bug is most likely here:
https://github.com/Lothrazar/Cyclic/blob/179e693db439a48822e2f47dfd0f86466f02063c/src/main/java/com/lothrazar/cyclic/item/datacard/filter/FilterCardItem.java#L121

Spent good 10 minutes figuring out why nothing works

**Comment by Reikahrob** [comment]
hello, i'm an outdated coder, i love this mod but had above issue, i seem to have fix the issue. i dont know how todo pull requests.
this one line is all i changed.

if (ItemStackUtil.matches(itemTarget.getItem().getDefaultInstance(), filterPtr)) {
