### ISSUE TITLE
The ocean config needs fixing

### ISSUE THREAD

**Issue by GH-Harry** [PrinceOfAmber/Cyclic#238]
The ocean floor config for clay is messed up (says size on description but chance next to value and doesn't have a separate chance option) 
![screen shot 2017-01-15 at 14 17 06](https://cloud.githubusercontent.com/assets/18425793/21962380/60d5141a-db2d-11e6-8da9-771c043ee1ef.png)

**Comment by PrinceOfAmber** [comment]
LOL oops, good catch!

**Comment by PrinceOfAmber** [comment]
Fixed in latest release https://minecraft.curseforge.com/projects/cyclic/files/2368842
