### ISSUE TITLE
Portal Lighter Block 

### ISSUE THREAD

**Issue by LunarAnticGitHub** [PrinceOfAmber/Cyclic#2380]
Minecraft Version: any 

Forge Version: any

Mod Version: any

Single Player or Server: any

Describe problem (what you were doing; what happened; what should have happened): it's a block that takes flintsteel or a portal activator from any mod and right clicks it into a portal

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Works as intended just use redstone with it 
![works as intended](https://github.com/user-attachments/assets/889a4a0a-7514-4a25-89b9-209a00592a97)

**Comment by LunarAnticGitHub** [comment]
Nononono I was talking about the Portal lighter block using modded portal
lighting systems like Astral Dimensions Flint and Dust on Radiant Obsidian
Stuff like that

**Comment by LunarAnticGitHub** [comment]
Wait which one of my issues with this is this about
