### ISSUE TITLE
HashMap memory leak

### ISSUE THREAD

**Issue by manugame** [PrinceOfAmber/Cyclic#2383]
Minecraft Version: 1.19.2

Forge Version: 43.3.8

Mod Version: 1.8.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

On heavy modpacks, the recipe cache from UtilPackager seems to leak a lot of memory when reconnecting to a server. I can provide you my memory dump if you need it.

Log file link: none

Video/images/gifs (direct upload or link): 
![image](https://github.com/Lothrazar/Cyclic/assets/44318832/56c8fcde-e15e-4747-aa01-8578f0af629e)

**Comment by PocketSizedWeeb** [comment]
How did you generate the memory dump? I may have found the reason, but want to check myself before I submit it.

**Comment by manugame** [comment]
> How did you generate the memory dump? I may have found the reason, but want to check myself before I submit it.

Using /sparkc heapdump

Dump are located in <mcroot>/config/spark
