### ISSUE TITLE
Crash on world gen with Cyclic+Terralith

### ISSUE THREAD

**Issue by linkjankens** [PrinceOfAmber/Cyclic#2394]
Minecraft Version: 1.20.1

NeoForge Version: 47.1.103

Mod Version:
Cyclic:    1.12.7
flib:      0.0.11
Terralith  2.4.11

Single Player or Server:
Single player

Describe problem (what you were doing; what happened; what should have happened):
There's a specific interaction with Terralith and Cyclic that is causing a crash on world generation. I've removed ALL mods except for these three (flib for dependency). I create a new world, and before generation starts it'll crash. When I say this, I mean it goes to the little world gen page and says 0%, and in the console, it normally starts saying what the world gen % is. In the case with Cyclic and Terralith, it never starts the % of generation and immediately throws a wall of text and then crashes to desktop.

I have made a pack of just these three mods for showing the interaction without the background noise of the rest of the pack. I initially discovered the crash in a big modpack I made, and did the painstaking job of figuring out which mods are causing the crash. I have confirmed it is an interaction between Cyclic and Terralith, but I don't know if there's an easy fix (like a compatibility mod)

Log file link:
https://mclo.gs/a0h3Zl1

**Comment by ModernGamingWorld** [comment]
@linkjankens use this https://modrinth.com/mod/cyclic-crash-fixer, It should fix the crashing. I had to use it to stop it crashing in my 1.20.1 forge pack
