### ISSUE TITLE
Crashes the game if running on Wayland

### ISSUE THREAD

**Issue by Enderteck** [PrinceOfAmber/Cyclic#2395]
Minecraft Version: 1.20.1

Forge Version: Neforge 47.1.103 (latest at the time)

Mod Version: 1.12.7 (latest at the time)

Single Player or Server:

Client only. 
At launch, the game crashes showing a pop up. 
If the mod is disabled this issue doesn't happen in my current modpack.
This issue also happens if only a few mod from my modpack are present/enabled but it looks like usually another fixes this issue as I can normally launch the game.

I really wanted to add this mod to my modpack for the reverse crafting and other cool features but if I can't luanhc the game on Wayland, it's not worth it. The XWayland bugs are too annoying. They are detailed in the issue below.

Here's a discussion I started about supporting native Wayland on NeoForge: https://github.com/neoforged/NeoForge/issues/657

Log file link:

[latest.log](https://mclo.gs/N3Dxj5Q)

Crash report link:

[Crash Report](https://mclo.gs/8lMclZ7)

Video/images/gifs (direct upload or link):

[Screen-Recording.webm](https://github.com/Lothrazar/Cyclic/assets/123917079/972bacfe-b329-46e8-b471-300453491f14)

![Error Pop up](https://github.com/Lothrazar/Cyclic/assets/123917079/ffac3885-203b-4368-ab53-d3f9935ab9f1)

**Comment by Lothrazar** [comment]
nothing to do with wayland, as of minecraft 1.19.4 & 1.20.1 and future the mod depends on https://www.curseforge.com/minecraft/mc-mods/flib  make sure to get version 14 or higher
