### ISSUE TITLE
Feature Request and Info

### ISSUE THREAD

**Issue by G3R0N1M079** [PrinceOfAmber/Cyclic#240]
Hi.
First of all congratulation for your mod.
I like the stuffs and i really love your configuration file.
Very extensive and complete, i love the ability and the possibility to config everythings.
I love the fishnet, the ender book... your recycler is fantastic.
I like the way you make thinkgs "expensive" but use all "default" material.
A very good mod in my opinion. Very well structured
Keep your work on.

Now i have two things:

- Can you please create a "fly" ring? I know that ExtraUt2 has one but i don't like it.
  A ring that functions without baubles. A ring that function when it is in the inventory.
  In this way i can soulbound it.

- About structure builder.
  Can you add some "config" in the GUI to build "chunk platform".
  A square platform, facing the builder, may be a level "down" where placed, starting from "left chunk corner"

Thank you very much for the effort on this fantastic mob.
Enrico

**Comment by PrinceOfAmber** [comment]
Structure builder : yes absolutely, a floor option is a great idea.

Flying: i dont know if i want to add that. maybe.  FYI someone very recently made an addon mod that forced the angel ring to fit into the baubles slot https://minecraft.curseforge.com/projects/angel-ring-to-bauble

**Comment by G3R0N1M079** [comment]
Hi.
Thank Yoou for the answer.

Yes, the ring of flying is a bit overpowered.
I hate found myself without energy and can't fly... then also potion effect may be annoying.
But is my point of view...
I would something to help me no fall in the void while building in the skyblock map.... and to "travell" fast between chunk platform in skyblock ever.

Maybe a ring of partial flying? With 30 sec of fly power... and then an auto recharge time of 15 sec?
OK, the potion effect ca be a good idea... but auto rechargable.... 
In this way is less over powered and you can use to go from chunk to chunk.... "like a big jump"....

I would use it in the inventory.... not baubles... becouse soulbound doesn't function with soulbound... at least in MC 1.7.10.
In this way the ring soulbounded in the inventory if i die is always with me and i can go to take my "gravestone"....

May be an upgrade for Void Charm?

Enrico

**Comment by PrinceOfAmber** [comment]
This post did get me thinking about vertical movement lately.  I have made two new items in the last two builds, not exactly flying but,

Climbing Gloves and Rod of Elevation.  Both need placed blocks however.  Also i have the launch enchantment and the plates.

Temporary flying i would be a good fit. maybe like an item with multiple uses or a potion effect. ill look into it 👍

**Comment by PrinceOfAmber** [comment]
Also For structure builder, im adding a fourth build type called "Solid".  This will be the same as the square but filled in, so if you set Height to = 1 you can get a floor platform

**Comment by PrinceOfAmber** [comment]
Version 1.9.18 of cyclic is out.  Adds a bunch of new building modes to Structure builder, one of them is called "Solid"

So if you put in solid and put the height to = 1 you will get the floor type you wanted 👍 

Still working on a tool that will give a short burst of flying.

**Comment by G3R0N1M079** [comment]
Ah nice!!!
Thank you very much!

Il giorno dom 22 gen 2017 alle 03:38 Sam Bassett <notifications@github.com>
ha scritto:

**Comment by PrinceOfAmber** [comment]
Glowing Chorus Fruit https://minecraft.curseforge.com/projects/cyclic/files/2378420
