### ISSUE TITLE
CTD with FLIB

### ISSUE THREAD

**Issue by Rightfuldeathray** [PrinceOfAmber/Cyclic#2408]
Minecraft Version: 1.20.1

Describe problem (what you were doing; what happened; what should have happened):

CTD after FLIB's update today

Copy of FLIB Issue:
[https://github.com/Lothrazar/FLib/issues/4](https://github.com/Lothrazar/FLib/issues/4)

**Comment by oldmooshie** [comment]
I'm having this problem too. Minecraft loads fine, identical crash to the above occurs upon loading into a world.

**Comment by Lothrazar** [comment]
Update to the latest versions of everything to get the fix. Specifically

Neoforge 47.1.99+

OR
‌

(old)forge 47.1.47+
and

cyclic 1.20.1-1.12.9

flib 0.0.14

**Comment by Lothrazar** [comment]
fixed with flib-1.20.1-0.0.14
