### ISSUE TITLE
Cyclic Mattock BUG!

### ISSUE THREAD

**Issue by DR4EL** [PrinceOfAmber/Cyclic#2411]
Minecraft Version:  1.20.1

Forge Version: 47.2.23

Mod Version: 1.12.6

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): if you break a shulker box with items innit, the items disapear from the shulker box after picking it up and placing it again.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Thanks for the report! I have released the fix in the latest version  https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5778100
