### ISSUE TITLE
Unable to find config

### ISSUE THREAD

**Issue by twilight-music** [PrinceOfAmber/Cyclic#2412]
Minecraft Version: 1.20.1

Forge Version: 47.2.18

Mod Version: Cyclic-1.20.1-1.12.9.jar

Single Player or Server:server

Describe problem (what you were doing; what happened; what should have happened):
I am unable to find the config part of the mod where it disable saplings from planting itself.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by HalcyonSeas73** [comment]
I assume you mean saplings dropped from trees? Have you tried deleting the existing config so a new one can generate? Sometimes that's needed between versions when new things are added.

**Comment by Lothrazar** [comment]
this mod does not make saplings plant themselves.

I do have a different standalone mod that does exactly this, download page is https://www.curseforge.com/minecraft/mc-mods/auto-plant  and for the issue tracker it is https://github.com/Lothrazar/AutoPlant/issues 

With that mod Check the /config/ folder for an autoplant.toml file with a true false just like you described, and a block list, looks just like this https://github.com/Lothrazar/AutoPlant/blob/trunk/1.20/autoplant.toml
