### ISSUE TITLE
Game is locking up and the single player internal server is crashing due to STEP_Hight when joining a world or joining an existing world. Looks like some bad interaction between flib and cyclic, but i'm not really sure?

### ISSUE THREAD

**Issue by JBSTheGamer** [PrinceOfAmber/Cyclic#2414]
Minecraft Version: 1.20.1

Forge Version: 47.2.30

Mod Version: 1.12.9

Single Player or Server: Singleplayer

Description of the problem
When joining or launching an existing minecraft world the game locks up and it seems like the internet server is crashing.
 
Log file link: https://drive.google.com/file/d/1IZC_jllE9aXxJO4IpOsIwxpeBdynBqWQ/view?usp=sharing

**Comment by JBSTheGamer** [comment]
Downgrading FLIB to version 1.20.1-0.0.12 from version 1.20.1-0.0.13 fixed the issue. FLIB's fix to the issue of
Four PlayerUtil functions added; fix crash error with dependency CustomGameRules. Which that fix FLIB made might have broken a feature in cyclic? Not really 100% sure.

**Comment by Lothrazar** [comment]
Update to latest versions for the fix

Neoforge 47.1.99+

OR

(old)forge 47.1.47+

cyclic 1.20.1-1.12.9

flib 0.0.14

See also https://github.com/Lothrazar/FLib/issues/4
