### ISSUE TITLE
Timed out waiting for world statistics

### ISSUE THREAD

**Issue by KooKooGH** [PrinceOfAmber/Cyclic#2417]
Minecraft Version: 
1.20.1
Forge Version: 
47.2.20
Mod Version: 
1.20.9
Single Player or Server:
single player
Describe problem (what you were doing; what happened; what should have happened):
load into my world.. 
keeps stopping create from loading

Log file link:

https://mclo.gs/qvpWoDb

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
hmm.. not sure what could be causing this.  When i just have a small set of mods i can get in an out of forge and neoforge servers with no issues on my machine : 
![server list](https://github.com/user-attachments/assets/b214bdb8-f30c-40b1-a84f-6c3959c79bdf)

**Comment by KooKooGH** [comment]
As of now it seemed to have stopped, believe it has something to do with how much ram was allocated to mc
