### ISSUE TITLE
Harvester server crash.

### ISSUE THREAD

**Issue by FoxFireMC** [PrinceOfAmber/Cyclic#242]
Hello, FoxFire here, i'm the dev for TMW-Pixelmon and its server.
 We have been having crashes recently due to what is says is the harvester. I see that we are a few versions behind (we are running version 1.10.2-1.9.9) and I was wondering if simply updating the mod would fix the problem as I didnt want to go through the hassle of updating the server/mod pack and making everyone else also update their clients again just to find that is wasnt fixed (also on the note of updating I have noticed that when I updated Cyclic in the test version of the pack my frames dropped and my mem usage went up, is this also a bug that has been fixed?) also I wasnt able to read all the change logs for Cyclic before it changed again.
If you could give me an answer soon that would be great, here is the crash we have been seeing.
[crash-2017-01-19_13.19.59-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/717206/crash-2017-01-19_13.19.59-server.txt)

Keep up the good work!
  ~Fox

**Comment by PrinceOfAmber** [comment]
I dont remember fixing a bug exactly like this, but ill look into it. Thanks for the logs

**Comment by PrinceOfAmber** [comment]
Should be fixed in latest release, let me know if it happens again ill take another look https://minecraft.curseforge.com/projects/cyclic/files/2371203

**Comment by FoxFireMC** [comment]
Thanks for the quick response! I will update the pack and server pronto! This bug has been populating our crash reports for the past few days so much in fact that we had to go around removing them! 
I have one other question, when I update Cyclic my frames just drop for an unknown reason... As soon as I go back to the version we were using (1.10.2-1.9.9) the frames go back up. Is there some fix for this?

If I have any other problems I know where to come! Thanks for the continued support!
~Fox
