### ISSUE TITLE
lime flowers are causing a feature cycle order crash in cyclic version 1.12.10

### ISSUE THREAD

**Issue by superdude808** [PrinceOfAmber/Cyclic#2421]
Minecraft Version: 1.20.1

Forge Version: 47.3.5

Mod Version: 1.12.10

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened): so I would go to generate a new world and it would crash and say feature cycle order so installed cyanide to find out which mod was doing it and disable it but each time i did it would crash again with another mod being responsible till I noticed that lime flower was what preceded the supposed cause.

so I went and downgraded cyclic to 1.12.9 and it stopped crashing altogether

Log file link: would give the log file but just from loading the game to trying to load the world and it crashing has the log file at over 25MB which is causing pastebin to have an out of memory error and crashing the web page when I try to paste the text

Video/images/gifs (direct upload or link): 
[crash-2024-08-02_11.02.31-server.txt](https://github.com/user-attachments/files/16465678/crash-2024-08-02_11.02.31-server.txt)

[crash-2024-08-02_12.42.56-server.txt](https://github.com/user-attachments/files/16465674/crash-2024-08-02_12.42.56-server.txt)

[crash-2024-08-02_12.12.51-server.txt](https://github.com/user-attachments/files/16465675/crash-2024-08-02_12.12.51-server.txt)

**Comment by Shura1oplot** [comment]
The same issue here.
