### ISSUE TITLE
minecraft crash after creating a new world

### ISSUE THREAD

**Issue by koi-illuminami** [PrinceOfAmber/Cyclic#2422]
Minecraft Version:  1.20.1

Forge Version: 47.3.0

Mod Version: Cyclic- 1.20.1-1.12.10

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
game crash when:

started with a world generation prob with minecraft:frozen_peak
when expending in my SKYBLOCK modpack dev world
 
and game crash when creating a world

i used a backup instance to go back to 2 days ago before 14 mods update.
updated one mod at a time and re-launch the game with no crash while creating a new world each time
and the last one was cyclic and now it crashes again
i am now back with update Cyclic- 1.20.1-1.12.9 and everything work fine 

Log file link:

https://pastebin.com/KbsqZUPe

Video/images/gifs (direct upload or link):

**Comment by uhloin** [comment]
Also, current world is crushed when new chunk is loaded
(no issues for version Cyclic-1.20.1-1.12.9.jar)

[crash-2024-08-02_20.05.25-server.txt](https://github.com/user-attachments/files/16472744/crash-2024-08-02_20.05.25-server.txt)

**Comment by koi-illuminami** [comment]
thx to MelanX 
https://pastebin.com/KbsqZUPe

**Comment by Absolute-Chazmania** [comment]
I had basically the same issue, a testing ground modpack I have, well, the modpack is at 400 mods cyclic wasn't working in previous versions, was excited about update, was working fine for a while, crashed during wandering, got the exact same biome pointed to minecraft:frozen_peaks, but got a mod suspect but, completely off mark as after I disabled cyclic I was able to load the world just fine, the suspect I received in my crash report was Team Abnormals library mod "Blueprint" like What?

**Comment by Shotguun29** [comment]
https://pastebin.com/KhK7qerp

cyclic crash while trying to generate new chunks. 1.20.1-1.12.10

**Comment by OxyMauron** [comment]
Same issue, disabled all but the absolute minimum of mods while testing. https://pastebin.com/Zr5ME9Ri

Cyclic-1.20.1-1.12.10

**Comment by EPiC-Inc** [comment]
Can confirm, an upgrade to Cyclic 1.12.10 broke my pack. Strangely, the server keeps on running just fine but the client gets a nice disconnect message. Terrain generation is impossible in singleplayer.

**Comment by uhloin** [comment]
I can confirm the fix, the new version .11 is valid, game doesn't crash.

**Comment by Lothrazar** [comment]
Thanks for the reports and the confirmation! https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5620124
