### ISSUE TITLE
[Crash on Chunk Generation] Feature order cycle found

### ISSUE THREAD

**Issue by Eonwe98** [PrinceOfAmber/Cyclic#2424]
Minecraft Version: 1.20.1

Forge Version: 47.3.5

Mod Version: Cyclic-1.20.1-1.12.10
                      flib-1.20.1-0.0.14

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):

When loading a world new or old the game will crash most of the time. It always crashes once it starts generating specific chunks, it gives on crash: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:frozen_peaks]

If you load a world with large biomes you have a higher likelihood of the game not crashing on start but it will crash again once you enter into generation range of a frozen_peaks biome.

Edit: Issue seems to not be present in cyclic version Cyclic-1.20.1-1.12.9

Log file link:
Log:
[latest.log](https://github.com/user-attachments/files/16493863/latest.log)
Crash report:
[crash-2024-08-05_02.34.48-server.txt](https://github.com/user-attachments/files/16493870/crash-2024-08-05_02.34.48-server.txt)

Video/images/gifs (direct upload or link):

**Comment by Erakla** [comment]
I had the exact same issue and used 7zip to directly apply the changes to the absalon.json file within the package according to the provided solution by @Apollounknowndev. It resolved the issue perfectly. (Thanks for that) 👍

**Comment by Beinmann** [comment]
Real men test in production.

**Comment by Beinmann** [comment]
Think this is now solved no?

**Comment by Apollounknowndev** [comment]
Yes
