### ISSUE TITLE
Crafting Crash

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#243]
I get a crash in the crafting GUI with vanilla, the inventory 3x3 crafting, and modded crafting benches whenever I try to craft. I am not sure if this is caused by your mod or not. I am using forge 2215. Do you have any idea what is causing this?

[Crash Log](https://minecraft.curseforge.com/linkout?remoteUrl=http%253a%252f%252fpastebin.com%252fTHZutEda)

**Comment by PrinceOfAmber** [comment]
Hmm could be. Ive never had a problem with it before, at least not in hermitpack and other packs i play.  

  Which items were you crafting?  Looks like something with an ore dictionary recipe but i cant tell further than that.  I should be able to get a fix out pretty quick once i see it happening on a specific thing :)

**Comment by WenXin20** [comment]
I was trying to craft a coal block using vanilla coal, I got the crash with the inventory 3x3 crafting, in the vanilla bench, and in the TConstruct crafting table.

**Comment by PrinceOfAmber** [comment]
Ok thanks for responding.  I installed cyclic 1.9.17 and TConstruct-1.10.2-2.5.2  . Im able to craft coal blocks in the crafting station and in my 3x3 GUI. 

 I guess i have to investigate some more. 

or maybe its just a rare happenstance?

**Comment by PrinceOfAmber** [comment]
Does the crash keep happening every time you craft the coal block like that, or did it just happen the once and not the next time?  Knowing this should help me out.

I want to fix this but at this point i would be putting safeguards in blindly since i cant replicate it.  I could do that and do a test release i guess.  Thanks again for reporting this

**Comment by WenXin20** [comment]
Yes, the crash happened everytime, but, as of this point in time, I have not tested yet to see if other items crash when crafting.
Thanks, that would be helpful, I think though that there is probably another mod involved.

**Comment by PrinceOfAmber** [comment]
I think this might have been an issue with an older version of stimmedcow : nomore recipe conflict or an older forge.

Retesting everything now in new versions, with or without recipeconflict and in other mod combinations, crafting ores or other things seems to be okay.

Marking as resolved for now but if anything like this happens again feel free to reopen this or make a new issue.

**Comment by WenXin20** [comment]
Ok, thanks. I'm not sure since I haven't got the crash since I made a new modpack, but it might've been a invalid script from CraftTweaker that I had written, since I had something like this happen with viewing furnace recipies in JEI.
