### ISSUE TITLE
Game crashed after placing soundproofing facade on energy cable

### ISSUE THREAD

**Issue by 03GuB** [PrinceOfAmber/Cyclic#2440]
Minecraft Version: 
1.20.1
Forge Version: 
47.3.11
Mod Version: 
1.12.16 (latest)
Single Player or Server:
Single Player
Describe problem (what you were doing; what happened; what should have happened):
tried to place soundproofing facade on energy cable after that game crashed and now game doesnt even let me load save since now it crashes on load.

Log file link:

[crash-2024-10-26_16.56.04-client.txt](https://github.com/user-attachments/files/17530820/crash-2024-10-26_16.56.04-client.txt)

Video/images/gifs (direct upload or link):

**Comment by Darkosto** [comment]
Hey Loth!

Just wanted to chime in with more info on this bug. It's a pretty critical issue as it breaks worlds. Here are my crash reports:

Crash when facade is placed: https://gist.github.com/Darkosto/5b86847bc9682bb18580c5287da6c62e

Crash when attempting to reload world after a restart: https://gist.github.com/Darkosto/346769b461f2e759b300cb6741e9b81f


MC: 1.20.1 
Forge: 47.3.0
Cyclic Version: 1.20.1-1.12.16

**Comment by 03GuB** [comment]
I hope fix of the bug will also fix my world

**Comment by Lothrazar** [comment]
thanks for the report!
v1.12.17 is just about to release this morning with a fix for this problem so update to this when you can.  

 if your world is stuck and the update isnt published yet, downgrading back to 1.12.15 will let you load the world again and v1.12.17 fixes the issue


As a side note, there is also a config section [cyclic.blocks.facades]  where blocks and entire mods can be disallowed from being used as facades, for example rails and torches can be used as facades if you remove from this list, they wont crash just looks weird

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5868632

https://modrinth.com/mod/cyclic/version/1.20.1-1.12.17

**Comment by 03GuB** [comment]
> if your world is stuck and the update isnt published yet, downgrading back to 1.12.15 will let you load the world again and v1.12.17 fixes the issue

world still crashes. i tried with version v1.12.17,  1.12.15,  1.12.14 but still world crashes

**Comment by Lothrazar** [comment]
i might have typed the wrong version, 1.12.14 is the first version with facades which may have the crash.  

roll back to 1.12.13 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5778100 to reload the world for sure    .  and there is another update coming soon. but i have not seen a crash report from 1.12.17 yet so i cant replicate it there any reports would help
