### ISSUE TITLE
Sleeping Bag Disconnect

### ISSUE THREAD

**Issue by Nivulpis** [PrinceOfAmber/Cyclic#2446]
Minecraft Version: 1.20.1

Forge Version: 47.3.12

Mod Version: Cyclic- 1.20.1-1.13.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
If a player is using a charge item (bow, trident, etc.) and scrolls over to the cyclic sleeping bag in their inventory they are kicked from the server. This only occurs when it is a time of day that a player would be able to sleep, otherwise nothing happens.

Log file link:
The player claims no crash logs were generated on his end. Only information in server log is as follows:
[Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: **** lost connection: Disconnected
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: **** left the game

Player received this message upon disconnection:
io.netty.handler.codec.DecoderException: Received unexpected null component.

Video/images/gifs (direct upload or link): 

![Screenshot_2024-11-18_131619](https://github.com/user-attachments/assets/255d7579-ecf5-44a4-8fb5-9270b9a786fd)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/5940363
