### ISSUE TITLE
Torch Charms Are Not Functioning

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#2447]
Minecraft Version: 
1.20.1
Forge Version: 
47.3.0
Mod Version: 
1.13.1
Single Player or Server:
SP
Describe problem (what you were doing; what happened; what should have happened):
Torch Charms (both normal and caving) don't work. They both can be turned on but are not placing torches.

Log file link:

Video/images/gifs (direct upload or link): 
![image](https://github.com/user-attachments/assets/12875599-5629-440a-a737-a16e2e3f75de)

**Comment by Lothrazar** [comment]
I have been trying to replicate this on my local dev environment and my survival modpack world.  Ive  tested this on Neoforge 47.1.104 ; on forge 47.2.36 and on forge 47.3.0 with a bunch of other mods installed, in superflat worlds and regular worlds and i cannot replicate this issue.  When i try it as expected the torch charm puts on the floor and caving charm puts on walls on the side when it can.  in this recorded GIF https://imgur.com/a/zfiAcU2 its in forge 47.3.0 to match yours, and this modlist https://pastebin.com/cfG1ZZd7    (i dont have any custom world types or dimensions or worldgen)    .  

What light limits are in your config files? 

each item has a different limit and it compares that to the blocklist. if the blocks are bright it wont place, defaults are 7 and 9  

```		[cyclic.items.caving_torch]
			# Light level at which to start placing down a torch
			#Range: 0 ~ 14
			light_limit = 7
```

**Comment by Lothrazar** [comment]
in F3 its based on the Block light, i took a screenshot of my f3 so its trying to place torches since block light is zero  , less than config 
![block light](https://github.com/user-attachments/assets/abf23b34-764c-4ec8-9b8d-627b664bd93e)

**Comment by Darkosto** [comment]
Got this figured out, turns out when setting Torch Charms to have -1 durability they will not function. I had removed durability from the entirety of the mod and those two items ceased function due to that. I've fixed it by omitting the torch charms and this issue should be resolved. Thanks!
