### ISSUE TITLE
Guidebook doesn't show in JEI

### ISSUE THREAD

**Issue by kiaen1** [PrinceOfAmber/Cyclic#2449]
Minecraft Version: 
1.20.1
Forge Version: 
NeoForge 47.1.106
Mod Version: 
1.13.1
Single Player or Server:
Single
Describe problem (what you were doing; what happened; what should have happened):

Guide book doesn't show up in JEI. This is related to the  "creative_tab": "cyclic:cyclicitems", line in data\cyclic\patchouli_books\guide_book\book.json. If you edit this to "minecraft:tools_and_utilities" it properly shows in jei.

Honestly not sure if this is a JEI issue, patchouli issue, or cyclic issue. But since I can fix it via cyclic configs, I'm posting it here.

As an added bit of info, Worn Notebook from Ars Nouveau doesn't use the tools and utilities tab, and still properly shows, which further makes me think it's a cyclic related issue.

Video/images/gifs (direct upload or link): 
![image](https://github.com/user-attachments/assets/c0c10bba-4c70-4fa8-b8ad-0c7294d1510d)

**Comment by Lothrazar** [comment]
Thanks for the report! v1.13.2 has the fix
