### ISSUE TITLE
Add FLIB relation on CurseForge for 1.20+ versions of the mod!

### ISSUE THREAD

**Issue by ChromamoonMC** [PrinceOfAmber/Cyclic#2453]
Minecraft Version: 1.20+

Forge Version: 47.3.0+

Mod Version: 

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):

Please include FLIB as a relation to the mod for 1.20+ versions on CurseForge so that FLIB auto-installs alongside the mod when using the CurseForge app. Thanks!

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
I have added this about seventeen times, curseforge keeps letting it fall off . time to do number 18.   lets count how many weeks til curseforge forgets again
