### ISSUE TITLE
1.11.2 Keybind crash (H, Y, Right Bracket or Left Bracket keys dont function)

### ISSUE THREAD

**Issue by Gunzoffire** [PrinceOfAmber/Cyclic#249]
I and a few friends have been playing the new frontier modpack and they would constantly crash do to pressing either the H key or Y key keybinds by accident from cyclic inventory movement so I searched around the controls for the keybinds that were causing it as well as looking at the logs from the launcher to see which mod's name came up. I've setup a new profile in curse with only forge version 13.20.0.2226 and the cyclic mod installed and I'll press H, Y, Right Bracket or Left Bracket keys and it makes minecraft not respond so I have to exit the game by either pressing the close button or force quitting it via task manager. I'm attaching the log from the minecraft launcher. I put it in a .txt file so it would not take up the whole page.
[Cyclic Crash log.txt](https://github.com/PrinceOfAmber/Cyclic/files/731887/Cyclic.Crash.log.txt)

**Comment by PrinceOfAmber** [comment]
hopefully unbinding the keys can be a short term fix for you. ill look at doing an update to fix

**Comment by Gunzoffire** [comment]
Unbinding them is the short term fix. I was just letting you know that was happening since I haven't seen any other bug reports that mention this bug for 1.11.2.

**Comment by PrinceOfAmber** [comment]
Thanks. Im going to leave it as an open bug, since that feature still doesnt work. but im glad you stopped crashing

**Comment by PrinceOfAmber** [comment]
These are finally working again https://minecraft.curseforge.com/projects/cyclic/files/2386657
