### ISSUE TITLE
[Request] Automatic Fishing Net auto-eject & automation on sides

### ISSUE THREAD

**Issue by xenoflot** [PrinceOfAmber/Cyclic#250]
I can see that this has been partially looked at in #200 but I'm not sure how we might go about automatically extracting from the Fishing net. Putting a hopper under it does extract the contents but appears to halt production.

With cyclic 1.10.2-1.9.19 I'm unable to extract from the top face using Translocators (extracts rod, not loot), Transfer Nodes, nor ActuallyAddition's ESD.  (edit: Tried using an AA PhantomFace too and it complains. I'm guessing your inventory isn't being made available)

Perhaps you could have the Net automatically eject to an inventory that's on the top face? That way we could throw a chest on top and then use automation to clear the chest.

---

With the current restriction on available faces, I'd have to choose between having a crafter auto-insert fresh rods, OR having something auto-extract the fish. I don't have EnderIO in this pack so I can't use one conduit for both :P 

Perhaps you could set the net to halt when the rod is close to breaking so that I don't lose my Unbreaking/Luck rod? Alternatively ease the placement restrictions to expose 2 faces for automation.

**Comment by PrinceOfAmber** [comment]
Yeah i could do an inventory on/off feature. so if its off then it will drop below always as if it was full.

letting rods break or not should be doable too.

i havent thought about the faces having only one open, ill look at it. maybe 3 out of 4 sides.

**Comment by PrinceOfAmber** [comment]
By the way, if the fishing rod has mending it shouldnt break in there, it should repair itself from the fishing xp

**Comment by PrinceOfAmber** [comment]
Made a bunch of changes in the latest release, let me know what you think https://minecraft.curseforge.com/projects/cyclic/files/2374252

**Comment by xenoflot** [comment]
Wonderful! I'll update the pack next weekend and check out the changes. Thanks!
