### ISSUE TITLE
Password Trigger Pulse mode & Also if you type 'e' into the password trigger it closes the gui (inventory keybind)

### ISSUE THREAD

**Issue by BenLarge1** [PrinceOfAmber/Cyclic#251]
Maybe have the X be customizable? 

Also if you type 'e' into the password trigger it closes the gui and you have to re-open the gui to keep typing

**Comment by PrinceOfAmber** [comment]
Yeah this might make sense. I think the timer might be worth adding

  i was also thinking of ways to get it to turn off without typing in chat. maybe  remote that you key with the password and it sends that silently

**Comment by Orenthion** [comment]
You could add an option to have the Password Trigger cancel the chat event before it gets sent to the other players instead of using a remote.

**Comment by PrinceOfAmber** [comment]
Yeah i usually play single player, but it would get annoying on a server having this used like taht, makes sense.

**Comment by PrinceOfAmber** [comment]
Added that feature where it blocks the chat event so it doesnt spam everyone on server.  

I dont think a timer makes sense in this block , but you could always hook it up to a timer.  

https://minecraft.curseforge.com/projects/cyclic/files/2379189

**Comment by PrinceOfAmber** [comment]
You probably wont read this, but ive been thinking about it. instead of adding an X timer,  I think ill make it have two modes

Toggle which is default what it does now.

New "Pulse" mode, so every time you do the password it just pulses on and then off.  Like a button click, however long those are i think 10 ticks.

**Comment by PrinceOfAmber** [comment]
Also while im in there, investigate player restrictions?  Only me allowed vs all players?  Maybe look into teams/scoreboards? 
![pass](https://cloud.githubusercontent.com/assets/621529/23343892/ead381d6-fc27-11e6-9d90-b938a9b50d8f.PNG)

**Comment by PrinceOfAmber** [comment]
Added the pulse mode, and a feature for the user to claim it so nobody else can use.  FTB utilities didnt have an api that i could see. here https://minecraft.curseforge.com/projects/cyclic/files/2387579


Also im working on the 'e' closing it feature next
