### ISSUE TITLE
Scaffolding issues/suggestion

### ISSUE THREAD

**Issue by Barhandar** [PrinceOfAmber/Cyclic#255]
Firstly, it seems to be almost exact copy of OpenBlocks' scaffolding, so it shares the issues. Namely, random timer until breakage, and dropping itself when it self-breaks. I would appreciate if it didn't drop an item on self-break, only on player break, thus not cluttering. 

Secondly, it acts as a non-transparent block, i.e. kills grass underneath, the placement/break sound is unproportionately loud, and in-air placement causes ghost scaffolding blocks as well as non-synchronized scaffolding itemstack drops (i.e. requiring inventory refresh until it is visible in inventory), all in singleplayer.

Thirdly, it would be most useful if the scaffolding, instead of self-breaking at all (because if you do self-break correctly it becomes identical to Block of Sticks from Random Things), had the following properties:
* Climbable like a ladder but faster.
* Right-clicking without sneaking replaces it with the block it was clicked with (=said block is placed in its position), without dropping an item-form of scaffolding/said item-form going straight to player inventory.
* Sneak-right-clicking _with another scaffold only_ places said scaffold on the opposite side from the one clicked.
* Trying to place scaffold on another scaffold while player is too close and blocks placement with themselves extending the scaffold stack instead (vertically if standing next to scaffolding, in the direction player's looking if standing on top of scaffolding for faster bridges).

**Comment by PrinceOfAmber** [comment]
- "I would appreciate if it didn't drop an item on self-break, only on player break, thus not cluttering." , i like it, but a change like that id just make a second version of it, which is probably easier anyway
- " in-air placement causes ghost scaffolding blocks as well as non-synchronized scaffolding itemstack drops (i.e. requiring inventory refresh until it is visible in inventory), all in singleplayer" fixable

- "Climbable like a ladder but faster" ive wanted to make a block like this for a while. maybe it makes sense here 

- "acts as a non-transparent block, i.e. kills grass underneath" agree, it should let grass live just like glass does

- " the placement/break sound is unproportionately loud", ill look into it, it (should follow block volume settings )

- "Sneak-right-clicking with another scaffold only places said scaffold on the opposite side from the one clicked .... Trying to place scaffold on another scaffold while player is too close and blocks placement with themselves extending the scaffold stack instead (vertically if standing next to scaffolding, in the direction player's looking if standing on top of scaffolding for faster bridges).." this sounds fun. . also vertical building would be useful  to go with the ladder feature.

... Cool lots of little ideas in here, i commented on some of them. Ill look into some of these and some other ideas and see what happens (no promises :P )

**Comment by PrinceOfAmber** [comment]
There are now three types of scaffolding with different properties in 1.10.3  Check them out and let me know what you think

https://minecraft.curseforge.com/projects/cyclic/files/2377827
