### ISSUE TITLE
Bucket Storage Dupe

### ISSUE THREAD

**Issue by Orenthion** [PrinceOfAmber/Cyclic#259]
Minecraft & Cyclic Version: Cyclic-1.10.2-1.9.19

**Description:** When breaking a Bucket Storage block, will duplicate it if broken with a Drill from Actually Additions. If the block has buckets inside, it will produce the original and the duplicate, where the duplicate only has 1 bucket inside it.

**Reproduce:**
1. Place a Bucket Stroage down
2. Break it with a Drill
3. Reap the duplicates
4. Rinse and repeat.

**Comment by PrinceOfAmber** [comment]
Hmm, normally it fires the 'block break event' which is where i put the buckets into the item instead. 

Working on it.

**Comment by PrinceOfAmber** [comment]
Fixed, check it out  https://minecraft.curseforge.com/projects/cyclic/files/2378039
