### ISSUE TITLE
Redstone Controls for Item Magnet

### ISSUE THREAD

**Issue by danielhickman** [PrinceOfAmber/Cyclic#265]
Re: https://twitter.com/danielhickman9/status/828181624688816134

**Comment by PrinceOfAmber** [comment]
I made it turn off when you send it a redstone signal, since its been out for a while and people are used to it just working without power

**Comment by danielhickman** [comment]
Totally understandable. Cool.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2378420
