### ISSUE TITLE
Empty Sack of Holding glitch

### ISSUE THREAD

**Issue by Y0ungSandwich** [PrinceOfAmber/Cyclic#268]
We are seeing from time to time that the Empty Sack of Holding will simply eat whatever inventory/spawner it picks up. Its not always a constant. THOUGH, we are seeing and hearing about
this from servers running the pack using Sponge.

**Comment by PrinceOfAmber** [comment]
I'm not seeing this in just vanilla. I know you said its not constant though.

What modpack are you using so i can download and test it there?

**Comment by Y0ungSandwich** [comment]
Mech & Magic.

Im almost willing to bet sponge I just want sure of your position on sponge support.

**Comment by PrinceOfAmber** [comment]
The sponge team opened a bug report with me before& they helped me out; they are great people.  I want to support it but i havent installed it on my machine or ever used it.  Ill download the pack from AT launcher and then look into if i can rig up some sort of localhost sponge.

**Comment by Y0ungSandwich** [comment]
Awesome sounds great!  Love cyclic and I know my users love using it.  Only real issue we have seen was this.  Thanks.

**Comment by PrinceOfAmber** [comment]
I have it loaded on  a sponge server, i used this for setup https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html . so far ive been playing off and on hand havent seen the sack of storage destroy something yet.  i want to trach down this issue if i can anyway.  Is there anything in your logs that would help? or maybe a video of it happening.

**Comment by O-Barbaro-Desenhista** [comment]
I know something close to, if you have a inventory item in your sack and try to pick another one (if you have two sacks) this gonna make one of the sacks disapear and give you the sack with the last inventory item picked up.
