### ISSUE TITLE
Suggestion: Heart Containers

### ISSUE THREAD

**Issue by Iteries** [PrinceOfAmber/Cyclic#270]
**Suggestion**:  Heart Containers (HC), upon reaching max heart have it where the HC no longer spawn as loot.  As of right now if you eat for food source and open up inventory it will respawn back into quick slot, making it an unlimited food source.

**Comment by PrinceOfAmber** [comment]
" upon reaching max heart have it where the HC no longer spawn as loot. ", yeah that would be really cool.  Im not sure if its possible, for the chest loot might be generated whenever the chunk is created, so the player who opens it isnt known. or maybe im wrong ill have to check.

the other part if you are at max hearts, it shouldnt let you eat it and gain food.

**Comment by PrinceOfAmber** [comment]
stopped the food source thing, you just cant eat it if hearts are max. and you can always give away or uncraft the hearts you dont need from chest loot . anyway 1.10.7 is here https://minecraft.curseforge.com/projects/cyclic/files/2380823
