### ISSUE TITLE
Crash with autonomatic user with a bucket

### ISSUE THREAD

**Issue by NikGold** [PrinceOfAmber/Cyclic#271]
i was trying to milk cows with it and crash
[crash-2017-02-11_17.42.51-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/768904/crash-2017-02-11_17.42.51-server.txt)

**Comment by PrinceOfAmber** [comment]
Yeah theres some weird antix with null item stacks and entities. http://i.imgur.com/7OwcFKi.png  i havent crashed it yet myself, but i think i see where it could happen.

**Comment by PrinceOfAmber** [comment]
Try this out in latest version https://minecraft.curseforge.com/projects/cyclic/files/2380823 . Fixed a few things. open another issue if anything happens.
