### ISSUE TITLE
Feature request: Merchant Almanac tooltips for enchanted books

### ISSUE THREAD

**Issue by farigiss** [PrinceOfAmber/Cyclic#274]
![java_2017-02-21_15-15-19](https://cloud.githubusercontent.com/assets/6200968/23168560/e7237c18-f848-11e6-93c7-85abf3c9e1d7.png)

Is it possible to make the tooltip be that that of the item I'm currently hovering over?

Thanks!

**Comment by PrinceOfAmber** [comment]
Oh yeah, thats an oversight, i didnt think of that.

**Comment by PrinceOfAmber** [comment]
Adding an update for this today. Will also work with enchanted armor/tools 
![ench](https://cloud.githubusercontent.com/assets/621529/23244843/f2101b8c-f93c-11e6-91e7-7ab603baf000.png)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2385274
