### ISSUE TITLE
Entering/Creating a world with Cyclic-1.11.2-1.1.0.jar crashes the game.

### ISSUE THREAD

**Issue by DeadPigman17** [PrinceOfAmber/Cyclic#279]

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this so quick, looking into it now. Do you have a crashlog?

**Comment by PrinceOfAmber** [comment]
I just downloaded it on curse with a few other mods added, it worked for me, i was using forge-13.20.0.2252 , heres a screenshot
 


![2017-02-26_12 40 36](https://cloud.githubusercontent.com/assets/621529/23343470/e7f187d0-fc20-11e6-85e0-85b74cf16242.png)

**Comment by PrinceOfAmber** [comment]
So to fix your issue a crashlog would include a full modlist, maybe there is some mod conflict i have to fix

**Comment by blackviperr** [comment]
@PrinceOfAmber  Here is the crash log: http://pastebin.com/k68beUFg

glad i'm not the only one w this issue

**Comment by DeadPigman17** [comment]
Here's the crashlog, I'm using Forge-13.20.0.2252 and Cyclic-1.11.2-1.1.0, no other mods.

https://justpaste.it/13xsn

**Comment by DeadPigman17** [comment]
@PrinceOfAmber Here's the crashlog, I'm using Forge-13.20.0.2252 and Cyclic-1.11.2-1.1.0, no other mods.

https://justpaste.it/13xsn

**Comment by Aphyxia** [comment]
I have the same issue. 
I had 1.11.2-13.20.0.2227 also installed and I tried that. The world loaded without crash 2 times and on the third time it crashed. All these times were with bonus chest.

Latest recommended 1.11.2 - 13.20.0.2228 and latest 1.11.2 - 13.20.0.2252 both crash with the same error.

So I tried the latest version of forge again with and without bonus chest. It crashed with bonus chest and loaded fine without bonus chest. I think it is related to that.

**Comment by PrinceOfAmber** [comment]
Thanks for the crash log , i see it up there.  

Also I think i had the same thing happen to me  . putting my log in in case they are caused slightly differently 

http://pastebin.com/26F2GWCi

**Comment by PrinceOfAmber** [comment]
Looks like i found the cause.  All our crashlogs were slightly different but this should work; releasing v.1.1.2 soon.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2386900
