### ISSUE TITLE
[1.11.2] Can't break furnaces with gold/iron pickaxes because it puts it inside the furnace.

### ISSUE THREAD

**Issue by DeadPigman17** [PrinceOfAmber/Cyclic#280]

**Comment by PrinceOfAmber** [comment]
Yeah i have a feature where if you tap a furnace with a smeltable item or fuel, it tries to go right in.  For the short term you can disable this in config under "player" -> "Furnace Speed"

I forgot that tools are now smeltable in the new 1.11 update so i need to tweak this to fix

**Comment by blackviperr** [comment]
OMFG. i've been trying to figure out why that's been happening for the longest time lmao.

now I know hahahaha

**Comment by PrinceOfAmber** [comment]
This is fixed in the latest release :)
