### ISSUE TITLE
[1.11.2-1.1.0] Opening the extended inventory produces ticking player crash

### ISSUE THREAD

**Issue by Aphyxia** [PrinceOfAmber/Cyclic#281]
Steps to reproduce:
1) Eat inventory unlocking cake
2) Push R or click the R button in inventory.
http://pastebin.com/19zCrEne

**Comment by PrinceOfAmber** [comment]
Thanks for crashlog, Ill try to get a fix out later today

**Comment by PrinceOfAmber** [comment]
https://github.com/PrinceOfAmber/Cyclic/commit/9c61a9741740aaad2fc337d00a5330a0f688ad60

**Comment by PrinceOfAmber** [comment]
Fix is out https://minecraft.curseforge.com/projects/cyclic/files/2386900
