### ISSUE TITLE
[1.11.2-1.1.0] Password trigger closes on pressing inventory key.

### ISSUE THREAD

**Issue by Aphyxia** [PrinceOfAmber/Cyclic#282]
Steps to reproduce:
1) Place Password trigger
2) Right click the trigger
3) Press inventory key (default "e")

**Comment by PrinceOfAmber** [comment]
I guess i never noticed since i use CTRL for inventory.  But yes, it should let you type this as a letter and ignore the keybind

**Comment by PrinceOfAmber** [comment]
Also happens in 1.10.2 version

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2387853

**Comment by PrinceOfAmber** [comment]
Fixed in 1.10, coming soon in 1.11

**Comment by PrinceOfAmber** [comment]
1.11.2 https://minecraft.curseforge.com/projects/cyclic/files/2388149
