### ISSUE TITLE
Ender Torch/Torch launcher places 2 torches sometimes.

### ISSUE THREAD

**Issue by joye-ramone** [PrinceOfAmber/Cyclic#283]
Right now if I use Ender Torch or Torch launcher to place a torch in long range, it places two torches sometimes. Does it makes sense to fix?

**Comment by PrinceOfAmber** [comment]
Yeah I've seen this happen a few times as well. Not every time.  Hopefully its an easy fix

**Comment by joye-ramone** [comment]
Yep, for me it happens only if I throw torch for long distance on flat surface.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2387579
