### ISSUE TITLE
[1.11.2]  potion recipes not visible in JEI, but still working

### ISSUE THREAD

**Issue by DeadPigman17** [PrinceOfAmber/Cyclic#284]
I've tried to generate dungeon chests with a mod; I've found potions like haste, health boost, etc... But not viscous. Also if you have a potion like, for example, haste I, you should be able to apply it glowstone or redstone in the brewing stand to make it last longer or level II, respectively.

**Comment by PrinceOfAmber** [comment]
Yes, all the potions should have recipes.  In 1.10.2 they show up in JEI for example

![visc](https://cloud.githubusercontent.com/assets/621529/23353056/54c6f0e4-fc7f-11e6-9d2c-b138cc68edf0.PNG)


 For some reason it looks like they arent showing up in JEI in 1.11.2  ... but i just tested and they do work.  So water bottle + cocoa = the Viscous potion even in 1.11.2, ill have to see why recipe doesnt show up

**Comment by PrinceOfAmber** [comment]
Can you test and verify a recipe  is working on your end too? Hopefully its only the JEI piece not working

**Comment by DeadPigman17** [comment]
Yes, it works for me, but for some reason JEI doesn't show me the recipe.

**Comment by PrinceOfAmber** [comment]
Changed the title to reflect what we discovered

**Comment by PrinceOfAmber** [comment]
I posted a bug report to JEI, since this worked perfectly in 1.10

**Comment by PrinceOfAmber** [comment]
Make sure to update JEI as well!  https://minecraft.curseforge.com/projects/cyclic/files/2396963
