### ISSUE TITLE
texture less slabs with gentle exchange scepter (Ender I/O Issue).

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#285]
if you have a slab "Painted" by the ender I/o machine and try to exchange the "painted" slab to a slab in the world, this will spawn a texture less slab and if you break it, this will give you a texture less slab.

**Comment by PrinceOfAmber** [comment]
Got it! stone slab painted as bedrock

![stone slab painted as bedrock](https://cloud.githubusercontent.com/assets/621529/23457492/15585ba0-fe2d-11e6-8ce1-09f39e271396.png)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2387579
