### ISSUE TITLE
Automated User Crash

### ISSUE THREAD

**Issue by layne135** [PrinceOfAmber/Cyclic#286]
Hello,
I seem to be having an issue with the Automated User. It works for about five seconds, and then the game crashes. Attached is my error report. I really love this mod, and the Automated User will be used quite extensively in my world (once this crash gets fixed). Also, I'm using the Cyclic-1.10.2-1.10.11 version. Thanks! :-)
[crash-2017-02-27_22.04.12-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/805643/crash-2017-02-27_22.04.12-server.txt)

**Comment by PrinceOfAmber** [comment]
What item did you have in the user, and what entities were nearby? im trying to replicate this and not seeing any crashes.

Regardless, i can put in some safety checks/catches to hopefully avoid this.

Possibly related to old https://github.com/PrinceOfAmber/Cyclic/issues/271

**Comment by PrinceOfAmber** [comment]
Loots related to Minecraft Comes alive mod interaction

**Comment by PrinceOfAmber** [comment]
With the new update, i pointed the block at a villager from MCA, and I;m not getting any crashes.  Hopefully fix will also work for you

![2017-03-01_03 29 12](https://cloud.githubusercontent.com/assets/621529/23458056/517a79fe-fe2f-11e6-9212-d9515e85e725.png)

**Comment by layne135** [comment]
Thank you for the response! How do I get this fix into my game? I'm kind of a noob when it comes to the code.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2387579
