### ISSUE TITLE
[Feature Request] Automated using buckets

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#288]
If you can make the automated user use buckets in the liquids that it can use, this will be realy helpful.

**Comment by PrinceOfAmber** [comment]
You mean like scoop up and place liquids? Im surprised this doesnt work already :).

Dont vanilla dispensers already do this?

**Comment by PrinceOfAmber** [comment]
I tried to add this and it just didnt work right the way i wanted.  So i backed out. and since dispensers already do this then i feel like i dont need to bother.

Glad you suggested anyway keep em coming

**Comment by PrinceOfAmber** [comment]
I found an easy way to add full & empty bucket interactions so reopening this

**Comment by PrinceOfAmber** [comment]
This is in 1.10 now, ill be adding to 1.11 soon also https://minecraft.curseforge.com/projects/cyclic/files/2424001
