### ISSUE TITLE
[Feature Request]Charm, Charms ,CHARMS!!!!!!!!!

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#293]
can you make a hotkey or a config to add for the charms, because the speed charm + elytra = To a 1000 blocks in 10 seconds, so you can add a option to disable all charms  and active them Will be realy useful.

Or even better, if you can add a config for the charm to use be more powerful with more uses like, a normal charm gonna waste 1 of durabilty per second a empowered charm gonna waste 5 per second but it gonna be more powerful. (It don't gonna work well with most of the charms but nhe.... is just a Idea).

and make a charm to auto feed you or make you eat more fast.

**Comment by PrinceOfAmber** [comment]
Yeah the charms are kind of always on, they should have some way to turn them off for sure.

For the speed charm, you can equip multiple ones and the effect stacks.

"and make a charm to auto feed you or make you eat more fast." ill look into it.

**Comment by O-Barbaro-Desenhista** [comment]
I said that the speed charm is fast, but you can make more and it will be Fastest damn, those charms are powerful.

**Comment by PrinceOfAmber** [comment]
Preview of toggle on/off for charms 
![toggle](https://cloud.githubusercontent.com/assets/621529/23585447/ae8051ac-0134-11e7-9876-33adb825acf7.png)

**Comment by PrinceOfAmber** [comment]
Added the on off toggle for charms.  Havent looked into eating speed  yet.

planning that for a feature in the future.

https://minecraft.curseforge.com/projects/cyclic/files/2389366

https://minecraft.curseforge.com/projects/cyclic/files/2389358
