### ISSUE TITLE
unlimited nether stars.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#294]
with the  uncraft machine, and the exchange mod you can make unlimited nether stars with 1 iron bar, so the Idea is make a blacklist for recipes like.

Made by a nether star, you can't uncraft it.

and add a list to items that you can uncraft even with the items on the blacklist (with that you can make your mod compatible with almost every mod without even trying to).

**Comment by PrinceOfAmber** [comment]
"and the exchange mod " which mod is this? you mean Equivalent exchange aka Project E?

There is a blacklist already, in cyclicmagic.cfg if you go down to "BlacklistInput" you can block things from being crafted.  Default is

`      S:BlacklistInput <
            minecraft:end_crystal
            minecraft:magma
         >
`

But you can add minecraft:iron_ingot to that

Also there is a blacklist output version too.

**Comment by O-Barbaro-Desenhista** [comment]
for the enchange mod is this one:
https://minecraft.curseforge.com/projects/exchange-orb.
there a lot of things that you can make unlimited but its can be fixed with the config that I dind't find before, thank you.

**Comment by PrinceOfAmber** [comment]
Thanks for the link!
