### ISSUE TITLE
Forever spectador mode.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#295]
Just do it:
1. Eat a chorus fruit.
2. Die on the void or die somehow.
3. when you respawn again you will be in the spectador mode forever.

**Comment by PrinceOfAmber** [comment]
Oh weird the countdown gets lost when you die.  I forgot dying was possible in spectator, makes sense though.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2389366

https://minecraft.curseforge.com/projects/cyclic/files/2389358
