### ISSUE TITLE
[Feature Request]Better fan pls.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#296]
make a upgraded fan, because when I turn it on is just annoying when I'm pushed back, is hard to set mobtraps.

**Comment by PrinceOfAmber** [comment]
"upgraded" in what way?

I guess i could add a GUI screen so you can open it and customize.

What kind of options make sense. maybe...

speed
range
particles on/off
maybe even a pull vs push?

**Comment by O-Barbaro-Desenhista** [comment]
speed is not neded because it can push the player runing (too fast)
 range is good the upgraded version have more blocks 
particles pls turn off (can save a lot of lag)
 push is not a bad idea at all
and better with this gui you can select the entities that can or can't be pushed by the fan.

**Comment by PrinceOfAmber** [comment]
I have started working on this 🔢

**Comment by PrinceOfAmber** [comment]
WIP 
![fan wip](https://cloud.githubusercontent.com/assets/621529/23585323/7f8cfb88-0130-11e7-8cbd-c313d84ee9c9.PNG)

**Comment by O-Barbaro-Desenhista** [comment]
don't forget about the elevator vesion (Or make a elevator to push the player or the entities UP (I have a lot of uses for blocks like this).

**Comment by PrinceOfAmber** [comment]
It wasnt as easy as I thought to make it face upwards. Ill have to revisit that another time.  Possibly as a new block.

Anyway the other stuff is out here

https://minecraft.curseforge.com/projects/cyclic/files/2389366

https://minecraft.curseforge.com/projects/cyclic/files/2389358

**Comment by PrinceOfAmber** [comment]
Oh yeah, actually i already have vertical facing machines including fans in my milestone planning, so its comming eventually. maybe next weekend https://github.com/PrinceOfAmber/Cyclic/milestone/14
