### ISSUE TITLE
[Feature Request]now a armor.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#298]
make a obsidian infused armors (not just a obsidian one because this is realy unoriginal), is like the vanilla amors (your ermerald armor two) infused with obsidian, that will make the armor itself more powerful and strong (durability and defense power), at the cost of your speed(now this is unoriginal, obsdian being hearvy kkkk) this will make the speed charm (Not the push one because this one is danguerous) be more useful.

**Comment by PrinceOfAmber** [comment]
Obsidian armor that is super strong decreases your speed; yeah its a decent idea.

 "now this is unoriginal" , maybe it is. but in most of the modpacks i play in, armor like this isnt around.  

Making it just with the armor shape and obsidian blocks seems a bit boring, ill try to think of a more interesting way to make it.

**Comment by O-Barbaro-Desenhista** [comment]
just a idea, molten obsidian 
made by a obsidian block and some lava (in a forger if you want to add even more armor later)
 or make the obsidian and iron (or any metal that you want to) throwed in lava the molten iron (or the metal name) infused obsidian (what a name).

**Comment by PrinceOfAmber** [comment]
I still kind of like this idea, but at the same time i already have the purple armor with cool abilities.

And also i have emerald armor, which is the same defense as diamond but it has a bit less durability in exchange for the enchantability of gold.  I dont know if other armors would fit

Anyway here are some other good armor mods to check out 

https://mods.curse.com/mc-mods/minecraft/237366-armorplus

https://mods.curse.com/mc-mods/minecraft/245939-morevanillaarmors-mod
