### ISSUE TITLE
[Minor Issue] Uncrafting machine plays sounds and acts turned on even after it runs out of items

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#299]
if you put a item on the crafthing machine and close the inventory, when the items run out the machine still working (making noises and the bar keep charging up), its a bit anoying but is not something realy big.

**Comment by PrinceOfAmber** [comment]
Yeah ive noticed that sometimes too. It should act like its off when its actually off

**Comment by PrinceOfAmber** [comment]
The progress bar now stops if the slot is empty https://minecraft.curseforge.com/projects/cyclic/files/2393324
