### ISSUE TITLE
Recipes for CyclicMagic Items?

### ISSUE THREAD

**Issue by DesertRayne** [PrinceOfAmber/Cyclic#301]
I'm loving your mod, and learning so much from my searches. But I can't seem to find any information on the actual recipes for the items in your mod. For example, how would I craft an exchange scepter on survival? I've been searching for weeks during my off time. Can you PLEASE point me in the right direction? Thanks so much for your fun mod!

**Comment by O-Barbaro-Desenhista** [comment]
easy, use Jei(Just enough Items) :
https://minecraft.curseforge.com/projects/just-enough-items-jei/files <--- link.
If you don't want to use the mod I can make a tutorial with the recipes for you.

**Comment by PrinceOfAmber** [comment]
Sorry, i havent got around to making a wiki page.Eventually I would like to make an ingame guidebook like so many other books have; but for now i just rely on JEI

**Comment by DesertRayne** [comment]
Thank you so much for your kind reply. It would be great to see a tutorial for crafting all the items if you find time! But until then I really appreciate your advice to check out JEI. Thanks for the great mod. Your work is valued! We look forward to seeing more of your work in the future. 



Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Sam Bassett <notifications@github.com> Date: 3/6/17  6:20 PM  (GMT-08:00) To: PrinceOfAmber/Cyclic <Cyclic@noreply.github.com> Cc: DesertRayne <jasminemaroon@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [PrinceOfAmber/Cyclic] Recipes for CyclicMagic Items? (#301) 
Sorry, i havent got around to making a wiki page.Eventually I would like to make an ingame guidebook like so many other books have; but for now i just rely on JEI

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PrinceOfAmber/Cyclic","title":"PrinceOfAmber/Cyclic","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PrinceOfAmber/Cyclic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PrinceOfAmber in #301: Sorry, i havent got around to making a wiki page.Eventually I would like to make an ingame guidebook like so many other books have; but for now i just rely on JEI "}],"action":{"name":"View Issue","url":"https://github.com/PrinceOfAmber/Cyclic/issues/301#issuecomment-284600707"}}}

**Comment by PrinceOfAmber** [comment]
Yeah no problem.  Similar questions have been asked before. Previously i didnt even have tooltips in fact https://github.com/PrinceOfAmber/Cyclic/issues/140

**Comment by PrinceOfAmber** [comment]
Planning to look into making a guide book for the mod, seems like what many of the other mods are doing. https://mods.curse.com/mc-mods/minecraft/228832-guide-api

**Comment by PrinceOfAmber** [comment]
In game guide book is done https://minecraft.curseforge.com/projects/cyclic/files/2417735
