### ISSUE TITLE
crafting cake of crashing

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#302]
when a player eat or had eaten a crafting cake then logs on to the server they crash here is the crash report they get http://pastebin.com/BdtCjk6u to fix this first had to reset there player profile but then i found out turning the cake off in the config will fix it when the player logs on it removes it from there inv.

running Cyclic-1.11.2-1.1.4
Forge 2233
Minecraft 1.11.2

**Comment by PrinceOfAmber** [comment]
Yep eating that item makes a button show up on the inventory screen. and its crashing when that happens.  I should have a fix out today or tomorrow

**Comment by PrinceOfAmber** [comment]
Added a check to make sure this doesnt happen. come back if there are any issues https://minecraft.curseforge.com/projects/cyclic/files/2393324
