### ISSUE TITLE
[Minor Issue]Can't disable charm when it is being repaired.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#303]
if you charm is losing durability and winning it at the same time you can't disable it
to do it just:
1. have player stats 2 ---> https://minecraft.curseforge.com/projects/player-stats-2. or any mod that repair items on your inventory.
2. put the item repairer ability on level max.
3. have a charm on your hand.
4. try to disable it.
you can't.

**Comment by PrinceOfAmber** [comment]
So i downloaded player stats. Upped my item repair to 20/20  Grabbed my speed charm and damaged it.

I can still disable it just fine.  Well, sometimes it does fail. but thats vanilla minecraft behavior, if its already in the middle of being used by teh repair, then the item is just busy.  BUT< it looks like it doesnt get repaired unless you are holding it in your hand.  In your step 3.  So, just disable it when its not in your hand.  So yeah i tried, but thats the way vanilla minecraftt just works

Thanks for bug report anyway. and i learned about a cool mod i didnt know about.
