### ISSUE TITLE
[Bug] [1.11.2] Controlled Miner Cannot Break Sugarcane

### ISSUE THREAD

**Issue by Calvin315** [PrinceOfAmber/Cyclic#306]
Hello, 

I was trying to make a farm using the controlled miner, however, it cannot break sugarcane. I have tested it on the 1x1 and 15x15 area settings with a height of 1.
While using the block breaker, it can break the sugarcane block without a problem.

Thanks~

**Comment by PrinceOfAmber** [comment]
Are you playing in 1.10 or 1.11?


It seems to work for me in 1.10 version

**Comment by Calvin315** [comment]
I am playing on 1.11.2.

**Comment by PrinceOfAmber** [comment]
Works perfectly for me here, let me know if anythings up https://minecraft.curseforge.com/projects/cyclic/files/2393324
