### ISSUE TITLE
[1.11.2] Whitelist Sugar Cane Fails to Break

### ISSUE THREAD

**Issue by Calvin315** [PrinceOfAmber/Cyclic#310]
Hello Again,

Great work on the implementation of the whitelist, however there seems to be another problem. When you place sugar cane into the whitelist it ignores the sugar canes, other than that everything seems to be working perfectly. 
The whitelist seems to work fine for all other items.

Thanks!

**Comment by PrinceOfAmber** [comment]
Yeah, if its set to blacklist and its empty it breaks sugar cane no problem. but as whitelist it doesnt detect that sugar cane item matches with sugar cane the block, but other blocks can match. Working on a fix

**Comment by PrinceOfAmber** [comment]
Try it now :) https://minecraft.curseforge.com/projects/cyclic/files/2395255
