### ISSUE TITLE
ItemPasswordRemote doesn't toggle block lever is attached to

### ISSUE THREAD

**Issue by MurphysChaos** [PrinceOfAmber/Cyclic#312]
Place redstone dust, place block above, place lever on block. Bind remote to lever. Activate remote, lever flips but redstone doesn't get powered.

The BlockLever class from Minecraft includes calls to notifyNeighborOfStateChange that aren't included as part of ItemPasswordRemote.trigger(ItemStack,World,EntityPlayer).

I believe the code below will fix the issue but I'm new to Minecraft modding and have had trouble getting Single Player to start after building Cyclic (client starts but crashes when trying to join game). ItemLever places the similar code immediately after the sound effect.

Code is:

```
worldIn.notifyNeighborsOfStateChange(pointer, blockState.getBlock(), false);
EnumFacing enumfacing = ((BlockLever.EnumOrientation)blockState.getValue(BlockLever.FACING)).getFacing();
worldIn.notifyNeighborsOfStateChange(pointer.offset(enumfacing.getOpposite()), blockState.getBlock(), false);
```

**Comment by PrinceOfAmber** [comment]
Ah thanks. Yeah looks like its not sending a block update to the neighbours... you are on the right track.

**Comment by PrinceOfAmber** [comment]
notifyNeighborsOfStateChange was the right function, but i had to pass 'true' to the last argument. Also i had to trigger this on the lever position and in all 6 directions, so .up(), .east(), etc

**Comment by PrinceOfAmber** [comment]
This should work, let me know how it goes https://minecraft.curseforge.com/projects/cyclic/files/2395255

**Comment by MurphysChaos** [comment]
Works perfectly, thanks!
