### ISSUE TITLE
Aquaculture & Automatic Fishing Net

### ISSUE THREAD

**Issue by InkDragon** [PrinceOfAmber/Cyclic#317]
can support for aquaculture fishing rods(wooden, iron,golden, diamond) be added to the fishing net? currently you can not insert them into it

**Comment by PrinceOfAmber** [comment]
Yeah, that shouldnt be too difficult

**Comment by InkDragon** [comment]
thank you <3

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2396963
