### ISSUE TITLE
[Feature Request] Prospector Customization

### ISSUE THREAD

**Issue by ulkunderscore** [PrinceOfAmber/Cyclic#321]
I am trying to put together a modpack with large but rare ore veins and ran into some issues.
The Prospector doesn't play well with modded blocks and air blocks, it will show code names that can be quite useless, like "tile.immersivengineering.name 2".
I am not sure if this can be fixed automatically. If not it would be nice to have an config option to specify names. Something like `Display: "tile.immersiveengineering.name 2" = "Lead Ore"` (or whatever I'm not a code sorcerer).
Also a blacklist would be handy, with air block activated by default. Maybe even with a reverse to whitelist function, to only show ores or "found nothing".

Thanks for considering these suggestions. Great mod by the way, it deserves more attention.

**Comment by PrinceOfAmber** [comment]
Yes it should show the translated language name, just like the one that shows on the block in your inventory.

**Comment by PrinceOfAmber** [comment]
I assume youre using 1.10.2 because you mentioned immersive eng

**Comment by PrinceOfAmber** [comment]
I think adding a blacklist makes the most sense.  I can default it to air, stone, dirt, and gravel.  Then any pack developers can add other things if desired, such as coal, or modded versions of dirt/stone such as marble or limestone.

Then ill just make sure it sends some sort of "nothing found" message if needed.

![2017-03-27_21 49 50](https://cloud.githubusercontent.com/assets/621529/24389564/691498c0-1337-11e7-9d83-3901c1ee6263.png)

**Comment by PrinceOfAmber** [comment]
Language issue fixed.

next Ill either just do a blacklist, or ill try MAYBE to make it go both ways.  Maybe a flag "isBlacklist: true" but you can switch to false in config to invert.

![2017-03-27_22 31 24](https://cloud.githubusercontent.com/assets/621529/24390425/a0043a92-133d-11e7-98af-76bb9b30b651.png)

**Comment by PrinceOfAmber** [comment]
Uploaded release, check it out once curse approves it

https://minecraft.curseforge.com/projects/cyclic/files/2398276

**Comment by ulkunderscore** [comment]
Thanks for the changes!
I tested it with a bunch of mods and it worked like a charm.
I haven't tried to do a whitelist yet but I'll report back if I run into issues.
