### ISSUE TITLE
[1.11.2] [v1.2.3] Crash when using Trader Book in a considerable distance of villager

### ISSUE THREAD

**Issue by xLastt** [PrinceOfAmber/Cyclic#324]
> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (?CxLibrary [1.4.0].jar)
  LoadingPlugin (•ChunkAnimator [1.2].jar)
  FarseekCoreMod (?Farseek 2.1.jar)
  DynamicSurroundingsCore (?DynamicSurroundings 3.3.1.1 [Sound Exp].jar)
  RBLoadingPlugin (•RealBench [1.3.2].jar)
  NWRTweak (•RedStonePaste [1.7.4].jar)
  LoadingPlugin (?Quark r1.2-86 [Vanilla Exp].jar)
  IvToolkit (?IvToolkit [1.3.2.1].jar)
  LoadingPlugin (•RandomThings 3.8.1 [Random Exp].jar)
  DLFMLCorePlugin (•DynamicLights 1.0.0.jar)
  MalisisCorePlugin (?malisiscore 5.1.1.jar)
  ShetiPhian-ASM (?ShetiphianCore [3.4.2].jar)
  MMFMLCorePlugin (•MultiMine [1.0].jar)
  MalisisSwitchesPlugin (?Malisisswitches 4.1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 3/27/17 9:00 PM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.lothrazar.cyclicmagic.gui.villager.GuiMerchantBetter$GuiButtonPurchase.func_146112_a(GuiMerchantBetter.java:126)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:72)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at com.lothrazar.cyclicmagic.gui.GuiBaseContainer.func_73863_a(GuiBaseContainer.java:73)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1425)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.lothrazar.cyclicmagic.gui.villager.GuiMerchantBetter$GuiButtonPurchase.func_146112_a(GuiMerchantBetter.java:126)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:72)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at com.lothrazar.cyclicmagic.gui.GuiBaseContainer.func_73863_a(GuiBaseContainer.java:73)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)

-- Screen render details --
Details:
	Screen name: com.lothrazar.cyclicmagic.gui.villager.GuiMerchantBetter
	Mouse location: Scaled: (256, 191). Absolute: (512, 384)
	Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['xLastt'/1092, l='MpServer', x=22.49, y=64.00, z=163.62]]
	Chunk stats: MultiplayerChunkCache: 281, 281
	Level seed: 0
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,256), Chunk: (at 8,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 68251 game time, 27696 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 50 total; [EntitySkeleton['§7Esqueleto§r'/48186, l='MpServer', x=74.50, y=15.00, z=116.50], EntityCreeper['§aCreeper§r'/48188, l='MpServer', x=76.50, y=15.00, z=116.50], EntityPlayerSP['xLastt'/1092, l='MpServer', x=21.28, y=68.00, z=267.86], EntitySheep['§bOveja§r'/125, l='MpServer', x=-21.48, y=76.00, z=153.75], EntityVillager['Aldeano'/133, l='MpServer', x=18.50, y=69.00, z=197.50], EntityVillager['Aldeano'/135, l='MpServer', x=16.40, y=74.00, z=183.50], EntityChicken['§bGallina§r'/137, l='MpServer', x=28.11, y=69.00, z=229.33], EntityChicken['§bGallina§r'/138, l='MpServer', x=-32.14, y=68.00, z=231.75], EntityChicken['§bGallina§r'/139, l='MpServer', x=23.22, y=68.00, z=218.30], EntityVillager['Aldeano'/144, l='MpServer', x=3.49, y=75.00, z=184.58], EntityVillager['Aldeano'/145, l='MpServer', x=43.30, y=63.00, z=163.30], EntityVillager['Aldeano'/146, l='MpServer', x=43.70, y=63.00, z=163.70], EntityVillager['Aldeano'/147, l='MpServer', x=38.50, y=68.00, z=196.41], EntityVillager['Aldeano'/148, l='MpServer', x=22.67, y=64.00, z=158.50], EntityChicken['§bGallina§r'/149, l='MpServer', x=-23.32, y=68.00, z=232.86], EntityVillager['Aldeano'/161, l='MpServer', x=69.69, y=64.00, z=141.41], EntityVillager['Aldeano'/162, l='MpServer', x=70.57, y=64.00, z=141.14], EntityVillager['Aldeano'/163, l='MpServer', x=66.46, y=67.00, z=159.44], EntityChicken['§bGallina§r'/170, l='MpServer', x=74.50, y=67.00, z=221.50], EntityChicken['§bGallina§r'/171, l='MpServer', x=75.50, y=67.00, z=222.50], EntityChicken['§bGallina§r'/172, l='MpServer', x=76.50, y=69.00, z=225.50], EntityChicken['§bGallina§r'/173, l='MpServer', x=77.50, y=69.00, z=224.50], EntitySheep['§bOveja§r'/174, l='MpServer', x=77.50, y=68.00, z=222.50], EntitySheep['§bOveja§r'/175, l='MpServer', x=77.50, y=68.00, z=223.50], EntitySheep['§bOveja§r'/176, l='MpServer', x=78.50, y=69.00, z=225.50], EntitySheep['§bOveja§r'/177, l='MpServer', x=80.50, y=69.00, z=225.50], EntitySkeleton['§7Esqueleto§r'/48335, l='MpServer', x=17.50, y=17.00, z=139.50], EntityZombie['§2Zombi§r'/48355, l='MpServer', x=1.05, y=39.00, z=228.68], EntityZombie['§2Zombi§r'/48356, l='MpServer', x=-6.50, y=41.00, z=219.50], EntityPlayerDummy['entity.PlayerDummy.name'/43267, l='MpServer', x=22.49, y=64.00, z=163.62], EntitySkeletonHorse['§7Caballo esqueleto§r'/44294, l='MpServer', x=-43.52, y=67.00, z=113.96], EntityPig['§bCerdo§r'/44301, l='MpServer', x=57.80, y=63.00, z=125.75], EntityPlayerSP['xLastt'/1092, l='MpServer', x=78.69, y=59.00, z=86.18], EntitySkeleton['§7Esqueleto§r'/48491, l='MpServer', x=66.50, y=38.00, z=232.50], EntityZombie['§2Zombi§r'/48515, l='MpServer', x=84.50, y=48.00, z=160.50], EntityCreeper['§aCreeper§r'/41440, l='MpServer', x=91.50, y=34.00, z=322.50], EntityPlayerDummy['entity.PlayerDummy.name'/42476, l='MpServer', x=-7.37, y=92.17, z=278.18], EntityPig['§bCerdo§r'/44573, l='MpServer', x=48.54, y=73.00, z=98.27], EntitySkeletonHorse['§7Caballo esqueleto§r'/40628, l='MpServer', x=3.09, y=67.00, z=213.98], EntityPlayerDummy['entity.PlayerDummy.name'/41706, l='MpServer', x=18.32, y=94.23, z=272.18], EntitySkeleton['§7Esqueleto§r'/47882, l='MpServer', x=73.50, y=16.00, z=116.73], EntityPig['§bCerdo§r'/44889, l='MpServer', x=33.73, y=68.00, z=85.50], EntityPig['§bCerdo§r'/44890, l='MpServer', x=42.54, y=71.00, z=91.70], EntityPlayerSP['xLastt'/1092, l='MpServer', x=22.49, y=64.00, z=163.62], EntityVillager['Aldeano'/10185, l='MpServer', x=74.28, y=69.00, z=141.15], EntityVillager['Aldeano'/10187, l='MpServer', x=86.27, y=77.94, z=135.77], EntityItemLoot['item.item.egg'/44010, l='MpServer', x=23.57, y=68.00, z=217.47], EntityPlayerSP['xLastt'/1092, l='MpServer', x=23.22, y=66.00, z=205.50], EntityZombieHorse['§bCaballo §2zombi§r'/33789, l='MpServer', x=-39.04, y=69.00, z=235.05], EntitySkeleton['§7Esqueleto§r'/48126, l='MpServer', x=45.50, y=19.00, z=96.50]]
	Retry entities: 4 total; [EntityCreeper['§aCreeper§r'/41440, l='MpServer', x=91.50, y=34.00, z=322.50], EntityCreeper['§aCreeper§r'/41441, l='MpServer', x=92.50, y=34.00, z=320.50], EntityPlayerDummy['entity.PlayerDummy.name'/41706, l='MpServer', x=18.32, y=94.23, z=272.18], EntityPlayerDummy['entity.PlayerDummy.name'/42476, l='MpServer', x=-7.37, y=92.17, z=278.18]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1962655752 bytes (1871 MB) / 4615794688 bytes (4401 MB) up to 5355339776 bytes (5107 MB)
	LiteLoader Brand: 1.11.2-SNAPSHOT-r23F62BD-b2-2
	LiteLoader Mods: 2 loaded mod(s)
          - Autofish version 0.6.1
          - WorldEditCUI version 1.11.2_00
	LaunchWrapper: 41 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: $wrapper.atomicstryker.multimine.common.fmlmagic.MMTransformer
          - Transformer: $wrapper.pw.prok.realbench.asm.RBTransformer
          - Transformer: $wrapper.vazkii.quark.base.asm.ClassTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: $wrapper.cubex2.cxlibrary.CoreModTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: pw.prok.realbench.asm.RBAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.lumien.chunkanimator.asm.ClassTransformer
          - Transformer: $wrapper.lumien.randomthings.asm.ClassTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.transformer.MalisisRendererTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.icon.asm.TextureMapTransformer
          - Transformer: $wrapper.net.malisis.core.util.clientnotif.ClientNotifTransformer
          - Transformer: $wrapper.net.malisis.switches.asm.MalisisSwitchesTransformer
          - Transformer: $wrapper.shetiphian.core.asm.ClassTransformer
          - Transformer: $wrapper.farseek.core.FarseekClassTransformer
          - Transformer: $wrapper.net.fybertech.nwr.NWRTransformer
          - Transformer: $wrapper.org.blockartistry.mod.DynSurround.asm.Transformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 92
	FML: MCP 9.38 Powered by Forge 13.20.0.2253 Optifine OptiFine_1.11.2_HD_U_B7 101 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2253.jar) 
	UCHIJAAAA	forge{13.20.0.2253} [Minecraft Forge] (forge-1.11.2-13.20.0.2253.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	malisiscore{1.11.2-5.1.1} [MalisisCore] (?malisiscore 5.1.1.jar) 
	UCHIJAAAA	malisisadvert{1.11.2-5.1.0} [Malisis Advert] ([M]-MalisisAdvert [5.1.0].jar) 
	UCHIJAAAA	worldedit{6.1.6} [WorldEdit] ([M]-Worldedit [6.1.6].jar) 
	UCHIJAAAA	additionalenderblocks{1.1} [Additional Ender Blocks] (AdditionalEnderBlocks-1.11-1.1.jar) 
	UCHIJAAAA	visiblearmorslots{3.1.1} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.1.1.jar) 
	UCHIJAAAA	thinkbigcore{1.6.1} [§5§m===§r §e§lThink Big Core §5§m===§r] (?ThinkBigCore [1.6.1].jar) 
	UCHIJAAAA	adinferos{1.2.6} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (•AdInferos 1.2.6 [Inferno Exp].jar) 
	UCHIJAAAA	aether_legacy{v1.4} [Aether Legacy] (•Aether 1.4 [Heaven Exp].jar) 
	UCHIJAAAA	babyanimals{1.11} [Baby Animals Model Swapper] (•BabyAnimals.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (•Baubles [1.4.3][D].jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (•Better BedRockGen 6.0.1.jar) 
	UCHIJAAAA	quark{r1.2-86} [Quark] (?Quark r1.2-86 [Vanilla Exp].jar) 
	UCHIJAAAA	betterwithmods{1.1.1} [Better With Mods] (•Better With Mods 1.1.1 [Better Exp].jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2169} [Biomes O' Plenty] (•BiomesOPlenty 6.0.2.2169 [Biomes Exp].jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (•BirdsNests 1.5.1.jar) 
	UCHIJAAAA	chiselsandbits{13.9} [Chisels & Bits] (•ChiselSandBits [13.9].jar) 
	UCHIJAAAA	chunkanimator{1.2} [Chunk Animator] (•ChunkAnimator [1.2].jar) 
	UCHIJAAAA	cleanchat{1.0.0} [Clean Chat] (•CleanChat 1.0.0.jar) 
	UCHIJAAAA	controlling{2.0.4} [Controlling] (•Controlling-2.0.4.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.13} [Cooking for Blockheads] (•CookingForBlockheads 5.3.13 [Cook Exp].jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (•CosmeticArmorRe 1a.jar) 
	UCHIJAAAA	customcrosshairmod{0.7.1} [Custom Crosshair Mod] (•Crosshair v071 [Cross Exp].jar) 
	UCHIJAAAA	customnpcs{1.11.2} [CustomNPCs] (•CustomNPCs [Npc Exp].jar) 
	UCHIJAAAA	cyclicmagic{1.2.3} [Cyclic] (•Cyclic 1.2.3 [Unkown Exp].jar) 
	UCHIJAAAA	dmonsters{1.142} [Deadly Monsters] (•Deadly Monsters 1.142 [Monsters Exp].jar) 
	UCHIJAAAA	dynamiclights{1.4.6} [Dynamic Lights] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (•DynamicLights 1.0.0.jar) 
	UCHIJAAAA	fairylights{2.1.0} [Fairy Lights] (•FairyLights 2.1.0 [Lights Exp].jar) 
	UCHIJAAAA	fbp{2.0.1} [Fancy Block Particles] (•FancyBlockParticles [2.0.1].jar) 
	UCHIJAAAA	inventory_x{1.11-1.0.2} [Inventory X] (•InventoryX 1.0.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (•JourneyMap 5.4.6 [Map Exp].jar) 
	UCHIJAAAA	jei{4.2.10.250} [Just Enough Items] (•Just Enough Items 4.2.10.250 [Recipes Exp].jar) 
	UCHIJAAAA	limelib{1.4.0} [LimeLib] (•Limelib [1.4.0].jar) 
	UCHIJAAAA	logicaldrops{0.9.4} [Logical Drops] (•LogicalDrops 13.20.0.2201.jar) 
	UCHIJAAAA	minemenu{1.5.0} [MineMenu] (•MineMenu 1.5.0.jar) 
	UCHIJAAAA	minicoal{1.0} [MiniCoal] (•Minicoal 1.0.jar) 
	UCHIJAAAA	morepaintings{1.10.2-3.2.0.1} [Paintings++] (•MorePaintings 3.2.0.1 [Paintings Exp].jar) 
	UCHIJAAAA	moreplayermodels{1.11.0} [MorePlayerModels] (•MorePlayerModels [Skin Exp].jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (•MouseTweaks 2.8.jar) 
	UCHIJAAAA	multimine{1.5.6} [Multi Mine] (•MultiMine [1.0].jar) 
	UCHIJAAAA	guilib{1.11 : updated by subaraki} [GUI Library] (•PaintSelection 1.0.0 [Gui Exp].jar) 
	UCHIJAAAA	paintingselgui{1.11 v1: updated by Subaraki} [PaintingSelectionGui] (•PaintSelection 1.0.0 [Gui Exp].jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (?ShetiphianCore [3.4.2].jar) 
	UCHIJAAAA	platforms{1.3.2} [Platforms] (•Platforms 1.3.2.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (•QuickLeafDecay 1.2.3.jar) 
	UCHIJAAAA	randomthings{3.8.1} [Random Things] (•RandomThings 3.8.1 [Random Exp].jar) 
	UCHIJAAAA	reccomplex{1.2.10} [Recurrent Complex] (•RecurrentComplex 1.2.10 [Structures Exp].jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (•RedStonePaste [1.7.4].jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.635} [Reliquary] (•Reliquary [1.3.3.635].jar) 
	UCHIJAAAA	reptilemod{3.6.2} [Reptile Mod] (•Reptilemod 3.6.2-65.jar) 
	UCHIJAAAA	roughmobs{1.0} [Rough Mobs] (•RoughMobs 1.0.9 [Difficult Exp].jar) 
	UCHIJAAAA	spikemod{1.11.2-1.2.1} [Spike Mod] (•spikemod 1.2.1.jar) 
	UCHIJAAAA	storageboats{1.6} [Storage Boats Mod] (•StorageBoats [1.9].jar) 
	UCHIJAAAA	fireballs{1.0} [fireballs] (•ThrowableFireballs 0.1.jar) 
	UCHIJAAAA	utopia{A_0.3} [Utopia] (•Utopia [A_0.3].zip) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (•VeinMiner 0.35.3.605.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (•VeinMiner 0.35.3.605.jar) 
	UCHIJAAAA	newthings{1.1-1.11.2} [101 New Things] (?101 New Things 1.3-1.11.2.jar) 
	UCHIJAAAA	botania{r1.9-342} [Botania] (?Botania r1.9-342 [Testing Exp].jar) 
	UCHIJAAAA	furniture{1.1.3} [How 'Bout That Furniture] (?HowBoutThatFurniture [1.2.1].jar) 
	UCHIJAAAA	cxlibrary{1.4.0} [CXLibrary] (?CxLibrary [1.4.0].jar) 
	UCHIJAAAA	multipagechest{1.8.0} [Multi Page Chest] (?MultiPageChest [1.8.0].jar) 
	UCHIJAAAA	packingtape{1.11.0-0.6.1} [Packing Tape] (?PackingTape [0.6.1].jar) 
	UCHIJAAAA	pg{0.6.5} [Power Gems] (?Power Gems 0.6.5.jar) 
	UCHIJAAAA	thutcore{4.3.2} [ThutCore] (?ThutCore [4.3.2].jar) 
	UCHIJAAAA	thuttech{5.0.0} [Thut's Tech] (?Thuttech [5.0.0].jar) 
	UCHIJAAAA	weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (?weaponcaseloot-1.11.2-5.0.3-beta.jar) 
	UCHIJAAAA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (?malisisdoors 6.1.0.jar) 
	UCHIJAAAA	malisisswitches{1.11.2-4.1.0} [Malisis Switches] (?Malisisswitches 4.1.0.jar) 
	UCHIJAAAA	farseek{2.1} [Farseek] (?Farseek 2.1.jar) 
	UCHIJAAAA	streams{0.3} [Streams] (?Streams [0.3].jar) 
	UCHIJAAAA	chatflow{ANT:VERSION} [ChatFlow] (?ChatFlow 1.3-6.jar) 
	UCHIJAAAA	dsurround{3.3.1.1} [Dynamic Surroundings] (?DynamicSurroundings 3.3.1.1 [Sound Exp].jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (?ForgeCreeperHeal 1.3.0.jar) 
	UCHIJAAAA	forgecreeperheal{1.3.0} [[Unofficial] Forge Creeper Heal] (?ForgeCreeperHeal 1.3.0.jar) 
	UCHIJAAAA	furnus{1.91} [Furnus] (?Furnus [1.91].jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (?Hopperducts [1.4.9].jar) 
	UCHIJAAAA	itemeditor{1.11.x-0.1.0.1} [Item Editor GUI] (?ItemEditor [0.1.0.1].jar) 
	UCHIJAAAA	itemzoom{1.2} [Item Zoom] (?ItemZoom [1.2].jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (?NoMoreRecipeConflict 0.6.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (?Pam's HarvestCraft 1.11.2g [Food Exp].jar) 
	UCHIJAAAA	rfpr{8.1.1} [Real First-Person Render] (?RealFirst-PersonRender [8.1.1].jar) 
	UCHIJAAAA	realdrops{1.1.8} [Realistic Item Drops] (?RealisticItemDrops 1.1.8 [Relism Exp].jar) 
	UCHIJAAAA	rpghud{3.4} [RPG-Hud] (?RPG-HUD 3.4.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (?SoundFilters [0.9].jar) 
	UCHIJAAAA	waddles{0.5.1} [Waddles] (?Waddles [0.5.1].jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (?AutoRegLib 1.1-4.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (?CxLibrary [1.4.0].jar)
  cubex2.cxlibrary.CoreModTransformer
LoadingPlugin (•ChunkAnimator [1.2].jar)
  lumien.chunkanimator.asm.ClassTransformer
FarseekCoreMod (?Farseek 2.1.jar)
  farseek.core.FarseekClassTransformer
DynamicSurroundingsCore (?DynamicSurroundings 3.3.1.1 [Sound Exp].jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
RBLoadingPlugin (•RealBench [1.3.2].jar)
  pw.prok.realbench.asm.RBTransformer
NWRTweak (•RedStonePaste [1.7.4].jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (?Quark r1.2-86 [Vanilla Exp].jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (?IvToolkit [1.3.2.1].jar)
  
LoadingPlugin (•RandomThings 3.8.1 [Random Exp].jar)
  lumien.randomthings.asm.ClassTransformer
DLFMLCorePlugin (•DynamicLights 1.0.0.jar)
  atomicstryker.dynamiclights.common.DLTransformer
MalisisCorePlugin (?malisiscore 5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ShetiPhian-ASM (?ShetiphianCore [3.4.2].jar)
  shetiphian.core.asm.ClassTransformer
MMFMLCorePlugin (•MultiMine [1.0].jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
MalisisSwitchesPlugin (?Malisisswitches 4.1.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8400GS/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2253
	LWJGL: 2.9.4
	OpenGL: GeForce 8400GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §e§cBlax§fCraft§f - BDcraft Music (incompatible), §e§cBlax§fCraft§f - BDcraft Sounds (incompatible), §e§cBlax§fCraft§f - Resources Mods (incompatible), §e§cBlax§fCraft§f - Resources Vanilla (incompatible)
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU E5400 @ 2.70GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 8400GS/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

>

**Comment by PrinceOfAmber** [comment]
Thanks for the crash log!

**Comment by PrinceOfAmber** [comment]
Ah, something changed since 1.10.  Looks like its trying to draw the button before the recipe list is ready and safe to access.  Ill upload a fix later tonight.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2399193
