### ISSUE TITLE
the best items on the surface.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#325]
the most powerful items of your mod sometimes you can easly find them in silly structures. its not a issue or a bug is just when you have all those items make the game a wayyy more easy.

**Comment by PrinceOfAmber** [comment]
Yeah it is a little bit. if you go exploring off.

You can change this in config.  Under 'world generation' you can set ChestLoot=false to disable all Cyclic items from coming into chests, or you can change ChestLootChance to a lower or higher number to change the rarity.

Thanks for the feedback, its definitely something to keep an eye on!!!!!.   Last time i started a new world, in 1.11.2 modded, i didn't find any dungeons but in the nether fortress i found some good stuff.
