### ISSUE TITLE
Crash after eating 2 storage upgrades

### ISSUE THREAD

**Issue by AsmodeiXIII** [PrinceOfAmber/Cyclic#327]
I foolishly ate 2 storage upgrades after finding them in treasures, now when i open the item tab, I'm greeted by this crash:
https://paste.ee/p/F4D7N
Cheers.

**Comment by PrinceOfAmber** [comment]
Thanks for the log, ill get it fixed

**Comment by PrinceOfAmber** [comment]
This SHOULD fix it, let me know if theres any other problems! https://minecraft.curseforge.com/projects/cyclic/files/2400629

**Comment by AsmodeiXIII** [comment]
Seems to work! tried with both upgrades on a creative world with no problems, haven't tried on the world it crashed as i cant access it (another bug from another mod).

Thanks for the update!
