### ISSUE TITLE
Crash when mousing over bag in JEI

### ISSUE THREAD

**Issue by LlubNek** [PrinceOfAmber/Cyclic#33]
Mousing over one of your bags in JEI causes a crash.

crash report:  http://pastebin.com/8AK2GSqW
game output:  http://pastebin.com/JNPx0Tp7

**Comment by PrinceOfAmber** [comment]
Thanks I will fix this right away :)

**Comment by PrinceOfAmber** [comment]
Fixed in version 1.1.0 of the mod (released for 1.9 and 1.10)
