### ISSUE TITLE
[Feature Request]Uncraft enchanted items.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#332]
as the title said.

**Comment by PrinceOfAmber** [comment]
Yeah maybe.  Could be an option in the config file to allow this i suppose.

**Comment by PrinceOfAmber** [comment]
I remember addressing this before, it cant work like this. some recipes involve enchantments on one side or the other.  So it exactly matches the output with or without enchants.

Instead, ive added  an item that lets you remove enchantments and put them on a book.  So you can do that first before uncrafting  https://minecraft.curseforge.com/projects/cyclic/files/2411176
