### ISSUE TITLE
Structure Builder Bug: Floating saplings and saplings everywhere.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#334]
if you put some saplings on the structure builder without any block below the structure will plant them.
(is a little bug I don't know if I need to put more information).

Because of this bug you can also put saplings where they can't be placed and they will work.
(like oaks saplings on obsidian).

**Comment by PrinceOfAmber** [comment]
Fix coming soon in v1.2.7

**Comment by PrinceOfAmber** [comment]
Released now in both versions, hopefully its great for you too

**Comment by O-Barbaro-Desenhista** [comment]
ty and I play on 1.10 if is the case.
