### ISSUE TITLE
[1.11.2] Client crash on AutoTorcher durability 0

### ISSUE THREAD

**Issue by Aphyxia** [PrinceOfAmber/Cyclic#336]
Client crashed on dedicated server when autotorch durability reached breaking point.

Server side log:
https://pastebin.com/P5Fn2w2p

Cyclic: 1.2.7
Forge 2277

**Comment by PrinceOfAmber** [comment]
Oops.

Thanks for the crash log

**Comment by PrinceOfAmber** [comment]
Got a quick hotfix out https://minecraft.curseforge.com/projects/cyclic/files/2405119
