### ISSUE TITLE
Magic Beans and drops (Question)

### ISSUE THREAD

**Issue by Tyranuss** [PrinceOfAmber/Cyclic#339]
Hello. I have a question about Magic Beans. I really like how they are like a lootbag in farming mode. 
But is it possible to configure the loot they drop? Like if it is possible to include more items from Vanilla (Like endstone for example), or to include items from mods present? Can this be done automatically or does it have to be manually done?

Also, I have an idea for them. What if Magic Beans come in several (three maybe?) ranks? For example: Low Quality Magic Beans, Medium and High Quality Magic Beans. This way we get a little bit of progression and each gives different items: Low Quality all current vanilla items, Medium same but with higher chance of getting some better items, High Quality gives us best of vanilla items and includes items from other mods? 
Ofc, the higher the rank the more expensive is to make them/upgrade them.

Anyway, its just an idea that came up seeing how lootbags work.

**Comment by PrinceOfAmber** [comment]
Yeah that would be a bit more balanced.  With the default config file, you can get anything from clay to a nether star

**Comment by PrinceOfAmber** [comment]
I thought about adding different tiers of random things, but i just want to move away from random drops in general.  I still might change how this crop works one day. 

Leaving it as is for now so I can add other content
