### ISSUE TITLE
[BUG] [1.10.2] Harvester range resetting on chunk reset.

### ISSUE THREAD

**Issue by Kenny-Kipling** [PrinceOfAmber/Cyclic#343]
The Harvester block from Cyclic resets the harvest range back to 15x15 every time the chunk it is in gets unloaded and re-loaded (basically every time I travel from my house to my farm).

**Comment by PrinceOfAmber** [comment]
Ok weird, ill dig into this

**Comment by PrinceOfAmber** [comment]
Fixed in both 1.10 and 1.11 https://minecraft.curseforge.com/projects/cyclic/files
