### ISSUE TITLE
[Feature] New suggestions and problems. 

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#345]
1. Experience Pylon is even good, but still lack possibility to drain exp from player for later storage. 
Additionally XP Bottlers pack(block) crafted from 9 exp bottles would be a better solution for xp storage. :)

2. Interdiction plate work too weak imho. Its repel power is too weak so is't effective against speed monsters like a spiders or mounted monsters(like a zombie on zombie horse). It's doesn't repel zombie/skeleton horses too. (see "rough mob" mod). 
Moreover -  repel in itself is weak effective if area isn't ideally flat or there is present a obstacle like wall or shallow holes. So this plate isn't suitable for protection NPC, etc. 
I propose, make this plate to does kill instantly all monsters or teleport them away from range. Or simply stronger repel power plus Wither X(10) effect for all monsters in range.

3. As known a furnane minecart is bugged(loses all power after cross corner). Would can you managed to create a new, separate one whose don't have this bug, and eventually pushed minecarts with little more stronger and speed? Maybe some GUI with control panel and slot for coal?  ;)

4. A autocrafing table/machine, connected with hoppers?

In general to, thank you for creating and sill deleveping this mod, same as for conside our ideas. :)

**Comment by PrinceOfAmber** [comment]
1. Yes, a way to take exp in from the player would be perfect. i will add that.  (i had just been using it a mob farm to collect exp on the ground.)

2. of course, i should have thought about obstacles.  if you put one of these in a house with a villager. it should keep the villager safe regardless of if theres a wall in the way. Killing seems too strong, but adding maybe weakness and slowness would be good.  Teleport seems like a bit of a different style of thing, so for that i should add a different new item, like an upgraded version.  and with that i should reduce the cost of the original.  Another idea i had, if its possible i could try to see if the updated version could stop things spawning, so it wouldnt need to kill just stop the spawn event, and also TP those that wander close.

3. I was actually thinking about adding a faster normal minecart anyway like a gold one, so maybe a gold furnace minecart.  This wont be easy but i can look into it eventually.

4.  I want to add autocrafting as well.  If you look here, this is where i add my own ideas/plans for future things https://github.com/PrinceOfAmber/Cyclic/milestones  .  Autocrafting is on there as an item listed https://github.com/PrinceOfAmber/Cyclic/milestones

**Comment by PrinceOfAmber** [comment]
Do you play normally in Minecraft 1.10 or 1.11?

**Comment by GrzechuGrek** [comment]
>Do you play normally in Minecraft 1.10 or 1.11?

MC 1.11.2.

**Comment by PrinceOfAmber** [comment]
Thanks for the link and the info

**Comment by PrinceOfAmber** [comment]
Latest release has a bunch of these features:   https://minecraft.curseforge.com/projects/cyclic/files/2411176
Interdiction plate upgrade is in latest release.  It seems to work well enough against the rough mob creepers and such.
Also the EXP Pylon has new features, including a deposit from player, and i made an autocrafter.

The minecart stuff i moved to my backlog. ill look at it later https://github.com/PrinceOfAmber/Cyclic/milestones

**Comment by PrinceOfAmber** [comment]
@GrzechuGrek  FYI ive started work on new minecarts. a plain one that is just faster than normal, and then a new furnace minecart that loses almost no momentum as long as it still has fuel, screenshot here https://twitter.com/lothrazar/status/862526147514347522
