### ISSUE TITLE
[Bug] Shearing sheared sheep produces wool

### ISSUE THREAD

**Issue by Compegen** [PrinceOfAmber/Cyclic#346]
After a sheep has been sheared, you can continue to use your shears at no cost of durability to shear the sheared sheep.

Tested with only Cyclic mod installed: https://gfycat.com/MistyUncommonAfricangoldencat
Version `1.10.2-1.10.19`
_____
Issue does not appear when wool bonus is turned off

**Comment by PrinceOfAmber** [comment]
Fixed in latest 1.10 release.
