### ISSUE TITLE
Classic Oceans?

### ISSUE THREAD

**Issue by Endmateria** [PrinceOfAmber/Cyclic#350]
Is the classic oceans option gone?  It's not showing up in the world gen config options.

**Comment by PrinceOfAmber** [comment]
Yeah . sorry a few things were removed in 1.3.0 as stated in the changelog https://minecraft.curseforge.com/projects/cyclic/files/2411176 .


Mobspawning was awkward and not very configurable . so rather than reinvent the wheel i saw it done better in other mods like InControl.  Same thing for Mob Loot drops and the ocean floor update.  These features werent great for modpack devs , were conflicted, and were just better implemented elsewhere


Just now i went back and edited that changelog and added some download links to other mods

To replace some of this removed functionality i suggest the following

https://mods.curse.com/mc-mods/minecraft/257356-in-control

https://mods.curse.com/mc-mods/minecraft/231837-ocean-floor-clay-sand-and-dirt

**Comment by Endmateria** [comment]
Thanks for the detailed response... yeah, the idea of having sand oceans is what drew me to this mod.  Regardless of whether or not that option is implemented, I'm glad I found it.  This mod has a ton of unique configurations, like Quark, but different.  Very handy.  Thanks for putting it together.

**Comment by Endmateria** [comment]
Hey, just passing along the information here... I had a crash involving terrain generators from some other mods, but your mod's emerald ore generation in the extreme hills biome was on the list...  https://gist.github.com/Endmateria/19b081faa7ec6bfe82cd9c2203b111f4#file-crash-2017-05-06_16-24-58-server-txt I brought this crash report to the attention of the Galacticraft guys and got schooled on how Minecraft terrain generation works... and he explicitly brought up vanilla emerald gen and how it doesn't conform to the typical rules of terrain generation, hence I've noticed some other mod authors have opted to avoid messing with it altogether.  I disabled the option in my configs, but you might want to look into the emerald ore generator a little bit more.  Here's what the guy at Galacticraft said...  

I think most mod developers don't really understand how Minecraft oregen works.

It's roughly like this.

Stage 1: chunks are generated with basic bedrock, rock, dirt and water, according to the heightmap

Stage 2: already generated chunks are "populated", but the vanilla Minecraft chunkprovider algorithm will only populate a chunk if at least 3 neighbors already populated, maybe it also depends which neighbors those are, you can study the vanilla code. (One exception is underwater temples which have a special rule.)

Therefore, a chunk can be generated but flagged not "populated".

Getting and setting blockstates in the world causes attempts to load those chunks, which causes generation of those chunks if not already generated.

Vanilla populate code - for example vanilla oregen - can use getting and setting to load chunks either side of the current chunk, so x and z in the range { -1, 0, 1 } from the current chunk's position. This is obviously necessary to build complete ore pockets or complete trees. But the oregen and tree code is carefully limited in the range it can cover, if you look at all the vanilla code you'll see it never strays more than around +/-20 blocks from the center of the current chunk. Therefore, it never triggers chunkgen outside the range { -1, 0, 1 }.

Because of the rule about only populating a chunk which has 3 populated neighbors already, this makes it impossible for vanilla worldgen to run away.

If any mod has code which gets or sets outside that tight range, it will cause runaway worldgen, simple as that.

I see Tinker's Construct slime islands mentioned in that code, as well as vanilla emerald gen. There's something about vanilla emerald gen which breaks these rules slightly, I don't remember it.

**Comment by Endmateria** [comment]
And sorry, I don't know how relevant it is to you, like the Galacticraft guys, your generator might just be an incidental victim of someone else's mistake... regardless though, I thought it worth mentioning just in case.
