### ISSUE TITLE
Agricraft compatibility with the harvester

### ISSUE THREAD

**Issue by Zeevian** [PrinceOfAmber/Cyclic#352]
[crash-2017-04-27_09.39.40-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/961744/crash-2017-04-27_09.39.40-server.txt)

Happened when I was trying to use harvester on agricraft crops.  It broke it completely no seed drop or anything.  Occurred when swapping from 1x1 to 3x3.  Redstone was set to always on.  

The suggestion would be to have it imitate right click harvesting like in pam's/other mods.  

Not sure if that would be a compatibility thing or what.

**Comment by PrinceOfAmber** [comment]
"The suggestion would be to have it imitate right click harvesting like in pam's/other mods." This is what it should be doing, harvest the crop while replanting one of the seeds.

I havent looked into agricraft  crops, it might not be able to understand them yet

**Comment by Zeevian** [comment]
That's what I thought.  Then that means the NPE would be from it trying to replant?

**Comment by PrinceOfAmber** [comment]
Found and fixed where it was crashing.

When i tried it now, i was able to harvest the carrots and drop seeds and carrot on ground, but couldnt replant seeds.  Yeah, dont see an easy api for crop sticks but maybe i can come back to it later

**Comment by Zeevian** [comment]
ok cool

**Comment by PrinceOfAmber** [comment]
I fixed the crash here. https://minecraft.curseforge.com/projects/cyclic/files/2414132  Ill edit the title here to mention compatibility

**Comment by PrinceOfAmber** [comment]
note to self: Agricraft api
http://tehnut.info/jenkins/job/Agricraft/

https://github.com/BuildCraft/BuildcraftCompat/blob/7.2.x/common/buildcraft/compat/agricraft/CropHandlerAgriCraft.java
https://github.com/HenryLoenwind/AgriCraft/commit/ecc8274280b42eb3942701c5a47fae4aefe92831

**Comment by PrinceOfAmber** [comment]
Looks like agricraft has been abandoned again.  No updates since June 28th 2017, and all 1.10.2 builds marked as Alpha.  (source; https://minecraft.curseforge.com/projects/agricraft/files ) Also, i am not adding features to 1.10 anymore, i simply dont have the time.   

If this mod gets revived or forked into 1.12, i will for sure look at this again at that time.
