### ISSUE TITLE
Compatibility with other Fishing Rods?

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#354]
Hey, is compatibility with other fishing rods (e.g. base metals) with longer duration planned? At the moment, those do not fit into the automatic fishing net.

**Comment by PrinceOfAmber** [comment]
From which mod exactly? Recently I did add support for fishing rods from Aquaculture https://github.com/PrinceOfAmber/Cyclic/issues/317  . So that should still work in new versions.  If there is another mod I would have to add support for that specifically.

Also are you in 1.10 or 1.11?

**Comment by D3nnis3n** [comment]
Oh, sorry, i use 1.10.2 and the Fishing Rods i use are from the mods "BaseMetals" and "ModernMetals" (there might be more in the other XMetals Mods). Those add fishing rods for every metal added with different durability.

**Comment by PrinceOfAmber** [comment]
Check it out in newest version
