### ISSUE TITLE
Chunkloader

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#355]
Did you ever think about adding a chunkloader to your mod? As it is a collection of many useful tools with the option to just disable anything one does not like it might be an option to add one? Afaik there are not many out there at the moment. Railcraft one is gone, extrautils has one. Do not want to use that mod, but lateley there came out a mod called "Weirding Gadget" that i use now.

**Comment by PrinceOfAmber** [comment]
Ive looked into making a chunk loader a few times, been suggested before.  It looks quite complicated to be honest.  I also use weirding gadet, i like that it has a natural timeout, and I like that its a standalone mod. (link for anyone else reading https://mods.curse.com/mc-mods/minecraft/258914-the-weirding-gadget )  Plus its made by AtomicBlom who is quite reputable and has many high profile mods.

I am currently working on in game documentation in form of a Guidebook, and also I have a big list of things I want to add, you can see them under milestones.  https://github.com/PrinceOfAmber/Cyclic/milestones ..So honestly i dont know i its worth my time right now..   If thats all done one day than maybe, but no need to reinvent the wheel a this point in time.

**Comment by D3nnis3n** [comment]
Alright! Then i will use Weirding Gadget further, until Railcraft has got its chunkloader back.
