### ISSUE TITLE
"Screens" Feature

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#356]
Another thing from another mod with over 9000 useless features i can't disable i like is a expandable screen block that allows to show an image posted into it as link.

And: Please just ignore my issues, if you do not want such things *g* I just like the concept of a utility mod that really allows disabling anything one does not want soooo much.

**Comment by PrinceOfAmber** [comment]
Does this mod do what you want? I havent tried it yet, and i dont know i its expandable.  https://mods.curse.com/mc-mods/minecraft/257815-onlinepictureframe

I can look into my own version .. IF we can think of a way to make it different, or if that mod doesnt do things in a certain way, know what i mean?.  I am no ignoring dont worry.  For example I recently added an AutoCrafter, even though lots of other mods have one i had a way to add it in my own unique way, and the other mods arent as configurable.

**Comment by PrinceOfAmber** [comment]
Also i found this one. again havent tested it yet but its different again https://mods.curse.com/mc-mods/minecraft/250822-sign-picture

**Comment by D3nnis3n** [comment]
Hey, i at the moment use OnlinePictureFrame but find it being very complicated and buggy. I didn't try sign picture until now.

Extrautils has the simplest, easiest and most reliable version - unfotrunatley it adds tons of things i do not want to have. I will look at Sign Picture, didn't find that yet and tell you if it is good. I'll report back.

Btw:
I'm really hoping for these features:
https://github.com/PrinceOfAmber/Cyclic/milestone/3
https://github.com/PrinceOfAmber/Cyclic/milestone/8
https://github.com/PrinceOfAmber/Cyclic/milestone/10

The reason i downloaded your mod was the autouser. Then i saw i could disable just anything i didn't want. I was sooo happy. Needed a block for auto farming sheep and cows. This would make that a lot easier.

**Comment by D3nnis3n** [comment]
It seems like SignPicture is a better choose than OnlinePictureFrame but both do:

Not use blocks for expanding the picture. You can watch and walk (!!!!!) through the pictures from behind. Configurations is pretty hard as i need to type coordinates instead of just use blocks, enter an url and i'm done.

So both mods do not meet my requirements. ExtraUtils one does perfectly though. At the moment i do not excactly know how you could change it to be also different from ExtraUtils one - they did the job right to give an easy, uncomplicated, block based solution for this.

**Comment by D3nnis3n** [comment]
Okay: ExtraUtilities only allows .png files from imgur to be displayed. Yours could allow any url :D

**Comment by PrinceOfAmber** [comment]
Yeah i love ExtraUtilities  but its hard to cleanly disable features.

Thanks for looking through milestones, good to hear what is more desired

**Comment by PrinceOfAmber** [comment]
Working on user range and display case now.  I have yet to dig into the forge liquids api , ive always wanted to but needs some research.  same with rendering web image

**Comment by D3nnis3n** [comment]
Yeah, but don't forget this is really just my opinion. There are some features, i really need, while others may absoluteley not. Extra Utilities also has this power-grid system i absoluteley do not like and some of the blocks i want, use it. Yours is better as it is based on vanilla but can be automated. For the missing need for electricity i just change the recipe to somewhat harder. 

Most important for me atm would be an output slot for the auto user, to pipe items out and fully automate them - which was their concept, i think?

I would also like to thank you very much for your efforts, that seems to be something very special in the overall modding community i absolutley appreciate.

To be honest, i could write a mod myself (it admin) but i hate programming - i'm the system administration guy :D

**Comment by D3nnis3n** [comment]
SignEdit has proven to be a good replacement for this feature in the last months. I, myself do no longer see a necessity for this. If you want, you can close this issue if you do not plan to add this feature, anyways.
