### ISSUE TITLE
Uncrafting Machine - Mekanism Compatibility

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#357]
As Mekanism beeing my main tech mod the uncrafter not being usable for it is a bit disappointing. If you can find time anytime you might could consider adding support? It tells me the recipe could not be found for any item of mekanism - even the most basic ones.

Here: https://github.com/PrinceOfAmber/Cyclic/issues/330
you wrote there is no support for moddes recipes - but i CAN uncraft EnderIO and GregTech Machines just fine!?

**Comment by PrinceOfAmber** [comment]
Well, yeah. it depends how mods create their recipes. 

For example, RefinedStorage has a thing called a Solderer, which is a 3x1 .  This is not a vanilla recipe system. so uncrafter doesnt know how to look it up.  Refined storage has a "solderer recipe" kind of like a furnace recipe, different from crafting table.

Similar way, there is an airship mod called vies craft, its recipes are made in a 3x3 shape, but must be made in a special airship table. its a standalone recipe type.

Ender IO and Gregtech all just use the vanilla recipe, they dont invent an 'ender io recipe" or "gregtech recipe".   

When pressing the "?" button on a mechanism item, it should say somethin in chat about the recipe not found, do you remember what it says exactly?  Also are you in 1.11 or 1.10?  

Its not impossible, but it depends if mechanism has an API or an interface to be able to look up the recipe ingredients.

**Comment by D3nnis3n** [comment]
Oh well, i do not need these special recipes, but i can't remember Mekanism machines are not made in normal crafting table. I'll look that up and report later.

**Comment by D3nnis3n** [comment]
Okay, it is a completley normal recipe that CAN be made in any vanilla crafting table.
This is the error message i get:

Unknown Recipe Type:
mekanism.common.recipe.ShapedMekanismRecipe

**Comment by D3nnis3n** [comment]
This seems to be compatible now. Therefore i Close my issue, if you're good with that.
