### ISSUE TITLE
Automated User - Buckets and other Items that needs to get back

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#358]
It seems like there is no compatibility for milking cows.
A Bucket is used, but no bucket full of milk is given back.
Also it tries using the bucket too often and uses it - even if the cow would no longer be able to give milk.

**Comment by D3nnis3n** [comment]
You could easily fix it by giving it an inventory to store filled buckets, etc.

For example i really would like to be able to automatically fill soul vials from EnderIO, transport them to my farm and release them there again. (Because i do not like the concept of spawn - kill - spawn - kill farming, but of somewhat harder farming with real resources)

**Comment by PrinceOfAmber** [comment]
This used to work in 1.10.2 , ill look into this bug, thanks for reporting.

Yeah it also has no 'output slots' or anything, that might be a good idea.

**Comment by D3nnis3n** [comment]
I'm using 1.10.2, but it is not working for me, hope you can nail the problem down.

**Comment by PrinceOfAmber** [comment]
OK ill have to fix in both versions then

**Comment by PrinceOfAmber** [comment]
Ill do the quick fix now, so at least milking cows and sch works, and then come back in the future to add inventory and range upgrade

**Comment by D3nnis3n** [comment]
It works now, but it doesn't seem to accept anything as input like chests or pipes, it just throws it out in the world. I can get them by using enderios vacuum chests, but this is pretty "lame". Any plans on making piping / chests possible?

**Comment by D3nnis3n** [comment]
Well, seems like this must be linked with the planned output inventory, wool from sheeps will also not be collected, didn't remember. Sorry.
