### ISSUE TITLE
Better Beacon

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#359]
I would like an better Beacon block. Something that works like a Beacon but with only One Block, bigger Range and the possibility of more features and more of the Dame at the same time.

I could think of using potions or enchantment books to specify the effects.

**Comment by PrinceOfAmber** [comment]
Yeah put in a potion or a book to tell it what to use.   Great idea

**Comment by D3nnis3n** [comment]
Or multiple!

**Comment by D3nnis3n** [comment]
As you've just added an empty beacon, what is your opinion on this suggestion now?

**Comment by PrinceOfAmber** [comment]
I currently have a half finished "real" better beacon thats in progress.  But it still needs some more work.  
  Last night I got the beam part of it working perfectly, so for now i just copied part of it and made this empty becaon.

The real better beacon still needs a name, what do you think I should call it?  @D3nnis3n  

Basically it wont need any blocks underneath it, it can be standalone, and it will be able to do any potion effect in the game, even modded ones.

**Comment by D3nnis3n** [comment]
Hey,
i'm not really good in giving things names, but i would suggest
https://en.wikipedia.org/wiki/Pharos_(disambiguation)

I'm from Germany, so i do not know if you would instantly understand the reference in english, but in german this is a word used as synonym for one of the seven ancient wonders of the world, the Lighthouse of Alexandria, which is thought to be the first lighthouse on earth. Seems like it would fit.

If you find that crazy, just drop the Suggestion! :D

**Comment by PrinceOfAmber** [comment]
Yeah thats a decent idea.  My current plan is instead of dropping an ingot into it, you brew a potion and drop it in. and whatever potion you give it is what you get.

**Comment by D3nnis3n** [comment]
Will it be based on Redstone to activate? What about a range config?

Am 26.09.2017 08:31 schrieb "Sam" <notifications@github.com>:

**Comment by PrinceOfAmber** [comment]
This is how it looks currently.

Right now it defaults to 64x, but i think i can add a range config up to maybe 256 or 512.

I am not sure if it needs a fuel bar.  But if i take that out, maybe i should give it more inventory slots and then it slowly consumes an entire potion item, something like one every 5 or 30 or 60 minutes.

![pharos](https://user-images.githubusercontent.com/621529/31061511-1b947744-a6d7-11e7-8296-107a7265c1db.PNG)

**Comment by D3nnis3n** [comment]
That Looks quite cool. Fuel bar is okay, but an Option for a way higher range would be great. We would use it in our main City, but as they do not need all those precious blocks anymore, we could also place multiple. Will those work with combined potions? Combined potions allow to Combine potions, so you could (theoretically) make one potion that has all effects available.

As for consuming the potion. Well, as Long as refilling is automatable, that would be fine with me.

**Comment by PrinceOfAmber** [comment]
Currently it does get a full list of potion effects applied to the item, and it uses a function from vanilla to get the list of potion items from it. so like this

` ItemStack s = this.getStackInSlot(0);
  this.effects = PotionUtils.getEffectsFromStack(s);`

So if the combined potion still use the vanilla potion item with standard nbt tags, then yes it will work.

and i will make sure it works with hoppers/pipes for auto refils

**Comment by D3nnis3n** [comment]
As far as i can see, they do. That's great. You might add a config for the consuming of potions? I would see it a bit to hard, when potions decay and using burning items, as Long as you must use potions with only effect, but it would be too easy if you could place in a combined potion, that does not wear out. So i or other modpack makers can just configure how they like it. What do you personally think of that?

**Comment by D3nnis3n** [comment]
Whoaaaa, it's there and still called Pharos :D

**Comment by D3nnis3n** [comment]
I just tried it out, but it does only take the first potion effect applied into it when i put in a potion with multiple effects. But they're in NBT.

**Comment by PrinceOfAmber** [comment]
Yeah.... there wasnt enough room in the GUI for all of them.  

Anyway I will close this, if there are any bugs, or of course any feature ideas/tweaks just open a new issue
