### ISSUE TITLE
Adjustable range for the autouser

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#360]
An adjustable Range for the autouser  (Maybe up to 3x3 in front or like the miner) could make autoshearing  / milking easier.

**Comment by PrinceOfAmber** [comment]
Ive had this on my mind for a while in my todo list https://github.com/PrinceOfAmber/Cyclic/milestone/10 

It does secretly try to reach out 2 blocks instead of 1 when interacting with entities.  But It would be better i it had a button just like Harvester, toggle it like 1x1 3x3 5x5 etc.

**Comment by PrinceOfAmber** [comment]
New range upgrade : One has a hoe, one has seeds, one has bonemeal.  Magic!

![farmit](https://cloud.githubusercontent.com/assets/621529/25648403/5da94570-2f80-11e7-9078-6833e0b30bc6.png)

**Comment by D3nnis3n** [comment]
This is awesome! (Even if this magic wouldn't work for me as forestry disabled "bonemeal" magic in favor of complex systems :D)

**Comment by PrinceOfAmber** [comment]
Short answer is, 1.10.2 is still supported for bugfixes, all new features are going in 1.11.2

Long answer: Sadly, I do not have the time.  There are many extreme differences between the two verrsions, the vanilla minecraft code as well as forge are pretty different.  I still have 1.10.2 version around in case i need to do a critical bugfix, but copying between the two isnt easy.  I know other mod devs do it and it impresses me.  I am lucky to get 2 hours per day to work on this between family and work and real life.

But the code is public, if you or anyone you know is a coder and wants to make an update /edit/pull request to port this to 1.10, i would happily accept that.  Hell if someone ported this to 1.7.10 i would also be happy.


Anyway, yeah.  So this feature is up now in the latest 1.11 release.  As well as some other cool stuff!

**Comment by D3nnis3n** [comment]
That's soo sad to hear. I will continue to post suggestions, but unfortunatley will never be able to use them. Many of the main big mods will not update to 1.11.2, as 1.10.2 is the new big version after 1.7.10. It will be another version after 1.11.2 that is a modpack version again. Well, most little mods ARE indeed compatible (which is new compared to earlier versions), but some of the bigger will not manage it.

I had hoped you would use something like the nifty "CompatibilityLayer" mod that makes your mod compatible with both versions. (You might take a look on it, if you don't know it already?) Unfortunatley Java is not the kind of language we use around here, so no friends that could help in that :D

> I am lucky to get 2 hours per day to work on this between family and work and real life.
To be honest. This seems pretty much. Other devs of big mods do only work at weekends for 3 - 5 hours. :O
