### ISSUE TITLE
Suggestion: Sound Muting Block

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#364]
A block that cancels / lowers noise in it's area.

Yes, there is a mod out there, called ellipsis but unfortunatley it does not work and crashes as of incompatibility :/

**Comment by PrinceOfAmber** [comment]
I would use that all the time actually, yeah (damn cows)

**Comment by D3nnis3n** [comment]
I would use it for machines and villagers :D

**Comment by PrinceOfAmber** [comment]
Soundproofing released [1.11.2] https://minecraft.curseforge.com/projects/cyclic/files/2415670
