### ISSUE TITLE
Guidebook text spills out of the bottom of the book

### ISSUE THREAD

**Issue by darkphan** [PrinceOfAmber/Cyclic#371]
See screenshot: http://i.imgur.com/YccQLBi.png
Cyclic version 1.11.2-1.4.0

**Comment by PrinceOfAmber** [comment]
Fix coming soon in 1.4.2.  Also I asked GuideAPI mod authors if I could add this as default behavior https://github.com/TeamAmeriFrance/Guide-API/issues/69

**Comment by PrinceOfAmber** [comment]
Fixed https://minecraft.curseforge.com/projects/cyclic/files/2419546
