### ISSUE TITLE
Bug in golden furmace minecart

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#374]
There is a bug in golden furmace minecart: When this powered minecart hit/touch a other minecart(especially the one where I'm sitting), then occasionally loses all speed and stop.

**Comment by PrinceOfAmber** [comment]
Yeah, absolutely.  I want this to have enough power to push at least one or two minecarts while carrying mobs.  I must have only tested with empty carts.

**Comment by PrinceOfAmber** [comment]
I overhauled the gold furnace minecart completely and did a bunch of tests.  if im sitting in a gold minecart it pushes me just fine, i had a long track with tons of corners. 
https://minecraft.curseforge.com/projects/cyclic/files/2420656
Let me know of course if you have  bugs OR ideas for improvements
