### ISSUE TITLE
Harvester interaction with Pam's Harvestcraft Trees

### ISSUE THREAD

**Issue by geomead** [PrinceOfAmber/Cyclic#375]
the Harvester works with the trees, but only on the same plane as the tree.  if there are multiple trees with varying leaf heights, you need multiple harvesters.  maybe some sort of way to control what planes the harvester will interact with?

**Comment by PrinceOfAmber** [comment]
Currently it only goes exactly the same horizontal level as the block.  So you could try moving the harvester up to same level as fruit.  

If that doesnt work, its  a bug.


In addition to that, i can see about adding a vertical height option, so defaults to 1 but optionally can harvest up .  This would also be good for things like cocoa beans at multi heights.
