### ISSUE TITLE
Cascading Worldgen Lag

### ISSUE THREAD

**Issue by Thiana** [PrinceOfAmber/Cyclic#376]
```
Cyclic loaded a new chunk (116, 27  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
```
With 1.11.2-1.4.2, Forge is reporting a large amount of cascading worldgen in 1.11.2. There is more information about the problem and possible fixes @ https://github.com/Vazkii/Quark/issues/412

Thanks.

**Comment by PrinceOfAmber** [comment]
Thanks for the report, i had no idea a all this was happening.

**Comment by PrinceOfAmber** [comment]
Looks like a proper solution is in debate but there are some possible answers. I will check in on this routinely.

**Comment by PrinceOfAmber** [comment]
Related link found in one of the threads from above link https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by PrinceOfAmber** [comment]
Update again: it was BiomeCrops feature causing this.  I was considering either overhaulling or removing this feature anyway, so ill just take it out or now

**Comment by PrinceOfAmber** [comment]
Should be fixed here let me know of course if you see that again https://minecraft.curseforge.com/projects/cyclic/files/2420656

**Comment by Endmateria** [comment]
This is a useful piece of info, in case your mod still has a config that messes with emerald ore gen.  There's a vanilla bug that often causes emerald ore to cause cascading worldgen lag...  https://bugs.mojang.com/browse/MC-114332
