### ISSUE TITLE
Uncrafting Grinder - Deleting / Voiding Items (Cyclic 1.4.4 for MC 1.11.2)

### ISSUE THREAD

**Issue by Nijoma69** [PrinceOfAmber/Cyclic#379]
When attempting to uncraft an item that is made up of multiple similar items (i.e. trying to uncraft 5x oak wood stairs when the recipe requires 6) the insufficient items are not moved to the internal inventory, instead they are voided and just cease to exist ... pretty sure this didn't happen in previous versions.

**Comment by PrinceOfAmber** [comment]
yeah what it did / is supposed to do is is put them in the right side, or drop in world if its full. ill get a fix out soon

**Comment by PrinceOfAmber** [comment]
Fixed in new version. Thanks for reporting this https://minecraft.curseforge.com/projects/cyclic/files/2422581
