### ISSUE TITLE
[1.10.2] Crash with XP orb on slime pad

### ISSUE THREAD

**Issue by tommyTT** [PrinceOfAmber/Cyclic#38]
I put down a slime plate and got attacked by zombies. After killing them my server crashed because of a ClassCastException when the plate tried to launch the XP orbs.

Minecraft: 1.10.2
Forge: 12.18.0.2004
Cyclic: 1.2.0

http://paste.ee/p/MIaZZ

**Comment by PrinceOfAmber** [comment]
Thanks for the report. I just released 1.3.0 version but i didnt see this in time, ill quickly get out a new one to fix this!

**Comment by PrinceOfAmber** [comment]
Fixed in version 1.3.1, just released: http://minecraft.curseforge.com/projects/cyclic/files
