### ISSUE TITLE
Garden Scythe cloning items.

### ISSUE THREAD

**Issue by NoVac101** [PrinceOfAmber/Cyclic#380]
https://youtu.be/aXdki6c5Vdk
Here's the example I've found.
Mod pack: All the Mods 2 1.11.2

**Comment by PrinceOfAmber** [comment]
Pergola block from https://minecraft.curseforge.com/projects/terraqueous

**Comment by PrinceOfAmber** [comment]
LOL so the Terraqueous devs coded Pergola  to be a Bush/Crop, not a block of wood, so the scythe is attempting to harvest and replant, it thinks its like a potato.

No problem im adding blacklist to fix it, its just weird to me

**Comment by PrinceOfAmber** [comment]
Fixed in new version.  Fix uses a blacklist in config, so any future weird problems like this will be much easier to deal with

 Thanks for reporting this

 https://minecraft.curseforge.com/projects/cyclic/files/2422581
