### ISSUE TITLE
Crash when using the Scyth on a tree 1.11.2

### ISSUE THREAD

**Issue by RedBullSlurpie** [PrinceOfAmber/Cyclic#383]
Here is the crash report I get upon right clicking a set of leaves.
Minecraft Version- 1.11.2
Cylic Version- 1.4.6
Minecraft Forge Version- 13.20.0.2304

Crash Report- https://pastebin.com/S3uqXsRv

**Comment by PrinceOfAmber** [comment]
Oops! I added a config blacklist to havesting recently but looks like i missed an edge case.  Knock on caused by https://github.com/PrinceOfAmber/Cyclic/issues/380

**Comment by PrinceOfAmber** [comment]
Hotfix will be out soon; also downgraded v1.4.5 and 1.4.6 to beta status https://minecraft.curseforge.com/projects/cyclic/files/2423574
