### ISSUE TITLE
Mining Dynamite leaves Invisible Blocks

### ISSUE THREAD

**Issue by scottosx** [PrinceOfAmber/Cyclic#386]
After explosion there are invisible blocks left, some that can damage the player. It may have to do with tile entities like torches or possibly falling blocks like gravel. Haven't nailed down the exact circumstance.

1.11.2 with no other mods besides JEI and JourneyMap

**Comment by PrinceOfAmber** [comment]
Does pressing F3+A to reload chunks bring them back? 

I know i can make these ghost blocks appear very easily using efficiency V and a haste II beacon in vanilla http://minecraft.gamepedia.com/Tutorials/Ghost_blocks

Ill look into it in case theres something i can do but it MIGHT just be part of the base game?

**Comment by scottosx** [comment]
F2+A doesn't get rid of them. Right clicking with another block does. Still you might have your head stuck in one taking damage. The ghost block link you sent does seem relevant.

**Comment by scottosx** [comment]
Could I also ask what is the blast radius? Or is it basically the same as indicated here: http://minecraft.gamepedia.com/Explosion#Model_of_block_destruction

I'm trying to figure out how to maintain a floor just above lava level.

**Comment by PrinceOfAmber** [comment]
This should have radius/power level  the same as charged creeper and Dynamite VI

**Comment by PrinceOfAmber** [comment]
I found out why its happening, kind of. It runs the explosion on server and client side in parallel, which should have the same positions affected, but. .. in one of my tests it said

Client side blocks destroyed:  a big number
Server side blocks destroyed: a different number!

so maybe doing a cleanup step afterwards to update the client side affected blocks will fix it

**Comment by PrinceOfAmber** [comment]
This happens with vanilla TNT and also vanilla shovels with efficiency V when digging.  

Nothing i can really do to fix except hope Mojang fixes it https://bugs.mojang.com/browse/MC-5694 


Also this might possibly fix it? not sure.  https://mods.curse.com/mc-mods/minecraft/273279-antighost
