### ISSUE TITLE
[Suggestion] range config for (garden) scythe 

### ISSUE THREAD

**Issue by 4Magma** [PrinceOfAmber/Cyclic#389]
I build my fields in a checkerboard pattern of 4x4 areas with path between them.
If i use the scythe on a path crossing, i can harvest all 4 fields around it.
Unfortunately harvests the scythe not only 9x9 or 11x11 (includes path),
but affected also the next row of the adjecent fields (?13x13?).

Could you add a way to change/reduce the range of the scythe?
a) as config option [3-current range]
b) on tool with right click like climbing cloves
c) on tool with shift right click in air

additionally:
Could you add a whitelist for brush scythe to break also modded plants?

**Comment by PrinceOfAmber** [comment]
I can do a range upgrade the same way that the Piston Scepter has one, where it toggles between modes.

It should work with many modded plants already (I have tested with several from Botania, Plants, harvestcraft)  

If I add a whitelist of things to break, it wont know how to replant them.  

If you can post a list of plants and what mods they are from i can upgrade that.

Also are you in 1.10 or 1.11

**Comment by 4Magma** [comment]
1.11.2 

the way how to set a range is unimportant.

could you also add a config, to change origin of scythe area?
- center = current mode
- side = like harvester (so i must no go to center of field)

Mod support should be for the brush scythe, not the garden scythe,
so replanting not necessary.

Would add support for world generated rustic and actually additions 
plants with a whitelist.

**Comment by PrinceOfAmber** [comment]
"side = like harvester (so i must no go to center of field)"  I am not sure I understand this.

Right now, the crops harvest and drop where they are.   Are you talking about a mode that teleports the drops to the player?  If so you can just use the machine called the Harvester.  Has same action as garden scythe but automated in a machine block and new addition in 1.5 it has inventory to capture drops.

"....support for world generated rustic and actually additions
plants ...."  What plants from AA dont work, what plants from rustic dont work.?

**Comment by 4Magma** [comment]
"side":
instead of using the scythe on the center of a field, i would
use it from the side of the field. Drops must not come to me.
(range collector or magnet mode are enough)
(scythe should affect all blocks which also a harvester on this
position would do)

"modded plants vs. brush scythe": (tested with 1.4.7*)
actuallyadditions canola, black lotus and rice are unaffected.
rustic aloe vera (on grass) as example also unaffected
And much other mods added plants to world generation.

*back to 1.4.7 because crash while opening fishing net in 1.5.0

**Comment by PrinceOfAmber** [comment]
Fishing net crash is fixed.  

Thanks for reporting on the canola and rice not working, i am looking into those now.

For the scythe , it doesnt really know where the edge or center is.  but for advanced harvesting you can just use the machine "Harvester" it does the same exact thing as the garden scythe but in machine farm.  Also new harvester machine in newer updates has its own inventory to collect drops.  And i have a Magnet purple item plate if you just have the scythe.

**Comment by PrinceOfAmber** [comment]
I have it working with Actually additions plants. , black lotus coming too

![Uploading fixy.png…]()

**Comment by PrinceOfAmber** [comment]
New version is up. thanks for all the feedback! https://minecraft.curseforge.com/projects/cyclic/files/2432741
