### ISSUE TITLE
Feature Request: Sleeping Mat Sets Spawn

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#391]
Is it possible to add a config option to allow the sleeping mat to set the player's spawn? Thank you very much for the consideration and I love the mod so far! <3

Darkosto

**Comment by PrinceOfAmber** [comment]
1.5.1 https://minecraft.curseforge.com/projects/cyclic/files/2429643

<3

A nice small request.  More are welcome in the future!
