### ISSUE TITLE
[Request] Glass Bottles with Automated User

### ISSUE THREAD

**Issue by scottosx** [PrinceOfAmber/Cyclic#395]
It is awesome that you added bucket support for the Automated User. Would it be possible to add glass bottles as well? This would be perfect for gathering water for fully automatic potion brewing.

I have tested and this currently doesn't seem possible.

**Comment by PrinceOfAmber** [comment]
Yeah good idea, this should work

**Comment by PrinceOfAmber** [comment]
Added this in latest version.  Also changed the UI a little bit for better optimization by adding output slots  

https://minecraft.curseforge.com/projects/cyclic/files/2432741
