### ISSUE TITLE
Crash right-clicking auto Fishing Net

### ISSUE THREAD

**Issue by Occassius** [PrinceOfAmber/Cyclic#396]
(Using 1.11.2 - 13.20.0.2314 Forge but crashes with other versions also)
Every time I right-click the Net after placing it down causes the entire game to crash with this error:

The game crashed whilst rendering screen
Error: java.util.IllegalFormatConversionException: f != java.lang.Integer

**Comment by PrinceOfAmber** [comment]
What version of cyclic are you using? I fixed this exact issue just recently in version 1.11.2-1.5.2 , https://github.com/PrinceOfAmber/Cyclic/issues/393
https://minecraft.curseforge.com/projects/cyclic/files/2430067

Make sure you're updated and try again, if it still happens in 1.11.2-1.5.2  ill check it out again.

**Comment by Occassius** [comment]
Yeah, I didn't realize that you updated, but checked after I made the bug
report, updated, and it did solve the problem, so I apologize for wasting
your time, but thank you for fixing the problem and replying back to me :)

**Comment by PrinceOfAmber** [comment]
Hey dont apologize, you reported a bug and thats the right thing to do 👍
