### ISSUE TITLE
Brush Scythe doesn't affect Biomes O'Plenty grasses.

### ISSUE THREAD

**Issue by stormseeker71** [PrinceOfAmber/Cyclic#397]
Per the title.  Clears out the vanilla grass but not the BOP variants.

**Comment by PrinceOfAmber** [comment]
note to self: Source code for BOP grass.  IDEA: use IShearable if that would work? 

https://github.com/Glitchfiend/BiomesOPlenty/blob/406dd93a2fffb79bcc2fdef5d88acfdf70e53fa9/src/main/java/biomesoplenty/common/block/BlockBOPPlant.java#L61

**Comment by PrinceOfAmber** [comment]
Should work with bushes, mushrooms, and other stuff https://minecraft.curseforge.com/projects/cyclic/files/2432741
