### ISSUE TITLE
[Bug][1.5.3]  Brush Scythe drops only flowers

### ISSUE THREAD

**Issue by 4Magma** [PrinceOfAmber/Cyclic#399]
1.5.3
Scythe gives no drops from grass
got only stacks of red and yellow flowers
1.5.2 ok

**Comment by PrinceOfAmber** [comment]
Oops, i must have broke something when i went and messed around with everything ot make it work with biomes o plenty and such (https://github.com/PrinceOfAmber/Cyclic/issues/397)

**Comment by PrinceOfAmber** [comment]
I think i fixed it https://minecraft.curseforge.com/projects/cyclic/files/2433833
