### ISSUE TITLE
[1.11.2] Unable to output from Harvest with ExUtils2 transfer nodes

### ISSUE THREAD

**Issue by Adiuva** [PrinceOfAmber/Cyclic#403]
Vanilla hoppers still work for pulling things out, but right now it requires a buffer of a hopper from the harvester to a chest to a node as opposed to simply using the node. I have not tried any other item routing from the Harvester.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this.  I added compatibility in 1.5.5, so it should work for you in that version, if not let me know. https://minecraft.curseforge.com/projects/cyclic/files/2433833
