### ISSUE TITLE
Auto-Smelt glitching and giving x64 stacks for a single block

### ISSUE THREAD

**Issue by aelfwyne** [PrinceOfAmber/Cyclic#404]
Running Cyclic on 1.11.2 -

Enchanted pick with "Auto-Smelt". Chop a stone block, it smelts into an entire stack! Same thing happens with iron ore - chop a single iron ore block, get a stack of 64 iron! 

Also once this bug triggers on a pick, it also causes furnaces in the game to glitch out. Furnaces will start giving x64 stacks as well for items such as cobble or iron.

For now I have disabled auto-smelt in the config file which is fine by me, since I don't really need auto-smelt. 

It may be possible others haven't encountered this bug because Tinker's also provides auto-smelt and they're using that one instead. I don't have Tinker's installed, so it is using Cyclic auto-smelt.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting it

**Comment by aelfwyne** [comment]
Well.... I suppose since in MY testing it was clearly Cyclic, I will simply have to keep it disabled. I don't have any uncommon mods that would affect this. Too bad you're unable to replicate this.

**Comment by PrinceOfAmber** [comment]
Yep no worries, thats why i have the config file. Ill keep the issue ticket open for now in case i see it happen later.

**Comment by PrinceOfAmber** [comment]
I think i found a fix for this, see the #485 for info

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2468801
