### ISSUE TITLE
fragile torches setting does not respect mobGriefing rule

### ISSUE THREAD

**Issue by bogger33** [PrinceOfAmber/Cyclic#406]
Maybe you wouldn't call this a bug, but I was quite surprised that even with mobGriefing set to off, mobs would still break torches when passing through them. Obviously the easy solution is to just change the setting, but I still think it'd be good to respect mobGriefing rules

**Comment by PrinceOfAmber** [comment]
Yep this makes sense

**Comment by PrinceOfAmber** [comment]
Added this and some other goodies in latest release https://minecraft.curseforge.com/projects/cyclic/files/2436763
