### ISSUE TITLE
Uncrafting grinder doesn't give items after completing

### ISSUE THREAD

**Issue by chokoth** [PrinceOfAmber/Cyclic#411]
minecraft 1.12
Forge 12.21.0.2343
Cyclic-1.12-1.5.7

When I place an item in the uncrafting grinder, the progress bar finishes, the sound of the item breaking plays, and then no items are returned.  I initially thought it was going into a near-by inventory (couple of chests) so I moved it off by itself to verify. Found no items in the machine. Attached a hopper underneath to see if I could extract the items. Got nothing. The items are simply deleted.

I am running a few other mods, but I have tried vanilla items, as well as items from cyclic (including another grinder) and I've seen no change in behavior. If you need a mod list, let me know.

**Comment by PrinceOfAmber** [comment]
Yeah 1.12 is still very beta, i expected a few weird things like this to come up. worked fine in 1.11 last time i checked.

**Comment by chokoth** [comment]
Well thank you for getting something out for us cutting edge players. Other than this, it seems to be working well. Looking forward to the fix when you can get to it. Thanks for the update.

**Comment by PrinceOfAmber** [comment]
Looks like a forge update is breaking lots of mods http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2366/forge-1.11.2-13.20.0.2366-changelog.txt

Anything up to and including 14.21.0.2347 works fine, but the newest forge versions break my mods and a ton of others with some random changes i guess.  Like the game wont even start, class not found "forge registry".   Just some info for you.

**Comment by PrinceOfAmber** [comment]
Sorry this took so long, finally got a fix out https://minecraft.curseforge.com/projects/cyclic/files/2445567
