### ISSUE TITLE
Can not craft Sack of storage 

### ISSUE THREAD

**Issue by mackie419** [PrinceOfAmber/Cyclic#412]
ver 1.11.2-1.5.7, every time you you go to craft weather in a normal crafting table of tinkers table when you click the bag to craft it, it shows in the inventory and when you go to open it it does nothing. If you click on the tinkers table it still shows the items in the table. If you use a normal crafting table when you click on it it just ejects the items out of the table

**Comment by mackie419** [comment]
Just an update. The error I was getting with the crafting was on a server. I tried it in single player and everything is seeming to work fine. I will update you if I find anything out.

**Comment by PrinceOfAmber** [comment]
Thanks for the update. I just tried it myself in single player and its fine ill try on server.

**Comment by PrinceOfAmber** [comment]
CLosed due to no updates, also everything working fine.

Reopen or make new issue if something comes up
