### ISSUE TITLE
crash on 1.10.2 when "sack of holding in the starter chest"

### ISSUE THREAD

**Issue by JasonKillsUs** [PrinceOfAmber/Cyclic#413]
this is a strange crash concerning "sack of holding" this happens only if i find the sack in the starter chest at the beginning of a new world/game never has happened when i craft the item later on.

"https://pastebin.com/4YWdQhUk"

**Comment by PrinceOfAmber** [comment]
I see, so somehow it has bad data when spawned from a loot table instead of crafted.  Whatever the cause ill have a fix out soon :)

**Comment by PrinceOfAmber** [comment]
This should fix it, hopefully i tested every angle.  Stop by again for any other issues. https://minecraft.curseforge.com/projects/cyclic/files/2441711
