### ISSUE TITLE
Sleeping Mat - server functionality

### ISSUE THREAD

**Issue by Seth0067** [PrinceOfAmber/Cyclic#415]
Hi Lothrazar - Is it out of current spec for the sleeping mat to work on servers?  

I didnt see anything to this effect in your mod description but I have been using mats as starting gear in SP, but once I put up a server instance neither myself nor the other player on the server can make it work (clicking with it in hand does absolutely nothing)

I'm running version Cyclic-1.11.2-1.5.7.jar.  If it helps I can get you FML logs or modlists etc. Just let me know.

**Comment by PrinceOfAmber** [comment]
A modlist could help but it might not matter.  I know for sure that back in 1.10 i played on a server and it worked alongside normal beds, and also it worked with morpheus. 

 I have not yet played multiplayer in 1.11.2 , what should happen is that 2 players sleeping in whatever thing (bed/mat) pass the full night, ill have to investigate.

**Comment by PrinceOfAmber** [comment]
I just tested this on my 1.11.2 server. forge 13.20.0.2309.  I passed the night ok... but i was the only person on the server. 

I know its been a few days but modlist would help

also when you say "does absolutely nothing" what does that mean. like literally nothing? and does it make a difference if 1 or more than one person online?

**Comment by Seth0067** [comment]
Hey...  thanks for the follow-up! When I right click in hand, literally nothing happens,  
[Check this out](https://dl.dropboxusercontent.com/u/22284242/sleepmat-no-workie.mp4)

[You can find the mods I use on my pack here](https://docs.google.com/spreadsheets/d/1Br-wVxq9GmhmthFD5xvud_PN33zomZnKb17Gkw_VOLs/edit?usp=sharing)

**Comment by Seth0067** [comment]
Update (did you see my Discord messages?)  

It wasn't you!  Apparently Mcjty did something with his worldgen in his "LostCities" mod that hosed sleeping bag items.  I vcaught this because he fixed this yesterday and posted an update and included a changelog item that mentioned this.  

Good arguement foir detailed change notes!

As I said in Discord - sorry to wate any time spent here on your part.
