### ISSUE TITLE
crash on startup in 1.12

### ISSUE THREAD

**Issue by JasonKillsUs** [PrinceOfAmber/Cyclic#416]
just to be informed MC_1.12 Forge 2377:

"https://pastebin.com/VHCDkc2m"

thanks :-)

**Comment by PrinceOfAmber** [comment]
Yep all 1.12 mods are going to run into this. forge 2347 is the last version compatible , after that forge broke the registry system and made it in a different way , so all mods have to update to fix it. I hope to get this done today, but im going away for the weekend so it might be a bit late.

References
PrinceOfAmber/Storage-Network#11
https://twitter.com/lothrazar/status/879228787258408960
https://twitter.com/modmuss50/status/878387667678806017

**Comment by PrinceOfAmber** [comment]
Looks like forge RB is out which means Release Build, so that is the stable version, so im told.  I just need to convert my mod to the new system since forge removed the old system.  http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt

**Comment by PrinceOfAmber** [comment]
Hopefully a release 12 hours from this comment.  hopefully.

**Comment by PrinceOfAmber** [comment]
I downgraded all the existing 1.12 builds out there to alpha status because of this https://minecraft.curseforge.com/projects/cyclic/files

**Comment by PrinceOfAmber** [comment]
Fixed version is up https://minecraft.curseforge.com/projects/cyclic/files/2443647 .

There could be other little issues but at least my server starts up and all the stuff is there.
