### ISSUE TITLE
1.12] Poof! crash...

### ISSUE THREAD

**Issue by Migmag789** [PrinceOfAmber/Cyclic#418]
There is a crash with your cool mod ! :/
[crash-2017-06-29_17.29.50-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/1112588/crash-2017-06-29_17.29.50-client.txt)

**Comment by PrinceOfAmber** [comment]
Thanks for reporting ! 

Forge removed their old registry setup and added a new one so you may see lots of mods having trouble until they update. I will hopefully have one in a few hours .  

more info here https://github.com/PrinceOfAmber/Cyclic/issues/418

**Comment by PrinceOfAmber** [comment]
Fixed version is up https://minecraft.curseforge.com/projects/cyclic/files/2443647 .

There could be other little issues but at least my server starts up
