### ISSUE TITLE
1.12-1.5.8 Workbench Crash

### ISSUE THREAD

**Issue by sdaddy** [PrinceOfAmber/Cyclic#420]
* NOTE: I will be out of town this weekend until July 3rd *

Minecraft version:
1.12

Mod Version:
1.5.8

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Crash when opening Workbench GUI.

Crash log (if any):
https://gist.github.com/sdaddy/aa7736ee3e4c719524c423b6ce77177c

**Comment by EmoKiba** [comment]
Same Bug Occured for Me Loth
https://pastebin.com/QaKJrcBR

**Comment by PrinceOfAmber** [comment]
This should fix it https://minecraft.curseforge.com/projects/cyclic/files/2445567
