### ISSUE TITLE
Bug when using OreExcavation and a tool with Experience Boost

### ISSUE THREAD

**Issue by NamelessFTW** [PrinceOfAmber/Cyclic#421]
Minecraft version & Mod Version:
1.12, 1.5.8

Single player or Server:
single player

Describe problem (what you were doing / what happened):
When using OreExcavation and a tool with Experience Boost to break multiple blocks at the same time, the xp orbs don't appear but the player still gains experience. Then when you leave the world and re-join all the xp orbs that should have spawned appear all at once, causing huge amounts of lag if lots of blocks were broken.

Crash log (if any):
N/A

I am using both Optifine and foamfix, forge version 14.21.1.2387

**Comment by PrinceOfAmber** [comment]
Not sure why they arent spawning right away.  

I think a better/less laggy solution would just be to add the value to the players EXP count directly, and just dont drop orbs.  (  Well, the vanilla ones will still drop but bonus ones from enchant wont.)

**Comment by PrinceOfAmber** [comment]
Made that change in 1.12 https://minecraft.curseforge.com/projects/cyclic/files/2445567

**Comment by aelfwyne** [comment]
Could you make this change in 1.11.2? Having the same issue. XP Boost is creating massive lag.
