### ISSUE TITLE
Climbing Gloves fall damage

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#428]
Minecraft version & Mod Version:
Minecraft 1.12
Cyclic 1.12-1.5.9

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When you land after using the climbing gloves, you take cumulative damage for every block you've gone down. So when I climb a 15m tree, then descend 5 blocks down and climb to the top again, when I land, it will count as if I've fallen 20 blocks, as far as I can tell.

**Comment by PrinceOfAmber** [comment]
Check out the fix here https://minecraft.curseforge.com/projects/cyclic/files/2447417

**Comment by NillerMedDild** [comment]
Thanks!
