### ISSUE TITLE
Crafting Upgrade Bug

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#429]
Minecraft version & Mod Version:
Minecraft 1.12
Cyclic 1.12-1.5.9

Single player or Server:
Server

Describe problem (what you were doing / what happened):

After crafting Oak Planks in my crafting window, provided by the Crafting Upgrade, I am unable to craft Oak Planks again by any means. This continues to happen, even after restarting the game completely. I was able to craft the planks again, after using the Crafting Upgrade window to craft carpet, which I then couldn't craft afterwards.

**Comment by PrinceOfAmber** [comment]
Very strange. thanks for reporting.  Sounds similar so should be easy to fix https://github.com/PrinceOfAmber/Storage-Network/issues/13

**Comment by NillerMedDild** [comment]
What's even stranger, is that it seems to affect anyone playing on the server.

**Comment by DingoX3** [comment]
This is also happening on our server when you use the stone workbench. I was able to craft oak planks then sticks then fences up to 48 fences. After that you are no longer able to craft sticks or fences and planks. I was able to disable cyclic and delete the configs. Then I restarted the server, /fml confirmed removed blocks. Stopped server again, Then enabled cyclic, and restarted the server and let the  new configs generate. Now we are able to craft sticks, planks, fences, ect. now.

**Comment by PrinceOfAmber** [comment]
@NillerMedDild  thats weird, but good news. 

@DingoX3  i will also fix it on the workbench

**Comment by NillerMedDild** [comment]
Thanks a lot for the fast fix :D

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2447417

:)
