### ISSUE TITLE
Please OreDictionary Recipes Using Dyes

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#430]
Minecraft version & Mod Version:
All Versions (specifically 1.11.2 is what I'm working on)
All versions

Single player or Server:
All

Describe problem (what you were doing / what happened):
Could you please make your recipes requiring dyes use oredictionary? 

Thank you!
Darkosto

**Comment by PrinceOfAmber** [comment]
Yes for sure .

For my reference it should look like dyeBlack, dyePurple, etc https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L281

**Comment by PrinceOfAmber** [comment]
Added this to the 1.11.2 version, will be coming to 1.12 soon.

Hopefully i got every recipe, i reviewed each one, let me know if i missed one.

https://minecraft.curseforge.com/projects/cyclic/files/2447050
