### ISSUE TITLE
Backport XP Boost fix to 1.11.2

### ISSUE THREAD

**Issue by aelfwyne** [PrinceOfAmber/Cyclic#436]
Version 1.11.2 has the same issue with XP Boost creating excess XP orbs in the world as was reported with 1.12. This causes MASSIVE lag and even crashing on the server. Was so bad recently on my server I couldn't even issue commands on the console to /kill the xp orbs. Ended up having to restore from backup.

As you've already implemented a fix on 1.12, could you backport this to 1.11.2 as this is a game breaking bug?

**Comment by PrinceOfAmber** [comment]
Yes, i can do that

**Comment by PrinceOfAmber** [comment]
Sorry it took a while, its out in latest release https://minecraft.curseforge.com/projects/cyclic/files/2450403
