### ISSUE TITLE
Add support for the EnderTeleportEvent in ender stuffs.

### ISSUE THREAD

**Issue by darkhax** [PrinceOfAmber/Cyclic#438]
Hi there, 

I've been looking through your mod and noticed that you have a fair number of things that do ender teleportation. I was wondering if you could fire the [EnderTeleportEvent](https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/event/entity/living/EnderTeleportEvent.java) for those things. There are several mods such as Dark Utilities which redirect ender teleportation, and allow it to be completely disabled in specific areas.

**Comment by PrinceOfAmber** [comment]
So basically just fire it like this?

MinecraftForge.EVENT_BUS.post(new EnderTeleportEvent( ____________  ));

**Comment by darkhax** [comment]
Sort of, you will want more info from the event though. The event should allow you to cancel the teleportation, change the x, y and z position the entity teleports to, and change the amount of damage done to the entity. I don't believe any of your teleportation systems will damage the player, but it would still be useful for other mods. You could just pass 0 for the base damage. 

I've written some code for this related to this in Bookshelf that you're free to use. [This](https://github.com/Darkhax-Minecraft/Bookshelf/commit/21c6a1693bff72f550f086b729a6460a02988daf) commit shows the exact changes. The code for changing a players dimension is very involved to make sure it's done correctly, which is why my methods for it are so big. The code for teleporting cross dimension is optional.

**Comment by PrinceOfAmber** [comment]
This is out for 1.12-1.6.0.    https://minecraft.curseforge.com/projects/cyclic/files/2449460
