### ISSUE TITLE
Ender Carrot Tooltip

### ISSUE THREAD

**Issue by darkhax** [PrinceOfAmber/Cyclic#439]
Minecraft version & Mod Version:
1.12 - 1.5.11

Single player or Server:
Both

Describe problem (what you were doing / what happened):
The tooltip of the Ender Carrot is missing/invalid. It shows as `item.hores_upgrade_jump.tooltip'

Crash log (if any):
Nope

**Comment by PrinceOfAmber** [comment]
You should be a QA tester, good eyes!

**Comment by PrinceOfAmber** [comment]
fixed in 1.12-1.6.0.    https://minecraft.curseforge.com/projects/cyclic/files/2449460
