### ISSUE TITLE
Can't craft IC2 items

### ISSUE THREAD

**Issue by fluid-uu-matter** [PrinceOfAmber/Cyclic#441]
Minecraft version & Mod Version:
MC1.10.2
Cyclic 1.10.24

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
I put an recipe of an IC2 item into the upgraded inventory craft but it can't output the result.
Crash log (if any):
Not crashed.
(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
so the same recipe works in a crafting table but not inventory? super weird

**Comment by fluid-uu-matter** [comment]
The same recipe works invanilla crafting table, vanilla 2x2 inventory crafting grid,  AE2 ME crafting terminal, IC2's own workbench and crafter, and RFTools crafter. But not work on the Cyclic inventory 3x3 crafting grid.

**Comment by PrinceOfAmber** [comment]
Yep i confirmed this is happening still, ONLY with IC2 recipes and only in this one specific inventory screen.  Other mods such as EnderIO or thermal work fine in this screen.  Spans across all minecraft versions i just tagged. 

I tried a few things but im still not 100% sure on the fix.

**Comment by PrinceOfAmber** [comment]
Also happens in Silent Gems, finally found a fix coming soon to 1.12 . (https://github.com/SilentChaos512/SilentGems/issues/251)

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
