### ISSUE TITLE
Automated User and small mobs. 

### ISSUE THREAD

**Issue by darkhax** [PrinceOfAmber/Cyclic#442]
Minecraft version & Mod Version:
1.12 1.5.11

Single player or Server:
Both

Describe problem (what you were doing / what happened):
The Automated User doesn't seem to attack small mobs like Silver Fish. I have an example on the ATC server if you want to see.

**Comment by PrinceOfAmber** [comment]
Fixed 1.12-1.6.0.    https://minecraft.curseforge.com/projects/cyclic/files/2449460
