### ISSUE TITLE
Enable repeat events for Ender Book

### ISSUE THREAD

**Issue by darkhax** [PrinceOfAmber/Cyclic#443]
When entering the name of an entry in the Ender Book, you have to hit the backspace key each time, and holding the key down does not work. It would be nice if you allowed this. IIRC the way to enable it is by enabling repeat events. 

```java
    @Override
    public void initGui () {

        Keyboard.enableRepeatEvents(true);
    }

    @Override
    public void onGuiClosed () {

        Keyboard.enableRepeatEvents(false);
    }
```

**Comment by PrinceOfAmber** [comment]
This is out for 1.12-1.6.0.  Probably eventually coming to 1.11 and 1.10 .
