### ISSUE TITLE
Caught Exception from Guide API

### ISSUE THREAD

**Issue by blackviperr** [PrinceOfAmber/Cyclic#445]
Minecraft version & Mod Version: 1.11.2

Single player or Server: single player

Describe problem (what you were doing / what happened):
I can't update past 1.2.9 b/c it crashes on startup due to a conflict with guide api every time

Crash log (if any):

https://pastebin.com/BTxEjb30

**Comment by PrinceOfAmber** [comment]
Seems like maybe your Guide API version is out of date, a new brewing recipe page was added.

It should work if you update to Guide-API-1.11.2-2.1.1-52.jar

**Comment by blackviperr** [comment]
thank you!!
