### ISSUE TITLE
[1.12] Entity Detector

### ISSUE THREAD

**Issue by Alaric323** [PrinceOfAmber/Cyclic#446]
Minecraft version & Mod Version: 1.12, Mod Version 1.6.0

Single player or Server: Singleplayer

Describe problem (what you were doing / what happened):

Entity Detector only detects players in the positive direction of coordinates.  Not sure if this is an intended change, but it wasn't like this in 1.10.2.  Video linked below shows the problem.

https://youtu.be/BqGw7FrTHgo

**Comment by PrinceOfAmber** [comment]
Yep yep looks like the detection area / radius is offcenter

**Comment by PrinceOfAmber** [comment]
Check out the improvements https://minecraft.curseforge.com/projects/cyclic/files/2451410
