### ISSUE TITLE
Ability to Cancel Sleeping Mat

### ISSUE THREAD

**Issue by SaxonHeart** [PrinceOfAmber/Cyclic#448]
Minecraft version & Mod Version:
1.12

Single player or Server:
Server

Describe problem (what you were doing / what happened):

Crash log (if any):

We need a way to cancel Sleeping Mat. On servers that take multiple people to end night Sleeping Mat leaves you stuck in place through the rest of night if no one else sleeps for whatever reason.

**Comment by PrinceOfAmber** [comment]
I will add in 1.6.1 so that you can sneak to cancel the sleeping.

**Comment by PrinceOfAmber** [comment]
Update is out https://minecraft.curseforge.com/projects/cyclic/files/2451410
