### ISSUE TITLE
Cyclic Harvester - IE interaction

### ISSUE THREAD

**Issue by gefailter71** [PrinceOfAmber/Cyclic#451]
MC version: 1.12
Cyclic version: 1.12-1.6.1
Immersive Engineering version: 0.12-67

Server: true

Cyclic Harvester doesn't seem to break the fully grown Hemp plants from Immersive Engineering.

**Comment by PrinceOfAmber** [comment]
Hmm, i tried doing this but i noticed the latest version of IE is 0.12-68.    I just bonemealed up the crops and put fuel in the harvester and it was working.  I made a quick imgur album.

http://imgur.com/a/dCibb

Can you try in latest IE build? If it still doesnt work for you, there could be some other weird thing happening, so a list of all mods on server would help figure this out.

**Comment by gefailter71** [comment]
I created a new profile with only Cyclic and IE on the latest builds it only works with coal inside the Harvest otherwise it won't touch the Hemp. Is it supposed to harvest the Hemp like this?: 
![image](https://user-images.githubusercontent.com/20716525/28498901-38b2d128-6fa9-11e7-96e9-ff36c18013ce.png)

List of mods would be the ATM3 pack version: 2.3 will provide u with a Pastebin of the mods if necessary.

**Comment by PrinceOfAmber** [comment]
OH right.  Yeah as of 1.6.0 all machines do not run for free, they only run with fuel.  Thats kind of a big change i should put it on the top of the curse page

**Comment by PrinceOfAmber** [comment]
Closed since its working perfectly for me and no updates in a while.

Reopen or make a new issue if you have any other issues!
