### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [PrinceOfAmber/Cyclic#453]
Latest build makes MC fall over during load?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Quark-r1.2-102.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/23/17 8:46 AM
Description: Initializing game

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
	at net.minecraftforge.fluids.FluidUtil.getFilledBucket(FluidUtil.java:701)
	at com.lothrazar.cyclicmagic.registry.FluidsRegistry.addRecipes(FluidsRegistry.java:51)
	at com.lothrazar.cyclicmagic.registry.RecipeRegistry.onRegisterRecipe(RecipeRegistry.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_438_RecipeRegistry_onRegisterRecipe_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:733)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
	at net.minecraftforge.fluids.FluidUtil.getFilledBucket(FluidUtil.java:701)
	at com.lothrazar.cyclicmagic.registry.FluidsRegistry.addRecipes(FluidsRegistry.java:51)
	at com.lothrazar.cyclicmagic.registry.RecipeRegistry.onRegisterRecipe(RecipeRegistry.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_438_RecipeRegistry_onRegisterRecipe_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:733)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 839395344 bytes (800 MB) / 2584334336 bytes (2464 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2419 103 mods loaded, 103 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2419.jar) 
	UCH	forge{14.21.1.2419} [Minecraft Forge] (forge-1.12-14.21.1.2419.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCH	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UCH	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCH	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UCH	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCH	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	UCH	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCH	quark{r1.2-102} [Quark] (Quark-r1.2-102.jar) 
	UCH	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCH	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCH	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCH	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCH	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCH	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCH	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.3 mc1.12.jar) 
	UCH	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCH	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UCH	cyclicmagic{1.7.0} [Cyclic] (Cyclic-1.12-1.7.0.jar) 
	UCH	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCH	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCH	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCH	movingworld{1.12-4.340} [Moving World] (movingworld-1.12-4.340-full.jar) 
	UCH	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-4.334-full.jar) 
	UCH	dsurround{3.4.6.0} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCH	presets{3.4.6.0} [Presets!] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCH	eim{1.0} [eim] (EIM-1.0.0.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	csb_ench_table{1.1.2-beta2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2-beta2.jar) 
	UCH	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCH	everlastingabilities{1.3.1} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.1.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCH	flatcoloredblocks{mc1.12-6.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.3.jar) 
	UCH	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCH	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCH	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCH	funores{1.5.6} [Fun Ores] (FunOres-1.12-1.5.6-116.jar) 
	UCH	goodluckskeleton{1.0} [Good Luck Skeleton] (goodluckskeleton-1.1-MC1.12.jar) 
	UCH	gravestone{1.0.11} [Gravestone] (GraveStone-1.12-Graves-1.0.11.jar) 
	UCH	igcm{1.0.0} [InGameConfigManager] (IGCM v1.2.0 pre-1 mc1.12.jar) 
	UCH	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCH	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCH	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCH	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.3-1.12.jar) 
	UCH	limelib{1.7.4} [LimeLib] (limelib-1.12-1.7.4.jar) 
	UCH	malisiscore{1.12-6.0.1} [MalisisCore] (malisiscore-1.12-6.0.1.jar) 
	UCH	malisisblocks{1.12-6.0.0} [Malisis Blocks] (malisisblocks-1.12-6.0.0.jar) 
	UCH	malisisdoors{1.12-7.0.2} [MalisisDoors] (malisisdoors-1.12-7.0.2.jar) 
	UCH	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	UCH	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCH	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCH	mendingfix{1.0.1} [Mending Fix] (mendingfix-1.0.1.jar) 
	UCH	minecolonies{1.12-0.8.3167} [MineColonies] (minecolonies-universal-1.12-0.8.3167.jar) 
	UCH	minemenu{1.6.1} [MineMenu] (MineMenu-1.12-1.6.1-universal.jar) 
	UCH	minions{2.0.2} [Minions] (Minions-1.12.jar) 
	UCH	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCH	mobends{0.23.4} [Mo' Bends] (mobends-0.23.4_for_MC-1.12.jar) 
	UCH	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCH	modlister{1.12-3.2.3} [ModLister] (ModLister-1.12-3.2.3.jar) 
	UCH	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCH	ob_stuff{1.1} [MSU: OpenBlocks Stuff] (MSU-OpenBlocks Stuff-1.1.jar) 
	UCH	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCH	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCH	packingtape{0.7.4} [Packing Tape] (PackingTape-1.12.0-0.7.4.jar) 
	UCH	harvestcraft{1.11.2i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN.jar) 
	UCH	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCH	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCH	reauth{3.5.1} [ReAuth] (ReAuth-3.5.1.jar) 
	UCH	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
	UCH	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCH	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCH	scannable{1.4.1.6} [Scannable] (Scannable-MC1.12-1.4.1.6.jar) 
	UCH	icc{0.2.1} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.1.jar) 
	UCH	simplebedding{1.1.0} [Simple Bedding] (simplebedding-1.1.0.jar) 
	UCH	simpleleather{1.12-1.0} [Simple Leather] (simpleleather-1.12-1.0.jar) 
	UCH	simplemagnet{1.12.0-1.2.6} [Simple Magnet] (simplemagnet-1.12.0-1.2.6.jar) 
	UCH	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCH	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCH	sounds_extended{1.8.2-1.12} [Sounds Extended] (sounds extended-1.8.2-1.12.jar) 
	UCH	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UCH	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCH	thut_wearables{3.0.4} [Thut's Wearables] (thut_wearables-3.0.4.jar) 
	UCH	thutcore{5.5.0} [Thut Core] (thutcore-5.5.0.jar) 
	UCH	thut_bling{2.0.0} [Thut's Bling] (thut_bling-2.0.0.d.jar) 
	UCH	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCH	tombstone{1.2.8} [Corail Tombstone] (tombstone-1.2.8-1.12.0.jar) 
	UCH	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCH	treechopper{1.2.1} [Tree Chopper] (TreeChopper-1.12-1.2.1.jar) 
	UCH	uncrafted{3.0.0pre2} [Uncrafted Mod] (Uncrafted 1.12 (v.3.0.0pre2).jar) 
	UCH	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCH	vctweaker{@MOD_VERSION@} [ViesCraft Tweaker] (ViesCraftTweaker-1.12-2.0.6.jar) 
	UCH	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCH	vtt{0.6.4} [Villager Trade Tables] (VillagerTrades-1.12-0.6.4.jar) 
	UCH	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Quark-r1.2-102.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Launched Version: 1.12-forge1.12-14.21.1.2419
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TEAVSRP2.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by JasonKillsUs** [comment]
yep same here :(

**Comment by trilexcom** [comment]
same on our pack https://pastebin.com/UUW3kc5d

**Comment by ElectricBlue1** [comment]
Im no pro but for now downgrade to the version that doesnt crash lol

**Comment by PrinceOfAmber** [comment]
Yep ill get this fixed tonight. It doesnt crash for me when ONLY cyclic is installed , looks like some conflicts with the poison fluid

**Comment by PrinceOfAmber** [comment]
For future reference: The bug is still i think my fault but its specifically conflicting with something in Biomes o Plenty.   Crash log with only these two mods installed:  https://pastebin.com/FdYbEX9Q

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2456094
