### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by jeffwcollins** [PrinceOfAmber/Cyclic#454]
Minecraft version & Mod Version: All The Mods 3 (2.3)

Single player or Server: Server

Describe problem (what you were doing / what happened):  The Builder will not complete building when placed under water.  It was placed on the bottom of a shallow ocean, and it took blocks to build above water and below the ocean floor, but would not build in the water itself.  I waited for an entire stack of coal to make sure I wasn't losing my mind, and while I may still be, the shape didn't finish.

I live the mod by the way, great job.

**Comment by PrinceOfAmber** [comment]
thanks for the nice words! Yeah i think currently it looks for exactly air blocks, but when a player builds certain materials are "replaceable" like water, so this is a nice feature that i will add.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2456094
