### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#456]
Single Player MC-1.12, Cyclic 1.7.0

Crash on startup, Tested without Cyclic and then it doesn't crash.

[Crashreport](https://pastebin.com/6NWzYbik).

**Comment by Ash70** [comment]
Just noticed this might be the same as #453 ?

**Comment by OrdinatorStouff** [comment]
Same thing on ATC -- forge 2424 and 2420 same error. cyclic 1.7.0
https://pastebin.com/j8Lrbxgg

**Comment by PrinceOfAmber** [comment]
yep duplicate of #453 . conflict is because poison is already added by biomes o plenty first, and then im adding a recipe for a Poison Bucket in an **unsafe** way.  Fix coming soon in 1.7.1
