### ISSUE TITLE
minor path problem

### ISSUE THREAD

**Issue by boosterdev** [PrinceOfAmber/Cyclic#457]
Minecraft version & Mod Version:
1.11.2 + latest 1.11.2 version ;)

Single player or Server:
Both

Describe problem (what you were doing / what happened):
wrong path Q:/CODE/minecraft/eclipseWorkspace/
(src/main/java/com/lothrazar/cyclicmagic/registry/RecipeFileWriter.java)

Crash log (if any):
no crash just a big log
https://gist.github.com/boosterdev/f55ce3cc9095192eb0372bea81caddb0

**Comment by PrinceOfAmber** [comment]
yeah good call, i meant to disable that before release oops

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2456973
