### ISSUE TITLE
Change torch launcher recipe & add refuel mechanic

### ISSUE THREAD

**Issue by AlexMason** [PrinceOfAmber/Cyclic#459]
I have a suggestion to change the 'Torch launcher' to 'Rechargeable Torch Launcher'(RTL).  With this I propose the following recipe changes, to make it more in line with vanilla: (coal or charcoal, the block doesn't matter)
![torch1](https://user-images.githubusercontent.com/740625/28630574-9ff9fa86-71f8-11e7-996e-2f66b04abc14.png)

Also, I propose adding a refuel mechanic to the torch, the player can add charges by craft a piece of wood, plank, stick, or (char)coal in a crafting grid with the RTL. 

Here is my proposed amount of torches you get:
Stick - 1
Plank - 2
Wood - 8
(Char)coal - 8

The idea is being able to store my torch charges then a single stack of torches.  Maybe a limit of 256?  You could also make it slightly less efficient by tweaking the refuel amount, maybe removing sticks and reducing others. 

I think this is a good idea, let me know.

**Comment by PrinceOfAmber** [comment]
Yeah a refuel would make sense.  Have it not completely break at zero and add some reload mechanic.

**Comment by PrinceOfAmber** [comment]
its not exactly as you imagined it, but it is repairable in an anvil https://minecraft.curseforge.com/projects/cyclic/files/2457419
