### ISSUE TITLE
[1.12] Can't Sneak+Click fuel into the furnace, also punching the furnace with fuel doesn't work.

### ISSUE THREAD

**Issue by dragon3025** [PrinceOfAmber/Cyclic#460]
Minecraft version & Mod Version: 1.12 and 14.21.1.2420

Single player or Server: Single Player

Describe problem (what you were doing / what happened): I think cyclic is preventing sneak+clicking fuel into the furnace in the furnace gui (I was guessing this mod was causing it because of the option to sneak+highlighting fuel to see it's duration, which I also tried turning off but it still wouldn't allow me to sneak+click it into the fuel slot).

Also punching the furnace with coal or iron only places items in the material slot, and not the fuel slot.

**Comment by PrinceOfAmber** [comment]
I'll check it out

**Comment by PrinceOfAmber** [comment]
When only cyclic is installed and nothing else, i can shift click fuel in just fine.  I think there is a mod that ads a recipe where you smelt coal into something and that messes it up.

Not sure which mod, looking into it a bit more

**Comment by dragon3025** [comment]
That would the Extreme Reactors mod. I tested it out just now and I'm able to shift+click the coal into the furnace if Extreme Reactors isn't installed.

**Comment by PrinceOfAmber** [comment]
Aha thanks for the update. That explains it.

**Comment by swestrup** [comment]
I am playing the FTB Horizons III pack and I can't find any way to automatically refuel an automated user. Any attempt to pump something in, from any side, just has it go in the input slot.
