### ISSUE TITLE
Suggestion -- Harvester block upgrade that affects all iGrowables in range at once

### ISSUE THREAD

**Issue by OrdinatorStouff** [PrinceOfAmber/Cyclic#461]
Just like the Scythe item (can't remember the name offhand) it would be really cool to get some kind of upgrade option to the harvester that could do the same every "operation" -- uproot/replant every plant in it's range in one go.

With extremely fast plant growth, not even multiple harvesters affecting the same range can keep up with reaping them fast enough that many plants sit idle for some time.

If using fuel, this mode could consume much more, this mods could also be a little slower like once every second or two maybe.

**Comment by OrdinatorStouff** [comment]
Or maybe an upgrade slot that you can place one of those scythe things into that it consumes durability from each time the harvester operates

**Comment by PrinceOfAmber** [comment]
Yes, there is the garden scythe that already does the large area.  Good idea to put them together.  So it goes in a restricted slot and then it does the area at once.  Ill put this on my list.

**Comment by PrinceOfAmber** [comment]
It was easier just to put in a button to toggle between Single and Area.  so area just costs more fuel.
