### ISSUE TITLE
[1.12] Step Up Permanently Feature Request

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#465]
Minecraft version & Mod Version:
MC: 1.12
Cyclic: 1.7.3

Single player or Server:
All of the above

Describe problem (what you were doing / what happened):
It's not a problem, per se. I would like to request a config option that allows the step up ability from the apple of lofty stature effect to be available all the time without eating the item. If you do this, I will grant you my dowry.

My dowry includes the following:
16 chickens
2 pigs (both male)
4 1/2 pairs of pantaloons
7 socks (not paired)
My 1 horse
My save in Cookie Clicker
A bottle of slightly expired salad dressing
Dark Souls 2: Scholar of the first sin edition
And a partridge in a pear tree

Crash log (if any):
This mod has never caused any crashes because it is simply amazing AND! for the low price of a step up config option it could be THE GREATEST MOD OF ALL TIME!

THANKS YOU!
Darkosto

**Comment by PrinceOfAmber** [comment]
Yeah, what i can do is just add a config so that we default new players with it turned on instead of turned off (so they could still craft and eat to toggle as normal.)

**Comment by PrinceOfAmber** [comment]
I've also added "HeartContainerDefault" just for fun

**Comment by PrinceOfAmber** [comment]
I tested these in both single player and multiplayer, let me know if theres any issues.  1.7.4 https://minecraft.curseforge.com/projects/cyclic/files/2460319

**Comment by Darkosto** [comment]
Thank you <3 <3 <3
