### ISSUE TITLE
Can't disable poison bucket

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#466]
Minecraft version & Mod Version:
Minecraft 1.12.1
Cyclic 1.7.5

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Even with all of the features disabled in the mod's settings (and restarting Minecraft after doing so), it's still possible to craft and use a poison bucket.

Crash log (if any):
N/A

**Comment by PrinceOfAmber** [comment]
Oh right, forgot to add a  config for the fluids. I will add one for the poison and the other fluids as well

**Comment by PrinceOfAmber** [comment]
I added these configs https://minecraft.curseforge.com/projects/cyclic/files/2461830
