### ISSUE TITLE
Parse error on Version Check JSON (Cyclic 1.11.2-1.5.9)

### ISSUE THREAD

**Issue by sibomots** [PrinceOfAmber/Cyclic#468]
Minecraft version & Mod Version:

forge-1.11.2-13.20.1.2429
Cyclic-1.11.2-1.5.9.jar

Single player or Server:
Server

Describe problem (what you were doing / what happened):
During server startup, the plugin attempts to retrieve a JSON file with meta data about the versions compared to the instance on the server.
After dumping the JSON to the fml-server-latest.log, the error message (below) indicates that the JSON might be out of spec.

Confirm?

Crash log (if any):
[15:15:02] [Forge Version Check/DEBUG] [ForgeVersionCheck/forge]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 183 column 4

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)
It' a bug report because it may be a condition that the JSON output is not to spec and thus failing the process to interpret the results.

**Comment by PrinceOfAmber** [comment]
Thanks for noticing! Ill get on that
