### ISSUE TITLE
[1.12] Harvester Inventory Bug

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#471]
Minecraft version & Mod Version:
Minecraft 1.12
Forge 1.12-14.21.1.2443
Cyclic 1.12-1.7.6

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The Harvester only utilizes two of its three internal inventory rows:

![javaw_2017-08-10_16-00-19](https://user-images.githubusercontent.com/21295394/29173993-45b44042-7de5-11e7-896c-f352d46db90c.png)
It spits out items it doesn't think it has room for.
![javaw_2017-08-10_16-00-15](https://user-images.githubusercontent.com/21295394/29173998-489a3f96-7de5-11e7-85b8-6eb41ff165e9.png)

**Comment by PrinceOfAmber** [comment]
Fixed in latest build, let me know if it doesnt work https://minecraft.curseforge.com/projects/cyclic/files/2463725

**Comment by NillerMedDild** [comment]
Thank you!
