### ISSUE TITLE
Crash upon quitting the game

### ISSUE THREAD

**Issue by asiekierka** [PrinceOfAmber/Cyclic#474]
Minecraft version & Mod Version: 1.12.1, Cyclic 1.7.7

Single player or Server: Single player

Describe problem (what you were doing / what happened): Quit the game, will happen randomly. Same issue happened in Quark - https://github.com/Vazkii/Quark/issues/573

Crash log (if any): http://paste.asie.pl/3LrU

**Comment by PrinceOfAmber** [comment]
New version checks the keyboard is created before accessing https://minecraft.curseforge.com/projects/cyclic/files/2465120
