### ISSUE TITLE
Infinite XP Bug

### ISSUE THREAD

**Issue by gefailter71** [PrinceOfAmber/Cyclic#475]
Forge version: 2443
Cyclic version: 1.7.5
DE Version: 2.3.2.258-universal
MC: 1.12
Server: true

Activating "Spray" on the Experience Pylon while the Draconic Evolution Magnet is activated causes something to break and give u infinite XP without draining anything. It won't stop after breaking the Pylon or deactivating the Magnet.

**Comment by PrinceOfAmber** [comment]
When this happens is the "collect" mode on? maybe both the magnet and the pylon are collecting the same exp orb at the same time.  I havent used Draconic in a while, ill do some testing.

**Comment by PrinceOfAmber** [comment]
Caused when Pylon tries to collect the orb and set isDead = true, but then magnet acts at the same moment and double collects.

As workaround I will attempt to set value to zero, and set pickup delay to large value, also cross reported to draconic tracker

**Comment by PrinceOfAmber** [comment]
@gefailter71 FYI the draconic dev said quote "Will be fixed in the next release." in the link above there, so looks like bug was on their side! Sounds good to me!
