### ISSUE TITLE
Mining dynamite explodes in water near land

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#476]
Minecraft version & Mod Version:
Minecraft 1.12, Cyclic 1.7.7

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
When throwing mining dynamite into water very close to land, it will often explode as if it hit land, rather than doing nothing like it does when landing in the middle of water.

Crash log (if any): N/A

**Comment by PrinceOfAmber** [comment]
Changed them to not explode in water https://minecraft.curseforge.com/projects/cyclic/files/2465120

**Comment by josephcsible** [comment]
I think this went a bit far. They used to "boom" in water but, except for this bug, not break stuff, and now they don't even "boom" anymore.
