### ISSUE TITLE
Automated user plays animation when out of energy

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#477]
Minecraft version & Mod Version:
Minecraft 1.12, Cyclic 1.7.7

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
When an automated user is set to "Always on" or is receiving a redstone signal, it always plays its active animation, even if it's out of energy.

Crash log (if any): N/A

**Comment by PrinceOfAmber** [comment]
I think this also happens with Uncrafter, possibly others

**Comment by PrinceOfAmber** [comment]
Fixed in latest version https://minecraft.curseforge.com/projects/cyclic/files/2466488
