### ISSUE TITLE
Fuel tweaks

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#479]
A few suggestions for the fuel system:

1. Can a config option be added to make fuel not be required?
2. The fuel gauge is currently kind of wonky. Both a chunk of coal and a coal block will fill it up to the same level, but it will then count down much slower with the coal block, so there's no way to tell at a glance how much fuel you really have left.
3. Could you make it possible for machines to be able to run on both energy and fuel? I saw in #192 you didn't want to add dependencies, but this would give the option of integration without a requirement, since fuel itself would still work.

**Comment by PrinceOfAmber** [comment]
1. Yep I will add one global config that will disable fuel needs for all machines
2. Yeah, right now the fuel number is a percentage.  Exactly the same way as the furnace fuel icon simply burns slower if you use lava, or faster if you use sticks.  But I see how that feels weird based on the way it looks, and when compared to RF power and such.  I think the largest burn value is Lava buckets, so i could add that as the maximum value, so then it would eat a few coal at once to fill up to the top.  Ill have to do some planning for this.
3. Ive been going back and forth on Energy systems.  We do have that new Forge Energy system built right into forge now, so I suppose i could wrap up both 2 and 3 at the same time by simply using that. Ill think on it

**Comment by PrinceOfAmber** [comment]
I have added a tooltip to the fuel bar to show the precise amount

Also i added an optional global config to move the fuelbar to the top.  Default is unchanged.


![2017-08-19_00 20 23](https://user-images.githubusercontent.com/621529/29484477-4c1aaf9e-8474-11e7-813c-d9bcfac0a3ec.png)
![2017-08-19_00 17 10](https://user-images.githubusercontent.com/621529/29484476-4c1a3398-8474-11e7-9f53-48f00279b1ad.png)

**Comment by PrinceOfAmber** [comment]
Fixed in latest version https://minecraft.curseforge.com/projects/cyclic/files/2466488

**Comment by josephcsible** [comment]
Two things:
1. If you change the "machines need fuel" option in-game, it doesn't work right until you restart the world, but you never set requiresWorldRestart for that option. Can you add that?
2. It doesn't look like you added Forge Energy. Should I open a new issue just for that?
