### ISSUE TITLE
Send mined blocks to inventory

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#480]
Suggestion: blocks harvested by a block miner or controlled miner should be able to be sent to an inventory, rather than dropped into the world as items.

**Comment by PrinceOfAmber** [comment]
For the block miner, I like keeping it the way it is to have a simple version, but i could add an upgraded version with an inventory.

For the controlled miner i can add a few inventory slots for collected blocks, so just like the Harvester it would collect during processing and you can export with hoppers or pipes easily.

**Comment by PrinceOfAmber** [comment]
I forgot that I added the item collector. Just put this beside the miner and it will pick up every drop!  It even has a whitelist system.  

Eventually item collector may get more features if requested such as size and range controls

**Comment by josephcsible** [comment]
I don't think that's ideal (among other things, a quick player could get the drops before the item collector), but I guess it will work.
