### ISSUE TITLE
[1.12] Hydrator dupe bug

### ISSUE THREAD

**Issue by Lukas45** [PrinceOfAmber/Cyclic#483]
Minecraft version & Mod Version:
1.12
Cyclic 1.7.8

Single player or Server:
Found on server (Enigmatica 2 modpack)
Replicated on Single Player with only Cyclic/JEI/JourneyMap

Describe problem (what you were doing / what happened):
If you shift click an item into the Hydrator with water in it, it has a high chance of duplicating (Double the amount gets inserted).
It was inconsistent in the single player test, but very consistent on the server

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
At first this wasnt happening with some items but now i see it happen.

First I filled it with water and turned the machine on.

Then i put a stack of dirt in there.  
Some of the dirt turned to farmland, and then when it got down to about 58 from 64, I shift click out the dirt, then back in, the same stack. 
 Suddenly its up to 63 now, but the farmland is still there. So dirt was duped.

**Comment by Lukas45** [comment]
Forgot to note that I set the machine to Always On, if that's relevant.
Items I managed to dupe:
Ice (Server)
Buckets (Server)
Marble (Server)
Iron Doors (Single Player)
Beacons (Single Player)

**Comment by PrinceOfAmber** [comment]
Fixed in latest version https://minecraft.curseforge.com/projects/cyclic/files/2466488

**Comment by Lukas45** [comment]
Hey again.
So our server just updated Cyclic to 1.7.9 (pack update happened right before 1.7.10 released), and this did not get fixed with the latest releases (neither 1.7.9 or 1.7.10 (tested in stand-alone)).

I did manage to find the consistent method for this dupe though. If you shift-click anything in from the Inventory (so not Hotbar), it will dupe in the Hydrator. Redstone mode, water/no water doesn't matter. The Hotbar not being affected is probably what lead it to be inconsistent in the first place (didn't really think about that as a factor).
