### ISSUE TITLE
[1.12.1] JEIPlugin

### ISSUE THREAD

**Issue by Blatts12** [PrinceOfAmber/Cyclic#484]
Minecraft version & Mod Version:
1.12.1

Single player or Server:
Client

Describe problem (what you were doing / what happened):
I saw it in my log

Crash log (if any):
Just log
https://pastebin.com/4N2dWvvA

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Fixed in latest version https://minecraft.curseforge.com/projects/cyclic/files/2466488
