### ISSUE TITLE
[Bug] Auto Smelt Enchantment Dropping More than Expected with Silent's Gems

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#485]
**Minecraft version & Mod Version:**
1.12
Cylic 1.7.7
Silent's Gems Version: 2.4.5

**Single player or Server:**
Single Player

Describe problem (what you were doing / what happened):
Using enchantment token provided by Silent's Gems to add Auto Smelt to various SG tools and vanilla tools (tested with only iron pickaxe) drops full stacks of stone when mining one block of stone/cobblestone. Sometimes it will also drop 4 full stacks of bricks from clay (not consistently), and sometimes it will drop 3-4x tin ingots from Thermal Foundation tin ore. Ores from other mods such as Embers and FuturePack seem unaffected in terms of quantity (they still smelt into respective ingots).

https://github.com/SilentChaos512/SilentGems/issues/198

**Comment by PrinceOfAmber** [comment]
Might be related to https://github.com/PrinceOfAmber/Cyclic/issues/404 .

This enchantment SHOULD do nothing if there is no smelting recipe for the item. For example, if putting the silents gems ore into the furnace has no output  then it should folllow that.  ill look into it.

**Comment by PrinceOfAmber** [comment]
There must be some third mod interfering, or some smelting recipes being added.  Can i have this information to solve this problem @Vyraal1 

- Can any of the gems be smelted in a furnace (i show them not smelting in the video below
- Which modpack you are playing in, OR
- if its not a curse modpack, a list of mods you are using (For a list of mods this is listed fully in the /logs/latest.log file)


I made an unlisted youtube video of me trying to replicate this problem, watch below.  I a small list of mods installed including Cyclic, silent's gems, draconic, evilcraft, thermal expansion, and a few others.  Its not happening for



https://www.youtube.com/watch?v=lvpnyzyEkMI&feature=youtu.be

**Comment by PrinceOfAmber** [comment]
Oh i misread your comment you said mining stone or cobblestone .

Right after making that video i tried mining some stone in the world, and i just get one smoothstone dropping each time.

So there still is a problem, i just dont know which combination of mods exactly is causing it

**Comment by SilentChaos512** [comment]
I'm the developer of Silent's Gems. I just tested this with just Cyclic and Gems and I see the issue. It seems to be linked to the Area Miner ability (mines a 3x3 when enabled) of supercharged pickaxes. The first use yielded 8 stone per block, the second use was full stacks. This is also modifying the stone stack in the cobblestone -> stone smelting recipe.
Why this is linked to Area Miner I'm not sure, but this looks like you need to be creating a copy of the smelting recipe's output stack. Currently, the original is being modified somewhere:
![2017-08-19_12 35 03](https://user-images.githubusercontent.com/5721949/29488965-183a5564-84db-11e7-99d8-930f41c2876c.png)

**Comment by PrinceOfAmber** [comment]
"this looks like you need to be creating a copy of the smelting recipe's output stack. Currently, the original is being modified somewhere:"
Thanks for the info, ill try that!!!

Sorry i didnt reply right away, been a busy week
