### ISSUE TITLE
[1.12] LAN Player Disconnect After Cyclic Error

### ISSUE THREAD

**Issue by MokahTGS** [PrinceOfAmber/Cyclic#487]
Minecraft version & Mod Version:
Minecraft 1.12 
Cyclic 1.79

Single player or Server:
Single Player Hosted LAN

Describe problem (what you were doing / what happened):
I was using the Cyclic Sack of Holding to pick up a storage crate.  The game lagged out and the other player got disconnected.

Crash log (if any):
No crash log but this was in the game log at the time of disconnect: https://pastebin.com/6RWLcdpm

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Cant replicate this in my lan world but the crash log shows me where its happening. ill try to get an error handler in there, im guessing some sort of crash caused by lag

**Comment by PrinceOfAmber** [comment]
Has it happened many times or just the once? I can patch it just in case .. just curious

**Comment by MokahTGS** [comment]
Lots of times truthfully

**Comment by PrinceOfAmber** [comment]
This should patch it https://minecraft.curseforge.com/projects/cyclic/files/2468801
