### ISSUE TITLE
Sort your creative tab

### ISSUE THREAD

**Issue by The-Fireplace** [PrinceOfAmber/Cyclic#488]
[Here's a tutorial.](http://www.minecraftforge.net/forum/topic/23576-sorting-your-creativetab/)
If you sort it, it will make it far easier to navigate this mess:
![2017-08-23_14 32 52](https://user-images.githubusercontent.com/5914284/29634611-073477b2-8810-11e7-9c2b-b9e06585bb92.png)

**Comment by PrinceOfAmber** [comment]
Hey cool! I didn't know this was possible.

**Comment by PrinceOfAmber** [comment]
Tutorial worked perfectly @The-Fireplace  !!! I replaced the explicit ordering with Ordering.usingToString(), just so i didnt have to make a list of everything.   Next if i see anything out of order I can just tweak the toString of that instance. its much better already

**Comment by PrinceOfAmber** [comment]
On second thought i might go to explicit order after all.

Side note: I found a way to add all my enchantments to the tab! see next commit below this
