### ISSUE TITLE
Glowing Chorus Fruit persists in death

### ISSUE THREAD

**Issue by ulkunderscore** [PrinceOfAmber/Cyclic#489]
Minecraft version & Mod Version: MC 1.12, Cyclic 1.7.9
Single player or Server: Singleplayer

The flying effect from the glowing chorus fruit persists in death, potentially trapping you in hours of creative flight.
Also, there is a small naming inconsistency: It's the "Corrupted Chorus" but the "Glowing Chorus Fruit".

**Comment by PrinceOfAmber** [comment]
Youre right on both counts

**Comment by PrinceOfAmber** [comment]
It does persist flying through death.  But this is working as intended, as long as the timer still expires and removes flying (timer in top right)

So my steps were

-eat in survival, get the flying timer
- kill self many times
- still flying, timer still works
- wait until it expires. flying goes off as normal.

Is this the same thing you notice.

![fly](https://user-images.githubusercontent.com/621529/29699801-48d21698-8914-11e7-8787-4ec813ec564d.png)

**Comment by PrinceOfAmber** [comment]
If the timer runs out and its still flying, that is a bug, but i didnt see that happen

**Comment by ulkunderscore** [comment]
Oh no then it's not a bug. I expected it to behave like a potion effect. 
I was talking about hours because I stacked up ~70 minutes of flight in my testworld and thought it could be an issue in survival if people used it as food or just tried to see how high it would go. Mostly due to the slower block breaking speed. I just now found out that you can sneak to get around that, so I don't see an issue anymore. It's just unexpected.
