### ISSUE TITLE
Magnet enchant on non-tools

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#493]
Would it be possible to add the ability to put the magnet enchantment on (e.g.) armor. Usecase: Currently making a modpack that makes heavy use of non-enchantable tools (like tinkers) so I'd like to have the ability to put this enchant on another item. I know tinkers has the magnet trait, but it just doesn't work very well (short range).

**Comment by PrinceOfAmber** [comment]
Thought about this off and on for a while.  I think instead of this, i can go even further and just make a magnet item.

By making it a standalone item, i can let the player configure it between both items & exp, only items, or only exp.

**Comment by Ash70** [comment]
Sounds good to me.

**Comment by PrinceOfAmber** [comment]
Magnet enchant updated in this version, works on any gear  https://minecraft.curseforge.com/projects/cyclic/files/2498679 

magnet item was more trouble than its worth, especially now with potion + pharos beacon

**Comment by Ash70** [comment]
Fantastic, thank you.
