### ISSUE TITLE
Harvester/Scythe Not correctly reaping ResourcefulCrops plants

### ISSUE THREAD

**Issue by OrdinatorStouff** [PrinceOfAmber/Cyclic#494]
Minecraft version & Mod Version:
1.12.1
Cyclic-1.12-1.7.9.jar

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Harvester and Scythe do not properly reap crops whose drops contain NBT
This example: **resourceful crops**. The crops drop a shard that is defined by it's nbt tag. When harvested by cyclic harvester or scythe the shard is "invalid" and doesn't match the nbt/meta of the shard that's supposed to drop.

Crash log (if any):
none

Normal Crop drops:
![image](https://user-images.githubusercontent.com/6283913/29856793-0cec06b2-8d0a-11e7-9812-ba4c8f76e949.png)

Cyclic reaped:
![image](https://user-images.githubusercontent.com/6283913/29856822-3f47e9fa-8d0a-11e7-84a7-693acf7a28fd.png)

**Comment by PrinceOfAmber** [comment]
What version of resourceful crops are you using? I tried to install and use it but it just crashed right away for me . I literally just opened the game and tried to find inky shards in creative inventory  The newest that the launcher gave me was ResourcefulCrops-1.12-2.1.0-61.jar) 

Im noting the changelog here in case i need to forward it to author

 
-- Item being rendered --
Details:
	Item Type: tehnut.resourceful.crops.item.ItemResourcefulPouch@7b05c69a
	Item Aux: 0
	Item NBT: {seed:"resourcefulcrops:inky"}
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:644)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

**Comment by OrdinatorStouff** [comment]
I'm using what's on ATC currently:

ResourcefulCrops-1.12-2.1.0-61.jar
Cyclic-1.12-1.7.12.jar
forge-1.12.1-14.22.0.2464-universal

**Comment by PrinceOfAmber** [comment]
Hmm, maybe its some conflict with the newest 1.12.1 forge. Reported to crops mod, after thats resolved I should have a fix for this on the way  https://github.com/TehNut/ResourcefulCrops/issues/51

**Comment by PrinceOfAmber** [comment]
I just noticed that Resourcefulcrops updated a few weeks ago to fix the JEI crash.


With current version of cyclic this bug no longer happens, I just harvested some Inky shards after planting Inky Seeds and using the garden scythe, so its resolved.

Huzzah!

**Comment by OrdinatorStouff** [comment]
Sweet! Thank's for the follow-up~
