### ISSUE TITLE
Using Merchant Almanac intermittently causes game to crash

### ISSUE THREAD

**Issue by mahilo3550** [PrinceOfAmber/Cyclic#497]
Minecraft version & Mod Version: 1.12,; 1.7.10

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Normal use of the Merchant Almanac will randomly crash the game. Seemingly when using it rapidly.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I will look into fixing this.  Do you have a crash log?

**Comment by PrinceOfAmber** [comment]
will be in the /crash-reports/ folder

**Comment by PrinceOfAmber** [comment]
I think i fixed it. not sure exactly without crash log but version 1.8.0 will be out soon

**Comment by PrinceOfAmber** [comment]
Closing due to no response and no crash log.  As far as I know the fix i put in 1.8.0 worked https://minecraft.curseforge.com/projects/cyclic/files/2476006

**Comment by mrdeadlocked** [comment]
I had the Merchant Almanac crash my server a few times. https://pastebin.com/UPcZmgMY It looked like if I was standing too close to solid blocks when doing the trades it would crash.

**Comment by Scorch-Mechanic** [comment]
I just got a crash that looks an awful lot like the one mrdeadlocked got. 
[crash-2017-10-20_14.44.12-server.txt](https://github.com/PrinceOfAmber/Cyclic/files/1403428/crash-2017-10-20_14.44.12-server.txt)
