### ISSUE TITLE
[1.12.1] Console spamming "sendToPlayer()"

### ISSUE THREAD

**Issue by PotatoSauceVFX** [PrinceOfAmber/Cyclic#500]
Minecraft version & Mod Version: Cyclic-1.12-1.7.10

Single player or Server: Server

Describe problem (what you were doing / what happened): The console of the server gets spammed with "sendToPlayer()".

Crash log (if any): None

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Ill send out a fix tonight 👍
