### ISSUE TITLE
Tool durability?

### ISSUE THREAD

**Issue by sefldron** [PrinceOfAmber/Cyclic#504]
As a suggestion could you possibly add an option to change the durability of certain tools and items that have a durability? Specifically the Mattock. I have spent so much time trying to get my modded game to work properly on my crappy computer and after months of learning jvm flags and testing with so many mods and finally getting my game to run smoothly I was able to finally craft one and it seems so op. I have not checked if this is already an option but I would love to be able to edit some of the op type tools. Either way I love this mod and cannot imagine my game without it. I don't even play online much because I'm so used to having all the mods. Thanks

**Comment by sefldron** [comment]
To make it easier to change the tool durability possibly just add a single option that would affect all tools at once? Like 0 is normal, 1 is half and 2 is 1/3rd normal durability?

**Comment by PrinceOfAmber** [comment]
I considered a config like this a while ago, it is a really great idea.

Then I saw some livestreams where modders were simply using craft tweaker to change max damage of anything they wanted.  For example


val pick = <minecraft:diamond_pickaxe>;


//sets the max damage of the Diamond Pickaxe to 256
pick.maxDamage = 256;

So its not really necessary.

http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/IItemStack/

https://minecraft.curseforge.com/projects/crafttweaker
