### ISSUE TITLE
Mattock harvest behavior

### ISSUE THREAD

**Issue by sefldron** [PrinceOfAmber/Cyclic#505]
Odd thing happens when using the Mattock to break torches. It will break any blocks in a 3x3 area next to the torch. Not a problem but  just something to think about I guess. 
Tool could use a warning in the tooltip. One reason I suggested an option to Nerf the durability.

**Comment by PrinceOfAmber** [comment]
Yeah, thats what it does.  Whenever you mine something it breaks a 3x3 area around it.  It is built to do that.  

Not sure what you mean by "nerf the ability".  If you want to mine a 1x1 instead of 3x3 you can use a different tool?

**Comment by sefldron** [comment]
I was speaking on my suggestion from before about the durability thing. I've been awake for a while. Don't mind me. I didn't know that the blocks breaking next to a torch was on purpose.
