### ISSUE TITLE
Controlled Miner not working

### ISSUE THREAD

**Issue by Shadowbugsy** [PrinceOfAmber/Cyclic#508]
Minecraft version & Mod Version:
Minecraft version 1.12, Mod version 1.12-1.8.4 jar and tried on 1.12-1.8.3jar

Single player or Server: Single player and multi player through Lan

Describe problem (what you were doing / what happened): We set up 2 controlled miners, one at bedrock level and one is at 65. Neither one will break blocks, they attempt to but it switches to another block before the one is working on breaks. We have tried obsidian aiot, the mattoxk, diamond pickaxe, gold and stone shovels. It seems to work the best with no tool but still doesn't break the block. With a tool it only hits the block for a second then switches, with no tool it hits until right before the block breaks then stops.

We have tried it with different size areas, different heights, white listing items and nothing changes it.  We only play on single player or multiplayer lan with the 2 of us.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Looking into this now :)

**Comment by PrinceOfAmber** [comment]
So it happens the same way in single player and lan?  The way you describe it sounds like lag which is weird. I am running it in single player right now and its fine, i will try LAN mode later. 

When it 'almost' breaks the block do you get any block drops from it?

**Comment by PrinceOfAmber** [comment]
I tried it in multiplayer and had no issues.  This means it must be 

- Something about block protection (server settings, spawn chunks protected, something like that, maybe another mod protecting blocks)

- a conflict with another mod


Do you have a full mod list along with their version numbers? The easiest way so take your entire "latest.log" file from the logs folder

**Comment by Shadowbugsy** [comment]
After playing around with it yesterday we found the issue. We have the minecolonies mod and in the area we built our town it will not use the controlled miner above or below ground. It is working around at 130 blocks away from the town hall.

**Comment by PrinceOfAmber** [comment]
Aha yes that makes sense.  Many mods or blocks that use permissions, such as saying "other players cannot mine here" also affects blocks, so it was treating controlled miner as a player and blocking it.  

Thanks for reporting this anyway! It was still a good thing to do, im glad I know!
