### ISSUE TITLE
Uncrafter crash

### ISSUE THREAD

**Issue by o0Karvanaama0o** [PrinceOfAmber/Cyclic#51]
I got this crash while trying to uncraft a Minecraft Fire Charge

http://pastebin.com/jHx6EkW1

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this, ill fix it right away

**Comment by PrinceOfAmber** [comment]
1.4.0 http://minecraft.curseforge.com/projects/cyclic/files/2316057

**Comment by o0Karvanaama0o** [comment]
Thank you so very much, you Sir deserve a star!
