### ISSUE TITLE
[Suggestion] RF Integration

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#510]
Hey,
i'm back now, as i now got an 1.12.2 pack, unfortunateley without EnderIO :(

I would like to suggest an Integration for RF, as fuel for your machines. You could make that configurable, so that People that do not use electricity mods will not be bugged by this, but People that do can integrate your machines easier in their modpack. It just seems a bit curious to use coal, when you got RF at your Hands.

**Comment by PrinceOfAmber** [comment]
I will consider this.  Might not be high on my list.

In the past i made the choice not to use power https://github.com/PrinceOfAmber/Cyclic/issues/192 but im more on the fence than I was.

I made a poll for voting here:

https://twitter.com/lothrazar/status/912566714092593154

**Comment by D3nnis3n** [comment]
I still got no twitter, consider me voting for energy. :D

As for your points:
1. I find the uncrafter extremely powerful. Being able to craft anything
back into its ingredients without any loss is really op - especially in
early game and at last in my pack.
2. In the other side: in my electric based pack coal is pretty rare. You
will have enough power at your disposal, but not so much burnables.

Anyway, i ever thought about that as optional and maybe configurable - so
no hard dependency.

Am 26.09.2017 08:38 schrieb "Sam" <notifications@github.com>:

**Comment by PrinceOfAmber** [comment]
Yeah i really like that the RF power api is now a standalone mod so its really easy to work with now, not like before.  

This is low in my priority list to be honest, i want to get through some of these other bugs and stuff on this and other mods first, but i will add it.  Maybe defaulted to disabled in config.  Not sure how the visuals will work, might just reuse the same fuel bars for now even.

**Comment by D3nnis3n** [comment]
Sure, just use the same bar and show RF buffer - why not?

**Comment by PrinceOfAmber** [comment]
I finally added this. Look for it in version 1.10.0, but it wont be for a few days or maybe a week.

So far ive tested it with battery type items in the fuel slots of the machines, or just connecting it directly.  So ive used the Thermal Expansion power conduits, and the Actually additions energy lasers things to fuel them.  

Still need to test, add configs, balance, polish etc

**Comment by D3nnis3n** [comment]
Very sexy. Though, i had hoped your Sapling Autoplant Support for mod-saplings is much less work, so it would maybe come before. 😃

I’ll test the RF Integration as soon as it is in, i’m using mekanism and immersive Engineering and not ThermalExpanison, though. So i hope that’ll work, too. As as of now they all work interchangeably on my big modpack.

Gesendet von Mail für Windows 10

Von: Sam
Gesendet: Freitag, 24. November 2017 06:01
An: PrinceOfAmber/Cyclic
Cc: D3nnis3n; Author
Betreff: Re: [PrinceOfAmber/Cyclic] [Suggestion] RF Integration (#510)

I finally added this. Look for it in version 1.10.0, but it wont be for a few days or maybe a week.
So far ive tested it with battery type items in the fuel slots of the machines, or just connecting it directly. So ive used the Thermal Expansion power conduits, and the Actually additions energy lasers things to fuel them.
Still need to test, add configs, balance, polish etc

**Comment by PrinceOfAmber** [comment]
Oh right this one, I forgot. Ill knock that one out and any other smaller ones https://github.com/PrinceOfAmber/Cyclic/issues/532

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
