### ISSUE TITLE
Suggestion - disable break effects on harvesters?

### ISSUE THREAD

**Issue by resinate** [PrinceOfAmber/Cyclic#512]
is there a way to add a config option to disable break effect on plants when harvesting to reduce lag?

**Comment by PrinceOfAmber** [comment]
Yes i can make it a config to turn off break effect, so  things like particle/sound

**Comment by PrinceOfAmber** [comment]
I added this in the last version :)  https://minecraft.curseforge.com/projects/cyclic/files/2488449
