### ISSUE TITLE
High CPU time from Cyclic capabilities of items in RefinedStorage system

### ISSUE THREAD

**Issue by OrdinatorStouff** [PrinceOfAmber/Cyclic#514]
### Minecraft version & Mod Version:
1.12.2 (forge 2493)
Cyclic-1.12-1.8.6.jar

### Single player or Server:
SMP (ATM3 official)

### Describe problem (what you were doing / what happened):
Seeing very high CPU usage from cyclic Capabilities call traces. Initially it looked like RefinedStorage but as I kept drilling down, cyclic's capabilities method was at the heart of it.

### Crash log (if any):
![screenshot_1](https://user-images.githubusercontent.com/6283913/31040401-e9ed72aa-a53b-11e7-804c-58a0ccf1efaf.png)
[snapshot-1506730916397.zip](https://github.com/PrinceOfAmber/Cyclic/files/1345958/snapshot-1506730916397.zip)

**Comment by PrinceOfAmber** [comment]
The mod id for cyclic is "com.lothrazar.cyclicmagic"  .  I dont see that in this list.  

cyclopscore Is i think this library https://minecraft.curseforge.com/projects/cyclops-core

Which is used by evilcraft and other mods

**Comment by OrdinatorStouff** [comment]
...I'm an idiot 🤦‍♂️ 

Sorry for taking your time :/

**Comment by PrinceOfAmber** [comment]
Hey no worries
