### ISSUE TITLE
Harvester dups seeds from Mystical Agraddations

### ISSUE THREAD

**Issue by ouroborus** [PrinceOfAmber/Cyclic#515]
Mystical Agradditions is an addon for Mystical Aggriculture. Among other things, it adds seeds for nether stars and awakened draconium. These are special in that they require a specific block under the soil in order to grow.

When the Harvester attempts to harvest one of these plants, when the plant doesn't have the support block in place, the harvester breaks the plant, retrieves the seed, but the plant is left in place. This allows the seed to be duplicated. This happens repeatedly and as fast as the harvester harvests.

https://github.com/BlakeBr0/MysticalAgradditions/issues/7

**Comment by PrinceOfAmber** [comment]
So weird that it gets blocked from breaking it.

**Comment by PrinceOfAmber** [comment]
Testing this out now. so weird.  So when i use any non-tier 6 seed, so from the base mod such as Fire seed, everything works as normal.

When using a Tier 6 seed, in this screenshot its Nether star seed, the harvester seems to think that the plant is fully grown, even when in reality its not.  Then it breaks and replants which makes seeds, one seed every time.  It should be trying to remove one seed from the drop of the items.    Saw it on dirt, so the block below doesnt seem to matter
![sparkle](https://user-images.githubusercontent.com/621529/31108941-5e1b7b46-a7b1-11e7-8314-0f76dda8b1d9.PNG)


Code where i get the seed
https://github.com/PrinceOfAmber/Cyclic/blob/04b525a5ba3a52c86a2f4750f717730e178ecae5/src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvestCrops.java#L108

remove one seed 
https://github.com/PrinceOfAmber/Cyclic/blob/04b525a5ba3a52c86a2f4750f717730e178ecae5/src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvestCrops.java#L263

Check if fully grown: if it cannot grow any more, its done growing, at least thats the assumption the code makes
https://github.com/PrinceOfAmber/Cyclic/blob/04b525a5ba3a52c86a2f4750f717730e178ecae5/src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvestCrops.java#L222

There are some rough spots in that giant function for sure.   but i dont know why the raw mod and the addons behave so differently.

**Comment by PrinceOfAmber** [comment]
Ill see if i can check their source code on the addon to see what weirdness is being used

**Comment by ouroborus** [comment]
It seems like it has something to do with not meeting the special block requirement. That addon mod has another seed (Inferium Seeds, Tier 6) that doesn't require a special block and works as expected with the harvester. The base mod doesn't have any seeds with that kind of dependency.

**Comment by ouroborus** [comment]
I'm thinking it would be best for Mystical Agradditions to change their code such that their special block detection is done in `updateTick` rather than `canGrow`. I'm not sure what the server impact of doing that way is.

**Comment by ouroborus** [comment]
Mystical Agradditions recently applied patches for this. So it should be fixed once that mod makes the rounds.

[[1.10] Fix tier 6 crops checking for the crux badly](https://github.com/BlakeBr0/MysticalAgradditions/commit/dd8b85fe50903b434194e1d066967a85a6886433) (Also contains fixes for 1.12)

[[1.11] Fix the tier 6 crop thingies and organize imports](https://github.com/BlakeBr0/MysticalAgradditions/commit/f9b3e131257f46138c579afbcc2753f7470313c5)
