### ISSUE TITLE
Dupe Possible in Upgraded Inventory

### ISSUE THREAD

**Issue by TristanaGW** [PrinceOfAmber/Cyclic#518]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Cyclic: 1.12-1.8.6 (All The Mods 3) and 1.12.2-1.9.0 (Standalone)

Single player or Server:
Server (1.12-1.8.6)
Single Player (1.12.2-1.9.0)

Describe problem (what you were doing / what happened):
If you have no room left in your extra upgraded inventory, and you shift-click on an item on the top row of your original inventory, it moves that item to another slot on that row and doubles it until max stack size. If there are no other slots, it puts it at max stack immediately.

(I checked to see if this has already been reported, so my bad if it already has.)

**Comment by PrinceOfAmber** [comment]
Ouch never seen this before, thanks for letting me know

**Comment by TristanaGW** [comment]
Just to add on, I've realised that the doubling happens in general when shift-clicking from the top non-upgrade inventory row. It'll move to the expanded inventory with double the stack. (maxing at max-stack, of course.)

**Comment by PrinceOfAmber** [comment]
Yep im seeing this happen now with no other mods installed.  Ill try to get a fix out after work today

**Comment by PrinceOfAmber** [comment]
fixed here, let me know if it comes back or anything else breaks https://minecraft.curseforge.com/projects/cyclic/files/2487756
