### ISSUE TITLE
[Suggestion] Redstone Item

### ISSUE THREAD

**Issue by mrdeadlocked** [PrinceOfAmber/Cyclic#520]
The Password trigger is great but it would be nice to expand on it and have something that works with a switch/lever/redstone input to apply redstone to a block remotely. Random Things has 2 things as an example.

https://randomthingsminecraftmod.wikispaces.com/Redstone+Interface
https://randomthingsminecraftmod.wikispaces.com/Advanced+Redstone+Interface

**Comment by PrinceOfAmber** [comment]
So, basically the remote lever but placeable in the world....  

You bind it to a location somehow, put it in the world, and it activates the remote spot ?

https://github.com/PrinceOfAmber/Cyclic/milestone/111

**Comment by mrdeadlocked** [comment]
Yes that would be great.  That milestone is new? or did i miss it? If i missed that sorry for the duplicate item.

**Comment by D3nnis3n** [comment]
Yeah, that would be something like Malisis Remote Levers. Great Idea.

**Comment by PrinceOfAmber** [comment]
@mrdeadlocked  milestones are just my personal TODO wishlist / brainstorm idea place, i dont expect people to check through before reporting no worries

**Comment by PrinceOfAmber** [comment]
In the latest versions in 1.12 I have added wireless redstone receiver and transmitters, which basically do the same thing. very similar anyway.   It is only 1 to 1 so pretty simple, but this way they did not need a complicated GUI  screen
