### ISSUE TITLE
[Suggestion] Fluid Placer

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#521]
As you've got an Block placer, you might also want to consider adding a fluid placer like the one from actually Additions :)

**Comment by PrinceOfAmber** [comment]
Now that I have added fluid pipes and pumps, I am looking into this next

**Comment by PrinceOfAmber** [comment]
How would I improve on the AA design? Not that I have to.  Facing all 6 directions and being redstone controlled is probably enough?

**Comment by PrinceOfAmber** [comment]
added the fluid placer https://minecraft.curseforge.com/projects/cyclic/files/2508261
