### ISSUE TITLE
[Suggestion] Automated Anvil

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#522]
I would like to see a block that allows automating anvil recipes, especially repairing. Instead of Levels it would use burnables / RF. At the Moment there is no mod known to me out there that has a possibility to allow automated repairs.

There is the actuall additions item repairer, but AA does not allow turning all other objects of, uses it's own items in crafting recipes and the item repairer only consumes energy, but not e.g. iron to repair.

**Comment by PrinceOfAmber** [comment]
So it would re-use ANY valid anvil recipe, including repairing enchanted tools, applying books to things and so on? 

 Yeah sounds interesting.

**Comment by D3nnis3n** [comment]
Yes, but it could be automated. And as i see in your "Unchant" Thing you could indeed make it use EXP by using bottles of enchanting like in the Unchanter. That would be pretty great. And nearly unique.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2522113
