### ISSUE TITLE
[Suggestion] Precision Dropper

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#524]
This Suggestion is derived from AA also - it's a block that allows a dropper that spills out items in the block in front of it and not all around everywhere. Useful for conveyor belts. I'm even wondering why those conveyor mods like simple conveyor mods seem to have not have such a block oO

**Comment by PrinceOfAmber** [comment]
Yeah the vanilla dropper sends stuff out really far and really randomly.

**Comment by PrinceOfAmber** [comment]
This was added in a recent version.  Called the 'Precise Dropper' , crafted with gold
