### ISSUE TITLE
[Suggestion] Magnet

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#525]
You might already have such an item and i didn't find it, but i'd like to see an EnderIO magnet for pulling items towards you.

**Comment by PrinceOfAmber** [comment]
I do have the Magnet enchantment and potion as well.  Do you think people would find uses for an item too? 

Are there any options or configs we could give an item to make it stand out a bit more?

Also related to https://github.com/PrinceOfAmber/Cyclic/issues/493

**Comment by D3nnis3n** [comment]
Dann. Yes, the config options in that issue is exactly what i would want to see. We also use TiC heavily.

**Comment by PrinceOfAmber** [comment]
Sorry, i decided not to add this item.  The potion and enchant are in alraeady, tons of other mods have one... and  I have tons and tons of other stuff i want to do, see the projects tab for more details.

**Comment by D3nnis3n** [comment]
You already added over 9000 sich useful and needed blocks and so many
proposed by me that you definateley don't need to be sorry. Eternal Thanks
for your Work.

Am 22.02.2018 09:06 schrieb "Sam" <notifications@github.com>:
