### ISSUE TITLE
[Suggestion] Filler Wand

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#526]
Maybe i've just overseen something again, but i only found a replacer wand.

I'd like a filling wand. Because what is most tedious and can be done by nearly no mod? Yeh, filling bigger Areas. So, a configurable filler, where you could set the block, and how big an area you want to fill and maybe in which shapes (1x8, 5x5, etc. pp) would be absoluteley cool and something "new". There sureley is any mod out there that can do this (without worledit), but i don't know any. So i would really like this wand the most of all my proposed Features.

**Comment by PrinceOfAmber** [comment]
I have the 'Structure Builder' which can fill in areas in different shapes and sizes.  But yeah its not in tool/wand form.  

This reminds me a little of the builders wand mod https://minecraft.curseforge.com/projects/better-builders-wands

But the differences are that one only matches existing placed blocks.   So if i had something that just would try to build a 3x3 where you click regardless of matching blocks, that would be new and interesting.

**Comment by PrinceOfAmber** [comment]
Also related https://github.com/PrinceOfAmber/Cyclic/issues/322

**Comment by D3nnis3n** [comment]
Uh, didn't know that mod, yet. Maybe this could be an alternative.
It's main usage for us would be to fill up holes with dirt or Stone. As we got shovels that can remove 3x3 we ever had the lack of a tool that was able to place that again ...

**Comment by PrinceOfAmber** [comment]
Yeah i am still planning some more tools.

So far im thinking one that builds on whats already placed and matches to the same block

one that just fills in empty space with whatever blocks are in your inventory

-> for filling holes, would it know where your feet are and stop filling up just below you? what if you use it against a wall, maybe it could layer over top of that like wallpaper. like putting a layer of wood planks on top of a cave you dug out?

i had another idea for an item that has specific shapes set and it tries to place that down. similar to this https://mods.curse.com/mc-mods/minecraft/264874-architect

**Comment by PrinceOfAmber** [comment]
I guess im never gonna get to this. Heres some other building stuff 
 
https://minecraft.curseforge.com/projects/better-builders-wands
https://minecraft.curseforge.com/projects/building-gadgets
https://minecraft.curseforge.com/projects/similsax-transtructors
https://minecraft.curseforge.com/projects/linear
