### ISSUE TITLE
[Suggestion] Enchant for Treefelling

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#528]
How bout' a Enchantment that allows you to fell complete trees at once?

**Comment by PrinceOfAmber** [comment]
So it would act like like vein miner, but less overpowered since its only for axes and logs.  https://minecraft.curseforge.com/projects/veinminer

**Comment by D3nnis3n** [comment]
Yes. We do that with a Tinker Tool, as it seems realistic. But People without tinker tools should be able to do that also. Mining entire veins of ore would be too much and unrealistic for us, at least.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2522113
