### ISSUE TITLE
[1.10.2] Crash when using Scepter

### ISSUE THREAD

**Issue by t3f** [PrinceOfAmber/Cyclic#53]
Crash in 1.10.2 when using Scepter 

Server Console:
https://gist.github.com/t3f/4a8b00aaf6440f8ef8e792f7e1a3370f

**Comment by PrinceOfAmber** [comment]
Ok, ill get on it today or tomorrow!

**Comment by PrinceOfAmber** [comment]
Should be fixed in version 1.4.1, if it happens again let me know !

https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.4.1
