### ISSUE TITLE
[Suggestion] Faster Leaf Decay

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#531]
I'd like to have an Option that allows the leaves do decay near instant. You got a lot of utiliy config Options and this one seems to fit. It would just let all the leaves drop in like 5 seconds, when no Wood blocks are adjacent anymore. This will prevent Floating Wood-bushes.

**Comment by PrinceOfAmber** [comment]
This is a great idea, but i would have no idea how to make this work..... and anyway there is a great mod that I use all the time to do exactly this.  https://mods.curse.com/mc-mods/minecraft/225839-quick-leaf-decay

**Comment by D3nnis3n** [comment]
Yeah, i use that mod, but as you are indeed adding other Features that small mods do add, as "AutoPlant" and "SignEdit" i had hoped to be able to remove the last of my Little "fix" mods. But if you wouldn't be able to add this in a reasonable time anyway, that's fully fine.
