### ISSUE TITLE
[Bug / Compatibility] AutoPlant for Mod Saplings

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#532]
Could you add the possibility to autoplant mod saplings. Your mod does not plant e.g. Forestry or Pam's Harvestcraft saplings. AutoPlant does this Job. As you are already having that Option i'd like to not download an extra mod for this Task. AutoPlant seems to be able to make this pretty easy, as forestry and Pams both extend the Sapling Class (whatever this is).

**Comment by PrinceOfAmber** [comment]
I couldnt think of a good way to do this before, but actually it should be easy by matching to the Ore Dictionary

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
