### ISSUE TITLE
Guidebook quality-of-life improvements

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#534]
Two suggestions for the guidebook to make it a bit more convenient to use:
1. When returning to the list of blocks/items/whatever after reading an individual entry, you should end up back on the page you were on instead of on page 1 all the time.
2. When hovering over a block/item/whatever in the list, you should get a preview of its entry's text.

**Comment by PrinceOfAmber** [comment]
1 => There is a back button in the top left, it should take you just up one page. Like if i go blocks -> sprinkler -> read the stuff, then go back one.

2. That would be a great feature.  However this guide book is actually made by a different API mod, similar to forge or JEI.  In Cyclic i basically compile a list of categories and items and text, and give it to the book and the book shows up.  So for a feature like this it would have to be added by that mod:  https://minecraft.curseforge.com/projects/guide-api

There is a search feature if you press back enough times

I have control over categories and content.  I can add recipes, text, and custom images.  

3> off topic but going over the book while checking this out, i do notice some little things.  
3a: blocks do not have recipes, but items do.
3b: some categories are too big, others do not really make sense, more categories might be better
3c maybe alphebetize the order ?

**Comment by josephcsible** [comment]
1. The back button doesn't seem to work like that for me. For example, if I go to Fire Slayer from page 3 of Items, when I hit Back, I end up on page 1 of Items.
2. Okay, I'll open an issue with Guide-API for that.
3a. Meh, JEI is a must-have anyway.
3b. Agreed.
3c. Agreed.

**Comment by PrinceOfAmber** [comment]
Looks like i forgot to close this so i will now.  For anyone reading in the future go here https://github.com/TeamAmeriFrance/Guide-API/issues
