### ISSUE TITLE
Hydrator Dupe

### ISSUE THREAD

**Issue by Guybrush0** [PrinceOfAmber/Cyclic#536]
Same as https://github.com/PrinceOfAmber/Cyclic/issues/518

shift clicking into hydrator dupes items, anywhere in inventory except hotbar

version: 1.9.1

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this!

**Comment by PrinceOfAmber** [comment]
Fix is out https://minecraft.curseforge.com/projects/cyclic/files/2489909
