### ISSUE TITLE
HEY FUCKHEAD - ADD INPUT TO DISABLE TIMER

### ISSUE THREAD

**Issue by Fuckcyclicdev** [PrinceOfAmber/Cyclic#538]
hEY DUMBASS, HERES A FUCKIN SUGGESTION.

IN YOUR FUCKING STUPID TIMER BLOCK ADD AN INPUT TO DISABLE THE CLOCK 
THANKS 
HAVE A GREAT FUCKING DAY YOU MONGOL

**Comment by PrinceOfAmber** [comment]
Grow up.
