### ISSUE TITLE
Pharos Beacon Abuse Issue

### ISSUE THREAD

**Issue by Guybrush0** [PrinceOfAmber/Cyclic#539]
In it's current state, on a server, a player can place a pharos beacon "nearby" someone's base and have a supply of instant damage potions in it, they can then use the password block to remotely trigger it to kill that person, this is going to cause issues in servers and such.

My suggestion, similar to the environmental controller from rftools, add a config option to disallow negative potion effects on players for the pharos beacon

**Comment by PrinceOfAmber** [comment]
Good idea, adding a blacklist

**Comment by PrinceOfAmber** [comment]
Config will be like this as default, can hold as many as you need

    S:PharosBeaconBlacklist <
        minecraft:instant_health
        minecraft:instant_damage
        minecraft:wither
        minecraft:poison
     >

**Comment by PrinceOfAmber** [comment]
Added https://minecraft.curseforge.com/projects/cyclic/files/2490559
