### ISSUE TITLE
Huge Dupe bug (Stackables)

### ISSUE THREAD

**Issue by NightbringerMc** [PrinceOfAmber/Cyclic#542]
Minecraft version & Mod Version:
1.12.1, cyclic 1.8.6

Single player or Server:
Server (Minecraft Mod Developement public server)

Describe problem (what you were doing / what happened):
Shift clicking an item into a full cyclic inventory (The inventory upgrade) dupes any item that is stackable if there is space in the vanilla inventory.
![2017-10-14_19 32 07](https://user-images.githubusercontent.com/11724469/31577867-72a9f452-b116-11e7-910b-e31575cc1eed.png)
![2017-10-14_19 32 09](https://user-images.githubusercontent.com/11724469/31577868-795507ce-b116-11e7-84d2-a01ce11a3967.png)
![2017-10-14_19 32 12](https://user-images.githubusercontent.com/11724469/31577871-7b72b452-b116-11e7-991c-393140c215f7.png)
![2017-10-14_19 32 13](https://user-images.githubusercontent.com/11724469/31577872-7cf0af3c-b116-11e7-8492-060cc589b6d2.png)
![2017-10-14_19 32 15](https://user-images.githubusercontent.com/11724469/31577873-7ec2ec4e-b116-11e7-8636-de557a86882d.png)
![2017-10-14_19 32 16](https://user-images.githubusercontent.com/11724469/31577874-80536624-b116-11e7-8134-0ebb1578884b.png)

Crash log (if any):
None

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by NightbringerMc** [comment]
(Btw, the 4 first slots seem a little bugged)

**Comment by PrinceOfAmber** [comment]
Thanks for the screenshots, thats really helpful. 

This was fixed in  a previous update though, see https://github.com/PrinceOfAmber/Cyclic/issues/518 for more information and download the latest version.


I notice you are still in 1.12.1, you should upgrade to 1.12.2 when you have a chance.  Fixes vanilla bugs and literally every 1.12.1 mod ive tried works just fine in 1.12.2

**Comment by PrinceOfAmber** [comment]
I tested again with the newest version of everything, using one of the ATM packs, seems still fixed.

Thanks for reporting anyway! better a duplicate report than no reports at all. I wish all reports had screenshots as good as these ❤️
