### ISSUE TITLE
Access UIs in Claimed Chunks

### ISSUE THREAD

**Issue by Dystinct** [PrinceOfAmber/Cyclic#547]
**Minecraft version & Mod Version:**
1.12.2-1.9.1

**Single player or Server:**
Server

**Describe problem (what you were doing / what happened):**
Players are allowed to access the UI of all Cyclic blocks that have a UI through the protection of claimed chunks provided by FTBUtilities. I have checked every other block that has a UI inside of the 2nd partie's (to which I have no access to) base and could not open any other UI Vanilla or modded other than that of Cyclic.

**Crash log (if any):**
N/A

**Comment by PrinceOfAmber** [comment]
Added in latest https://minecraft.curseforge.com/projects/cyclic/files/2494016
