### ISSUE TITLE
Autocrafter eats replaced items in some recipes

### ISSUE THREAD

**Issue by dazsim** [PrinceOfAmber/Cyclic#548]
Minecraft version & Mod Version:
1.12.1

Single player or Server:

both
Describe problem (what you were doing / what happened):
tried to turn iron bucket of water into wooden bucket from harvestcraft. worked but didnt get empty iron bucket back (interaction with harvestcraft)

Crash log (if any):
n/a

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Fixed in latest https://minecraft.curseforge.com/projects/cyclic/files/2493417

**Comment by Skar78** [comment]
Minecraft version & Mod Version:
1.12.2

Single player or Server: 
server (atm 3.5.6)

Describe problem (what you were doing / what happened):
Mystical Aggriculture (Magic Crops like) infusion crystal was "eaten" when doing a inferium to prudentium recipe.

Crash log (if any):
n/a
