### ISSUE TITLE
Empty Sack of Holding

### ISSUE THREAD

**Issue by Ezelberoth** [PrinceOfAmber/Cyclic#55]
So I created an empty sack of holding, not really understanding what its supposed to do. I shift-right-clicked on my chests (unfortunately all of them). They disappeared, but now I can't find out how to get them back. Right clicking says it only works on Inventories. I couldn't find anything in config or options or keybinds to find out how to get my chests back. Also, not sure if this is also your mod, but there is a small button which looks like a chest with a green arrow pointing into it, is this your mod? If so, where do those items go?

**Comment by PrinceOfAmber** [comment]
It is supposed to turn your chest into a full sack of holding.  Then you use that full sack of holding to place down the chest again.

Basically it is used to transport chests, and it keeps all the items inside.

Can you check around if maybe it dropped somewhere?

Regardless i will do some tests and see if they are bugged out.

**Comment by Ezelberoth** [comment]
I keep getting the empty sack again. I used it on several chests, and it
stays an Empty Sack of Holding. I guess I just lost all my stuff from all
my chests. LOL. Back to mining I guess...

**Comment by PrinceOfAmber** [comment]
Im going to look into this again tonight I really want to fix this if i can

**Comment by Ezelberoth** [comment]
Thanks! Let me know if you find anything! :D

Evie

**Comment by PrinceOfAmber** [comment]
Fix coming out in 1.4.3 release

**Comment by Ezelberoth** [comment]
Thanks!

**Comment by PapiDimmi** [comment]
That’s why you gotta back up your world.
