### ISSUE TITLE
Automatic Fisher doesn't support modded rods properly

### ISSUE THREAD

**Issue by Guybrush0** [PrinceOfAmber/Cyclic#550]
Version: 1.9.5

Using a modded fishing rod such as the flux infused fishing rod from redstone arsenal will cause the rod to be deleted after one use, i'm assuming it's you check for durability and it doesn't use that so it's "one use".

**Comment by PrinceOfAmber** [comment]
Just realized this was reported before... In 1.10 i had put in a quickfix to at least stop it from deleting item, but it still didn't drain RF.  https://github.com/PrinceOfAmber/Cyclic/issues/388

Ill look into doing it the right way instead, meaning

- check if the fishing rod item uses durability or RF and drain the right thing

which means pulling in the RedstoneFluxAPI, which i was bound to do eventually anyway

https://mods.curse.com/mc-mods/minecraft/270789-redstone-flux

**Comment by PrinceOfAmber** [comment]
Do you happen to know the item ids of the fishing rods that use energy instead of durability? 

Is it ONLY from this mod or are there others?

https://minecraft.curseforge.com/projects/redstone-arsenal

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2501283
