### ISSUE TITLE
Hydrator does not accept items from AE 2 export bus/interface

### ISSUE THREAD

**Issue by ffgda** [PrinceOfAmber/Cyclic#551]
Minecraft version & Mod Version:
1.12.2, 1.8.6

Single player or Server:
Server (All the mods 3)

Describe problem (what you were doing / what happened):
Tried to automate the production of black concrete with AE 2. First put an ME interface on every side of the hydrator except bottom (water source) and added a processing recipe 1 black concrete powder -> 1 black concrete. Didn't take items. Then put an export bus on all sides except bottom and set it to export black concrete powder. Didn't take items. Then tried chest + Thermal Dynamics itemducts -> worked.

I guess I can work around by connecting an interface to an itemduct but it would be nice if you could export items to the hydrator directly.

Edit: The import bus doesn't pull items out either.

Edit 2: make that it doesn't output items at all, n'either with an itemduct nor with a chest directly placed next to the hydrator.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
This is a weird one.  Normally if i get something working with pipes and hoppers it works with everything.  

For the Hydrator im running it now and hoppers alone are working. But just like you said, item ducts work too.

If you have time, can you test some other Cyclic machine blocks and see if they work?  I havent used AE2 in a long time; im just wondering if its ONLY Hydrator + AE2 that has issues, or if its all Cyclic blocks + AE2

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2508261
