### ISSUE TITLE
[Minor] JEI says MonsterBall breaks after releasing mob, it does not.

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#552]
MC 1.12.2 and Cyclic 1.9.6

Both single player and server

Monster balls do not get destroyed upon release the mob (tried with both pigs, endermen, and abyssalcraft mobs, contrary to what is said on the description in JEI. Just wanted to give a heads up if you wanted to correct the JEI entry or add in a way so that the MonsterBall deletes itself.

**Comment by PrinceOfAmber** [comment]
Yeah i changed it to make it reuseable but forgot to update docs. Thanks for noticing

**Comment by PrinceOfAmber** [comment]
Fixed in latest https://minecraft.curseforge.com/projects/cyclic/files/2494016
