### ISSUE TITLE
[Suggestion] Sneak to walk normally on Slime Conveyors

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#553]
Would it be possible if slime conveyors would not affect the player if they were sneaking?

**Comment by PrinceOfAmber** [comment]
Yeah great idea! this is an easy thing to add

**Comment by PrinceOfAmber** [comment]
Added in latest. can be turned off in config for those that didnt like it https://minecraft.curseforge.com/projects/cyclic/files/2494016
