### ISSUE TITLE
Player kicked when using a torch placer.

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Cyclic#556]
Minecraft version & Mod Version:
Cyclic-1.12.2-1.9.6

Single player or Server:
Server

Describe problem (what you were doing / what happened):
User places a torch with a torch placer, and gets kick and stacktrace produced in console.

Crash log (if any):
https://gist.github.com/ProsperCraft/4f33482a398c1910b10ab6617b5e15dc

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Looks like its crashing after placing the block and trying to mark chunk as dirty for other clients to see it.  
` world.markChunkDirty(placePos, null); `
Fix coming soon.

**Comment by PrinceOfAmber** [comment]
Let me know if its better/worse/same with this version please https://minecraft.curseforge.com/projects/cyclic/files/2495936

**Comment by xILukasIx** [comment]
Hi,
I've had the same problem on my server, using the version you supplied above (1.9.8) players no longer get kicked. Thanks!

FYI:
A new message appears very frequently (every few seconds) on console now:
`[03:51:37] [Server thread/ERROR] [cyclicmagic]: Error attempting to place block
[03:51:37] [Server thread/ERROR] [cyclicmagic]: null
[03:51:37] [Server thread/ERROR] [cyclicmagic]: [Ljava.lang.StackTraceElement;@3fc4b722`

**Comment by PrinceOfAmber** [comment]
Thanks for the log. Yeah that was the part that used to crash. I might remove this log later
