### ISSUE TITLE
Dupe bug within a mod pack

### ISSUE THREAD

**Issue by Ragetiger** [PrinceOfAmber/Cyclic#557]
Minecraft version & Mod Version:
Better Not Panic 1.0.2 Minecraft 1.12.1 forge 14.22.1.2485

Single player or Server:
single player

Describe problem (what you were doing / what happened):
hydrator was doubling up items when I shift clicked them from inventory into the hydrator. Was not sure if it's only with the terracota blocks I was trying to turn back into clay.

**Comment by PrinceOfAmber** [comment]
Yep, i fixed this just recently.  Im surprised at this actually, usually darkphan is up on the latest verison.

It was fixed in  Cyclic-1.12.2-1.9.3.jar so that or later will be good

Its in 1.12.2, see info here https://github.com/PrinceOfAmber/Cyclic/issues/536
