### ISSUE TITLE
Harvester AOE not consistent with preview

### ISSUE THREAD

**Issue by ouroborus** [PrinceOfAmber/Cyclic#561]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.9.7

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The Harvester's area of effect, when configured for "Area", doesn't match the preview area. In the screenshot, below, you can see the row at the right  of the field is not being harvested. (The row on the left is harvested. I haven't tested if this a misshapen AOE or an offset AOE.)

![2017-10-31_19 26 28](https://user-images.githubusercontent.com/392047/32257291-715371c4-be71-11e7-8ff8-426bdebf5d84.png)

**Comment by PrinceOfAmber** [comment]
Yeah it should harvest everything included.

**Comment by PrinceOfAmber** [comment]
Fixed in 1.9.9 let me know if anything else comes up https://minecraft.curseforge.com/projects/cyclic/files/2497630
