### ISSUE TITLE
Experience Pylon and Server TPS

### ISSUE THREAD

**Issue by xElementzx** [PrinceOfAmber/Cyclic#564]
Minecraft version & Mod Version: MC1.12 - Mod1.9.6

Single player or Server:
SpongeForge Server Version 1.12.2-2503-7.0.0-BETA2706

Describe problem (what you were doing / what happened):

Experience Pylon drops TPS when placed, Issue is fairly consistent.

I Placed the XP Pylon in the server, nothing interesting happened TPS was a solid 20, then i placed some XP in it and it dropped the TPS to 10TPS, Seems to be the Collecting XP function as TPS comes back up when i turn it off.

**Comment by PrinceOfAmber** [comment]
Yeah ive never really measured something like this before.  Looking at the code though, the pylon is firing off its action every tick, so I will reduce this a bunch, maybe every 10,15,20 ticks, something like that. should help

Ill measure with https://minecraft.curseforge.com/projects/debugserverinfo

**Comment by PrinceOfAmber** [comment]
Updated in 1.9.9 . if this doesnt help much let me know i can look into it more  https://minecraft.curseforge.com/projects/cyclic/files/2497630

**Comment by PrinceOfAmber** [comment]
more improvements in latest version https://minecraft.curseforge.com/projects/cyclic/files/2501283
