### ISSUE TITLE
Underwater Scaffolding [ glowing version ] 

### ISSUE THREAD

**Issue by scottosx** [PrinceOfAmber/Cyclic#565]
Minecraft version & Mod Version:
1.10.2
Cyclic 1.10.30

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
When placing scaffolding underwater using shift for ranged building only a single scaffold block is placed beyond the original. This occurs with all types of scaffolding.

It happens both fully submerged and on the surface of water.

Hope this can be fixed as it is a great block for building underwater.

Crash log (if any):
N/A

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yeah great idea. ill add this to 1.12 first and 1.10 later. probably today.

**Comment by scottosx** [comment]
No hurry and thanks for your attention (and one of the best overall set of nifty additions to MC). 

If you are ever wanted to expand on these blocks then a light emitting version would really round out the set. Probably just add some glowstone dust with a scaffold. Not sure if fragile makes sense but maybe.

That way you could push lights into dark spaces like caves, across big building structures or underwater.

Just a suggestion and if accepted, no hurry.

**Comment by PrinceOfAmber** [comment]
FYI I consider the versions in minecraft 1.10 and 1.11 as feature complete, so no updates there unless its a gamebreaking bug of some kind.  

New features are constantly being added to 1.12.2 however, so I will look into it there.

**Comment by scottosx** [comment]
Understood. But you will be adding the underwater ability to scaffolding in 1.10.2? A few mods necessary for my pack there have not updated.

**Comment by PrinceOfAmber** [comment]
I decided not to add light sources, sorry.  I have tons and tons of other stuff i want to do, see the projects tab for more details
