### ISSUE TITLE
[Suggestion]Way to get back experience out of the experience pylon directly to player experience inventory

### ISSUE THREAD

**Issue by mcdodge34** [PrinceOfAmber/Cyclic#568]
This is just a suggestion here but it would be nice to be able to get back the experience we store in the experience pylon back to the player and not only with the bottles cause this isn't as accurate and practical solution, I was an addict of the experience rod from EnderIO that would allow me to store my XP in any kind of fluid tank and be able to get the levels I needed when I wanted them, would love to see this kind of functionality back, and by the look at the GUI, it must probably be easy to do on your side. I'm not sure yet if we can draw liquids in and out of the pylon (its my next project and one of the first thing I will test) but if its not supported yet, it could be an interesting feature as well.

**Comment by PrinceOfAmber** [comment]
Yeah ive been thinking about this for a while.  You can deposit all but you might not want to.

A system where i could "deposit X levels" or "withdraw X levels" directly with one click, where X is like 10 or 20.  

I havent used the Ender IO thing in a while but ill make it better.

You can pull liquid out in a bucket as liquid XP, havent tried with pumps or pipes, it should work fine just like a tank

**Comment by PrinceOfAmber** [comment]
@mcdodge34 would anyone care if i removed the "spray" feature ? That gives more room for buttons, and i think is not needed after upgrading this

**Comment by PrinceOfAmber** [comment]
added in this version https://minecraft.curseforge.com/projects/cyclic/files/2498679

**Comment by mcdodge34** [comment]
The spray gives way too much XP in 1 shot, so a better option would be to remove it. Thanks for the quick build, will see it this evening, have to work today first.

**Comment by PapiDimmi** [comment]
@PrinceOfAmber I haven’t tried the new versions of Cyclic, so I don’t know if you did this already, but it would be great if you could see exactly how many XP **levels** are in the experience pylon, rather than just the amount of XP.
