### ISSUE TITLE
Question: The new "get item" feature renders all harvesters unuseable 

### ISSUE THREAD

**Issue by JasonKillsUs** [PrinceOfAmber/Cyclic#569]
Which harvester is able to harvest the Magic Beans + Junk and Treasures?
Since the "get items" feature got introduced i´m no able to use the "Actual Addition" Harvester anymore.

**Comment by PrinceOfAmber** [comment]
thanks for being patient, this looks like a small fix ill get it out soon

**Comment by PrinceOfAmber** [comment]
@JasonKillsUs  what other modded crops is it failling with? I have a fix im releasing soon, but which mods and crops had problems? Was it only the magic bean?

**Comment by PrinceOfAmber** [comment]
harvester+magic bean fixed in this version https://minecraft.curseforge.com/projects/cyclic/files/2498679


 if theres other modded crops that dont work, let me know and ill check it out
