### ISSUE TITLE
Block Placer duplication bug

### ISSUE THREAD

**Issue by ResqDiver1317** [PrinceOfAmber/Cyclic#570]
Minecraft version & Mod Version:
MC 1.12.2, FTB Horizons III version 1.0.0, Cyclic Version 1.12.2-1.9.6

Single player or Server:
FTB Horizons III server running SpongeForge 1.12.2-2503-7.0.0-BETA-2716

Describe problem (what you were doing / what happened):
Had a player setup a block placer and they reported it was not consuming items when placing. They tried with a few diff blocks and all the same result.

Crash log (if any):
Not Applicable

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Ill check this out.  

Do you  see anything weird in the log files when this was happening? This usually helps a lot if possible.

Also were there any claimed chunks in the area? Sometimes its related to FTB Utilities or sponge or related things.

**Comment by PrinceOfAmber** [comment]
COuld it possibly be client/server desync with inventory? 

So on your server you put in stack of 64, it places 1 and you still see 64. 

If you leave it off does it eventually update to 63 I am wondering?  

....i dont see the issue on my server, so just looking for a theory.

**Comment by Keaton1188** [comment]
Hey, seems this is to do with sponge.

We are also having this issue on our Sponge server, I just tested in Single Player and didn't have an issue.

**Comment by PrinceOfAmber** [comment]
Fix is here thanks for the pull request . let me know if anything else comes up

https://minecraft.curseforge.com/projects/cyclic/files/2499867
