### ISSUE TITLE
LootTables - disabling EnderWing / EnderWing Prime

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#571]
Minecraft version & Mod Version:
1.12.2 - 1.9.9

How does Cyclic interact with the vanilla minecraft's loot tables? I'm trying to use LootTweaker atm, but it can't seem to find your loot table json. I want to prevent the occurrence of some of your tools in dungeon/stronghold/mineshaft chests without disabling them outright. Is there a JSON that you inject into the vanilla minecraft's chest loot table that's accessible by CraftTweaker or some other addon?

**Comment by PrinceOfAmber** [comment]
The mod adds directly to the loot tables via code; and I do not know if this is written to the loot table files or not (if it is, mods might overwrite).

There is a "ChestLoot" config in "world generation" config, but this disables ALL cyclic items from ALL chests.

So you could do that, but its not perfect.

What I want to look into doing (eventually, one day) is has a full list of all the cyclic items in loot tables, so you can have this kind of direct control. [well, either that or make it work with loottweaker somehow, whatever is easier.]

**Comment by Vyraal1** [comment]
Ok thanks! If anyone else is reading this my current workaround is mostly like adding Doomlike Dungeons or Roguelike Dungeons then, disabling all Cyclic lootgen in chests via the config. Then I can use the configs from DLD/RLD to add the Cyclic items manually.

**Comment by PrinceOfAmber** [comment]
Looked into this a bit.  Anything i could roll up would not be as good as the actual tweaker scripts so for now ill just leave my "one config to turn loot table hook on and off". Most people use this already anyway  https://github.com/Darkhax-Minecraft/LootTableTweaker/wiki/Methods
