### ISSUE TITLE
Harvester Log Spam

### ISSUE THREAD

**Issue by MokahTGS** [PrinceOfAmber/Cyclic#575]
Minecraft version & Mod Version:
1.12.2 & Cyclic 12.2.2.1.9.10

Single player or Server:
Single Player LAN

Describe problem (what you were doing / what happened):
Getting a spam in the logs when the harvester does anything which contributes to lag.

https://www.dropbox.com/s/sg7jzl345s60e1x/cyclicspam.jpg?dl=0

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
This should be blocked by the config file. in cyclicmagic.cfg  it has this

`    logging {
        # Log debug related information.  This can be very spammy, only used for debugging problems or new features, so just leave it off normally. [default: false]
        B:Debug=false

        # Log basic game startup information such as ore dictionary registration [default: true]
        B:Information=false

        # Run unit tests on startup and log the result.  Still experimental and not widely used [default: false]
        B:UnitTests=false
    }`


If these are true, then turning them false should stop the logs

If those are false for you, and you are still seeing this, its a bug i need to fix.

**Comment by PrinceOfAmber** [comment]
I see, i think part of it is that i set the default value of some of these logger flags to true, they should always start out as false so i can fix that in next release, also setting to false should fix this for you

**Comment by MokahTGS** [comment]
https://pastebin.com/44BXRmQi

From my config...if I change it to false it should stop?

**Comment by PrinceOfAmber** [comment]
false should stop the logs yes.

Also i straight up deleted most of these logs anyway : Fixed version https://minecraft.curseforge.com/projects/cyclic/files/2499688
