### ISSUE TITLE
Question: harvester connecting to pipes

### ISSUE THREAD

**Issue by vertex101** [PrinceOfAmber/Cyclic#580]
i am using the latest version of the mod and i have been trying to pull the items out of the harvester but cant find anything that will do it i am playing Horizons 3 modpack on a server

**Comment by PapiDimmi** [comment]
Hopper, item conduits/cables, etc.?

**Comment by vertex101** [comment]
i have tried using the item ducts from thermal but they dont pull the items out of the harvester

**Comment by PrinceOfAmber** [comment]
@vertex101  have you tried connecting to the bottom? They might not come out on the side, and if not i can update that.  


I know a hopper does pull from below.

**Comment by PrinceOfAmber** [comment]
Made change to allow side connections

**Comment by vertex101** [comment]
i tried all sides with the item conduit n servo

**Comment by PrinceOfAmber** [comment]
all sides even the bottom?

In old version it only connected on bottom, in this new version it should extract items on the sides.    https://minecraft.curseforge.com/projects/cyclic/files/2501283 

If this new version doesnt work let me know

**Comment by vertex101** [comment]
yeah it was old sides but i will download that new version and do a test to see if it works with the itemducts and will let you know

**Comment by Ash70** [comment]
I'm using 1.9.13 and have a hopper below a harvester, but nothing drops in.

**Comment by PrinceOfAmber** [comment]
Ok ill fix it, thanks for the feedback

**Comment by Ash70** [comment]
My issue with this was related to #596 so disregard my reply in this issue.

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
