### ISSUE TITLE
Experience pylon - localization issue 

### ISSUE THREAD

**Issue by PapiDimmi** [PrinceOfAmber/Cyclic#581]
![cyclic - localization issue](https://user-images.githubusercontent.com/25916106/32814231-61bf2b3e-c9ae-11e7-9958-4845430a6829.png)

**Minecraft version**: 1.12.2
**Cyclic version**: 1.9.9

**Comment by PrinceOfAmber** [comment]
LOL good catch, i missed this one

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2501283
