### ISSUE TITLE
Experience pylon - Not all of the player’s XP is deposited

### ISSUE THREAD

**Issue by PapiDimmi** [PrinceOfAmber/Cyclic#583]
Whenever I deposit my experience, there’s a full green XP bar left which I cannot deposit.
****
**Minecraft version**: 1.12.2
**Cyclic version**: 1.9.12

**Comment by PrinceOfAmber** [comment]
Yeah i am seeing that too.  Sometimes when i do the deposit all i still have <1 level left but still some green in the exp bar. 

But in contrast, if i /xp 50 and then deposit 50, i go to exactly zero, so inconsistent

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2501283

**Comment by PapiDimmi** [comment]
@PrinceOfAmber Thanks for the fix!
