### ISSUE TITLE
[Suggestion: Tweak] Redstone Clock Offswitch

### ISSUE THREAD

**Issue by FryoKnight** [PrinceOfAmber/Cyclic#584]
So, I was playing around with the Redstone Timer/Clock, and I was wanting to suggest that you add a way to disable the clock. There are some cases where you don't want the clock running constantly, and at the moment, the only real way of disabling it is by breaking it.

I recommend that if it is receiving a redstone signal (but not currently emitting one), that it "pauses" the current tick or simply disables the block.

**Comment by PrinceOfAmber** [comment]
Currently you can set the Power setting to zero to disable it, this was added pretty recently.

"I recommend that if it is receiving a redstone signal (but not currently emitting one), that it "pauses" the current tick or simply disables the block." I thought about this before. I wasnt sure if i can tell the difference between giving and sending signal, but i can revisit this, it probably can be done.  

What would make the most sense is adding one of those "redstone torch / dust" toggle buttons that many other machines have, so it goes between "always on" to "only on if getting a signal.

**Comment by PrinceOfAmber** [comment]
Added toggle button.  So in the redstone dust state, you need a lever on top (or some other signal) to enable it

![redstone clock example](https://user-images.githubusercontent.com/621529/32983826-fa3f9be8-cc4f-11e7-848b-54e80639b170.PNG)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2501283
