### ISSUE TITLE
Chunk Loader?

### ISSUE THREAD

**Issue by FryoKnight** [PrinceOfAmber/Cyclic#585]
So yes, I do know there isother miss out there that add their own Chunk Loaders, but alot of them are either really late-game, or over powered and available early-game.

That, and the fact that the Horizon III modpack doesn't have any sort of chunkloading and I don't want to inject Mods into the pack.

I was wanting to ask for a Chunk Loader. Something mid-game, but posdible only load a single chunk at a time?
Possible only working when the owner is online in servers? Or only on for a short time after they log off?

As for the recipe, I thinking the following:
[Blank] [Experience Pylon] [Blank]
[Diamond] [Blank?] [Diamond]
[Eye Of Ender][Furnace][Eye Of Ender]

And it would require dual to keep chunks loaded. Either normal fuel but doesn't provide alot of time, or Bottles o' Enchanting/liquid Experience for long run times.

Let me know what y'all think. :3

**Comment by PrinceOfAmber** [comment]
I dont know how chunk loaders work but i can look into it... probably wont be any time soon.


This is the chunk loader I always use  https://minecraft.curseforge.com/projects/the-weirding-gadget

I used to use this one too https://minecraft.curseforge.com/projects/persistent-bits

**Comment by PapiDimmi** [comment]
Just use [FTBU](https://minecraft.curseforge.com/projects/ftb-utilities).

**Comment by FryoKnight** [comment]
@PapiDimmi
I can not. Our server has chunk claiming disabled in favor of the Nations plugin.

**Comment by PrinceOfAmber** [comment]
I will look into adding one in the future, I just have other stuff on my list I want to do first.

**Comment by PapiDimmi** [comment]
Like @PrinceOfAmber said, there are plenty of mods that add a chunk loader. In my opinion, there’s no reason for him to add a chunk loader to the mod if there are too many mods that already do that.

**Comment by PapiDimmi** [comment]
Like @PrinceOfAmber said, there are plenty of mods that add a chunk loader. In my opinion, there’s no reason for him to add a chunk loader to the mod if there are too many mods that already do that.

My personal favourite is FTB Utilities because it doesn’t require you to craft anything. I’ve always wondered why chunk loaders are so fucking expensive. Ender pearls, diamonds, gold, iron, etc. Why do you need so many expensive things to simply make your machines and farms work when you’re out exploring or mining? Chunk loading should be a part of vanilla, dammit!

Excuse my little rant there. I just don’t get why chunk loading is treated like a luxury.

**Comment by FryoKnight** [comment]
@PapiDimmi
Well, as I said before, sadly out server has chunk claiming (and thus loading) disabled in favor for another "claiming" system.

As for cost on chunk loaders, from a SP perspective, it seems dumb, but in servers and such (which most chunk loaders are designed for), they force the chunk to load, making it use resources it normally wouldn't if a player is away.
And Chunk Loading really had no use in vanilla outside of Redstone contraptions, farming, and furnaces...

And this is only a request, I honestly don't expect him/her to add one, and if they do, I would be overly excited.

**Comment by GrzechuGrek** [comment]
This is best ChunkLoader like stuff IMHO:
https://minecraft.curseforge.com/projects/chunkloader-simple

It is simple, very effective, open source and has simple configuration option.
It's good to pattern on it.

**Comment by PapiDimmi** [comment]
>And Chunk Loading really had no use in vanilla outside of Redstone contraptions, farming, and furnaces...

That sentence is pretty self-contradictory. I would want my furnaces, automatic farms, etc. to function when I’m not at home in vanilla. An idea would be that every furnace would chunk load the chunk it’s placed in, but there would be a limit, and it wouldn’t work on servers. That would be pretty neat.

**Comment by PapiDimmi** [comment]
>And Chunk Loading really had no use in vanilla outside of Redstone contraptions, farming, and furnaces...

That sentence is pretty self-contradictory. I would want my furnaces, automatic farms, etc. to function when I’m not at home in vanilla. An idea would be that every furnace would chunk load the chunk it’s placed in, but there would be a limit, and it wouldn’t work on servers. That would be pretty neat. Or maybe there could just be a button that you could click in singleplayer to chunk load a chunk.

**Comment by PrinceOfAmber** [comment]
Moved this to my project planning backlog https://github.com/PrinceOfAmber/Cyclic/projects/1
