### ISSUE TITLE
Hydrator should support same item in all input slots [and inputs can break recipe]

### ISSUE THREAD

**Issue by viveleroi** [PrinceOfAmber/Cyclic#587]
I'm trying to automate concrete production using the hydrator but it seems that I can't use a vanilla hopper to automate input, because it outpaces the concrete production and begins to fill up more than a single slot with concrete powder. As soon as the hopper puts in more than 64 concrete powder, the hydrator stops recognizing the recipe and stops producing concrete.

I'm not sure I have a way around this in my specific modpack, but it seems like it would be much simpler if the recipe would still work with multiple stacks of the same items.

**Comment by PrinceOfAmber** [comment]
Oh i see what you mean. so the recipe is only using 1 out of the four slots, and those slots fill up and it stops crafting.

"but it seems like it would be much simpler if the recipe would still work with multiple stacks of the same items." Yeah so the recipe is locked in, and then it just uses whatever

We do need some solution. In most normal autocrafters, the place you set the recipe is a different section of the GUI than where you fill up the contents, so usually this isnt a problem.  a third option is a way for player to "lock out" some slots. or somehow .

**Comment by PrinceOfAmber** [comment]
Ive got it working so if there is a 4x4 of concrete powder, it just takes one out for the cost.

I am also going to add some sort of button that locks it down so each input slot cant go smaller than 1. this helps for filtering out unwanted input, and also for keeping 4x4 recipes set so the wrong item doesnt go in the wrong place.

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
