### ISSUE TITLE
Ladder sounds when using climbing gloves

### ISSUE THREAD

**Issue by PapiDimmi** [PrinceOfAmber/Cyclic#588]
There are ladders sounds when using the climbing gloves. It’s not a big deal, but it doesn’t make much sense either, since you’re not actually climbing a ladder.

****

**Minecraft version**: 1.12.2
**Cyclic version**: 1.9.12

**Comment by Vyraal1** [comment]
I think the sound is fine, and appropriate mechanics wise, as sometimes if you don't use baubles much and you just find yourself sticking to and climbing walls, the sound is a good reminder you have the gloves on.

**Comment by PrinceOfAmber** [comment]
I might swap it out to my own custom sound one day, but it might be bad and it would confuse players like "what is that".  This seems like a well known "climbing sound". like splashing in water. pretty standard

SO yeah works as intended.

**Comment by PapiDimmi** [comment]
Why would a player be confused by a sound when they’re climbing when they made and enabled climbing gloves?
