### ISSUE TITLE
Can't export out of Uncrafting Grinders

### ISSUE THREAD

**Issue by GoDiddleACactus** [PrinceOfAmber/Cyclic#589]
Minecraft version & Mod Version: 1.10.2 - 1.10.29

Single player or Server: Both Single Player and Server

Describe problem (what you were doing / what happened): No item cables extract from the uncrafting grinders (tested Itemducts from Thermal Dynamics, Item Conduits from Ender IO, and Buses from Applied Energistics 2)

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Have you tried exporting out of the bottom?  I know it works with hoppers last i checked.

**Comment by PrinceOfAmber** [comment]
Ive fixed this in Minecraft 1.12.

legacy versions such as 1.11 and 1.10 are stable and feature complete, so they wont get an update unless there is a gamebreaking bug of some kind
