### ISSUE TITLE
[Suggestion / Enhancement] Workbench integration with Crafting Tweaks

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#590]
MC 1.12.2
Cyclic 1.9.13

Would it be possible to implement two changes with the Cyclic Workbench? The first is integration with 
 Crafting Tweaks (https://minecraft.curseforge.com/projects/crafting-tweaks) to allow for hotkeys to clear/rotate/etc. the crafting bench. Aside from installing TiC just for the TiC crafting station, I like your implementation of the workbench the best.

Second could you allow for configs to darken outside the GUI's? I'm not actually sure if it's Optifine or Cyclic, but  It seems so far unique to GUI's within Cyclic. Most of them are fine, but it did feel slightly off to have a crafting grid without a tinted background.

**Comment by PrinceOfAmber** [comment]
I havent really used tweaks, hopefully its a nice easy add.  Thanks for the nice words too!

"crafting grid without a tinted background." I will check into what other mods are doing. I do want it to be consistent.

**Comment by PrinceOfAmber** [comment]
Note to self: docs here https://github.com/blay09/CraftingTweaks/blob/1.12/README.md

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
