### ISSUE TITLE
[1.12] Tank block containing lava gives off no light.

### ISSUE THREAD

**Issue by JaSpr** [PrinceOfAmber/Cyclic#591]
Version:
1.12.2-0.10.23

A tank (block) full of lava should give off light.  There should be a setting such as setLightLevel that can be called on the block class to set the amount of light it is giving off.  I would assume you could have a check for whether the contents are lava, and if so, set it to whatever.  I've seen many other tanks from other mods do this as well, which is the main reason it stood out to me that this one didn't.

**Comment by JaSpr** [comment]
Here is a screenshot of the Mekanism tank with lava on top of the Cyclic tank with lava: 

![Screenshot](https://i.imgur.com/i11av66.png)

**Comment by PrinceOfAmber** [comment]
Thats a good idea, great feature to add.

**Comment by PrinceOfAmber** [comment]
Luckily mek is open source so I could see the line i was missing

https://github.com/aidancbrady/Mekanism/blob/049c78088850eb5bb8415c652923d171b97013d9/src/main/java/mekanism/client/render/tileentity/RenderFluidTank.java#L103

This is what it looks like now.  Not exactly like Mek but much brighter now, its not almost black anymore.

![not dark anymore](https://user-images.githubusercontent.com/621529/33194918-33b2dc28-d088-11e7-88f1-a70b98362a33.PNG)

**Comment by PrinceOfAmber** [comment]
Update again: Even brighter now even with more darkness 
![2017-11-23_20 06 10](https://user-images.githubusercontent.com/621529/33195132-d8df8fb0-d089-11e7-81a0-a894d2025bf9.png)

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
