### ISSUE TITLE
Sandstone tools lack localization in JEI

### ISSUE THREAD

**Issue by PapiDimmi** [PrinceOfAmber/Cyclic#592]
![cyclic - localization issue 2](https://user-images.githubusercontent.com/25916106/33134341-c4f4f192-cf9f-11e7-98c0-8797de8d09e6.png)

****

**Minecraft version**: 1.12.2
**Cyclic version**: 1.9.13

**Comment by PrinceOfAmber** [comment]
also happens on the emerald tools & armor

**Comment by PapiDimmi** [comment]
Please fix it. Cyclic is literally unplayable ATM.

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0

**Comment by PapiDimmi** [comment]
Thanks!

**Comment by PapiDimmi** [comment]
By the way, I have a question, @PrinceOfAmber: Are you only updating the Cyclic version for MC 1.12.2, or will you backport features, changes, and fixes to 1.9,4, 1.10.2, and 1.11.2?
