### ISSUE TITLE
Crash / Game Freeze with Cyclic Building Wand

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#593]
**Minecraft**: 1.12.2
**Cyclic**: 1.9.13
**Single Player**

Game seems to freeze at random times when my Building Wand runs out of materials.

Crash log (if any): https://gist.github.com/Vyraal1/8ddbaa6052c535b634ed34a30bdb425c

Sorry for the lack of a proper crash log, for some reason the game doesn't actually crash and hang up, but I copied and pasted the area where it seems to get stuck at and never outputs an actual crash log.

**Comment by PrinceOfAmber** [comment]
No that log is perfect actually, its right on the error.

You are right on the money, it runs out of stuff but then tries to place that "empty slot" item in the world as an air block and it all breaks.
