### ISSUE TITLE
Redstone clock only ticks once

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#596]
MC 1.12.2
Cyclic 1.9.13

Single player.

Maybe I misunderstand. But setting the clock to work on redstone signal and placing a lever on it. The clock only ticks once. It looks like it ticks visually but nothing happens. I have a dropper placed next to it and that only drops 1 item when I first turn the lever on.

**Comment by PrinceOfAmber** [comment]
I saw your situation when the clock and lever were all touching.  But if the clock is just in "always on" state, it works.

Also it works as shown here if i add some distance between them. Therefore I think the lever must be also powering the hopper indirectly, (sometimes redstone does weird things and powers things 2 blocks away.)

![clockhopper](https://user-images.githubusercontent.com/621529/33235431-3ad98838-d1ed-11e7-897f-fc91154cb25c.gif)

**Comment by Ash70** [comment]
Good to know; I can work around that. Thnx.

**Comment by Ash70** [comment]
I had the same issue with a harvester it seems (I therefore wrongly added a reply to #580). Placing a lever directly on a harvester also disables the hopper underneath it. I haven't tried it yet; but I am hoping I can resolve this using the new wireless transmitter/receiver blocks (awesome additions btw).
