### ISSUE TITLE
Crash Using Recipe Book in Vanilla Crafting Table

### ISSUE THREAD

**Issue by MadToilet** [PrinceOfAmber/Cyclic#597]
Minecraft version & Mod Version: Minecraft 1.12.2 & Forge 1.12.2-14.23.1.2554-universal

Single player or Server: Server

Describe problem (what you were doing / what happened): Opening the recipe book in the vanilla crafting table.

Crash log (if any): https://paste.ee/p/OWYKS

**Comment by PrinceOfAmber** [comment]
Yeah for some reason the recipe in the guidebook item (from the guidebook API mod) was glitching out.  I just removed the recipe in the 1.10 update.  You get the book on spawn anyway.
