### ISSUE TITLE
Strange EXP glitch

### ISSUE THREAD

**Issue by Jacobeta** [PrinceOfAmber/Cyclic#60]
When I had Cyclic installed (and I know it was Cyclic because I took apart my modpack) I noticed that things like:

Equipping Wildwood Armor from Roots

Firing a Mana Blaster from Botania Unofficial

Or even dealing critical damage

Wildwood Armor gave me an incredible "experience generation" rate that couldn't be stopped until unequipping a piece.
All else gave me around a level or two at level zero.

**Comment by PrinceOfAmber** [comment]
Ill look into this.   I dont have many features that touch exp, and each of them can be turned off with a conflig true/false, once we figure out what it is.

 one of them is ' gaining experience  gives random exp' but that should only happen once.

 ill get back to you

**Comment by PrinceOfAmber** [comment]
Yeah, i just saw it happen with botania - 314 and cyclic 1.4.4, using forge-1.10.2-12.18.1.2044

**Comment by PrinceOfAmber** [comment]
Cause found: A forge event was telling me "HEY this player got an achievement".  but actually, the player met all the conditions to gain it, except they didnt have a prerequisite achievement.  so the real game said they didnt get it, but my feature thought they did.

Its the feature in the in-game config : player -> Exp Achievements. to turn it off.

Also fixing this in upcoming 1.4.5 release

**Comment by PrinceOfAmber** [comment]
1.4.5 released to fix this! let me know how it looks on your end

https://minecraft.curseforge.com/projects/cyclic/files/2320355
