### ISSUE TITLE
Crashed while trying to access Cyclic Inventory Crafting Table / Extra Inventory Space

### ISSUE THREAD

**Issue by Quostin** [PrinceOfAmber/Cyclic#601]
Minecraft version & Mod Version:
1.12.2 
1.9.13

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Basically I was working on something, and had sticks in my hand and was going to move them to either the Inventory Crafting Table or Extra Inventory Space. I clicked on one of the buttons next to your model to try to open it, and it crashed as soon as I clicked it. It basically crashed the server it was on, but not the game itself.

**Comment by PrinceOfAmber** [comment]
I will look into this.  Do you have a crash log for it?  Any weird items inside there?

**Comment by Quostin** [comment]
I can't seem to replicate it again. It happened about 3 times so far on accident, but when I go and try to do it the way I did it before, it just works normally with me throwing the sticks or items on the floor. I don't have a crash log that I can find. I checked logs and couldn't find anything about it. Maybe I did something before dragging sticks and clicking the buttons that it didn't like, but trying to replicate it not working...

**Comment by PrinceOfAmber** [comment]
Thanks for reporting anyway.  I cant get it to trigger, but I will leave thee issue open in case you see it again or someone else comes along.

If its on a server, there is always that slight small chance that someone else crashed it as a coincidence.  Or there is some modded item in the inventory doing something weird.

**Comment by PrinceOfAmber** [comment]
Looks like we found more information on this so there should be progress soon https://github.com/PrinceOfAmber/Cyclic/issues/624

**Comment by PrinceOfAmber** [comment]
This seems fine in latest version. if it happens again after all mods are updated, just reopen issue or make a new one
