### ISSUE TITLE
Forester too slow; logs despawn

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#603]
MC 1.12.2
Cyclic 1.10.1
Single Player

The forester is slow in chopping down trees. Esp. when there are a lot and some are very high, the upper logs drop down onto leaves and have despawned by the time they (potentially would) reach the ground (within range of a hopper or collector)

**Comment by PrinceOfAmber** [comment]
I 
Also, there are ways to speed up item collection.  The Item Collector in cyclic can grab things from long range.  Also there is the item plate which pulls item stowards it

But even with those, yeah i can see super tall trees like 4x4 spruces causing a problem.  I'll look into speeding it up a little bit. T least make it chop blocks faster, maybe Efficiency V speed

**Comment by PrinceOfAmber** [comment]
Should the Forester also chop down leaves?  Then any logs that land on a leaf will fall faster

**Comment by Ash70** [comment]
Also 'chopping' leaves would help yes. Thanks

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2505275
