### ISSUE TITLE
Emerald apple does not get consumed when used on zombie villager

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#606]
Minecraft version & Mod Version:
Horizons III modpack , 1.12

Single player or Server: SP

Emerald apple is supposed to be a single use item and get consumed 

https://twitter.com/lothrazar/status/936489057974067200

**Comment by forestbat** [comment]
Emerald apple is so expensive that I think it shouldn't be consumed。

**Comment by PrinceOfAmber** [comment]
Maybe i did do that on purpose, i forget.  

Or maybe it could have multi uses, or be cheaper?

It kind of does two different things, maybe that could be split into 2 items? Ill think on that. Any suggestions?

**Comment by forestbat** [comment]
Player can use emerald apple to let two villagers breed a little villager。Is it OK？

**Comment by forestbat** [comment]
Some people want zombie villager become a new special villager（need custom in code）or just villagers in other mods such as AA or IE。

**Comment by PrinceOfAmber** [comment]
When a zombie villager is cured, it can be come any type, modded or not from what I have seen.

I will make it much cheaper so that having it get consumed is not so bad. Ill do some testing and get some feedback before release
