### ISSUE TITLE
[Suggestion] Add a liquid rubbish bin.

### ISSUE THREAD

**Issue by droashen** [PrinceOfAmber/Cyclic#609]
Thx for adding some useful pipe in your mod.
I sugguest :
Just adding a void bin(a bin can destroy some useless liquid),
May make things better.

**Comment by PrinceOfAmber** [comment]
Makes sense.  Maybe it could void both items and fluids

**Comment by PrinceOfAmber** [comment]
This has been added in the latest update https://minecraft.curseforge.com/projects/cyclic/files/2515962
