### ISSUE TITLE
[Suggestion] Pattern replicator flip option.

### ISSUE THREAD

**Issue by BeardStroker** [PrinceOfAmber/Cyclic#610]
The pattern replicator is an amazing block that I enjoy a great deal, but I am currently building a bunch of symmetrical areas where having the option to copy an area and rotate it, or flipping it like a mirror image of the target would be a fantastic timesaver and I would love to see something like that implemented.

**Comment by PrinceOfAmber** [comment]
Fantastic Idea. I'll look into this

**Comment by PrinceOfAmber** [comment]
Since im workign in here anyway, I am thinking about a few more improvements

- Make it build in a linear path, not random
- POSSIBLY have some sort of blueprint-type-item to select the region, and read write into them.  Totally optional, but gives an alternate method to using the buttons

**Comment by PrinceOfAmber** [comment]
OH and i added a better preview.  I figured why is the target just an empty box when it could instead outline the shape of exactly what its about to build

![better preview](https://user-images.githubusercontent.com/621529/33751778-03eb492a-db92-11e7-88e2-c878cf680c7a.png)

**Comment by BeardStroker** [comment]
This is awesome! I love this mod and this adds icing on the delicious cyclic cake. Thanks for looking into this :)

**Comment by PrinceOfAmber** [comment]
Feature is out in latest version. come back any time if you have bugs or suggestions 

https://minecraft.curseforge.com/projects/cyclic/files/2508261
