### ISSUE TITLE
[Bug/Suggestion] Refilling / Repairing Automatic Torch

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#613]
**Minecraft** 1.12.2 and **Cyclic** 1.10.3
**Single Player**
**Describe problem:**
Seems like in the anvil you can combine ANYTHING with the Cyclic Automatic Torch to restore 64 durability to it. In the linked at first I tried combining it with one torch, and on a whim I tried to repair it with an abyssalcraft monster egg, both registered as valid to repair the automatic torch.

Maybe instead of using an anvil to repair the torch, possibly make it similar to the Silent's Gems Torch Bandolier, where you can cycle through an auto-fill option and it will absorb any torches inside a player's inventory to restore a point of durability each. 

https://imgur.com/a/ejQgx

edit: Also maybe you could implement this automatic restore function for the Torch Launcher as well.

**Comment by PrinceOfAmber** [comment]
Fixed the repair issue.

" an auto-fill option and it will absorb any torches inside a player's inventory to restore a point of durability each."... I'll look into this for a future update

**Comment by PrinceOfAmber** [comment]
I fixed the repair bug 
https://minecraft.curseforge.com/projects/cyclic/files/2508261

I put other feature on backlog, the auto refil one https://github.com/PrinceOfAmber/Cyclic/milestone/139
