### ISSUE TITLE
[1.12.2] Eating Cyclic Hearts seems to have no effect on the player

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#614]
**Minecraft** 1.12.2 & **Cyclic** 1.10.3
**Single player**
**Describe problem**
Eating the cyclic hearts seems to have no effect on the player except a minor saturation restoration as if you were eating any normal food. Eating it at half health did not heal any hearts as well, and my health bar stayed at 10 hearts, I jumped into lava to confirm. The difficulty was on Hard if it matters. Am I using this item correctly?

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Vyraal1** [comment]
Ahh ouch, it's a fairly large custom pack I've been working on for the past 3 months, glancing quickly at the modlist at the possible mods that might affect hearts:
Betweenlands
Baubley Heart Canisters
Mantle (handles the changing heart colors like how TiC used to do it)
Nutrition (it's additional hearts though seems to be compatible with Mantle)

I might be missing a couple but those 4 seem to be it at the moment.

**Comment by PrinceOfAmber** [comment]
It depends how they are written. Cyclic goes "you eat a thing, ok take your current hearts and add +1" so its usually fairly compatible, ive used it with nutrition and mantle before, others not so much.

What some mods may do is something like

"What does my mod logic say the players health should be? is it 10 hearts? ok set that now" and run that at regular intervals.  So when you eat a heart and go to 11, some other mod will be like "nope fix that". 

Not anybodys fault really just how it works.  So you could either

A) disable the heart items from Cyclic in config file and let other systems take over
B) find out what mod is conflicting, and make a bug report there

**Comment by PrinceOfAmber** [comment]
Sounds like we figured this out, and its just a matter of mods doing the same thing in different ways.

I will mark as fixed by config, if theres any issues with only Cyclic, open them up anytime!
