### ISSUE TITLE
Self sustaining infinite item dupe bug using item pipes

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#615]
**Minecraft version & Mod Version:**
1.12.2, forge: 14.23.1.2561 Cyclic: 1.12.2-1.10.3

**Single player or Server:**
Server, as far as I've discovered.

**Describe problem (what you were doing / what happened):**
When comboing a large amount of roosts from roost mod and a roost collector my roosts periodically put out eggs and feathers that go to the roost collect if it's close enough. But my roosting area is quite long, so I've got 3 roost collectors in different locations.

I then proceeded to use item pumps with mounted levers on them to pump the feathers and eggs as they periodically come out into the item pipes over the roosts and into a waiting projectE chest to turn them into a more compressed form for storage.

HOWEVER, when I crossed the beams of my three different roost collectors into one item pipe beam going forward out of the roost area into the chest I discovered that the roosts were producing a stack of feathers or eggs per second and the condenser could barely keep up. The moment I stop the machine, the chest would immediately fill up over a small handful of panicked and surprised seconds. this was just one condenser. I then decided to split the pipe into 3 more different condensers...still the same problem. all instantly full unless it was going constantly in which case it could perfectly keep up keeping only a single stack of feathers or eggs there being infinitely replenished even if I took the stack out manually and constantly. 
I made 3 more chests off that. still the same issue. I expanded the amount of item pipes I was using between transportation and put more chests on them. still, full. I had created a self sustaining micro sun/blackhole inside the item pipes that was going to cover the universe in feathers and eggs if I stopped.

It wasn't until I destroyed the item pipes and changed the item pipes to not be combining in the center did it turn back to what was expected. even if I did get a stack of feathers or eggs from each of the item pipes. :V

So I believe there is some form of weird laggy beam crossing duplication black hole that is occuring which is making this stupidly OP. of course after I was done, from just eggs and feathers I had 250,000,000 EMC to get rid off cause I'm not fond of abusing bugs. :V

Crash log (if any): None. it just occurs, and I didn't have access to console if it was spamming anything or not cause friend was hosting.

**Comment by PrinceOfAmber** [comment]
Thanks Ill do some testing.

You mention three into one, you mean something like this? (items flowing to the bottom)

![2017-12-09_23 48 54](https://user-images.githubusercontent.com/621529/33803054-9ec6d400-dd3b-11e7-9c1f-f1bec32c7cb6.png)

**Comment by Darkmega18** [comment]
nice. excellent. super good. and all that.

**Comment by PrinceOfAmber** [comment]
I put out a fix for this.  It worked in all the ways i tested, if it happens again let me know  https://minecraft.curseforge.com/projects/cyclic/files/2508261

**Comment by Darkmega18** [comment]
Roger! thanks for the quick fix and response!
