### ISSUE TITLE
Item collector not working properly

### ISSUE THREAD

**Issue by Trixz2018** [PrinceOfAmber/Cyclic#617]
Minecraft version & Mod Version:
Cyclic-1.12.2-1.10.4     

Single player or Server:
SP

Describe problem (what you were doing / what happened):
when using the item collector with itemducts from TE. the first slot of the item filter gets pulled out. 

![2017-12-10_14 28 45](https://user-images.githubusercontent.com/8538100/33808543-7f49e16e-ddb6-11e7-8dc1-385e05aff3e7.png)

It seems the first slot of the filter list and the first slot of the inventory got switched.

**Comment by Trixz2018** [comment]
![2017-12-10_14 34 50](https://user-images.githubusercontent.com/8538100/33808602-83b4170a-ddb7-11e7-8994-b220baaaa0f3.png)
![2017-12-10_14 36 22](https://user-images.githubusercontent.com/8538100/33808606-88b41be2-ddb7-11e7-9654-e42afb6f62ef.png)

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this. Yep looks like its off by one at least at where its aiming to insert/extract

**Comment by Trixz2018** [comment]
thanks, all patched up in the latest update
