### ISSUE TITLE
Possible memory leak: Auto-user + Garden Scythe + large amounts of sprinklers

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#623]
Minecraft version & Mod Version: 1.12.2, 1.10.5

Single player or Server: Server, but affected my client

Describe problem (what you were doing / what happened):
So, I had a brainwave tonight and decided to make a bunch of super long farms. basically 4 blocks wide on either side of a channel of water down the center, the water channel fully loaded with sprinklers all the way down.
On both sides of the farm channels I planted soybeans and peanuts from harvestcraft, and on the other I did potatoes+carrots and spice leaves.

I then though, "This harvest scythe pulls all the drops to me and is pretty massive, wonder what happens if I float an auto-user over a sprinkler every so often and give this to it". So I did it. harvest scythe whacked everything up, but the visuals were desynced. The plants were harvested but the visuals didn't reset unless I block updated them with a rightclick or the sprinklers went nuts again and made them change. not a big issue. it works fine if I use it myself.

but a massive amount of stuff came out the top of the user and I was soon being flooded with veges and leaves everywhere. so I put an item collector from random things connected to a projectE alchemy chest+gem of eternal density combo above it and let it run... it went remarkably well. I set up 4 more of them across the farm equally spaced out on the opposite side to avoid OCD.

However once they were all good and going I was gradually noticing that my RAM usage was going up faster than usual and it eventually hit 95% or so while I was putting up some signage for friends later down the line and made my game freeze for a spot of time which was long enough to get boot off the server for reason "disconnected". 

This world is completely in void, being essentially an OP skyblock and the farm had been mostly all I was doing during that login onto the server asides from some tinker things.

Thoughts on the matter? The users were all fueled with a stack of charcoal each, were set to lowest speed and had 3 garden scythes loaded up ready to reload and there was just a stupid amount of sprinklers cause of the farms length but that lag only came in bursts kinda when the water came out.

Crash log (if any): nope.

**Comment by Darkmega18** [comment]
![2017-12-14_15 40 11](https://user-images.githubusercontent.com/8104689/33975821-48b49cb6-e0e5-11e7-8966-180548f934b8.png)

here is a screenshot with my F3 active so you can see exactly what I had up. I notice that the leak doesn't happen if I'm not looking at it for some reason. since i went back down to my primary platform and I didn't notice it going up anymore. (I've got one of those fun bases that require mobility tools to get to the different places)

**Comment by Darkmega18** [comment]
Ok, I did some science. 
1. it doesn't seem to be the harvests or the graphical glitch. I turned off the users and RAM was still slowly overloading.

I took out all the nonvanilla plants and just did potatoes and carrots. RAM was still going up. but once I was done and the plants were all fully grown I've sat here for a couple mins and no RAM increase. except maybe a very small one but not as fast as when it was occuring.

and now I... *whacks all crops with a few swings of garden scythe*

oh lordy, yeah, the RAM ticker is going nuts now and it's gradually going up again. it seems to possibly be to do with the sprinklers only. initially I only had a small farm with just a single one before making this platform so the lag wasn't noticeable. but now i see it crapping itself like no other with all these going at once.
Might need to take an optimization pass or something on that.

**Comment by PrinceOfAmber** [comment]
The Garden Scythe uses the same exact action as the Harvester with the ALL function.  The difference is the scythe drops on ground, and harvester gathers right away.


 It hits every plant at once, instead of slowly one by one.  This will put a ton of items on the ground at once.

I will look into it.

**Comment by Darkmega18** [comment]
yeah, hence the observation from the next two posts when I stopped using it that it was actually the copious amount of sprinklers doing something weird instead.

**Comment by PrinceOfAmber** [comment]
Ok im running a test for myself, doing up a big wheat field with a ton of sprinklers and ill leave the game open for a few hours and see what happens

**Comment by Darkmega18** [comment]
you gotta keep harvesting the plants also, using a system like I was doing with harvest scythes and auto-users. it's cause the sprinklers were going constantly and the sheer volume of them in my picture that it was occuring. when I had just one sprinkler it wasn't noticeable or allowed the farms to fully mature and hence the sprinklers to stop sprinkling the RAM bloat stopped.

**Comment by PrinceOfAmber** [comment]
I do see the ram spike up a bit.  Not as much as you, maybe because my setup is much smaller  I recorded a gif of a small test (single player).  crops are wheat, coffee from AA and hemp from IE


Recording below: so before harvest im running about 1000 MB ram, as soon as I harvest it spikes to 1800 at the highest.  Ill see what i can do.  

GIF LINK: https://i.imgur.com/ibScslw.gifv

Probably not sprinklers since it only happens on harvest, so its that harvest action doing the thing.

Either its my mod acting up OR it might just be all the items hitting the ground all at once.  Either way there is a solution, because if its the items fault, then thats why the Harvester block exists since it does not spawn items in the world

**Comment by Darkmega18** [comment]
but the ram for me only goes up while the sprinklers are actively sprinkling stuff and making their little water particle bursts. :V when the blocks are fully grown, no ram expansion from sitting around in the area watching the plants grow anymore.

The harvest scythes also barely get time to drop stuff on the ground cause there are item collectors on each of them that just vacuum everything up into the collectors or they go to my inventory if I'm doing it myself.

You see the spike in the rate that your ram percentage ticks up and down right AFTER you use the garden scythe and the sprinklers spring to life again? thats what it does while they're all going. theres a small lag burst on harvest but not that big on my end, but then without actually causing FPS drops until RAM starts getting maxed the RAM's rate of climb and then dropping and then climb again goes absolutely nuts. it's during that which I think it's leaking and causing the ram usage to slowly go up further and further each cycle.

**Comment by Darkmega18** [comment]
Alright, got the video. It's exporting now, then gonna upload it to my youtube as unlisted for you to view. :)

**Comment by Darkmega18** [comment]
https://www.youtube.com/watch?v=ISbetC8ClPQ&feature=youtu.be

here you go. Also notice that the sprinklers once fully done and then harvested with garden scythe didn't keep producing particles. Although I have a feeling that was something on my side, even if all my particles were on. But I've had this before while using sprinklers too, so might be worth a look at.

**Comment by PrinceOfAmber** [comment]
Hey i didnt forget about this.  IM not sure what to change for harvesting or users, but I soon will be releasing an update where you can turn off the particles from the sprinklers, this should help a lot https://imgur.com/89kgO2J

**Comment by Darkmega18** [comment]
Alright. will have to try it with the sprinkler array again and see if it still affects my ram as severely... next time I get back to MC. since I've been playing other things since MC doesn't hold me as well as it used to... :V

**Comment by PrinceOfAmber** [comment]
Ive youre done with MC don't worry about it, someone else will notice it.

For anyone else reading this, two other tickets got fixed that may be causing this or related.  Both affect sprinklers/harvesters/lag 
https://github.com/PrinceOfAmber/Cyclic/issues/688
https://github.com/PrinceOfAmber/Cyclic/issues/690

Ill mark this as cannot replicate for now which is like "semi-fixed" better than it was, but leave open in case of updates
