### ISSUE TITLE
Faith Plates don't conserver much sideways speed

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#625]
Is it a minecraft thing that the player doesn't conserve momentum as well when being launched diagonally on faith plates? 

as I go incredibly high off them, but when I go sideways my momentum absolutely sucks and I don't keep going so I can't use them in replacement for bridges for launching across chasms etc.

It might have been a long time back, but the faith plates when ichun did them in the portal mod were the good stuff, you kept going unless you directional influenced out or hit a surface. As you could bounce off them and keep going. Are you able to replicate that or is that not possible anymore?

this is an alright example of what they were like back in the day that I wished I could use them like: https://www.youtube.com/watch?v=5kubLIfXzxc&index=18&list=PLVPJ1jbg0CaFv_XteJAlFNz66nFzu_mNN

and heres a spotlight where the person in video leaves them default and gets sent flying, around 3 quarters through: https://www.youtube.com/watch?v=hDLM8wXKwQU

**Comment by PrinceOfAmber** [comment]
Yeah the iChun plates is what inspired me to make these, but I'll be honest havent tested or played with them in a while.  

Great feedback and videos, ill work on this.

**Comment by PrinceOfAmber** [comment]
I upgraded this, try it out and let me know how it feels! Speed and momentum changes means existing layouts or settings might have to change of course  https://minecraft.curseforge.com/projects/cyclic/files/2513600

**Comment by Darkmega18** [comment]
Alright, cool! will do. Once I get all the updates to other mods that cropped up over christmas day also and get back on my server when it's all updated. :)

**Comment by Darkmega18** [comment]
Works great! thanks for upgrading them. :)
