### ISSUE TITLE
Sleeping Mat Places Torches / Blocks from off hand. 

### ISSUE THREAD

**Issue by KaneHart** [PrinceOfAmber/Cyclic#626]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic-1.12.2-1.10.6.jar

Single player or Server:
Dedicated MP

Describe problem (what you were doing / what happened):
When I use the sleeping mat it places torches/blocks from my off hand on the ground.

Should cancel the right click event.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2511574
