### ISSUE TITLE
Empty Beacon Beam Issue

### ISSUE THREAD

**Issue by xorinzor** [PrinceOfAmber/Cyclic#627]
Minecraft version & Mod Version:
MC 1.12.2 & Cyclic 1.10.6

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The beam from the Empty Beacon block disappears when you look up and the block is no longer within the viewport.

**Comment by PrinceOfAmber** [comment]
Yeah i need to improve it so for sure; good call

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2511574
