### ISSUE TITLE
cyclic harvester minor bug

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#628]
Minecraft version & Mod Version:
1.12.2 cyclic version is 1.12.2-1.10.5

Single player or Server:
single player

Describe problem (what you were doing / what happened):
cyclic harvesters take any item as fuel even non fuel items 

Crash log (if any):
doesnt crash but is a bug

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
How did you get the non fuel into the fuel slot? I tried putting in stone and pressure plates and they wont go in. tried with hoppers and the interface

**Comment by CharCharthemonkey** [comment]
basically i had a wheat farm setup didnt realize my seed storage filled up then checked and it showed seeds in the fuel slot for the harvester from cyclic

**Comment by IamAlathe** [comment]
Is this in a modpack or with other mods?  I know one of the packs I'm playing lets you burn wheat seeds as fuel.

**Comment by CharCharthemonkey** [comment]
@IamAlathe its my custom pack but it didnt actually burn the seeds it just shoved them in the slot cause of a full inventory

**Comment by PrinceOfAmber** [comment]
Yep thats what its doing, when it gets full its treating the fuel slot as a regular storage one when it shouldnt.  Fix on the way

**Comment by CharCharthemonkey** [comment]
thank you lothrazar

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2513600
