### ISSUE TITLE
Document obsidian armor and inverted stirrups

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#629]
https://github.com/PrinceOfAmber/Cyclic/blob/f688bcee7e66b286167839ca933a2559b6aa4108/src/main/resources/assets/cyclicmagic/lang/en_US.lang#L356-L363

https://github.com/PrinceOfAmber/Cyclic/blob/f688bcee7e66b286167839ca933a2559b6aa4108/src/main/resources/assets/cyclicmagic/lang/en_US.lang#L434-L435

These should really have guide text.

**Comment by PrinceOfAmber** [comment]
I also found a bug on obsidiian armor while testing for this: crafting it with shift click did not add the enchantments so fixing that now

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2511574
