### ISSUE TITLE
Diamond Spikes Duplication Glitch

### ISSUE THREAD

**Issue by tigerdan2** [PrinceOfAmber/Cyclic#630]
1.12.2 - Cyclic-1.12.2-1.10.6.jar

Yet testet on SP

When you remove a redstoneblock behind a extended spike (diamond or iron)
the spike will drop 
BUT
there will be a retracted still flying in the air
You can extend this spike again and repeat this process infinitly

with some work you can make a dupe masterpiece with it

https://streamable.com/8ybc1
https://streamable.com/ohrcf

**Comment by PrinceOfAmber** [comment]
Thanks for making the video thats perfect

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2511574
