### ISSUE TITLE
Experience Pylon XP Value Wrapping Around to Negative

### ISSUE THREAD

**Issue by Yukondano2** [PrinceOfAmber/Cyclic#632]
Minecraft version & Mod Version:
  Minecraft 1.12.2, Cyclic 1.10.3
  Horizons 3 Pack

Single player or Server:
  Server, horizons3.brierie.net

Describe problem (what you were doing / what happened):
  The Experience Pylon XP value is wrapping around to a negative value, looks like it's wrapping at the upper limit of an int16 (not to try and pretend I know how your code works). It still works fine, though, it's just presented weird. 

![2017-12-18_22 56 05](https://user-images.githubusercontent.com/12215434/34144522-b4c80f8c-e446-11e7-9f22-3524b77ddf74.png)

**Comment by PrinceOfAmber** [comment]
Thanks for the report I had fixed something similar in the past, but that was before changing the interface I think.  https://github.com/PrinceOfAmber/Cyclic/issues/573

**Comment by PrinceOfAmber** [comment]
Do you remember what it was working with to become negative? Maybe fluid pipes from mekanism or thermal?

**Comment by Yukondano2** [comment]
I use no mechanisms with my pylon. I walk up to it when I get any XP, click the "all" button, then leave. No pipes or anything. I can recreate it at will with the pylon at my base, all I gotta do is deposit beyond the upper limit. I can add XP to my player just fine, it wraps back to positive then goes down normally.

**Comment by PrinceOfAmber** [comment]
bug was introduced by https://github.com/PrinceOfAmber/Cyclic/issues/599

**Comment by PrinceOfAmber** [comment]
Sorry for the trouble, i got a fix out https://minecraft.curseforge.com/projects/cyclic/files/25118470000000000000000

**Comment by yuri0r** [comment]
issue still appers in version 1.16.6 but only on dedicated servers
tested with default configs and no other mods installed.
