### ISSUE TITLE
Scepter Crash

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#635]
**MC** 1.12.2 
**Cyclic** 1.10.7

**Single player**
Although the crash seems to kick me out of the internal server, doesn't fully crash the client (for some reason when the game stopped, it put me in the Multiplayer server selection screen), and doesn't produce a crash report like last time. Copied and pasted what I thought was the relevant parts from the log.

Describe problem (what you were doing / what happened):
Was using scepter to make a vanilla farm on a skyblock. Wanted to place planks below dirt, right clicked and saw the scepter was empty, hence the first message in the log. I placed 32 planks in the first slot, and used it a couple of times. and then switched my tool to break some dirt blocks. When I scrolled with the mouse wheel across the hotbar, I it crashed when it cycled past the Scepter (which should've still had oak planks left in it). 

Crash log (if any): https://hastebin.com/ojumofoqay.php

**Comment by PrinceOfAmber** [comment]
Added a fix for it. Glad youre enjoying the tool! https://minecraft.curseforge.com/projects/cyclic/files/25118470000000000000000
