### ISSUE TITLE
1.10.2-Garden Scythe Bug

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#64]
Harvesting a 2 block tall sugar cane plant will leave the top block floating in the air

**Comment by PrinceOfAmber** [comment]
Yeah i see it doing that too.  Seems to work ok with cactus but not with reeds, ill check it out asap

**Comment by WenXin20** [comment]
Thanks

**Comment by PrinceOfAmber** [comment]
Version 1.5.0 has a fix for this ( as well as other features and fixes ) . I just uploaded it, so should be available once curse finishes its processing.

Let me know how it works on your end.

https://minecraft.curseforge.com/projects/cyclic/files

**Comment by WenXin20** [comment]
It works, but I also noticed that when it harvests cocoa beans, the beans don't connect to the jungle log on the correct side.

**Comment by PrinceOfAmber** [comment]
Aha, yep. i see that too, the cocoa beans get put on the wrong side. Can you please open a new issue ticket for the cocoa beans bug?

**Comment by WenXin20** [comment]
Ok
