### ISSUE TITLE
Automated user cannot place cobblestone into Advanced Mortars

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#640]
Minecraft version & Mod Version:Cyclic-1.12.2-1.10.8.jar

Single player or Server: both

Describe problem (what you were doing / what happened):

The user can affect the mortars when empty handed, and advance their state.  But cannot place blocks inside them.

As a real player, i can place items inside and then activate

Other mod https://minecraft.curseforge.com/projects/advanced-mortars

**Comment by codetaylor** [comment]
It could be something on my end... I'll poke at it after I get some sleep.

**Comment by codetaylor** [comment]
I tested and it seems to work with items that are not blocks.

I think this is the culprit:
https://github.com/PrinceOfAmber/Cyclic/blob/b8d45881abf4f23f078bb898ad6ee9a1a377a6e1/src/main/java/com/lothrazar/cyclicmagic/component/autouser/TileEntityUser.java#L175

I'm pretty sure you mentioned something to this effect already.

BTW: Thank you for making this awesome mod! :)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2513600

**Comment by PrinceOfAmber** [comment]
Yeah I think at first i did not want it to place blocks in the world so i did that.... but i just stripped it out.
