### ISSUE TITLE
[1.12.2] LAN Player Crash - Ender Book Use

### ISSUE THREAD

**Issue by MokahTGS** [PrinceOfAmber/Cyclic#641]
Minecraft version & Mod Version:
1.12.2 Cyclic 1.10.6

Single player or Server:
Singleplayer Hosted LAN player

Describe problem (what you were doing / what happened):
When a LAN player used the Ender Book to teleport to a WP they crashed.

Crash log (if any):
https://pastebin.com/3UU3Cmt2

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I tried it a few times in my own LAN world and didnt' crash, 

..but log mentioned issue with SoundManager.. maybe its trying to play sound before the world had loaded?   so anyway it gives me somewhere to start investigating.

**Comment by PrinceOfAmber** [comment]
no updates. I have not found anything, or replicated it.  Crash log does mention cyclic at all.  I wonder if its different in newer forge, or if one of your 20 coremods is doing something funky... 

Feel free to repoen if this is still happening all the time and causing you grief, but i dont see what I can do.
