### ISSUE TITLE
Corrupted Chorus fruit teleportation

### ISSUE THREAD

**Issue by tigerdan2** [PrinceOfAmber/Cyclic#645]
Minecraft version & Mod Version:

MP 1.12.2 1.10.8

Corrupted Chorus sets you in spectator mode, wich allows you to move through walls
but if you press any hotkey it still opens the spectator menu where you can tp to other players.

**Comment by PrinceOfAmber** [comment]
Thats weird, I guess I only tested it in single player, I dont see that menu, I see this regular inventory.


![corrup](https://user-images.githubusercontent.com/621529/34474425-6b857984-ef33-11e7-8349-f466b36326d0.PNG)




.. The fix i find just doesnt let the player open/use their inventory while in this mode, just auto closes it

**Comment by PrinceOfAmber** [comment]
Oh nevermind, its not the inventory screen you use hotbar buttons (123) and it pops up, i remember now. Ok looking into it

![hotbar chorus](https://user-images.githubusercontent.com/621529/34474855-0a3b7cc6-ef3a-11e7-9e07-4e1c722e0dbb.PNG)

**Comment by PrinceOfAmber** [comment]
Check out this fix it should block out all access to that. If not come back and let me know :) https://minecraft.curseforge.com/projects/cyclic/files/2515962

**Comment by shinji257** [comment]
This issue is still present.  If you spam Shift + 1 or Space +1 the spectator menu will come up and still allow you to use the teleportation feature.

Cyclic: 1.19.15
Minecraft: 1.12.2
