### ISSUE TITLE
Suggestion: Sprinkler compatibility with certain liquids to create effects.

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#647]
An idea for you to improve the sprinklers with powers I've never seen done that you could do first.

Ability to place sprinklers on top of other types of liquids from suggested mods to provide effects to crops or surrounding area.

Suggestions to start with, liquid fertilizer from the recently updated Hatchery mod. Using a sprinkler over block of liquid fertilizer placed in the world could cause the sprinklers effects to be improved by a certain factor while randomly transforming farmland to it's own fertilized variant.

Gelid Cryotheum in thermal foundation could produce snow onto all blocks in the sprinklers radius over time that stacks up like snow drifts until it becomes a full sized snow block, while being within the radius when it lets off a puff could slow mobs down.

Witchwater from Ex Nihilo could be used to entice the gradual spread of mushrooms in an area but has a negative effect on natural crops and produces negative buffs if you're in the area when it goes off to produce it's effects.

Sprinklers on lava or pyrotheum could provide some form of in world smelting for blocks placed in the radius, turning cobble into stone, lighting netherracks on fire, smelting ores into ingots, woods into charcoals etc. but it only procs on a smaller area or random spots in the area for balance reasons. and of course sets entities on fire in the radius.

The sprinkler could also benefit from being able to get turned off from a redstone signal for these types of effects that you wouldn't want going 100% of the time or produce negative effects when they go off. So people can set these up and have them wired probably side on or wirelessly through a mod like Malisis switches to achieve greatness.
A limiter if needed could also be imposed in the form of the sprinkler could consume non-water based liquids and only run for a certain amount of sprinkler procs before it can't be used anymore which can either be configured off or the amount of procs as a multiplier could be set.

**Comment by PrinceOfAmber** [comment]
Yeah that is certainly a cool idea.  Would probably need a "v2" upgraded block of sprinkler that actually has a tank of fluid , maybe have it connect to pipes.  There is also things like poison fluid that could kill grass and hurt living things.

**Comment by Darkmega18** [comment]
Aye, indeed. A v2 with internal tank sounds like a good idea.

**Comment by PrinceOfAmber** [comment]
Several updates came out recently for lag, as noted in other issues and in changelogs.One feature is you can right click sprinkler to disable particles. 

 As for giving potion effects, i already have the super Beacon for that.  Sorry im just going to leave this as is.

**Comment by Darkmega18** [comment]
Super beacons eh? it's either they're new or I never got into them. But thats fine then. But it was more on suggesting liquids that it's placed over to give different effects rather than as a potion diffuser like the original post. like being able to make hatchery fertilized soil or spread mushrooms but also badness with witchwater etc.
