### ISSUE TITLE
Request: add recycling compatiblity for thermal expansion machines

### ISSUE THREAD

**Issue by MadRatSRP** [PrinceOfAmber/Cyclic#649]
Vanilla tools and armor can be recycled in thermal expansion machines. Add compatibility of doing recycling with cyclic tools and armor

**Comment by PrinceOfAmber** [comment]
Uncrafter by design only works with vanilla 2x2 and 3x3 recipes, so custom recipes will never work. too big of a change.

Vanilla tools and armor can already be uncrafted if they are fully repaired.
