### ISSUE TITLE
[Suggestion} ghost blocks on filter list

### ISSUE THREAD

**Issue by Trixz2018** [PrinceOfAmber/Cyclic#650]
I was wondering if it is possible to instead of having to place a item in the filter list to have it be a ghost block but still resemble the block that you placed in the filter list.

**Comment by PrinceOfAmber** [comment]
Yeah this would be a good upgrade.  Would save leaving items laying around like that.  

I wanted to when i started but i literally dont know how.  Ill look into it, might have to read source of other mods.  

Also step 2 of doing this is, when someone updates and they have existing items in filter, that is now about to become the ghost filter..., they would have to somehow not get deleted. dropped on ground or something maybe?

**Comment by Trixz2018** [comment]
im not a coder by any means but i know how thermal dynamics servo's/filters work i would suggest looking into their code, who knows maybe talk to cofh team for some help.

also i would say make a big bold statement in the changelog about it when it does get added but knowing how other ppl are they won't read the changelog. But it's your call on how you handle things.

**Comment by PrinceOfAmber** [comment]
Ghost slots are now added to many blocks
