### ISSUE TITLE
Request: Configs to Disable Fluid Placer

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#651]
Minecraft version & Mod Version:
1.12.2 and 1.10.9

Would it be possible to add configs to disable the Fluid Placer? Similar to how there are configs to disable the Block Placer? This is a copy of my current configs, so it could just be a failure on my end to update the configs properly, but I couldn't find one.

https://hastebin.com/bohecavimi.vbs

**Comment by PrinceOfAmber** [comment]
Oh yeah.. currently the fluid placer is enabled or disabled using the shared "PumpAndPipes" config, but ill split it out into a standalone one

**Comment by PrinceOfAmber** [comment]
Added this https://minecraft.curseforge.com/projects/cyclic/files/2520152
