### ISSUE TITLE
Request: blacklist blocks for Sack of Holding

### ISSUE THREAD

**Issue by xorinzor** [PrinceOfAmber/Cyclic#652]
As a server admin, I'd really love a feature to blacklist blocks to be grabbed by the Sack of Holding.
This allows us to manually intervene with plugin issues, or prevent players from grabbing blocks, we don't want them to grab (gravestones for example).

**Comment by PrinceOfAmber** [comment]
Thanks for your patience, i finally got around to this.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2543738
