### ISSUE TITLE
Sidedness for fuel insertion

### ISSUE THREAD

**Issue by TheWerdOfRa** [PrinceOfAmber/Cyclic#654]
MC 1.12.2 & Cyclic 1.10.9

I looked in open and closed issues and skimming I did not see this posted. I have tried to insert into some of the machines, such as a forester, from all 6 sides and none of those sides leads to fuel going into the fuel slot. Everything goes into the main inventory. 

These machines are great for automation, but not being able to supply their fuel automatically leads to a bit of a break down in that automation. Especially when you have a forest of trees that now block your path to the machine to refuel it.

It would be most ideal if we could select the side in game, but second best would be for you to dictate a side for fuel input and have it be obvious to users (a different graphic on that side).

Thank you for your hard work on this mod!

**Comment by PrinceOfAmber** [comment]
"It would be most ideal if we could select the side in game, but second best would be for you to dictate a side for fuel input and have it be obvious to users (a different graphic on that side)." Yep that would be ideal, other mods such as Thermal do that.  (Would be a lot of work, not sure where to start.)

Had to turn off automation going to fuel slot by default so it doesnt mess up normal slots.  

It does work if you connect power to it such as RF, like the thermal power cables or the AA laser relays, this was added fairly recently.

**Comment by TheWerdOfRa** [comment]
I didn't realize it accepted power from power conduits (never tried). That works for me. It would still be nice to have that sidedness, but I definitely understand not being able to do it (I certainly don't do any modding!)

**Comment by PrinceOfAmber** [comment]
Oh yeah I remembered now.

Yeah this changed when I added support for power systems (RF power, etc). People were reporting bugs that items werent being inserted, but they didnt know that was the fuel side.

Also I am adding energy cables in an upcoming release, and maybe power generation after that. :) :) 

Thanks for reports, always appreciate it
