### ISSUE TITLE
Remote lever does not work across dimensions [test if chunk is loaded first]

### ISSUE THREAD

**Issue by ouroborus** [PrinceOfAmber/Cyclic#655]
Any chance we could get a remote switch that works interdimensionally?

**Comment by PrinceOfAmber** [comment]
Yeah that makes sense.  The existing remote lever and wireless redstone blocks should work cross dimensions.

**Comment by PrinceOfAmber** [comment]
I finally came back to this after way too long.  

GIF:

![dimension redstone](https://user-images.githubusercontent.com/621529/43936221-80107968-9c0c-11e8-807b-191233a38408.gif)
