### ISSUE TITLE
Item pipes & storage drawers with void upgrade

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#656]
Minecraft version & Mod Version:  1.12.2-1.10.11

Single player or Server: Both

Have a storage drawer that is totally full, and a void upgrade.

Connect item pipe to it: it won't insert.

Not sure if fault on Cyclic end or both

**Comment by CharCharthemonkey** [comment]
ive noticed that on other storage types as well even without using void upgrades for drawers

**Comment by BigAl607** [comment]
Same thing happening with me. Once I break the item cables and place them back, they work fine for a while.

**Comment by PrinceOfAmber** [comment]
Thanks for the update @BigAl607 . weird that breaking the cable changes things for a while.

Investigating against this version https://minecraft.curseforge.com/projects/storage-drawers/files/2522494

**Comment by PrinceOfAmber** [comment]
I made a very simple setup with a void upgraded drawer.  In isolation in this simple case it works fine

https://imgur.com/a/P7fqT





Maybe it only happens after longer periods of time? Maybe only in more complex networks? If this is the case ... sounds just like  
https://github.com/PrinceOfAmber/Cyclic/issues/693

**Comment by PrinceOfAmber** [comment]
Closed due to inactivity, also it seems to be working fine, for me at least
