### ISSUE TITLE
Monster ball deletes and does not capture villagers

### ISSUE THREAD

**Issue by emiliebarnard** [PrinceOfAmber/Cyclic#659]
Minecraft version & Mod Version: Minecraft 1.12.2, Cyclic 1.10.9

Single player or Server: Server

Describe problem (what you were doing / what happened): When I use a Monster Ball to catch a villager, the villager simply "disappears" as if it was caught, but the ball lands on the ground empty.

Crash log (if any): None.

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I tried this a few times on my small localhost dev server, was working fine for me. So something else is causing the mod that we have to dig at. (gif recording below)

- Can you make this happen again and capture logs from when it happened?
- What modpack or modlist was this?
- Was it a vanilla or modded villager?

![monster ball villagerw](https://user-images.githubusercontent.com/621529/35208835-2323e0dc-feff-11e7-9ad7-eb7d7c57e65f.gif)

**Comment by PrinceOfAmber** [comment]
Any update on this?
