### ISSUE TITLE
Sleeping Mat

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#66]
Should you be able to see yourself when you sleep with the sleeping mat like on the normal bed?

**Comment by PrinceOfAmber** [comment]
Yeah i guess so, i didnt think about it.  This doesnt change anything with the players animation or position so i might have to do something the same as the bed does it.

**Comment by WenXin20** [comment]
Ok, that would be cool to be able to see yourself

**Comment by PrinceOfAmber** [comment]
I looked into this a bit, looked at how the bed works in vanilla, tried a few things. not sure how to accomplish this exactly. Ill leave it open though.

**Comment by Ash70** [comment]
I must admit, I'm not a big fan of the "trying to sleep standing up" message (which I assume is based on this issue?). I understand why you implemented it like that and the additional bonus is that you bypass the infamous "bed bug" (I think?). Don't really know what to suggest to change it. Just my 2 cents (not worth much I know). But maybe just make the screen fade faster to black and no message at all? Whenever I see the message it just "feels" wrong and breaks my immersion somehow.

**Comment by PrinceOfAmber** [comment]
Finally got around to this.  Player will now lay down while sleeping, no more standing up https://minecraft.curseforge.com/projects/cyclic/files/2538330
