### ISSUE TITLE
Suggestions : *Options* to make gold harder to get in nether (vs totally turn it off)

### ISSUE THREAD

**Issue by LordHellscream** [PrinceOfAmber/Cyclic#661]
I love this mod, but some aspects of it trivialize the challenges.
Gold is especially a pain to amass in early to early-mid game since a lot of mods using gold as a way to gate some power recipe by requiring a large amount of it.
In some game, depends on luck, diamond sometimes was easier to come by than gold (not literally, but more of quantity vs demand, for instance I always have enough diamond for my need for most recipe but gold is constantly low until i get some kind of automated quarry in late game, at that point most resources become trivial)

The point is, having gold so easily get in nether really made the modded game much much easier, it's true that gold in the nether is gated behind silk touch, but it's fairly easy to get silk touch in early game with tinker construct (1 emerald, 4 gold and a bunch of silks) and the quantity of gold and the ease to obtain is insane.

Instead of turning it off completely, I would like some kind of option to make it more challenging to get.
Ideas: (1 of them would probably be enough)
1. Spawn only 1-2 per vein.
2. increase hardiness so it takes longer to mine.
3. Possibly enrage nearby zombie pigman  (they are a pain to fight off in early game without good armor or some kind of flying ability)

**Comment by IamAlathe** [comment]
I think these are valid points, but not everyone plays with all the mods, so perhaps something could be implemented as a config option?  I realize you may have meant that by saying *options* in the title of your post, I just wanted to clarify.  :)

**Comment by LordHellscream** [comment]
yes I am simply asking for options to do and they can be turned off by default, and enable in config. I think in general cyclic is a fantastic mod it will be even better if some options can be included to make it so more the mod are usable in a more challenging settings or modpacks.

**Comment by PrinceOfAmber** [comment]
My goal is to make everything controllable in config, and if somethings missing ill add it.

In this case if you search for " netherorecustom " in config file, you will see the following



`.
# Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountGold=8

    # Chance of a vein to spawn.  Zero means no spawns. [range: 0 ~ 100, default: 45]
            I:spawnChanceGold=45
`


Now in hindsight, when looking at this I could probably reduce the DEFAULT of 45.  My thinking originally was that, well it only drops nuggets.  And when I watch players or streamers use this mod, it usually gets ignored.  But I guess you can process the silk touched ore, or use fortune.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
