### ISSUE TITLE
Bug/Mod incompatibility?

### ISSUE THREAD

**Issue by Nexusdog** [PrinceOfAmber/Cyclic#663]
MC/F 1.12.2/2607

1.11.1 seems to be disagreeing with inventory tweaks - I have this bug which prevents me from shift clicking items from inventory or hotbar, but only certain slots; slot 7 on hotbar. I also cannot shift click some items from the extended inventory into regular inventory - again this is weirdly erratic, inconsistent.

I've rolled back to version 1.11.0 and so far, things are behaving normally again.

Not sure what other information I can provide, sorry.

**Comment by PrinceOfAmber** [comment]
Hmm I will look into it, there were a bunch of small changes in that latest version

**Comment by PrinceOfAmber** [comment]
Updated this in latest version https://minecraft.curseforge.com/projects/cyclic/files/2527760
