### ISSUE TITLE
Using Almanac causes crash; CME in EntityTracker

### ISSUE THREAD

**Issue by OrdinatorStouff** [PrinceOfAmber/Cyclic#664]
Forge: `forge-1.12.2-14.23.1.2587-universal.jar`
Cyclic: `Cyclic-1.12.2-1.10.11.jar`
ATM3 (Official Server) running pack ver 5.7b 

Partial duplicate report of https://github.com/PrinceOfAmber/Cyclic/issues/497 -- that issue might have originally been related to the screen events but a new/different crash is happening now. Two users have added new crashlogs on that issue that match what I'm seeing and can reproduce on our server.

Player uses Cyclic's Merchant Almanac to "spam" trades in a rapid manner and after a few trades the server crashes with a CME in EntityTracker. 

My armchair-mod-dev spidey-senses wonder if this is maybe a problem in vanilla minecraft but not detectable because in the vanilla villager trade interface it would be almost impossible to "spam" trades fast enough to have them in quick-enough succession to trigger the CME.

[Crash Log](https://gist.github.com/OrdinatorStouff/76ae4ef4937acc419ab090dac9cbff17#file-crash-2018-01-31_15-58-08-server-txt)

**Comment by PrinceOfAmber** [comment]
I replicated this once but I am at a loss of how to fix it exactly.   

I have had one  ConcurrentModificationException in the past, but that was because of editing multiple blocks at once in the main thread so the solution does not apply here.

It might e related to it trying to updating the buttons, or it might be syncing the tradelist from server to client, but those are guesses.

**Comment by OrdinatorStouff** [comment]
I believe the same kind of crash can be reproduced using a Pam's Harvestcraft "market" that exchanges emeralds for seeds and spawn eggs and such. The link of emeralds being involved in both might just be anecdotal only but perhaps there are some similarities in each codebase that can be compared for hints to a root cause? I know code from one mod to the next is sometimes "apples to oranges" but maybe it's worth a peek? I'm not sure how else to help-- if you think of anything let me know.

**Comment by PrinceOfAmber** [comment]
Trade source 

https://github.com/PrinceOfAmber/Cyclic/blob/04b525a5ba3a52c86a2f4750f717730e178ecae5/src/main/java/com/lothrazar/cyclicmagic/component/merchant/ContainerMerchantBetter.java#L116

Called from this packet 
https://github.com/PrinceOfAmber/Cyclic/blob/343ec58c8076de57679985081b880b83d3a257de/src/main/java/com/lothrazar/cyclicmagic/component/merchant/PacketVillagerTrade.java#L45

As shown i did in the past try to add a DUPE_BLOCKER flag to prevent spam clicking (ages ago).  Seems like this does not work 100%.  

Bug hard to replicate in current version, i got a bunch of gold iron and coal and went through lots of blacksmith trades and hasnt happened yet today, must be infrequent.  

Thanks for tip i will look at the market code.  For now ill mark as 'stuck' so i dont forget

**Comment by PrinceOfAmber** [comment]
Doing cleanup and i fixed something small in the GUI container for this, i had one method duplicated and it was sending the wrong inventory and sometimes logging NPE errors without affecting gameplay.  Maybe fixes it? Maybe not? 

I can still hardly ever replicate this though so not sure.  Ill still leave issue open tho.   https://github.com/PrinceOfAmber/Cyclic/commit/18027704890d88b0ac6447fda9b9016eb5d5d243

**Comment by PrinceOfAmber** [comment]
Ive been using this a lot in my own gameplay with no issues.  

Closing this ONLY because its stale, and because i cant replicate personally.

if it happens more in newer versions feel free to reopen with any relevant logs/info
