### ISSUE TITLE
Wrong Russian Localization

### ISSUE THREAD

**Issue by TimeConqueror** [PrinceOfAmber/Cyclic#665]
I saw, that you added Russian Localization to your project. But it is very and very raw. I'm sure that all strings were translated, using Google Translator and nothing more. Names and descriptions are mispresented to the extent that players cannot understand the right meaning.
These mistakes were made in almost every line. For example: (If you translate this back to English variant)
- entity.cyclicmagic.turretminecart.name=Вагонетка с башней -> Minecart with *tower*
- item.food_step.tooltip=Съешьте, чтобы увеличить высоту Вашего шага к полному блоку как лошадь -> Eating increases your step height, and block is like horse... - What???
- tile.block_fishing.guide=... Рыбы быстрее, больше сторон покрыты водой, минимум 4 из 6. Затем дать ему удочку и рыбы для вас. Он использует все, что находится в рыбалку бабло таблицы -> (It is very funny) ... Fishes become faster, more sides will be covered in water, minimum 4 of 6. Then (smb) give him the fishing rod and fishes, for you. It uses whatever is the fishing process and spreadsheet of money (WHAT???)

Due to these mistakes the discription of every item turns into drivel. :/

**Comment by PrinceOfAmber** [comment]
Yeah I have no ability to proofread these translations, I just take what is given and had to trust it.

Source was https://github.com/kellixon/Cyclic/commit/d5072f3a17720810414d7b6d6b72267d345373c8

I will happily take any corrections or updates to the file.  I will link the main below copy for convenience.

https://raw.githubusercontent.com/PrinceOfAmber/Cyclic/master/src/main/resources/assets/cyclicmagic/lang/ru_RU.lang

**Comment by PrinceOfAmber** [comment]
@TimeConqueror  feel free to submit corrections to any translations you see and I can add them.

**Comment by TimeConqueror** [comment]
I'll put it in tab "Pull Request"

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
