### ISSUE TITLE
Cyclic items in JEI are unsorted

### ISSUE THREAD

**Issue by Hubry** [PrinceOfAmber/Cyclic#667]
Minecraft version & Mod Version: Minecraft 1.12.2, Cyclic 1.12.2-1.11.2, Forge 14.26.2.2611, JEI 4.8.0.111

Single player or Server: Singleplayer

Describe problem: Cyclic items in JEI are unsorted, this seems to be caused by JEI using the registration order (which seems random in your mod) and not the creative tab (which you sort manually). From quick googling, HashMap (which you are using) doesn't preserve insertion order, LinkedHashMap or just a List with items would be a good alternative.

A small sample of the JEI display on searching `@Cyclic`:
![Screenshot](https://user-images.githubusercontent.com/26120076/35773190-3d74d31e-094b-11e8-9efb-13a820c652aa.png)

**Comment by PrinceOfAmber** [comment]
Yeah thats a mess. somehow. Ideally it would look like the vanilla Creative tab, which is sorted nicely

**Comment by PrinceOfAmber** [comment]
Previously I was using a HashMap (unsorted), changed to using ArrayList (preserves order that i add)

Next update it will look like:

![new sort](https://user-images.githubusercontent.com/621529/36633834-b43147a2-1950-11e8-95dd-2f123654baf5.PNG)

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2534743
