### ISSUE TITLE
[1.12.2] Brush Scythe picks up the Windy Gardens instead of breaking them

### ISSUE THREAD

**Issue by FnordMan** [PrinceOfAmber/Cyclic#668]
Talking about the Windy Garden from Pam's Harvestcraft
Namely, it doesn't break it and give you the various drops like it should. One gets the the actual Windy Garden item, almost like a silk touch thing.

**Comment by PrinceOfAmber** [comment]
I see so it needs to break and get drops.  Thanks good find!
