### ISSUE TITLE
Garden Scythe-Cocoa Beans Bug

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#67]
Cocoa beans get placed in the wrong direction when harvested with the scythe.

**Comment by PrinceOfAmber** [comment]
Confirmed.. fix coming

**Comment by WenXin20** [comment]
Thanks

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2321903
