### ISSUE TITLE
floating spikes

### ISSUE THREAD

**Issue by tigerdan2** [PrinceOfAmber/Cyclic#670]
1.12.2 Cyclic-1.12.2-1.11.2

SP

If you move a spike with a piston into a powered block (like a redstone block) the spike is going to float and not drop
Video of me doing the glitch
https://streamable.com/atl89

**Comment by PrinceOfAmber** [comment]
Yep, it wasn't checking the right side when looking at if it can stay.

**Comment by PrinceOfAmber** [comment]
Resolved in https://minecraft.curseforge.com/projects/cyclic/files/2530166
