### ISSUE TITLE
{Issue] Wireless Readstone Drops on Break

### ISSUE THREAD

**Issue by DigitalSketch** [PrinceOfAmber/Cyclic#671]
Minecraft version & Mod Version: 
MC 1.12.2, Cyclic 1.11.2 (Latest Release)

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Breaking a wireless transmitter drops 2 transmitters, and breaking a wireless receiver drops nothing.

**Comment by PrinceOfAmber** [comment]
Resolved in https://minecraft.curseforge.com/projects/cyclic/files/2530166
