### ISSUE TITLE
Wireless Receiver

### ISSUE THREAD

**Issue by vampire369** [PrinceOfAmber/Cyclic#672]
Minecraft version & Mod Version:
v1.12.2 & Cyclic-1.12.2-1.11.1, modpack: Forever+Stranded+Lost+Souls-1.0.3.5-B3

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Broke a wireless receiver with a tinker's construct pickaxe, and the block disappeared.

**Comment by Jandakast** [comment]
Breaking the Redstone Receiver block with any pick is still destroying the block in Cyclic 1.15.3 Beta.

**Comment by PrinceOfAmber** [comment]
re-fix https://minecraft.curseforge.com/projects/cyclic/files/2564637
