### ISSUE TITLE
Enchanter consumes tools

### ISSUE THREAD

**Issue by TyreForHyre** [PrinceOfAmber/Cyclic#676]
Minecraft version & Mod Version: 1.12.2, Cyclic 1.11.2

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Enchanter will simply consume tools rather than... Well, enchanting them. Also still consumes power and liquid xp. Works fine on books though.

Crash log (if any): N/A FML log if needed: https://pastebin.com/2NR305e3

**Comment by PrinceOfAmber** [comment]
Oh man when did that happen.  Yeah you are right, it works fine on books but not on tools.  Working on it.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
