### ISSUE TITLE
Spawner Seeker: Does not seek closets spawner if there are multiple

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#678]
Minecraft version & Mod Version: 1.12.0

Single player or Server: Both

Describe problem (what you were doing / what happened):

Put out a few spawners on the ground.

Use Spawner Seeker.

Expected result: It always targets the one closest to player, and seeks out that.

Actual result: It always seeks out the same one, and not always closest.  Seems like its just the first one found while scanning; first one from arbitrary list.

**Comment by LegacyGaming** [comment]
The spawner seeker in Sevtech Ages 3.0.8 does not move anywhere to seek spawners and leaves orb (eye) floating in the world where its used and you cannot get rid of it. Any fix for this? cannot find one so far.
