### ISSUE TITLE
Baubles can't be turned off, despite tooltip.

### ISSUE THREAD

**Issue by TherminatorX** [PrinceOfAmber/Cyclic#679]
Minecraft version & Mod Version:
1.12.2 & 1.11.2

Single player or Server:
Singleplayer

Describe problem (what you were doing / what happened):
Items listed as a Bauble/togglable with right click cannot actually be turned off
This causes constant loss of durability on certain items, and have to be put in a separate inventory to not apply their effects. Originally discovered with the Climbing Glove.

**Comment by PrinceOfAmber** [comment]
What inventory screen do you have open when you right click? Is it in a hotbar, a chest, or equipped?  I remember one time they refused to work in the creative inventory screen, but in survival inventory and baubles screen they worked fine.

**Comment by PrinceOfAmber** [comment]
![toggle](https://user-images.githubusercontent.com/621529/36193235-e74fc012-1119-11e8-8a87-717930520dae.gif)

**Comment by TherminatorX** [comment]
...well then. This explains how you're supposed to toggle effects with the bed mat.

I have honestly never seen a mod use that approach. I was trying to right click it in my hand, hoping for on-demand toggling. Could I perhaps suggest adding "in inventory" to the tooltip to make it more clear, or adding that functionality to items that don't have a right click behavior?

**Comment by PrinceOfAmber** [comment]
Yeah I should do something.  The tooltip text is already getting long, maybe i can put it in the guide text, meaning the blue (i) tab in jei theres more room.

**Comment by TherminatorX** [comment]
That'd probably be a good spot for the text to go, just having Activated/Deactivated on the item itself. Could be easier to explain mechanics there as well. Dunno if you'd want a "see JEI" on it or not, up to you.

**Comment by TyreForHyre** [comment]
Yeah it seems these items simply can't be turned off/on in creative mode is also a source of confusion when first encountering this mechanic.

**Comment by PrinceOfAmber** [comment]
I will take another look to see if i can fix the creative issue.  Or maybe it was a forge bug with the events, the numbers are all wrong

....  Last time I checked, the click event was giving "you clicked slot 7" but actually slot 7 was empty and the buable was in slot 20.   But only in creative mode.

**Comment by PrinceOfAmber** [comment]
Just tested, and yeah creative issue still persists.

To be specific, its only the creative view with all the tabs on top and bottom. On that invenotyr the click event always says "yep you sure did click slot zero  (gui.getSlotUnderMouse().slotNumber always zero).  So thats a #blameforge thing

So actually, if you are in creative and click B for baubles invo screen it works fine there.


I will update the ".guide" text to be more clear about click event (this text shows up both in JEI blue info tab, and the guidebook)

**Comment by PrinceOfAmber** [comment]
Updated documentation https://minecraft.curseforge.com/projects/cyclic/files/2534743
