### ISSUE TITLE
[Mod Conflicts] Not able to craft Pattern in TC Stencil Table

### ISSUE THREAD

**Issue by jokish63** [PrinceOfAmber/Cyclic#68]
Can not Patterns crafting in Stencil Table from Tinkers Construct
This behavior began with version 1.4.4. from the Cyclic mod
no Crash.
Forge 2046 - TConstruct-1.10.2-2.4.0.jenkins312 - Mantle-1.10.2-0.10.4.jar

**Comment by PrinceOfAmber** [comment]
hmm, thats weird.  im not removing any recipes on purpose, in fact i dont even use tinkers construct.  

Ill install them and see what i can see

**Comment by papa3boyz** [comment]
Also Refined Storage solderer stop working when i install this mod, please fix. TQ

**Comment by PrinceOfAmber** [comment]
going to do a release that i have waiting for different issues, then ill look into mod conflicts with version 1.5 and see what i can see. Sorry if it wont be fast.

**Comment by PrinceOfAmber** [comment]
Im still trying to figure out why this is happening.  I just tested it: TConstruct-1.10-2.3.3a by itself: stencils work fine.  but TConstruct plus Cyclic 1.5.1 dont work and havent found out why yet, so weird. Hopefully i can figure it out this weekend

**Comment by PrinceOfAmber** [comment]
Found a fix.  So with latest tinkers, and Cyclic 1.5.2, i am able to create patterns no problem.
https://minecraft.curseforge.com/projects/cyclic/files/2322841

 Sorry about that.  If any other mods have conflicts , report away!

**Comment by papa3boyz** [comment]
Great jobs! TQVM 4 de updates... :P
