### ISSUE TITLE
cyclicmagic.fake_player.sapling_regrowth wakes up Weirding Gadget chunk loader

### ISSUE THREAD

**Issue by Aphyxia** [PrinceOfAmber/Cyclic#680]
Minecraft version & Mod Version:
Forge 2615
1.12.2
Cyclic-1.12.2-1.11.2
Latest Weirding Gadget

Single player or Server:
Server

Cyclic cyclicmagic.fake_player.sapling_regrowth triggers Weirding Gadget chunk loader. Excerpt from log:
`[10:36:09] [Server thread/INFO] [weirdinggadget]: Waking up Chunk Loader at BlockPos{x=2577, y=66, z=1175} because cyclicmagic.fake_player.sapling_regrowth placed/interacted with it`

**Comment by PrinceOfAmber** [comment]
Yeah this should not be happening if the config "Plant Despawning Saplings"= false is set. which is the default.   So ill have to look into this.

**Comment by Aphyxia** [comment]
Well I have it set to true but regardless, it should not wake up chunk loaders I think.

**Comment by PrinceOfAmber** [comment]
For some dumb reason i did this with a fake player?  which is totally not needed.  So yeah ill just make it work without a fake player and that will fix it I bet

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
