### ISSUE TITLE
Nether/End Ore blocks vs generation

### ISSUE THREAD

**Issue by IMarvinTPA** [PrinceOfAmber/Cyclic#681]
Minecraft version & Mod Version: 1.12.2  and 1.11.2

Single player or Server:  Single

Describe problem (what you were doing / what happened):
I disabled Nether and End ore spawn and the blocks were removed from the game..

Crash log (if any):  None

Make an option to keep the ore blocks, just disable the ore gen.  I am using COFH World for all of my ore gen and would like to use the ores from this mod for Netherack/endstone places.

Thanks,
IMarv

**Comment by PrinceOfAmber** [comment]
Oh I see what you mean, thats a good idea.  

Ok ill add a new flag to allow you to "enable" the ore block as true or false, so that way if its 'true' but the spawn count is zero then the block still exists for other worldgen.

**Comment by PrinceOfAmber** [comment]
Update: turns out there is already a way to do this in config file.

So if you set "Nether Ore"=false , then yes it totally removes the blocks.


However, if you leave "Nether Ore"=true, you can still disable the world gen using the blockCount___ = 0. For example

`        netherorecustom {
            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountCoal=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountDiamond=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountEmerald=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountGold=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountIron=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountLapis=0

            # Approximate ore vein size.  Zero means no spawns. [range: 0 ~ 32, default: 8]
            I:blockCountRedstone=0`

**Comment by IMarvinTPA** [comment]
Excellent! 
Sorry for my derp.
