### ISSUE TITLE
Pattern Replicator is not placing redstone dust.

### ISSUE THREAD

**Issue by IMarvinTPA** [PrinceOfAmber/Cyclic#682]
Minecraft version & Mod Version:  1.12.2 and 1.12.0

Single player or Server:   Single

Describe problem (what you were doing / what happened):  Using the Pattern Replicator to copy Compact Machine recipes.  There is placed redstone dust in the pattern.  The replicator is not placing it.

Crash log (if any):  None

**Comment by PrinceOfAmber** [comment]
Fixed it for redstone dust, repeaters, comparitors.

Anything else you know of thats affecting this?

**Comment by IMarvinTPA** [comment]
Not that I know of.
Thank you!

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438

**Comment by IMarvinTPA** [comment]
If the redstone dust is on top of another layer in the copy zone, the random order it places blocks may result in the dust being placed in mid-air, dropping the dust.  It either needs to detect that a block is below the dust or have an option to always build bottom to top.

Thanks,
IMarv
