### ISSUE TITLE
Pattern Replicator Ignores Rotational/Flip Input

### ISSUE THREAD

**Issue by SerrpentDagger** [PrinceOfAmber/Cyclic#683]
Minecraft version & Mod Version:
1.12.2

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I was trying to copy the wall of a circular room, and got the _preview_ of the copy to line up with what I wanted, but when I turned the replicator on, it built as if the rotation or flip (I tried both) was not engaged. I did more testing with a smaller scale object (a 9x1x9 area with 4 distinct blocks in the corners), and got the same results.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
