### ISSUE TITLE
Particles shown for all clients, not just nearby ones

### ISSUE THREAD

**Issue by thraaawn** [PrinceOfAmber/Cyclic#684]
***Minecraft version & Mod Version:***
1.12.2, don't know, seen on stream

***Single player or Server:***
Single player

***Describe problem (what you were doing / what happened):***
Chunkloaded machines generate particles for clients no matter what dimension they are in.
Reproduce by playing a particle generating block in the overworld and go to the nether to a nearby position. You can see the particles.

***Bug is probably here:***
https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/util/UtilParticle.java#L78

Sending this message to all clients causes particles to show up even if no players are nearby. (Well, they are nearby in another dimension).
You can switch to the nearby player aware version of the send method.

**Comment by PrinceOfAmber** [comment]
Wow good catch! And thanks for digging into the code too!

**Comment by PrinceOfAmber** [comment]
I guess it needs to be "sendToAllAround"

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2531438
