### ISSUE TITLE
[1.12.2]  Add Config Option for No Guide Book on World Start

### ISSUE THREAD

**Issue by MokahTGS** [PrinceOfAmber/Cyclic#687]
Can you please add an option in the config for turning off the giving of the guide book when a player first spawns?  I know there are mods for controlling starting inventory, but I should be able to do that via your config for your mod items.

**Comment by PrinceOfAmber** [comment]
This is out of my control but also already implemented.  If you go int oconfig/Guide-API folder  you can turn it on or off, it will look like this

`# Configuration file

##########################################################################################################
# books
#--------------------------------------------------------------------------------------------------------#
# All settings related to Books.
##########################################################################################################

books {
    # Allows books to spawn with new players.
    # This is a global override for all books. [default: true]
    B:canSpawnWithBooks=true

    ##########################################################################################################
    # spawn
    #--------------------------------------------------------------------------------------------------------#
    # If true, the user will spawn with the book.
    # This defaults to the value the book owner has set and is overridden by this config.
    ##########################################################################################################

    spawn {
        B:"cyclicmagic:guide"=true
    }

}


##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# Miscellaneous settings.
##########################################################################################################

general {
    # Enables extra information being printed to the console. [default: true]
    B:enableLogging=true
}


`
