### ISSUE TITLE
[Harvester Enhancement Suggestion]

### ISSUE THREAD

**Issue by Morpheus1101** [PrinceOfAmber/Cyclic#688]
Currently on the server i play i myself and others have encountered the situation, that once the harvester is harvesting more then you can pull out, it simply spits the items out of the top of the machine.  The issue we've found is that if its harvesting something like magical crops for example and they have  the chunk loaded, the items just keep spitting out and eventually kills the servers tps, so my suggestion is to have it, so once the internal of the machine space for items is full, that it simply stops harvesting rather then continuing to harvest spitting items out the top of the machine.

**Comment by PrinceOfAmber** [comment]
Yeah thats a good change. ill make it just always stop if its full.  

At worst case, if it has one slot open slots and it grabs two items at once, it will have to drop the second one. but then the next cycle it will be halted.

**Comment by PrinceOfAmber** [comment]
Another edge case: every slot is at 64 except the last 2: one has a single seed, one has a single crop.  

With the new changes, in this edge case it will keep harvesting and putting crops in the machine and dropping seeds on the ground.. untill the crop stack is full and then it will finally halt.   ( When halted it will no longer use fuel or affect any crops )

**Comment by PrinceOfAmber** [comment]
https://i.imgur.com/89kgO2J.gifv

**Comment by PrinceOfAmber** [comment]
Added https://minecraft.curseforge.com/projects/cyclic/files/2533149

**Comment by Morpheus1101** [comment]
This incident is still occurring using v1.12.1

**Comment by Morpheus1101** [comment]
This incident is still occurring using v1.13.5//1.14.3
