### ISSUE TITLE
Inventory Crafting & JEI

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#69]
The plus button when viewing a recipe doesn't input the ingredients into the crafting grid.

**Comment by PrinceOfAmber** [comment]
Yep, i just saw this happen.  

Well, if you shift click the output slot, the crafting does actually occur.  But for some reason they are invisible. Ill see if theres anything i can do

**Comment by WenXin20** [comment]
Thanks

**Comment by PrinceOfAmber** [comment]
Ill try to make sure this gets fixed now, shouldnt have closed it. Related to #107

**Comment by PrinceOfAmber** [comment]
I had to rebuild this screen, but now it has full working JEI support and more features . download and screenshot at https://minecraft.curseforge.com/projects/cyclic/files/2333207

**Comment by WenXin20** [comment]
Thanks
