### ISSUE TITLE
Client side feature request for turning off sprinklers water particles.

### ISSUE THREAD

**Issue by ProxyNeko** [PrinceOfAmber/Cyclic#690]
Would you mind adding in a client-side config option that allows the player when in the game to turn off the water particles that the sprinklers add to reduce the effect on their fps for users with a lower end PC?

The main reason for this request is a lot of players I've seen use these sprinklers and some of them have to hide the farms because it kills the fps when they have them all around the farm in an attempt to boost the growth for with the harvester.

**Comment by PrinceOfAmber** [comment]
Good idea to have a way to turn them off. 

I think a more intuitive way for player to do this is a simple right click (possibly sneak right click) on the block to toggle particles. (and display message accordingly).  Also then you can configure per block .

**Comment by PrinceOfAmber** [comment]
https://i.imgur.com/89kgO2J.gifv

**Comment by ProxyNeko** [comment]
Thanks for the quick addition! :D

**Comment by PrinceOfAmber** [comment]
Added https://minecraft.curseforge.com/projects/cyclic/files/2533149

**Comment by ProxyNeko** [comment]
Thanking you :D
