### ISSUE TITLE
Pipes rendering connection to side of extractors

### ISSUE THREAD

**Issue by FinalMiner** [PrinceOfAmber/Cyclic#692]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic-1.12.2-1.12.2TEST (from GitHub on Feb 18, 2018)
Forge 14.23.1.2594

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Pipes are rendering as connecting to the side of extractors when placed adjacent to them, however extractors do not render as connecting to their "sides" (right angles from the block they are extracting from), and do not provide service to pipes there.

Crash log (if any):
none

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2533149
