### ISSUE TITLE
Item pipes not properly inserting into machines

### ISSUE THREAD

**Issue by FinalMiner** [PrinceOfAmber/Cyclic#693]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic-1.12.2-1.12.2TEST
Forge 14.23.1.2594

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Item pipes not properly distributing to connected machines.
I created a pillar of peat engines on top of each other, then connected item pipes down the side, and finally connected an extractor at the bottom to a chest filled with peat fuel. (I triple-checked to make sure it was the correct version of peat, not the soaked peat.) At first the extractor pulled several stacks and inserted into some of the machines. However, some machines never got inserted into, and those that did, did not get replenished when they ran out. I right-clicked the pipes themselves to track the items moving inside, and was told that the items were indeed moving there. When I placed a chest at the bottom pipe so that it would attach, the items emptied from the pipes immediately.

Similar:
I had a pillar of peat farms, with pipes connected to the side, feeding them bog earth. The bottom farm (closest to the extractor and on the same Y level) was completely filled with bog earth. The 8 above it, however, were only given 4 stacks each. As soon as any of these farms used a block of bog earth, it was replaced, so that their stock was constantly maintained (in those 4 slots).

Crash log (if any):
none

**Comment by PrinceOfAmber** [comment]
Yeah it seems like for simple networks its fine, when its more complex things are looping back and forth and getting lost.

**Comment by TyreForHyre** [comment]
Actually Peat-fired Generators simply won't accept anything into their inventory. Even vanilla hoppers don't seem to do anything.

**Comment by PrinceOfAmber** [comment]
After the previous fix i made a stack to mimic this. 

https://imgur.com/a/TG4rp

By design, when an item gets to a pipe intersection, it picks a random unused direction.  So in the video there, the one in the middle where the first pipes comes in gets favored, it gets more, since 1/3 of the options go right in. and its less as it gets farther away.  Ill keep this open for now but it seems ok, ill jsut do more testing and research

**Comment by PrinceOfAmber** [comment]
Testing with some more complex networks with loops and dead ends to see if anything gets locked up.


![2018-02-23_20 11 42](https://user-images.githubusercontent.com/621529/36625519-d6ce8688-18d5-11e8-921c-3ee577708af2.png)

**Comment by FinalMiner** [comment]
DM me on twitter if you want me to do some more testing.

**Comment by PrinceOfAmber** [comment]
Issue is stale, i think some of the undocumented fixes I added in have improved things a ton i just never looped them back to this issue.  Ive seen tons of sevtech streamers use them with no issue as well so ill close this for now :D:D:D <3
