### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#696]
Minecraft version & Mod Version:
1.12.2 minecraft 1.12.2-1.13.0 cyclic and before

Single player or Server:
single player

Describe problem (what you were doing / what happened):
ores in every dimention seem sparser then supposed to be

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

was wondering if cyclic changed ore spawn for overowrld and mining dimention and nether cause if not then i just have really bad luck with finding enough ores

**Comment by PrinceOfAmber** [comment]
It does add ore spawning to the end and the nether.  Only the new ores.  There are a few other small ore related features, but all can be turned off in the "world generation"config section

even those features dont block or remove any ores spawns .  

I dont know much about other mods or dimensions, sorry if i couldnt help.  Try posting on their forum pages 

:D best of luck
