### ISSUE TITLE
Extractors simply will not function on top/bottom of machines/storage

### ISSUE THREAD

**Issue by TyreForHyre** [PrinceOfAmber/Cyclic#698]
Minecraft version & Mod Version: 1.12.2 1.13.0

Single player or Server: Single player

Describe problem (what you were doing / what happened): as stated in the title: Extractors simply will not function on top/bottom of machines/storage. This includes chests, tanks, machines of all kinds. They function just fine on the sides and properly extract that way.

Crash log (if any): N/A

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2533820
