### ISSUE TITLE
[Suggestion] Toggle all Extractor's redstone control

### ISSUE THREAD

**Issue by TyreForHyre** [PrinceOfAmber/Cyclic#699]
Ability to toggle fluid and energy extractors to not require a redstone signal, in line with the item one. This would be especially useful when the block being extracted from is sensitive to redstone itself.

**Comment by PrinceOfAmber** [comment]
Yep this is a great addition.   Adding a screen with the standard redstone button and I will default them to Always On

**Comment by PrinceOfAmber** [comment]
LOL so this is out.  I was actually already working on this before you posted so your next suggestion probably wont be as quick 👍   

https://minecraft.curseforge.com/projects/cyclic/files/2533820
