### ISSUE TITLE
Precise dropper only drops from first slot in its inventory

### ISSUE THREAD

**Issue by darkphan** [PrinceOfAmber/Cyclic#701]
Minecraft version & Mod Version:

1.12.2, cyclic 1.13.1

Single player or Server: Only tested in single player at the moment

Describe problem (what you were doing / what happened):

Trying to drop an item down from the precise dropper

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2534743
