### ISSUE TITLE
Forester is not planting saplings When there is a roof above and not open to sky (it should ignore roof)

### ISSUE THREAD

**Issue by Cantose** [PrinceOfAmber/Cyclic#703]
Minecraft version & Mod Version:
1,12,2 & 1.12.1

Single player or Server:
Server - All the mods 3

Describe problem (what you were doing / what happened):
There are several issues with the forester.
1. It does not reliably plant saplings. 99% of the time I cannot get it to take saplings from it's inventory and place it. Very occasionally ... it will do it randomly. 

I have a small set up with Mekanism's logistics pipes, and thermal expansion RF.  The logistics pipes remove items from the item collector and disburse them to the correct machines as expected. The saplings enter into the forester and never get placed. If I stuff the device full of saplings, it will even take the slot meant to take the fuel to power the machine. It appears to cut everything down just fine. It just won't plant.

2. every time I enter the forester's GUI it reset's the power to 0 and forces it refill it's buffer. I have tried this with direct coal, or feeding it RF directly through Thermal Expansion. 

3. I have been unable to find a way to feed coal into the forester in an automated fashion. All attempts with hoppers and pipes push the coal/charcoal into the main inventory and not the fuel slot. (Though this may be intentional)

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Thanks for the detailed report.  Ill make new comment block for each one

1. It will only plant on blocks that accept a sapling as if from a player.  And only at the same y level as the harvester.  Ive added a GIF recording below of me using it.   Also you can turn on the preview mode and the particles track the foresters current pointer location

![saplings](https://user-images.githubusercontent.com/621529/36882077-a0a75c6e-1d86-11e8-82e4-86487b264ed0.gif)


If it still doesnt work
- are the dirt blocks or saplings you use from a mod?  Any other details that could help me debug?

**Comment by PrinceOfAmber** [comment]
2. [summary: possible mod compatibility RF bug]

 I will try those pipes later when i get a chance..  Its possible that maybe my machines are allowing pipes to "pull out" or extract energy , maybe they think im a battery, so if my guess is true then this is something i can fix. 

 I know that without any pipes it seems okay.
![saplingsfuel](https://user-images.githubusercontent.com/621529/36882167-0f6cc396-1d87-11e8-9d26-00002d486610.gif)

**Comment by PrinceOfAmber** [comment]
3. Yes this was intentional.  It was requested to remove this once RF energy capability was added.  So the fuel slot is kind of a legacy leftover, ok for early game but for full automation its expected just to use RF batteries or pipes.

((once Minecraft 1.13 exists and gets big,  i might remove fuel slots fully in that version, but im not decided for sure yet.))

**Comment by accessdenied0** [comment]
First, if it means any:
Great respect for this mod. You developed this mod to one of my favourite utilities mods. It contains alot of very creative and useful contraptions, I don't really wanna miss anymore.

Secondly, sadly:
I have the same issue and I have a guess why it maybe not work, correct me if I'm wrong:

But does it check for obstacles and counts roofs and torches to it and don't plant it?

[At least I got these Images to visualise it.](https://imgur.com/a/yZ9Zc)

It uses all his Power/Coal and does nothing but running checks.

I hope this was helpful.

**Comment by PrinceOfAmber** [comment]
Thanks for the screenshots.  Torches and light level should not affect things.   Your top screenshot it should work there, with that elevation.  https://i.imgur.com/krEj14h.png

I see you have oak saplings, and everything is enabled with redstone and energy.

Looks like theres a glass roof, which should be fine but ill test with that to be sure on my side .


@Cantose  or @accessdenied0  would it be possible to provide a full list of mods you have installed (or name of modpack if its premade)?  It must be 2 mods conflicting in some way, if it works for me in standalone form .

**Comment by PrinceOfAmber** [comment]
Update: nevermind , there is a bug in my mod that only happens when there is a roof above the forester. your screenshot helped me find that thanks @accessdenied0

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
