### ISSUE TITLE
Speed Charm with Mending doesn't get repaired

### ISSUE THREAD

**Issue by max17** [PrinceOfAmber/Cyclic#705]
Minecraft version & Mod Version: 1.12.2 forge-14.23.2.2618 & Cyclic-1.12.2-1.12.1 (Forever Stranded Lost Souls modpack)

Single player or Server: Multiplayer Server

Describe problem (what you were doing / what happened): Speed Charm doesn't get repaired by experience when enchanted with mending.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
So this works if im holding the charm in my hand, the mending repairs it.

![speed mending](https://user-images.githubusercontent.com/621529/36932310-2844c2a6-1e7c-11e8-8be5-2a4b548c8e60.gif)




If we want it to repair while equiped in the closed-away baubles inventory screen , that would have to be a new feature added to the baubles API. Not something i can do on my end. You could try requesing here https://github.com/Azanor/Baubles/issues


But hey, good news is you can just hold the Charm in your hand while getting an XP shower

**Comment by PrinceOfAmber** [comment]
Thanks for reporting BTW ❤️

**Comment by max17** [comment]
Oh, good to know! That was the only thing i didn't try! Anyway thanks to you for your hard work!
