### ISSUE TITLE
Crash with the User

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#707]
Minecraft version: 1.12.2
Mod Version: 1.13.2
Server
Describe problem :
![image](https://user-images.githubusercontent.com/26587049/36856100-3411e83c-1d43-11e8-82e7-f9f17bf41704.png)

Crash log (if any): https://hastebin.com/sajasawowo.pl

**Comment by PrinceOfAmber** [comment]
Looks like i have a compatibility issue, either with the latest forge (1.12.2-14.23.2.2623) or with one of the coremods.

**Comment by PrinceOfAmber** [comment]
Or possibly a bug that happens serverside only and not client

**Comment by Vyraal1** [comment]
https://hastebin.com/nekebinowi.pl

Here's another crash report (sorry if they are identical) however this time the situation was different. 
I'll make another issue but it also seems like the automated user dupes buckets.

https://streamable.com/eactx

The video below is the my modpack tester trying to simulate milking a cow (not sure why he decided to use a creative blood tank from Mekanism). He also reported that the Automatic User is _duping the buckets_ as well, as the entire system only started with 2 buckets - one in each user. The first user is milking the cow/blood tank with an empty bucket, and then pipes are transferring it to the storage tank.

**Comment by PrinceOfAmber** [comment]
I did a quick fix for the cow crash  https://minecraft.curseforge.com/projects/cyclic/files/2536608



 ill look into bucket issue next

**Comment by PrinceOfAmber** [comment]
I narrowed down the same bug to happen with only a hopper.

Start with two buckets, a fluid tank, and a hopper below.

Turn it on, now you have three buckets.

![bucket dup](https://user-images.githubusercontent.com/621529/36929530-bc581c3a-1e46-11e8-9fd3-a7f034871f0c.gif)

**Comment by PrinceOfAmber** [comment]
PS you guys are awesome.

Can you test ALL my content this thoroughly?  ❤️ ❤️ ❤️ ❤️

**Comment by PrinceOfAmber** [comment]
@Vyraal1  i made a special prerelease build for you , should fix button dupe.  

Please test if you have time.


. Real release in a few days maybe Sunday.  https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.13.4PRE

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2537511

**Comment by Vyraal1** [comment]
Hey, thanks for the update. We'll definitely be glad to be testing most of the content in Cyclic and ERZ(in fact that's the plan, we're trying to figure out where your items/mobs fit along in terms of progression in our pack). Also if it's not too much to ask, any update on the ERZ loottables? some of the fairies or pixies are dropping glowstone, and would like to alter them if possible. Thanks again for the update on this one
