### ISSUE TITLE
Cannot Disable Up and Down directions on Redstone Clock

### ISSUE THREAD

**Issue by BrisingrAerowing** [PrinceOfAmber/Cyclic#708]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.13.2

Single player or Server: SP

Describe problem (what you were doing / what happened):
I tried to disable the up and down directions on the Redstone Clock, and when I closed and reopened the GUI, they were re-enabled.

Crash log (if any): N/A

On a side note, this is a very useful mod.

**Comment by PrinceOfAmber** [comment]
If you leave the GUI, wait a minute, and then come back, do they stay disabled?  

Trying to pin down if this is a visual refresh, or data not saving.

**Comment by BrisingrAerowing** [comment]
I'll have to check. I just got a crash when mining Nether Redstone Ore (from this mod).

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2537511
