### ISSUE TITLE
Cyclic-1.10.2-1.5.3 cause Refined Storage Solderer stop working.

### ISSUE THREAD

**Issue by papa3boyz** [PrinceOfAmber/Cyclic#71]
Please fix/check this bug. Version Cyclic-1.10.2-1.5.2  working fine. TQ

**Comment by PrinceOfAmber** [comment]
Damn. I released 1.5.2 to fix this bug so i must have made a mistake somewhere, ill check it out right away

**Comment by PrinceOfAmber** [comment]
I just tested it, and it seems ok for me.  I will list some of the mods installed


Cyclic-1.10.2-1.5.3
MCMultiPart-1.2.1-universal
refinedstorage-0.8.20

Forge version 18.1.2046

Now the solderer did not work until I added a Controller attached to it, totally regardless of power.  In fact i tested the config file and set

 # The energy used by Solderers [range: 0 ~ 2147483647, default: 3]
    I:solderer=0

And even then, the solderer did not process at all UNTIL i added in the refined storage controller block.


The recipe i tested was silicon to printed silicon.

Please check your RF and your controller.  If it is still an issue, let me know what mods you have installed and what recipe you are testing and we can go from there

**Comment by PrinceOfAmber** [comment]
Thanks again for the report, but it works for me as noted so I will close this issue for now.  If it happens again please comment / reopen and post any details you have.  Its possible that some other 3rd mod is causing a problem for you, my tests were only with the two mods.

**Comment by papa3boyz** [comment]
Please tell me how to smelt your Nether Ore?  I using Allthemods modpack. TQ
