### ISSUE TITLE
Automatic Fishing Net doesn't catch anything when gamerule doDaylightCycle = false

### ISSUE THREAD

**Issue by dragon3025** [PrinceOfAmber/Cyclic#710]
Minecraft version & Mod Version:

- Minecraft Forge 14.23.2.2611
- Cyclic 1.13.3

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
I placed an Automatic Fishing Net in the water with a fishing rod and at first it was working fine. Later on it stopped worked, and it took me a long time, but I found out that reason is because doesn't work when gamerule doDaylightCycle = false.

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2537771
