### ISSUE TITLE
Crash Mining Nether Redstone Ore

### ISSUE THREAD

**Issue by BrisingrAerowing** [PrinceOfAmber/Cyclic#712]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.13.2

Single player or Server: SP

Describe problem (what you were doing / what happened): Tried mining Nether Redstone Ore

Crash log (if any): [Crash Log](https://gist.github.com/BrisingrAerowing/e9e5f4cd817b162de46b09d57e44b4e4)

Additional: I was in peaceful mode at the time.

**Comment by PrinceOfAmber** [comment]
Aha, yeah there is that feature where the ores try to spawn silverfish/endermines when mined (can be disabled in config)

Apparently in peaceful mode this caused an issue but thats a super quick fix

**Comment by PrinceOfAmber** [comment]
Updated https://minecraft.curseforge.com/projects/cyclic/files/2537511
