### ISSUE TITLE
[1.12.2] Model Loading Errors

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#715]
Minecraft version & Mod Version:
1.12.2
1.13.3

Single player or Server:
Single Player

Problem:
There are multiple model loading errors that occur on startup.
I'm not sure anything is actually breaking, but I certainly like to keep a clean logfile and this is an extra four hundred lines I could do without.

Error log:
https://gist.github.com/NotAVerb/89076568b80a9d67f37213d1f54af212

**Comment by PrinceOfAmber** [comment]
Yep, typos in some JSON files and some were just missing.

Forge is weird, the items looked and worked fine in the mod even with these errors.  Good to fix.

**Comment by NotAVerb** [comment]
There's also this in the latest 1.13.5 release
`[main/WARN] [cyclicmagic]: Mod cyclicmagic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.13.5`
and this in EmberRoot Zoo 1.3.5
`[main/WARN] [emberroot]: Mod emberroot is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.3.5`
I didn't think they were important enough to warrant their own issues.

**Comment by PrinceOfAmber** [comment]
version.properties file, never heard of it.  Supposedly this was the correct way for the longest time so i might look into that one day   https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/resources/mcmod.info#L7



anyway, mod is Updated https://minecraft.curseforge.com/projects/cyclic/files/2537771
