### ISSUE TITLE
[Suggestion] The Monster Ball should probably have a blacklist

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#717]
Personally I think the prospect of capturing and releasing something like an Ur-Ghast in a friends base is hilarious.
The hydra doesn't play nicely with the balls though, the body becomes unkillable once beheaded.
![2018-03-05_20 24 25](https://user-images.githubusercontent.com/30223331/37009457-f23af53a-20de-11e8-84c1-e15882edecd9.png)
![2018-03-05_20 36 03](https://user-images.githubusercontent.com/30223331/37009462-f69e08c4-20de-11e8-94e3-c8e2f9124851.png)

**Comment by PrinceOfAmber** [comment]
was added in 1.14.1
