### ISSUE TITLE
Better way to transport redstone signal, better logic gates, dice game....

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#719]
1. Do you saw a "Redstone Paste" mod? This mod allow to place redstone dust(and repeater, comparactor, etc) on walls and celling in any way. So I've think, that this solution can be welcome in here too.

Hmm... maybe energy cable could be able to transport a redstone signal too? The new "redstone transmitter" block(that I propose) could link a redstone dust with energy cable and has simple GUI to set a strength of signal passed from redstone dust to cable. This would be: signal strength as is, or refreshed to 15(like as repeater). Signal transmitted in energy cable would doesn't fade out until don't get end of cable.

2. Just one-halfblock logic gates in repeater style. AND, OR, XOR etc. 

3. Dice(k6) block. Block with random textured after placing. Just for some internal board games in MC world and for fun :)

------------------------------------
I still think that upgraded interdiction plate(teleport monsters away from range) would be great, same as block like "Alarmcraft mod". 

Anyway, I very liked this mod. I think, that it's "must have" in Minecraft :+1:

**Comment by PrinceOfAmber** [comment]
Hey thanks for youre patience on this, some good ideas.

1. Not sure if this is needed since I already have Wireless transmitter and receiver for redstone connections. ... however yeah, it does not transmit the signal strength, it starts over at full power.   Is this the one you are referencing?  https://minecraft.curseforge.com/projects/redstone-paste

2.  Im not a redstone expert, but this might be interesting.  I wonder how many 1.12 mods that have simple logic gates   like this? 

3. Sure dice dont sound too hard.

4. I think it makes more sensse to have an "alarm" block that simply plays a sound each time it gets a redstone signal, like a doorbel but on restone instead of user click.  That can be combined with an Entity Detector

**Comment by GrzechuGrek** [comment]
Ad. 1 
Yes, THIS mod. Do you tried it?

Ad. 2
Well, few weeks after create this thread I'd saw one... but I don't remember exactly its name now. Anyway this solution is comfortable, simples and save more space than in vanilla way.

Ad. 4
This SFX block, which you added, perfectly fulfills its task. 
But one question about this: How to best way to add own sounds do play?
Maybe will be good to add some possibility to set folder or zip file for search sound files?

-----------
Now, since this thread is still open, let me to add some ideas right here, for avoid doubled threads. I has some proposes again: 

5. You just mentioned about wireless transmitter blocks and I think about addressing possibility those. When right clicked on blocks(sender and receiver), then a gui appear where you can set 3(or 4) digit code. 
For example you did place many wireless blocks and set code "123" for two senders and five receivers. Now, when you will powered one of this sender blocks(with this code), then this block will transmit a redstone singall to all five receive blocks whose have set same code! Moreover, in sender block's gui would be a option(on/off) to set if strenght of redstone singal may saved before transfer or not.
This would be a really very usefull. 

6. Ok, there is a peat-fired generator. But presently(fixed plant pattern in hydrator) gathering certain plants for produce biomass can be a little/more troubled especially on some maps/worlds. I think that is good to have alternative for this. And then I propose simple thermal generator just fueled in same way like a furnance.
But of course, something for something: It's efficiency would will a lot less. Since peat-fired generator does generate 128 pow/t, then let thermal generator will does generate a 16/24/32 pow/t. Moreover if nessesary, this generator canbe to restrict to accepts only charcoal, coal and block of coal as fuel.

**Comment by PrinceOfAmber** [comment]
Textures are not done, need more work but i did the slingshot to use same logic as bow, it goes and looks for ammo in inventory (pebbles)  
![slingshot](https://user-images.githubusercontent.com/621529/40957985-65e6a45c-684c-11e8-8f56-b913724fe4d7.gif)

**Comment by GrzechuGrek** [comment]
Well, I like that stuff whose you added in last release(1.15.9). :)
This imbue station is great. Maybe this should work with slingshot too(eventually with half efficiency), besides bow?

And rainbow cannon is cool too, altrough with somem minor issue as projectile blocking on grass and tall grass.
Anyway great work! 

I hope that you don't forget to consider what I'd post in above suggestions.
