### ISSUE TITLE
[1.12.2] Invisible Spirit Seeker projectiles

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#721]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.13.5

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
The spirit seeker projectiles seem to be invisible. Sometimes I'd see a flash of a blaze powder looking thing on my screen followed by nothing. The only indication generally that the stave had done anything was that surrounding mobs would occasionally flash red or keel over dead.

**Comment by PrinceOfAmber** [comment]
I dont remember this happening in dev, but yeah they are invisible in my world.  I have optifine running, maybe thats part of it?

I guess instead of doing standard particles i should so something custom.  (which reminds me, if particles are turned off that would also kill these)

**Comment by PrinceOfAmber** [comment]
This should use the same projectile rendering as the Duskflame Hex and other magic items,. so thanks this info helps me debug it

**Comment by PrinceOfAmber** [comment]
Coming soon.  Feedback is welcome

![homing](https://user-images.githubusercontent.com/621529/37507666-fce1d014-28ac-11e8-9778-02a02c2df584.gif)

**Comment by NotAVerb** [comment]
Personally, when it comes to color I'd expect the projectile to be a pale blue to match the scepter's color scheme. Purple's fine too, but I'd make it darker so that the palette harmonizes better with the staff's dark tip and the enchantment glow.

**Comment by PrinceOfAmber** [comment]
^^ yeah i agree in hindsight, old pink is a bit gawdy.  Fix is here for invisibility but ill leave issue open for now to recolor it https://minecraft.curseforge.com/projects/cyclic/files/2541669

**Comment by PrinceOfAmber** [comment]
first attempt 

![magic_missile](https://user-images.githubusercontent.com/621529/37563910-53793484-2a48-11e8-96af-60438c3341db.png)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
