### ISSUE TITLE
[1.12.2] Emerald Carrot is bugged

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#722]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.13.5

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
I was testing out the horse upgrade carrots and upon using the emerald carrot my horse died and was duplicated into two zombie horses. Using the carrot again (the emerald carrot wasn't consumed either) on one of the zombie horses killed the zombie horse and spawned two skeleton horses. Using the carrot again on one of the skeleton horses killed it and spawned two new horses of the same pattern as my original horse.
I believe Ember Root Zoo is involved. I'm off to test without it.

edit: The issue is present with no mods, save cyclic, installed

**Comment by PrinceOfAmber** [comment]
Yeah those are issues.

On top of fixing these im changing it to only change from Living horse -> Zombie.

Also it will remember the Owner and saddle, so you can still ride the zombie horse.

**Comment by PrinceOfAmber** [comment]
Fix is up https://minecraft.curseforge.com/projects/cyclic/files/2541330````
