### ISSUE TITLE
[Suggestion] 1.12.2 - Fluid Storage Tank - Voiding In-World

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#724]
Minecraft version: 1.12.2
Mod Version: 1.14.1

Would it be possible to have a way for players to void tanks in-game? Such as the ability to maybe right click the tank with a stick or shift+right click it and it will empty out the tank? Maybe even crafting the tank into itself as a way to empty it (however some modpack makers will remove the original recipe via CraftTweaker so this might get overlooked commonly).

**Comment by PrinceOfAmber** [comment]
I do have the Trash Void that deletes items and fluids.  So you could pump out of the tank into the void tank.

Would that work?

**Comment by PrinceOfAmber** [comment]
The way I understand the feature seems like overkill, and solutions in the previous comment accomplish the same result (easily emptying out the tank).  

Works as intended, but feedback was welcome as always 👍
