### ISSUE TITLE
[Likely Unintended Behaviour] Bouncy Potion Effect allows unbounded accelleration during Elytra Flight.

### ISSUE THREAD

**Issue by TeetoKaziim** [PrinceOfAmber/Cyclic#725]
Minecraft version & Mod Version:
Minecraft 1.12
Cyclic 1.14.1

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Flying with elytra while under the influence of a bouncy potion (or the bouncy potion effect of a player launcher) allows one to accellerate to absurd speeds, travelling thousands of blocks in seconds, faster than the game can load or generate terrain.

I thought the player launcher could serve as a handy replacement for fireworks. It exceeded both my expectations and the speed limit.

Even mere creative flight seems to allow one to accellerate in a very difficult to control fashion while under the effects of this potion.

Crash log (if any):
No crash!

Thanks for your time and consideration, and, what continues to be one of my favorite content mods of this era.

**Comment by PrinceOfAmber** [comment]
"what continues to be one of my favorite content mods of this era." Thank you! Literally nobody has ever said that before.


Yep i just did that too, went a few hundred blocks.  Its intended to keep horizontal momentum to simulate a bounce, so ill just disable it while ElytraFlying action is on

**Comment by PrinceOfAmber** [comment]
Fix is up https://minecraft.curseforge.com/projects/cyclic/files/2541330
