### ISSUE TITLE
[Suggestion] Config controls to slow down the cable's transfer rate

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#726]
The cables are so fast by default that transporting items via minecart is practically obsolete.
If a config to control cable speed is too much, I recommend toning down transfer speed to be akin to the rate of vanilla hoppers.

**Comment by PrinceOfAmber** [comment]
Good idea, speeds / capacity of cables should be in config ill add that for next release

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
