### ISSUE TITLE
[Suggestion] Custom projectile for two of the epic swords instead of potions

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#727]
Terraqueous causes splash potions to create glass shards upon being broken. The two potion swords are now infinite sources of glass. I don't like that.

This issue also pertains to Ember Root Zoo's potion creepers.

**Comment by PrinceOfAmber** [comment]
To be honest, i thought this was a great idea when I was getting started, but now that I'm in there and using it, not very useful actually.  Potions aren't the best.  Annoying when it happens by accident also.

Also, they fly up at a weird arc compared to throwing, same with ender pearl.  

Maybe it could have an inventory or some other way to stock whatever you wanted in there? 

For the glass shards, I don't know how to stop that, you might have to use the config file in Terraqueous to disable? 

For the short term, i might just add a config to disable the projectiles flat out, couldn't hurt.

**Comment by NotAVerb** [comment]
Terraqueous provides a boolean to control whether glass shards are dropped or not. 
However my desire to keep the shards is why I suggested the use of new projectiles. So that Terraqueous wouldn't trigger its drops upon glass bottle breakage.
In the mean time I'm simply limiting myself to the evasion blade.

By the way, since the sword abilities are bound to left click they conflict with the use of shields.

**Comment by PrinceOfAmber** [comment]
Yeah initially they were going to be 2 handed swords, but i didnt know how to implement that.

For now im adding a config so you can disable the projectile per sword.  Later ill look into customizing so its more than just a potion; i have some bigger plans anyway

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
