### ISSUE TITLE
Possible bug, Weird outcome of using Cyclic Harvester on Natura berry bushes.

### ISSUE THREAD

**Issue by Nightcaste** [PrinceOfAmber/Cyclic#729]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.13.6, Natura 4.3.2.42

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When the Cyclic Harvester harvests a Natura berry bush, the bush is reduced to the "just planted" size, and what shows up inside the harvester is another bush, instead of the berry.  

Crash log (if any):
No crashes, just... not what I expected the machine to do.

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Testing with this version https://minecraft.curseforge.com/projects/natura/files/2519128

**Comment by Nightcaste** [comment]
For the sake of completeness, here's my full setup.  I'm using a cyclic Redstone clock to turn the harvester on and off,  delay set to 3000, duration set to 100, just putting coal in the harvester fuel slot.

**Comment by PrinceOfAmber** [comment]
and it looks like there are 8 bushes in the mod.

Ill test with Barley and Cotton too, i think those are the only crops.

**Comment by Nightcaste** [comment]
I was using blueberry and blackberry.

What's interesting is the wildberry bushes from Rustic work just fine.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
