### ISSUE TITLE
[Bug] Stone Minecarts generate cobblestone

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#731]
Minecraft version & Mod Version:
1.12.2
V 1.14.2

Single player or Server:
Single Player

Problem:
Stone minecarts are placed into the world carrying cobblestone. Breaking the cart and placing it again generates another new block of cobblestone.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2541669
