### ISSUE TITLE
Crash connecting energy cables to RFtools Powercell

### ISSUE THREAD

**Issue by Beannsss** [PrinceOfAmber/Cyclic#733]
Minecraft version & Mod Version:
MC: 12.2.2
Cyclic: 1.14.2

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Connecting cyclic energy cables to an rftools  powercell on input mode causes crash.

Crash log (if any):  https://pastebin.com/VZsVbYa7

I'm hesitant to post this on rftools github since I'm unaware of any other cable doing this, but will do that if you find it's not on your end.

Also, not sure if intended or not, but peat generators don't export their energy by itself, a lot of cables won't take energy from them.

**Comment by PrinceOfAmber** [comment]
This appears to be an issue on RF tools side, but regardless i should be able to put in a safeguard.

And good idea on upgrading generator also.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
