### ISSUE TITLE
Precise Dropper not accepting Pipe/Hopper Input

### ISSUE THREAD

**Issue by Beannsss** [PrinceOfAmber/Cyclic#734]
Minecraft version & Mod Version:
MC: 12.2.2
Cyclic: 1.14.2

Single player or Server: Single Player

Describe problem (what you were doing / what happened):

Simply put, the precision dropper does not accept input from entities such as hoppers/pipes

Crash log (if any): N/A

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
