### ISSUE TITLE
[Bug]Autonomous User Block Bug

### ISSUE THREAD

**Issue by sandtechnology** [PrinceOfAmber/Cyclic#736]
Minecraft version & Mod Version:
Minecraft 1.12.2  Cyclic-1.12.2-1.14.3 Pixelmon-1.12.2-6.2.2(downloaded at https://www.reforged.gg/)

Single player or Server: 
Single player

Describe problem (what you were doing / what happened):
When I Use Autonomous User Block to automatic harvest Pixelmon mod's Apricorn Tree,the output doesn't have Apricorn instantly:
![2333](https://user-images.githubusercontent.com/20417547/37550236-c09934e4-29c4-11e8-8a95-9efd9af795a7.gif)
A few movements later:
![image](https://user-images.githubusercontent.com/20417547/37550402-97f1b7f2-29c7-11e8-934f-e804a00b89e6.png)

Crash log (if any):None

**Comment by PrinceOfAmber** [comment]
Does it work if you move to +1 setting? Do you have to click a certain part of the tree to harvest?  Also thanks for download link

**Comment by sandtechnology** [comment]
It doesn't work,Right-Click tree's every part will harvest apricorn when tree grown.

**Comment by PrinceOfAmber** [comment]
Releasing version 1.14.4 soon that has a fix for this.    If you want to also use bonemeal when harvesting, put bonemeal in a second user and put its speed a bit lower than the gathering one (does not have to be exact same numbers as the gif)

https://i.imgur.com/FzwqZjo.gifv

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
