### ISSUE TITLE
[Bug] Automated User Block unlimited ExpOrbs

### ISSUE THREAD

**Issue by MarvTekko** [PrinceOfAmber/Cyclic#738]
### Minecraft version & Mod Version: 
MC 1.12.2 
Cyclic-1.12.2-1.12.1

Modpack: All the Mods 3

### Single player or Server: 
Multiplayer Server

### Describe problem (what you were doing / what happened):

I use the block to right click Solidified Experience from Actually Additions.
I piped those items into it and disconnect all cables to it.
The block was filled with Solidified Experience and started to use them. After 63 items they will no longer be used up. The block still generates the Experience Orbs, but does not consume any more items.
This allows you to create infinite experience.

This is the status in which the block creates infinite experience.
![2018-03-17_13 07 39](https://user-images.githubusercontent.com/10160305/37555214-5bf8fbda-29e4-11e8-9a16-4eb58ce45447.png)

**Comment by MarvTekko** [comment]
Btw, you can also easily turn the block on and off via Redstone Input Settings.

**Comment by PrinceOfAmber** [comment]
Yep it leaves 1 remaining item and doesnt consume.  Very weird, when its something like Eggs, it does consume the last.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
