### ISSUE TITLE
Pharos beacon beam turns invisible when viewed at an upwards angle

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/Cyclic#739]
Minecraft version & Mod Version:
1.12.2
1.14.3

Single player or Server:
Single player

Problem:
The pharos beacon beam turns invisible if the player looks towards it at an upwards angle
![2018-03-17_20 35 36](https://user-images.githubusercontent.com/30223331/37561352-9318cbbc-2a44-11e8-95a0-0e3085a2d57b.png)
![2018-03-17_20 35 42](https://user-images.githubusercontent.com/30223331/37561353-98237bde-2a44-11e8-98d3-1843ac7b68f2.png)

**Comment by PrinceOfAmber** [comment]
I thought this sounded familiar, but apparently, I only fixed it for one and not the other!

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2542723
