### ISSUE TITLE
Item frame dont work with cyclic anymore

### ISSUE THREAD

**Issue by Fleymer** [PrinceOfAmber/Cyclic#744]
Minecraft version & Mod Version:
Cyclic-1.12.2-1.14.3

Single player or Server:
single Play

Describe problem (what you were doing / what happened):
If i put the mod Cyclic in FTB Pyramid Reborn the item frame dont work anymore.
I cant put any Item in it

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I dont know anything about the pack, but i downloaded it just now...  and item frames seem fine to me.  

![frame](https://user-images.githubusercontent.com/621529/37572177-8c7be93a-2ac4-11e8-9f6f-5d8b408d511b.gif)

**Comment by PrinceOfAmber** [comment]
Oh I just remembered, if you put an item frame on a chest or container, and you want to access it you probably have to turn this config option to False:  (cyclicmagic.cfg file)



```
        # Open chests (and other containers) by passing right through the attached signs, banners, and item frames [default: true]
        B:"Pass-Through Click"=true
```

**Comment by PrinceOfAmber** [comment]
closing issue: no updates, cannot replicate, & mod is not even in the pack anyway
