### ISSUE TITLE
Recipe conflict with Advanced Generators 

### ISSUE THREAD

**Issue by CommYutzy** [PrinceOfAmber/Cyclic#747]
The Control Circuit from Advanced Generators and Redstone Clock from Cyclic have the same recipe. Would it be possible to get an alternate recipe or other work around? Currently no one on my server can make anything useful in Advanced Generators without spawning in control circuits.

**Comment by PrinceOfAmber** [comment]
This can be changed with Craft tweaker, but regardless yeah i can change recipe

**Comment by iDarper** [comment]
Also: adding the norecipeconflict mod to packs helps avoid issues like this.  😀

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2543738
