### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#748]
Minecraft version & Mod Version:
1.12.2 1.12.2-1.14.3 

Single player or Server:
sinlge player

Describe problem (what you were doing / what happened):

was wondering y ores spawn that have absolutely 0 uses in the nether? certus ore thorium dilithium and such but checked JEI and they have no uses besides visual deco blocks cause not having the mods that normally add those installed
Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by CharCharthemonkey** [comment]
oh and this links sort of to #709

**Comment by PrinceOfAmber** [comment]
Yep thats why they default to turned off. So when you download the mod and run. they are automatically turned off.

So when you download and run the mod and dont change any configs, they dont exist.

Using the magic of ore dictionary, other mods can use these.

So if you have a mod that uses thorium, then you can enable this ore and it will be fully compatible.   You are correct with the 709 link.  I forget which one, but one of " Nuclearcraft, Industrialcraft, Tech Reborn, Mekanism, Applied Energistics, and Advanced Rocketry " probably uses thorium and certus and dilithium.

For example I know Mekanism uses Osmium, but not many other mods do.  So if you have mekanism, you can enable Osmium.  If you dont, you can set all Osmium to false and move on.

**Comment by CharCharthemonkey** [comment]
thats the thing by default they were turned on which is weird and im not 100% sure they are turned off unless im just a real big obilivous person lol but thank you

**Comment by PrinceOfAmber** [comment]
Oh sorry.

 i just tested now with latest 14.4 on curseforge (fresh install, deleted cyclic_ores.cfg) , and the ore does not exist, not showing in JEI, not spawning in nether.  So  Yes I think there might have been a bug in 14.1 or 14.2 where it defaulted to on, but at least we know its fixed.  So yeah, delete that file or set to false. 

Thanks for reporting !
