### ISSUE TITLE
Magnet enchant doesnt work while on armor

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#749]
Minecraft version & Mod Version:
1.12.2 / 1.14.4

Describe problem
I have magnet II on my leggings, but blocks and items do not get pulled towards me. Putting the enchant on a pickaxe works as expected. Am I doing something wrong?

**Comment by CharCharthemonkey** [comment]
im 20% sure it only is "supposed" to work on tools not armor tho using indutrial forgoing basically breaks enchants

**Comment by PrinceOfAmber** [comment]
Yes, the enchantment was initially set up for armor and tools

But I suppose since things are able to put it on armor, i can just make it work on armor :D

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2543738
