### ISSUE TITLE
Error Setting Reach - Client Freezing

### ISSUE THREAD

**Issue by Siriuo** [PrinceOfAmber/Cyclic#750]
Minecraft version & Mod Version: MC - 1.12.2 Cyclic - 1.12.2-1.14.4

Single player or Server: Client Error

Describe problem (what you were doing / what happened):

Client experiences freezing and client console repeats the following.
Error setting reach : net.minecraft.client.multiplayer.PlayerControllerMP cannot be cast to com.lothrazar.cyclicmagic.proxy.ClientProxy$ReachPlayerController

**Comment by PrinceOfAmber** [comment]
Error is from the Reach enchant trying and failing to update players reach distance.

**Comment by PrinceOfAmber** [comment]
Tested a fix on both client and server. seems ok, crossing my fingers

**Comment by Siriuo** [comment]
Thanks for the quick response :)

As soon as I see the release I will test and confirm if it resolves the issue for us.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2543738

If it happens again feel free to reopen this or make a new issue 👍
