### ISSUE TITLE
Dropper Crash

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#752]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic-1.12.2-1.14.2

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Crash occurred after placing a Cyclic Dropper.

Crash log (if any):
https://pastebin.com/i1uveSAX

Original report: https://github.com/NillerMedDild/Enigmatica2Expert/issues/17

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2543738
