### ISSUE TITLE
[Mod Compatibility]A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by sandtechnology** [PrinceOfAmber/Cyclic#756]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.14.6
Spongeforge-1.12.2-2655-7.1.0-BETA-3055
(https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)

Single player or Server:
Server

Describe problem (what you were doing / what happened):

When I use Ender book teleporting,I lost connection because "A fatal error has occurred, this connection is terminated"

Server log:
https://paste.ubuntu.com/p/8BfNymt3Bx/

**Comment by PrinceOfAmber** [comment]
Did you intend to close this issue or was that an accident? 


It looks like there might be an issue on my end here when i see the logs

`       at com.lothrazar.cyclicmagic.component.enderbook.ItemEnderBook.teleport(ItemEnderB
ook.java:153) ~[ItemEnderBook.class:?]
        at com.lothrazar.cyclicmagic.component.enderbook.PacketWarpButton.onMessage(Packet
WarpButton.java:53) ~[PacketWarpButton.class:?]
        at com.lothrazar.cyclicmagic.component.enderbook.PacketWarpButton.onMessage(Packet
WarpButton.java:34) ~[PacketWarpButton.class:?]`

**Comment by sandtechnology** [comment]
solved by enable this sponge setting:
```
        # If enabled, any request for a chunk not currently loaded will be denied (exceptions apply for things like world gen and player movement). 
        # Note: As this is an experimental setting for performance gain, if you encounter any issues then we recommend disabling it.
        deny-chunk-requests=true
```
