### ISSUE TITLE
Creative Tab Bug

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#758]
Minecraft version & Mod Version:
1.12.2

Single player or Server:
SP

Describe problem (what you were doing / what happened):
While looking through a crash report, I stumpled upon a minor bug in the Creative tab of Cyclic, thought I'd let you know :)

Crash log (if any):
[Paste of log](https://gist.github.com/NillerMedDild/7676cb5b697158a330fd94c34846e6c2)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2546192
