### ISSUE TITLE
[Crash] TESR render baked model exception

### ISSUE THREAD

**Issue by JayWood** [PrinceOfAmber/Cyclic#759]
**Minecraft version & Mod Version:**
* Minecraft Version 1.12.1
* Mod Version 1.14.5

> I do not have optifine or any shaders installed, I realize this issue is with rendering so that may be the first avenue explored. This is a regular install directly from the twitch launcher for AllTheMods 3 ( link to issue below ). 

**Single player or Server:**
* Server

Describe problem (what you were doing / what happened):
Upon loading into the server, I crash as soon as I login. I first reported a similar bug over at AllTheMods/ATM-3#469 but removing the block and restarting the server fixed that.

Ended up playing all day yesterday, no issues... However once I logged into the server today, I get the below issues.

Looks like it originates here: https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/block/base/BaseMachineTESR.java#L124 

Which stems from this commit - https://github.com/PrinceOfAmber/Cyclic/commit/6ffe6f449c89119ce4bcdf19da08e60f27eae9e3#diff-85725e042cb726a548f96aa0a6e2ca0c

**Crash log (if any):**
https://gist.github.com/JayWood/67e3cf3c7e40ab797a1f5c25f1e8f5f1

The crash log doesn't provide too much information, so reviewing latest.log I find **the actual bug**:
https://gist.github.com/JayWood/f9200a777c065c40dead2aed6512f989

This goes inline with the code/commits above. Considering the previous version of the pack was using 1.12.1, I can't begin to compare diffs, seems like a lot of stuff going on.

**Comment by PrinceOfAmber** [comment]
Thanks for the amazing detail. Commit you linked was attempt to fix the exact same issue.

It has transformed from being a simple Null pointer exception and now its a "java.lang.IllegalStateException: Already building!". 

Ill do some research for a real cause, if i dont find anything ill get a quick fix up at least.

**Comment by PrinceOfAmber** [comment]
Thanks for the amazing detail. Commit you linked was attempt to fix the exact same issue.
It has transformed from being a simple Null pointer exception and now its a "java.lang.IllegalStateException: Already building!".

I will respawn in kind with detail,  Source of exception is in vanilla minecraft code.  Somehow it is trying to double draw, or draw when its already drawing, so i just have to not do that.

`    if (this.isDrawing)
        {
            throw new IllegalStateException("Already building!");
        }
        else
        {
            this.isDrawing = true;
            this.reset();
            this.drawMode = glMode;
            this.vertexFormat = format;
            this.vertexFormatElement = format.getElement(this.vertexFormatIndex);
            this.noColor = false;
            this.byteBuffer.limit(this.byteBuffer.capacity());
        }`

**Comment by PrinceOfAmber** [comment]
Commit linked above looks like a bandaid, because it is.  But i cannot replicate issue before or after, however this does deal with the exception in the logs. at least a little bit.

As showin in the comments, if I had a "buffer.isdrawing()" get function, i could just check that and halt, but its private of course.

**Comment by PrinceOfAmber** [comment]
This should fix it, but im not 100% sure since this has come back around at different angles a few times now. 

If this or a similar crash happens again please reopen issue or make a new one

https://minecraft.curseforge.com/projects/cyclic/files/2546192
