### ISSUE TITLE
[Bug] Disabling registering of ore blocks still allows mod to generate them, but they're buggy.

### ISSUE THREAD

**Issue by TeetoKaziim** [PrinceOfAmber/Cyclic#761]
Minecraft version & Mod Version:
1.12.2 minecraft
1.14.6 cyclic

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
In the main cyclicmagic.cfg, if the config entries for
```
        # Generate ore in the end.
        B:"End Ore"=false
        # Generate ore in the nether.
        B:"Nether Ore"=false
```
are set to false, as seen here, but you do not change the ore generation parameters at all, the ores still generate, as missing textured blocks that have some problematic behaviours. (Waila crashes when you look at them, some of them generate as veins of ghost-blocks that pop into existence when you try to place a block in their place).

They're easiest to spot in-world in the end.

Unloading and reloading the area banishes them from existence, but, probably just don't want them generating if the blocks aren't registered.

Thanks for your time, and good luck!

**Comment by PrinceOfAmber** [comment]
Sorry about this, it was fixed in an old version but i must have missed something.  

Possibly the same bug or a new version of this has either come back or was never /really/ fixed https://github.com/PrinceOfAmber/Cyclic/issues/730

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2546192
