### ISSUE TITLE
Harvester machine not accepting coal from any sort of pipe or hopper

### ISSUE THREAD

**Issue by JohnnyDevo** [PrinceOfAmber/Cyclic#763]
Minecraft version & Mod Version:
Unsure of cyclic version, using the "All The Mods 3" modpack.

Single player or Server:
Server

Describe problem (what you were doing / what happened):
As title. There's not much to expand upon, other than saying I tried everything available in my base at the time. My Xnet network interfaces with the harvester properly to pull items out, but cannot put coal, coal blocks, charcoal, or charcoal blocks into the harvester. I also tried itemducts and servos, didn't work. I even put a hopper pointed into it, would not go in.

Crash log (if any): Does not crash game

**Comment by PrinceOfAmber** [comment]
Yes, this was on purpose when they were changed to accept RF power.  So any cable or generator that makes RF compatible energy can send it right in.

I should have removed the fuel slots to avoid this confusion, do you think maybe I still should?  

Thanks

**Comment by JohnnyDevo** [comment]
Hmm... I can agree that the fuel slots do add a bit of confusion. If you want it to still have early game non-RF usage, maybe make it so that right clicking the machine with a fuel source adds an appropiate amount of fuel and consumes the item? I don't know the feasibility of it.

I can say that one thing that contributed to the confusion, though, is that the forester block DOES accept coal from my xnet network, so I had felt there's a bit of inconsistency.
