### ISSUE TITLE
block reach bug

### ISSUE THREAD

**Issue by mattrix444** [PrinceOfAmber/Cyclic#764]
Minecraft version & Mod Version: 1.12.2-1.14.7

Single player or Server: single player

Describe problem (what you were doing / what happened): after enchanting a chest piece with block reach i am unable to mine anything at any distance at all. i have tried it with vanilla tools and blocks and modded ones also. removing the enchant returns everything to normal.

Crash log (if any): no crash

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by mattrix444** [comment]
just to add also what ever block i try to mine looks like it wants to mine as a little crack appears on the block but then thats it. it goes back to unbreakable

**Comment by PrinceOfAmber** [comment]
Do you have a list of mods or a modpack name / link you are playing in?  Issues like this can often be a mod conflict.

It works for me with the small number of mods I have installed so theres something else happening.

**Comment by mattrix444** [comment]
sorry the list is extensive :D yeah i am thinking it may be one of my mods messing with the enchants, i dont have any that alter reaching as far as i know.
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Baubles-1.12-1.5.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\jei_1.12.2-4.8.5.159.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mylittlemobgrinder-1.12.2-1.0.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\TConstruct-1.12.2-2.9.1.65.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Draconic-Evolution-1.12-2.3.10.284-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\p455w0rdslib-1.12-2.0.29.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\UniDict-1.12.2-2.4c.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\forge-1.12.2-14.23.1.2586-installer.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\HammerCore-1.12.2-1.9.8.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\LycanitesMobsComplete+1.19.5.0+[1.12.2].jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EverlastingAbilities-1.12.2-1.3.15.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\TrashSlot_1.12.1-8.4.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MineAddons-v2.1-mc1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\xnet-1.12-1.6.9.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\valkyrielib-1.12.2-2.0.9b.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Triumph-1.12.2-1.10.3.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BNBGamingCore-1.12-0.7.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Traverse-1.12.2-1.4.1-49.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Toast Control-1.12.2-1.4.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\tinyprogressions-1.12.2-3.3.25-Release.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\sonarcore-1.12.2-5.0.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\simplegenerators-1.12.2-2.0.9a.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\rftoolsdim-1.12-5.53.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\rftools-1.12-7.33.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Placebo-1.12.2-1.3.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Pam's HarvestCraft 1.12.2t.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Overloaded-1.12.2-0.0.47.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\modtweaker-4.0.10.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\KleeSlabs_1.12.2-5.4.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\industrialforegoing-1.12.2-1.8.7-132.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\industrialcraft-2-2.8.73-ex112.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\fluxnetworks-1.12.2-3.0.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EvilNotchLib-1.2.02.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\environmentaltech-1.12.2-2.0.9c.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\DungeonTweaks-1.2.4.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\DefaultOptions_1.12.2-9.2.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\cucumber-1.12-1.1.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Ceramics-1.12-1.3.4.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\base-1.12.2-3.7.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Ruins-1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\foamfix-0.9.6-1.12.2-anarchy.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\plustic-6.3.7.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\levels-2.0.3.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mysticalagriculture-1.12-1.6.9.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mysticalagradditions-1.12-1.2.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EnderCore-1.12.2-0.5.18.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EnderIO-1.12.2-5.0.20.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MobGrindingUtils-0.3.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\furniture-4.2.0-1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BNBGamingLib-1.12-2.10.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Cyclic-1.12.2-1.14.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\LagGoggles-FORGE-1.12.2-4.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ScalingHealth-1.12-1.3.13-94.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\SilentLib-1.12-2.2.18-100.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\GottschCore-mc1.12-f14.21.1.2387-v1.3.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Treasure2-mc1.12.2-f14.23.1.2555-alpha0.5.3.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\AutoRegLib-1.3-16.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Quark-r1.4-123.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\silkspawners-1.6.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\disenchanter-[1.12]1.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\appliedenergistics2-rv5-stable-11.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CyclopsCore-1.12.2-0.11.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Xaeros_Minimap_1.14.9.1_Forge_1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mcjtylib-1.12-2.6.7.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Hwyla-1.8.24-B39_1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\extinguish-1.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\DarkUtils-1.12.2-1.8.207.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CraftingTweaks_1.12.2-8.1.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CookingForBlockheads_1.12.2-6.3.26.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Bookshelf-1.12.2-2.3.537.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ActuallyAdditions-1.12.2-r133.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ElementalCreepers-v4.1.4.2.g84e9cc0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mobultion-0.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Cool Vreatures 1.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\DungeonTactics-1.12.2-0.14.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\natura-1.12.2-4.3.2.42.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CraftStudio-1.0.0.93-mc1.12-alpha.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BattleTowers-1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MCA-1.12.x-5.3.1-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EquivalentEnergistics-1.12.2-0.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\SilentsGems-1.12-2.6.9b-265.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\torcherino-7.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\xpfromharvest-1.12-1.0.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Tesla-1.12.2-1.0.63.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\tesla-core-lib-1.12-1.0.13.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\betteragriculture-1.12.2-1.2.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\hud-1.3.9-1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OreCore 1.12.2 (v1.3.7).jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Chisel-MC1.12.2-0.2.0.31.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Neat 1.4-15.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\PotionCore-1.6_for_1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Wawla-1.12.2-2.5.253.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CedProjectEAddOn-1.12.2-0.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CedStuff-1.12.2-0.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Ender Bags-1.12.2-2.1.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\IvToolkit-1.3.3-1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\primitivemobs-1.1.6_beta.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Reliquary-1.12.2-1.3.4.757.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\SoManyEnchantments V0.3.1 (1.12.2).jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BetterBedrockGenerator-1.12-6.1.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BiblioCraft[v2.4.3][MC1.12.0].jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\mobends-0.24_for_MC-1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\WailaHarvestability-mc1.12-1.1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\yoyos_1.12.2-1.2.2.20.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ClassicCombat-1.12-1.0.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\diethopper-1.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\InventoryTweaks-1.63.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\moreoverlays-1.13-mc1.12.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\SimpleSponge-1.12.2-3.6.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CTM-MC1.12-0.2.3.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\fairylights-2.1.2-1.12.x.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MouseTweaks-2.8-mc1.12.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\TinkerToolLeveling-1.12-1.0.3.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\torohealth-1.12.2-11.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\DoomlikeDungeons-1.11.1-MC1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\enderutilities-1.12.2-0.7.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Mekanism-1.12.2-9.4.3.330.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\NoMobSpawningOnTrees-1.2.1-mc1.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\RedstoneFlux-1.12-2.0.1.2-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\refinedstorageaddons-0.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CustomBackgrounds-MC1.12-1.1.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\JustEnoughResources-1.12.2-0.8.7.41.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MikeDongles-0.6.0-[1.12.2].jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Morph-o-Tool-1.2-16.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ProjectE-1.12-PE1.2.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BetterFps-1.4.8.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CodeChickenLib-1.12.2-3.1.6.339-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MekanismTools-1.12.2-9.4.3.330.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OpenBlocks-1.12.2-1.7.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Controlling-3.0.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Ding-1.12.1-1.0.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\funky-locomotion-1.12.2-1.1.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\malisiscore-1.12.2-6.4.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OpenModsLib-1.12.2-0.11.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\flatcoloredblocks-mc1.12-6.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Harvest-1.12-1.2.6-18.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\RandomThings-MC1.12.2-4.1.4.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ReAuth-3.5.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\badwithernocookiereloaded-1.12.2-2.12.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EnderZoo-1.12.1-1.4.0.49.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\InfernalMobs-1.12.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\twilightforest-1.12.2-3.6.345-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MCMultiPart-2.4.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OpenComputers-MC1.12.2-1.7.2.67.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\RadixCore-1.12.x-2.2.1-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\WanionLib-1.12.2-1.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\AIImprovements-1.12.1-0.0.1b1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\AppleSkin-mc1.12-1.0.9.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Clumps-3.0.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\modnametooltip_1.12.2-1.10.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\notenoughwands-1.12-1.6.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Xtones-1.12-1.0.8-11.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BedBugs-1.12-1.0.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\EnderStorage-1.12.2-2.4.2.126-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\NotEnoughIDs-1.5.4.2.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\shetiphiancore-1.12.0-3.5.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CustomStartingGear-1.12-1.2.0.9-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\extrautils2-1.12-1.7.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\JAOPCA-1.12.2-2.2.6.78.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\malisisdoors-1.12.2-7.3.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MTLib-3.0.4.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\BrandonsCore-1.12-2.4.0.152-universal.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Forgelin-1.6.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\GraveStone-1.12-Graves-1.0.14.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OpenGlider-1.12.1-1.1.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\rftoolsctrl-1.12-1.8.1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Stairs-1.12.2-b18.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\buildcraft-7.99.15.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\platforms-1.12.0-1.4.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\randomtweaks-1.12.2-1.17.1.0.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CraftTweaker2-1.12-4.1.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\endertanks-1.12.0-1.6.5.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\chiselsandbits-14.16.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\HelpFixer-1.12.1-1.5.18.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\NoMoreRecipeConflict-0.10(1.12.2).jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\OreExcavation-1.4.113.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\CosmeticArmorReworked-1.12.2-v1.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ElevatorMod-1.12.2-1.3.6.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\Mantle-1.12-1.3.1.21.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\MekanismGenerators-1.12.2-9.4.3.330.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\QuickLeafDecay-MC1.12.1-1.2.4.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\refinedstorage-1.5.32.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\WrapUp-1.12-1.1.3.jar"
"C:\Users\matty5ps\Desktop\MultiMC\instances\mattrixx444\minecraft\mods\ActuallyBaubles-1.12-1.1.jar"

**Comment by mattrix444** [comment]
i know its not really your place to do anything to sort it out since its mod compat, but could you offer any advice looking through my mods as to which mod might be affecting the block reach only if you know of course :D thanks budd

**Comment by PrinceOfAmber** [comment]
This is the million dollar question.  I have seen even the biggest pack devs and even twitch streamers go through one by one disabling mods (or the opposite, adding htem in) a few at a time until the bug appears or goes away, and then you know the ones that just changed might have an issue, so you try with just that batch.

It might not be another enchant, it could be anything else that sets a players reach.  Maybe something that gives players abilities like a skill tree? maybe theres a tool or stick that is controlling block reach from some mod?    Actually it could be anything that messes with PlayerControllerMP  in theory, which is a wide net, so hard to say

My related code is
https://github.com/PrinceOfAmber/Cyclic/blob/d4d11ee3d83283d9216b1df6d2efcca45de68b5b/src/main/java/com/lothrazar/cyclicmagic/proxy/CommonProxy.java#L68
and
https://github.com/PrinceOfAmber/Cyclic/blob/d4d11ee3d83283d9216b1df6d2efcca45de68b5b/src/main/java/com/lothrazar/cyclicmagic/proxy/ClientProxy.java#L275

The thing is, I do have a logger sending any errors with this to the console, so hopefully something would be in one of the /log/ files right at the time of equip.

**Comment by mattrix444** [comment]
disabled potioncore, reloaded, enchanted chest with block reach. works like a charm. sorted bruvva haha thanks for the help.
