### ISSUE TITLE
Automated User Can't Place Items into Astral Sorcery's Starlight Infuser and other suggestions

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#766]
Minecraft version: 1.12.2
Mod Version: 1.14.6
Server
SevTech Modpack 3.0.4

Describe problem (what you were doing / what happened):
https://streamable.com/yy6or
Cyclic user in "Use" item mode doesn't allow to place crafting ingredients into Astral Sorcery's Starlight Infuser. It does work with activating the Starlight Infuser when you leave a Resonating wand 

Maybe a possible fix is to allow for more 'modes' for the user ranging from activation of blocks as well as using an item on a block?

Also on another suggestion, would it be possible to have a hold-down right click functionality with the automated user? Kind of like using Botania's Horn of the Wild, all other users as far as I'm aware only allow for really fast right clicking/use of the item.

**Comment by PrinceOfAmber** [comment]
I just tried this in 1.4.7 and it looks okay.  GIF is the aquamarine but i tried with the crushed quartz and that works as well

![user 148](https://user-images.githubusercontent.com/621529/38471334-8a11c12c-3b24-11e8-91cd-aad8ce7a4e48.gif)

**Comment by Vyraal1** [comment]
Updated to 1.14.7 (or maybe it was there all along and I mistyped), but either way, I guess it might be some weird interaction in the pack. Unless the gif you made was from SevTech as well? In which case, I have no idea what's going on.

**Comment by PrinceOfAmber** [comment]
My gif only had about 10 mods installed. 

Yeah it could be either a mod conflict in pack, or it was disabled in the pack on purpose? Sevtech does have a discord and an issue tracker as well if its a config issue that needs fixing

**Comment by PrinceOfAmber** [comment]
closed: stale.  Still works in isolation and with minimal mods installed so i guess theres nothing I can do on my end .

If more information comes up then reopen and let me know

**Comment by PrinceOfAmber** [comment]
Looks like its fixed in the dev version of the modpack too https://github.com/DarkPacks/SevTech-Ages/issues/1692
