### ISSUE TITLE
Structure Builder Height Reset on Reload

### ISSUE THREAD

**Issue by TherminatorX** [PrinceOfAmber/Cyclic#768]
Minecraft version & Mod Version:
MC 1.12.2, Cyclic 1.13.3

Single player or Server:
SP

Describe problem (what you were doing / what happened):

While trying to automate a process involving repeated block placement (Botania), I experienced an unrelated crash that closed my game. Upon reloading the world, the height parameter of the Structured Builder had reset to 3, where I had set it to one previously, and had placed blocks above where I needed them to be.

Crash log (if any):
Unrelated

**Comment by PrinceOfAmber** [comment]
Should work in latest https://minecraft.curseforge.com/projects/cyclic/files/2550423
