### ISSUE TITLE
Controlled Miner: Tool Slot included in Filter

### ISSUE THREAD

**Issue by TherminatorX** [PrinceOfAmber/Cyclic#769]
Minecraft version & Mod Version:
MC 1.12.2, Cyclic 1.13.3

Single player or Server:
SP

Describe problem (what you were doing / what happened):

When placing a block in the "Tool" slot for the miner, it will include that block in the Whitelist/Blacklist when checking what blocks to break.

Crash log (if any):
nope.avi

**Comment by PrinceOfAmber** [comment]
So basically this right? It was treating shears as part of whitelist 
![whitelist shears](https://user-images.githubusercontent.com/621529/38470473-6e140266-3b18-11e8-8250-07aa3e47242f.PNG)

**Comment by TherminatorX** [comment]
Correct, but it wouldn't have done anything since shears aren't a breakable block afaik

**Comment by PrinceOfAmber** [comment]
Should work in latest https://minecraft.curseforge.com/projects/cyclic/files/2550423
