### ISSUE TITLE
[Bug]Fuel slots for Auto crafter block doesn't work

### ISSUE THREAD

**Issue by sandtechnology** [PrinceOfAmber/Cyclic#770]
Minecraft version & Mod Version:
1.12.2&1.12.2-1.14.6

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Fuel slots for auto crafter block doesn't work:
![tim 20180407151347](https://user-images.githubusercontent.com/20417547/38452402-53bf4cba-3a76-11e8-83ba-120a4699367b.png)

Crash log (if any):
None

**Comment by PrinceOfAmber** [comment]
Should work in latest https://minecraft.curseforge.com/projects/cyclic/files/2550423
