### ISSUE TITLE
1.12.2 - Ender Book

### ISSUE THREAD

**Issue by TheSnowyChickens** [PrinceOfAmber/Cyclic#771]
Minecraft version & Mod Version: 
-MC 1.12.2
-Cyclic 1.14.7
-forge1.12.2-14.23.2.2654

Single player or Server: 
-Single player (In a RFTools World)

Describe problem (what you were doing / what happened):
-The Waypoints, thats the Ender Book create, is not 100% correct.
-(The pictures show an example)

Created Waypoint at "1 63 1" \/
![2018-04-08_01 02 47](https://user-images.githubusercontent.com/29357962/38461126-add3163a-3ac8-11e8-84f0-e5e269a72910.png)

Teleported to "1 63 0" + into this corner \/
![2018-04-08_01 03 50](https://user-images.githubusercontent.com/29357962/38461132-bce0fea8-3ac8-11e8-95d2-1169d3271999.png)

Crash log (if any):
-No

Extras:
-I may remember that Vanilla MC had a TP fail with always -1 in x & z.

**Comment by PrinceOfAmber** [comment]
Aha found it! It was rounding off the decimals, so -1.9 was sending you to -1.0 exactly

**Comment by PrinceOfAmber** [comment]
Should work in latest https://minecraft.curseforge.com/projects/cyclic/files/2550423

**Comment by TheSnowyChickens** [comment]
Thx
