### ISSUE TITLE
Sleeping mat doesnt dismount properly

### ISSUE THREAD

**Issue by 0xb00b** [PrinceOfAmber/Cyclic#772]
Minecraft version & Mod Version:
1.12; ;latest; sevtech 3.0.6

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Independently of me, someone else encounterd this issue here https://github.com/Darkosto/SevTech-Ages/issues/1641

When you use the sleeping mat on a horse (while mounted); after you wake up the game thinks you're still on a horse. E.g. being unable to re-mount the horse (since the 'game' thinks you're already mounted probably) and me specifically, got attacked by a zombie, ran away and the zombie was able to kill me as if i was on the horse) 

Personally i've tried to replicate this behaviour with other 'sleeping' mods like the Tipi and the vanilla bed, they all seem to be dismounting the player correctly before/after the sleep happens. Since this works with vanilla horses + cyclic sleeping mat ( i did not test this in a clean environment with only vanilla+cyclic, i must admit.) im assuming its a problem where the sleeping mat doesnt do a dismountEverything(); or something like that. 

Note that a relog fixes the issue. 

Crash log (if any):
--

**Comment by PrinceOfAmber** [comment]
Should work in latest https://minecraft.curseforge.com/projects/cyclic/files/2550423

**Comment by ryankhart** [comment]
Thank you @0xb00b for submitting [my bug](https://github.com/Darkosto/SevTech-Ages/issues/1641) to the right mod maker. I didn't think to take that next step and find out which mod was causing it.
