### ISSUE TITLE
Item pipes cause tps lag

### ISSUE THREAD

**Issue by Kekko961** [PrinceOfAmber/Cyclic#775]
Minecraft version & Mod Version:
1.12.2 latest released on 11/04/2018

Single player or Server:
Sp

Describe problem (what you were doing / what happened):
If you have a lot of item pipes they cause major tps and fps lag, diagnosed with lag goggles mod. 

Crash log (if any):
No crash

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/laggoggles/files/2536205

**Comment by PrinceOfAmber** [comment]
Finally found some time to check this out.  Looks like it uses a green/red system to identify lag, so things like hopper and my normal machines hit around 8 or 11 uS, and pipes can be around 25 uS.  There is one case where a corner is around 184

Some screenshots   https://imgur.com/a/4R64r4G

**Comment by PrinceOfAmber** [comment]
Oops looks like i tagged this in a commit for 1.15.8 but forgot to close it.  Still not perfect, may not be better than other pipes but its better than it was
