### ISSUE TITLE
Extraction Cables misleading or not working as intended.

### ISSUE THREAD

**Issue by jthawkins95** [PrinceOfAmber/Cyclic#776]
Minecraft version & Mod Version:
Sevtech Ages 3.0.6
Cyclic 1.14.7

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Fluid extraction cable JEI information says "Drains from all sides except the facing direction." Seems to only drain from side opposite of facing direction.

Images:
![image](https://user-images.githubusercontent.com/15057011/38753272-bcc0def4-3f12-11e8-94ef-b7f6a09337a5.png)

**Comment by PrinceOfAmber** [comment]
New wording 

"Drains straight out in one direction between any compatible blocks.  Connect this to another tank or Fluid Cable."

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2552920
