### ISSUE TITLE
Cyclic isolated duplication bug

### ISSUE THREAD

**Issue by jthawkins95** [PrinceOfAmber/Cyclic#778]
## Issue / Bug
When a *damaged* Cyclic Garden Scythe is used with a Cyclic Automated User, Every crop the user would harvest also drops a copy of that Garden Scythe. Videos attached:
https://clips.twitch.tv/GoodProtectiveAlpacaFunRun
https://clips.twitch.tv/ClumsyHardGarageCeilingCat

## Possible Solution
Prevent scythes from taking durability damage.

## Steps to Reproduce (for bugs)
Everything I know about how it was produced is in those two videos.
Damage a Cyclic scythe, somehow (I did it by using it on tomatoes). Use Scythe in Cyclic Automated User. Bam. Infinite blaze rods (via uncrafting table).

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used:
Twitch lawnchair
* Memory Allocated:
7gb
* Server/LAN/Single Player: Single
* Resourcepack Enabled?: Nope
* Optifine Installed?: Nope

**Comment by PrinceOfAmber** [comment]
Yep confirmed this happens outside modpack as well, simply point at a planted wheat seed.

**Comment by PrinceOfAmber** [comment]
note to self for later:  I think this was introduced when i forced in some compatibility https://github.com/PrinceOfAmber/Cyclic/issues/353

**Comment by PrinceOfAmber** [comment]
After the fix 
![dupe](https://user-images.githubusercontent.com/621529/38910520-80bfb924-427e-11e8-88af-7666f5f7c61b.gif)

**Comment by PrinceOfAmber** [comment]
Possibly same cause as https://github.com/PrinceOfAmber/Cyclic/issues/757

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2552920
