### ISSUE TITLE
Infinite Multi Jump when falling with boat

### ISSUE THREAD

**Issue by randomlypickedname** [PrinceOfAmber/Cyclic#781]
Minecraft version & Mod Version: 1.12.2, 1.14.7 (SevTech 3.0.6)

Single player or Server: Server

Describe problem (what you were doing / what happened): Something propelled me in the air when I discovered it the first time, but after further testing, I'm able to multi jump while in the air with a boat as much as I'd like.

~~Crash log (if any):~~

**Comment by PrinceOfAmber** [comment]
Looked into this and i remembered what I was doing.

I wanted to be able to double-jump while riding a horse, so i let the enchantment trigger if player is mounted.

I will look into tweaking this, maybe looking for "living mounts" , or maybe reducing power if its a boat or something.  But i guess it was working as intended at the time.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2568479
