### ISSUE TITLE
umm not sure [automated user + Birds Nests mod]

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#782]
Minecraft version & Mod Version:
1.12.2 1.14.8

Single player or Server:

single player
Describe problem (what you were doing / what happened):
using an automated user to open birds nests for items but instead it dupes them massively please check if this is a compat bug pretty please?

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
good news: As of 1.15.0 release, it no longer dupes the items.

Bad news: it does not open the nest.  Not sure if there is anything I can do (i can try), it might be issue on the other end.

**Comment by PrinceOfAmber** [comment]
Update: confirmed working latest versions 1.15.1, and probably 1.15.0 as well 
![bird](https://user-images.githubusercontent.com/621529/39955041-668eb754-557e-11e8-990c-fb3a7c721f73.gif)
