### ISSUE TITLE
Sage and Druid trades.

### ISSUE THREAD

**Issue by Bullorg74** [PrinceOfAmber/Cyclic#783]
Not a suggestion really but a question.

The Sage and Druid trades are they all ment to be selling only emeralds and buying alot of diffrent stuff?
I thought they sold alot of "wierd" things for emeralds but they dont.
I was thinking of using them as the only way to get blaze rods. As I got it when reading the configs. But when I test they buy blazerods not sell.

BTW great mod TY

Cyclic : 1.12.2-1.14-9
Forge : 14.23.3.2668

**Comment by PrinceOfAmber** [comment]
I checked it out and im happy with what they trade right now.  Thanks for the compliment and report and suggestion they are always welcome

There is a way to customize trades if you need that https://minecraft.curseforge.com/projects/villager-trade-tables
