### ISSUE TITLE
Game crashes when opening player inventory crafting GUI.

### ISSUE THREAD

**Issue by GeekTechMedia** [PrinceOfAmber/Cyclic#784]
Minecraft version & Mod Version:
Minecraft 1.12.2 Forge Version: 14.23.3.2669  Mod Version: 1.14.9

Single player or Server:
This was on single player.

Describe problem (what you were doing / what happened):
I am not sure if this is a Cyclic issue or Thaumcraft issue, however when you open the player inventory crafting grid of cyclic, the game crashes. I was able to reproduce multiple times. 

Crash log (if any):
https://pastebin.com/3NDxFTrA

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I dug into this a bunch more.  My code does nothing except call vanilla function

   super.drawScreen(mouseX, mouseY, partialTicks);


and thats literally the only time cyclic gets mentioned,  from there it goes into vanillla minecraft and comes out at thaumcrafts end, so i have to assume its on their end

in other words, the fix has to be added here

java.lang.NullPointerException: Rendering screen
    at thaumcraft.api.crafting.ShapelessArcaneRecipe.func_77569_a(ShapelessArcaneRecipe.java:60)
