### ISSUE TITLE
[1.12.2] Conflict with Scaling Health. *Cyclic Hearts glitches out health.*

### ISSUE THREAD

**Issue by Z-Tunic** [PrinceOfAmber/Cyclic#785]
Minecraft: 1.12.2
Forge: 14.23.3.2673

Mods:
Cyclic-1.12.2-1.14.9
ScalingHealth-1.12-1.3.14-96
SilentLib-1.12-2.2.18-100

-----
Issue:
Scaling health allows you to alter the players health such as how much they start with, you can also use it's Heart Containers to boost health to a cap. Say... if you set SH's config to max health 200 then you health will cap out at 200.

If you happen to use Cyclic's Hearts to increase health then there will be some confusion of what to do with the player's health. Even though health is capped at, say 200... using Cyclic's Hearts should allow it to go to 220 but instead it's a tug o war between 200 & 220.

Some other health modifiers don't cause this as they're more of a 'Bonus Health' thing, as I call it, and they work alongside Scaling Health... such as Aether Legacy's Life Shards (Up to +10 Hearts, can increase cap via config), the Ring of Odin from Botania (+10 Hearts when worn) or Cyberware's Bonlacing (+2 Hearts per Bone Lace, up to 5 Bone Lacing which is +10 Hearts.)

![](https://cdn.discordapp.com/attachments/377171551155650560/438717622318792714/scalinghealthcyclichpbug.PNG)
Health Cap should be 40 in this image but the counter is glitched and shows 39/20 after using 10 Cyclic Hearts. No Scaling Health Hearts were used to boost health.

Upon looking into it further it does take into account that your health is above scaling health's cap but it's HUD won't show it correctly. However if you die then Cyclic's Health Boost no longer applies with no way to boost it anymore.

**Comment by PrinceOfAmber** [comment]
I'm not sure if there is anything I can do, your best bet might just be to disable the hearts from Cyclic (already available in the config file) if you are using other mods.

Basically, each mod keeps track of player health in their own way. So Cyclic goes "ok your hearts are now 12"  and mod X goes "Oh I thought their hearts were 11",  and then you eat a cyclic heart and it says "ok go +1 to your health" , ....  but now is that 12 or 13? , and its just a mixup.

**Comment by Z-Tunic** [comment]
Is there a way to have it alter health like how Aether Legacy's Life Shards, Cyberware's Bonelacing, Botania's Ring of Odin, etc. I think because it affects "generic.maxHealth" directly is where the mix-up occurs.

Looking at Scaling Health's Debug info... there's a list of Attribute Modifiers of what's affecting the player's health. Here's a image of what it looks like...
![](https://cdn.discordapp.com/attachments/377171551155650560/440896187332034570/cyclicheartsownmod1.PNG)
These are the Health Modifiers in use from other mods that affects the player's health, which work alongside each other due to them having there own "Attribute Modifier". Using a Cyclic Heart affects the "ScalingHealth.HealthModifier" which turns the value from 0.0 to -2.0... then that mix-up happens.

If Cyclic Hearts had it's own Attribute Modifier... it would work without conflicting with each other since it wouldn't be affecting "generic.maxHealth", thus allowing them to stack on top of the other modifiers.

If it's not possible then I'll just use the config to disable the hearts to avoid the mix-up.

**Comment by PrinceOfAmber** [comment]
Based on our testing, this now uses the attribute system and is good to go in the latest version https://minecraft.curseforge.com/projects/cyclic/files/2580565
