### ISSUE TITLE
Enchanter - Specific Enchants

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#786]
I first tried your enchanter today and saw it takes random enchants - any possibility to make an item that can automatically apply enchantment books to items? Seems not possible with the vanilla table and not possible with the powered anvil.

**Comment by PrinceOfAmber** [comment]
This is a great idea for a feature, im just not sure how to fit that information into the GUI.

Maybe an "advanced" verison of the block with different costs involved and a new screen?

**Comment by D3nnis3n** [comment]
Well, it's not that hard i think.
You only need another slot for the input of an enchanted book and it should cost energy as it does now.
Experience has already been paid for by enchanting the book, but in the Anvil the applying also costs some more experience, so you need liquid xp.

Usually it's done with the vanilla anvil, but that does not allow automation as you need to click in the anvil.

You would just pump in the items and the enchantment books and it would process them with energy and liquid experience. (That would keep to vanilla, at least).

That would make the automation of creating items with specific enchantments possible.

----------------------------------------------------------------------------------------------------------

Another funny thing would be the automatic creation of specific enchantment books.

That could happen by a machine in which you insert an enchantment book that you have made in the vanilla table and put it into that machine as blueprint. You will insert energy, experience, books and maybe another resource (maybe a nether resource?) to copy these.

**Comment by PrinceOfAmber** [comment]
Ive tried to brainstorm a few ways to do it but i think this mod does it much better https://www.curseforge.com/minecraft/mc-mods/enchanting-plus 

so not gonna add this, but i do have lots of other plans
