### ISSUE TITLE
[Suggestion] Grass scythe not dropping Primal Core plant fiber 

### ISSUE THREAD

**Issue by BigAl607** [PrinceOfAmber/Cyclic#787]
1.12.2
single player
When using the grass scythe on large areas, the scythe doesn't drop the plant fibers from Primal Core in the SevTech: Ages modpack. Would be nice to have the plant fibers drop, as the "normal" torches still take the plant twine to make, as well as the twine comes in handy in other aspects of the game until you progress farther in the pack.

**Comment by PrinceOfAmber** [comment]
I tried to look into thus, sadly primal core is closed source so i dont know why this isnt working.  Seems to work with other custom drops and other custom grass from certain mods. Ill keep it on backlog to come back to it

**Comment by PrinceOfAmber** [comment]
Note to self, attempted the obvious forge hook with no success:

 `       world.getBlockState(pos).getBlock().onBlockDestroyedByPlayer(world, pos, world.getBlockState(pos));`

**Comment by PrinceOfAmber** [comment]
Note to self
try using the `replacedBlock.harvestBlock(world, player, curPos, replacedBlockState, null, itemStackHeld);` as discovered here, might work 

(different issue but it might have the same solution, item only drops if the block break has player context) 
https://github.com/DarkPacks/SevTech-Ages/issues/2485

**Comment by PrinceOfAmber** [comment]
Gottem! Coming in 1.15.6 update soon 
![gottem](https://user-images.githubusercontent.com/621529/40579827-a17845b6-60e5-11e8-8677-b058bdc1b782.gif)

**Comment by PrinceOfAmber** [comment]
fix https://minecraft.curseforge.com/projects/cyclic/files/2566207
