### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by X1machinemaker1X** [PrinceOfAmber/Cyclic#792]
Adding a way to pump a fuel like coal or charcoal into the automated user or allowing them to use forge energy would be a great way to make them so much more useful. Unless I'm missing something, you can't pump coal into the fuel slot (I tried from all sides).

**Comment by PrinceOfAmber** [comment]
They already use forge energy.  ALso the charcoal slot will be removed in version 1.15.0
