### ISSUE TITLE
Editing signs does not work

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#793]
Minecraft version & Mod Version: 1.12 / 1.14.9

Single player or Server: Server

Describe problem (what you were doing / what happened):
Put up a sign, write something on it. Punch it with left-click and nothing in hand (when the option to do so is activated). Write a new text. Save. See the new text. Leave the chunk, so it get's unloaded. Come back. See the old text. Ask yourself, if you're dumb or not. Repeat this several times, until you start recognizing a bug and reporting it on the issue tracker.

**Comment by PrinceOfAmber** [comment]
I just tried this again and in latest 1.15.x versions its working for me.

Recording of server, log out and log in and its saved.  Anything on log files when this happens?

![sign edit server](https://user-images.githubusercontent.com/621529/40319845-74e43542-5cde-11e8-8592-1ca80ab0d75a.gif)

**Comment by PrinceOfAmber** [comment]
Suddenly this stopped working for me again, i dont know what i was doing in that GIF but now i do the same thing and it doesnt save.  Maybe is just RNG sometimes working? looking into it

**Comment by D3nnis3n** [comment]
Hah, cool you could reproduce it now. For me it didn't work even a single
Time.

Sam <notifications@github.com> schrieb am Mo., 28. Mai 2018, 08:17:

**Comment by PrinceOfAmber** [comment]
I think im going to rewrite the feature to add an item to do the editing. Also will let me add more features such as  these https://github.com/PrinceOfAmber/Cyclic/issues/789

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2567501

**Comment by D3nnis3n** [comment]
Hey, did you add this item? It seems the old way does no longer work.
