### ISSUE TITLE
[Mod Compatibility]A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by sandtechnology** [PrinceOfAmber/Cyclic#795]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.14.6
Spongeforge-1.12.2-2655-7.1.0-BETA-3055
(https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)

Single player or Server:
Server

Describe problem (what you were doing / what happened):

When I use Ender book teleporting,I lost connection because "A fatal error has occurred, this connection is terminated"

Server log:
https://paste.ubuntu.com/p/8BfNymt3Bx/

This issue is about 2 month ago,I solved by enable this sponge setting:
```
        # If enabled, any request for a chunk not currently loaded will be denied (exceptions apply for things like world gen and player movement). 
        # Note: As this is an experimental setting for performance gain, if you encounter any issues then we recommend disabling it.
        deny-chunk-requests=true
```
But this setting is an experimental setting and cause more mod compatibility issue,could you solve this compatibility issue?

**Comment by PrinceOfAmber** [comment]
When teleporting into UN-loaded chunks, the chunks have to load, otherwise you are just in a void thats not really a void.  

I cant say for sure theres anything I can do, but mabye.
