### ISSUE TITLE
[Question, 1.12.2] About sizes from your machines

### ISSUE THREAD

**Issue by TheSnowyChickens** [PrinceOfAmber/Cyclic#799]
Idea/Question:
Hello,
my question is very simple, Is it possible to create sizes not like "1x1" ... "11x11" ... "15x15", but rather like "2x2" ... "10x10" ... "14x14" ... and so on? (for Harvester as example, or forester)

I like it to build in a chunk format, to avoid bugs with chunk borders, and I always want to style it symmetric and with 15x15 or odd numbers its difficult. :D

![grafik](https://user-images.githubusercontent.com/29357962/39785704-6bdf33cc-531d-11e8-9e95-85e7d5002ed7.png)
Left (15x15) and right (14x14) (black glass as marker)

Is there something, what you can do?^^

Versions (atm in use)
MC: 1.12.2
Cyclic-1.12.2-1.14.9.jar
Forge: 1.12.2 - 14.23.3.2679

**Comment by PrinceOfAmber** [comment]
Right now the center of the square is in line with the machine itself, i laid it out in a grid here in this screenshot below.

The problem with doing a square that is even such as 6x6, is that then the center of that square would be a 2x2 area.... but now where does that center go? (continued in next comment)
![2018-05-11_18 38 43](https://user-images.githubusercontent.com/621529/39952400-c9f7d0ac-554a-11e8-98d4-5a1aeba73aab.png)

**Comment by PrinceOfAmber** [comment]
Shown here is the machine set as 3x3.  If i wanted to increase that to 4x4, there are (at least) two optoins: 
 

Should the machine  lay it out like this checkerboard pattern here, or do i move it left one to where the green is?  And how does it decide?

![2018-05-11_18 41 38](https://user-images.githubusercontent.com/621529/39952416-206afc3e-554b-11e8-9d8e-8274fece2e30.png)

**Comment by PrinceOfAmber** [comment]
But how would it decide? I would need some awkward "left or right" yes no button in the gui, that is hidden if its odd, and visible if its even, sorry it just doet feel liek a clean solution Its just not worth it.

If you want to farm a 4x4 area, just plant a 4x4 and set harvester to use 5x5. being a bit too big  SOrry and thanks for all the feedback anyway

**Comment by Kazuto** [comment]
As a UX designer I've got the following suggestion:
Make increment/decrement buttons for Width, Length, Offset X (Width).
This way the user is completely independent of where the desired area is and it would allow odd numbers.
