### ISSUE TITLE
[1.12.2] Converyor Belt Corner Won't Face Right & Forward

### ISSUE THREAD

**Issue by Andronomos** [PrinceOfAmber/Cyclic#800]
**Minecraft version & Mod Version:** 
1.12.2-1.15.0

**Single player or Server:** 
Single player

**Describe problem (what you were doing / what happened):**
When placing a conveyor belt corner it will always face left moving forward in the same direction as the previous conveyor belt.

[Screenshot 1](https://i.imgur.com/OMIUeYB.png)

If you hold down shift the corner will face right but will be moving in the opposite direction of the previous conveyor belt.

[Screenshot 1](https://i.imgur.com/9ECiV40.png)

I'm not sure if this is a bug or I am doing something wrong but no matter what direction I face or what button I hold while placing I can't get the conveyor belt corner to face right moving in a forward direction.

**Comment by PrinceOfAmber** [comment]
The corner blocks as items are not meant to be obtainable by the player.  When you place a straight conveyor, it turns into a corner when it detects nearby rails.

Once placed corners can be rotated with tools.

I am open to improving this system, i know it could be better, but im not sure what your intended workflow is here.

![conv test](https://user-images.githubusercontent.com/621529/39952378-072b1368-554a-11e8-88e0-b1a21c702d99.gif)

**Comment by PrinceOfAmber** [comment]
To avoid confusion, i have disabled the item versions of these blocks and hidden from JEI/creative tab, and disabled middle click.  

![middle click](https://user-images.githubusercontent.com/621529/39952625-d6c282dc-554f-11e8-9e51-4de08198acf1.gif)

**Comment by Andronomos** [comment]
Oh, okay. My apologies I didn't know they weren't supposed to be obtainable. I saw your update and got excited and rushed to go try it out in a test world and just played with what JEI gave me.

I can't really think of an improvements that need made. I would be curious to see what they looked like if they worked with connected textures when placed side by side so they became one giant conveyor belt. But that's not necessary.

Great job on this update, conveyor belts have become my go-to method for transporting mobs through my farm now.

**Comment by PrinceOfAmber** [comment]
No worries, never feel bad about reporting something you think is wrong :D And as i posted above it reminded me i could improve useability by hiding the item versions.
