### ISSUE TITLE
Error render model after upgrading version

### ISSUE THREAD

**Issue by kellixon** [PrinceOfAmber/Cyclic#806]
MC 1.12.2. Cyclic 1.15.2 Single player. Error render model. Crash - not, only spam error at log.
Log - https://gist.github.com/kellixon/4ede55e99ef4e7fb8cdd19e346d51062
Lines - 12026, 12055, 16665, 16690, 16787, 16812, 16834, 16859, 16881, 16906, 16998

**Comment by PrinceOfAmber** [comment]
i did a ctrl-f of my mod id"cyclicmagic", updater whent fine on mine. in fact barely any references.  

This file ends at line 7300 something. last reference i can see is "[16:51:33] [Forge Version Check/INFO] [forge.VersionCheck]: [cyclicmagic] Found status: UP_TO_DATE Target: null"

I think github cropped the tail end?

**Comment by kellixon** [comment]
Pls download this is file (71 776 lines)

**Comment by PrinceOfAmber** [comment]
Copying related parts here for my own convenience


`: Could not load vanilla model parent 'cyclicmagic:block/block_storeempty' for `

...

`[16:53:37] [main/ERROR] [FML]: Exception loading model for variant cyclicmagic:plate_push_fast_angle#inventory


`Exception loading model for variant cyclicmagic:battery_infinite#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model cyclicmagic:item/battery_infinite with loader VanillaLoader.INSTANCE, skipping`


`Exception loading model for variant cyclicmagic:plate_push_med_angle#inventory`
` Exception loading model for variant cyclicmagic:plate_push_med_angle#inventory,`
`Exception loading model for variant cyclicmagic:block_anvil_magma#inventory,`
`Exception loading model for variant cyclicmagic:block_anvil_magma#inventory`
`Exception loading model for variant enderstorage:ender_storage#type=ender_chest`

**Comment by PrinceOfAmber** [comment]
Note to self: create new world and then  F3+T to replicate without reloading game, this reloads resources and shows any remaining errors every time

, will make fixing it easier

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2567501
