### ISSUE TITLE
Crash related to permissions

### ISSUE THREAD

**Issue by nullifiedcat** [PrinceOfAmber/Cyclic#808]
Minecraft version & Mod Version: 1.12.2 | 1.14.9  

Single player or Server: Server

Describe problem (what you were doing / what happened): Just running, the game crashed

Crash log (if any): https://pastebin.com/3vqVPGPe

**Comment by nullifiedcat** [comment]
This happens when I have torch placer on

**Comment by PrinceOfAmber** [comment]
Thanks for reporting! This was fixed in a previous version https://github.com/PrinceOfAmber/Cyclic/issues/796

**Comment by nullifiedcat** [comment]
Sorry for reporting already fixed bug, I was just playing a modpack with outdated version of the mod when it happened.
