### ISSUE TITLE
[Issue] Sorter misses his color

### ISSUE THREAD

**Issue by accessdenied0** [PrinceOfAmber/Cyclic#809]
Minecraft version & Mod Version:
Cyclic-1.12.2-1.15.2

Single player or Server:
SSP

Describe problem (what you were doing / what happened):
The new Ghost-Items-filter is cool, but sadly the Sorter lost all his colors in the GUI. Makes it difficult to choose the proper output for the items.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2563194
