### ISSUE TITLE
Reseting step height with Apple of Lofty Stature sets player.stepHeight to wrong value

### ISSUE THREAD

**Issue by winauer** [PrinceOfAmber/Cyclic#810]
Minecraft version & Mod Version:

Minecraft: 1.12.2
Cyclic: 1.12.2-1.15.2

Single player or Server:

single player

Describe problem (what you were doing / what happened):

Eating a second Apple of Lofty Stature to reset step height to normal sets player.stepHeight to 0.5 but it should be 0.6. This creates issues with chisel&bits stairs.
See AlgorithmX2/Chisels-and-Bits#85

Crash log (if any):

None

**Comment by Jandakast** [comment]
This was also reported on the SevTech-Ages issue tracker https://github.com/DarkPacks/SevTech-Ages/issues/2440

Just adding more info, tested in an instance with only Cyclic 1.15.2 and Forge 2688. When this issue happens I can open the level.dat from a singleplayer world and set the cyclicmagic_stepforced value for the player to 0 to fix it.

**Comment by ButerBreaGrieneTsiis** [comment]
> This was also reported on the SevTech-Ages issue tracker DarkPacks/SevTech-Ages#2440
> 
> Just adding more info, tested in an instance with only Cyclic 1.15.2 and Forge 2688. When this issue happens I can open the level.dat from a singleplayer world and set the cyclicmagic_stepforced value for the player to 0 to fix it.

I opened my singleplayer world with NBTExplorer but I can't find cyclicmagic_stepforced, can you help me out?

**Comment by PrinceOfAmber** [comment]
Yep you are correct.  in one of the base classes (EntityLivingBase) constructor it precisely has

`        this.stepHeight = 0.6F;`

**Comment by PrinceOfAmber** [comment]
Note for existing players: once this fix comes out, if you are still  stuck at 0.5 you MIGHT (probably) have to eat more to turn it on & off again.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2563194
