### ISSUE TITLE
Uncrafting copper ingot gives Tome of Alkahestry

### ISSUE THREAD

**Issue by shikaku2** [PrinceOfAmber/Cyclic#811]
Minecraft version & Mod Version: 1.12.2 & Cyclic-1.12.2-1.14.9

Single player or Server: Server

Describe problem (what you were doing / what happened): Uncrafting copper ingot gives Tome of Alkahestry (from Reliquary), which is definitely not something it should be outputting, should fail instead.

**Comment by PrinceOfAmber** [comment]
What modpack are you playing?

Is there a recipe where you craft a Tome of Alkahestry into a copper ingot?

The grinder just looks up existing recipes in forge registry.

Ill look into it a bit, but best solution is probably just adding the Tome to blacklist config.  (config file where it says "Blacklists and other tweaks for the Uncrafting Grinder")

**Comment by PrinceOfAmber** [comment]
When I install just a few mods the uncraft correctly finds the recipe, it matches the crafting.  If youre in a big modpack there could be other scripts or things going on maybe

![Uploading tome.PNG…]()

**Comment by PrinceOfAmber** [comment]
![tome](https://user-images.githubusercontent.com/621529/40156047-f3431ba6-594b-11e8-92a0-b22dd0b61750.PNG)

**Comment by shikaku2** [comment]
It's a big modpack on a private server.  I can zip up the mods if you wish.  Also I forgot to mention it does it when 2 copper ingots are put in.  And I'll go ahead and blacklist Tome of Alkahestry, but just letting you know that it does that so you can blacklist it in an update I guess

**Comment by PrinceOfAmber** [comment]
Yep thanks for the report as always!
