### ISSUE TITLE
Cyclic Block Placer deletes Better with Mods mini blocks instead of placing them

### ISSUE THREAD

**Issue by Jandakast** [PrinceOfAmber/Cyclic#812]
Minecraft version & Mod Version:
Minecraft 1.12.2 
Cyclic 1.15.3
Better With Mods 1.18

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Block Placer deletes Better With Mods Mini Blocks instead of placing them.
Mini blocks are siding, moulding, and corners. 

Crash log (if any):
None

Originally posted on the SevTech issue tracker. https://github.com/DarkPacks/SevTech-Ages/issues/2538

Maybe provide a block placer blacklist in the config?

**Comment by PrinceOfAmber** [comment]
Ill poke the BWM devs and see if i can get some insight.  If not then yeah maybe blacklist?


Bottom line is that when i go "world.setBlockState(...)" it returns TRUE for success, which is supposed to mean "yep block is placed in the world" and thats why i steal from slot.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2564637
