### ISSUE TITLE
[Bug]Hydrator doesn't produce biomass, and some glitch

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#816]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.15.5

Single player or Server:
Single

Describe problem (what you were doing / what happened):
When I put into hydrator pattern slots a differents plants(even according do JEI recipe), then doesn't happens although hydrator is filled with water and energy. It's a bug, or I does something wrong?

Second problem is with moon phase sensor. When I place it, then this glitch is visilble:
http://pokazywarka.pl/nn7ju5/

Crash log (if any):
none

**Comment by PrinceOfAmber** [comment]
fix https://minecraft.curseforge.com/projects/cyclic/files/2566207
