### ISSUE TITLE
[bug]  Inability to synthesize peat_biomass in cyclic 1.15.5 and 1.15.4

### ISSUE THREAD

**Issue by AsleepSnake** [PrinceOfAmber/Cyclic#817]
Minecraft version & Mod Version:1.12.2   Cyclic-1.12.2-1.15.5 and  Cyclic-1.12.2-1.15.4

Single player or Server: Single player 

Describe problem (what you were doing / what happened): Inability to synthesize peat_biomass, block_hydrator Inability to synthesize peat_biomass,in cyclic 1.15.5 and 1.15.4
It's really a lot of trouble，I have some screenshots, I don't know if you can see it.
http://wx2.sinaimg.cn/large/7bda2a17gy1froiqi7it4j20mq0d4gn9.jpg
http://wx2.sinaimg.cn/large/7bda2a17gy1froiqhpmrqj20lf0cw0te.jpg

I really want the agitator to be still
I like this mod, and I'll support you

Crash log (if any): none

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Aha yep it was having trouble matching some of the blocks with ore dictionary such as the Red flower, fix coming out tonight!

**Comment by PrinceOfAmber** [comment]
Also FYI if you are a modpack dev using crafttweaker you can add custom hydrator recipes like this https://github.com/PrinceOfAmber/Cyclic/blob/master/scripts_zen_example/hydrator.zs

**Comment by PrinceOfAmber** [comment]
fix https://minecraft.curseforge.com/projects/cyclic/files/2566207
