### ISSUE TITLE
Ender bookshelf causing significant FPS drop

### ISSUE THREAD

**Issue by Miral007** [PrinceOfAmber/Cyclic#819]
Minecraft version & Mod Version:1.12.2, 1.15.3

Single player or Server: Server

Describe problem (what you were doing / what happened): placed ender library and a few ender bookshelves, put a few books in, fps dropped by ~30%

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Miral007** [comment]
seems it only occurs during rain.

**Comment by Miral007** [comment]
nevermind it's back again without rain

**Comment by PrinceOfAmber** [comment]
I'll see if there's something I can optimize

Also, I probably don't need to show on all 4 sides I should make them 1-way, what do you think about that?

If i cant fix it,  maybe i should have an option just like what they do with Storage Drawers where you can turn off the rendering of the items, i bet that is causing the heavy load.

**Comment by Miral007** [comment]
showing on one side might help, could even look better if the other sides are given a frame texture.
