### ISSUE TITLE
Doorbell's crafting recipe conflict

### ISSUE THREAD

**Issue by Minecraftbegin2snow** [PrinceOfAmber/Cyclic#821]
Minecraft version & Mod Version:
mc:1.12.2
mod:1.15.7
Single player or Server:Single player
Describe problem (what you were doing / what happened):
I found a crafting recipe conflict about doorbell.
Screenshots
![1](https://user-images.githubusercontent.com/37864486/40716890-08afc222-643d-11e8-9572-2d0b06658903.png)
MrCrayfish's Furniture's doorbell.

![2](https://user-images.githubusercontent.com/37864486/40716936-2d7e02d0-643d-11e8-9e64-a1839149fc0d.png)
Cyclic's doorbell

![3](https://user-images.githubusercontent.com/37864486/40717001-6bcb70cc-643d-11e8-83d9-0a3ab8656849.png)
A stone button and a note block were in the crafting table.I couldn't craft Cyclic's doorbell.

Crash log (if any):
No crash log
(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
IM going to change to a shaped recipe and probably change it up a little bit

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2568479
