### ISSUE TITLE
possible config derp?

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#822]
Minecraft version & Mod Version:
1.12.2                      1.12.2-1.15.3

Single player or Server:
single player

Describe problem (what you were doing / what happened)
ores are spawning in the nether even when configs are turned off as far as i know
Crash log (if any):
doesnt crash but is odd
cyclic ores
https://pastebin.com/Wa9qit3L

cyclic magic
https://pastebin.com/tAKn6apw

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Minecraftbegin2snow** [comment]
Excuse me,can you upload your game screenshots to github?I'll try to find a method to solve your issue.

**Comment by CharCharthemonkey** [comment]
i was told only to upload the configs so thats wat i did

**Comment by CharCharthemonkey** [comment]
also what screenshots and ill try to get them for you

**Comment by Minecraftbegin2snow** [comment]
I'd like to see your world's Nether or End screenshots.

**Comment by PrinceOfAmber** [comment]
Looks like globalOverride=false is set, which disables only all the modded ores. In other words, this only applies to blocks in THAT standalone config file.


In the second config file on line 781 it has 
`"Nether Ore"=true`
and also 
`B:"End Ore"=true`
on 775

**Comment by CharCharthemonkey** [comment]
umm nether might be possible but the end is not even doable atm cause new world and not even found the portal yet

**Comment by CharCharthemonkey** [comment]
![2018-06-02_20 51 49](https://user-images.githubusercontent.com/30783285/40897688-1c2d8bac-6782-11e8-87d3-75e326314abd.png)
as requested above lol

**Comment by CharCharthemonkey** [comment]
also i found out if you silk touch the ores then they drop as normal which imo is ok just hope it doesnt change hehe

**Comment by PrinceOfAmber** [comment]
In newest versions, silk touch drops the raw ore and not the items ( silk touch enchant). Looks like configs are working fine as well, so thanks for the report!
