### ISSUE TITLE
Cyclic Item Sorter lost colours in GUI

### ISSUE THREAD

**Issue by magicmanuk** [PrinceOfAmber/Cyclic#825]
Minecraft version & Mod Version:
Minecraft: 1.12.2, Cyclic: 1.15.2

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Cyclic Item sorter used to have each row in the GUI colour coded to match the output side - now there is no colour in the GUI at all, so no way of knowing which row relates to which side of the sorter.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Thanks for the report! This has been fixed in previous version  https://github.com/PrinceOfAmber/Cyclic/issues/809
