### ISSUE TITLE
xp pylon

### ISSUE THREAD

**Issue by forestbat** [PrinceOfAmber/Cyclic#828]
I think xp pylon is too small——only 1000000mb，a similar thing in EIO is 2.1 billion mb。
And it can't push xp to neighbor tanks automatically。

**Comment by GrzechuGrek** [comment]
I'd connected XP Pylon with fluid pipes to tank and it's work. So... didn't you forget about fluid pipe extractor?
And extends tanks capacity seems unnecessary too.

**Comment by forestbat** [comment]
@GrzechuGrek Pipes is too slow whatever do you use。

**Comment by PrinceOfAmber** [comment]
You can pipe out into Fluid tanks, which are connected blocks now , might have to pipe into the top.

Feels pretty large already but i only use vanilla style mob farms, advanced ones might be better.

Extractors/pipes beeing too slow and/or not enough capactiy ive heeard before, maybe i can up it or put in config, maybe some speed upgrades....

**Comment by PrinceOfAmber** [comment]
A few updates ago the fluid extractors got a GUI slider to change draw speed :D
