### ISSUE TITLE
Suggestion: Antidote Charm should protect against Dragon Breath

### ISSUE THREAD

**Issue by Milesman34** [PrinceOfAmber/Cyclic#829]
I have noticed that the Antidote Charm does not protect against Dragon Breath. I'm not sure if this is intended behavior or an oversight, but it seems reasonable to expect from the name of the item that it should protect against Dragon Breath. I think that this should be implemented.

**Comment by PrinceOfAmber** [comment]
Does Dragon breath give a status effect over time or is it just Magic damage?

Im just wondering if theres an easy way to detect damage from this vs other sources.

**Comment by Milesman34** [comment]
I think it is magic damage (similar to a lingering Potion of Harming), but I can't be sure. I'm pretty sure there wasn't a status effect, although I was too busy getting out of the way of the attack to pay much attention.

**Comment by Z-Tunic** [comment]
Ender Dragon's Breath Damage Type is "indirectMagic" damage. Doesn't give any status effects as far as I'm aware after testing.

Just making sure... the Dragon Breath is that purple smoke effect that lingers on the ground, right?

**Comment by Milesman34** [comment]
Yes it is.
