### ISSUE TITLE
sack of storage render issue in hotbar

### ISSUE THREAD

**Issue by scalda** [PrinceOfAmber/Cyclic#83]
please see video link for the issue 

[https://www.youtube.com/watch?v=HfoVmVPJATY ](url)

**Comment by PrinceOfAmber** [comment]
Weird, yeah it still renders it in your hand even when its the previous item. Same thing happens for me. ill fix it if i can.

**Comment by PrinceOfAmber** [comment]
Download 1.7.2 for fix
