### ISSUE TITLE
Peat Generator Power Transfer Quirks

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#831]
Minecraft version & Mod Version: 1.12.2 & 1.15.8
Single player or Server: Both
Describe problem (what you were doing / what happened):

Peat Generator exhibits some weird FE power transfer issues, it doesn't seem to transfer power from most FE compatible cables (CoFH Fluxducts, EIO Conduits, Mekanism Cables). As shown in this picture, no FE is getting to the ID battery.
![image](https://user-images.githubusercontent.com/26587049/40993311-3f198af8-68c7-11e8-9924-6e0b74b37abf.png)

However placing compatible FE storage next to the peat generator transfers energy just fine.
![image](https://user-images.githubusercontent.com/26587049/40993346-59a460c8-68c7-11e8-95ab-3cc74ff4f62e.png)

And it gets even better, as you can actually transfer power to Mekanism cables, but only if you connect more than one in a line
![image](https://user-images.githubusercontent.com/26587049/40993407-8dbe1a5c-68c7-11e8-8431-ad15f978c050.png)
![image](https://user-images.githubusercontent.com/26587049/40993424-97515af2-68c7-11e8-9bc1-18399b295828.png)

**Comment by Vyraal1** [comment]
Whoops, seems like this might be related to https://github.com/PrinceOfAmber/Cyclic/issues/788

**Comment by PrinceOfAmber** [comment]
Yeah Ill test it out now that 788 fix is in, hopefully the same fix applies

**Comment by PrinceOfAmber** [comment]
Actually i had to reaply a very similar fix to generator & battery :D
