### ISSUE TITLE
broken enchant:  block reach on mystical agriculture red armor breaks the flight aspect of it

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Cyclic#833]
Minecraft version & Mod Version:
1.12.2-1.15.8

Single player or Server:
single player

Describe problem (what you were doing / what happened):
using the enchant block reach on mystical agriculture red armor breaks the flight aspect of it

Crash log (if any):
doesnt crash

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Did you have anything in the charm slots? 

When i tried with just basic red armor by itself it was working fine for me, both reach and flight:  


https://imgur.com/a/aP8NoDp

**Comment by CharCharthemonkey** [comment]
nope nothing in the slots but for me block reach broke the armor hmm

**Comment by CharCharthemonkey** [comment]
[Charlie's Towny Pack-1.9.zip](https://github.com/PrinceOfAmber/Cyclic/files/2090637/Charlie.s.Towny.Pack-1.9.zip)
heres my "current" version of my modpack if u wanna test on that cause for all i know either its something else in the pack or on mystical agricultres end that might be broken but i dont know hmm

**Comment by PrinceOfAmber** [comment]
Ill import it tomorrow and see what happens

**Comment by PrinceOfAmber** [comment]
What other mods add custom survival flight in there? Does draconic have something that gives flight? or aether legacy?

**Comment by CharCharthemonkey** [comment]
draconic has the draconic armor (orange) for flight and as for aether legacy umm idk if it adds flight lol

**Comment by Darkmega18** [comment]
https://vignette.wikia.nocookie.net/mlp/images/c/c5/Phoenix_wright_hold_it.png/revision/latest?cb=20130324182312
**[hold it!]**
aether adds it's own form of attack range reach and block reach through valkyrie tools.

and fancy that I've actually just discovered that having had used block reach on a piece of armor just completely overwrote and broke the attack range for my valk tools and also for my botania pride ring.

They had been working just prior to enchanting a diamond chestplate with reach and putting it on. The Cyclic reach is massive and I had previously thought it was the combination of my reach and the pride ring reach. But upon taking off reach and just equipping the pride ring, I found the ring no longer worked. and neither did the reach on the valkyrie tools in aether, nor the recently added reach tinker tool buff from aether tinkers valkyrie modifier.

Dieing didn't fix this for me.

so it appears your enchant might be messing with everyone elses. however interestingly the valkyrie lance doesn't seem to have issue with it's attack range so it must be built into the item or something.

I also had actually went to report the pride ring not giving me attack range, and when doing some science this is when I had noticed it. heres the issue I had just posted before my realization.

https://github.com/Vazkii/Botania/issues/2660

**Comment by CharCharthemonkey** [comment]
[latest.log](https://github.com/PrinceOfAmber/Cyclic/files/2151362/latest.log)
as requested and from wat i could tell nothing to even give any hints

**Comment by PrinceOfAmber** [comment]
I just tested with Cyclic 1.17.2, Mystical 1.6.13 and forge 14.23.4.2760. 

Full set of red armor gives me flight. block reach is enchanted on it, both reach and flight working for me.  which was the original report at the top. 

As for the other piece, yes it looks like if more than one mod messes with player reach then forge cant handle it gracefully ( im not sure how to make them compatible i guess they arent, its not like hearts or armor).  Thank you very much for the log file.

Also it looks like #870 linked to this and might resolve this partially.
Only solution here is to configure the modpack to remove all "reach" abilities except one, doesnt matter which.  Then players should not have issues.  Cyclic enchant is easy to disable in config file.

For now i will mark this as resolved and closed .  new issues are always welcome !
