### ISSUE TITLE
Latest Version crashes Steve Carts when being searched in JEI

### ISSUE THREAD

**Issue by Ghostrider231** [PrinceOfAmber/Cyclic#837]
### **Minecraft version & Mod Version:** 
1.12.2-1.15.9

### **Single player or Server:** 
Both (Client-sided Only)

### **Describe problem (what you were doing / what happened):** 

Okay, this is an interesting crash, whenever I have **steve carts (doesn't matter which version)** and **jei (just enough items, also doesn't matter what version is installed)** installed alongside with this I end up having a looping crash involving a rendering item which talks about steve cart's modules when searching it in JEI's search bar.

**Now, what does this cyclic have to do with this?** Well, with the latest version installed that I've provided in this issue post. **Whenever this version is installed,** apparently typing @ste **(or anything that brings up steve cart's items)** in the jei search bar crashes me resulting in saving and quitting then booting me out.

However, If I try to enter that world again, it'll just give me the same crash again (looping crash). Until I clear the jei world settings, so I can access that world again.

**If I try to use an older version, the game behaves normally and won't crash. It's just this very version.**

Issue report on Steve Cart's side: https://github.com/TechReborn/StevesCarts/issues/151

### **Crash log (if any):** 
https://pastebin.com/JUzBPSnk

**Comment by GoryMoon** [comment]
Was an issue on the SC end, you can close this.
