### ISSUE TITLE
Crafting Problem

### ISSUE THREAD

**Issue by mac2040** [PrinceOfAmber/Cyclic#839]
Minecraft 1.1.12 Forge 14.23.4.2707
Cyclic 1.12.2-1.15.9

Single player

When crafting a new item it add a <minecraft:stick>.withTag({}) in sted of <minecraft:stick> in both 2x2 and 3x3 crafting 

no crash

**Comment by PrinceOfAmber** [comment]
Found the bug in the Imbue block and related events, fix coming out tonight

**Comment by PrinceOfAmber** [comment]
Try this fix https://minecraft.curseforge.com/projects/cyclic/files/2572232

**Comment by mac2040** [comment]
thank for the quick fix
