### ISSUE TITLE
Tree Scythe does not harvest Rubber tree leaves from ic2

### ISSUE THREAD

**Issue by scalda** [PrinceOfAmber/Cyclic#84]
Tree Scythe does not harvest Rubber tree leaves from ic2.

**Comment by PrinceOfAmber** [comment]
Yeah, looks like i hardcoded it to look for only vanilla leaves, i should upgrade it. wont work for biomes o plenty / other leaves either.

**Comment by PrinceOfAmber** [comment]
Resolved in 1.7.5
