### ISSUE TITLE
Bundled Cable interaction with Mekanism

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#840]
Minecraft version & Mod Version:
1.12.2
Cyclic-1.12.2-1.15.9

Single player or Server:
SP

Describe problem (what you were doing / what happened):
A Cyclic Bundled Cable touched a Mekanism Universal Cable (energy pipe)

Crash log (if any):
https://paste.dimdev.org/unevonetor.txt

**Comment by PrinceOfAmber** [comment]
Yep fix coming out soon, same root cause as https://github.com/PrinceOfAmber/Cyclic/issues/841

**Comment by PrinceOfAmber** [comment]
Try this fix https://minecraft.curseforge.com/projects/cyclic/files/2572232

**Comment by NillerMedDild** [comment]
Seems fixed, thank you!
