### ISSUE TITLE
[1.12.2] Bows or any item that fires Projectiles are broken, even modded ones like Tinker's Bows/Crossbows/etc.

### ISSUE THREAD

**Issue by Z-Tunic** [PrinceOfAmber/Cyclic#843]
Minecraft: 1.12.2
Forge: 14.23.4.2708

Mods:
Cyclic-1.12.2-1.15.10

Mantle-1.12-1.3.2.24
TConstruct-1.12.2-2.10.1.87

---
Video of the Bug:
https://www.youtube.com/watch?v=4rwGOFkAwRE

So... Bows are broken where they won't work in either the Main-Hand or Off-Hand regardless if you have arrows or not, and even if you have arrows... the projectile won't fire from it but it will consume the arrow as well as the bow's durability.

Items from mods that fire some sort of projectile are affected as well, such as Tinker's Bows/Longbows/Crossbows/Shurikens but only from the Off-Hand... unless you hold a Tinker's Weapon in your Main-Hand, then the Bows/Longbows/Crossbows/Shurikens will work correctly. If it's not a Tinker's Weapon and you attempt to use the Off-Hand... no projectiles will fire but you will consume their ammo/durability.

**Comment by TeetoKaziim** [comment]
Can confirm, even happens with just Cyclic 1.15.10 and Forge 14.23.4.2708 installed.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2573155
