### ISSUE TITLE
[1.12.2] Growth level on Apple sprout of TOP

### ISSUE THREAD

**Issue by TheSnowyChickens** [PrinceOfAmber/Cyclic#845]
Minecraft version & Mod Version:
1.12.2
Cyclic: 1.15.10
Forge: 1.12.2 - 14.23.4.2707

Question:
Is it possible, that you can add this feature to your Apple sprout? (Picture below)
Or is this something, that team TOP has to add?
![growth](https://user-images.githubusercontent.com/29357962/41446754-b58b5720-7051-11e8-8208-9a57c4a64a6a.png)

**Comment by TheSnowyChickens** [comment]
And fast another question, is this size wanted? (Newest Version from today)
![2018-06-18_02 15 13](https://user-images.githubuser content.com/29357962/41513488-95b57252-729d-11e8-9387-8d578ec0179f.png)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2616415

**Comment by TheSnowyChickens** [comment]
Ty. :)
