### ISSUE TITLE
Ender Book Crash

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#846]
Minecraft version & Mod Version:
1.12.2
1.12.2-1.15.10

Single player or Server:
SP

Describe problem (what you were doing / what happened):
One of my users used the Ender Book, and crashed to desktop.
Original report: https://github.com/NillerMedDild/Enigmatica2Expert/issues/105

Crash log (if any):
https://hastebin.com/akawefegiv.sql

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
I put a comment on the other issue.

I loaded version 1.28 of the expert back, havent replicated it yet so still investigating

**Comment by PrinceOfAmber** [comment]
Looks like i do have some chunk loading force action going in 

https://github.com/PrinceOfAmber/Cyclic/blob/c7edb436d41868a015254d219c8909c45e5be6ea/src/main/java/com/lothrazar/cyclicmagic/item/enderbook/ItemEnderBook.java#L164

... seems like it has been there for a while, since at least 2017-07-11 according to git blame, but i cant think of what else would cause corruption like this

**Comment by PrinceOfAmber** [comment]
Ender wing does similar teleportation, investigating overlap https://github.com/PrinceOfAmber/Cyclic/issues/850

**Comment by Xandaros** [comment]
Just had a similar problem: http://tcpst.net/nuto

Was playing in multiplayer and just testing the book to see what it does. The other player, who was standing right next to me (and also next to my target location, as it was only a couple blocks away) heard the noise the book makes and then also crashed.

**Comment by PrinceOfAmber** [comment]
Yep Xandaros crash log also mentions playing sound "net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:252)"

**Comment by PrinceOfAmber** [comment]
Aha, i deleted all my custom sound effect calls and still heard a sound.  So vanilla was trying ot hit up the enderman built in sound, and mine was going on top (plus i was playing them twice and doing weird server/client stuff)

Cleaned that all out for next release so 1.15.13 will be more stable

**Comment by PrinceOfAmber** [comment]
Not sure if this will be a 100% fix but i cleaned up what i can let me know if it dies again https://minecraft.curseforge.com/projects/cyclic/files/2575589

**Comment by NillerMedDild** [comment]
Sounds good, thank you :)
