### ISSUE TITLE
[1.12.2] Conflict: Bows or any item that fires Projectiles breaks Tinker's Tools to the point where everything on that tool is wiped clean.

### ISSUE THREAD

**Issue by Z-Tunic** [PrinceOfAmber/Cyclic#848]
Minecraft: 1.12.2
Forge: 14.23.4.2708

Mods:
Cyclic-1.12.2-1.15.11

Mantle-1.12-1.3.2.24
TConstruct-1.12.2-2.10.1.87

---
Video of Bug:
https://www.youtube.com/watch?v=dNPfxjr-FmI

While the bug which prevented projectiles from being fired was fixed, another bug surfaced... this time it breaks Tinker's Construct Tools quite badly and it's possible it may affect other things.

What happens is that if you have a Tinker's Tool that fires a projectile from it.. the Tool becomes broken to the point where all Tool Parts and modifiers on that Tool are gone with the Durability being strange.

If you have... say a Tinker's Broadsword in your Main-Hand and you use a Vanilla Bow or a Tinker's Tool that uses projectiles from your Off-Hand, the Broadsword instantly breaks with everything wiped from it.

This type of bug didn't occur in Cyclic-1.12.2-1.15.10.

**Comment by CrossJaw** [comment]
Can confirm.
It totally wiped my electrum knightslime longbow. 
https://imgur.com/a/MWuR5Im

**Comment by PrinceOfAmber** [comment]
Hm i thought i fixed this in last version, but you are already on 15.11 so ill have to check again https://github.com/PrinceOfAmber/Cyclic/issues/843

**Comment by PrinceOfAmber** [comment]
SO kind of duplicate, but not really since the fix didnt actually work and caused new issues

**Comment by PrinceOfAmber** [comment]
This fixes it for me. if it comes back or theres something else let me know !!! https://minecraft.curseforge.com/projects/cyclic/files/2573825

**Comment by Z-Tunic** [comment]
Can confirm it's fixed in...

Cyclic-1.12.2-1.15.12

...will let you know if something else happens.
