### ISSUE TITLE
[1.12.1]  Crash when i approached some unpowered cyclic bundled cables

### ISSUE THREAD

**Issue by vvenaya** [PrinceOfAmber/Cyclic#849]
Minecraft version & Mod Version:  
   1.12.1  / cyclic version 1.15.10

Single player or Server:
    Single player

Describe problem (what you were doing / what happened):
    Minecraft crashed when i approached an some unused bundled cables. 
    I am nolonger able to enter my world, it is a perma crash.

Crash log (if any):

     https://paste.dimdev.org/edusapaluy.txt

Something to do with Waila

**Comment by PrinceOfAmber** [comment]
This fixes it for me. if it comes back or theres something else let me know !!! https://minecraft.curseforge.com/projects/cyclic/files/2573825
