### ISSUE TITLE
Tinkers Construct bow broken

### ISSUE THREAD

**Issue by flier268** [PrinceOfAmber/Cyclic#853]
Minecraft version & Mod Version:
Minecraft 1.12.2
 Cyclic-1.12.2-1.15.11

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Here:https://github.com/SlimeKnights/TinkersConstruct/issues/3544

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by NillerMedDild** [comment]
To elaborate, when any ranged weapon is fired, it has its' NBT data reset.
Tested with just Tinkers' Construct, Mantle, JEI and Cyclic version 1.12.2-1.15.11

**Comment by PrinceOfAmber** [comment]
Yes is true, thanks for the report. fix coming out soon https://github.com/PrinceOfAmber/Cyclic/issues/848
