### ISSUE TITLE
Crash [Spawner Seeker]

### ISSUE THREAD

**Issue by tyler489** [PrinceOfAmber/Cyclic#856]
Minecraft version & Mod Version:
1.12

**Cyclic-1.12.2-1.15.11.jar**
Single player or Server:
Server

Describe problem (what you were doing / what happened):

Used the spawner seaker to find a spawner then broke it..  when i used the spawner seaker again server crashed.
Crash log (if any):
http://termbin.com/dd3l
http://termbin.com/7laj
http://termbin.com/0vfj2

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by tyler489** [comment]
After i broke it and used the item again the orb stayed stationary for about 10 seconds then the game crashed

**Comment by PrinceOfAmber** [comment]
Did this happen only the once? Or does it happen every time.  Maybe some conflict with another mod?

Seems like an uncommon occurence, i hunted and broke about 30 spawners on a server testing it out :

![trying to crash short](https://user-images.githubusercontent.com/621529/41579022-ecbc1388-7349-11e8-93e7-b6199da514d6.gif)

**Comment by tyler489** [comment]
It seemed consistant if it was locked onto a spawner that didnt exist... but if i moved away it would work fine.. i do have mods changing spawners drops... enderio adds broken spawners and actually additions adds spawner shards but neither one changes the spawner itself.. also have recurent  complex adding vanilla blaze spawners to the overworld.

**Comment by tyler489** [comment]
Also scaling health

**Comment by tyler489** [comment]
https://minecraft.curseforge.com/projects/enigmatica2expert

**Comment by Aaron1011** [comment]
This is almost certainly caused by https://github.com/PrinceOfAmber/Cyclic/issues/863 (`ItemProjectileDungeon` corresponds to Spawner Seeker)

**Comment by tyler489** [comment]
Interesting.. but im not using spongeforge. I was told if you want to come on the server and test that you could

**Comment by Aaron1011** [comment]
@tyler489: The issue exists with or without SpongeForge installed. Installing SpongeForge makes the issue more visible, but doesn't create it.

**Comment by PrinceOfAmber** [comment]
Changed some things in the other issue, also the config for disabling threading should help https://minecraft.curseforge.com/projects/cyclic/files/2578660
