### ISSUE TITLE
Ender Book Crash

### ISSUE THREAD

**Issue by wellsie514** [PrinceOfAmber/Cyclic#857]
Minecraft version & Mod Version: 1.12 / recent. All the Mods 3 pack

Single player or Server: Server

Describe problem (what you were doing / what happened): Crash on Ender book teleportation. I've seen previous posts about crashes with the ender book. I can replicate this crash as it _only happen when flying / in the air_. I will consistently crash when using the Ender book if not firmly planted on the ground. The coordinates / length of the teleport does not appear to be relevant. 

Crash log (if any):

**Comment by PrinceOfAmber** [comment]
Maybe related to https://github.com/PrinceOfAmber/Cyclic/issues/846 , maybe not. I will test it while flying

**Comment by PrinceOfAmber** [comment]
Not sure if this will be a 100% fix but i cleaned up what i can let me know if it dies again https://minecraft.curseforge.com/projects/cyclic/files/2575589
