### ISSUE TITLE
Conveyor Behaviour Problems

### ISSUE THREAD

**Issue by TeetoKaziim** [PrinceOfAmber/Cyclic#858]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Forge: 14.23.4.2708
Cyclic: 1.15.12

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):

When Items first hit an upward ramp conveyor, even one of "slowest" speed, they are launched several blocks into the air and off the conveyor.

Further, if your conveyor ramp IS long enough that the items land back on it, when it gets to the top of the ramp it gets stuck on the edge of the next "flat" conveyor:

https://i.imgur.com/yGnIcol.png

PS: Really like the new conveyor models and graphics, they're snazzy. :3

**Comment by PrinceOfAmber** [comment]
AHA
![smoooooth](https://user-images.githubusercontent.com/621529/41806101-ef67de1c-766b-11e8-947c-f49cccdb5c73.gif)
 much smoother now

**Comment by TeetoKaziim** [comment]
Ooh, that's silky :3 I am excited :3

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2575589
