### ISSUE TITLE
Experience Pylon not working properly

### ISSUE THREAD

**Issue by rebeccap2012** [PrinceOfAmber/Cyclic#860]
Minecraft version & Mod Version:
1.12.2-1.15.13

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Once the pylon is completely empty (through spraying orbs) it won't collect exp given from player. Though if some exp remains in the pylon it will continue to collect.
Even a newly made and placed pylon isn't accepting exp.

**Comment by PrinceOfAmber** [comment]
Yep confirmed. ONLY when pylon is empty.

Ive seen this bug before, but i couldnt narrow it down or make it happen.   https://github.com/DarkPacks/SevTech-Ages/issues/2898

Steps to reproduce:
- get pylon fully 100% empty (make a new one or just empty with spray as you said)
- have non-zero experience as a player (say 2 levels)
- press all button
- player has zero exp, and pylon has zero exp

Expected result: 
- pylon should have absorbed that exp

**Comment by CharCharthemonkey** [comment]
ive seen that too but i just assumed the fluid pipes was pulling out the XP faster then it would register on the pylon

**Comment by rebeccap2012** [comment]
Thank you guys, it seems to be working again now :)
