### ISSUE TITLE
Auto-torch issue with moving via shift-click

### ISSUE THREAD

**Issue by CloWnicide** [PrinceOfAmber/Cyclic#862]
Minecraft version & Mod Version: MC Version - 1.12.2; Mod Version - 1.14.9

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Issue with shift clicking the auto-torch item into my inventory, seems to be having an issue with Micdoodle core and trying to figure out a place to actually put the item. 2nd time this has happened with this specific item.

Crash log (if any): 
<details>
<summary> Click to expand </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  EECore (ExpandedEquivalence-1.12.2-4r.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.16-99.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.11.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/25/18 6:13 PM
Description: Ticking entity

java.lang.RuntimeException: Do not check permissions on client side! Node: cyclic.player.modify
	at com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler.hasPermission(FTBUtilitiesPermissionHandler.java:44)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.lothrazar.cyclicmagic.registry.PermissionRegistry.hasPermissionHere(PermissionRegistry.java:41)
	at com.lothrazar.cyclicmagic.util.UtilPlaceBlocks.placeStateSafe(UtilPlaceBlocks.java:87)
	at com.lothrazar.cyclicmagic.util.UtilPlaceBlocks.placeStateSafe(UtilPlaceBlocks.java:69)
	at com.lothrazar.cyclicmagic.item.bauble.ItemAutoTorch.onTick(ItemAutoTorch.java:64)
	at com.lothrazar.cyclicmagic.item.base.BaseCharm.func_77663_a(BaseCharm.java:91)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:364)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:386)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler.hasPermission(FTBUtilitiesPermissionHandler.java:44)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.lothrazar.cyclicmagic.registry.PermissionRegistry.hasPermissionHere(PermissionRegistry.java:41)
	at com.lothrazar.cyclicmagic.util.UtilPlaceBlocks.placeStateSafe(UtilPlaceBlocks.java:87)
	at com.lothrazar.cyclicmagic.util.UtilPlaceBlocks.placeStateSafe(UtilPlaceBlocks.java:69)
	at com.lothrazar.cyclicmagic.item.bauble.ItemAutoTorch.onTick(ItemAutoTorch.java:64)
	at com.lothrazar.cyclicmagic.item.base.BaseCharm.func_77663_a(BaseCharm.java:91)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:364)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:386)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
	Entity ID: 879
	Entity Name: Matricide
	Entity's Exact location: 13.35, 64.00, 55.65
	Entity's Block location: World: (13,64,55), Chunk: (at 13,4,7 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.09, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Matricide'/879, l='MpServer', x=13.35, y=64.00, z=55.65]]
	Chunk stats: MultiplayerChunkCache: 3405, 3405
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (508,71,332), Chunk: (at 12,4,12 in 31,20; contains blocks 496,0,320 to 511,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13071250 game time, 15527604 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 210 total; [EntitySpider['Spider'/4612, l='MpServer', x=-40.50, y=88.00, z=26.50], EntityChickensChicken['Bone White Chicken'/1034, l='MpServer', x=47.50, y=68.00, z=86.50], EntitySkeleton['Skeleton'/4623, l='MpServer', x=-22.27, y=70.00, z=94.46], EntityWitherWitch['Wither Witch'/11791, l='MpServer', x=-40.50, y=64.00, z=-3.71], EntityZombie['Zombie'/4624, l='MpServer', x=-18.50, y=82.00, z=26.50], EntityCreeper['Creeper'/11793, l='MpServer', x=71.50, y=59.00, z=123.50], EntityZombie['Zombie'/4627, l='MpServer', x=-12.50, y=82.00, z=58.28], EntityPegasus['Pegasus'/1044, l='MpServer', x=6.50, y=68.00, z=110.50], EntityWitherCat['Wither Cat'/11797, l='MpServer', x=-44.30, y=64.00, z=1.50], EntityWitherCat['Wither Cat'/11798, l='MpServer', x=-36.50, y=64.00, z=-6.50], EntityWitherCat['Wither Cat'/11799, l='MpServer', x=-40.50, y=64.00, z=-2.03], EntityWitherCat['Wither Cat'/11800, l='MpServer', x=-37.50, y=64.00, z=-4.50], EntityChocobo['Chocobo'/1049, l='MpServer', x=3.50, y=87.00, z=83.18], EntityChocobo['Chocobo'/1050, l='MpServer', x=3.50, y=87.00, z=84.87], EntityChocobo['Chocobo'/1051, l='MpServer', x=11.00, y=87.00, z=73.11], EntityChocobo['Chocobo'/1052, l='MpServer', x=7.87, y=87.00, z=85.87], EntityChocobo['Chocobo'/1053, l='MpServer', x=7.50, y=87.00, z=80.50], EntityChocobo['Chocobo'/1054, l='MpServer', x=3.50, y=87.00, z=81.50], EntityGib['unknown'/4641, l='MpServer', x=-18.50, y=83.50, z=26.50], EntityGib['unknown'/4642, l='MpServer', x=-18.77, y=83.28, z=26.27], EntityGib['unknown'/4643, l='MpServer', x=-18.23, y=83.28, z=26.73], EntityGib['unknown'/4645, l='MpServer', x=-12.50, y=83.50, z=58.28], EntityBlightFire['entity.BlightFire.name'/11813, l='MpServer', x=-40.50, y=65.20, z=-3.71], EntityGib['unknown'/4646, l='MpServer', x=-12.42, y=83.28, z=58.63], EntityGib['unknown'/4647, l='MpServer', x=-12.58, y=83.28, z=57.94], EntityZombie['Zombie'/3112, l='MpServer', x=8.50, y=64.00, z=33.44], EntityZombie['Zombie'/3114, l='MpServer', x=9.74, y=64.00, z=21.54], EntityGib['unknown'/3116, l='MpServer', x=8.50, y=65.50, z=33.44], EntityGib['unknown'/3117, l='MpServer', x=8.22, y=65.28, z=33.23], EntityGib['unknown'/3118, l='MpServer', x=8.78, y=65.28, z=33.64], EntityGib['unknown'/3120, l='MpServer', x=9.74, y=65.50, z=21.54], EntityGib['unknown'/3121, l='MpServer', x=9.50, y=65.28, z=21.29], EntityGib['unknown'/3122, l='MpServer', x=9.99, y=65.28, z=21.78], EntityZombie['Zombie'/9786, l='MpServer', x=9.35, y=64.00, z=52.11], EntityGib['unknown'/9797, l='MpServer', x=9.35, y=65.50, z=52.11], EntityGib['unknown'/9798, l='MpServer', x=9.68, y=65.28, z=51.99], EntityGib['unknown'/9799, l='MpServer', x=9.02, y=65.28, z=52.24], EntityGib['unknown'/1610, l='MpServer', x=8.70, y=71.50, z=21.05], EntityGib['unknown'/1611, l='MpServer', x=8.81, y=71.28, z=21.38], EntityGib['unknown'/1612, l='MpServer', x=8.59, y=71.28, z=20.71], EntityBat['Bat'/8269, l='MpServer', x=-33.25, y=58.99, z=76.40], EntityBat['Bat'/4688, l='MpServer', x=-54.49, y=58.03, z=-4.51], EntityGib['unknown'/1618, l='MpServer', x=3.40, y=71.50, z=20.75], EntityZombie['Zombie'/4178, l='MpServer', x=14.28, y=64.00, z=37.50], EntityGib['unknown'/1619, l='MpServer', x=3.74, y=71.28, z=20.84], EntityGib['unknown'/1620, l='MpServer', x=3.06, y=71.28, z=20.67], EntityZombie['Zombie'/5204, l='MpServer', x=-9.82, y=76.00, z=52.24], EntityBat['Bat'/8278, l='MpServer', x=-39.71, y=58.33, z=71.03], EntityGib['unknown'/4183, l='MpServer', x=14.28, y=65.50, z=37.50], EntityGib['unknown'/5207, l='MpServer', x=-9.82, y=77.50, z=52.24], EntityGib['unknown'/4184, l='MpServer', x=14.27, y=65.28, z=37.15], EntityGib['unknown'/5208, l='MpServer', x=-9.62, y=77.28, z=51.95], EntityGib['unknown'/4185, l='MpServer', x=14.29, y=65.28, z=37.85], EntityGib['unknown'/5209, l='MpServer', x=-10.01, y=77.28, z=52.53], EntityGib['unknown'/1626, l='MpServer', x=8.50, y=65.63, z=34.14], EntityGib['unknown'/1627, l='MpServer', x=8.38, y=65.40, z=34.47], EntityGib['unknown'/1628, l='MpServer', x=8.62, y=65.40, z=33.81], EntityZombie['Zombie'/4702, l='MpServer', x=4.04, y=70.00, z=20.28], EntitySkeleton['Skeleton'/6239, l='MpServer', x=9.11, y=64.00, z=51.35], EntityGib['unknown'/4709, l='MpServer', x=4.04, y=71.50, z=20.28], EntityGib['unknown'/4710, l='MpServer', x=3.95, y=71.28, z=19.94], EntityGib['unknown'/4711, l='MpServer', x=4.12, y=71.28, z=20.62], EntityZombie['Zombie'/5735, l='MpServer', x=4.72, y=58.00, z=43.50], EntityGib['unknown'/6247, l='MpServer', x=9.11, y=65.50, z=51.35], EntityZombie['Zombie'/5736, l='MpServer', x=14.25, y=58.00, z=37.55], EntityGib['unknown'/6248, l='MpServer', x=8.79, y=65.28, z=51.50], EntityGib['unknown'/6249, l='MpServer', x=9.42, y=65.28, z=51.19], EntityGib['unknown'/5738, l='MpServer', x=4.72, y=59.50, z=43.50], EntityGib['unknown'/5739, l='MpServer', x=5.05, y=59.28, z=43.59], EntityGib['unknown'/5740, l='MpServer', x=4.38, y=59.28, z=43.41], EntityItemLoot['item.item.feather'/4718, l='MpServer', x=50.09, y=68.00, z=84.98], EntitySkeleton['Skeleton'/5231, l='MpServer', x=-14.22, y=76.00, z=56.31], EntityGib['unknown'/5748, l='MpServer', x=14.25, y=59.50, z=37.55], EntityGib['unknown'/5237, l='MpServer', x=-14.22, y=77.50, z=56.31], EntityGib['unknown'/5749, l='MpServer', x=14.17, y=59.28, z=37.21], EntityGib['unknown'/5238, l='MpServer', x=-14.01, y=77.28, z=56.59], EntityGib['unknown'/5750, l='MpServer', x=14.32, y=59.28, z=37.89], EntityGib['unknown'/5239, l='MpServer', x=-14.42, y=77.28, z=56.02], EntityZombie['Zombie'/5250, l='MpServer', x=5.79, y=64.00, z=36.70], EntityGib['unknown'/5255, l='MpServer', x=5.79, y=65.50, z=36.70], EntityGib['unknown'/5256, l='MpServer', x=5.69, y=65.28, z=36.37], EntityGib['unknown'/5257, l='MpServer', x=5.89, y=65.28, z=37.04], EntityRat['Rat'/10900, l='MpServer', x=-4.50, y=64.00, z=24.50], EntityRat['Rat'/10901, l='MpServer', x=-5.50, y=64.00, z=25.50], EntityRat['Rat'/10902, l='MpServer', x=-9.50, y=64.00, z=25.50], GoatEntity['Goat'/1176, l='MpServer', x=-90.66, y=64.00, z=38.48], EntityFallenKnight['Fallen Knight'/4761, l='MpServer', x=-19.50, y=70.00, z=98.50], EntityRat['Rat'/10905, l='MpServer', x=-25.50, y=88.00, z=-29.50], GoatEntity['Goat'/1178, l='MpServer', x=-99.50, y=64.00, z=35.50], EntityCreeper['Creeper'/4768, l='MpServer', x=-64.50, y=52.00, z=55.50], EntityChocobo['Chocobo'/1187, l='MpServer', x=1.09, y=87.00, z=85.58], EntityChocobo['Chocobo'/1188, l='MpServer', x=6.73, y=87.00, z=66.31], EntityChocobo['Chocobo'/1189, l='MpServer', x=5.94, y=87.00, z=78.56], EntityGib['unknown'/4774, l='MpServer', x=-22.27, y=71.50, z=94.46], EntityGib['unknown'/4775, l='MpServer', x=-22.42, y=71.28, z=94.78], EntityGib['unknown'/4776, l='MpServer', x=-22.12, y=71.28, z=94.15], EntityItemLoot['item.tile.sapling.oak'/9908, l='MpServer', x=-20.21, y=64.00, z=14.29], GoatEntity['Goat'/1719, l='MpServer', x=309.50, y=65.00, z=-120.50], GoatEntity['Goat'/1720, l='MpServer', x=310.50, y=65.00, z=-122.50], EntitySkeleton['Skeleton'/6335, l='MpServer', x=10.27, y=58.00, z=37.49], EntityGib['unknown'/6346, l='MpServer', x=10.27, y=59.50, z=37.49], EntityGib['unknown'/6347, l='MpServer', x=10.02, y=59.28, z=37.25], EntityGib['unknown'/6348, l='MpServer', x=10.52, y=59.28, z=37.74], EntitySpider['Spider'/9943, l='MpServer', x=-37.01, y=58.62, z=27.12], EntitySpider['Spider'/9944, l='MpServer', x=-26.50, y=58.00, z=23.50], EntitySpider['Spider'/9945, l='MpServer', x=-22.50, y=58.00, z=26.50], VengeanceSpirit['Vengeance Spirit'/5338, l='MpServer', x=-10.79, y=64.00, z=54.30], EntityAncientGolem['Ice Golem'/8934, l='MpServer', x=-27.50, y=58.00, z=34.50], VengeanceSpirit['Vengeance Spirit'/12014, l='MpServer', x=1.38, y=64.00, z=56.51], EntityItemLoot['item.item.feather'/4335, l='MpServer', x=48.17, y=68.00, z=86.38], GoatEntity['Goat'/2295, l='MpServer', x=445.50, y=64.00, z=324.50], EntityCustomArrow['entity.draconicevolution:CustomArrow.name'/9463, l='MpServer', x=-8.95, y=63.96, z=57.04], GoatEntity['Goat'/2296, l='MpServer', x=444.50, y=64.00, z=324.50], GoatEntity['Goat'/2297, l='MpServer', x=446.89, y=64.00, z=323.50], GoatEntity['Goat'/2305, l='MpServer', x=448.50, y=66.00, z=327.50], GoatEntity['Goat'/2311, l='MpServer', x=-327.50, y=101.00, z=-60.50], GoatEntity['Goat'/2312, l='MpServer', x=-326.50, y=100.00, z=-57.50], GoatEntity['Goat'/2313, l='MpServer', x=-325.50, y=101.00, z=-58.50], EntitySkeleton['Skeleton'/12554, l='MpServer', x=9.89, y=64.00, z=43.48], EntityGib['unknown'/12044, l='MpServer', x=1.25, y=64.00, z=57.57], EntityGib['unknown'/12045, l='MpServer', x=1.15, y=64.00, z=56.14], EntityGib['unknown'/12046, l='MpServer', x=1.15, y=64.00, z=56.29], EntityGib['unknown'/12047, l='MpServer', x=-2.30, y=64.00, z=55.77], EntityGib['unknown'/12048, l='MpServer', x=-1.25, y=64.00, z=56.84], EntityGib['unknown'/12049, l='MpServer', x=-2.00, y=64.00, z=56.73], EntityGib['unknown'/12567, l='MpServer', x=9.89, y=65.50, z=43.48], EntityGib['unknown'/12568, l='MpServer', x=10.24, y=65.28, z=43.48], EntityGib['unknown'/12569, l='MpServer', x=9.54, y=65.28, z=43.48], EntitySkeleton['Skeleton'/2843, l='MpServer', x=7.45, y=64.00, z=37.92], EntityGib['unknown'/2846, l='MpServer', x=7.45, y=65.50, z=37.92], EntityZombie['Zombie'/11038, l='MpServer', x=5.68, y=59.00, z=46.71], EntityGib['unknown'/2847, l='MpServer', x=7.69, y=65.28, z=37.67], EntityZombie['Zombie'/11039, l='MpServer', x=3.53, y=58.00, z=44.73], EntityGib['unknown'/2848, l='MpServer', x=7.20, y=65.28, z=38.17], EntityGib['unknown'/11051, l='MpServer', x=5.68, y=60.50, z=46.71], EntityGib['unknown'/11052, l='MpServer', x=5.93, y=60.28, z=46.95], EntityGib['unknown'/11053, l='MpServer', x=5.42, y=60.28, z=46.47], EntityGib['unknown'/11055, l='MpServer', x=3.53, y=59.50, z=44.73], EntityGib['unknown'/11056, l='MpServer', x=3.20, y=59.28, z=44.84], EntityGib['unknown'/11057, l='MpServer', x=3.87, y=59.28, z=44.62], EntitySquid['Squid'/5942, l='MpServer', x=-8.58, y=53.74, z=97.74], GoatEntity['Goat'/3899, l='MpServer', x=162.50, y=64.00, z=432.50], GoatEntity['Goat'/3900, l='MpServer', x=160.50, y=64.00, z=434.50], GoatEntity['Goat'/3901, l='MpServer', x=158.50, y=67.00, z=431.50], VengeanceSpirit['Vengeance Spirit'/9540, l='MpServer', x=8.33, y=64.00, z=55.54], EntityBat['Bat'/12620, l='MpServer', x=-20.64, y=58.18, z=68.76], EntityBat['Bat'/12621, l='MpServer', x=-23.20, y=58.21, z=69.60], EntityBat['Bat'/12622, l='MpServer', x=-28.07, y=58.01, z=69.30], EntityZombie['Zombie'/2383, l='MpServer', x=3.41, y=70.00, z=17.90], EntityGib['unknown'/2392, l='MpServer', x=3.41, y=71.50, z=17.90], EntityGib['unknown'/2393, l='MpServer', x=3.74, y=71.28, z=18.02], EntityGib['unknown'/2394, l='MpServer', x=3.08, y=71.28, z=17.78], EntityBat['Bat'/880, l='MpServer', x=20.46, y=25.85, z=-0.50], EntityPig['Pig'/881, l='MpServer', x=14.28, y=64.00, z=-1.47], EntityPig['Pig'/882, l='MpServer', x=8.30, y=64.00, z=-6.27], EntityPig['Pig'/883, l='MpServer', x=8.25, y=64.00, z=13.50], GCEntityClientPlayerMP['Matricide'/879, l='MpServer', x=13.35, y=64.00, z=55.65], EntityBat['Bat'/8568, l='MpServer', x=-7.25, y=52.42, z=-22.53], EntityBat['Bat'/8569, l='MpServer', x=-4.48, y=53.00, z=-21.81], VengeanceSpirit['Vengeance Spirit'/11649, l='MpServer', x=10.30, y=64.00, z=54.47], EntitySkeleton['Skeleton'/3986, l='MpServer', x=13.51, y=82.00, z=24.71], EntityCreeper['Creeper'/917, l='MpServer', x=-36.22, y=70.00, z=40.51], EntityGib['unknown'/3990, l='MpServer', x=13.51, y=83.50, z=24.71], EntityGib['unknown'/3991, l='MpServer', x=13.85, y=83.28, z=24.68], EntityGib['unknown'/3992, l='MpServer', x=13.16, y=83.28, z=24.74], EntityBat['Bat'/3482, l='MpServer', x=-33.25, y=59.08, z=1.28], EntitySkeleton['Skeleton'/4515, l='MpServer', x=5.88, y=64.00, z=23.66], EntityCustomXPOrb['entity.custom_xp_orb.name'/12197, l='MpServer', x=0.72, y=64.00, z=56.75], EntitySkeleton['Skeleton'/4518, l='MpServer', x=6.33, y=64.00, z=25.50], EntityCustomXPOrb['entity.custom_xp_orb.name'/12199, l='MpServer', x=0.30, y=64.00, z=56.75], EntityCreeper['Creeper'/936, l='MpServer', x=-30.50, y=58.00, z=-14.22], EntityGib['unknown'/4520, l='MpServer', x=5.88, y=65.50, z=23.66], EntityGib['unknown'/4521, l='MpServer', x=5.62, y=65.28, z=23.43], EntityCustomXPOrb['entity.custom_xp_orb.name'/12201, l='MpServer', x=0.40, y=64.00, z=56.75], EntityGib['unknown'/4522, l='MpServer', x=6.15, y=65.28, z=23.89], EntityCustomXPOrb['entity.custom_xp_orb.name'/12203, l='MpServer', x=-1.01, y=64.00, z=55.25], EntityGib['unknown'/4524, l='MpServer', x=6.33, y=65.50, z=25.50], EntityGib['unknown'/4525, l='MpServer', x=6.07, y=65.28, z=25.26], EntityGib['unknown'/4526, l='MpServer', x=6.58, y=65.28, z=25.74], EntityGib['unknown'/5048, l='MpServer', x=-17.50, y=71.50, z=98.50], EntityGib['unknown'/5049, l='MpServer', x=-17.38, y=71.28, z=98.83], EntityLatchedRenderer['unknown'/1466, l='MpServer', x=13.35, y=64.00, z=55.65], EntityGib['unknown'/5050, l='MpServer', x=-17.62, y=71.28, z=98.17], EntityGib['unknown'/5052, l='MpServer', x=-19.50, y=71.50, z=98.50], EntityGib['unknown'/5053, l='MpServer', x=-19.59, y=71.28, z=98.84], EntityGib['unknown'/5054, l='MpServer', x=-19.41, y=71.28, z=98.16], EntityBat['Bat'/959, l='MpServer', x=-8.35, y=58.71, z=-17.43], EntityWitherWitch['Wither Witch'/4548, l='MpServer', x=-39.50, y=64.00, z=-4.50], EntityItemFrame['entity.ItemFrame.name'/2508, l='MpServer', x=39.50, y=94.50, z=202.97], EntityItemFrame['entity.ItemFrame.name'/2509, l='MpServer', x=40.50, y=94.50, z=202.97], EntityItemFrame['entity.ItemFrame.name'/2510, l='MpServer', x=41.50, y=94.50, z=202.97], EntityPig['Pig'/975, l='MpServer', x=9.70, y=64.00, z=-6.47], EntityFallenKnight['Fallen Knight'/4564, l='MpServer', x=-17.50, y=70.00, z=98.50], EntitySpider['Spider'/4569, l='MpServer', x=38.50, y=70.00, z=91.50], EntityZombie['Zombie'/986, l='MpServer', x=8.70, y=70.00, z=21.05], EntitySkeleton['Skeleton'/988, l='MpServer', x=3.40, y=70.00, z=20.75], EntitySkeleton['Skeleton'/990, l='MpServer', x=8.50, y=64.13, z=34.14], EntitySpider['Spider'/991, l='MpServer', x=5.81, y=77.00, z=37.30], EntityBat['Bat'/10218, l='MpServer', x=-49.99, y=52.05, z=-4.75], EntityBat['Bat'/10219, l='MpServer', x=-54.49, y=52.05, z=-7.89], EntityBat['Bat'/10220, l='MpServer', x=-50.52, y=52.05, z=-4.75], GoatEntity['Goat'/3053, l='MpServer', x=165.50, y=64.00, z=-225.50], EntityBat['Bat'/10221, l='MpServer', x=-55.72, y=52.14, z=-4.75], GoatEntity['Goat'/3054, l='MpServer', x=164.50, y=99.00, z=-222.50], EntityBat['Bat'/10222, l='MpServer', x=-25.60, y=58.02, z=70.60], GoatEntity['Goat'/3055, l='MpServer', x=164.50, y=64.00, z=-225.50], EntityChickensChicken['Bone White Chicken'/1021, l='MpServer', x=51.50, y=67.00, z=83.50], EntityChickensChicken['Bone White Chicken'/1022, l='MpServer', x=51.50, y=67.00, z=84.50], EntityChickensChicken['Bone White Chicken'/1023, l='MpServer', x=49.50, y=68.00, z=85.50], EntityCustomXPOrb['entity.custom_xp_orb.name'/9727, l='MpServer', x=6.44, y=64.00, z=56.12]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
</details>

Edit: If the full log is needed, please let me know.

**Comment by PrinceOfAmber** [comment]
Aha I remember this one.  It has since been fixed in the latest versions, but thanks for the report and the log ! 

https://github.com/PrinceOfAmber/Cyclic/issues/796

**Comment by PrinceOfAmber** [comment]
If you are playing on a server or modpack, let your admins know that they can update the mod to fix this
