### ISSUE TITLE
[1.12.2] Add Config Option For Uncrafting Grinder Speed and Energy Usage

### ISSUE THREAD

**Issue by Andronomos** [PrinceOfAmber/Cyclic#864]
Could you make the Uncrafting Grinder speed and energy usage configurable? I'm using the lootbags mod that contains a lot of grindable stackable items and my system gets backed up because the grinder is painfully slow. I've been trying to mitigate the problem by adding more grinders but their power generation is so ridiculously high that I have to give each one it's own power cell.

EDIT:

Would is be possible to also add in a way to see the items you'll get from the grinder for a particular item?

**Comment by PrinceOfAmber** [comment]
There is already a config for energy, so you can customize that. (maybe i should reduce the default if thats too much) 

`  # Fuel/Energy/RF cost to run machine [range: 0 ~ 500000, default: 200]
        I:uncrafting_block=200`

.. but i dont think I have one for speed, so I will look into that

**Comment by Andronomos** [comment]
To be fair, I was using basic cells from TE. Perhaps if I upgrade them they will be able to power the grinders for longer. Might actually make the grinder more balanced that way now that I think about it.

But the speed config would definitely be nice to have. In fact, didn't Cyclic used to have a config option for it? I'm pretty sure I remember changing it.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2591567
