### ISSUE TITLE
Black Concrete Powder now makes White Concrete in Hydrator

### ISSUE THREAD

**Issue by Sorbe** [PrinceOfAmber/Cyclic#867]
**Minecraft version & Mod Version:**
Minecraft 1.12.2
Java 8u172 x64
Sevtech 3.0.8
Cyclic 1.15.8

**Single player or Server:**
SMP - Client/Server

**Describe problem (what you were doing / what happened):**
I had just made 1000 Black Concrete Powder and I tried to use the Hydrator to turn into Black Concrete.
Instead it started to convert it all into White Concrete.  (see screenshots)

![2018-06-30_01 33 44](https://user-images.githubusercontent.com/7958470/42123394-563ef5cc-7c06-11e8-8963-3462205edd18.png)
![2018-06-30_01 33 45](https://user-images.githubusercontent.com/7958470/42123395-56569d26-7c06-11e8-916a-67dcb9c16136.png)

**Comment by Sorbe** [comment]
Apologies if this unexpected outcome is a modpack specific bug.

![2018-06-30_02 08 20](https://user-images.githubusercontent.com/7958470/42123654-97791ab4-7c0a-11e8-93e5-647ff5b2a549.png)

**Comment by Meatnog** [comment]
I am having the same issue on SevTech 3.0.8

**Comment by Vercci** [comment]
Also playing on Sevtech. This used to work before the last update to Sevtech which had a Cyclic update. Quite a few machines including the Hydrator now use power. Back when it only required redstone the recipe was fine.


Also personally, the hydrator's power meter doesn't fill with red but it functions. OP's screenshot has red so  I dunno what went wrong there.

**Comment by PrinceOfAmber** [comment]
Hmm last thing I changed was I think here where i fixed a bunch of bugs so it must have creeped in here. Looks like metadata error... recipe itself is fine just bug in execution https://github.com/PrinceOfAmber/Cyclic/issues/673

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2578660
