### ISSUE TITLE
[1.12.2] 3 little bugs (Wireless Energy)

### ISSUE THREAD

**Issue by TheSnowyChickens** [PrinceOfAmber/Cyclic#873]
Minecraft version & Mod Version:
1.12.2 - MC
1.12.2 - 14.23.4.2727 Forge
1.12.2 - 1.16.0 Cyclic

Single player or Server:
Singleplayer

Describe problem (what you were doing / what happened):
1. - You can see in the left corner the TOP display with a full RF bar, but in your GUI from the energy transfer Node is nothing aka its empty. (Edit: after a relog the bar is filled)
2. - You can see in the chat "tile.thermalexpansion.machine.name", this occurs if I press the "Detect target block" Button. Connected to this GPS marker is a "Redstone Furnace"
3. - After a relog, the "transfer Rate" slider reset to 500
![2018-07-08_20 00 29](https://user-images.githubusercontent.com/29357962/42422619-a6c3837a-82e9-11e8-87d7-2ced22ff0e06.png)

Crash log (if any):
Nope

**Comment by PrinceOfAmber** [comment]
Thanks for the bug reports ill get these fixed up soon

**Comment by PrinceOfAmber** [comment]
In my test it seems like TOP is working ok so far, but ill dig into it a bit more . This was with TOP  1.4.23 and forge 14.23.3.2655

![top gif](https://user-images.githubusercontent.com/621529/42488756-fd018246-83bb-11e8-86ff-3601e66d2129.gif)

**Comment by TheSnowyChickens** [comment]
TOP worked good, it was just a refresh rate bug in your GUI from the Energy Transfer Node. (Its like Immersive Engineering, first look in the machine = no energy, *close* GUI and open it again = full energy)

**Comment by PrinceOfAmber** [comment]
Oh i see. so ill try reloading the world and NOT opening GUI to replicate that part, hopefully its an easy fix for next version

Bugs 2 and 3 fixed in this version  https://minecraft.curseforge.com/projects/cyclic/files/2581557

**Comment by TheSnowyChickens** [comment]
Thx
