### ISSUE TITLE
[suggestion] Error checking on Sack of Holding

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#876]
Just today, I had a soul shattering experience. after taking several hours to mcguiver up an enhanced storage network from the mod of the same name on my server, along with several generators and other bits and transferring close to 4k items of special loot, resources and mundanes from my super dangerzoned chests (as far as it's cell was concerned) I was moving stuff around my base using the sack of holding to make it faster to not drop inventories and energy storage.

It works fine for machines for the most part, but when I came to the storage drive which held my cells it apparently null pointered and didn't pick it up and picked up a phantom empty copy that was placed when I used the bag again. what this essentially did was destroy my original drive and when placed down place an empty one which as a result destroyed all my items. it also shot some errors into the console. Because when I noticed there was still a drive where I had picked it up from that drive just turned out to be a phantom...

what I'd like to suggest is that you somehow have a form of error checking on the bag that if it was to pick up something but hits a snag with stuff that it doesn't understand  (like projectE alchemical chests from sometime back before they updated, and now these storage drives) it doesn't complete the picking up process or some kind of safeguard.

if not, does this mean my safeguard is only "knowledge" and blacklisting things that are known to have errors?

https://pastebin.com/hC2050fH

Heres a paste of multicraft's console stuff in the section when it happened, to when I left after confirming it with creative and looking for my drive to see if it really went boom and stuff... read from bottom to top, cause multicraft console is upside down so new stuff is at top. :V 
there wasn't an actual crash however. thankfully i had to remove a mod earlier in the day cause of errors also which procced an automatic backup due to it's items going poof which I can roll back to and for the bother I can just cheat anything in particular back in...

**Comment by PrinceOfAmber** [comment]
Note to self: Bug is very easy to reproduce, dont even need that many items

1 disc drive
1 64k disk
add a few stocks of cobblestone
pick it up with the bag and place in different location

Refined Storage version 1.5.34

**Comment by Darkmega18** [comment]
well, I took the bag and used it on most everything and it worked fine.

but with the storage drive, I picked it up but it was still there but my bag was glowing. I didn't notice at first, i thought it was lag.
I placed down the drive that was in my bag, but it was empty. no cells in it. but it looked like there was cells at first.
I turn to the side, notice the drive with my original cells is still in it's original spot, I at first think it's the duplication bug I used to have with projectE several months ago. but upon interacting with it, it's just a phantom copy due to the nullpointer and the bag meaning to take a copy of it then delete it. and so it disappears when I interact with it to my confusion.
I then proceeded to be completely dumbfounded for a few minutes when the drive i had placed down was empty and no longer had any cells after I checked it and the rendering updated as such resulting in all my items being lost to the hungry bag of holding gods. Then proceeded to test it out a bit more generating more console spam and more phantoms and re-emptied drives, then reset my world to a backup.

that was the only thing I know of so far that "dupes". but it's not really a dupe. it goes to pick up the original and fails so just gets a factory default version. but still deletes the original in the world returning no items as if it did pick it up, only realizing it did after you interact with it and make the phantom object remove itself due to time paradox. you then place it down, and you've got a factory default drive with nothing in it. :V

**Comment by PrinceOfAmber** [comment]
With error checking it looks like this.  It puts up a "sack.error.pickup" text which eventually will be a nice message like "error trying to pickup block, action cancelled to prevent data loss"

[GIF]
https://i.imgur.com/h6RoQY2.gifv

**Comment by Darkmega18** [comment]
absolutely brilliant. thats perfect. :)

**Comment by PrinceOfAmber** [comment]
Release is out with these changes https://minecraft.curseforge.com/projects/cyclic/files/2588760
