### ISSUE TITLE
Crash to Desktop when putting tools in crafting grid

### ISSUE THREAD

**Issue by psychofad** [PrinceOfAmber/Cyclic#88]
I have already posted this issue on Botania's Github, but for completeness I wanted you to also be aware of it so that you can make sure it is not something on your end as well. 

If I put any of the Emerald tools in a crafting window, the client crashes to desktop with the following error:

[http://pastebin.com/Bg5VYC5Z](http://pastebin.com/Bg5VYC5Z)

I have also seen this behavior in Mekanism Tools, and Router Reborn's RR Pickaxe.  Router Reborn's author was able to fix the issue on his end due to using an old itemstack method or something, however the Mekanism author does not believe it is on his end at this point which prompted me to make the issue on Botania's Github found here (which also has references to the Mekanism issue):

[https://github.com/williewillus/Botania/issues/471](https://github.com/williewillus/Botania/issues/471)

Maybe through some combined effort everyone involved can work out what is going wrong.

**Comment by PrinceOfAmber** [comment]
Pretty crazy. Repair material should just be an emerald; looking into it now.

**Comment by PrinceOfAmber** [comment]
Releasing 1.7.4 soon to fix this. no crash in any crafting window, and i can repair my tools in the anvil as well.  I had Botania-unofficial.r1.8-318 installed and a ton of other stuff.
