### ISSUE TITLE
Extended Inventory Crash - when Using Quark's Link item in chat feature (Shift-T) 

### ISSUE THREAD

**Issue by NillerMedDild** [PrinceOfAmber/Cyclic#882]
Minecraft version & Mod Version:
1.12.2
1.15.15

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Using Quark's Link item in chat feature (Shift-T) crashes the game.

Crash log (if any):
https://pastebin.com/WDTVenHw

Original issue:
https://github.com/NillerMedDild/Enigmatica2Expert/issues/160

**Comment by PrinceOfAmber** [comment]
Ill look into how quark does this. hopefully its an easy fix...., but if i cant get it fixed soon you might have to disable one or the other, or warn players about it.

**Comment by PrinceOfAmber** [comment]
Nevermind , easy fix

**Comment by NillerMedDild** [comment]
Sweet, thanks :)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2591567
