### ISSUE TITLE
Mystical agriculture fishing rod problem with cyclic fisher

### ISSUE THREAD

**Issue by violetkitty87** [PrinceOfAmber/Cyclic#883]
Minecraft version & Mod Version:
MC 1.12.2 Mod version 1.16.2

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I made a unbreakable fishing rod from mystical agriculture (the supremium one) and was able to put it in the fisher from cyclic but it does one round of fishing then deletes the rod. Being that this is an unbreakable rod it should not do that.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Hmm, yeah looks like its just taking -1 durability without checking if it has durability or not.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2591567

**Comment by violetkitty87** [comment]
im now in the new update of cyclic and it still does this
