### ISSUE TITLE
Excavation enchant breaks a lot more blocks than it should

### ISSUE THREAD

**Issue by Lykrast** [PrinceOfAmber/Cyclic#886]
Minecraft: 1.12.2
Cyclic: 1.16.5

The Excavation enchantment breaks a lot more blocks than it should according to the config. It is possible to harvest stacks of stone in a single block break with Excavation III, despite the config saying it should cap at 46.

This is likely caused by how the recursion is done, as [here](https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/enchant/EnchantExcavation.java#L118) the method doesn't have any information on how many block its "child" calls destroyed, meaning they produce a lot more calls than they should to correctly cap.

**Comment by PrinceOfAmber** [comment]
Fix is up https://minecraft.curseforge.com/projects/cyclic/files/2597632
