### ISSUE TITLE
Dry Peat Bog no longer converts into Saturated Peat Deposite

### ISSUE THREAD

**Issue by tommyTT** [PrinceOfAmber/Cyclic#888]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Forge: 14.23.4.2747
Cyclic: 1.16.6

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
I set up the peat farmer on an older version of the mod, everything worked fine. After updating to 1.16.6 the dry peat bog blocks no longer convert into saturated peat deposite blocks. 
I looked into the code and found that the block no longer ticks randomly (see [commit](https://github.com/PrinceOfAmber/Cyclic/commit/84f9acf98a6a86ed360bf435691eceec5e5485d1#diff-81266676c81b25a376ce109272a0c815L57)). I couldn't find another way, this conversion happens, so maybe this was accidentally changed?

**Comment by PrinceOfAmber** [comment]
Hmm.  I am still on Forge 14.23.1.2594, ill update and make sure this is fixed in next version

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2599607

**Comment by tommyTT** [comment]
Thank you for the fix. I was able to work around this bug by re-enabling the random ticks for the block through CraftTweaker, but good to now this is no longer needed with that update.
