### ISSUE TITLE
Harvester not working with Plants "crops".

### ISSUE THREAD

**Issue by Yamza** [PrinceOfAmber/Cyclic#896]
Minecraft version & Mod Version:
1.12.2
Cyclic-1.12.2-1.16.8
Modpack: ATM3 v6.0

Single player

Describe problem (what you were doing / what happened):
Trying to harvest Plants crops with the harvester, harvester ignores the crops. (night shade)
Should gather the crops produce.

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)
Might be a bit of both?
https://github.com/Shadows-of-Fire/Plants/issues/98

**Comment by PrinceOfAmber** [comment]
I will check it out.

Some of their plants are just plain plants... so Is NightShade the only crop or are there others i should look out for?

**Comment by Yamza** [comment]
The only other plant I tested was "Wine Raspberry Bush". I can test more if you'd like but it seems like you've got it sorted out. Thanks!

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2601662
