### ISSUE TITLE
Mod content Blacklist bug

### ISSUE THREAD

**Issue by pingvikin** [PrinceOfAmber/Cyclic#900]
**Minecraft version:** 1.12.2
**Mod Version:** 1.16.9

**Single player or Server:** Server

**Describe problem**:
I'm added to content black list the dynamite. But it is still available in the game.

**My config:** https://gist.github.com/pingvikin/e4e2fd195a4e5491124b3695da006507

**Comment by PrinceOfAmber** [comment]
Yeah some items got renamed, but the configs still list the old name.   To delete the main red dynamite set these to false

:EnderBombs=true

**Comment by PrinceOfAmber** [comment]
Ill update the comment so its easier to detect, it will in future update say 

        # Dynamite I-IV Set false to delete - requires restart [default: true]
:EnderBombs=true
