### ISSUE TITLE
Cross mod dupe bug (Oreberries + Cyclic Harvester)

### ISSUE THREAD

**Issue by SirLyle** [PrinceOfAmber/Cyclic#903]
Minecraft version & Mod Version:
MC 1.12.2, Cyclic 1.15.15, Oreberries 0.5.0

Single player or Server:
Tested on single, suspect on all.

Describe problem (what you were doing / what happened):
Trying to automate Oreberries (https://minecraft.curseforge.com/projects/oreberries) using the Cyclic Harvester.

Instead of providing the oreberries, the harvester waited for the bushes to fully grow, then produced and replanted the bushes—duping the bush. 

Expected behavior:
Harvester produce some oreberries and reset the bush's age to "2".

Looking at the source it appears you have some code to handle natura bushes which these behave similar to.

**Comment by PrinceOfAmber** [comment]
Ore berries would need to add some compatibility changes to make the block add more like a crop and work with harvester type machines.  (it needs to use getDrops and drop berries based on age )

However, this mod might be designed this way on purpose

Good news: Just use a cyclic automated user aimed at the ore berry and this works.

![user](https://user-images.githubusercontent.com/621529/46577664-b0070300-c9a0-11e8-9b0a-8444aaf18f2d.PNG)
