### ISSUE TITLE
JEI categories do not have a catalyst

### ISSUE THREAD

**Issue by Lykrast** [PrinceOfAmber/Cyclic#907]
**Minecraft version & Mod Version:** Cyclic-1.12.2-1.16.10

**Problem:**

The various JEI categories (Hydrator, Packager, Dehydrator) do not have their machine set as catalyst (the machine icon on the left as seen on image).

![image](https://user-images.githubusercontent.com/8684850/44516449-6c448c80-a6c5-11e8-9aa8-c28f999b5f52.png)

This means that finding usage for those machines does not show the appropriate category, and that when looking at those categories it is not easy to find the appropriate machine (and thus look at its recipe).

**Comment by PrinceOfAmber** [comment]
I hope i can find something bout this on the WIKI https://github.com/mezz/JustEnoughItems/wiki/Recipe-Categories

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2609136
