### ISSUE TITLE
Possible to suffocate in a Trash Void

### ISSUE THREAD

**Issue by Maxwell-lt** [PrinceOfAmber/Cyclic#908]
Minecraft version & Mod Version: Cyclic-1.12.2-1.16.10

Describe problem (what you were doing / what happened):

The hitbox of the Trash Void allows a player to walk into one placed at head height and take suffocation damage.

**Comment by PrinceOfAmber** [comment]
Yep. also happens to Item Sorter (in newer versions)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2609136
