### ISSUE TITLE
Garden Scythe Compatibility w/ Rustic Grapes

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#915]
Forge v14.23.4.2757-1.12.2
Rustic v1.0.8
Cyclic v1.17.1
Currently, the garden scythe harvests the grape stem instead of the grapes on the plant, as you can see in the pictures.
![2018-09-03_15 21 56](https://user-images.githubusercontent.com/12000593/45000870-f924fb00-af8d-11e8-91aa-4f38690ba41f.png)

![2018-09-03_15 22 28](https://user-images.githubusercontent.com/12000593/45000860-ed393900-af8d-11e8-8296-c0b739c01021.png)

**Comment by PrinceOfAmber** [comment]
Hey thanks for your patience. Looking into this now.  So it needs to ignore and skip over the  grape_stem blocks sand not harvest seeds from them.

and then grab the grapes from the smaller bushes

**Comment by WenXin20** [comment]
Thanks!

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
