### ISSUE TITLE
Wireless Transmitter Duplication (Possible mod-compat issue)

### ISSUE THREAD

**Issue by Quickslash78** [PrinceOfAmber/Cyclic#916]
Minecraft version & Mod Version: 

Minecraft 1.12.2, 
Forge-14.23.4.2759.
Cyclic 1.17.0

Single player or Server: Singleplayer

Describe problem (what you were doing / what happened):

Broke a wireless transmitter with Actually Additions drill, dropped two of itself. 
(Consistently repeatable, but was exclusive to the drill as far as I was able to test.)

Crash log (if any): N/A

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yeah, does not happen with a pickaxe which is very weird

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
