### ISSUE TITLE
LifeLeech Bugs

### ISSUE THREAD

**Issue by tyler489** [PrinceOfAmber/Cyclic#917]
Minecraft version & Mod Version:
1.12.2
1.17.0
Single player or Server:
Both 

Describe problem (what you were doing / what happened):
Adding LifeLeech to a sword stops mobs from droping any loot. Playing Enigmatica 2 expert mode. https://gyazo.com/4b63455aaac70983b3f96e1fa8c96ad6

**Comment by PrinceOfAmber** [comment]
That is a lot of enchantments.  Are you sure it is lifeleech?

I did a quick test while i was damaged, similar enchantments to you but without some of the modded ones.  I am healing on the killing blow at the same time as getting drops 👍 

https://i.imgur.com/zbwfvNA.gifv

**Comment by PrinceOfAmber** [comment]
For modpacks you can often just report to the pack issue tracker, sometimes it is a conflict between several mods, or sometimes it might be something done on purpose    .

If you report there you will probably get more help.  Also feel free to link this issue as well, and if theres anything I can do on my end we can just reopen the issue 



https://github.com/NillerMedDild/Enigmatica2/issues

**Comment by tyler489** [comment]
The issue did not occure when lifeleach was removed. Probably should have tested with just lifeleach..
