### ISSUE TITLE
no way to lookup hydrator recipes

### ISSUE THREAD

**Issue by IngmarBitter** [PrinceOfAmber/Cyclic#919]
Minecraft version & Mod Version:
MC 1.12.2 
Cyclic 1.17.1

Single player or Server:
Both

tested with https://www.technicpack.net/modpack/atlantica

Describe problem (what you were doing / what happened):
There seems to be no way to lookup hydrator recipes, even with JEI installed.
Similar out of game a google search for "cyclic hydrator recipes" also does not get anything useful.

Maybe have a list of recipes on this github so said search above will find it?
Or add it to the overview here: https://minecraft.curseforge.com/projects/cyclic

**Comment by PrinceOfAmber** [comment]
You can click on the title in the screen to show recipes.


They also show up in JEI at least when I try it they do: GIF below 

![hydrator recipes](https://user-images.githubusercontent.com/621529/45335096-95bd3f00-b532-11e8-85a7-2e0c5aec288b.gif)

**Comment by PrinceOfAmber** [comment]
Does the modpack have an issue tracker? It might be something they have with custom scripts or recipes?
