### ISSUE TITLE
FR - Apple Sprout right clickable

### ISSUE THREAD

**Issue by G3R0N1M079** [PrinceOfAmber/Cyclic#922]
Hi.
If is not OP, in your vision, can be apple growth by apple sprout harvestable by right click?

Thank You

**Comment by PrinceOfAmber** [comment]
This does make sense.

However, you can already perform with action either with the Garden Scythe item or the Harvester block

Also there are a few mods that add this right click feature to all crops, so me doing something custom would be a bit redundant.

Thanks for the post

**Comment by G3R0N1M079** [comment]
Hi PoA.
I know the action wit garden scythe.
I didnt check the harvester and i will do in the evening.
With third part right click mod doesn't function.

Nevermind. I will use the garden scythe.
thank you
enrico
