### ISSUE TITLE
BUG - Water Candle (breaking & light levels)

### ISSUE THREAD

**Issue by G3R0N1M079** [PrinceOfAmber/Cyclic#923]
Minecraft version & Mod Version:
MC ver 1.12.2
Cyclic 1.12.2-1.17.1

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Placing a Water candle. Breaking it with a pick axe.
Water Candle will be destroyed but not picked up. It disapear.

Crash log (if any):
not present, not looked at.

If you need other test information i can make it in the evening.

Thank You for your effort in this project.
Enrico

**Comment by G3R0N1M079** [comment]
Hiu PoA.
Thank You for the fix i will try with the next release.
About the candle function.

I try it and i saw that it spawn at hifh rate hostile mobs and passive mobs.
But it breaks any "spawn" rules.
For example in a chunk perfectly illuminated (no hostile mobs spawn normally) it permits to hostile mobs to spawn.

Is this intended?
Have a nice day.
Enrico

**Comment by PrinceOfAmber** [comment]
It should follow normal spawn rules, such as no pigmen in the overworld, no creepers in the end, ETC.

If everything is high light level in the overworld nothign should spawn i will check into this thank you

**Comment by G3R0N1M079** [comment]
Hi.
I made some tests, with the 1.17.2 version
Result:
Radius setting is ok and functions.
Light rules is compleatly broken. Hostile mobs spawn regardless the light level
Slab rules is broken. Hostile mobs spawn half block upper the slab below.
Seams that water candle permits to hostile mobs to spawn in the air one block above the une below

Water candle permit to hostile mobs to spawn in the air. If you put the water candle on a 4x4 platform  (skyblock for example with defaul radius 8 blocks) hostile mobs spawn in the air out of the platform inside the radius of the candle

Enrico

**Comment by PrinceOfAmber** [comment]
Thanks for your patience  this past while.
It does not spawn any passive mobs
it does work with darkness levels, at least for vanilla mobs. 
in a superflat world, i just dig a small 2 high area and place it down and things spawn, but nothing on the overworld in a different site

- for the slabs rule, yes i think its using Spawner block logic, which will spawn mobs evein in midair, and not using wilderness logic that looks for slabs. I will investigate but possibly not change it.

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
