### ISSUE TITLE
Crash with Life Leech

### ISSUE THREAD

**Issue by Lykrast** [PrinceOfAmber/Cyclic#924]
Minecraft version & Mod Version:

1.12.2-1.17.0

Single player or Server:

Server

Describe problem (what you were doing / what happened):

Had a sword with Life Leech and the damage reflect perk from Astral Sorcery. Got attacked by a Shadow Wraith from Electroblob's Wizardry and the server crashed.

Looks to be using a client side function on the server.

Crash log (if any):

https://gist.github.com/retep998/8b1c4a0b275f0aedb9b7b367f5c3a8ad

**Comment by PrinceOfAmber** [comment]
Looking into this

 Forge version - 14.23.3.2655



Other details

MC 1.13: net/minecraft/util/FoodStats.setFoodSaturationLevel
Name: b => func_75119_b => setFoodSaturationLevel
Descriptor: (F)V
Comment: None
Side: CLIENT
AT: public net.minecraft.util.FoodStats func_75119_b(F)V # setFoodSaturationLevel

**Comment by Hubry** [comment]
Um, in that crash report the Forge version very clearly was 1.12.2-14.23.4.2739...

**Comment by Hubry** [comment]
Also should probably note that this modpack is [Wikipack 3.2](https://minecraft.curseforge.com/projects/wikipack-3-2). If you ask on the FTB Wiki discord, I think we could try to reproduce it on the server again?

**Comment by Lykrast** [comment]
While this is not linked to the crash this is linked to the same enchant and is probably caused by the same thing.

On that same server, I have a sword with Life Leech and entities don't drop anything when killed with it. This appears in the logs : https://gist.github.com/retep998/10770e2b5d5adb8501a49cc3ab07235c

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
