### ISSUE TITLE
Charms with Horrible Vanilla Repair Costs.

### ISSUE THREAD

**Issue by KaneHart** [PrinceOfAmber/Cyclic#926]
Minecraft version & Mod Version:
1.12.2 / 1.17.1

Single player or Server:
SP

Using the Speed Charm for an example if you are to repair it in a normal anvil it will take 4 emerald blocks to repair it. I found the speed charm only last maybe 5 minutes. Then I went to repair it and it costs 4 emerald blocks emeralds would not work.

Clearly your mod offers powerful ways to repair but I feel like vanilla repair is a bit over the top as it costs 4 times more materials at least for the speed charm.

**Comment by KaneHart** [comment]
I just wanted to comment on this as a separate reply. Maybe consider tweaking the usage of the speed charm a bit. I feel like it gets used way to fast and does not make it feel worth it. Even later on if it's free repair the effort alone to turn it on and off almost does not outweigh the value.

**Comment by PrinceOfAmber** [comment]
Repairing in one of the anvils is much cheaper almost free. But yeah the anvil recipe is bad and the durability could be higher.  Or actually better if it jus drains slower.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2616415
