### ISSUE TITLE
Uncrafting Grinder + Automatic Torch = Infinite coal blocks

### ISSUE THREAD

**Issue by ChaoticLogic** [PrinceOfAmber/Cyclic#927]
**Minecraft version & Mod Version:** 
MC 1.12.2
Cyclic 1.16.9

**Single player or Server:**
Single player

**Describe problem (what you were doing / what happened):**
If you place an automatic torch into an uncrafting grinder, you will get 3 blocks of coal and another automatic torch. Infinite coal.

**Crash log (if any):**
No crash occurred.

**Comment by PrinceOfAmber** [comment]
yeah im just gonna remove these repair recipes.

You can refil with torches and just repair with anvils

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2616415
