### ISSUE TITLE
Extended inventory tool belt screen is empty on multiplayer servers

### ISSUE THREAD

**Issue by Hubry** [PrinceOfAmber/Cyclic#929]
Minecraft version & Mod Version: 1.12.2, 1.17.1, Forge 14.23.4.2739
Single player or Server: Dedicated server

Describe problem: Accidentally pressed R outside of inventory, saw that screen that was teased on reddit, except it was empty, despite my extended inventory being full of loot from my last adventure.

![tool belt screen, which is empty](https://user-images.githubusercontent.com/26120076/45358447-be444800-b5c9-11e8-9bc7-ca2405e10eb3.png)
![extended inventory, basically only one or two slots empty](https://user-images.githubusercontent.com/26120076/45358434-aff62c00-b5c9-11e8-8bac-026c089dbb07.png)

Note that clicking on a slot works as expected - it swaps the item in hand with the selected slot of extended inventory.

**Comment by PrinceOfAmber** [comment]
Yep its not rendering from a server good catch
