### ISSUE TITLE
[Bug] Bucket Storage drops when broken in creative

### ISSUE THREAD

**Issue by starg09** [PrinceOfAmber/Cyclic#93]
Not much to say, just a minor bug :P 

Happening as far as v1.7.5

**Comment by PrinceOfAmber** [comment]
Thanks for the report, doesnt matter how minor :)

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.6 https://minecraft.curseforge.com/projects/cyclic/files/2332155
