### ISSUE TITLE
Wrong enchantments coming up when searching in JEI

### ISSUE THREAD

**Issue by LumberWizard** [PrinceOfAmber/Cyclic#931]
Minecraft version & Mod Version:
Cyclic version 1.17.1 for Minecraft 1.12.2 with JEI 4.12.0.216

Single player or Server:
Server, assuming the same happens on a singleplayer world.

Describe problem (what you were doing / what happened):
I searched in JEI for "quickdraw" and an enchanted book with Venom 1 came up if I recall correctly. Most enchantments bring up the wrong book; a few bring up nothing or random items instead. This only occurs for enchantments added by Cyclic.

**Comment by Hubry** [comment]
It's on JEI, or rather, the way Minecraft stores enchantments not working well with JEI - see mezz/JustEnoughItems#1202.

**Comment by PrinceOfAmber** [comment]
Using forge=14.23.5.2768 and jei 4.13.1.220 .. yeah i see this happening.

'smelt' brings up life leech and 'water' brings up excavation book.

But it sounds like a bug on the other end? no idea

**Comment by PrinceOfAmber** [comment]
Yep looks like mezz from JEI recognized the bug exists but theres no short term fix so i guess thats the story
