### ISSUE TITLE
Build from Source: com.lothrazar.cyclicmagic.net.PacketSyncToolslot missing

### ISSUE THREAD

**Issue by dldummy** [PrinceOfAmber/Cyclic#932]
I tried to build your mod from GitHub sources but 'com.lothrazar.cyclicmagic.net.PacketSyncToolslot' (in every BRANCH) is missing.

Am i dumb or does i oversee somthing !?

**Comment by PrinceOfAmber** [comment]
oh sorry i forgot to commit that it was a last minute change to 17.2

**Comment by PrinceOfAmber** [comment]
Develop branch is up to date and working now
