### ISSUE TITLE
Incorrect language key

### ISSUE THREAD

**Issue by sandtechnology** [PrinceOfAmber/Cyclic#933]
Minecraft version & Mod Version:
Minecraft 1.12.2 and Cyclic 1.17.2

Single player or Server:
both

Describe problem (what you were doing / what happened):
The language key "item.storage_bag.pickup" should be "item.storage_bag.togglepickup"

Crash log (if any):
None

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
