### ISSUE TITLE
Block Placer convert block wood type (Primal Core Yew to PrimalCore IronWood)

### ISSUE THREAD

**Issue by Fireztonez** [PrinceOfAmber/Cyclic#936]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Cyclic: 1.16.10
Forge: 14.23.4.2760

Single player or Server: Single Player

Describe problem (what you were doing / what happened):
The bug happen during my live, so I record a clip for you... Like you can see in the clip, I place PrimalCore Yew Log into the block placer and it place IronWood from the same mod (IronWood = primal:logs:0 and Yew is primal:logs:1). So I imagine the bug came from a problem with your Meta Data handler...

I can report that to PrimalCore too if needed...
https://clips.twitch.tv/AntsyDarlingVultureAllenHuhu
and a second test: https://clips.twitch.tv/DistinctKnottyMonkeyImGlitch

I look the meta-data when placed it should be exactly the same as Oak and Spruce, but when you palce spruce it really place spruce and not oak, so I don't really understand why...

Fireztonez

**Comment by PrinceOfAmber** [comment]
It really does seem somehow it is only primal wood, but not wood with metadata from other mods . doesnt make much sense

**Comment by Fireztonez** [comment]
I have completly forget to look back this issue before!

Thank's for having fix the issue, I will try again with the new version and let you know.

Fireztonez

**Comment by PrinceOfAmber** [comment]
Yeah took me a minute but i came back to it :D https://minecraft.curseforge.com/projects/cyclic/files/2633018
