### ISSUE TITLE
[Bug] Sack of Holding breaks some machines when moved

### ISSUE THREAD

**Issue by starg09** [PrinceOfAmber/Cyclic#94]
Example found is Ender IO's Buffers, but there may be more.

* Item Buffer loses it's internal inventory: https://gfycat.com/AdorableMammothCentipede

* Energy and Omni Buffers turn into Item Buffers, with the same issue: https://gfycat.com/KlutzyWeeklyHyena

Versions used:

* Cyclic v1.7.5

* Ender IO 1.10.2-3.0.1.107

**Comment by PrinceOfAmber** [comment]
Yeah, mod compatibility is always hard.  What the bag does basically is try and copy the inventory data,  and copy the block id, and try to replicate that.  Ill have to try to copy the entire block of data stored in the tile entity and replace that again.  

As usual with mod compatibility issues, cant promise anything but ill try.

**Comment by PrinceOfAmber** [comment]
7 Items affected: all three scythes, the piston tool, the three detectors (spawn, spelunker, prospector)

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.6 https://minecraft.curseforge.com/projects/cyclic/files/2332155
