### ISSUE TITLE
Crash on interaction between Thaumcraft Everfull Urn and Bundled Cable

### ISSUE THREAD

**Issue by DSquirrelGM** [PrinceOfAmber/Cyclic#943]
Minecraft version & Mod Version:
1.12.2 / 1.17.2

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Placing Thaumcraft Everfull Urns near bundled cable causes server crash - appears to be trying to fill the cable and the cyclic check for targets causes crash.

Crash log (if any):
[https://gist.github.com/607993b7e5ae1f31ab97fa69696d8e1c](https://gist.github.com/607993b7e5ae1f31ab97fa69696d8e1c)

**Comment by PrinceOfAmber** [comment]
I checked out latest thaumcraft and it worked for me, the water arced up and out and into the cable.

But from the log i see exactly where a crash can come from in some cases. which makes it easy fix

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
