### ISSUE TITLE
Dupe bug with Butterfingers

### ISSUE THREAD

**Issue by Sunekaer** [PrinceOfAmber/Cyclic#944]
Minecraft version & Mod Version:
1.12.2-14.23.4.2765
Cyclic-.1.12.2-1.17.2

Single player or Server:
only tested in single player

Describe the problem (what you were doing / what happened):
you take the butterfingers potion, clear out your hot bar place, the one item of any kinda in your hot bar use potion of butterfingers walk or run around while pressing either 1 and 2 on the keyboard or use the scroll mouse!!

**Comment by xILikepuddingx** [comment]
https://files.ilikepudding.de/n51sw4w9ni.mp4 Server too

**Comment by PrinceOfAmber** [comment]
If you are able can you test this pre alpha fix version on your servers  ?  @xILikepuddingx  @Sunekaer   I think i have it fixed but i only tested here.

 jar file is on this link  https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.17.3-testpotion

**Comment by Sunekaer** [comment]
i have tested in single player, currently dont have an test server up

**Comment by xILikepuddingx** [comment]
If @sunekaer Update the stoneblock Pack with ur fix i can Test. We cant Test without it because many twitch Launcher User cant join anymore the pack

**Comment by xILikepuddingx** [comment]
Tomorrow the update will come on our servers. I will contact you again.

**Comment by PrinceOfAmber** [comment]
Thanks . i was just trying to do a sneak early peak to test, release is out now.  report back for any new issues.

1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191
