### ISSUE TITLE
Ender Sack can be placed inside itself

### ISSUE THREAD

**Issue by dmsaxon** [PrinceOfAmber/Cyclic#946]
Minecraft version & Mod Version:
1.12.2 (Playing Enigmatica 2 : Expert Edition - non-Skyblock)
Cyclic 1.17.2

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
When opening the Ender Sack, you're able to place the item inside itself.  Aside from the dimension twisting issues that this can cause, it also means I have to craft another in order to recover the contents (certainly not easy on E2:EE!)

I guess I'd expect not to be possible to pick up the sack from my inventory when the sack GUI is open.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yep, its just an ender chest , so it follows all the same rules and logic of an ender chest .  If you lose the bag you can go do any already-placed chest and get it back there, the inventory is linked

**Comment by dmsaxon** [comment]
Ah, okay - I understand.  I wasn't sure if the ability to put it inside itself should be blocked.  Thanks for clarifying!
