### ISSUE TITLE
 [Automated User] Isolated Fluid Dupe #797 {re-open for newer version}

### ISSUE THREAD

**Issue by Demlou6** [PrinceOfAmber/Cyclic#949]
Minecraft version & Mod Version:
1.12.2 & 1.17.2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Started with one bucket and now:
https://gyazo.com/fecac48b39783b64f94771587d724b18

Adding the original issue:

https://github.com/PrinceOfAmber/Cyclic/issues/797

**Comment by PrinceOfAmber** [comment]
Thanks for the updated information !

**Comment by PrinceOfAmber** [comment]
WHat tank were you using it on? I made a recording with https://www.screentogif.com/  and i cant get it to break  
![fluid rep](https://user-images.githubusercontent.com/621529/46901304-cc55e480-ce65-11e8-8d16-98df0d09f9f6.gif)

**Comment by Demlou6** [comment]
Cobblestone cauldron, from More Cauldrons with Inspiration support.

**Comment by Mrbysco** [comment]
When Inspirations is installed I simply extend their Cauldron block. I've done some testing and the issue lies on Inspirations part.

https://imgur.com/a/Svh2fke

As it seems to happen to the vanilla cauldron as well [Which Inspirations replaces with theirs].

**Comment by PrinceOfAmber** [comment]
Trying to investigate which mods it does or does not happen with

**Comment by PrinceOfAmber** [comment]
Found the issue.  

Same exact test as above, this time with Inspirations installed and config set to true where cauldron holds 4 bottles not 3:
      # Makes the cauldron hold 4 bottle per bucket instead of 3. Translates better to modded fluids. [default: false]
        B:bigger=true

Also it does not happen the first time when I drop in the leftmost slot.  However when I place in the far right slot, it slides over and dupes.  

Its very likely that other mods such as inspirations have nothing to do with it, unsure at this point  

![found it](https://user-images.githubusercontent.com/621529/47633455-354a8700-db0b-11e8-96c8-96649b27bd65.gif)

**Comment by PrinceOfAmber** [comment]
Nevermind, false alarm.  When i try this out the "dupe" is just a fake ghost item its not really there, the client is out of sync for a second .  

Seems like everything is fine in Cyclic 1.17.5+ , can you confirm? or do you  get a real dupe 

![fake item](https://user-images.githubusercontent.com/621529/47633701-20babe80-db0c-11e8-93ad-acc1ba724118.gif)

**Comment by Mrbysco** [comment]
![afbeelding](https://user-images.githubusercontent.com/9308260/47658390-36bf9200-db93-11e8-865e-e54123ca9c11.png)
![afbeelding](https://user-images.githubusercontent.com/9308260/47658492-62427c80-db93-11e8-8fe5-652f8246132f.png)
![afbeelding](https://user-images.githubusercontent.com/9308260/47658520-6cfd1180-db93-11e8-8d18-b271b7d9429c.png)
![afbeelding](https://user-images.githubusercontent.com/9308260/47658536-71c1c580-db93-11e8-9543-6319c2ac9063.png)
![afbeelding](https://user-images.githubusercontent.com/9308260/47658555-7ab29700-db93-11e8-9919-bc780917ac68.png)
![afbeelding](https://user-images.githubusercontent.com/9308260/47658569-7edeb480-db93-11e8-95a7-09b464b149c9.png)

Using latest Cyclic with Inspirations. (Config set to 3 bottles per cauldron aka default)

**Comment by PrinceOfAmber** [comment]
Yep, this dupe does occur when Inspirations is installed. - wuth  Empty bucket + empty cauldron as you noted 

It does not dupe when inspirations is not installed .

**Comment by PrinceOfAmber** [comment]
So, ignoring inspirations there were 4 test cases fixed after refactoring
- normal use (bonemeal on grass or whatever, not much changed here)
- fluid tank
- cauldron
- fluids in the world

1.17.7 will have these changes . and of course a modpack can always blacklist cauldrons in the config if needed 
![444444444444444](https://user-images.githubusercontent.com/621529/47771329-12051080-dca0-11e8-9a6d-85151b624ef0.png)
