### ISSUE TITLE
Holding Problems

### ISSUE THREAD

**Issue by jules552** [PrinceOfAmber/Cyclic#95]
Hi,

I don't know if you know but some objects having the ancient holding system. Can you fix that please ? ;) 
If you don't understand me there is 2 pictures with the news holding system and the problem of your mod items ;) 

Normal : http://i.imgur.com/QIhRqfu.png

Your items : http://i.imgur.com/OjaSJKP.png

Thank you for your work and have a nice day :)

**Comment by PrinceOfAmber** [comment]
I see what you mean, how its flipped the wrong way, i can see it in f5 mode as well.

I will see what i can do.

**Comment by PrinceOfAmber** [comment]
Fixed in 1.7.6 https://minecraft.curseforge.com/projects/cyclic/files/2332155
