### ISSUE TITLE
Extra Inventory sometimes doesn't allow shift-clicking items

### ISSUE THREAD

**Issue by neoc666** [PrinceOfAmber/Cyclic#954]
Minecraft version & Mod Version: StoneBlock 1.0.20, MC 1.12.2, Cyclic-1.12.2-1.17.3

Single player or Server: Single player

Description:

Shift-clicking items from main inventory into (cookie-) extended inventory ("I") sometimes doesn't work. When this happens I can't shift-click more items. Also the other way around (extended inventory -> main). Can't give any instructions to reproduce.

Seems to happen only with the Cyclic extra inventory, so I suppose Cyclic is responsible, not the pack or any other mod in the pack.

**Comment by PrinceOfAmber** [comment]
When my bottom right slot is the only one empty, then the shift click is blocked for me. i cant shift click into the inventory from mine

I think other slots seem okay

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2629096
