### ISSUE TITLE
[Question] Air Charm - can't be repaired in anvil?

### ISSUE THREAD

**Issue by neoc666** [PrinceOfAmber/Cyclic#956]
Minecraft version & Mod Version: StoneBlock 1.0.20, MC 1.12.2, Cyclic-1.12.2-1.17.3

Single player or Server: Single player

Description:

I played StoneBlock with Cyclic a few weeks ago and I'm pretty sure Air Charm could be repaired in an anvil, with bone blocks. Doesn't work now. Am I mistaken here? Can charms be repaired in an anvil, and is the upper right item in the charm recipe the item you need to repair it?

**Comment by PrinceOfAmber** [comment]
In the mod by itself as it is now they do not get repaired in the regular anvil.  (maybe some other modpack added bone blocks to repair, not sure.)

You can recharge it in things that refill durability such as powered Anvil
