### ISSUE TITLE
Beacon night vision flicker

### ISSUE THREAD

**Issue by mrtomwolf** [PrinceOfAmber/Cyclic#957]
Suggestion:
Remove the flicker of night vision applied by the beacon that is due to it constantly being below 10 sec left.

**Comment by PrinceOfAmber** [comment]
Yeah good idea. Pharos beacon only gave 8 sec to copy regular beacon, ill set it to 20

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2631841
