### ISSUE TITLE
[Bug/Suggestion] Auto Crafter doesn't automatically stop when full

### ISSUE THREAD

**Issue by Gamertech** [PrinceOfAmber/Cyclic#959]
Minecraft version & Mod Version:
MC: 1.12.2
Cyclic: 1.17.4

Single player or Server:
Both

The Cyclic Auto Crafter continues crafting when the output is full and drops the excess output onto the ground.

Ideally, it would automatically stop crafting when full and resume when there's room for the craft to continue.

**Comment by PrinceOfAmber** [comment]
Yes i am slowly phasing out the old "drop on ground" mechanic since its bad and dumb so thanks for finding this

**Comment by PrinceOfAmber** [comment]
I think i have it in a good state 
![stopfull](https://user-images.githubusercontent.com/621529/47534711-437b7780-d86d-11e8-8cad-f7c60bbd5cba.gif)

**Comment by Gamertech** [comment]
Working as intended in 1.17.5. Thanks mate :)
