### ISSUE TITLE
Console Message On Every Shift-Click

### ISSUE THREAD

**Issue by Adorabus** [PrinceOfAmber/Cyclic#962]
https://github.com/PrinceOfAmber/Cyclic/blob/b4c823b44701c839b444e01d8535d821b8918258/src/main/java/com/lothrazar/cyclicmagic/playerupgrade/storage/ContainerPlayerExtended.java#L144

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2631841
