### ISSUE TITLE
Power drain when looking in UI of

### ISSUE THREAD

**Issue by RobertH332** [PrinceOfAmber/Cyclic#973]
Minecraft version & Mod Version: MC: 1.12.2 Mod: 1.12.2-1.17.7

Single player or Server: Single player

Describe problem (what you were doing / what happened): I have a harvester hooked up to Thermal Expansion Leadstone Conduits and when you are in the GUI the power seams to drop to 0. When you leave the GUI it instantly fills back up.

**Comment by PrinceOfAmber** [comment]
Yep i have it tracked down. (same thing in single player and server).   Machines were draining power  on both client and server but kind of in parallel.

thermal cables were (correctly) only transfering energy server side, and letting client update naturally.  Fix will first to make my cables and machines only calculate server side (like all other mods) and then make sure its clean when gui is open. Before and after GIF using that one proble (below):

**Comment by PrinceOfAmber** [comment]
Before the fix, showing bug (note the top left has correct power since its getting input and output at the same time)
![oops before](https://user-images.githubusercontent.com/621529/48982372-67adbc80-f096-11e8-8121-c63169980a3c.gif)

**Comment by PrinceOfAmber** [comment]
the difference after fix 
![after 973](https://user-images.githubusercontent.com/621529/48982384-8449f480-f096-11e8-9de0-7099f7ee4e67.gif)

**Comment by PrinceOfAmber** [comment]
Also probably related https://github.com/PrinceOfAmber/Cyclic/issues/939

**Comment by PrinceOfAmber** [comment]
Let me know if something else comes up https://minecraft.curseforge.com/projects/cyclic/files/2641400
