### ISSUE TITLE
Controlled Miner 1x1 option missing

### ISSUE THREAD

**Issue by Psithief** [PrinceOfAmber/Cyclic#978]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.17.2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Recent versions have removed the ability to choose 1x1 via the Controlled Miner GUI.
Miners with the NBT tag of `size` set to `0` still mine 1x1 as expected.
I don't mind if the default is 3x3, but it would be nice to still have the 1x1 option.

**Comment by SirMoogle** [comment]
Why not just use the Block Breaker?

**Comment by SirMoogle** [comment]
@Psithief There is another block in the mod called Block Miner that breaks the block in front of it.

**Comment by Psithief** [comment]
It was disabled in my modpack, but after enabling it, it's still not fit for purpose.
It doesn't allow providing a (fortune enchanted) tool to break the block.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
