### ISSUE TITLE
Simple Corn Mod Compatibility

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#979]
Minecraft version & Mod Version:
MC v1.12.2
Forge v14.23.5.2772
Cyclic v1.17.7
Simple Corn v2.4.1

Describe problem (what you were doing / what happened):
Using the Garden Scythe leaves behind floating corn plants.
![2018-11-14_23 01 11](https://user-images.githubusercontent.com/12000593/48531588-6a244100-e862-11e8-98a3-3e65b04a7031.png)

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
