### ISSUE TITLE
Can't disable GPS Marker

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#984]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
There's no config option to disable the GPS Marker item.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
