### ISSUE TITLE
Throwing Torch voided if it misses

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#987]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
When you throw ~~the Enhanced Shears or~~ the Throwing Torch, and they don't hit a suitable target, they're voided instead of being dropped as an item. This is a regression, as it used to work back in Cyclic 1.7.12. Specifically, it was the texture changes in commit 990458f that broke them (the relevant lines were commented out and never restored).

~~This will also be a problem for the Alluring Fishhook if ddf216b is ever reverted.~~

Never mind about the Enhanced Shears or the Alluring Fishhook; I see they use durability now instead.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
