### ISSUE TITLE
Torch Launcher projectiles invisible without Throwing Torch

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#988]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
If the Throwing Torch is disabled in the config, then the torch projectiles that the Torch Launcher shoots will be invisible. The effect of using it will be that nothing seems to happen for a few seconds, then a torch suddenly appears wherever the invisible projectile landed.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
