### ISSUE TITLE
Null names in config file

### ISSUE THREAD

**Issue by josephcsible** [PrinceOfAmber/Cyclic#991]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Some entries in the config file have `null` where the machine name is supposed to be:
```
    fuelcost {
        # Fuel/Energy/RF cost to run machine [range: 0 ~ 500000, default: 99]
        I:null=1

        # Lava cost per damage unit [range: 1 ~ 10000, default: 100]
        I:null_lava=100

        # Experience fluid cost per damage unit [range: 1 ~ 1000, default: 100]
        I:null_xpjuice=100
    }

    time {
        # Number of ticks needed to perform one action by this machine [range: 1 ~ 9000, default: 80]
        I:null=35
    }
```

**Comment by PrinceOfAmber** [comment]
This is a pretty critical bug since many packs may rely on these configs. rushing out a quick release to address this before looking at other issues in the release after that

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
