### ISSUE TITLE
Bow's enchantments issue

### ISSUE THREAD

**Issue by mcBegins2Snow** [PrinceOfAmber/Cyclic#997]
Minecraft version & Mod Version:
1.17.8

Single player or Server:
Single player

Describe problem (what you were doing / what happened):

- Quickdraw
- The quickdraw effect cannot be used to the bow in left hand.
- Multi-Shot
- The extra arrows always have the largest strength, whether the bow is full or not.

**Comment by PrinceOfAmber** [comment]
Good catch, i didnt test with left hand.  

The extra arrow strength is weird i didnt expect that

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2641400
